### DISCUSSION TITLE
cron trigger

### DISCUSSION THREAD

**Discussion by ansonauhk** [kedacore/keda#1045] [Q&A / Need Help] [answered]
Hi,

I don't understand what exactly start , end mean here? Normally a Linux cron job only has one interval per job, but we have 2 in keda , start and end.

So in the given example, does it mean every 30 min it scale to 30 replica, and every 45 min it scale to 0 replica?

https://keda.sh/docs/1.5/scalers/cron/

Thanks,
Anson

**Comment by zroubalik** [comment]
Hi, yeah, it should be like that.

@ckuduvalli could elaborate more, if you need to :)

**Comment by ckuduvalli** [comment, marked as answer]
@ansonauhk You are correct as @zroubalik said. Basically, we would want the scaler to be active only during a particular time frame (start to end). Once that timeframe passes, the scaler should become inactive and HPA should scale down to the minReplicaCount if specified, otherwise scale down to zero.

**Comment by bretagne-peiqi** [comment]
If we configure multiple triggers, which contains cron scaler,  how keda work if cron scaler and a metrics type scaler both meet the condition ?

**Reply by tomislater** [reply]
Good question! I did not find an answer for that. I think I just need to implement it on my side and test it.

**Reply by tomislater** [reply]
I tested it on my cluster and looks that with these settings:
```yaml
spec:
  ...
  maxReplicaCount: 5
  minReplicaCount: 1
  triggers:
    - metadata:
        value: '100'
      metricType: Utilization
      type: cpu
    - metadata:
        desiredReplicas: '2'
        end: 0 9 * * *
        start: 0 8 * * *
        timezone: Europe/Warsaw
      type: cron
```

By default there would be `one` replica. But during 8:00am-9:00am baseline would be `2` replicas. But if you have different triggers (like `cpu` in my case) they will work as usual in this 8-9 period. So if there is a high demand for CPU, k8s will add more pods.
