### DISCUSSION TITLE
Keda - Scaling based on Azure Service bus message along with pod identity

### DISCUSSION THREAD

**Discussion by sai25590** [kedacore/keda#1116] [General] [answered]
I followed the instructions here to setup a autoscaling of pods based on number of messages in the service bus queue. I also set the pod binding in KEDA deployment so that authentication occurs via managed identity. But I get the following error in the keda operator pod:

**kubectl logs keda-operator-5b7b47c48f-khq8w --namespace keda -f**
`{"level":"error","ts":1599627991.2951298,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"scaledobject-controller","request":"default/autofab-autoscale-scaledobject","error":"error getting scaler for trigger #0: error parsing azure service bus metadata: No subscription name provided with topic name","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/zroubali/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/zroubali/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/zroubali/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/Users/zroubali/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/zroubali/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/zroubali/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/zroubali/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88"}
`
My important configuration:
Install KEDA operator and bind the aadpodidbinding :
```
# Install keda autoscaler using helm
helm repo add kedacore https://kedacore.github.io/charts
helm repo update
kubectl create namespace keda
helm upgrade --install keda kedacore/keda --namespace keda --set aadPodIdentity=azureresourceaccess
```

**Deployment:**
---
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autofab-autoscale-deployment
  labels:
    app: autofab-autoscale
    aadpodidbinding: azureresourceaccess
spec:
  template:
    metadata:
      name: autofab-autoscale
      labels:
        app: autofab-autoscale
        aadpodidbinding: azureresourceaccess
    spec:
      containers:
        - name: autofab-autoscale
          image: ${acrlogin}/${autofabautoscaleimage}:${version}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1000m
          volumeMounts:
            - mountPath: /mnt/azure
              name: volume
          env:
            - name: SERVICEBUS_NAMESPACE
              value: ${sbnamespace}
            - name: AUTOSCALE_QUEUE_NAME
              value: "autofab-autoscaleq"
      restartPolicy: Always
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefile
  selector:
    matchLabels:
      app: autofab-autoscale

```

**ScaledObject:**
```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
namespace: default # must be same namespace as the Triggerauth
metadata:
  name: autofab-autoscale-scaledobject
spec:
  scaleTargetRef:
    deploymentName: autofab-autoscale-deployment # must be in the same namespace as the ScaledObject
  pollingInterval: 30  # Optional. Default: 30 seconds
  #cooldownPeriod:  300 # Optional. Default: 300 seconds. Matters only on scaling to 0
  minReplicaCount: 3   # Optional. Default: 0
  maxReplicaCount: 100 # Optional. Default: 100
  triggers:
  - type: azure-servicebus
    metadata:
      # Required: queueName OR topicName and subscriptionName
      queueName: autofab-autoscaleq
      subscriptionName: ${subscriptionname}
      queueLength: "1" # Optional. Subscription length target for HPA. Default: 5 messages
    authenticationRef:
      name: autoscale-servicebus-triggerauth
```

**TriggerAuthentication:**
```
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: autoscale-servicebus-triggerauth
  namespace: default # must be same namespace as the ScaledObject
spec:
  podIdentity:
      provider: azure # Optional. Default: none
```

**Comment by tomkerkhove** [comment, marked as answer]
The problem lies in your trigger definition:
```
- type: azure-servicebus
    metadata:
      # Required: queueName OR topicName and subscriptionName
      queueName: autofab-autoscaleq
      subscriptionName: ${subscriptionname}
      queueLength: "1" # Optional. Subscription length target for HPA. Default: 5 messages
```

You are using a queue, but yet still provide the `subscriptionName` which is used for topics. Given that one is specified, we block because the name of the topic is not there.

**Reply by sai25590** [reply]
Given a queue name, how do you know the subscription? the fix is to remove the subscription and queue name alone uniquely identifies the resource?

**Reply by sai25590** [reply]
I created a new MI and tried again (without subscription name). This time I get this:
{"level":"error","ts":1599632419.968029,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"scaledobject-controller","request":"default/autofab-autoscale-scaledobject","error":"error getting scaler for trigger #0: error parsing azure service bus metadata: namespace is required when using pod identity"

**Reply by tomkerkhove** [reply]
>  Given a queue name, how do you know the subscription? the fix is to remove the subscription and queue name alone uniquely identifies the resource?

Yes, that's correct!

> I created a new MI and tried again (without subscription name). This time I get this:
> {"level":"error","ts":1599632419.968029,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"scaledobject-controller","request":"default/autofab-autoscale-scaledobject","error":"error getting scaler for trigger #0: error parsing azure service bus metadata: namespace is required when using pod identity"

It looks like we have an undocumented `namespace` configuration value you'll have to add ([source](https://github.com/kedacore/keda/blob/master/pkg/scalers/azure_servicebus_scaler.go#L118)). Will fix the docs for this, sorry!

**Reply by sai25590** [reply]
Where should I add the namespace? To the KEDA operator (via --set namespace=keda) or aad-pod-binding.yml (adding an entry to metadata below) ?

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: aadpod-identity
spec:
  type: 0
  resourceID: ${msiresourceidkeda}
  clientID: ${msiclientidkeda}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: aadpod-identity-binding
spec:
  azureIdentity: aadpod-identity
  selector: sbaccesskeda
```

or somewhere here?
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: autoscale-servicebus-triggerauth
  namespace: default # must be same namespace as the ScaledObject
spec:
  podIdentity:
      provider: azure # Optional. Default: none

**Reply by tomkerkhove** [reply]
To your trigger metadata:

```yaml
- type: azure-servicebus
    metadata:
      # Required: queueName OR topicName and subscriptionName
      queueName: autofab-autoscaleq
      namespace: your-service-bus-namespace
      queueLength: "1" # Optional. Subscription length target for HPA. Default: 5 messages
```

Feel free to let me know if it works.
