### DISCUSSION TITLE
prometheus trigger type

### DISCUSSION THREAD

**Discussion by jeffgriffith** [kedacore/keda#1203] [Q&A / Need Help] [answered]
Question about the prometheus trigger type. The examples queries show using a sum and indeed the HPA thresholding seems to indicate an (avg). The metric result gets divided by the number of pods automatically then. This seems to map to the HPA target types of Value vs AverageValue. Is there a way to tell KEDA to use a raw metric value against the threshold rather than having it do an avg of the sum based on # of pods?  Thanks!

```
triggers:
- type: prometheus
  metadata:
    # Required
    serverAddress: http://<prometheus-host>:9090
    metricName: http_requests_total
    threshold: '100'
    query: sum(rate(http_requests_total{deployment="my-deployment"}[2m])) # Note: query must return a vector/scalar single element response
```
