### DISCUSSION TITLE
Scale down if threshold is greater than some value

### DISCUSSION THREAD

**Discussion by lambohamp** [kedacore/keda#1333] [Q&A / Need Help] [answered]
Hello. I would like to use KEDA for scaling down my applications if the number of messages in a RabbitMQ queue is greater than some value. For instance, I have a producer application and I want to turn it off when a queue size is more than 1000 messages. I've checked out the documentation but failed to find the answer. 
Could you suggest if it is possible? Thank you.

**Comment by zroubalik** [comment, marked as answer]
Hi, we don't support this kind of scenario, it is interesting though.

**Reply by lambohamp** [reply]
I see, thanks. If you are interested, I am using the following workaround which seems to work fine:

```
...
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-operated.monitoring.svc:9090
      metricName: rabbitmq_queue_messages
      threshold: '1000'
      query: '1000 - sum(rabbitmq_queue_messages)'
...
```

So when there are 1000 messages in a queue, the `target` is 0/1k and the producer pod gets scaled down.
Anyway, it would be cool to have a built-in option to do that through `ScaledObject`.
