### DISCUSSION TITLE
SQS Scaler

### DISCUSSION THREAD

**Discussion by brunozrk** [kedacore/keda#1364] [Q&A / Need Help]
Trying to scale pod with SQS scaler, but the HPA is not working, any tip to troubleshoot? Probably it is not a Keda issue, but I dont know where to call on

The event:
```
unable to get external metric default/AWS-SQS-Queue-keda-queue-1/&LabelSelector{MatchLabels:map[string]string{scaledObjectName: aws-sqs-queue-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: 
unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get AWS-SQS-Queue-keda-queue-1.external.metrics.k8s.io)
````

```
# kubectl version                                           
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0",...
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.1400",...
```

config files:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'tail -f /dev/null']
---
apiVersion: v1
kind: Secret
metadata:
  name: keda-secrets
data:
  AWS_ACCESS_KEY_ID: <SECRET>
  AWS_SECRET_ACCESS_KEY: <SECRET>
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID
    name: keda-secrets
    key: AWS_ACCESS_KEY_ID
  - parameter: awsSecretAccessKey
    name: keda-secrets
    key: AWS_SECRET_ACCESS_KEY
---
  apiVersion: keda.sh/v1alpha1
  kind: ScaledObject
  metadata:
    name: aws-sqs-queue-scaledobject
    namespace: default
  spec:
    scaleTargetRef:
      name: busybox
    minReplicaCount: 1
    maxReplicaCount: 5
    pollingInterval: 5
    triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-trigger-auth-aws-credentials
      metadata:
        queueURL: my_queue_url
        queueLength: "5"
        awsRegion: "us-east-1"
```
