### DISCUSSION TITLE
ScaledJob and scalingStrategy

### DISCUSSION THREAD

**Discussion by bobko69** [kedacore/keda#1435] [General]
im using a scaledjob to launch a rabbitmq consumer for every message added to the queue.  the job is long running (some times for hours).  the consumer does not ack the massage till the job is complete.  no matter how many messages are in the queue, only 1 consumer is run at a time.  i need a consumer to run for every message in the queue.

i think the secret to get this working is to add a scalingstrategy but i keep getting an error when i try to apply it:  'unknown field "scalingStrategy" in sh.keda.v1alpha1.ScaledJob.spec'.  im using keda 2.0 installed with the helm instructions.   what am i over looking?

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: worker-keda
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: worker
      spec:
        containers:
        - name: worker
          image: <image name and tag go hear>
    backoffLimit: 4
  pollingInterval: 20
  maxReplicaCount: 30
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  scalingStrategy: "custom"
  customScalingQueueLengthDeduction: 1
  customScalingRunningJobPercentage: "0.5"
  scalingStrategy:
    strategy: "custom"
    customScalingQueueLengthDeduction: 1
    customScalingRunningJobPercentage: "0.5"
  triggers:
  - type: rabbitmq
    metadata:
      queueName: work_que
      hostFromEnv: RabbitMqHost
      queueLength: '5'
```
