### DISCUSSION TITLE
Does it can send a notification when scale

### DISCUSSION THREAD

**Discussion by helloworlde** [kedacore/keda#1443] [Ideas]
We want to send a notification to user when triggered scale. Like `Deployment 'demo' scale up to 5 instances because of 'CPU' metrics exceed threshold `  
And the webhook configuration like 

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
spec:
  webhook: http://xxxx/webhook
  triggers:
```
