### DISCUSSION TITLE
My Kafka Consumer and producer are in same deployment but it keep scale up and scale down again and again

### DISCUSSION THREAD

**Discussion by abhi-dwivedi** [kedacore/keda#1481] [Q&A / Need Help]
HI Team

after deploy the Keda 1.5 because my k8s version is 1.15 and then I deploy the ScaledObject below is the configuration:

```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  labels:
    deploymentName: kafka-consumer # Required Name of the deployment we want to scale.
spec:
  scaleTargetRef:
    deploymentName: kafka-consumer # Required Name of the deployment we want to scale.
  pollingInterval: 5
  cooldownPeriod:  30
  minReplicaCount: 2   #Optional Default 0
  maxReplicaCount: 10  #Optional Default 100
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: xyz:9092,abc:9092
      consumerGroup: kafka-consumer #ake sure that this consumer group name is the same one as the one that is consuming topics
      topic: kafka-consumer
      lagThreshold: "4" # Optional. How much the stream is lagging on the current consumer group
```
    
and then my deployment automatically keep doing scale up and scale down again nd again. Could you tell me why its doing of there is no work on worker
