### DISCUSSION TITLE
Can Keda scale down when a Kafka topic has events but the lag is low?

### DISCUSSION THREAD

**Discussion by hector-meza** [kedacore/keda#1490] [Q&A / Need Help]
Hello.

I'm relatively new to Kubernetes and new to Keda so I'd like to make sure if what I'm seeing is the way it's supposed to work or maybe I'm missing something.

I installed Keda 2.0.0 via yaml files on a minikube local installation.

I have a very simple kafka consumer that reads a message and then sleeps for two seconds to simulate heavy work. I then created a ScaledObject for that deployment with this YAML

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-demo-scaledobject
  namespace: default
  labels:
    deploymentName: kafka-demo-deployment
spec:
  scaleTargetRef:
    name: kafka-demo-deployment
  pollingInterval: 5
  minReplicaCount: 0
  maxReplicaCount: 50
  cooldownPeriod:  30
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: 192.168.1.118:9092
      consumerGroup: group      
      topic: validation_event_monitor_demo2
      lagThreshold: "30"
      offsetResetPolicy: latest
```

After that I launched a Gatling load test that gradually decreases the number of users like this:

![image](https://user-images.githubusercontent.com/66093628/103948258-7ab16880-5107-11eb-98fc-67aa4695950f.png)

What I'm seeing is that when the load is high, my deployment will be scaled up and I'll have 5-7 pods running (not a fixed number since the test has a random element). But during the final stages of the test, the lag stays under 20, but the pods remain the same. 

Only when the test stops, leaving the topic without any new messsages will the pods get scaled down to zero.

Is it possible to have the pods scaled down to a smaller, non-zero number when the lag is low? In my services I will never have a topic with zero messages but I will have peak and valley loads so I'd like for example to have X pods during peak time but not so many pods during valley time.

Can this be done with Keda?

Thank you.
