### DISCUSSION TITLE
Kafka scaler - Need for clarification about the lagThreshold

### DISCUSSION THREAD

**Discussion by Vince-Chenal** [kedacore/keda#1519] [Q&A / Need Help]
Hey,

I'm running a POC with the kafka scaler and trying to understand the way it's behaving.

Here's the content of the ScaledObject I'm using:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-kafka-poc
spec:
  scaleTargetRef:
    name: kafka-keda-poc-consumer
  minReplicaCount: 0
  maxReplicaCount: 20
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: mykafka:9092
      consumerGroup: consumergroup
      topic: topic
      lagThreshold: "2000"
      offsetResetPolicy: earliest
```

Here's a screenshot of the metrics I'm getting when running my POC.
In order of appearance:
- The number of replicas of my consumer, 
- The message rate of incoming message into the topic (msgs/sec)
- The lag computed by [Kafka Minion](https://github.com/cloudworkz/kafka-minion)
- The metric exported by the keda-operator-metrics-apiserver

![poc_dashboard](https://user-images.githubusercontent.com/2440058/105334714-7d1bc400-5bd7-11eb-914e-a6c3617c9453.png)

When I look at the HPA I see that the lagThreshold is the target, but the value I'm getting for the "current value" is not the same "scale"as the Keda metric I have in my graph.

For example, when I have about 4k in the Keda metric, I see 470300m (470) in the current value:
```
NAME                      REFERENCE                            TARGETS              MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-keda-kafka-poc   Deployment/kafka-keda-poc-consumer   470300m/2k (avg)   1         20        10          27h
```

I have the impression that the current value is "per replica" (Keda metric / Nb Replicas). Am I missing something ?

Can someone clarify  if the lagThreshold relates to the "total lag" or some kind of "lag per replica" ?

Thanks in advance
