### DISCUSSION TITLE
Not able to setup metadata for jobTemplate created by keda scalejob

### DISCUSSION THREAD

**Discussion by connatix-cradulescu** [kedacore/keda#1558] [Q&A / Need Help]
Hi,

I am trying to add a certain label and annotation to a job template but I am not able to do that. Here is my configuration:
```
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: keda-scaling-{{ .Release.Namespace }}
        annotations:
          sidecar.istio.io/inject: "false"
      spec:
        containers:
    ------
```
Here is the result in cluster:
```
 spec:
    failedJobsHistoryLimit: 1
    jobTargetRef:
      backoffLimit: 4
      template:
        metadata: {}
        spec:
          containers:
``` 

From the format, this would be the logical choice but seems the CRD is ignoring my setup. 

Any advice please, on how I can update the metadata?

**Comment by TsuyoshiUshio** [comment]
Hi @connatix-cradulescu  Could you share your ScaledJob yaml file?
The ScaledJob is just copy under the JobTargetRef. https://github.com/kedacore/keda/blob/main/pkg/scaling/executor/scale_jobs.go#L91
It might be indentation issue.

**Reply by connatix-cradulescu** [reply]
Hi @TsuyoshiUshio here is my template:
````
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: keda-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: keda-{{ .Chart.Name }}
      spec:
        containers:
        - name: keda-{{ .Chart.Name }}
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: rabbitmq-consumer
          env:
            - name: APPSETTINGS__RUNASJOB
              value: "true"
          {{- range $key, $value :=  .Values.env }}
            - name: {{ $key | upper | replace "-" "_" }}
              value: {{ $value | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.affinity }}
        affinity:
          {{ toYaml . | indent 10 | trim }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{ toYaml . | indent 10 | trim }}
        {{- end }}
        restartPolicy: Never
    backoffLimit: 1
  pollingInterval: 5          # Optional. Default: 30 seconds
  maxReplicaCount: {{ .Values.kedaScalingJob.maxReplicaCount }}           # Optional. Default: 100 Note: The real value is maxReplicaCount - Values.replicaCount. This is driven for tests with below custom strategy
  successfulJobsHistoryLimit: 1   # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 1       # Optional. Default: 100. How many failed jobs should be kept.
  scalingStrategy:
    strategy: "custom"
    customScalingQueueLengthDeduction: 2
    customScalingRunningJobPercentage: "1"
  triggers:
  - type: rabbitmq
    metadata:
      protocol: http
      queueName: video_encoding_hardware
      queueLength  : "1"
    authenticationRef:
      name: keda-{{ .Chart.Name }}
      ```
      
      Regarding the annotation, i did remove it since I am with Istio still in tests. But I can't see the label on the pod created by job.
