### DISCUSSION TITLE
Keda V2.1. RabbitMQ Scaler. ScalerNotActive

### DISCUSSION THREAD

**Discussion by Vincentvwal** [kedacore/keda#1586] [Q&A / Need Help]
I'm trying to set up the RabbitMQ Scaler on Keda V2.1, however i am receiving the error "ScalerNotActive"

Kubernetes version: (AKS) 1.19.6
Keda: V2.1
Installed using helm

Setup using the following Yaml:

```
apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  host: <HOSTDATA> # base64 encoded value of format amqp://guest:password@localhost:5672/vhost
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: StatefulSet
    name: test-instance
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: rabbitmq
    metadata:
      type: rabbitMQTrigger
      protocol: amqp
      queueName: TestQueue
      queueLength: "20"
      vhostName: /
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
```

ScaledObject status:
```
Status:
  Conditions:
    Message:  ScaledObject is defined correctly and is ready for scaling
    Reason:   ScaledObjectReady
    Status:   True
    Type:     Ready
    Message:  Scaling is not performed because triggers are not active
    Reason:   ScalerNotActive
    Status:   False
    Type:     Active
```
