### DISCUSSION TITLE
Azure service bus : Error checking metric name uniqueness

### DISCUSSION THREAD

**Discussion by shashanksdixit** [kedacore/keda#1593] [Q&A / Need Help] [answered]
Hi All

I have used Azure service bus scaler and created example using the documentation here 
https://github.com/kedacore/sample-dotnet-worker-servicebus-queue/blob/main/connection-string-scenario.md

Once I create the scaled object and run the command `kubectl describe scaledobject`, I am getting below error.

`Message:               Error checking metric name uniqueness`
    `Reason:                ScaledObjectCheckFailed`
    `Status:                False`
    `Type:                  Ready`
    `Message:               ScaledObject check failed`
    `Reason:                UnkownState`
    `Status:                Unknown`
    `Type:                  Active`

I am not sure what is missing. Can somebody help.

Thanks in advance.

**Comment by tomkerkhove** [comment, marked as answer]
What version of KEDA are you using and can you share the raw YAML please?

**Reply by shashanksdixit** [reply]
I am using Keda 2.1
Deployed using yaml https://github.com/kedacore/keda/releases/download/v2.1.0/keda-2.1.0.yaml

This is my scaledobject as below. 

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-servicebus-queue-scaledobject
  namespace: example
spec:
  scaleTargetRef:
    name: receiverdeploy
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: testqueue
      subscriptionName: subscription1
      namespace: kedatest
      messageCount: "5"
    authenticationRef:
        name: azure-servicebus-auth
```
