### DISCUSSION TITLE
unable to use secrets under secret-mounts in TriggerAuthentication Keda scaler

### DISCUSSION THREAD

**Discussion by sivakumar715** [kedacore/keda#1594] [Q&A / Need Help] [answered]
I'm trying to setup keda scaler on azure queue trigger function. As per the queue scaler trigger, the queue connection string is mandatory for keda scaler.

I have queue connection string stored in secret-mounts with name "TestQueueConnectionString" and below is my secretProvider.yaml looks like.

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{- include "testqueuefunctions.labels" . | nindent 4 }}
spec:
  provider: azure                   
  parameters:
    usePodIdentity: "true"         
    keyvaultName: {{ .Values.keyVault.name | quote }}
    objects:  |
      array:
        - |
          objectName: {{ .Values.storage.queueConnectionStringKeyVaultSecretName }}
          objectAlias: TestQueueConnectionString
          objectType: secret
          objectVersion: {{ .Values.storage.queueConnectionStringKeyVaultSecretVersion }}
    resourceGroup: {{ .Values.keyVault.resourceGroupName | quote }}
    subscriptionId: {{ .Values.keyVault.subscriptionId | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
```

how to use **TestQueueConnectionString** in TriggerAuthentication Keda which is referred in ScalarObject?. please let me know if any one have solution for above issue.
