### DISCUSSION TITLE
External metric name is all messed up

### DISCUSSION THREAD

**Discussion by adrianmiron** [kedacore/keda#1604] [Q&A / Need Help] [answered]
Hi,

This is the chart i am using : 

```
{{ if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{{ template "mediawarp.name" . }}-worker"
  namespace: {{ .Release.Namespace | quote }}

  labels:
    app.kubernetes.io/name: "{{ template "mediawarp.name" . }}-worker"
    app.kubernetes.io/component: "mediawarp"
    app.kubernetes.io/part-of: "connect"

    helm.sh/chart: "{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Values.image.tag | trunc 63 }}"
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
  scaleTargetRef:
    name: "{{ template "mediawarp.fullname" . }}-worker"
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod:  {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.worker.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.worker.autoscaling.maxReplicas }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: "https://prometheus.internal.{{ .Values.env.name }}.{{ .Values.env.owner }}.{{ .Values.env.baseUrl }}"
        metricName: default_media_warp_3_0_0_worker_taskCount
        threshold: "{{ .Values.worker.autoscaling.queueLengthTargetValue }}"
        query: default_media_warp_3_0_0_worker_taskCount
{{ end }}
```

This is how the scaledobject looks (notice the  External Metric Name, which seems to be a weird mix between  Server Address andd Metric Name)

```
Triggers:
    Metadata:
      Metric Name:     default_media_warp_3_0_0_worker_taskCount
      Query:           default_media_warp_3_0_0_worker_taskCount
      Server Address:  https://prometheus.internal.myenv.adrian.adrian.playground.ownzones.dev
      Threshold:       1
    Type:              prometheus
Status:
  Conditions:
    Message:  ScaledObject is defined correctly and is ready for scaling
    Reason:   ScaledObjectReady
    Status:   True
    Type:     Ready
    Message:  Scaling is not performed because triggers are not active
    Reason:   ScalerNotActive
    Status:   False
    Type:     Active
  External Metric Names:
    prometheus-https---prometheus-internal-myenv-adrian-adrian-playground-ownzones-dev-default_media_warp_3_0_0_worker_taskCount
```

This happened after v2 upgrade, i followed the guide but i did not notice anything i missed.

Thanks
