### DISCUSSION TITLE
Unable to use azure AD Pod Identity under trigger auth for Azure Storage Queue scaler in keda v2.0

### DISCUSSION THREAD

**Discussion by sivakumar715** [kedacore/keda#1605] [Q&A / Need Help]
I want to use trigger auth based on Azure AD pod identity to authenticate my azure storage queue scaler, but it's not working. here is my scaler.yaml file. 

```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Release.Name }}
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{- include "testfunctions.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Release.Name | quote }}
  pollingInterval: {{ .Values.autoScaling.pollInterval }}
  cooldownPeriod: {{ .Values.autoScaling.cooldownSeconds }}
  minReplicaCount: {{ .Values.autoScaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoScaling.maxReplicaCount }}
  triggers:
  - type: azure-queue
    metadata:
      queueName: {{ .Values.storage.queueName | quote }}
      queueLength: {{ .Values.autoScaling.queueLength | quote }}
    authenticationRef:
      name: {{ .Release.Name }}
```
please suggest us if anyone is aware of on , how to use azure queue scaler based on azure ad pod identity trigger auth?.
