### DISCUSSION TITLE
(Keda V2.1) Idle connections are not closed in Postgres DB while using Postgres Scaler

### DISCUSSION THREAD

**Discussion by rrramkarthick** [kedacore/keda#1608] [Q&A / Need Help]
Hi,
I'm using Postgres Scaler to scale my application deployment. PFB given yaml file content that I used to create Postgres Scaler scaled object,
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-postgres-scaler
  namespace: default
spec:
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 60  
  cooldownPeriod:  60 
  scaleTargetRef:
    name: my-app
  triggers:
    - type: postgresql
      metadata:
        userName: "<username>"
        host: "<host-name>"
        dbName: "<db-name>"
        sslmode: "require"
        port: "<port>"
        query: "SELECT count FROM db_table WHERE id=1"
        targetQueryValue: "1"
      authenticationRef:
        name: postgres-password-auth
```
I see idle connections for my database table in Postgres DB. Please find below the query result of idle connection from pg_stat_activity,
```
datid  | datname  |  pid   |          query_start          |         state_change          | query | state
-------+----------+--------+-------------------------------+-------------------------------+-------+-------
 30314 | db_table | 894832 | 2021-02-15 07:13:03.60811+00  | 2021-02-15 07:13:03.60811+00  | ;     | idle
 30314 | db_table | 899324 | 2021-02-15 09:10:42.882847+00 | 2021-02-15 09:10:42.882847+00 | ;     | idle
 30314 | db_table | 900040 | 2021-02-15 09:11:01.351342+00 | 2021-02-15 09:11:01.351342+00 | ;     | idle
 30314 | db_table | 899816 | 2021-02-15 09:10:44.476584+00 | 2021-02-15 09:10:44.476584+00 | ;     | idle
 30314 | db_table | 899792 | 2021-02-15 09:10:44.492219+00 | 2021-02-15 09:10:44.492219+00 | ;     | idle
 30314 | db_table | 900624 | 2021-02-15 09:14:34.020814+00 | 2021-02-15 09:14:34.020814+00 | ;     | idle
```
These connections are opened by postgres scalers. I don't see any errors in Keda operator logs.

These connections should be closed by Postgres scalers Right? 

Is there anything that I can configure to close these idle connections ?
