### DISCUSSION TITLE
Azure EventHub - unable to get eventhub client

### DISCUSSION THREAD

**Discussion by hgreving** [kedacore/keda#1618] [Q&A / Need Help]
The Azure EventHub scaler documentation I found on keda.sh is not clear about what to configure when using PodIdentity. It only tells to configure: eventHubName and eventHubNamespace when using Azure as PodIdentity provider. The HPA is created but there is no scaling happening due to the following error in the KEDA operator log:
```
2021-02-16T17:07:25.578Z ERROR controller Reconciler error {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "name": "example-keda-scaled-object", "namespace": "example", "error": "error getting scaler for trigger #0: unable to get eventhub client: failed to refersh token: &{{{ 0 0 0 } 0x3a45858 {{ <nil> false } { <nil> false } {http <nil> 169.254.169.254 /metadata/identity/oauth2/token false api-version=2018-02-01&resource=https%3A%2F%2Feventhubs.azure.net%2F } { <nil> false }} https://eventhubs.azure.net/ true 300000000000} 0xc000abb760 0xc0008689f0 <nil> [] 5}"}
github.com/go-logr/zapr.(*zapLogger).Error
```

Also found the following messages in the scaledobject:
```
    - message: Error checking metric name uniqueness
      reason: ScaledObjectCheckFailed
      status: 'False'
      type: Ready
    - message: ScaledObject check failed
      reason: UnkownState
      status: Unknown
      type: Active
``` 

I hope someone could point me in the right direction on how to configure it correctly?

I installed KEDA v2.1.0.

Here some manifests:

TriggerAuthentication.yaml:

```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: example-keda-trigger-auth
  namespace: example
spec:
  podIdentity:
    provider: azure
```

ScaledObject.yaml:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example-keda-scaled-object
  namespace: example
spec:
  maxReplicaCount: 4
  minReplicaCount: 1
  scaleTargetRef:
    name: example-keda-deployment
  triggers:
    authenticationRef:
      name: example-keda-trigger-auth
    metadata:
      eventHubName: example-keda
      eventHubNamespace: dev-example-keda-log-ns
      storageConnectionFromEnv: StorageConnection
      unprocessedEventThreshold: '10'
    type: azure-eventhub
```

Deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-keda-deployment
  namespace: example
spec:
  selector:
    matchLabels:
      app: example-keda
  template:
    metadata:
      labels:
        app: example-keda
        aadpodidbinding: keda-scaler-identity-selector
    spec:
      containers:
      - name: example-keda
        image: --removed image--
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: example-keda-config
        - secretRef:
            name: example-keda-secret
```

**Comment by tomkerkhove** [comment]
@ahmelsayed Do you have an idea?

**Comment by hgreving** [comment]
I found a misconfiguration with the managed identities permissions. After fixing that I have the following error in the keda operator log:
```
2021-02-17T13:56:18.778Z ERROR controller Reconciler error {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "name": "example-keda-scaled-object", "namespace": "example", "error": "error getting scaler for trigger #0: unable to get eventhub metadata: no storage connection string given"}
```

and the ScaledObject has the same status:
```
status:
  conditions:
    - message: Error checking metric name uniqueness
      reason: ScaledObjectCheckFailed
      status: 'False'
      type: Ready
    - message: ScaledObject check failed
      reason: UnkownState
      status: Unknown
      type: Active
```

I don't know yet why the ScaledObjectCheck failed?

**Reply by tomkerkhove** [reply]
Does this contain the connection string for Azure Storage?

```
        envFrom:
        - configMapRef:
            name: example-keda-config
        - secretRef:
            name: example-keda-secret
```
