### DISCUSSION TITLE
should we install different metrics server other than keda for resource metrics data (cpu/memory)

### DISCUSSION THREAD

**Discussion by Cogniser** [kedacore/keda#1644] [Q&A / Need Help]
Hi,
I m trying to test auto scaling based on cpu/memory using keda provied scalers
https://keda.sh/docs/2.1/scalers/cpu/
https://keda.sh/docs/2.1/scalers/memory/

Below is my config yaml
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metadata-svc-memory
  namespace: jobsync
spec:
  scaleTargetRef:
    apiVersion:    apps/v1  # Optional. Default: apps/v1
    kind:          Deployment        # Optional. Default: Deployment
    name:          metadata-service        # Mandatory. Must be in the same namespace as the ScaledObject
  pollingInterval: 30                                # Optional. Default: 30 seconds
  cooldownPeriod:  300                               # Optional. Default: 300 seconds
  minReplicaCount: 1                                 # Optional. Default: 0
  maxReplicaCount: 5                               # Optional. Default: 100   
  triggers:
  - type: memory
    metadata:
      type: Utilization
      value: "50"
```
Getting below issue
```
the HPA was unable to compute the replica count: unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
```
Only external API service is available
```
kubectl get apiservices | grep metrics
v1beta1.external.metrics.k8s.io             keda/keda-operator-metrics-apiserver   True        3d22h
```
do we need to install metrics server for cpu/memory related data
https://github.com/kubernetes-sigs/metrics-server
