### DISCUSSION TITLE
Spread ScaledJobs evenly across multiple nodes in one cluster

### DISCUSSION THREAD

**Discussion by luthv** [kedacore/keda#1691] [Q&A / Need Help] [answered]
Hi,
We're running Keda ScaledJobs on a linode LKE cluster with two nodes, but we're seeing only one node gets utilized by the auto scaler. We're using RabbitMQ trigger with this configuration
```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: $CI_PROJECT_NAME
  namespace: $NAMESPACE
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: $CI_PROJECT_NAME
          image: $GCR_REGISTRY/$GCR_PROJECT_ID/$GCR_PROJECT_NAME:$BUILD_ID
          imagePullPolicy: IfNotPresent
          command: ["./run.sh"]
        imagePullSecrets:
        - name: $IMAGE_PULL_SECRET
        restartPolicy: Never
    backoffLimit: 4
  pollingInterval: 20             # Optional. Default: 30 seconds
  maxReplicaCount: 30             # Optional. Default: 100
  successfulJobsHistoryLimit: 1   # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 0       # Optional. Default: 100. How many failed jobs should be kept.
  scalingStrategy:
    strategy: 'accurate'                        # Optional. Default: default. Which Scaling Strategy to use.
  triggers:
  - type: rabbitmq
    metadata:
      queueName: $QUEUE
      host: $AMQP_URL
      queueLength  : '1'
```
The job is designed to consume only one message, process the message and then exit immediately after the process completed.

Is there anything we can do to make the jobs spread evenly between the two nodes in the cluster?
