### DISCUSSION TITLE
Azure Service Bus Scaler with HashicorpVault authentication fails with Error getting scalers

### DISCUSSION THREAD

**Discussion by rajarajan-s-imanage** [kedacore/keda#1746] [Q&A / Need Help] [answered]
Hello, 

I'm trying to use Azure Service Bus Scaler and TriggerAuthentication configured with HashicorpVault, 

Here's my configuration, 

```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: crack-app-trigger-auth
  namespace: ku-local
spec:
  hashiCorpVault:
    address: "http://vault.vault-ns.svc.cluster.local:8200"
    authentication: kubernetes
    role: "kcs-keda-role"
    mount: "kubernetes"
    credential:
      serviceAccount: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    secrets:
      - parameter: crack-app-keda-autoscaler
        key: "secretKey"
        path: "kv/data/secret-1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: crack-app-keda-autoscaler
  namespace: ku-local
spec:
  scaleTargetRef:
    name: crack-app
  pollingInterval: 10
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  maxReplicaCount: 15
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: service-bus-queue-name
        namespace: service-bus-namespace-name
        messageCount: "3"
      authenticationRef:
        name: crack-app-trigger-auth


```

Just in case, 
Vault role config, 
 vault write auth/kubernetes/role/kcs-keda-role \
   bound_service_account_names=keda-operator \
   bound_service_account_namespaces=keda \
   policies=kcs-policy \
   ttl=24h
   
Vault policy kcs-config,
path "kv/data/secret-1"
{
  capabilities = ["read"]
}

secret exists in path 
kv/secret-1
"secretKey": "service-bus-connection-string"

Sorry if I'm missing anything obvious, 

Here's the stackTrace, 

```
2021-04-19T09:54:43.012Z	ERROR	controllers.ScaledObject	Error getting scalers	{"ScaledObject.Namespace": "ku-local", "ScaledObject.Name": "crack-app-keda-autoscaler", "error": "error getting scaler for trigger #0: error parsing azure service bus metadata: no connection setting given"}
github.com/kedacore/keda/v2/controllers.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/hpa.go:47
github.com/kedacore/keda/v2/controllers.(*ScaledObjectReconciler).createAndDeployNewHPA
	/workspace/controllers/hpa.go:30
github.com/kedacore/keda/v2/controllers.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/scaledobject_controller.go:316
github.com/kedacore/keda/v2/controllers.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/scaledobject_controller.go:204
github.com/kedacore/keda/v2/controllers.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/scaledobject_controller.go:160
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:244
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90
2021-04-19T09:54:43.012Z	ERROR	controllers.ScaledObject	Failed to create new HPA resource	{"ScaledObject.Namespace": "ku-local", "ScaledObject.Name": "crack-app-keda-autoscaler", "HPA.Namespace": "ku-local", "HPA.Name": "keda-hpa-crack-app-keda-autoscaler", "error": "error getting scaler for trigger #0: error parsing azure service bus metadata: no connection setting given"}
github.com/kedacore/keda/v2/controllers.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/scaledobject_controller.go:316
github.com/kedacore/keda/v2/controllers.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/scaledobject_controller.go:204
github.com/kedacore/keda/v2/controllers.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/scaledobject_controller.go:160
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:244
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90
2021-04-19T09:54:43.012Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"ScaledObject","namespace":"ku-local","name":"crack-app-keda-autoscaler","uid":"271d5ae6-ce19-4a39-b90b-d71b7dba56b5","apiVersion":"keda.sh/v1alpha1","resourceVersion":"1102689"}, "reason": "KEDAScalerFailed", "message": "error parsing azure service bus metadata: no connection setting given"}
2021-04-19T09:54:43.012Z	ERROR	controllers.ScaledObject	Failed to ensure HPA is correctly created for ScaledObject	{"ScaledObject.Namespace": "ku-local", "ScaledObject.Name": "crack-app-keda-autoscaler", "error": "error getting scaler for trigger #0: error parsing azure service bus metadata: no connection setting given"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:244
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90
2021-04-19T09:54:43.013Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"ScaledObject","namespace":"ku-local","name":"crack-app-keda-autoscaler","uid":"271d5ae6-ce19-4a39-b90b-d71b7dba56b5","apiVersion":"keda.sh/v1alpha1","resourceVersion":"1102689"}, "reason": "ScaledObjectCheckFailed", "message": "Failed to ensure HPA is correctly created for ScaledObject"}
2021-04-19T09:54:43.023Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "name": "crack-app-keda-autoscaler", "namespace": "ku-local", "error": "error getting scaler for trigger #0: error parsing azure service bus metadata: no connection setting given"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90
```
