### DISCUSSION TITLE
RabbitMQ Trigger doesn't work after upgrading to 2.2

### DISCUSSION THREAD

**Discussion by basilfx** [kedacore/keda#1751] [Q&A / Need Help] [answered]
I've updated from KEDA Chart 2.0.1 to 2.2.1, and I noticed that scaling doesn't work anymore (by observing the `keda` user in the RabbitMQ connection list in the management interface). When I downgrade back to 2.0.1, it works again. I'm running K8s 1.19.

I have the following ScaledObject (I also updated the parameters with 2.2 parameters, no effect):

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redacted
  namespace: redacted
spec:
  maxReplicaCount: 10
  minReplicaCount: 1
  scaleTargetRef:
    name: redacted
  triggers:
  - metadata:
      host: amqp://keda:keda@redacted.namespace
      queueName: Gateway-Queue
      queueLength: "100"
    type: rabbitmq
```

KEDA seems to pick-up the job, and reports the following (but note ScalerNotActive):

```yaml
...
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is not performed because triggers are not active
    reason: ScalerNotActive
    status: "False"
    type: Active
  externalMetricNames:
  - rabbitmq-Gateway-Queue
  originalReplicaCount: 1
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment
```

According to the release notes, there are no breaking changes. But I don't understand why it isn't working, or how I should activate the trigger.

Any idea's?
