### DISCUSSION TITLE
Scale to zero with cron trigger

### DISCUSSION THREAD

**Discussion by dorroddorrod** [kedacore/keda#1759] [Q&A / Need Help] [answered]
### Report

Hi !,
I'm running few k8s dev cluster and i would like to scale few deployments to 0 during the weekend to save some costs.
I used the cron trigger to schedule a scale down but nothing really happen
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-to-zero
  namespace: default
spec:
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 30
  scaleTargetRef:
    name: my-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 18 * * * *
      end: 30 * * * *
      desiredReplicas: "0"
```

I probably didn't configure something right.. didnt find any doc's regarding this use-case 

### Expected Behavior

The number of replicas should decrease to 0

### Actual Behavior

Nothing

### Steps to Reproduce the Problem

1. Apply the above yaml file and watch the number of pods that are running 

### KEDA Version

2.2.0

### Kubernetes Version

1.16

### Platform

Amazon Web Services

### Scaler Details

Cron

**Comment by tomkerkhove** [comment]
I looks like you're explicitly telling it to have at least one instance:
```yaml
  minReplicaCount: 1
```

Can you change that to 0 and try again please?

**Comment by dorroddorrod** [comment]
When setting the minReplicaCount to 0, i get no pods even though the ScaledObject is not triggered.
I would like to have 1 replica when the ScaledObject is "Off" and when it turned "On" (according the to cron time-frame) i should have 0 pods.

Any idea what am i doing wrong ?

**Reply by zroubalik** [reply]
What if you set the minReplicaCount to 0 and then specify the cron the other way round - ie. when do you want to have it scaled to 1.

**Reply by dorroddorrod** [reply]
Thanks for the fast response @zroubalik  !
I tried this as well, at the moment i applied the ScaleObject with the following spec, the replica number went down to 0
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-to-zero
  namespace: default
spec:
  minReplicaCount: 0
  maxReplicaCount: 1
  scaleTargetRef:
    name: my-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 0 0 * * 7 ##At 00:00 on Sunday
      end: 0 0 * * 5 ## At 00:00 on Friday
      desiredReplicas: "1"
```
I think it happen cause the cron start window didnt kicked in so the minReplicaCount set it to 0

**Reply by zroubalik** [reply]
yeah, I'd recommend to check that it si working as you would like to, by setting the cron to some test values (ie. some time that allows you to double check the functionality right now)

**Reply by dorroddorrod** [reply]
Yeah, i checked and it is, but its doesn't solve the problem when applying the ScaledObject at the first time for longer range

**Reply by tomkerkhove** [reply]
I'm not sure if I'm following, so if you apply the `ScaledObject` it scales to 0 but it never goes up in that period or?

**Reply by iarc13** [reply]
The [KEDA docs](https://keda.sh/docs/2.14/scalers/cron/#scale-to-0-during-off-hours) also suggest to use the other way round like @zroubalik says above.

**Comment by dorroddorrod** [comment]
Any updates ?

**Comment by dorroddorrod** [comment]
I will try to explain :
My goal is to scale to zero during the weekends.

First thing i tried is to set the following object :
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-to-zero
  namespace: default
spec:
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 30
  scaleTargetRef:
    name: my-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 0 0 * * 5 ## At 00:00 on Friday
      end: 0 0 * * 7 ##At 00:00 on Sunday
      desiredReplicas: "0"
```
It means - during the weekdays, the minReplicaCount should be 1 and the maxReplicaCount should be 5 and during the weekends, it should be 0.
That doesnt work at all. (it stays 1 all the time).

Then, i tried the opposite way, 
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-to-zero
  namespace: default
spec:
  minReplicaCount: 0
  maxReplicaCount: 1
  scaleTargetRef:
    name: my-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 0 0 * * 7 ##At 00:00 on Sunday
      end: 0 0 * * 5 ## At 00:00 on Friday
      desiredReplicas: "1"
```
All the time it should be 0 unless its weekdays.
This one works BUT, at the moment i apply the ScaledObject, it scales down my pods to 0 until the start time of the cron pass, means i'll need to wait until next Sunday to get the ScaledObject work as i expected.

**Reply by tomkerkhove** [reply]
I think your expectations are different from how it works I think.

What you are looking for is a cron trigger to apply the max replica during the window and minimum replica outside of the window, is that correct?

Because what we do now is only give you what you configure in the desiredReplicas

**Comment by dorroddorrod** [comment]
@tomkerkhove i'm looking for a scale-to-zero solution triggered by time, is Keda supports it ? 
For example : if its weekend my deployment goes to 0 replicas BUT if its not, scale to 2.
If so, can you please show me an example how can i achieve that ?

**Reply by tomkerkhove** [reply]
That's exactly what it allows you to do!

For example, I have this workload scaling with CRON:
![image](https://user-images.githubusercontent.com/4345663/125035856-95eb3980-e092-11eb-8b7c-d44a0062ba04.png)

And this is its ScaledObject:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scheduled-autoscaling
spec:
  minReplicaCount: 5
  scaleTargetRef:
    name: nginx-reverse-proxy
  triggers:
  - metadata:
      desiredReplicas: "10"
      end: 45 * * * *
      start: 30 * * * *
      timezone: Asia/Kolkata
    type: cron
```

I think what's confusing here, though, is that it uses `desiredReplicas` and not `maxReplicaCount`. Do you recall why we made that decision @zroubalik?

**Reply by dorroddorrod** [reply]
@tomkerkhove The thing is, it doesn't work when you set the desiredReplicas to 0.
Cause the minReplicaCount > 0 so it will never scale to 0.

**Reply by tomkerkhove** [reply]
But I think you just need to turn it around:
- Define the window during which is needs to be available, and set desired accordinly
- Outside of the window, it will scale to minReplicaCount which is 0 in this case

**Reply by dorroddorrod** [reply]
@tomkerkhove i tried it as well,
When the `minReplicaCount` is set to 0, and the current time is between the `start` and the `end` time at the moment i apply the `scaledObject`, it still scale down my deployment to 0, until the next time the `start` window occurs.

**Reply by tomkerkhove** [reply]
Then that might be a bug but if a new cycle starts it should apply it, if I get it correctly that's what you are acking here as well, is that correct?

If so, we'll have to have a look for the apply-bug.

**Reply by dorroddorrod** [reply]
Yes, you are correct,
When i apply the following object my deployment goes to 0 even though is should be 1 (It is Friday 13:00 in Israel)
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-to-zero
  namespace: default
spec:
  minReplicaCount: 0
  maxReplicaCount: 1
  scaleTargetRef:
    name: my-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 0 0 * * 7 ##At 00:00 on Sunday
      end: 0 0 * * 6 ## At 00:00 on Saturday
      desiredReplicas: "1"
```

**Reply by dorroddorrod** [reply]
It's easy to reproduce, just apply the following object at <hour>:31-44 and see that the min replicas is 0
```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-to-zero
  namespace: default
spec:
  minReplicaCount: 0
  maxReplicaCount: 1
  scaleTargetRef:
    name: nginx
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 30 * * * *
      end: 45 * * * *
      desiredReplicas: "1"
EOF
```
@tomkerkhove probably because of this : 
https://github.com/kedacore/keda/blob/dff7b3244a51a2b8fb8ec00483a661c1af7ed753/pkg/scalers/cron_scaler.go#L59

**Comment by dammianhr** [comment, marked as answer]
I have the same problem. not scaling to zero with:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject
spec:
  scaleTargetRef:
    name: backoffice
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cron
    metadata:
      timezone: America/Argentina/Buenos_Aires
      start: 35 13 * * *
      end: 40 13 * * *
      desiredReplicas: "0"
```
I am trying to scale to zero between start and end.
But it doesn't

**Reply by tomkerkhove** [reply]
https://github.com/kedacore/keda/discussions/2153

**Reply by thuandt** [reply]
I have same problem when trying to create `power management cron` using KEDA `cron` scaler.

Even with `minReplicaCount: 0` and `desiredReplicas: "0"`, KEDA is not scale down my deployment to zero  between `start` and `end`

**Reply by tomkerkhove** [reply]
I have suggested to open a bug on https://github.com/kedacore/keda/discussions/2153#discussioncomment-3153245

**Reply by gaganyaan2** [reply]
Opened as a feature request: https://github.com/kedacore/keda/issues/3609

**Comment by cezaroliveira** [comment]
This config works for me.

There are replicas only during the specified interval and no replicas outside these hours.
```yaml

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-replica-zero
spec:
  cooldownPeriod: 300
  maxReplicaCount: 2
  minReplicaCount: 0
  pollingInterval: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-replica-zero
  triggers:
  - metadata:
      desiredReplicas: "1"
      start: 50 19 * * *
      end: 30 20 * * *
      timezone: America/Sao_Paulo
    type: cron
```
