### DISCUSSION TITLE
How can I implement KEDA for multiple namespaces

### DISCUSSION THREAD

**Discussion by harshik9** [kedacore/keda#1761] [General] [answered]
Currently i have 4 namespaces on my cluster and each namespace belongs to a project. I was successful in implementing KEDA for one namespace. The problem is when I try to Implement the kind:APIService for another namespace, the one that I have already implemented gets replaced with the new one. How can i make this work for different namespaces. 

[Keda1-namespace.txt](https://github.com/kedacore/keda/files/6394928/Keda1-namespace.txt)
[Keda2-namespace.txt](https://github.com/kedacore/keda/files/6394929/Keda2-namespace.txt)

we are scaling applications based on the confluent kafka partition

**Comment by zroubalik** [comment, marked as answer]
Unfortunately it is not possible to install mutliple KEDA instances on one cluster, this needs to be solved first https://github.com/kedacore/keda/issues/470 (TLDR Metrics Adapter doesn't allow this, as you correctly mentioned that the `APIService` object gets replaced, as there could be only one such resource in the cluster).

But you can setup your KEDA to watch all namespaces (that's the default setting), thus scaling will be working across all of them.

**Reply by harshik9** [reply]
@zroubalik, thank you for the response. How can i make my metrics server listen to all the namespaces. Do I need separate operator for each namespace?
Can I have the api metrics server in one namespace and have it listening for a service which is another namespace?
Is there an example/code that I can refer to?

**Reply by zroubalik** [reply]
If you install KEDA with default settings (into `keda` namespace, with env variable `WATCH_NAMESPACE=""`), it will watch and autoscale your workloads across all namespaces. You don't need to install mutliple operators or anything else.

**Reply by sidharthkumarpradhan** [reply]
Hello @zroubalik and @harshik9 , thank you for the insightful discussion here, I am sure it must have assisted many. Currently, our team is struggling to install KEDA for Namespace specific wise , instead of cluster. We have AKS cluster, and have many Namespaces with Production applications running within them. Our goal is to use KEDA to watch some specific namespace for scaling the deployments and scaled jobs. We have installed KEDA using this approach.

# Including admission webhooks
kubectl apply --server-side -f https://github.com/kedacore/keda/releases/download/v2.11.0/keda-2.11.0.yaml

We have all these resources that got installed

![image](https://github.com/kedacore/keda/assets/66263561/27cfd166-1666-4e56-8a74-6c468e9223e2)


Could you kindly help us here? what we need to do to achieve our desire goal. Thank you so much.

**Reply by JorTurFer** [reply]
Hi, currently it's not supported. You can use 1 KEDA instance for the whole clusters or for just 1 namespace, but filtering the namespaces isn't supported at this moment.

**Reply by sidharthkumarpradhan** [reply]
Hello @JorTurFer, Thank you so much for responding to my queries, then the WATCH_NAMESPACE env variable is for specifying only one namespace?  If this is the case, how can we restrict KEDA access to other namespaces? As we have a production workload deployed to other Namespaces, we don't want anyone accidentally deploying a Scaled Object in them, which in turn will scale up the instances that we don't want to be scaled up.

Thank you again for your support.

**Reply by JorTurFer** [reply]
Once you set `WATCH_NAMESPACE=XXXXX`, KEDA will only ready resources from that namespace (even though the RBAC allows reading from others, it's handled by the code). The problem is that ScaledObjects must be in the same namespace where the workloads are, you can't deploy ScaledObjects in KEDA namespace for scaling workloads in other namespaces

**Reply by sidharthkumarpradhan** [reply]
Thanks @JorTurFer, yes I understand that **WATCH_NAMESPACE = "namespace_1"** is currently what supported, is there any way we can achieve this **WATCH_NAMESPACE = "['namespace_1', 'namespace_2','namespace_3']"**. The goal is to restrict KEDA to some specific Namespaces instead of ALL the Namespaces in the Cluster. As we are using a shared cluster, we have other applications deployed into other Namespaces. How to restrict KEDA to specific Namespaces only in a Cluster? What are our options here?

Thanks

**Reply by JorTurFer** [reply]
> Hi, currently it's not supported. You can use 1 KEDA instance for the whole clusters or for just 1 namespace, but filtering the namespaces isn't supported at this moment.

Not at this moment. The only option you have for that is **in case of only using ScaledJobs**, you can deploy KEDA operator manually on each namespace and limit the scope to that namespace. If you are using ScaledObjects, currently KEDA metrics server is cluster scoped due to upstream limitations. If you need ScaledObjects, deploying KEDA at cluster level, bringing access to all the namespaces is the only option to have multiple namespaces.

It could be a nice feature if you are willing to contribute with it, but currently there isn't any other option than above paragraph

**Reply by sidharthkumarpradhan** [reply]
Thank you so much @JorTurFer, I would love to contribute to KEDA project, I love this application. For our issue we are good with using ScaledJobs, I was wondering **how can we deploy operator namespace-wise and restrict access as you have mentioned above**, could you kindly guide me to some documentation please? 

Many Thanks

**Reply by sidharthkumarpradhan** [reply]
Hello @JorTurFer, correct me if I am wrong , what you mean is just **install keda-operator deployment** in each Namespace that we want to control. So , what i was wondering, what about the default keda-operator in Keda Namespace, should we delete that from there?  As I was checking the keda-operator deployment , I have noticed two things it is using a Secret and Service Account, so we have to create those with Role and Rolebinding for all the Namespaces that we want to deploy keda-operator, right?

```
      serviceAccount: keda-operator
      serviceAccountName: keda-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - name: certificates
        secret:
          defaultMode: 420
          optional: true
          secretName: kedaorg-certs
```
Thanks

**Reply by sidharthkumarpradhan** [reply]
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.11.0
  name: keda-operator
  namespace: crs-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.11.0
  name: keda-operator
  namespace: crs-dev
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - configmaps/status
  - events
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - external
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
- apiGroups:
  - '*'
  resources:
  - '*/scale'
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - keda.sh
  resources:
  - scaledjobs
  - scaledjobs/finalizers
  - scaledjobs/status
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.11.0
  name: keda-operator
  namespace: crs-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-operator
subjects:
- kind: ServiceAccount
  name: keda-operator
  namespace: crs-dev
---
```
Do you think the above permission is appropriate to our use cases. Thanks
