### DISCUSSION TITLE
Azure ServiceBus in other Azure Clouds (not Public)

### DISCUSSION THREAD

**Discussion by cvik1** [kedacore/keda#1861] [Q&A / Need Help]
Hi when using KEDA in Azure clouds other than Public where the URI for Service Buses don't follow the standard { namespace }.servicebus.windows.net/, how can we specify that we're in a different cloud so the URI is resolved with the correct endpoint? 
I have my trigger configured like this (which works in Azure public cloud):
```
pollingInterval: 30 # Optional. Default: 30 seconds
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 100 # Max number of pods of this type that can run at the same time.
  triggers:
  # {list of triggers to create jobs}
  - type: azure-servicebus
    metadata:
      # Required: queueName and namespace OR topicName and subscriptionName
      queueName: ${sbqueue}
      namespace: ${sbnamespace}
      messageCount: "1" # Optional. Default: 5 messages
    authenticationRef:
      name: autoscale-servicebus-triggerauth
---
```
but in the keda-operator logs I can see that the URI is being formed with ".servicebus.windows.net"
