### DISCUSSION TITLE
Understanding KEDA HPA metric value

### DISCUSSION THREAD

**Discussion by ChayanBansal** [kedacore/keda#1880] [Q&A / Need Help]
I have a KEDA enabled Azure Storage Queue Triggered function running in the Azure Kubernetes Service.

When I try to describe the hpa using kubectl command the following is shown:

![](https://user-images.githubusercontent.com/33371154/121165849-31a84080-c86e-11eb-84e9-c9f1d1ace0c9.png)

**Can you please explain what does the target average value 4167m / 5 mean?**

Here is the scaledobject.yaml:

```
apiVersion: v1
kind: Secret
metadata:
  name: queue-connection-secret
data:
  connection-string: ####
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-queue-auth
spec:
  secretTargetRef:
  - parameter: connection
    name: queue-connection-secret
    key: connection-string
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queuetrigfuncpod
spec:
  scaleTargetRef:
    name: queuetrigfuncpod
  minReplicaCount: 0
  maxReplicaCount: 120
  pollingInterval: 1
  cooldownPeriod: 900

  triggers:
  - type: azure-queue
    metadata:
      queueName: k8s-poc-queue
      queueLength: "1"
    authenticationRef:
        name: azure-queue-auth
```
