### DISCUSSION TITLE
Trouble combining ScaledObject and ClusterTriggerAuthentication with influxdb scaler

### DISCUSSION THREAD

**Discussion by acobaugh** [kedacore/keda#1892] [Q&A / Need Help] [answered]
I'm running the latest version of keda. I've poured over the documentation and read the code, and I can't quite fathom why this isn't working the way I expect it to. I'll summarize the resources I have and the error I'm seeing below:

## resources
```
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: influx-blue
spec:
  secretTargetRef:
  - key: authToken2
    name: influx-blue-auth
    parameter: authToken
  - key: serverURL
    name: influx-blue-auth
    parameter: serverURL
```

```
apiVersion: v1
data:
  authToken: REDACTED
  serverURL: REDACTED
kind: Secret
  name: influx-blue-auth
  namespace: keda
type: Opaque
```

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: course-group-jms-processor
  namespace: swe-develop
spec:
  maxReplicaCount: 3
  minReplicaCount: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: course-group-jms-processor
  triggers:
  - authenticationRef:
      kind: ClusterTriggerAuthentication
      name: influx-blue
    metadata:
      query: |
        from(bucket:"telegraf")
        |> range(start:-300s)
        |> filter(fn:(r) =>
          r._measurement == "ActiveMQ" and
          r.destinationName == "dev.notifications.courseGroupProc.in_q" and
          r.host =~ /amq-d.*.test.REDACTED/ and
          r._field == "QueueSize"
      thresholdValue: "1"
    type: influxdb
```

## errors

```
keda-operator-6b676d8c87-4hrxn keda-operator 2021-06-15T14:14:00.295Z	ERROR	controllers.ScaledObject	Failed to ensure HPA is correctly created for ScaledObject	{"ScaledObject.Namespace": "swe-develop", "ScaledObject.Name": "course-group-jms-processor", "error": "error getting scaler for trigger #0: error parsing influxdb metadata: no auth token given"}
keda-operator-6b676d8c87-4hrxn keda-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
keda-operator-6b676d8c87-4hrxn keda-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:244
keda-operator-6b676d8c87-4hrxn keda-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
keda-operator-6b676d8c87-4hrxn keda-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
keda-operator-6b676d8c87-4hrxn keda-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
keda-operator-6b676d8c87-4hrxn keda-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
keda-operator-6b676d8c87-4hrxn keda-operator k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
keda-operator-6b676d8c87-4hrxn keda-operator 	/go/pkg/mod/k8s.io/apimachinery@v0.20.7/pkg/util/wait/wait.go:155
keda-operator-6b676d8c87-4hrxn keda-operator k8s.io/apimachinery/pkg/util/wait.BackoffUntil
keda-operator-6b676d8c87-4hrxn keda-operator 	/go/pkg/mod/k8s.io/apimachinery@v0.20.7/pkg/util/wait/wait.go:156
keda-operator-6b676d8c87-4hrxn keda-operator k8s.io/apimachinery/pkg/util/wait.JitterUntil
keda-operator-6b676d8c87-4hrxn keda-operator 	/go/pkg/mod/k8s.io/apimachinery@v0.20.7/pkg/util/wait/wait.go:133
keda-operator-6b676d8c87-4hrxn keda-operator k8s.io/apimachinery/pkg/util/wait.Until
keda-operator-6b676d8c87-4hrxn keda-operator 	/go/pkg/mod/k8s.io/apimachinery@v0.20.7/pkg/util/wait/wait.go:90```
