### DISCUSSION TITLE
Can a single TriggerAuthentication object be used for multiple triggers?

### DISCUSSION THREAD

**Discussion by amirschw** [kedacore/keda#1911] [Q&A / Need Help] [answered]
Suppose I have a ScaledObject with multiple triggers - can I use the same TriggerAuthentication object for all triggers? Is this recommended? Or should I create a different TriggerAuthentication for each trigger?

Example with two triggers (azure-queue and azure-servicebus):

```YAML
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: myapp
  namespace: keda
spec:
  cooldownPeriod: 1800
  maxReplicaCount: 10
  minReplicaCount: 2
  pollingInterval: 15
  scaleTargetRef:
    name: myapp
  triggers:
  - authenticationRef:
      name: myapp
    metadata:
      messageCount: "5"
      namespace: ns
      subscriptionName: sub
      topicName: topic
    type: azure-servicebus
  - authenticationRef:
      name: myapp
    metadata:
      accountName: account
      queueLength: "500"
      queueName: queue
    type: azure-queue
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: myapp
  namespace: keda
spec:
  podIdentity:
    provider: azure
```
