### DISCUSSION TITLE
Problem with fetching Azure custom metric through Azure Monitor scaler

### DISCUSSION THREAD

**Discussion by dymitrs** [kedacore/keda#1946] [Q&A / Need Help] [answered]
Hi all, 
Recently we started using the Monitor scaler and we're trying to use some custom metrics to scale our pods.
According to docs and the PR, Custom Metrics are supported after those changes https://github.com/kedacore/keda/pull/1883.

```
  triggers:
  - type: azure-monitor
    metadata:
      resourceURI: Microsoft.Insights/Components/app-insights
      subscriptionId: <...>
      tenantId: <...>
      resourceGroupName: <...>
      metricName: customMetrics/<metric name>
      metricNamespace: azure.applicationinsights
      metricAggregationInterval: "0:3:0"
      metricAggregationType: Count
      targetValue: "{{ .Values.scale_settings.target_value }}"
```
      
The autoscaler works fine for "default" metrics but for my custom one I'm getting this error and it fails - log from Keda operator pod:

```
ERROR   azure_monitor_scaler    error getting azure monitor metric      {"error": "error getting azure monitor metric customMetrics/<metric name>: got metric result for Microsoft.Insights/customMet
rics/<metric name> and aggregate type COUNT without timeseries"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).isScaledObjectActive
        /workspace/pkg/scaling/scale_handler.go:216
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
```

Is anyone using the scaler with custom metrics from Azure Monitor and encountered this issue? 
Maybe I've got something misconfigured.
