### DISCUSSION TITLE
how to increase memory and cpu limit for KEDA?

### DISCUSSION THREAD

**Discussion by subhamkhemka** [kedacore/keda#1988] [General]
Hi

I am currently using 10 queues with KEDA in dev environment.

However I would like to use around 100 queues in production, so i would like to increase the memory limit.

How do I do this ?

Is there any guidelines as well which we can refer while setting the resource limits ?

Thanks & Regards,
Subham

**Comment by tomkerkhove** [comment]
I'm not sure how the amount of queues to monitor relate to the KEDA memory limits, but you can manage it similar to any other Kubernetes workload.

**Comment by JorTurFer** [comment]
If you are using helm to deploy KEDA, the [chart supports it](https://github.com/kedacore/charts/blob/master/keda/values.yaml#L107-L117)
You can specify using somthing like this:
```yaml
resources: 
  limits:
    cpu: 600m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 256Mi
```
