### DISCUSSION TITLE
Azure Monitor Scaler

### DISCUSSION THREAD

**Discussion by Savitha-Amaldev** [kedacore/keda#2006] [Q&A / Need Help] [answered]
I was trying to configure Azure Monitor Scaler for keda autoscaling. In my scaled object I have specified the Clientid and password for the application. In azure portal as well, I can see the clientid , password and tenantid . But after deploying the scaledobject , I'm getting error on keda operator like  no activeDirectoryClientId given. I don't know what went wrong. Can anyone please help me here?

```
 ERROR   controllers.ScaledObject        Failed to ensure HPA is correctly created for ScaledObject      {"ScaledObject.Namespace": "xxxx", "ScaledObject.Name": "azure-monitor-keda-scaledobject", "error": "error getting scaler for trigger #0: error parsing azure monitor metadata: no activeDirectoryClientId given"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:244
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90
2021-08-03T11:41:27.230Z        ERROR   controller      Reconciler error        {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "name": "azure-monitor-keda-scaledobject", "namespace": "xxxx", "error": "error getting scaler for trigger #0: error parsing azure monitor metadata: no activeDirectoryClientId given"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90
```

**Comment by tomkerkhove** [comment, marked as answer]
Sorry to hear, would you mind sharing your ScaledObject please?

**Reply by Savitha-Amaldev** [reply]
Sure..
Please find my scaledobject below:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: azure-monitor-secrets
data:
  activeDirectoryClientId: base 64 encoded client id
  activeDirectoryClientPassword: base 64 encoded client pwd
--
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-monitor-trigger-auth
spec:
  secretTargetRef:
    - parameter: activeDirectoryClientId
      name: azure-monitor-secrets
      key: activeDirectoryClientId
    - parameter: activeDirectoryClientPassword
      name: azure-monitor-secrets
      key: activeDirectoryClientPassword
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-monitor-keda-scaledobject
  namespace: xxxx
spec:
  scaleTargetRef:
    name:  xyz
  pollingInterval: 60 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 2 # Optional. Default: 0
  maxReplicaCount: 20 # Optional. Default: 100
  triggers:
    - type: azure-monitor
      metadata:
       resourceURI: Microsoft.ContainerService/managedClusters/azureMonitorCluster
       tenantId: ****************************************
       subscriptionId: ****************************************
       resourceGroupName: azureMonitor
       metricName: HttpIncomingRequestCount
       metricFilter: namespace eq 'xxxx'
       metricAggregationInterval: "0:1:0"
       metricAggregationType: Count
       targetValue: "50"
```

**Reply by tomkerkhove** [reply]
You need to link your TriggerAuthentication resource: https://keda.sh/docs/2.3/scalers/azure-monitor/#example

Rough example:
```yaml
  - type: azure-monitor
    metadata:
       <redacted>
    authenticationRef:
      name: azure-monitor-trigger-auth
```
