### DISCUSSION TITLE
KEDA does not scale to zero

### DISCUSSION THREAD

**Discussion by rafaelarcanjo** [kedacore/keda#2119] [Q&A / Need Help] [answered]
Hi, I would like some help, KEDA is not scaling to zero. Where can I go wrong? Thanks.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-apache
spec:
  selector:
    matchLabels:
      run: hpa-apache
      #  replicas: 0
  template:
    metadata:
      labels:
        run: hpa-apache
    spec:
      containers:
      - name: hpa-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-apache
  labels:
    run: hpa-apache
spec:
  ports:
  - port: 80
  selector:
    run: hpa-apache
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: hpa-apache
  namespace: default
spec:
  minReplicaCount: 0
  maxReplicaCount: 2
  cooldownPeriod: 5
  pollingInterval: 5

  scaleTargetRef:
    name: hpa-apache
  triggers:
  - type: cpu
    metadata:
      type: "Utilization"
      value: "10"
```

**Comment by tomkerkhove** [comment, marked as answer]
Scale to 0 is not supported for CPU as you can see in the docs:
![image](https://user-images.githubusercontent.com/4345663/134851646-0ddc5011-93d0-4d0c-ba5e-30b578b227f3.png)


https://keda.sh/docs/2.4/scalers/cpu/

**Comment by rafaelarcanjo** [comment]
Thanks for replying, I changed the metrics for Prometheus, now it scales to 0. But now replicas don't go out to 0, could you help me again?
```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  namespace: default
  labels:
    deploymentName: go-prom-app
spec:
  scaleTargetRef:
    deploymentName: go-prom-app
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-service.default.svc.cluster.local:9090
      metricName: access_frequency
      threshold: '3'
      query: sum(rate(http_requests[2m]))
```
