### DISCUSSION TITLE
cron scaler on GKE not scale to zero.

### DISCUSSION THREAD

**Discussion by dammianhr** [kedacore/keda#2153] [Q&A / Need Help] [answered]
HI! I need some help. I'm trying to scale "deployments" to 0 from start to finish but it doesn't work.
The scaler starts at the indicated time but the pods do not update to 0

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject
spec:
  scaleTargetRef:
    name: backoffice
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cron
    metadata:
      timezone: America/Argentina/Buenos_Aires
      start: 35 13 * * *
      end: 40 13 * * *
      desiredReplicas: "0"
```

GKE version: 1.20.10-gke.301 
Keda version: 2.4.0

keda installed with helm.

**Comment by tomkerkhove** [comment, marked as answer]
It's not scaling to 0 because your minimum replica count is set to 1.

You should omit that and try again, normally it should then scale to 0.

Given this is your only trigger, `min` & `max` should be left out imo

**Reply by dammianhr** [reply]
using this configuration and with 1 replica working. at the time where apply the new scaledobject, this scales the deployment to 0, when the cron starts it scales to 1. when cron end, does nothing.

I need to scale from 1 to 0 when cron start and scale up to 1 (original size) when cron end.
but I think I have erratic behavior in this.

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject
spec:
  scaleTargetRef:
    name: backoffice
  triggers:
  - type: cron
    metadata:
      timezone: America/Argentina/Buenos_Aires
      start: 35 13 * * *
      end: 40 13 * * *
      desiredReplicas: "0"
```

```
  Normal  KEDAScalersStarted          2m12s                 keda-operator  Started scalers watch
  Normal  KEDAScaleTargetDeactivated  2m12s                 keda-operator  Deactivated apps/v1.Deployment dev/backoffice from 1 to 0
  Normal  ScaledObjectReady           115s (x2 over 2m12s)  keda-operator  ScaledObject is ready for scaling
  Normal  KEDAScaleTargetActivated    72s                   keda-operator  Scaled apps/v1.Deployment dev/backoffice from 0 to 1
```
