### DISCUSSION TITLE
"On-demand" e2e test execution on PRs

### DISCUSSION THREAD

**Discussion by JorTurFer** [kedacore/keda#2224] [General] [answered]
During the last Community Standup (October 26th), we were talking about that it would be nice if there are any option to run e2e as part of the PR checks. Executing e2e test is slow and requires external resources, so we were talking about the possibility of using commands on the PR itself (from people who have at least written permissions) to trigger those e2e test only if he/she wants.
Also we suggested running a small subset of e2e test instead of the whole suite as a smoke test but following the approach of something manual which anyone who has written permissions should trigger.

I'm trying to figure out if there is any already done solution for this use case and I haven't been able to find any, so I propose using 2 different actions executed in a row to achieve the desired behavior.
- [pull-request-comment-trigger](https://github.com/marketplace/actions/pull-request-comment-trigger)
- [has-permission](https://github.com/marketplace/actions/has-permission)

Do you know about any built-in solution or any GitHub action which already does it? Does this approach make sense for you?

**Comment by zroubalik** [comment]
The very best thing would be to specify which e2e test to run in the trigger, maybe somehow specify the regex that's been set here https://github.com/kedacore/keda/blob/7f619bd2036bec8cf8f8b3e37f13e79b0e5397e6/tests/run-all.sh#L21 ? Maybe I am just halucinating, but that would be awesome. This way we can run just e2e for a scaler that is being added and what not 🔥

**Reply by JorTurFer** [reply]
I think that this could be possible writing our own [Github Action](https://docs.github.com/es/actions/creating-actions/creating-a-docker-container-action). Maybe we can create our own GitHub Action from scratch and match all our requirements, I mean, maybe we can create it and put all things together:
- Check the command
- Check permissions
- Trigger e2e tests

I'm doing the PoC of the first approach, but maybe if we are open to create our own Action, I can create it

**Reply by JorTurFer** [reply]
As a first approach, this could be enough to trigger another action:
```yaml
name: Manual run e2e test

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: khan/pull-request-comment-trigger@master
        id: check-comment
        with:
          trigger: 'e2e'
          reaction: rocket
          prefix_only: true
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Check user permission
        id: check-permission
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run only if user has sufficient permissions
        if: steps.check-comment.outputs.triggered == 'true' && steps.check-permission.outputs.has-permission        
        run: echo "DO THE STUFFS TO RUN E2E TESTS"
        
      - name: Run only if user has NOT sufficient permissions
        if: "! steps.check-permission.outputs.has-permission"
        run: echo "Sorry!"
```

Basically, if someone with writing permissions post a comment that starts with `e2e`, the step `Run only if user has sufficient permissions` will be executed. We can place there all the things that we want
