### DISCUSSION TITLE
Troubleshooting KEDA Selenium Grid v4

### DISCUSSION THREAD

**Discussion by lroque2021** [kedacore/keda#2248] [Q&A / Need Help]
Hello
This is the keda i deployed:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: autoscaler-selenium-chrome
  namespace: NAME
  labels:
    deploymentName: autoscaler-selenium-chrome-node
spec:
  maxReplicaCount: 3
  scaleTargetRef:
    name: selenium-chrome-node
  triggers:
    - type: selenium-grid
      metadata:
        url: 'http://PRIVATEURL/graphql'
        browserName: 'chrome'
```

Keda deployed correctly but scaledobject is not active.
when i make the command "kubectl describe scaledobject"
i have message :scaling is not performed because triggers are not active

thanks for your help
