### DISCUSSION TITLE
How to use Azure Managed Identity in place of storageConnectionFromEnv for Event Hub Trigger

### DISCUSSION THREAD

**Discussion by sanjaydebnath** [kedacore/keda#2284] [Q&A / Need Help]
Hi All, I am trying to add event hub trigger like below but it needs to point to a full storage connection string still while the Event Hub can use Managed Identity. Is there a way to use MSI for this storage account too? In below example, my pods have an env variable called 'AzureWebJobsStorage' with full connection string of a storage account (I want to avoid that).

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-eventhub-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: azureeventhub-function
  triggers:
  - type: azure-eventhub
    metadata:
      storageConnectionFromEnv: AzureWebJobsStorage
      eventHubNamespace: mynamespace
      eventHubName: myhub
    authenticationRef:
        name: trigger-auth-name
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-name
  namespace: default
spec:
  podIdentity:
    provider: Azure
```

**Comment by tomkerkhove** [comment]
@ahmelsayed Do you know?

**Reply by sanjaydebnath** [reply]
This would help to reduce dependency from the full storage connection string (like not managing key rotation etc. anymore). Also KEDA already has MSI for event hub (and other azure resources like storage itself https://keda.sh/docs/2.4/scalers/azure-storage-blob/) using pod identity. If not yet supported, the proposal can be something like below where we can accept the base blob uri and for that we can use the same auth as of the event hub.

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-eventhub-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: azureeventhub-function
  triggers:
  - type: azure-eventhub
    metadata:
      **storageBlobUrl: https://mystorage.blob.core.windows.net**
      eventHubNamespace: mynamespace
      eventHubName: myhub
    authenticationRef:
        name: trigger-auth-name
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-name
  namespace: default
spec:
  podIdentity:
    provider: Azure
```
