### DISCUSSION TITLE
EventHubs Scaler With Dapr - Won't Scale Beyond Single Pod

### DISCUSSION THREAD

**Discussion by peter-alegeus** [kedacore/keda#2295] [Q&A / Need Help]
Good afternoon, I am creating a POC that uses .Net 6, Dapr, and Keda running on a local minikube, deployed via helm chart. The Daprized app is a standard web API used as a pubsub subscriber to eventhubs. The overall app works fine; I can send messages to the subscriber and it can process them, with a 5s delay. I recently added Keda to it and have stumbled a bit; I can't seem to get the deployment for the pubsub subscriber (named dapr-pubsub-keda) to spawn more than a single pod instance. Note that it also does not scale down to 0, other than a single time. Yesterday I applied an update to minikube, the kubernetes version with, and rebooted. When minikube came up my pod had scaled down to 0! I added messages to the queue and it quickly spawned a single pod. I currently have the unprocessedEventThreshold set to 5 and I send anywhere from 50 to 1000 messages, so it should scale past a single pod. I tried adding a failure condition to the spec to go to 3 pods just in case Keda was unsuccessfully pulling info from EventHubs, but since I'm still at a single pod and nothing shows in the log about using the failure condition, I don't think this helped any. I'll happily provide any information that can be of use. For starters, here's the yaml for the ScaledObject: 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: eventhubs-scaledobject-keda
  namespace: default
spec:
  maxReplicaCount: 5
  pollingInterval: 5  # Optional. Default: 30 seconds
  cooldownPeriod:  10 # Optional. Default: 300 seconds
  fallback:
    failureThreshold: 3
    replicas: 3
  scaleTargetRef:
    name: dapr-pubsub-keda
    #envSourceContainerName: dapr-pubsub-poc
  triggers:
    - type: azure-eventhub
      metadata:
        connectionFromEnv: EVENTHUB_CONNECTION
        storageConnectionFromEnv: EVENTHUB_STORAGE_CONNECTION
        eventHubNamespace: alegeus-peter-dapr
        eventHubName: alegeus-peter-dapr-keda
        consumerGroup: dapr-pubsub-keda
        unprocessedEventThreshold: '5'
        blobContainer: peterdaprqueuecontainerkeda
        checkpointStrategy: blobMetadata
---
```

I'm running on Keda v2.4, minikube v1.24.0, k8s version 1.22.3 (client is 1.22.0), and using Dapr 1.3.0.

I've checked the logs of the keda operator and the keda metrics operator, and while I'm new to this nothing in there looks fishy to me. Will happily provide the info within if requested.

Any help would be appreciated, thanks.
