### DISCUSSION TITLE
Azure DevOps scaler issue

### DISCUSSION THREAD

**Discussion by PixelRobots** [kedacore/keda#2323] [Q&A / Need Help]
Currently having issues with Azure pipelines scaledjob.

Yaml is:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: azdevops-scaledjob
  namespace: devops
spec:
  jobTargetRef:
    template:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: agentpool
                  operator: In
                  values:
                  - devops         
        containers:
        - name: azdevops-agent-job
          image: acrurl.io/devopsagent:v5
          imagePullPolicy: Always
          env:
            - name: AZP_URL
              value: https://dev.azure.com/org
            - name: AZP_TOKEN
              value: pattoken
            - name: AZP_POOL
              value: poolname
  pollingInterval: 30
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10   
  scalingStrategy:
    strategy: "default"               
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: "393"
      organizationURLFromEnv: "AZP_URL"
      personalAccessTokenFromEnv: "AZP_TOKEN"
```

Everything deploys ok, but it never starts a job when something is in the queue. I have another agent sat waiting which is disabled so it has an agent, and the pool is not empty.

The scaledjob output looks like this.

```
Spec:
  Failed Jobs History Limit:  5
  Job Target Ref:
    Template:
      Metadata:
        Creation Timestamp:  <nil>
      Spec:
        Affinity:
          Node Affinity:
            Required During Scheduling Ignored During Execution:
              Node Selector Terms:
                Match Expressions:
                  Key:       agentpool
                  Operator:  In
                  Values:
                    devops
        Containers:
          Env:
            Name:             AZP_URL
            Value:            https://dev.azure.com/org
            Name:             AZP_TOKEN
            Value:            pat
            Name:             AZP_POOL
            Value:            aimmsdevaks
          Image:              azurecr.io/devopsagent:v5
          Image Pull Policy:  Always
          Name:               azdevops-agent-job
          Resources:
  Max Replica Count:  10
  Polling Interval:   30
  Scaling Strategy:
    Strategy:                     default
  Successful Jobs History Limit:  5
  Triggers:
    Metadata:
      Organization URL From Env:       AZP_URL
      Personal Access Token From Env:  AZP_TOKEN
      Pool ID:                         393
    Type:                              azure-pipelines
Status:
  Conditions:
    Status:   Unknown
    Type:     Ready
    Message:  Scaling is not performed because triggers are not active
    Reason:   ScalerNotActive
    Status:   False
    Type:     Active
    Status:   Unknown
    Type:     Fallback
Events:
  Type    Reason              Age                  From           Message
  ----    ------              ----                 ----           -------
  Normal  KEDAScalersStarted  112s                 scale-handler  Started scalers watch
  Normal  ScaledJobReady      112s (x2 over 112s)  keda-operator  ScaledJob is ready for scaling
```

As you can see it says ScalerNotActive.

When using a scaled job the HPA is not being created. When using a scaledobject the HPA is created and looks like:

```
Name:                                                                keda-hpa-azure-pipelines-scaledobject
Namespace:                                                           devops
Labels:                                                              app.kubernetes.io/managed-by=keda-operator
                                                                     app.kubernetes.io/name=keda-hpa-azure-pipelines-scaledobject
                                                                     app.kubernetes.io/part-of=azure-pipelines-scaledobject
                                                                     app.kubernetes.io/version=2.4.0
                                                                     scaledobject.keda.sh/name=azure-pipelines-scaledobject
Annotations:                                                         <none>
CreationTimestamp:                                                   Tue, 23 Nov 2021 15:06:09 +0000
Reference:                                                           Deployment/azdevops-deployment
Metrics:                                                             ( current / target )
  "azure-pipelines-queue-org-393" (target average value):  0 / 1
Min replicas:                                                        1
Max replicas:                                                        20
Deployment pods:                                                     1 current / 1 desired
Conditions:
  Type            Status  Reason               Message
  ----            ------  ------               -------
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
  ScalingActive   True    ValidMetricFound     the HPA was able to successfully calculate a replica count from external metric azure-pipelines-queue-org-393(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: azure-pipelines-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  False   DesiredWithinRange   the desired count is within the acceptable range
Events:           <none>
```

No errors showing in keda pod just the following info:

```
2021-11-23T15:26:19.629Z        INFO    scalehandler    Active trigger  {"Scaler": {}, "isTriggerActive": false}
2021-11-23T15:26:19.629Z        INFO    scalehandler    Scaler targetAverageValue       {"Scaler": {}, "targetAverageValue": 1}
2021-11-23T15:26:19.696Z        INFO    scalehandler    QueueLength Metric value        {"Scaler": {}, "queueLength": 0}
2021-11-23T15:26:19.696Z        INFO    scalehandler    Scaler maxValue {"maxValue": 0}
2021-11-23T15:26:19.697Z        INFO    scaleexecutor   Scaling Jobs    {"scaledJob.Name": "azdevops-scaledjob", "scaledJob.Namespace": "devops", "Number of running Jobs": 0}
2021-11-23T15:26:19.697Z        INFO    scaleexecutor   Scaling Jobs    {"scaledJob.Name": "azdevops-scaledjob", "scaledJob.Namespace": "devops", "Number of pending Jobs ": 0}
```

Any ideas?
