### DISCUSSION TITLE
Helm Upgrade Fails for clustertriggerauthentications.keda.sh

### DISCUSSION THREAD

**Discussion by souvikg10** [kedacore/keda#2340] [Q&A / Need Help] [answered]
Hello,
I have tried looking everywhere for this but most point to bug fixes in the latest release
I have installed the latest keda 2.4 in the keda namespace. My scaled-object is installed in a separate namespace and upon 

Helm upgrade, i receive the following error
```
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: CustomResourceDefinition "clustertriggerauthentications.keda.sh" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "rasa-worker": current value is "keda"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "rasa": current value is "keda"
```
My ScaledObject is using credentials from Env
```
        hostFromEnv: QA_REDIS_HOST
        portFromEnv: QA_REDIS_PORT
        passwordFromEnv: QA_REDIS_PASS
```

So i am not sure why clustertriggerauthentication is needed when i don't have a triggerAuthenticationObject, not sure if i need one either

**Comment by tomkerkhove** [comment, marked as answer]
May I ask what you are upgrading to? Because KEDA v2.4 is already the latest version?

**Reply by souvikg10** [reply]
Hi Tom,
I am trying to upgrade my own helm chart actually

**Reply by tomkerkhove** [reply]
There was a breaking change on Helm for v2.2.1 which is documented on https://keda.sh/docs/2.4/troubleshooting/.

This seems very similar, but you've mentioned that you already use KEDA v2.4 so I'm not sure.

**Reply by tomkerkhove** [reply]
I'm not sure how your own Helm chart is trying to change our CRD?

**Reply by souvikg10** [reply]
Keda 2.4 is installed in our cluster. And thus i wanted to upgrade my helm release to include the ScaledObject but that is currently failing. 

My helm chart is installed in a separate namespace while keda is installed in the namespace called keda

**Reply by souvikg10** [reply]
```{{- if .Values.keda.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  labels:
    deploymentName: scaledobject
spec:
  minReplicaCount: {{ .Values.keda.minReplicaCount}}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount}}
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  scaleTargetRef:
    name: worker
  triggers:
    - type: redis
      metadata:
        {{- if eq .Values.worker.environment.ENV_STATE "prod"}}
        hostFromEnv: PROD_REDIS_HOST
        portFromEnv: PROD_REDIS_PORT
        passwordFromEnv: PROD_REDIS_PASS
        {{- else if eq .Values.worker.environment.ENV_STATE "pre_prod"}}
        hostFromEnv: PRE_PROD_REDIS_HOST
        portFromEnv: PRE_PROD_REDIS_PORT
        passwordFromEnv: PROD_REDIS_PASS
        {{- else }}
        hostFromEnv: QA_REDIS_HOST
        portFromEnv: QA_REDIS_PORT
        passwordFromEnv: QA_REDIS_PASS
        {{- end }}
        listName: celery
        listLength: "5"
{{- end }}```

**Reply by souvikg10** [reply]
That is what i added to my helm chart release. I use fromENV credentials too. so i am not sure why it is trying to upgrade the CRDs in a different namespace

**Reply by tomkerkhove** [reply]
I don't see that as well, did you add any CRDs to your own Helm chart or depend on another Helm chart?

**Reply by souvikg10** [reply]
My chart depends on Redis
```
dependencies:
- name: redis
  version: ~10.5.12
  repository: https://charts.bitnami.com/bitnami
  condition: redis.install
```

**Reply by tomkerkhove** [reply]
Did you rename the chart or are you specifying the correct chart?

> key "meta.helm.sh/release-name" must equal "rasa-worker": current value is "keda";

This makes me wonder because it's trying to change release names.

**Reply by souvikg10** [reply]
```
helm upgrade --install keda kedacore/keda --namespace keda -f values.yaml
```

This is what was used to install keda on the keda namespace

**Reply by souvikg10** [reply]
additional labels are also added
```
# Default values for keda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


watchNamespace: ""

podLabels:
  keda: {}
  metricsAdapter: {}
  app: keda
  environment: devops-staging
  service: keda
  team: rasa
  environment2: rasa
  component_type: application


resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi
```
