### DISCUSSION TITLE
Helm upgrade of kind ScaledObject is failing.

### DISCUSSION THREAD

**Discussion by Nitesh-vaidyanath** [kedacore/keda#2356] [Q&A / Need Help]
We are using helm to add scaledobject kind, whenever we do some modification to manifest file it is not getting updating with "helm upgrade" command.

**Comment by tomkerkhove** [comment]
Can you provide some more information please?

**Comment by Nitesh-vaidyanath** [comment]
@tomkerkhove 

This is the new changes made to spec in helm package, after upgrade we are  still seeing minReplicaCount as 2.
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: activity
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: activity
  pollingInterval: 60
  minReplicaCount: 1
  maxReplicaCount: 10
```
After upgrade:
```
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: activity
  pollingInterval: 60
  minReplicaCount: 2
  maxReplicaCount: 100
```
