### DISCUSSION TITLE
Service Bus based KEDA triggered message more than one time.

### DISCUSSION THREAD

**Discussion by atulthummar** [kedacore/keda#2376] [Q&A / Need Help]
Hello Team,

We have implemented Service Bus Based Message Trigger using KEDA and hosted on AKS cluster.
Currently We have configured each service bus message will be executed on each PODs 
For example :
There are Five message triggered at a time then - Five PODs will be run each message.

Here is the Deployment configuration
```yaml
apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: jobprocessor-workerapp-scaler
spec:
  scaleTargetRef:
    name: jobprocessor-workerapp
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  minReplicaCount: 1 
  maxReplicaCount: 100
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: jobqueue
      connectionFromEnv: SERVICEBUS_CONNECTIONSTRING
      namespace: conversion
      **messageCount: '1'**
    authenticationRef:
     name: jobprocessor-workerapp-trigger-auth
```

Now we are facing below issue : 

If in Service Bus has 2 Message passed then two PODs running to execute each message -  Thats fine as per configuration
If In Service Bus has 5 Message passed then five PODs running to execute each message but SOMETIME we face some of the messages run in PODs completed early then other Message that is ALREADY running in another PODs also triggered SECOND time CAUSE ISSUE

Expected behavior - Message should NOT be re triggered to ANY  OF THE FREE PODs IF its already running

Please provide me any input for RESOLVE this issue.

Thanks,
