### DISCUSSION TITLE
What is SERVICEBUS_CONNECTIONSTRING_ENV_NAME

### DISCUSSION THREAD

**Discussion by gauranitai** [kedacore/keda#2380] [Q&A / Need Help]
I am having trouble understanding how to pass the _connectionFromEnv_ that is mentioned here: [Trigger Specification](https://keda.sh/docs/2.4/scalers/azure-service-bus/#trigger-specification). I tried multiple things but I continue to see this error:  

> "error parsing azure service bus metadata: no connection setting given"

I setup a secret with name "myproject-auto-scale". Then I passed that as a value to _connectionFromEnv_ . In my secret I have a label called _connection_ with the value as my actual connection string.

I would appreciate any help on how to correctly configure this.

**Comment by gauranitai** [comment]
Below is an alternate way I ended up using to get it working. But it would still be useful to understand what is _connectionFromEnv_.

```

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: asb-queue-scaledoject-test
  namespace: mynamespace
spec:
  scaleTargetRef:
  	# Deployment that will be autoscaled
    name: mydeployment
  pollingInterval: 30
  minReplicaCount:  1
  maxReplicaCount:  100
  # Default is 300
  cooldownPeriod: 300
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: myqueuename
      messageCount: "5" # default 5
    authenticationRef:
      name: asb-queue-trigger-authentication-test
      
---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: asb-queue-trigger-authentication-test
spec:
  secretTargetRef:
  - parameter: connection
    name: mysecretname
    key: connection #name of the key inside mysecretname
```
