### DISCUSSION TITLE
Composed Scaler

### DISCUSSION THREAD

**Discussion by or-shachar** [kedacore/keda#2431] [Ideas]
KEDA and k8s native HPA are limited in that they can only look at one metric at a time and cannot compose formula on top of multiple metrics.

I think that a "Composed Scaler" that allows to put in a simple formula that references multiple other metrics - can be super useful.

Here's a real-world problem: I have a backend process that consumes "write" tasks from a queue and persists them to DB. My DB has a single writer node that is CPU-bound. A task may implicit varying load on the CPU (depending on the content of the write).

I have 2 relevant metrics to determine the replica count:
```
q := queue-length
cpu := DB-writer CPU utilization
```

Composed metric formula: `ceil((1-cpu) * q)` can promise that replicas would grow if queue is high but avoid growing if CPU is loaded. Right now the only option for me to do it is to create my own service that exposes that metric.

Imagine we had a "Composed Scaler" (/Composite scaler) with a trigger that can be defined like this:
```yaml
triggers:
  - type: composed
    metadata:
      metrics:
        q_length: 
          type: aws-cloudwatch
          metadata:
            namespace: AWS/SQS
            ... # SQS length
        cpu_util:
          type: aws-cloudwatch
          metadata:
            namespace: AWS/Neptune
            ... # neptune writer CPU
      formula: "ceil((1 - $cpu_util) * $q_length)"
      targetMetricValue: "5"
      minMetricValue: "0"

```

This would make Keda a powerful tool not only for collecting external metrics but also for making smart decisions based on multiple conditions.

WDYT?

**Comment by zroubalik** [comment]
This is indeed a good idea, I was thinking about this as well.

We have something like this (less powerful though) implemented for ScaledJobs: https://keda.sh/docs/2.5/concepts/scaling-jobs/#scaledjob-spec

One of my concerns is the `formula`, we will need to come up with something robust and simple how to specify it and validate 🤷‍♂️ 

I'd prefer to not intoduce a new type of scaler, but instead referencing triggers in a separate section in the ScaledObject:

```yaml
scaledObject.spec:
  ...
  mutlipleTriggersCalculation:    ### we should find a better name for this probably
      formula: "ceil((1 - $cpu_util) * $q_length)"
      targetMetricValue: "5"
      minMetricValue: "0"
  triggers:
    - type: aws-cloudwatch
       name: q_length     ### name added here
       metadata:
            namespace: AWS/SQS
            ... # SQS length
    - type: aws-cloudwatch
       name: cpu_util       ### name added here
       metadata:
            namespace: AWS/Neptune
            ... # neptune writer CPU
```
