### DISCUSSION TITLE
Keda + GKE "Unable to read all metrics"

### DISCUSSION THREAD

**Discussion by mfatihaktas** [kedacore/keda#2439] [Q&A / Need Help]
We are experiencing the same issue described [here](https://github.com/kedacore/keda/issues/1852) -- their solution with "firewall rule" was not useful to us.
We are using Keda 2.5.0 in GKE to scale a deployment based on the Google Pub/Sub trigger.
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

Once the subscription queue is non-empty, KEDA scales 0 -> 1, but it does not scale any further while it should.
The status of KEDA-HPA shows the following:
```
status:
  conditions:
  - lastTransitionTime: "2022-01-04T15:01:38Z"
    message: recommended size matches current size
    reason: ReadyForNewScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2022-01-04T15:29:06Z"
    **message: 'the HPA was unable to compute the replica count: unable to get external
      metric ml-models-dev/s0-gcp-ps-xxx-predreq-queue-dev/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:
      xxx-hpa-keda,},MatchExpressions:[]LabelSelectorRequirement{},}:
      unable to fetch metrics from external metrics API: the server could not find
      the descriptor for metric s0-gcp-ps-xxx-predreq-queue-dev:
      googleapi: Error 404: Could not find descriptor for metric ''s0-gcp-ps-xxx-predreq-queue-dev''.,
      notFound'
    reason: FailedGetExternalMetric**
    status: "False"
    type: ScalingActive
  - lastTransitionTime: "2022-01-04T15:01:38Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentMetrics:
  - type: ""
  currentReplicas: 1
  desiredReplicas: 1
```

We could not debug the root cause of this. We would greatly appreciate any help or pointer on how we should go about debugging this.

@yosoku-games-user, we would appreciate if you let us know if this issue is similar to what you had.
