### DISCUSSION TITLE
KEDA scales my Az Function pods to my number of Event Hub partitions

### DISCUSSION THREAD

**Discussion by nansravn** [kedacore/keda#2442] [Q&A / Need Help]
I'm using KEDA to scale Azure Functions (running on AKS) consuming events from Event Hub. I have a conceptual doubt about how to configure properly the pod autoscaler.
- Based on my tests, when I create an Event Hub with 10 partitions, KEDA will scale by default my number of pods running my Azure Function to 10.
- If i have an Event Hub with 20 partitions, KEDA will scale the number of pods to 20.
- How can I force KEDA to start only 1 pod, running my Azure Functions image. I should be able to have only 1 pod consuming from all my 20 Event Hub partitions, right?

This is my manifest:
```
kind: ScaledObject
metadata:
  name: dropai
  labels: {}
spec:
  scaleTargetRef:
    name: dropai
  pollingInterval: 60
  cooldownPeriod: 300
  minReplicaCount: 3
  maxReplicaCount: 20
  triggers:
  - type: azure-eventhub
    metadata:
      direction: in
      eventHubName: evh-newvideos-dev
      cardinality: one
      consumerGroup: $default
      dataType: binary
      connectionFromEnv: EVH_CONNECTION_STRING
      storageConnectionFromEnv: ADLS_CONNECTION_STRING
      unprocessedEventThreshold: '64'
```
