### DISCUSSION TITLE
HPA reports incorrect metric value

### DISCUSSION THREAD

**Discussion by sidprak** [kedacore/keda#2451] [Q&A / Need Help] [answered]
### Report

I used the Cloudwatch scaler. Using kubectl, I can see the correct metric value:
```
% kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/istio-system/s1-aws-cloudwatch-TargetGroup"
{"kind":"ExternalMetricValueList","apiVersion":"external.metrics.k8s.io/v1beta1","metadata":{},"items":[{"metricName":"s1-aws-cloudwatch-TargetGroup","metricLabels":null,"timestamp":"2022-01-06T20:26:09Z","value":"23344"}]}
```

However, the HPA reports a totally different value, sometimes 0 and sometimes something very large. In addition, the HPA does not seem to scale up at all even though the reported value is much higher than the target. See output:
```
% kubectl get hpa -n foo foo
NAME      REFERENCE              TARGETS                MINPODS   MAXPODS   REPLICAS   AGE
foo   Deployment/foo   0/10k (avg), 19%/70%   60        100       60         14m

% kubectl get hpa -n foo foo
NAME      REFERENCE           TARGETS                      MINPODS   MAXPODS   REPLICAS   AGE
foo   Deployment/foo   321567m/10k (avg), 19%/70%   60        100       60         14m
```

### Expected Behavior

I would expect the cloudwatch value to display in the HPA and since the value is much higher than the target.

### Actual Behavior

Incorrect value and no scaling.

### Steps to Reproduce the Problem

Create ScaledObject like below:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: foo
  namespace: foo-ns
spec:
  scaleTargetRef:
    name: foo
  pollingInterval: 30
  minReplicaCount: 60
  maxReplicaCount: 100
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "70"
  - type: aws-cloudwatch
    metadata:
      namespace: AWS/ApplicationELB
      dimensionName: TargetGroup
      dimensionValue: targetgroup/foo
      metricName: RequestCountPerTarget
      targetMetricValue: "10000"
      minMetricValue: "0"
      identityOwner: operator
      awsRegion: us-west-2
      metricStatPeriod: "60"
      metricStat: "Sum"
      metricCollectionTime: "120"
```

### Logs from KEDA operator

These logs are repeated:
```
2022-01-06T20:59:39.422Z	DEBUG	controller.scaledobject	ScaledObject is defined correctly and is ready for scaling	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "foo", "namespace": "foo-ns"}
2022-01-06T20:59:55.160Z	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "foo", "namespace": "foo-ns"}
2022-01-06T20:59:55.160Z	DEBUG	controller.scaledobject	Parsed Group, Version, Kind, Resource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "foo", "namespace": "foo-ns", "GVK": "apps/v1.Deployment", "Resource": "deployments"}
```

### KEDA Version

2.5.0

### Kubernetes Version

1.18

### Platform

Amazon Web Services

### Scaler Details

Cloudwatch
