### DISCUSSION TITLE
scaling is disabled since the replica count of the target is zero

### DISCUSSION THREAD

**Discussion by lokesh-wise** [kedacore/keda#2452] [Q&A / Need Help]
Hi

I'm new to Keda. I'm trying to use Kinesis stream autoscaler and here's my configuration

```
apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
  namespace: v2-dev1
data:
  AWS_ACCESS_KEY_ID: <encoded in base64>
  AWS_SECRET_ACCESS_KEY: <encode in base64>
--- 
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: v2-dev1
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID     # Required.
    name: test-secrets       # Required.
    key: AWS_ACCESS_KEY_ID        # Required.
  - parameter: awsSecretAccessKey # Required.
    name: test-secrets        # Required.
    key: AWS_SECRET_ACCESS_KEY    # Required.
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: qldb-aws-kinesis-stream-scaledobject
  namespace: v2-dev1
spec:
  scaleTargetRef:
    name: qldb-consumer-service-deployment
  triggers:
    - type: aws-kinesis-stream
      authenticationRef:
        name: keda-trigger-auth-aws-credentials
      metadata:
        # Required
        streamName: qldb-stream-dev
        # Required
        awsRegion: "us-west-2"
        # Optional: Default: 2
        shardCount: "2"
        minMetricValue: "1"

```

Soon after applying this configuration my pod scales to 0. Any idea, why so? These are the relevant output - 

```
>  k describe hpa keda-hpa-qldb-aws-kinesis-stream-scaledobject -n v2-dev1                                                             

Name:                                                  keda-hpa-qldb-aws-kinesis-stream-scaledobject
Namespace:                                             v2-dev1
Labels:                                                app.kubernetes.io/managed-by=Helm
                                                       app.kubernetes.io/name=keda-hpa-qldb-aws-kinesis-stream-scaledobject
                                                       app.kubernetes.io/part-of=qldb-aws-kinesis-stream-scaledobject
                                                       app.kubernetes.io/version=2.5.0
                                                       scaledobject.keda.sh/name=qldb-aws-kinesis-stream-scaledobject
Annotations:                                           <none>
CreationTimestamp:                                     Fri, 07 Jan 2022 14:33:31 +0530
Reference:                                             Deployment/qldb-consumer-service-deployment
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 80%
Min replicas:                                          1
Max replicas:                                          100
Deployment pods:                                       0 current / 0 desired
Conditions:
  Type           Status  Reason             Message
  ----           ------  ------             -------
  AbleToScale    True    SucceededGetScale  the HPA controller was able to get the target's current scale
  ScalingActive  False   ScalingDisabled    scaling is disabled since the replica count of the target is zero
Events:          <none>
```

```
╰─ k describe ScaledObject qldb-aws-kinesis-stream-scaledobject -n v2-dev1                                                              ─╯
Name:         qldb-aws-kinesis-stream-scaledobject
Namespace:    v2-dev1
Labels:       app.kubernetes.io/managed-by=Helm
              scaledobject.keda.sh/name=qldb-aws-kinesis-stream-scaledobject
Annotations:  meta.helm.sh/release-name: v2-dev1-qldb-consumer-service
              meta.helm.sh/release-namespace: v2-dev1
API Version:  keda.sh/v1alpha1
Kind:         ScaledObject
Metadata:
  Creation Timestamp:  2022-01-07T09:03:31Z
  Finalizers:
    finalizer.keda.sh
  Generation:        1
  Resource Version:  90023303
  Self Link:         /apis/keda.sh/v1alpha1/namespaces/v2-dev1/scaledobjects/qldb-aws-kinesis-stream-scaledobject
  UID:               6eeb0e9d-5859-4cfe-b4dc-7396c91d25e2
Spec:
  Scale Target Ref:
    Name:  qldb-consumer-service-deployment
  Triggers:
    Authentication Ref:
      Name:  keda-trigger-auth-aws-credentials
    Metadata:
      Aws Region:        us-west-2
      Min Metric Value:  1
      Shard Count:       2
      Stream Name:       qldb-stream-dev
    Type:                aws-kinesis-stream
Status:
  Conditions:
    Message:               ScaledObject is defined correctly and is ready for scaling
    Reason:                ScaledObjectReady
    Status:                True
    Type:                  Ready
    Message:               Scaling is not performed because triggers are not active
    Reason:                ScalerNotActive
    Status:                False
    Type:                  Active
    Status:                Unknown
    Type:                  Fallback
  Original Replica Count:  1
  Scale Target GVKR:
    Group:            apps
    Kind:             Deployment
    Resource:         deployments
    Version:          v1
  Scale Target Kind:  apps/v1.Deployment
Events:
  Type    Reason                      Age                    From           Message
  ----    ------                      ----                   ----           -------
  Normal  KEDAScalersStarted          8m35s                  keda-operator  Started scalers watch
  Normal  ScaledObjectReady           8m35s (x2 over 8m35s)  keda-operator  ScaledObject is ready for scaling
  Normal  KEDAScaleTargetDeactivated  8m35s                  keda-operator  Deactivated apps/v1.Deployment v2-dev1/qldb-consumer-service-deployment from 1 to 0

```
