### DISCUSSION TITLE
Unable to get Keda working with AWS SQS queue using access key and secret

### DISCUSSION THREAD

**Discussion by vnmnm** [kedacore/keda#2489] [Q&A / Need Help] [answered]
I deployed Keda using Helm as described in the documentation.

I have a sample app that dequeues messages from AWS SQS queue and processes them. Its deployment yaml file is as below. I am deploying this in local Kubernetes cluster within the namespace Keda. I want to scale this deployment with the SQS queue volume.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqsmessageprocessor-deployment
  namespace: keda
  labels:
    app: sqs-message-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqs-message-processor
  template:
    metadata:
      labels:
        app: sqs-message-processor
    spec:
      containers:
        - name: sqs-message-processor
          image: sqsmessageprocessor:latest
          imagePullPolicy: Never
```
Below is the yaml file for my Keda ScaledObject that I used as is from this [link](https://keda.sh/docs/2.5/scalers/aws-sqs/#scaling-a-deployment-using-iam-users).
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: keda
data:
  AWS_ACCESS_KEY_ID: {base64_encoded_key}
  AWS_SECRET_ACCESS_KEY: {base64_encoded_secret}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: keda
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID     # Required.
    name: aws-secrets            # Required.
    key: AWS_ACCESS_KEY_ID        # Required.
  - parameter: awsSecretAccessKey # Required.
    name: aws-secrets            # Required.
    key: AWS_SECRET_ACCESS_KEY    # Required.
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: keda
spec:
  scaleTargetRef:
    name: sqsmessageprocessor-deployment
  pollingInterval: 2
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: https://sqs.{region}.amazonaws.com/{acocuntId}/{queue-name}
      queueLength: "1"
      awsRegion: "region"
```
I see below error in the Keda operator logs.

> E0117 10:45:56.943191       1 provider.go:124] keda_metrics_adapter/provider "msg"="error getting metric for scaler" "error"="error parsing SQS queue metadata: awsAccessKeyID not found"  "scaledObject.Name"="aws-sqs-queue-scaledobject" "scaledObject.Namespace"="keda" "scaler"={}

I tried giving plain text (not base64 encoded) access key and secret. Even then I get the same error. I have everything deployed to the same namespace called keda.

Not sure what I am missing here. Can someone please help?
