### DISCUSSION TITLE
Getting "error parsing cloudwatch metadata: awsAccessKeyID not found" even though I'm using a TriggerAuthentication

### DISCUSSION THREAD

**Discussion by paul-civitas** [kedacore/keda#2616] [Q&A / Need Help] [answered]
This is version 2.4.

I have a ScaledObject with the sepc:

```yaml
spec:
  fallback:
    failureThreshold: 3
    replicas: 6
  scaleTargetRef:
    name: my-deployment-name
  triggers:
    - authenticationRef:
        name: my-trigger-auth-name
      metadata:
        awsRegion: us-east-1
        dimensionName: QueueName
        dimensionValue: my-queue-name
        metricName: ApproximateAgeOfOldestMessage
        minMetricValue: '0'
        namespace: AWS/SQS
        targetMetricValue: '30'
      type: aws-cloudwatch
```

I have a TriggerAuthentication that isn't throwing any error, it has the name "my-trigger-auth-name" and the spec:
```yaml
spec:
  podIdentity:
      provider: aws-kiam
```

However I get the error: "error parsing cloudwatch metadata: awsAccessKeyID not found"

But I'm not trying to use an access key to authenticate here, so why am I still getting this error?
