### DISCUSSION TITLE
Keda-operator cannot create KafkaScaledObject when using TLS due to Kafka client error "client has run out of available brokers to talk to (Is your cluster reachable?)"

### DISCUSSION THREAD

**Discussion by michelb-ciandt** [kedacore/keda#2636] [Q&A / Need Help]
Hi guys,

I know that it seems it is similar to this issue(#1764 ) but unfortunately not.

We are trying to setup HPA on AWS EKS cluster using Keda with AWS MSK(Kafka) protected by TLS, we're getting the below error
`error creating kafka client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)`

Important the below scenarios are working:
- AWS EKS + Producer APP + AWS MSK + TLS
- AWS EKS + Producer APP + KEDA

However, when we configure KEDA + TLS it is not working

**Details:**
- EKS version: 1.8
- Keda version: 2.4.0 even using 2.6.1 it is failing
- AWS MSK version: 2.2.1

**AWS MSK TLS Config:**
![ksnip_20220215-004852](https://user-images.githubusercontent.com/76108868/153989882-94d4b3fa-0d53-40da-a926-e25ce84068a4.png)

Here is the `ScaledObject` spec,

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: test-ci-debug
  labels:
    deploymentName: kafka-consumer-deployment
spec:
  scaleTargetRef:
    name: kafka-consumer-deployment
  pollingInterval: 5
  minReplicaCount: 0 
  maxReplicaCount: 3
  triggers:
  - type: kafka
    metadata:      
      bootstrapServers: b-3.AMAZON_ADRESS_HERE.kafka.us-east-1.amazonaws.com:9094,b-2.AMAZON_ADRESS_HERE.us-east-1.amazonaws.com:9094,b-1.AMAZON_ADRESS_HERE.kafka.us-east-1.amazonaws.com:9094
      consumerGroup: keda_group_id  
      topic: test.keda
      lagThreshold: "10"
      offsetResetPolicy: earliest
      allowIdleConsumers: "true"      
      version: 2.2.1
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
```

**_Note: I just replaced the AWS link to AMAZON_ADRESS_HERE_**

**Here is one of the tentative config for the Keda trigger auth Kafka credential file:**
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: test-ci-debug
spec:
  secretTargetRef:
  - parameter: tls
    name: keda-kafka-secrets
    key: tls      
  - parameter: ca
    name: keda-kafka-secrets
    key: ca
```

any idea guys?

**Comment by michelb-ciandt** [comment]
@Dorn-, @zroubalik, @tomkerkhove do you have any idea? Light here.

**Reply by zroubalik** [reply]
Hard to tell, unfortunately I don't have any experience with AWS MSK. Have you tried to specify CA?

We are using Sarama Go client for Kafka. You can try to check that. Or you can try to create a simple Sarama client for testing purposes to find out what is the right configuration.
Quick googling gave me this: https://github.com/Shopify/sarama/issues/2087

**Reply by michelb-ciandt** [reply]
Thank you @zroubalik, let me take a look, I will share the details.

**Reply by michelb-ciandt** [reply]
@zroubalik, sorry I fixed the Keda trigger auth file, yes We tried specifying CA,
AWS MSK is supposed to be an Apache Kafka managed by AWS I don't think they have big differences.

I could not create a Sarama client for testing yet, and the documentation is not helping too much on this.

**Comment by stv-io** [comment]
if this is of any help I have just gotten the below to work

```
---
  apiVersion: v1
  kind: Secret
  metadata:
    name: keda-kafka-secrets
    namespace: dummy-namespace
  data:
    tls: "ZW5hYmxlCg==" # enable
  type: Opaque
  ---
  apiVersion: keda.sh/v1alpha1
  kind: TriggerAuthentication
  metadata:
    name: keda-trigger-auth-kafka-credential
    namespace: dummy-namespace
  spec:
    secretTargetRef:
    - parameter: tls
      name: keda-kafka-secrets
      key: tls      
  ---  
  apiVersion: keda.sh/v1alpha1
  kind: ScaledObject
  metadata:
    name: keda-kafka-scaled-object-test
    namespace: dummy-namespace
  spec:
    scaleTargetRef:
      name: dummy-namespace-arm-dummy-namespace
    triggers:
    - type: kafka
      metadata:
        bootstrapServers: b-1.dummy-kafka-staging.1sb0eb.c1.kafka.us-west-2.amazonaws.com:9094
        consumerGroup: dummyConsumerGroup
        topic: dummy-topic
        lagThreshold: '50'
      authenticationRef:
        name: keda-trigger-auth-kafka-credential
```

kafka 2.7.0 (MSK)

<img width="831" alt="image" src="https://user-images.githubusercontent.com/6401588/168842750-2e443208-3641-4215-af61-286e9467ba90.png">


keda 2.7.1
