### DISCUSSION TITLE
unable to fetch metrics from external metrics API: error when getting scalers no scaler found for type: aws-dynamodb

### DISCUSSION THREAD

**Discussion by samueleresca** [kedacore/keda#2671] [Q&A / Need Help]
Hi,

I'm building the AWS DynamoDB scaler #2486. I'm trying to run keda locally using the `make run` command. The project runs correctly activates/deactivates the scaler correctly, but the metric is not sent out to the HPA

Below is the error, I see when I run the ` kubectl describe hpa` command:

```
kubectl describe hpa keda-hpa-aws-dynamodb-table-scaledobject
Warning: autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
Name:                                                         keda-hpa-aws-dynamodb-table-scaledobject
Namespace:                                                    default
Labels:                                                       app=agent
                                                              app.kubernetes.io/managed-by=keda-operator
                                                              app.kubernetes.io/name=keda-hpa-aws-dynamodb-table-scaledobject
                                                              app.kubernetes.io/part-of=aws-dynamodb-table-scaledobject
                                                              app.kubernetes.io/version=main
                                                              deploymentName=agent
                                                              scaledobject.keda.sh/name=aws-dynamodb-table-scaledobject
Annotations:                                                  <none>
CreationTimestamp:                                            Thu, 24 Feb 2022 22:47:38 +0000
Reference:                                                    Deployment/nginx-deployment
Metrics:                                                      ( current / target )
  "s0-aws-dynamodb-keda-events-sort" (target average value):  <unknown> / 1
Min replicas:                                                 1
Max replicas:                                                 100
Deployment pods:                                              1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric default/s0-aws-dynamodb-keda-events-sort/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: aws-dynamodb-table-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: error when getting scalers no scaler found for type: aws-dynamodb
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetExternalMetric       13s (x5 over 74s)  horizontal-pod-autoscaler  unable to get external metric default/s0-aws-dynamodb-keda-events-sort/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: aws-dynamodb-table-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: error when getting scalers no scaler found for type: aws-dynamodb
  Warning  FailedComputeMetricsReplicas  13s (x5 over 74s)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get s0-aws-dynamodb-keda-events-sort external metric: unable to get external metric default/s0-aws-dynamodb-keda-events-sort/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: aws-dynamodb-table-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: error when getting scalers no scaler found for type: aws-dynamodb
```

Below is the configuration that I'm using to test everything locally:

```
apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
data:
  AWS_ACCESS_KEY_ID: "..." # Required.
  AWS_SECRET_ACCESS_KEY: "..." # Required.
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: default
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID     # Required.
    name: test-secrets            # Required.
    key: AWS_ACCESS_KEY_ID        # Required.
  - parameter: awsSecretAccessKey # Required.
    name: test-secrets            # Required.
    key: AWS_SECRET_ACCESS_KEY    # Required.
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-dynamodb-table-scaledobject
  namespace: default
  labels:
    app: agent
    deploymentName: agent 
spec:
  scaleTargetRef:
    name: nginx-deployment
  maxReplicaCount: 100             # Optional. Default: 100
  triggers:
    - type: aws-dynamodb
      authenticationRef:
        name: keda-trigger-auth-aws-credentials
      metadata:
        awsRegion: eu-west-2
        tableName: keda-events-sort
        expressionAttributeNames: '{ "#k" : "event_type"}'
        keyConditionExpression: "#k = :key"
        expressionAttributeValues: '{ ":key" : {"S":"scaling_event"}}'
        targetValue: "1"
---
```
