### DISCUSSION TITLE
Help needed - Keda doesn't scale up

### DISCUSSION THREAD

**Discussion by arsenelee** [kedacore/keda#2873] [Q&A / Need Help] [answered]
Hi,

I'm using Keda version 2.6.1.

I set the lagThreshold to 5. I tried to produce messages on the topic and have a slower consumer. I checked the Kafka lag and the topic have  1000+ messages not consumed.

However, I don't see the pod scale up at all. 

I checked the operator and metric-api logs. The logs don't have any errors. How can I debug the issue and move forward?

Helm Manifest
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject-entitlement-broker
  namespace:
  labels:
    app: entitlement-broker
    deploymentName: entitlement-broker
spec:
  scaleTargetRef:
    name: entitlement-broker
  pollingInterval: 60
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 100
  fallback:
    failureThreshold: 3
    replicas: 3
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: pkc-43n10.us-central1.gcp.confluent.cloud:9092
        consumerGroup: entitlement-broker
        topic: acx.entitlement-broker.keda-test
        lagThreshold: "5"
        offsetResetPolicy: latest
      authenticationRef:
        name: keda-trigger-auth-kafka-credential
```
