### DISCUSSION TITLE
Unable to scale out based on an Azure Service Bus using KEDA

### DISCUSSION THREAD

**Discussion by jitendrabehera2** [kedacore/keda#2877] [Q&A / Need Help]
Hi 
I am trying to set a scaling rules in Azure Container Apps using KEDA.
I followed the tutorial here:
https://www.codit.eu/blog/scaling-apps-with-kubernetes-based-event-driven-autoscaling-keda/?country_sel=be

But after insert message in my azure subscription it not scaled up. Please help me on this.

**Specifications**

1. **KEDA Version: 2.6
2. Platform & Version: Windows 10, Docker Desktop Kubernetes cluster**

**deploy-order-processor.yml**

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  labels:
    app: order-processor
data:
  SERVICEBUS_QUEUE_CONNECTIONSTRING: XXXXXXXXXXXXXXXXXXX
  
---
  
kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-processor
  labels:
    app: order-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: order-processor
    spec:
      containers:
        - name: order-processor
          image: myapps:latest
          env:
            - name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
              valueFrom:
                secretKeyRef:
                  name: order-secrets
                  key: SERVICEBUS_QUEUE_CONNECTIONSTRING
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
spec:
  podIdentity:
    provider: azure


---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prism-processor-scaler
  namespace: prism-akscontainer
  labels:
    app: order-processor
    deploymentName: order-processor
spec:
  scaleTargetRef:
    name: order-processor
  minReplicaCount: 1  # We don't want pods if the queue is empty
  maxReplicaCount: 5  # We don't want to have more than 5 replicas
  triggers:
  - type: azure-servicebus
    metadata:
      topicName: prismcoretopic
      subscriptionName: QC_GA_DADE_Subscription
      connection: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
      messageCount: '5'
      pollingInterval: '30'
      cooldownPeriod: '300'
```
