### DISCUSSION TITLE
EKS Error: NoCredentialProviders: no valid providers in chain

### DISCUSSION THREAD

**Discussion by askkhan84** [kedacore/keda#2912] [Q&A / Need Help] [answered]
I am deploying Keda 2.6.1 on EKS 1.21. I installed using helm charts. I want to scale my deployment using AWS SQS queue length. I have annotated the keda-operator service account with the iam role:
```
Name:                keda-operator
Namespace:           keda
Labels:              app.kubernetes.io/component=operator
                     app.kubernetes.io/instance=keda
                     app.kubernetes.io/managed-by=Helm
                     app.kubernetes.io/name=keda-operator
                     app.kubernetes.io/part-of=keda-operator
                     app.kubernetes.io/version=2.6.1
                     helm.sh/chart=keda-2.6.2
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/container-aod-sa
                     eks.amazonaws.com/sts-regional-endpoints: true
                     meta.helm.sh/release-name: keda
                     meta.helm.sh/release-namespace: keda
Image pull secrets:  <none>
Mountable secrets:   keda-operator-token-xtfxx
Tokens:              keda-operator-token-xtfxx
Events:              <none>
```

Here is my code for TriggerAuthentication and Scaledobject. I have tried setting identityOwner to pod and operator but same error. I can confirm that the pod service account has the right AWS permissions and can access AWS services:
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: container-aod
spec:
  podIdentity:
    provider: aws-eks # or aws-eks when using IRSA
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: container-aod
spec:
  scaleTargetRef:
    name: secret-scanning
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: https://sqs.ap-southeast-2.amazonaws.com/111111111111/container-aod-q
      queueLength: "1"
      awsRegion: "ap-southeast-2"
      #identityOwner: operator
```

When I check the logs for the Keda operator, I get this error:
```
1.65003133568383e+09    INFO    controller.scaledobject Reconciling ScaledObject        {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "aws-sqs-queue-scaledobject", "namespace": "container-aod"}
1.6500313473852682e+09  ERROR   scalehandler    Error getting scale decision    {"scaledobject.Name": "aws-sqs-queue-scaledobject", "scaledObject.Namespace": "container-aod", "scaleTarget.Name": "secret-scanning", "error": "NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:149
1.6500313773838859e+09  ERROR   scalehandler    Error getting scale decision    {"scaledobject.Name": "aws-sqs-queue-scaledobject", "scaledObject.Namespace": "container-aod", "scaleTarget.Name": "secret-scanning", "error": "NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:149
1.6500314074206955e+09  ERROR   scalehandler    Error getting scale decision    {"scaledobject.Name": "aws-sqs-queue-scaledobject", "scaledObject.Namespace": "container-aod", "scaleTarget.Name": "secret-scanning", "error": "NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
```
Here is my deployment yaml file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-scanning
  namespace: container-aod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-scanning
  template:
    metadata:
      labels:
        app: secret-scanning
    spec:
      serviceAccountName: container-aod-sa
      containers:
        - name: secret-scanning
          image: myrepo/secret_scanning:latest
```

I am not sure what am I missing!
