### DISCUSSION TITLE
keda scaling

### DISCUSSION THREAD

**Discussion by shyam-ks** [kedacore/keda#2937] [Q&A / Need Help]
``` 
spec:
  cooldownPeriod: 300
  maxReplicaCount: 5
  minReplicaCount: 2
  pollingInterval: 600
  scaleTargetRef:
    kind: StatefulSet
    name: compute-svc
  triggers:
    - metadata:
        enableTLS: 'true'
        host: redis-tls.redis.cache.windows.net
        listLength: '4'
        listName: 'kpi:pending'
        passwordFromEnv: REDIS_PASSWORD
        port: '63
```
This is my configuration for redis stream keda scaleset config. If my list length is above 4, pods can scale up to 5. Please help me with following queries
 - if the list length goes up to 12 and comes back to 4, will keda scales down the number of pods to 2 which is the min replica count?
 - if the list length goes up to 12 keda scales up number of pods and i have configured HPA (outside keda) to scaled-down based on CPU utilization, what is the expected behavior? 
 Thanks in advance.
