### DISCUSSION TITLE
Prometheus threshold semantics

### DISCUSSION THREAD

**Discussion by kefik** [kedacore/keda#3035] [Q&A / Need Help] [answered]
Hi! Thanks a lot for Keda! 

I'm facing a scaling issue with the following scaledobject
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: xxx
  namespace: some-namespace
  labels:
    deploymentName: xxx
spec:
  minReplicaCount: 1
  maxReplicaCount: 20
  pollingInterval: 60
  scaleTargetRef:
    kind: Deployment
    name: xxx
  triggers:
  - type: prometheus
    metadata:
      serverAddress: correct_address
      metricName: correct_metric_name
      threshold: '1'
      query: sum(correct_metric_spec)
      namespace: some-namespace
```

I don't quite understand the 'threshold' semantics. My initial thought was that the 
`number of replicas == round_down(metric / threshold)`

However that seems to hold only up to the metric value of 11, then if there are 11 running replicas and the metric is 12.1, HPA reports 1.091/1 and refuses to scale to number of replicas 12.

Appreciate any thoughts here! Thanks!

EDIT

Keda revision is 2.6.2
Here is a sequence of readings how the metric is translating to HPA value
```
Replicas	Metric		HPA
1		1		1/1
1		2.1		2/1 -> scale up
2		3.1		1500m/1 -> scale up
3		3.1 		1/1
4		4.1 		1334m/1 -> scale up
4 		5.1 		1200m/1 -> scale up
5 		6.1 		1200m/1 -> scale up
6		6.1 		1167m/1 -> scale up
7 		7.1 		1143m/1 -> scale up
8 		8.1 		1/1
8		9.1 		1125m/1 -> scale up
9		9.1 		1/1
9		10.1 		1112m/1 -> scale up
10 		10.1 		1/1
10 		11.1 		1100m/1 -> scale up
11  		11.1 		1/1
11 		12.1 		1091m/1 -> NOT scaling up
```
