### DISCUSSION TITLE
ScaledObject cooldownPeriod semantics

### DISCUSSION THREAD

**Discussion by kefik** [kedacore/keda#3036] [Q&A / Need Help] [answered]
Hi! I'm fighting scaledobject definition using Prometheus trigger.
Keda revision is 2.6.2 and I'm having a problem with `cooldownPeriod` spec. 
What is its semantics? Originally I thought that no scaling may take place for `cooldownPeriod` of time (in seconds?).
However that does not seem to be the case.

My scaledobject manifest is:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: xxx
  namespace: some-namespace
  labels:
    deploymentName: xxx
spec:
  minReplicaCount: 1
  maxReplicaCount: 20
  pollingInterval: 15
  cooldownPeriod: 60
  scaleTargetRef:
    kind: Deployment
    name: xxx
  triggers:
  - type: prometheus
    metadata:
      serverAddress: correct_address
      metricName: correct_metric_name
      threshold: '1'
      query: sum(correct_metric_spec)
      namespace: some-namespace
```

Here are HPA readings
```
05-11-22 16-04-04
NAME                                      REFERENCE                      TARGETS     MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-manager-1-scaledobject   Deployment/manager-1   2/1 (avg)   1         20        1          3m6s
05-11-22 16-04-15
NAME                                      REFERENCE                      TARGETS     MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-manager-1-scaledobject   Deployment/manager-1   1/1 (avg)   1         20        2          3m16s
05-11-22 16-04-25
NAME                                      REFERENCE                      TARGETS     MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-manager-1-scaledobject   Deployment/manager-1   1/1 (avg)   1         20        2          3m26s
05-11-22 16-04-35
NAME                                      REFERENCE                      TARGETS     MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-manager-1-scaledobject   Deployment/manager-1   1/1 (avg)   1         20        2          3m37s
05-11-22 16-04-46
NAME                                      REFERENCE                      TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-manager-1-scaledobject   Deployment/manager-1   1500m/1 (avg)   1         20        2          3m47s
05-11-22 16-04-56
NAME                                      REFERENCE                      TARGETS     MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-manager-1-scaledobject   Deployment/manager-1   1/1 (avg)   1         20        3          3m58s
```

At time (HH-MM-SS) 16-04-15 scale-up from 1 to 2 replica occurred, here I would expect nothing will change for `cooldownPeriod` of time. But then another scale-up occurred 16-04-56, which is only 41s away from previous scale up, even if I take script reporting period into an account (10s) that would be 51s away from the last scale up, which is still bigger then `cooldownPeriod` which was set to 60.

Any thoughts are appreciated.
