### DISCUSSION TITLE
ScaledJob is not working but ScaledObject does with pod idenetity

### DISCUSSION THREAD

**Discussion by darkmatter18** [kedacore/keda#3044] [Q&A / Need Help]
My ScaledJob configuration looks something like this

```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-service
  namespace: ml
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: ml-heuristics
  namespace: ml
spec:
  jobTargetRef:
    parallelism: 1 # [max number of desired pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    completions: 1 # [desired number of successfully finished pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    activeDeadlineSeconds: 600 # Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
    backoffLimit: 6
    template:
      metadata:
        labels:
          app: ml-heuristics
          aadpodidbinding: aad-pod-identity
      spec:
        containers:
        - name:  ml-heuristics
          image:  <image>
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
          - name: SERVICE_BUS_CONNECTION_STR
            value: <env1>
          - name: SERVICE_BUS_QUEUE_NAME
            value: <env2>
        restartPolicy: Never
  pollingInterval: 30                         # Optional. Default: 30 seconds
  successfulJobsHistoryLimit: 10              # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 10                  # Optional. Default: 100. How many failed jobs should be kept.
  maxReplicaCount: 5                          # Optional. Default: 100
  scalingStrategy:
    strategy: "custom"                        # Optional. Default: default. Which Scaling Strategy to use. 
    customScalingQueueLengthDeduction: 1      # Optional. A parameter to optimize custom ScalingStrategy.
    customScalingRunningJobPercentage: "0.5"  # Optional. A parameter to optimize custom ScalingStrategy.
  triggers:
  - type: azure-servicebus
    metadata:
      namespace: <namespace>
      queueName: <queue>
      messageCount: '5'
    authenticationRef:
      name: trigger-auth-service
```

My ScaledObejct configuration looks like this
```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-service-bus
  namespace: ml
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: iotcamera-scaler
  namespace: ml
spec:
  scaleTargetRef:
    name: ml-heuristics
  minReplicaCount: 0
  maxReplicaCount: 10
  
  triggers:
  - type: azure-servicebus
    metadata:
      namespace: <namespace>
      queueName: <queue>
      messageCount: '5'
    authenticationRef:
      name: trigger-auth-service-bus
```

Here is the deployment for the scaledObject
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ml-heuristics
  namespace: ml
  labels:
    app:  ml-heuristics
spec:
  selector:
    matchLabels:
      app: ml-heuristics
  replicas: 0
  template:
    metadata:
      labels:
        app: ml-heuristics
        aadpodidbinding: aad-pod-identity
    spec:
      containers:
      - name:  ml-heuristics
        image:  <image>
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: SERVICE_BUS_CONNECTION_STR
          value: <env1>
        - name: SERVICE_BUS_QUEUE_NAME
          value: <env2>
```

The pod identity is set up properly and the `ScaledObject` is working like a charm. But the ScaledJob is not working at all.

When I inspect the logs from the `keda-opeator` pod, I got something like this

```bash
1.6523586471186104e+09	INFO	controller.sazure_servicebus_scalercaledjob	Initializing Scaling logic according to ScaledJob Specification	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob", "name": "ml-heuristics", "namespace": "ml"}
1.652358647118849e+09	ERROR	azure_servicebus_scaler	error	{"error": "Get \"http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fservicebus.azure.net%2F\": context canceled"}
github.com/kedacore/keda/v2/pkg/scalers.(*azureServiceBusScaler).IsActive
	/workspace/pkg/scalers/azure_servicebus_scaler.go:177
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).getScaledJobMetrics
	/workspace/pkg/scaling/cache/scalers_cache.go:257
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledJobActive
	/workspace/pkg/scaling/cache/scalers_cache.go:124
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:286
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149
```
Please help me resolve the issue. Thanks a lot
