### DISCUSSION TITLE
How to restrict Azure Kubernetes Service - Node to schedule one POD per Node ?

### DISCUSSION THREAD

**Discussion by atulthummar** [kedacore/keda#3058] [Q&A / Need Help] [answered]
Hi 

How to restrict Azure Kubernetes Service - Node to schedule one POD per Node ? OR Schedule One POD per Core for processing.

Currently I am using KEDA with Service Bus per message scaling how to achieve with per Node one Pods should be schedule.

```yaml
apiVersion: keda.sh/v1alpha1 
kind: ScaledJob
metadata:
  name: usernode-workerapp-scaler
spec:
  jobTargetRef:
    template:
      spec:
        nodeSelector:
          beta.kubernetes.io/os: linux
        containers:
          - name: usernode-workerapp
            image: test.azurecr.io/generatorv1:latest_gb
            imagePullPolicy: Always
            env:
            - name: SERVICEBUS_CONNECTIONSTRING
        imagePullSecrets:
            - name: acr-secret
        restartPolicy: OnFailure

  successfulJobsHistoryLimit: 0   
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: avatarrequestqueue
      connectionFromEnv: SERVICEBUS_CONNECTIONSTRING
      namespace: sb-faceapp-demo
      messageCount: '1'
    authenticationRef:
     name: usernode-workerapp-trigger-auth
```
