### DISCUSSION TITLE
Values mismatch between Datadog and the Datadog scaler

### DISCUSSION THREAD

**Discussion by taliv-upstream** [kedacore/keda#3060] [Q&A / Need Help] [answered]
Hi all,
I am testing DaatDog scaler, I am using the following configuration:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: datadog-scaledobject
  namespace: test
spec:
  scaleTargetRef:
    name: deployment-api-server
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 60
  triggers:
  - type: datadog
    # Optional: (Value or AverageValue). Whether the target value is global or average per pod. Default: AverageValue
    metadata:
      # Required: datadog metric query
      query: "sum:num.messages{subenv:prod}.as_rate()"
      # Required: according to the number of query result, to scale the TargetRef
      queryValue: "500"
      type: "global"
      # Optional: The time window (in seconds) to retrieve metrics from Datadog. Default: 90
      age: "100"
      # Optional: The metric value to return to the HPA if a metric value wasn't found for the specified time window
      metricUnavailableValue: "0"
    authenticationRef:
      name: keda-trigger-auth-datadog-secret
```
The metric I use shows values greater than 10k on my DataDog dashboard. When examining the  targets column on the created HPA object I see that their value is ranging from 500 to 800 approximately , I just followed the queried values for several minutes. 

I am not sure what I am missing here, why do I see a difference between the values shown in DataDog to what the scaler queries?
