### DISCUSSION TITLE
Azure pipelines scaler - Agent pool not found

### DISCUSSION THREAD

**Discussion by ugurgural** [kedacore/keda#3122] [Q&A / Need Help]
Hi, i am using azure devops hosted agents on AWS EKS cluster behind of company proxy. Wanted to use keda with ScaledJob approach so agents can run until they are done then can be auto-removed. Here is the deployment yaml I am using taken from [official example](https://keda.sh/blog/2021-05-27-azure-pipelines-scaler/#run-the-self-hosted-agent-as-a-job) : 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: azdevops-scaledjob
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: azdevops-agent-job
          image: xxx.dkr.ecr.eu-central-1.amazonaws.com/xxx
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: proxy-config
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-volume
          env:
            - name: AZP_URL
              value: "https://dev.azure.com/organization"
            - name: AZP_TOKEN
              value: "azure devops PAT token - not encoded"
            - name: AZP_POOL
              value: "vsts-docker-agent-pool"
            - name: AZP_AGENT_USE_LEGACY_HTTP
              value: "true"
        volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock
  pollingInterval: 30
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10   
  scalingStrategy:
    strategy: "default"               
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: "24"
      organizationURLFromEnv: "AZP_URL"
      personalAccessTokenFromEnv: "AZP_TOKEN"
```

First agent seems created fine without issues, but when it needs to scale up I am getting this error from keda operator pod : 

```
ERROR	controller.scaledjob	Failed to ensure ScaledJob is correctly created	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob", "name": "azdevops-scaledjob", "namespace": "azure-pipelines-agents", "error": "error parsing azure Pipelines metadata: agent pool with id `24` not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
```

Obviously first thing I checked was maybe I am getting wrong pool id, but it seems correct, confirming the pool id is correct with this url via postman : 

`https://dev.azure.com/organization/_apis/distributedtask/pools?poolIds=24`

Can anyone help me what am i missing here ? Thank you very much.
