### DISCUSSION TITLE
dimensionName field of ScaledObject is documented as optional but seems to be required

### DISCUSSION THREAD

**Discussion by 60k41p** [kedacore/keda#3134] [Q&A / Need Help]
### Report

According to https://keda.sh/docs/2.7/scalers/aws-cloudwatch/, the `dimensionName` field should be optional.

The metric for scaling has no dimensions:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/9840837/171150202-2a3e00ac-060c-4926-9e88-af3f6cfee971.png">

However, after applying the below resource definition, 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redash-rq-worker
spec:
  scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: redash-rq-worker
  minReplicaCount: 1
  maxReplicaCount: 4
  triggers:
  - type: aws-cloudwatch
    metadata:
      namespace: Redash/Workers
      metricName: BUSY
      metricCollectionTime: "300" # the default
      metricStat: "Average" # the default
      metricStatPeriod: "30"
      metricUnit: ""
      targetMetricValue: "4"
      awsRegion: us-east-1
      identityOwner: operator
```

### Expected Behavior

The ScaledObject should be ready for scaling with dimensionName omitted in the manifest.

### Actual Behavior

After `kubectl apply` of the above manifest,
`kubectl describe ScaledObject redash-rq-worker` gives:
```
  Warning  ScaledObjectCheckFailed  13s (x12 over 24s)  keda-operator  Failed to ensure HPA is correctly created for ScaledObject
  Warning  KEDAScalerFailed         3s (x13 over 24s)   keda-operator  error parsing cloudwatch metadata: dimension name not given
 ```

### Steps to Reproduce the Problem

1. Install KEDA 2.7.1
2. kubectl apply the manifest given above
3. kubectl describe ScaledObject redash-rq-worker

### Logs from KEDA operator

```
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227
1.6539913265347884e+09	ERROR	controller.scaledobject	Reconciler error	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "redash-rq-worker", "namespace": "default", "error": "error parsing cloudwatch metadata: dimension name not given"}
```

### KEDA Version

2.7.1

### Kubernetes Version

1.21

### Platform

Amazon Web Services

### Scaler Details

AWS CloudWatch
