### DISCUSSION TITLE
Using vault in triggered authentication not working

### DISCUSSION THREAD

**Discussion by taliv-upstream** [kedacore/keda#3179] [Q&A / Need Help]
Hi,
I am creating the following k8s objects:
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: ta
  namespace: test
spec:
  hashiCorpVault:
    address: https://vault.infra:8200
    authentication: kubernetes
    role: default
    mount: kubernetes
    credential:
      serviceAccount: /var/run/secrets/kubernetes.io/serviceaccount/token
    secrets:
    - parameter: apiKey
      key: api
      path: /secret/data/dd-sec
    - parameter: appKey
      key: app
      path: /secret/data/dd-sec

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: datadog-scaledobject-vault
  namespace: test
spec:
  scaleTargetRef:
    name: web
  triggers:
  - type: datadog
    # Optional: (Value or AverageValue). Whether the target value is global or average per pod. Default: AverageValue
    metadata:
      # Required: datadog metric query
      query: "sum:load.web.app.ui{subenv:temp-demo}"
      # Required: according to the number of query result, to scale the TargetRef
      queryValue: "7"
      type: "global"
      # Optional: The time window (in seconds) to retrieve metrics from Datadog. Default: 90
      age: "120"
    authenticationRef:
      name: ta
```

I am trying to make the triggered authentication work, but I want to use the internal vault that I have installed on k8s, is that possible? I am not sure what I am missing here since everything is configured by the docs
I get the following error in the operator:
`ERROR	controller.scaledobject	Reconciler error	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "datadog-scaledobject-vault", "namespace": "upstream", "error": "error parsing Datadog metadata: no api key given"}`
