### DISCUSSION TITLE
Scaling is not performed because triggers are not active

### DISCUSSION THREAD

**Discussion by shengzhizhou** [kedacore/keda#3181] [Q&A / Need Help]
In our kubernetes cluster, we installed keda-operator and scaleobject and all, everything works fine, pods scale up and down, but in Rancher it shows error "Scaling is not performed because triggers are not active". Just this warning looks not correct.
Thanks for answering!

## Specifications

  - **KEDA Version: Keda-operator image keda:2.6.1
  - **Platform & Version: Provider: rke2r2
  - **Kubernetes Version: v1.23.6

**Comment by tomkerkhove** [comment]
Can you add some more information such as logs and what you are doing please?

**Comment by zroubalik** [comment]
That is not an error. `status.Active` field set to false marks when the scaling is not happening, together with this message. Once the deployment is scaled out the `status.Active` field is set to true together with updated message

**Comment by Shaked** [comment]
Hey @shengzhizhou did you figure a way to remove the error from rancher? 

@tomkerkhove basically it shows this on the keda resource:

```
status:
  conditions:
  - message: ScaledJob is defined correctly and is ready to scaling
    reason: ScaledJobReady
    status: "True"
    type: Ready
  - message: Scaling is not performed because triggers are not active
    reason: ScalerNotActive
    status: "False"
    type: Active
  - status: Unknown
    type: Fallback

``` 

And then rancher treats that as if there's an error: 

![image](https://user-images.githubusercontent.com/960015/202226269-cb462e11-e7b6-411f-86a0-8837d2a580f3.png)
