### DISCUSSION TITLE
Keda using Prometheus Scaler on multi-env

### DISCUSSION THREAD

**Discussion by ZviMints** [kedacore/keda#3208] [Q&A / Need Help] [answered]
Hey!
Consider the following `keda.yaml`:
```
{{- if and (.Values.keda.enabled) (eq .Values.phase "stable") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.keda.behavior.scaleUp.stabilizationWindowSeconds }}
          {{- with .Values.keda.behavior.scaleUp.policies }}
          policies:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        scaleUp:
          stabilizationWindowSeconds: {{ .Values.keda.behavior.scaleDown.stabilizationWindowSeconds }}
          {{- with .Values.keda.behavior.scaleDown.policies }}
          policies:
          {{- toYaml . | nindent 10 }}
  {{- end }}
  triggers:
    {{- if .Values.keda.triggers.cpu }}
    - type: cpu
      metadata:
        type: Utilization
        value: {{ .Values.keda.triggers.cpu.percent | quote }}
    {{- end }}
    {{- if .Values.keda.triggers.memory }}
    - type: memory
      metadata:
        type: Utilization
        value: {{ .Values.keda.triggers.memory.percent | quote }}
    {{- end }}
    {{- if .Values.keda.triggers.cron }}
    - type: cron
      metadata:
        timezone: {{ .Values.keda.triggers.cron.timezone }}
        start: {{ .Values.keda.triggers.cron.startSchedule }}
        end: {{ .Values.keda.triggers.cron.endSchedule }}
        desiredReplicas: {{ default .Values.keda.maxReplicaCount .Values.keda.triggers.cron.desiredReplicas | quote }}
    {{- end }}
    {{- if .Values.keda.triggers.prometheus }}
    - type: prometheus
      metadata:
        serverAddress: http://p-thanos-querier.prod:9090
        metricName: {{ .Values.keda.triggers.prometheus.metricName }}
        threshold: {{ .Values.keda.triggers.prometheus.threshold | quote }}
        query: {{ .Values.keda.triggers.prometheus.query }}
    {{- end }}
{{- end }}
```
And the following `values.yaml`:
```
keda:
  enabled: true
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
  triggers:
    cpu:
      percent: 60
    memory:
      percent: 80
    cron:
      timezone: Asia/Jerusalem
      startSchedule: 0 03 * * *
      endSchedule: 0 04 * * *
    prometheus:
      metricName: http_requests_total
      threshold: 100
      query: sum(rate(http_requests_total[2m]))
```
And the following metrics:
```
http_requests_total{cluster="gp-1", namespace="service"}
http_requests_total{cluster="gp-2", namespace="service"}
http_requests_total{cluster="gp-3", namespace="service"}
```
which uses the same `serverAddress`, how its possible to create a different serverAddress per env without explicit override on each value, is it possible to create `serverAddress` per deployment?

Thanks!
