### DISCUSSION TITLE
Azure Pipelines Scaler - private CA issue

### DISCUSSION THREAD

**Discussion by RPM8887** [kedacore/keda#3324] [Q&A / Need Help] [answered]
### Report

When using KEDA with an onprem/privately hosted Azure DevOps Server instance with HTTPS enabled signed by a private CA operator is unable to connect to the provided endpoint:
`error parsing azure Pipelines metadata: Get \"[https://xxxx.private.int/tfs/XYZ/_apis/distributedtask/pools?poolName=k8s-pool-test\":](https://xxxx.private.int/tfs/XYZ/_apis/distributedtask/pools?poolName=k8s-pool-test\%22:) x509: certificate signed by unknown authority"`

From what I've seen in the past, similar issues have already been reported for other scalers (eg.: RabbitMQ: https://github.com/kedacore/keda/issues/967). Any easy way of maybe injecting trusted CAs into the operator so that all scalers support them?

### Expected Behavior

Request successful

### Actual Behavior

Request fails because of untrusted certificate

### Steps to Reproduce the Problem

1. Configure Azure Pipelines ScalableObbject against an Azure DevOps instance that uses a privately signed certificate
2. Review operator logs

### Logs from KEDA operator

`error parsing azure Pipelines metadata: Get \"[https://xxxx.private.int/tfs/XYZ/_apis/distributedtask/pools?poolName=k8s-pool-test\":](https://xxxx.private.int/tfs/XYZ/_apis/distributedtask/pools?poolName=k8s-pool-test\%22:) x509: certificate signed by unknown authority"`

### KEDA Version

2.7.0

### Kubernetes Version

1.22

### Platform

Any

### Scaler Details

Azure DevOps Pipeline

**Comment by RPM8887** [comment, marked as answer]
ended up injecting the needed certificates from a configmap as a volume:
````
        volumeMounts:
        - name: certificates
          mountPath: /etc/ssl/certs/certs.pem
          subPath: private_ca
          readOnly: false
````
          
````
      volumes:
        - name: certificates
          configMap:
            name: certificates  
````

**Reply by MarioCat** [reply]
Where did you add that please ? 
I tried adding it in the deployment, but it does not fix the issue for me.
Could you please provide the complete YAML file.

Thanks.

**Reply by emboss64** [reply]
I'm using the following kustomize patch to add the custom CA to `keda-operator` deployment:

````
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-operator
spec:
  template:
    spec:
      containers:
        - name: keda-operator
          volumeMounts:
            - name: custom-ca
              mountPath: /custom/ca
      volumes:
        - name: custom-ca
          configMap:
            name: ca-certificates
````

the `ca-certificates` config map is created with:
````
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: ca-certificates
    files:
    - files/ca-intermediate.crt
    - files/ca-root.crt
````

ref: https://keda.sh/docs/2.11/operate/security/
