### DISCUSSION TITLE
PostgreSQL Scaler not working

### DISCUSSION THREAD

**Discussion by gerardoemr** [kedacore/keda#3499] [Q&A / Need Help]
Hello, 

I am trying to setup a KEDA PostgreSQL scaler for testing purposes. The `keda-operator` pod shows logs indicating that the configuration was applied correctly, however the selected deployment is not scaling out. Could someone point me in the right direction in solving this? Or should I report a bug?  

Here is the configuration: 
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: status-service-psql
  namespace: pod-namespace
spec:
  scaleTargetRef:
    name: status-service
  pollingInterval: 30    # Optional. Default: 30 seconds
  cooldownPeriod:  300    # Optional. Default: 300 seconds
  maxReplicaCount: 5      # Optional. Default: 100
  triggers:
    - type: postgresql
      metadata:
        userName: postgres
        host: postgres-database
        port: "5432"
        dbName: postgres
        sslmode: disable
        query: "SELECT any_metric FROM some_table LIMIT 1" 
        targetQueryValue: "1"
```
**NOTE** I removed the `password` from the configuration since in the Postgres database I  set the configuration to `POSTGRES_HOST_AUTH_METHOD=trust` 

`keda-operator` logs
```
1.659550750656355e+09	INFO	controller.scaledobject	Initializing Scaling logic according to ScaledObject Specification	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "status-service-psql", "namespace": "pod-namespace"}
1.6595507506897547e+09	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "status-service-psql", "namespace": "pod-namespace"}
1.6595507659439638e+09	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "status-service-psql", "namespace": "pod-namespace"}
```

**What I've tried**
- Setting up different queries and tables.
- I verified that KEDA works properly by trying out first with a CRON scaler.
- I confirmed that KEDA connects to the database by checking `pg_stat` (see attached image)

![image](https://user-images.githubusercontent.com/15000065/182698584-a28c81e0-208b-4792-bb53-80a43ceb4cf0.png)

I highly appreciate any help!

Thanks
