### DISCUSSION TITLE
use deployment service account token for HashiCorpVault triggerAuthentication

### DISCUSSION THREAD

**Discussion by nfrappart** [kedacore/keda#3553] [Ideas]
Hi,
I've been playing with keda on AKS, with external vault cluster, and had a hard time with the HashiCorp vault authentication.
I thought /var/run/secrets/kubernetes.io/serviceaccount/token would refer to the auto mounted token in deployment pods, but it appears it uses keda-operator service account token instead.
As a result, I had to create a separate role with policy on vault (as I don't want keda to have unnecessary authorisations).

Do you think it would be possible (does it make sense ?) to specify a containerName for the hashiCorpVault spec in the TriggerAuthentication? Just like we can retrieve a environment variable?
Below is my configuration to make it clearer

```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: devopsagent-trigger-auth
  namespace: devopsagent
spec:
  env:
  - parameter: organizationURL
    name: "AZP_URL"
    containerName: devopsagent    
  hashiCorpVault:
    address: https://vault.mydomain.extension:8200
    authentication: kubernetes
    role: keda
    mount: hubk8s
    credential:
      serviceAccount: /var/run/secrets/kubernetes.io/serviceaccount/token
    secrets:
    - parameter: personalAccessToken
      key: pat
      path: secret/data/devops
```

Just like we get the env from the specified container here:
```yaml
  env:
  - parameter: organizationURL
    name: "AZP_URL"
    containerName: devopsagent    
```

could we do the same like so ?
So that the trigger authentication know where to get the token with the provided path.
```yaml
    address: https://vault.mydomain.extension:8200
    authentication: kubernetes
    role: devopsagent
    mount: hubk8s
    credential:
      serviceAccount: /var/run/secrets/kubernetes.io/serviceaccount/token
      containerName: devopsagent
    secrets:
    - parameter: personalAccessToken
      key: pat
      path: secret/data/devops
```
Or maybe replace the `serviceAccount` path by a `serviceAccountName` altogether making it even more straightforward?

What do you think?

Thanks

PS: keda is awesome btw :)
