### DISCUSSION TITLE
Pod identity based authentication

### DISCUSSION THREAD

**Discussion by prashathsenthil** [kedacore/keda#3581] [General]
Hi,

I have deployed the latest KEDA version 2.8.0 in my EKS Cluster (version v1.22.10-eks-84b4fe6), I'm trying to leverage KEDA for AWS SQS Queue scaler via Pod identity based authentication, however when I follow the documentation https://keda.sh/docs/2.8/scalers/aws-sqs/#example and deploy the scaledobject and triggerauth with the below manifests targeting my POD with IRSA enabled, I could see errors that indicates KEDA is trying to use the underlying worker node's IAM Role to perform sts:AssumeRole action on the IAM role annotated to my POD's ServiceAccount.

Ideally I would like KEDA operator and metric server to use my POD IAM role to connect with SQS Queue. Was looking at the scaler (https://github.com/kedacore/keda/blob/main/pkg/scalers/aws_sqs_queue_scaler.go) and aws IAM auth code (https://github.com/kedacore/keda/blob/main/pkg/scalers/aws_iam_authorization.go) not sure if my above requirement is feasible. Any help/guidance would be very useful.

```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: my-test-namespace
spec:
  podIdentity:
    provider: aws-eks
```

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: my-test-namespace
spec:
  scaleTargetRef:
    name: my-test-scaledobject
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: https://sqs.us-east-1.amazonaws.com/<my_aws_account>/my-test-queue
      queueLength: "2"
      awsRegion: "us-east-1"
      identityOwner: pod
```

My POD IRSA works as expected as I was able to test it out by pushing messages to Queue and was able to have the POD read them, also below is the POD STS getcallerIdentity O/P,

{'UserId': 'xxxxxx', 'Account': 'xxxxx', 'Arn': 'arn:aws:sts::xxxxx:assumed-role/consumer-role/botocore-session-xxxxxx', 'ResponseMetadata': {'RequestId': 'xxxxxx', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'xxxxxx', 'content-type': 'text/xml', 'content-length': '500', 'date': 'Tue, 23 Aug 2022 02:34:24 GMT'}, 'RetryAttempts': 0}}
