### DISCUSSION TITLE
SQS scaler sets 0 replicas even when there are in-flight messages

### DISCUSSION THREAD

**Discussion by Obbart** [kedacore/keda#3583] [Q&A / Need Help]
Hello,
I'm trying to scale a deployment in an EKS cluster using an SQS queue length as the metric for the scaler.
The pods in the deployment take some time to process each message (1 for each pod) and the messages are very sparse in time so the deployment is almost always at 0.
I noticed this behavior: when a pod is created (on Fargate) and the message is put in-flight from the application, the ScaledObject immediately reports the trigger `ACTIVE = False`  and deletes the running pod before the message is deleted from the queue.

Here is my scaler configuration:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mydeploy-scaling
spec:
  scaleTargetRef:
    kind: Deployment
    name: mydeploy
  pollingInterval: 15
  cooldownPeriod:  300
  minReplicaCount: 0
  maxReplicaCount: 10
  fallback:
    failureThreshold: 5
    replicas: 0
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-meshing-sqs-trigger-auth
    metadata:
      queueURL: https://sqs.eu-west-1.amazonaws.com/<ACCOUNTID>/myqueue.fifo
      queueLength: "1" # Each pod handles one message at a time
      awsRegion: "eu-west-1"
      scaleOnInFlight: "true"
      identityOwner: operator
```

I set the parameter `scaleOnInFlight: "true"` according to the docs and checking the Available/InFlight messages in the queue with a python script they are reported correctly by the SQS API.

Is there something that am I missing?
Thanks for the support, have a nice day.
