### DISCUSSION TITLE
scaler[ postgresql ] cannot use scaledobject.spec.triggers.passowrd as connection password

### DISCUSSION THREAD

**Discussion by spwangxp** [kedacore/keda#3612] [General]
### Report

when i set scaledobject.spec.triggers.passowrd as connection password, it's not work ❌, the log shows "password" are not set;
when i set scaledobject.spec.triggers.passowrdFromEnv as connection password, it's worked fine ✅;

![image](https://user-images.githubusercontent.com/24298044/186804219-e922945f-d272-4952-b8ae-aa374a554cb4.png)

### Expected Behavior

the scaledobject.spec.triggers.passowrd works as expect

### Actual Behavior

see report

### Steps to Reproduce the Problem

1. see report

### Logs from KEDA operator

```
2022-08-26T02:33:41Z    ERROR   scalehandler    Error getting scalers   {"object": {"apiVersion": "keda.sh/v1alpha1", "kind": "ScaledObject", "namespace": "default", "name": "pg-scaler"}, "error": "error establishing postgreSQL connection: pq: password authentication failed for user \"admin\""}
```

### KEDA Version

2.8.0

### Kubernetes Version

1.23

### Platform

Other

### Scaler Details

postgresql

**Comment by tomkerkhove** [comment]
I don't think we should do this as this would mean there are hardcoded passwords, we should use trigger authentication instead (which should already be supported I think)

**Comment by tomkerkhove** [comment]
this is also not really a bug as `password` is supported, but through trigger authentication:
https://keda.sh/docs/2.8/scalers/postgresql/#authentication-parameters

**Comment by spwangxp** [comment]
https://github.com/kedacore/keda-docs/blame/main/content/docs/2.9/scalers/postgresql.md#L81

https://github.com/kedacore/keda/pull/3601?w=1#issuecomment-1228127320

**Comment by tomkerkhove** [comment]
The docs that you are referring to is purely for TriggerAuthentication and not for trigger metadata.

**Comment by Sathya-omnius** [comment]
HI Team , any solution for this issue I am facing the same issue when I provide postgres data base details

**Reply by JorTurFer** [reply]
This is a design decision, you cannot use the plain text password in the ScaledObject, you have to read it form the workload or use TriggerAuthentication. We won't change that behavior because ScaledObject isn't secure

**Reply by Sathya-omnius** [reply]
Hello Jorturfer thanks for the response i tried using TriggerAuthentication but I am getting following error , the postgres SQL is in Azure.
ERROR   Reconciler error        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"abby-scaledobject4","namespace":"engine"}, "namespace": "engine", "name": "abby-scaledobject4", "reconcileID": "1d297d9d-60f2-4ce6-80b5-76e1eaa35afb", "error": "error establishing postgreSQL connection: pq: no pg_hba.conf entry for host \"10.0.1.6\", user \"decicdqa\", database \"engine_document_service\", no encryption"}
can you please let me know what would be solution for this, I tried in different ways but still getting same error

**Reply by JorTurFer** [reply]
It looks like if the firewall is blocking the traffic. Is the firewall of the PostgreSQL Server set? Does your workload reach the database?

**Reply by Sathya-omnius** [reply]
Hello,
we dont have any firewall blocker with in the pod we can connect postgressql, we tried in all the ways but still no luck can you please check the configuration we are using,do i need to add any additional configuration w.r.t password,thanks for the quick response
#this is postgres trigger 
```yaml
triggers:
    - type: postgresql
      metadata:
        userName: {{ .Values.configmapvalues.DATABASE_USERNAME }}
        host: {{ .Values.configmapvalues.DATABASE_HOST }}
        dbName: 'engine_service'
        passwordFromEnv: postgrespassword
        sslmode: disable
        port: '5432'
        query: "SELECT ceil(COUNT(*)::decimal / 16) FROM table WHERE status='PROCESSING'"
        targetQueryValue: "3"
      authenticationRef:
        name: postgresqlpassword
```
	
#this is trigger authentication		
```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: postgresqlpassword
spec:   
  secretTargetRef:                                                       
  - parameter: passwordFromEnv                          
    name: postgres-909                                           
    key: postgrespassword       
```

#this is our secret code
```yaml
apiVersion: v1
data:
  postgrespassword: {{ .Values.DATABASE_PASSWORD | b64enc | quote }}
kind: Secret
metadata:
  name: postgres-909 
type: Opaque	
```

**Reply by JorTurFer** [reply]
Your trigger authentication isn't doing anything because the parameter that you are setting is wrong, `passwordFromEnv` it's a key for metadata section to read the environment variable from the pod with that name. 
Has the pod an env named `postgrespassword` with the password? If yes, You can remove the TriggerAuthentication and the reference to it, keeping simpler the ScaledObject. If you prefer to use the TriggerAuthentication, the parameter has to be `password` and not `passwordFromEnv` and you have to remove `passwordFromEnv` from metadata section.

In any case, I don't think that this duplication is the root cause. Please, check the username and the password to ensure that are correct and also validate if the user has enough permission in the database:
- https://help.heroku.com/DR0TTWWD/seeing-fatal-no-pg_hba-conf-entry-errors-in-postgres

You should also check the connection parameters. The problem is in a misconfiguration at some place

**Reply by Sathya-omnius** [reply]
Hello,

thanks for the reply we have env variable passwordFromEnv: postgrespassword but still its not working,when i use TriggerAuthentication
i am referring to 
authenticationRef:
        name: postgresqlpassword
as per the Keda document, where should i use password if I use TriggerAuthentication

**Reply by Sathya-omnius** [reply]
when we enable (sslmode: require) I am getting following error
ERROR   Reconciler error        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"abby-scaledobject5","namespace":"engine"}, "namespace": "engine", "name": "abby-scaledobject5", "reconcileID": "181c20b1-ede0-40ac-81c1-b1595109a858", "error": "error establishing postgreSQL connection: pq: password authentication failed for user \"decicdqa\""}

**Reply by JorTurFer** [reply]
```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: postgresqlpassword
spec:   
  secretTargetRef:                                                       
  - parameter: password
    name: postgres-909                                           
    key: postgrespassword    
```

**Reply by Sathya-omnius** [reply]
thank you so much for your quick response ,every thing is working fine by doing some changes w.r.t sslmode

**Comment by thinkbigdatanalytics** [comment]
@Sathya-omnius  @JorTurFer  @tomkerkhove 


I have the same problem "**server error (FATAL: no pg_hba.conf entry for host \"10.75.9.197\**"

I don't see anything wrong in this config, please let me know if there are any issues here. I tried both **passwordFromEnv** and **TriggerAuthentication**, and it does have the same error. Looks like the password is getting fetched.


```yaml

apiVersion: v1
kind: Secret
metadata:
  name: test-db-secret
  namespace: dev
type: Opaque
data:
  PG_PASSWORD: "G3BuGGDdBdjZmcw=="
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-postgres-secret
  namespace: dev
spec:
  secretTargetRef:
  - parameter: password
    name: test-db-secret
    key: PG_PASSWORD
  env:
  - parameter: password
    name: PG_PASSWORD
    containerName: test-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
        app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: linuxacademycontent/store-products:1.0.0
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: test-db-secret
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-app
spec:
  scaleTargetRef:
    name: test-app
  pollingInterval: 10
  cooldownPeriod: 30
  maxReplicaCount: 2  
  minReplicaCount: 0
  triggers:
    - type: postgresql
      metadata:
        userName: testuser
        host: test_host
        port: "5432"
        dbName: test_db
        sslmode: disable
        query: "SELECT ceil(message_count) as message_count FROM instance"
        targetQueryValue: "1"
      authenticationRef:
        name: keda-trigger-auth-postgres-secret

```
