### DISCUSSION TITLE
keda: Keda not scaling pod with inbound azure service bus

### DISCUSSION THREAD

**Discussion by azmrehman** [kedacore/keda#3622] [Q&A / Need Help] [answered]
Using keda for scaling camel-k pods having inbound azure service bus. Scaled object defined as
```yaml
apiVersion: keda.sh/v1alpha1  
kind: ScaledObject  
metadata:  
  name: main-router-scaledobject  
  namespace: rehmannazar-camel-dev  
spec:  
  minReplicaCount:  0  
  maxReplicaCount: 10  
  scaleTargetRef: 
    name: mainrouter
    kind: Deployment
  triggers:
  - type: azure-servicebus  
    metadata:  
      topicName: topic4test  
      subscriptionName: sub3  
      messageCount: "10"  
      activationMessageCount: "0"  
    authenticationRef:  
      name: trigger-auth-service

apiVersion: keda.sh/v1alpha1  
kind: TriggerAuthentication  
metadata:  
  name: trigger-auth-service  
spec:  
  secretTargetRef:   
  - parameter: connection  
    name: connectionsecret  
    key: connection
````
and connectionsecret defines connection string to azure service bus.

kubectl describe scaledobject main-router-scaledobject 

is having status
```
Status:  
  Conditions:  
    Message:  ScaledObject is defined correctly and is ready for scaling  
    Reason:   ScaledObjectReady  
    Status:   True  
    Type:     Ready  
    Message:  Scaling is not performed because triggers are not active  
    Reason:   ScalerNotActive  
    Status:   False  
    Type:     Active  
    Message:  No fallbacks are active on this scaled object  
    Reason:   NoFallbackFound  
    Status:   False  
    Type:     Fallback  
  External Metric Names:  
    s0-azure-servicebus-topic4test  
  Health:  
    s0-azure-servicebus-topic4test:  
      Number Of Failures:  0  
      Status:              Happy  
  Hpa Name:                keda-hpa-main-router-scaledobject  
  Original Replica Count:  1  
  Scale Target GVKR:  
    Group:            apps  
    Kind:             Deployment  
    Resource:         deployments  
    Version:          v1   
  Scale Target Kind:  apps/v1.Deployment  
Events:  
  Type    Reason                      Age                    From             Message
  ----    ------                      ----                   ----           -------     
  Normal  KEDAScaleTargetDeactivated  3m53s (x191 over 98m)  keda-operator    Deactivated apps/v1.Deployment rehmannazar-camel-dev/mainrouter from 1 to 0  
```

```
$ kubectl get ScaledObject main-router-scaledobject  
NAME                       SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   TRIGGERS           AUTHENTICATION         READY   ACTIVE   FALLBACK   AGE  
main-router-scaledobject   apps/v1.Deployment   mainrouter        0     10    azure-servicebus   trigger-auth-service   True    False    False      101m  
```

yet pods are not scaled to zero and when posting messages on subscription sub3 pods are not upscaled. Pods are also not downscaled to zero when sub3 has no messages. There is always a single pod in running state. Only activity I am observing is pods getting terminated and new pod getting started but pods replicas always remain 1. Is there something I missed in keda configuration?.

**Comment by azmrehman** [comment]
Hi @tomkerkhove please have a look at keda config and implementation.

**Reply by tomkerkhove** [reply]
Most likely there is an authentication problem. Can you share the logs from KEDA's operator please?

**Reply by azmrehman** [reply]
[file1.txt](https://github.com/kedacore/keda/files/9469373/file1.txt)
PFA keda operator logs

**Reply by tomkerkhove** [reply]
There you go:
> 2022-09-01T05:00:19Z	ERROR	Target resource doesn't exist	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"main-router-scaledobject","namespace":"rehmannazar-camel-dev"}, "namespace": "rehmannazar-camel-dev", "name": "main-router-scaledobject", "reconcileID": "fa4e7402-9cde-4d99-adb1-21e1a3429f57", "resource": "apps/v1.Deployment", "name": "mainrouter", "error": "deployments.apps \"mainrouter\" not found"}

**Reply by tomkerkhove** [reply]
@zroubalik @JorTurFer This is not ideal though - Can we surface these kind of failures as events in the ScaledObject/ScaledJobs so that people wouldn't even have to go to logs in first place?

These scenarios I'd expect to be in the events:
- Auth failure
- Scale target not found
- Others?

**Reply by azmrehman** [reply]
Hi @tomkerkhove 

   Executing kubectl get deployments returns me mainrouter deployment  the target resource. 

 k get deployments
NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
camel-k-operator                  1/1     1            1           3d20h
keda-operator                     1/1     1            1           43h
keda-operator-metrics-apiserver   1/1     1            1           43h
mainrouter                        1/1     1            1           7h5m

 k get rs
NAME                                        DESIRED   CURRENT   READY   AGE
camel-k-operator-dc8489bfc                  1         1         1       3d20h
keda-operator-5584f56d8c                    1         1         1       43h
keda-operator-metrics-apiserver-f5d7b56d8   1         1         1       43h
mainrouter-57587dd56b                       1         1         1       7h5m

**Reply by JorTurFer** [reply]
Raising events in the SO/SJ could be a nice improvement yes

**Reply by tomkerkhove** [reply]
@azmrehman Can you please run `k describe deployment/mainrouter`?

**Reply by tomkerkhove** [reply]
Created https://github.com/kedacore/keda/issues/3629

**Reply by azmrehman** [reply]
[file2.txt](https://github.com/kedacore/keda/files/9469698/file2.txt)
Response from k describe deployment mainrouter attached in file

**Reply by tomkerkhove** [reply]
Deployment:
```
Name:                   mainrouter
Namespace:              rehmannazar-camel-dev
```

ScaledObject:
```yaml
apiVersion: keda.sh/v1alpha1  
kind: ScaledObject  
metadata:  
  name: main-router-scaledobject  
  namespace: rehmannazar-camel-dev
spec:  
  minReplicaCount:  0  
  maxReplicaCount: 10  
  scaleTargetRef: 
    name: mainrouter
    kind: Deployment
```

Hm, do you know what could be up @JorTurFer?
