### DISCUSSION TITLE
Selenium scaler: keda-metrics-apiserver: Failed to make webhook authorizer request: Unauthorized

### DISCUSSION THREAD

**Discussion by deepakguna** [kedacore/keda#3647] [Q&A / Need Help]
Hello , 

I am trying to use keda selenium scaler for my grid in AWS k8s - however it is having issue with  keda-metrics-apiserver: Failed to make webhook authorizer request: Unauthorized. Please let me know what am i missing, 

My scaled object: 
```

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-chrome-scaledobject
  namespace: selenium
  labels:
    deploymentName: selenium-chrome-node-deployment
spec:
  minReplicaCount: 0
  maxReplicaCount: 30
  scaleTargetRef:
    name: selenium-chrome-node-deployment
  triggers:
    - type: selenium-grid
      metadata:
        url: 'https://internal.selenium.abc.com/graphql'
        browserName: 'chrome'
        unsafeSsl : 'true'
```

kubectl logs -n keda keda-metrics-apiserver-5ff7b56d-4bmcs -c keda-metrics-apiserver

Following is the trace : 
I0722 13:06:58.868308       1 secure_serving.go:266] Serving securely on [::]:6443
I0722 13:06:58.868367       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0722 13:06:58.968046       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0722 13:06:58.968061       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController
I0722 13:06:58.968069       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
E0731 22:17:26.826557       1 webhook.go:224] Failed to make webhook authorizer request: Unauthorized
E0731 22:17:26.826586       1 errors.go:77] Unauthorized
E0904 17:04:23.041039       1 webhook.go:224] Failed to make webhook authorizer request: Unauthorized
E0904 17:04:23.041069       1 errors.go:77] Unauthorized
E0904 17:04:24.194544       1 webhook.go:224] Failed to make webhook authorizer request: Unauthorized
E0904 17:04:24.194575       1 errors.go:77] Unauthorized
E0904 17:04:24.214166       1 webhook.go:224] Failed to make webhook authorizer request: Unauthorized
E0904 17:04:24.214187       1 errors.go:77] Unauthorized
E0904 17:04:24.225470       1 webhook.go:224] Failed to make webhook authorizer request: Unauthorized
E0904 17:04:24.225494       1 errors.go:77] Unauthorized
E0904 17:04:24.326895       1 webhook.go:224] Failed to make webhook authorizer request: Unauthorized
E0904 17:04:24.326917       1 errors.go:77] Unauthorized
E0904 17:04:24.342616       1 webhook.go:224] Failed to make webhook authorizer request: Unauthorized
E0904 17:04:24.342633       1 errors.go:77] Unauthorized
