### DISCUSSION TITLE
ScaledJob without support of repeated port with different names in container template

### DISCUSSION THREAD

**Discussion by zd9KgA** [kedacore/keda#3658] [Q&A / Need Help]
Dear community,

In the definition of a `ScaledJob.spec.jobTargetRef.template.containers`, I'd expect to be able to state something like this:

```yaml
          ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          - containerPort: 8080
            name: probes
            protocol: TCP
```
That is, to refer to the same physical port by different names. This works for a `Pod`, and I did not find any restriction why the same `PodSpec` shouldn't work in the definition of a `ScaledJob`.

My setting comprises K8s@1.23.5 on Ubuntu and KEDA@2.8.1 via Helm (from https://kedacore.github.io/charts).

Am I missing something?

Cheers
