### DISCUSSION TITLE
How to set log level for metric server

### DISCUSSION THREAD

**Discussion by karimrut** [kedacore/keda#3667] [Q&A / Need Help]
Hi! 

How do I set the log level for the Keda metric server to warn or error? Not sure what it means to set "an integer value greater than 0". Any value between 1-3 still gives me info level logging. 

Ref: https://github.com/kedacore/charts/tree/main/keda
`logging.metricServer.level`

```yaml
logging:
  operator:
    level: error
  metricServer:
    level: ? #0=info, 4=debug
```

Thanks in advance
Karim
