### DISCUSSION TITLE
KEDA Metrics API - Ignore Certificate Errors

### DISCUSSION THREAD

**Discussion by wymangr** [kedacore/keda#3728] [Q&A / Need Help]
I'm trying to setup the Metrics API KEDA scaler. I have an internal API setup with a self signed certificate, but when I deploy it I'm getting the following error:

```
Warning  KEDAScalerFailed    11s                keda-operator  Get "https://api.com/aks_autoscaler": x509: certificate has expired or is not yet valid
```

I was wondering if there was a way to ignore certificate errors with this scaler? 

here is my setup:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: appraisals-scale
  namespace: app
  labels:
    app: app_name
spec:
  maxReplicaCount: 12
  scaleTargetRef:
    name: app_name
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "7"
        url: "https://api.com/aks_autoscaler"
        valueLocation: 'value'
```
