### DISCUSSION TITLE
AWS Sqs queueURL filter or Regex

### DISCUSSION THREAD

**Discussion by noamgreen** [kedacore/keda#3769] [General]
HI , new to keda 

i wander if we can regex "queueURL"
queueURL: https://queue.amazonaws.com/xxxxxxxxxxxxx/my-q-func-* <---- regex
as i can have one server that listen to many queues 
my-q-func-1
my-q-func-2
etc ....

and can we add list of queues

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: dev
spec:
  scaleTargetRef:
    name: dev-notification-processor-high
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-trigger-auth-aws-credentials
        kind: ClusterTriggerAuthentication
      metadata:
        queueURL: 
          - https://queue.amazonaws.com/xxxxxxxxxxxxxx/Organization-0
          - https://queue.amazonaws.com/xxxxxxxxxxxxxx/Organization-1
          - https://queue.amazonaws.com/xxxxxxxxxxxxxx/Organization-2
          - https://queue.amazonaws.com/xxxxxxxxxxxxxx/Organization-3
        queueLength: "1"
        awsRegion: "us-east-1"
        identityOwner: operator


```
Thanks
