### DISCUSSION TITLE
Azure AD Pod Identity using existing pod identity

### DISCUSSION THREAD

**Discussion by AnthonyDewhirst** [kedacore/keda#3776] [Q&A / Need Help]
Hi, I am not sure that I have this correct, but this was my understanding of how the feature mentioned in (https://github.com/kedacore/keda/issues/2656 and https://keda.sh/docs/2.8/authentication-providers/azure-ad-pod-identity/) would work:

Image:
![keda](https://user-images.githubusercontent.com/642569/197764626-e9fc9956-f0eb-4732-b9ca-865626345c61.png)

That by using the pod identity, we wouldn't need a "fallback" identity that keda would use by default.
Is this not correct?

I can't seem to work out how to get this to work. From the documentation supplied, it's not clear to me what value to place in "What value here"

```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-name
spec:
  podIdentity:
    provider: azure           
    identityId: <What value here>
```

I think from reading through the github issue, that it was clientId from the AzureIdentity
```yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ .Values.identity.name }}
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  type: 0
  resourceID: {{ .Values.identity.resourceId }}
  clientID: {{ .Values.identity.clientId }} # <--- this value
```
But I haven't had any luck getting this to work. I have also tried putting the metadata.name, but again, no dice.

MUST I have the fall back identity? 

What I would love to have is keda deployed _without_ setting podIdentity.activeDirectory.identity
And that all the bindings are within the workload namespace.

I haven't had a working solution using a setting where TriggerAuthentication.spec.podIdentity.identityId is set
