### DISCUSSION TITLE
Does keda create self signed certificate?

### DISCUSSION THREAD

**Discussion by smartaquarius10** [kedacore/keda#3816] [Q&A / Need Help]
Team,

As keda executes custom metrics server. Does it creates the self signed certificate while running. 

If yes, the is there any procedure to pass our own certificate. 

Kindly suggest. Thank you. 

Kind Regards,
Tanul

**Comment by zroubalik** [comment]
Yeah, by default KEDA Metrics Server uses self signed certificates. You can provide your own, you can specify that in the `args` section in the KEDA Metrics Server Deployment:

For example:
```yaml
...
args:
    - '--client-ca-file=/cabundle/service-ca.crt'
    - '--tls-cert-file=/certs/tls.crt'
    - '--tls-private-key-file=/certs/tls.key'
...
```

If you use your own CA bundle, you should also update the `v1beta1.external.metrics.k8s.io` `APIService` resource, that is created by KEDA installation. You should also make sure that `insecureSkipTLSVerify` is not set to `true`.

eg:
```yaml
kind: APIService
apiVersion: apiregistration.k8s.io/v1
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    namespace: keda
    name: keda-metrics-apiserver
    port: 443
  group: external.metrics.k8s.io
  version: v1beta1
  caBundle: >-
    LAABSDFS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t.......
```
