### DISCUSSION TITLE
Keda with EventHub

### DISCUSSION THREAD

**Discussion by marcelloraffaele** [kedacore/keda#3869] [Q&A / Need Help]
Hi Team,
I am trying to use keda to scale pod number using the number of messages inside an Azure Event Hub.
I followed the documentation but I am getting the following error inside the Operator:

```
2022-11-16T18:06:32Z    ERROR    scalehandler    Error getting scale decision    {"scaledobject.Name": "azure-eventhub-scaledobject", "scaledObject.Namespace": "default", "scaleTarget.Name": "azureeventhub-consumer", "error": "unable to get unprocessedEventCount for isActive: unable to get checkpoint from storage: %!s(<nil>)"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
    /workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
    /workspace/pkg/scaling/scale_handler.go:149
```

My configuration is the following:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-eventhub-scaledobject
  namespace: default
  labels:
    deploymentName: azureeventhub-consumer
spec:
  scaleTargetRef:
    name: azureeventhub-consumer
  triggers:
  - type: azure-eventhub
    metadata:
      connectionFromEnv: EVENTHUB_CONNECTIONSTRING
      storageConnectionFromEnv: STORAGE_CONNECTIONSTRING
      consumerGroup: $Default
      unprocessedEventThreshold: '64'
      blobContainer: 'test-container'
```
and the env vars are correctly set on deployment.

Can you help me to understand where's my mistake?

Thank you,
RM
