### DISCUSSION TITLE
Error from server: exactly one ScaledObject should match label

### DISCUSSION THREAD

**Discussion by hajdukda** [kedacore/keda#3976] [Q&A / Need Help] [answered]
Hey,

I have few scaled object like this:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: some-scaler-{uniqueIdentifierName}
spec:
  scaleTargetRef:
    name: some-deployment-{differentDeployment}
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      name: some-hpa-{SomethingUnique}
      behavior:
         .... doesnt matter whats here
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
    - type: prometheus
      metadata:
        serverAddress: http://prometheus:9090
        metricName: my_metric_name{uniqueName}
        metricType: AverageValue
        threshold: "500"
        query: max(rabbitmq_messages{queue="something{uniqueName}"})
        ignoreNullValues: "false"
```
When Im quering API to get the latest value of my metric - api returns whats in title...

```
kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/something/s1-prometheus-my_metric_name"
Error from server: exactly one ScaledObject should match label
```

MetricsServer ofcourse reports the same, "soemthing something should match label"

Funny enough that my HPA reports:

```
ValidMetricFound    the HPA was able to successfully calculate a replica count from external metric s1-prometheus-my_metric_name
```

But getting metric value through API still fails.. Does anyone has any idea why that might be the case ?

ps. Status of my scaler - for which Im quering API is:

```
Status:
  Conditions:
    Message:  ScaledObject is defined correctly and is ready for scaling
    Reason:   ScaledObjectReady
    Status:   True
    Type:     Ready
    Message:  Scaling is performed because triggers are active
    Reason:   ScalerActive
    Status:   True
    Type:     Active
    Message:  No fallbacks are active on this scaled object
    Reason:   NoFallbackFound
    Status:   False
    Type:     Fallback
  External Metric Names:
    s1-prometheus-my_metric_name..
  Health:
    s1-prometheus-my_metric_name..:
      Number Of Failures:  0
      Status:              Happy
  Hpa Name:                my-hpa
```
