### DISCUSSION TITLE
Keda integrate with AWS cloudwatch

### DISCUSSION THREAD

**Discussion by bdshibly** [kedacore/keda#4009] [Q&A / Need Help]
Hi,

Hi,

I am trying to scale pods based on cloudwatch metrics. Here is my yaml

```
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: myapp
  namespace: default
spec:
  podIdentity:
    provider: aws-eks
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: myapp
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: aws-cloudwatch
    metadata:
      namespace: AWS/ApplicationELB
      dimensionName: LoadBalancer
      dimensionValue: app/k8s-default-myapp/hash
      metricName: RequestCount
      targetMetricValue: "8"
      minMetricValue: "0"
      identityOwner: operator
      awsRegion: us-east-1
      metricStatPeriod: "60"
      metricStat: "Sum"
      metricCollectionTime: "120"
    authenticationRef:
      name: myapp

```

Though RequestCountPerTarget becomes more than 10, the pods never get scaled up. IAM is OK. Here is the log I found.

`2022-12-12T22:10:40.361Z        INFO    controller.scaledobject Reconciling ScaledObject        {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "myapp", "namespace": "default"}`

Could you help me integrating keda with AWS cloudwatch?

Cheers
Ferdous Shibly
