### DISCUSSION TITLE
Is there a way to scale number of pods by a multiple of queryValue?

### DISCUSSION THREAD

**Discussion by Zonalds** [kedacore/keda#4027] [Q&A / Need Help]
I am using MongoDB and here is my YAML:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject-encoder
  namespace: default
spec:
  scaleTargetRef:
    # kind: Deployment
    name: encoder
  pollingInterval: 15
  cooldownPeriod: 7000
  maxReplicaCount: 5000
  minReplicaCount: 50
  triggers:
    - type: mongodb
      metadata:
        dbName: "vedx"
        collection: "lists"
        query: '{"status.statusMsg":"encoding"}'
        queryValue: "1"
        metricName: "global-metric"
      authenticationRef:
        name: mongodb-trigger
```

I noticed that for each mongo result found, a pod is created. So I guess my question is; how do I scale by say 10 for each new mongo result found?
