### DISCUSSION TITLE
Kafka scaler attribute bootstrapServersFromEnv does not pick values from environment variable set in docker image

### DISCUSSION THREAD

**Discussion by milosz-mm** [kedacore/keda#4070] [General] [answered]
Hi,

I'm trying to set Kafka scaler to take bootstrap servers from environment variable by using **bootstrapServersFromEnv**. 

This works perfectly if environment variable is set in container attribute in k8s Deployment, as is described in #3675. 

However if the environment variable is set in docker image, KEDA does not pick the value and `kubectl describe so` shows errors saying it cannot connect to Kafka brokers. Below is sample docker image and scaled object definition.

Does KEDA support using environment variables set in docker images? If so I would appreciate any assistance regarding how to set up this. Thank you.

Dockerfile
```
FROM ubi8/openjdk-11
ENV KAFKA_BOOTSTRAP_SERVERS=server1:9092
...
```

ScaledObject
```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    deploymentName: my-deploymeny
  pollingInterval: 30
  triggers:
  - type: kafka
    metadata:
      bootstrapServersFromEnv: KAFKA_BOOTSTRAP_SERVERS
      consumerGroup: my-group
      topic: my-topic
```
