### DISCUSSION TITLE
Kafka scaler - "error creating kafka client: kafka: client has run out of available brokers to talk to: EOF"

### DISCUSSION THREAD

**Discussion by nkfirdigi** [kedacore/keda#4090] [Q&A / Need Help] [answered]
Hi
I'm using kafka scaler
Keda version 2.9.1
using kafka confluent cloud
Getting error "error creating kafka client: kafka: client has run out of available brokers to talk to: EOF" in keda operator
I used various versions  "0.10.x.0" up to "3.3.1", got the same error.
Appreciate any suggestion, 

my kafka scaler:
```
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: pkc-yyyyyy.aws.confluent.cloud:9092
        consumerGroup: typed-consumer      
        topic: keda-test
        lagThreshold: "2"
        activationLagThreshold: "1"
        offsetResetPolicy: "latest"
        scaleToZeroOnInvalidOffset: "true"
        allowIdleConsumers: "true"
        version: "0.10.2.0"
      authenticationRef:
        name: keda-trigger-auth-kafka-credential

```

**Comment by nkfirdigi** [comment, marked as answer]
Just for reference
I was using the wrong property name
I used authMode (from keda 1.4) instead of "sasl" which is the correct property name for keda 2.9 I'm using.
so I was able to connect to confluent cloud with following settings

```
apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
data:
  sasl: "cGxhaW50ZXh0" # plaintext base 64 encoded
  tls: "ZW5hYmxl" # enable base 64 encoded
  username: $(secrets.kafka.username)
  password: $(secrets.kafka.password
```
