### DISCUSSION TITLE
Fallback isn't working for KEDA - NoFallbackFound

### DISCUSSION THREAD

**Discussion by ralimardanov** [kedacore/keda#4111] [Q&A / Need Help] [answered]
Hi everyone!

I'm trying to use New Relic scaler for Keda and everything is working pretty fine, except for fallback method. 
This is how my configuration looks like:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-scaledobject
  namespace: test
spec:
  scaleTargetRef:
    name: test
    apiVersion: apps/v1
  pollingInterval: 5
  cooldownPeriod: 10
  minReplicaCount: 4
  maxReplicaCount: 20
  fallback:                                          
    failureThreshold: 1                          
    replicas: 10 
  triggers:
    - type: new-relic
      metricType: AverageValue
      metadata:
        account: '<redacted>'
        queryKey: <redacted>
        region: "US"
        nrql: "SELECT rate(count(apm.service.transaction.duration), 1 minute) FROM Metric WHERE (entity.guid = '<redacted>') AND (transactionType = 'Web') SINCE 60 seconds AGO"
        activationThreshold: '25'
        threshold: '30'
        noDataError: "true"
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:                 
      name: keda-hpa-test-scaledobject
      behavior:                                      
        scaleDown:
          stabilizationWindowSeconds: 180
          policies:
          - type: Percent
            value: 25
            periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          selectPolicy: Max

```

It's always in False/noFallbackFound state for fallback and I also tried to test it by removing account field:
```
NAME                          SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   TRIGGERS    AUTHENTICATION   READY   ACTIVE    FALLBACK   AGE
test-scaledobject   apps/v1.Deployment  test    4     20    new-relic                    False   Unknown   False      48m

```

```
status:
  conditions:
    - message: Failed to ensure HPA is correctly created for ScaledObject
      reason: ScaledObjectCheckFailed
      status: 'False'
      type: Ready
    - message: ScaledObject check failed
      reason: UnkownState
      status: Unknown
      type: Active
    - message: No fallbacks are active on this scaled object
      reason: NoFallbackFound
      status: 'False'
      type: Fallback
```

And I see such messages in HPA output:
`unable to get external metric <redacted>/s0-new-relic/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: test-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: error when getting scalers error parsing new-relic metadata: no account given`

I was expecting, that if something goes wrong, it should scale up from 4 to 10 pods.
Am I doing something wrong?
Thanks
