### DISCUSSION TITLE
Use keda operator with karpenter

### DISCUSSION THREAD

**Discussion by AmmarRami** [kedacore/keda#4174] [General] [answered]
Hello,

We use the selenium grid scaler of keda operator in our kubernets cluster for autoscale chromes node according to arrived tests request.
Our infra team added recently karpenter in the kubernetes cluster to optimize kubernetes nodes provisionning.
With karpenter I shoud have in my chrome pod this annotation:
annotations:
    karpenter.sh/do-not-evict: "true"
I added this annotation to my deployment. But when ked autoscale chrome pods the annotation is not added. So my pod is evicted with karpenter, Keda will create a new pod but the current session of test is lost.

Does it exist a method to allow keda operator to pass the annotation from deployment to created pod? I saw the possible metadata values of scaledObject but I dont find how define it.

My deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    **karpenter.sh/do-not-evict: "true"**
    meta.helm.sh/release-name: prod-selenium-chrome
    meta.helm.sh/release-namespace: fr-selenium-npr
  creationTimestamp: "2023-01-31T16:58:15Z"
  generation: 26
  labels:
    app: prod-selenium-node-chrome
    app.kubernetes.io/managed-by: Helm
    chart: chart-prod-selenium-node
```
.
.
.
My ScaledObject
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    meta.helm.sh/release-name: prod-selenium
    meta.helm.sh/release-namespace: fr-selenium-npr
  creationTimestamp: "2023-01-25T14:09:42Z"
  finalizers:
  - finalizer.keda.sh
  generation: 1
  labels:
    app: prod-selenium-grid-chrome-scaledobject
    app.kubernetes.io/managed-by: Helm
    chart: chart-prod-selenium
    deploymentName: prod-selenium-node-chrome-deploy
    scaledobject.keda.sh/name: prod-selenium-grid-chrome-scaledobject
    manager: keda-adapter
    operation: Update
    subresource: status
  - apiVersion: keda.sh/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
        f:externalMetricNames: {}
        f:hpaName: {}
        f:lastActiveTime: {}
        f:originalReplicaCount: {}
        f:scaleTargetGVKR:
          .: {}
          f:group: {}
          f:kind: {}
          f:resource: {}
          f:version: {}
        f:scaleTargetKind: {}
    manager: keda
    operation: Update
    subresource: status
  name: prod-selenium-grid-chrome-scaledobject
  namespace: fr-selenium-npr
spec:
  maxReplicaCount: 10
  minReplicaCount: 0
  scaleTargetRef:
    name: prod-selenium-node-chrome-deploy
  triggers:
  - metadata:
      browserName: chrome
      url: http://prod-selenium-hub-service.fr-selenium-npr:4444/graphql
    type: selenium-grid
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is performed because triggers are active
    reason: ScalerActive
    status: "True"
    type: Active
  - message: No fallbacks are active on this scaled object
    reason: NoFallbackFound
    status: "False"
    type: Fallback
  externalMetricNames:
  - s0-seleniumgrid-chrome
  health:
    s0-seleniumgrid-chrome:
      numberOfFailures: 0
      status: Happy
  hpaName: keda-hpa-prod-selenium-grid-chrome-scaledobject
  lastActiveTime: "2023-02-01T10:44:09Z"
  originalReplicaCount: 0
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment
```

Thanks
