### DISCUSSION TITLE
Could not find stackdriver metric with filter

### DISCUSSION THREAD

**Discussion by pkhadka56** [kedacore/keda#4252] [Q&A / Need Help]
Hello,

I am using gcp-stackdriver to scale but I am getting the following error in keda-operator pod
```
ERROR scalehandler  error getting metric for scaler {"scaledObject.Namespace": "ns", "scaledObject.Name": "gcp-stackdriver-scaledobject", "scaler": "stackdriverScaler", "error": "could not find stackdriver metric with filter metric.type=\"loadbalancing.googleapis.com/https/backend_request_count\" AND resource.label.backend_target_name=\"..."}
```

Here is the log from keda metrics apiserver pod
```
E0217 14:19:23.341756       1 status.go:71] apiserver received an error that is not an metav1.Status: &status.Error{s:(*status.Status)(0xc0004b2e70)}: rpc error: code = Unknown desc = error when getting metric values no matching metrics found for s0-gcp-stackdriver-...
```

Here is my scaledobject yaml file:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: gcp-stackdriver-scaledobject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment
  pollingInterval:  20
  cooldownPeriod:   240
  idleReplicaCount: 0
  minReplicaCount:  1
  maxReplicaCount:  3    
  triggers:
  - type: gcp-stackdriver
    authenticationRef:
      name: keda-trigger-auth-gcp-credentials
    metadata:
      projectId: "project-id"
      filter: 'metric.type="loadbalancing.googleapis.com/https/backend_request_count" AND resource.label.backend_target_name="...'
      targetValue: '100'
      activationTargetValue: "0"
```

Any suggestions?
