### DISCUSSION TITLE
ERROR azure_eventhub_scaler Blob container :  not found to use checkpoint strategy, getting unprocessed event count without checkpoint

### DISCUSSION THREAD

**Discussion by haorzhan** [kedacore/keda#4257] [Q&A / Need Help]
I am trying to set up the C# EventHub triggered Azure Function but I keep getting erros:

2023-02-21T08:33:54Z ERROR azure_eventhub_scaler Blob container :  not found to use checkpoint strategy, getting unprocessed event count without checkpoint {"type": "ScaledObject", "namespace": "default", "name": "kedademo", "error": "-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /workspace/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=ContainerNotFound) =====\nDescription=The specified container does not exist.\nRequestId:f07955d5-c01e-0001-6fcf-45a862000000\nTime:2023-02-21T08:33:54.9118884Z, Details: \n   Code: ContainerNotFound\n   GET https://kedademo.blob.core.windows.net/azure-webjobs-eventhub/kedademoeventhub.servicebus.windows.net/kedatestingeventhub/kedaeventhubconsumergroup/0?timeout=61\n   Authorization: REDACTED\n   User-Agent: [Azure-Storage/0.15 (go1.18.8  linux)]\n   X-Ms-Client-Request-Id: [9d2fb714-89e1-4f44-64f5-30080b7f8e7a]\n   X-Ms-Date: [Tue, 21 Feb 2023 08:33:54 GMT]\n   X-Ms-Version: [2020-10-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 404 The specified container does not exist.\n   Content-Length: [225]\n   Content-Type: [application/xml]\n   Date: [Tue, 21 Feb 2023 08:33:54 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [9d2fb714-89e1-4f44-64f5-30080b7f8e7a]\n   X-Ms-Error-Code: [ContainerNotFound]\n   X-Ms-Request-Id: [f07955d5-c01e-0001-6fcf-45a862000000]\n   X-Ms-Version: [2020-10-02]\n\n\n"}

From the error message, looks like the container blob is not found. Should I manually create the container blob?

Here is the yaml file:
```
data:
  AzureWebJobsStorage: storageconnectionstirng
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
  EVENTHUB_CONNECTIONSTRING: eventhubconnectionstring 
apiVersion: v1
kind: Secret
metadata:
  name: kedademo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kedademo
  labels:
    app: kedademo
spec:
  selector:
    matchLabels:
      app: kedademo
  template:
    metadata:
      labels:
        app: kedademo
    spec:
      containers:
      - name: kedademo
        image: kedademo.azurecr.io/kedademo:v4
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: KedaEventHub
        - name: storageAccountConnectionString
          valueFrom: 
            secretKeyRef:
              name: storageaccountconnectiostring
              key: storageAccountConnectionString
        - name: kustoappkey
          valueFrom: 
            secretKeyRef:
              name: kustoappkey
              key: kustoappkey
        - name: ehubconnectionstring
          valueFrom: 
            secretKeyRef:
              name: ehubconnectionstring
              key: ehubconnectionstring
        envFrom:
        - secretRef:
            name: kedademo
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      imagePullSecrets: 
      - name: containerregistrysecret
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kedademo
  labels: {}
spec:
  scaleTargetRef:
    name: kedademo
  triggers:
  - type: azure-eventhub
    metadata:
      connectionFromEnv: ehubconnectionstring
      storageConnectionFromEnv: AzureWebJobsStorage
      consumerGroup: kedaeventhubconsumergroup
      checkpointStrategy: azureFunction
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 100 # Optional. Default: 100
  pollingInterval: 1  # Optional. Default: 30 seconds
  cooldownPeriod:  10 # Optional. Default: 300 second
---


```
