### DISCUSSION TITLE
cloudwatch trigger giving averageValue Invalid value error

### DISCUSSION THREAD

**Discussion by lana-rosenbaum** [kedacore/keda#4317] [Q&A / Need Help]
My ScaledObject is reporting this error:  `error parsing cloudwatch metadata: dimension name not given`, despite the fact that I have expression set in my trigger meta data.

```
triggers:
    - metadata:
        activationTargetMetricValue: '500'
        awsRegion: us-west-1
        expression: SELECT MAX(default_queue_length) FROM “My App"
        identityOwner: operator
        metricCollectionTime: '180'
        metricName: default_queue_length
        metricStat: Maximum
        metricStatPeriod: '60'
        minMetricValue: '0'
        namespace: My App
        targetMetricValue: '0'
      type: aws-cloudwatch
```
I can't set dimensionName because there is none for the metric I'm referencing. 

I'm using KEDA version 2.8.1.

Any help would be greatly appreciated :)
