### DISCUSSION TITLE
We're eager to learn about your KEDA deployments!

### DISCUSSION THREAD

**Discussion by tomkerkhove** [kedacore/keda#4410] [Show and tell]
As open-source maintainers, we are eager to learn about how you are using KEDA and how big of a deployment you have!

If you are allowed to and want to share, we'd love to learn how many scaled objects/scaled jobs you have in your cluster and what your experience has been!

We are also considering introducing our own performance benchmarking which you can learn more about on https://github.com/kedacore/keda/issues/4411.

**Comment by wiseelf** [comment]
Current amount of ScaledJobs and ScaledObjects.
``` 
% k get so -A --no-headers=true | wc -l
    1426
% k get sj -A --no-headers=true | wc -l
    704
 ```
 Had an issue with kube-api request rate, so I have to tune some keda parameters and I'm using cached metrics as well.
 My config for KEDA (maybe the values too high, but it works well)
```
## Extra KEDA Operator and Metrics Adapter container arguments
extraArgs:
  keda:
    kube-api-qps: 150
    kube-api-burst: 250
  metricsAdapter:
    kube-api-qps: 150
    kube-api-burst: 250

## Extra environment variables that will be passed onto KEDA operator and metrics api service
env:
  - name: KEDA_SCALEDJOB_CTRL_MAX_RECONCILES
    value: "50"
  - name: KEDA_SCALEDOBJECT_CTRL_MAX_RECONCILES
    value: "100"
  - name: KEDA_METRICS_CTRL_MAX_RECONCILES
    value: "50"
```
For the SO,SJ i do specify `useCachedMetrics: true`
