### DISCUSSION TITLE
Kafka scaling doesn't work as expected

### DISCUSSION THREAD

**Discussion by krishna-kariya** [kedacore/keda#4414] [Q&A / Need Help]
Hi all,  
I have been trying to investigate issue related to Kafka Scaling. I have created an Azure Container App with Kafka scale rule. The issue is that the scaling from 1->0 after cooldown period doesn't happen as expected. Even, scaling from 1->n doesn't happen for this container app when I produce messages on Kafka topic. I have added the details related to the scale object for reference. Keda version for the container apps environment is 2.9.2. I checked the scaledobject and hpa and they are fine. I checked the logs of metrics api server and operator, but I couldn't find any errors or warnings. 
I got the same behavior on AKS cluster with Keda installed. Please let me know if any further details are required. Any help is appreciated. Thanks. 

tagging @tomkerkhove @JorTurFer @zroubalik 

cc: @krishnajaju @lpapudippu

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: default
stringData:
  sasl: "plaintext"
  username: "$ConnectionString"
  password: "<EventHub_Connection_String>"
  tls: "enable"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: default
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-secrets
    key: sasl
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: keda-kafka-secrets
    key: password
  - parameter: tls
    name: keda-kafka-secrets
    key: tls
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: kafka-pod
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 30
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: <EventHubNs>.servicebus.windows.net:9093
      consumerGroup: $Default 
      topic: topic-new
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
```
