### DISCUSSION TITLE
Can't get azureKeyVault TriggerAuthentication to work with Azure Pipelines Scaler on a ScaledJob

### DISCUSSION THREAD

**Discussion by ericyew** [kedacore/keda#4434] [Q&A / Need Help] [answered]
Have been trying to get TriggerAuthentication using azureKeyVault with the Azure Pipelines Scaler on a ScaledJob but I keep getting an error with the personalAccessToken. 
Is there a way to check which component is failing as I don't see any info from the keda operator pod logs. 
This is all I see in the logs:

> 2023-04-04T08:38:11Z    ERROR   Error getting scalers   {"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "ScaledJob": {"name":"infr-adocst-01-prd-aks-aue-test-agent-scaledjob","namespace":"azdevopstest"}, "namespace": "azdevopstest", "name": "infr-adocst-01-prd-aks-aue-test-agent-scaledjob", "reconcileID": "445a10e5-efdb-46e6-8377-6fb2b8755860", "error": "error parsing azure Pipelines metadata: no personalAccessToken given"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledJobReconciler).reconcileScaledJob
        /workspace/controllers/keda/scaledjob_controller.go:172
github.com/kedacore/keda/v2/controllers/keda.(*ScaledJobReconciler).Reconcile
        /workspace/controllers/keda/scaledjob_controller.go:139
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:323
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235
2023-04-04T08:38:11Z    ERROR   Failed to ensure ScaledJob is correctly created {"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "ScaledJob": {"name":"infr-adocst-01-prd-aks-aue-test-agent-scaledjob","namespace":"azdevopstest"}, "namespace": "azdevopstest", "name": "infr-adocst-01-prd-aks-aue-test-agent-scaledjob", "reconcileID": "445a10e5-efdb-46e6-8377-6fb2b8755860", "error": "error parsing azure Pipelines metadata: no personalAccessToken given"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledJobReconciler).Reconcile
        /workspace/controllers/keda/scaledjob_controller.go:142
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:323
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235
2023-04-04T08:38:11Z    ERROR   Reconciler error        {"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "ScaledJob": {"name":"infr-adocst-01-prd-aks-aue-test-agent-scaledjob","namespace":"azdevopstest"}, "namespace": "azdevopstest", "name": "infr-adocst-01-prd-aks-aue-test-agent-scaledjob", "reconcileID": "445a10e5-efdb-46e6-8377-6fb2b8755860", "error": "error parsing azure Pipelines metadata: no personalAccessToken given"}

This is my yaml file:
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azdevops-triggerauth
  namespace: azdevopstest
spec:
  azureKeyVault:                                                     
    vaultUri: https://devops-kvt-ey.vault.azure.net/            
    podIdentity:                                      
      provider: azure       
      identityId: select-ado-kub-prd-mid-aue
    cloud:                                                                
      type: AzurePublicCloud 
    secrets:                                                            
    - parameter: personalAccessToken                               
      name: 'pat-sa-azure-prd-ado-buildagent'
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: infr-aks-test-agent-scaledjob
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: azdevops-agent-job
          image: acrname.azurecr.io/aks-build-agent:1.3.8
          imagePullPolicy: Always
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          env:
          - name: AZP_URL
            value: https://dev.azure.com/EYOrg
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            value: AKS-Agent-Test
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
        volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: devops-kvt-ey
  maxReplicaCount: 4
  pollingInterval: 10
  rollout: {}
  scalingStrategy:
    strategy: "default"               
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: "56"
      organizationURLFromEnv: "AZP_URL"
    authenticationRef:
      name: azdevops-triggerauth
```

Any suggestion how to troubleshoot further or where to look?
Also, is it  possible for the secret from the TriggerAuth to be reference in the job template spec for AZP_TOKEN env variable?

Thannks
