### DISCUSSION TITLE
Kafka consumers scaling from zero with timed messages

### DISCUSSION THREAD

**Discussion by sansmoraxz** [kedacore/keda#4466] [Q&A / Need Help] [answered]
Say I have a scaler defined something like this:

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-scaler-1
spec:
  scaleTargetRef:
    name: my-statefulset-1
    kind: StatefulSet
  pollingInterval: 5
  cooldownPeriod: 300
  idleReplicaCount: 0
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: "kafka-broker-1.kafka-endpoints.svc.cluster.local:9092,kafka-broker-2.kafka-endpoints.svc.cluster.local:9092"
      consumerGroup: MyConsumerGroup
      topic: consumer.data
      lagThreshold: "10000"
      offsetResetPolicy: latest
      activationLagThreshold: "1"
```

The pods in `my-statefulset-1` have `auto.offset.reset` as `latest`

Let's say the topic `consumer.data` is newly created and no offsets has been commited yet. The pods are scaled to `minReplicaCount` which is to be expected. And after 5 mins of empty queue, the pods will be scaled down to 0.

Now let's assume that the topic `consumer.data` is set to clear old data with `log.retention.hours=1` 

If a new record is added to the queue, after 1 hour; the scaler occasionally refuses to scale out, with no errors being logged, and status as "Scaling is not performed because triggers are not active"

This behavior sticks even after the scaler is recreated. Hell even manually scaling the pod starts to scale it back down to zero.

So any suggestions on what I may be missing?

keda version: 2.10.0
kafka version: 3.3.2
