### DISCUSSION TITLE
Error from server (ServiceUnavailable): the server is currently unable to handle the request

### DISCUSSION THREAD

**Discussion by FaraSys** [kedacore/keda#4484] [Q&A / Need Help] [answered]
Hi.
I deployed keda 2.10 using helm. I configure scaleObject with prometheus trigger.
I see in logs keda-operator (pod)
```
2023-04-28T07:10:29Z	DEBUG	scale_handler	Getting metrics and activity from scaler	{"scaledObject.Namespace": "applications", "scaledObject.Name": "prometheus-scaledobject", "scaler": "prometheusScaler", "metricName": "s0-prometheus-prometheus", "metrics": [{"metricName":"s0-prometheus-prometheus","metricLabels":null,"timestamp":"2023-04-28T07:10:29Z","value":"0"}], "activity": false, "scalerError": null}
2023-04-28T07:10:29Z	DEBUG	scaleexecutor	ScaleTarget no change	{"scaledobject.Name": "prometheus-scaledobject", "scaledObject.Namespace": "applications", "scaleTarget.Name": "my-web"}
2023-04-28T07:10:39Z	DEBUG	scale_handler	Getting metrics and activity from scaler	{"scaledObject.Namespace": "applications", "scaledObject.Name": "prometheus-scaledobject", "scaler": "prometheusScaler", "metricName": "s0-prometheus-prometheus", "metrics": [{"metricName":"s0-prometheus-prometheus","metricLabels":null,"timestamp":"2023-04-28T07:10:39Z","value":"2"}], "activity": true, "scalerError": null}
2023-04-28T07:10:39Z	DEBUG	scale_handler	Scaler for scaledObject is active	{"scaledObject.Namespace": "applications", "scaledObject.Name": "prometheus-scaledobject", "scaler": "prometheusScaler", "metricName": "s0-prometheus-prometheus"}
2023-04-28T07:10:49Z	DEBUG	scale_handler	Getting metrics and activity from scaler	{"scaledObject.Namespace": "applications", "scaledObject.Name": "prometheus-scaledobject", "scaler": "prometheusScaler", "metricName": "s0-prometheus-prometheus", "metrics": [{"metricName":"s0-prometheus-prometheus","metricLabels":null,"timestamp":"2023-04-28T07:10:49Z","value":"0"}], "activity": false, "scalerError": null}
2023-04-28T07:10:49Z	DEBUG	scaleexecutor	ScaleTarget no change	{"scaledobject.Name": "prometheus-scaledobject", "scaledObject.Namespace": "applications", "scaleTarget.Name": "my-web"}
```
And logs in keda-operator-metrics-apiserver:
```
I0427 14:26:01.528559       1 provider.go:231] keda_metrics_adapter/provider "msg"="KEDA Metrics Server received request for list of all provided external metrics names" 
`I0427 14:26:01.528955       1 httplog.go:132] "HTTP" verb="GET" URI="/apis/external.metrics.k8s.io/v1beta1" latency="965.986µs" userAgent="Go-http-client/2.0" audit-ID="d7066b57-5533-40f6-a5b1-7a5a82ec57ad" srcIP="10.128.61.201:16625" resp=2`
```
But when i do **kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1"** 
i get **Error from server (ServiceUnavailable): the server is currently unable to handle the request**

kubectl get apiservice --all-namespaces:
`v1beta1.external.metrics.k8s.io        keda/keda-operator-metrics-apiserver   True        23m`

kubectl get apiservice v1beta1.external.metrics.k8s.io -o yaml:
```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  annotations:
    meta.helm.sh/release-name: keda
    meta.helm.sh/release-namespace: keda
  creationTimestamp: "2023-04-27T14:05:47Z"
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: v1beta1.external.metrics.k8s.io
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.10.1
    helm.sh/chart: keda-2.10.2
  name: v1beta1.external.metrics.k8s.io
  resourceVersion: "78710591"
  uid: 152a87ef-c2a6-46d2-bbc1-cddbc67ca5d1
spec:
  group: external.metrics.k8s.io
  groupPriorityMinimum: 100
  service:
    name: keda-operator-metrics-apiserver
    namespace: keda
    port: 443
  version: v1beta1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2023-04-27T14:05:58Z"
    message: all checks passed
    reason: Passed
    status: "True"
    type: Available
```

My scaleObject yaml:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  namespace: applications
spec:
  scaleTargetRef:
    name: my-web
  minReplicaCount: 2       # Меньше одной реплики не хотим
  maxReplicaCount: 3       # А то же время больше пяти тоже
  pollingInterval: 10      # Как часто ходить за метрикой
  cooldownPeriod:  60
  triggers: 
  - type: prometheus
    metadata:
      threshold: '10'
      query: sum(irate(nginx_ingress_controller_requests{service="info4me-web"}[1m])) by (service)
      unsafeSsl: "true"
```
kubectl describe scaledobjects.keda.sh -n applications prometheus-scaledobject
```
Status:
  Conditions:
    Message:  ScaledObject is defined correctly and is ready for scaling
    Reason:   ScaledObjectReady
    Status:   True
    Type:     Ready
    Message:  Scaling is not performed because triggers are not active
    Reason:   ScalerNotActive
    Status:   False
    Type:     Active
    Status:   Unknown
    Type:     Fallback
  External Metric Names:
    s0-prometheus-prometheus-http_requests_total
  Hpa Name:                keda-hpa-prometheus-scaledobject
  Last Active Time:        2023-04-27T14:14:43Z
  Original Replica Count:  2
  Scale Target GVKR:
    Group:            apps
    Kind:             Deployment
    Resource:         deployments
    Version:          v1
  Scale Target Kind:  apps/v1.Deployment
Events:
  Type    Reason              Age   From           Message
  ----    ------              ----  ----           -------
  Normal  KEDAScalersStarted  24m   keda-operator  Started scalers watch
  Normal  ScaledObjectReady   24m   keda-operator  ScaledObject is ready for scaling
```
but its not scaling my deployment.
Help pls.

**Comment by JorTurFer** [comment]
> But when i do **kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1"**
> i get **Error from server (ServiceUnavailable): the server is currently unable to handle the request**

After v2.9 this doesn't work anymore due to internal changes. The correct way to do it is documented: https://keda.sh/docs/2.10/operate/metrics-server/
Basically, you need to add the scaledobject name to the request. This is because it's how the HPA controller does it

**Reply by FaraSys** [reply]
I try:
```
kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/applications/s0-prometheus-prometheus?labelSelector=scaledobject.keda.sh%2Fname%3Dscale-myapp-web"
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```
Namespace - applications
MetrikName: s0-prometheus-prometheus
SOName: scale-myapp-web
Kubernetes v24.2 and V26.3 (two cluster)
OS Ubuntu 22.04 LTS

**Reply by JorTurFer** [reply]
mmm. This is weird because your APIService looks healthy :/
do you see something if you list the available metrics?
`kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1"`

**Reply by FaraSys** [reply]
```
kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1"
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```

**Reply by JorTurFer** [reply]
Could you share the output of `kubectl describe apiservice v1beta1.external.metrics.k8s.io`?

**Reply by FaraSys** [reply]
```
root@kmaster-01:~# kubectl describe apiservice v1beta1.external.metrics.k8s.io
Name:         v1beta1.external.metrics.k8s.io
Namespace:    
Labels:       app.kubernetes.io/component=operator
              app.kubernetes.io/instance=keda
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=v1beta1.external.metrics.k8s.io
              app.kubernetes.io/part-of=keda-operator
              app.kubernetes.io/version=2.10.1
              helm.sh/chart=keda-2.10.2
Annotations:  meta.helm.sh/release-name: keda
              meta.helm.sh/release-namespace: keda
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2023-04-29T12:51:20Z
  Managed Fields:
    API Version:  apiregistration.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
          f:app.kubernetes.io/part-of:
          f:app.kubernetes.io/version:
          f:helm.sh/chart:
      f:spec:
        f:group:
        f:groupPriorityMinimum:
        f:service:
          .:
          f:name:
          f:namespace:
          f:port:
        f:version:
        f:versionPriority:
    Manager:      helm
    Operation:    Update
    Time:         2023-04-29T12:51:20Z
    API Version:  apiregistration.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .:
          k:{"type":"Available"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:reason:
            f:status:
            f:type:
    Manager:         kube-apiserver
    Operation:       Update
    Subresource:     status
    Time:            2023-04-29T12:51:20Z
  Resource Version:  106198158
  UID:               2c1fa03b-31ea-4fa0-8eff-ab9f6fd6d8c2
Spec:
  Group:                   external.metrics.k8s.io
  Group Priority Minimum:  100
  Service:
    Name:            keda-operator-metrics-apiserver
    Namespace:       keda
    Port:            443
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2023-04-29T12:51:40Z
    Message:               all checks passed
    Reason:                Passed
    Status:                True
    Type:                  Available
Events:                    <none>
```

**Reply by JorTurFer** [reply]
The apiservice isn't patched with the caBundle, so maybe the problem comes from there, the api server doesn't trust in the KEDA metrics server. How did you deploy KEDA?

**Reply by JorTurFer** [reply]
For example, this is how the apiservice should look:
```yaml
kubectl describe apiservice v1beta1.external.metrics.k8s.io
Name:         v1beta1.external.metrics.k8s.io
Namespace:    
Labels:       aadpodidbinding=keda
              app.kubernetes.io/name=v1beta1.external.metrics.k8s.io
              app.kubernetes.io/part-of=keda-operator
              app.kubernetes.io/version=main
Annotations:  <none>
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2023-05-02T09:24:11Z
  ... SOME METADATA FIELDS REMOVED ...
Spec:
  Ca Bundle:               LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFoTVJBd0RnWURWUVFLRXdkTFJVUkIKVDFKSE1RMHdDd1lEVlFRREV3UkxSVVJCTUI0WERUSXpNRFV3TWpBNE1qVXdNVm9YRFRNek1EUXlPVEE1TWpVdwpNVm93SVRFUU1BNEdBMVVFQ2hNSFMwVkVRVTlTUnpFTk1Bc0dBMVVFQXhNRVMwVkVRVENDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlczOWdwbmVnUmJYYnRodnFQUHpEcUFjYmUvbkR0WTlJWHAKc3RGMlNnQ0l1bkEra2ltQmgreWE4SXYydFIwcGlFR1BmS08yK2xTa2tZWkUxZ2NHSWt1Y3QwVEVKMnhHS205VAptRWdUTU1taE51a0gzcy85MElqTnZTdnpaVWVZUnZ3SG1iT0lhVlM4K1NLYWpuYUovb1VKYm9MZ1k2ZUowdEtnCm9rd1BxM3l5Y2VkTXVqc0RHZ3J1SHlHVmNVcVhrbzN0MDBxQld5YzJ0QTJRMzRrMjg3OHErMHRNbkZrU2YzNEgKYmZ2aW9ONGdwb1c3QURFd0tEUldySng1QUxYNENiU056MTQzM2lwN0VUL2JaS3grK1N1ekw1UFhBNFBWaTFTNwpIMzNkQWs4eFZwVWUvZ1RybmNIWFEwT0NkVzV5azFQbzZ5TXN0T0RhRkwwYUZkUFo0TmtDQXdFQUFhTlRNRkV3CkRnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRlB3OGxqWDYKd05KUTdoUGNadXhxYTNJakVIUmlNQThHQTFVZEVRUUlNQWFDQkV0RlJFRXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUo4TVE4dHpWejIzMmNkR0dYUkdkeklwcmRzTnkrOFFOVGR4cDh3L2poUlU3QjhVb2xzaFBkSFczQzRxCktmWXNWaU5TQ1BLSm0yTEphT1hNVjV4K3FYN1JscG1FUWk4Sy9FMko5YzNKcVF5UVBtUytjaFNIZEl1dmlrTVQKWmg0RXE1bGh3U1A5TUtNUUJockVTckpWS2FPYzYzUE91Vzd0WkQ0Y2NqTDdPMTZzMThsR0RQWGZCQnVuU3NEaQpoaXIzKzFOTHo0VVdFc01Ucm0wYmpDclJqWVZNRUFhb2xZNXhaQUxCMUNrdWNiM2ovMm9Kdkp1R1lKMElJakZ4CmM0NDRtcVRNNk5uN1czOHFhcUJIV3JEeHNvaXpYQXMwZmJNSENJMGM0NmE5b2NPa2s0d0NLeGU3c1R0MmlEOGIKMWJHUXdmQ0Facm1jYTBVejhLYkIvMmtFWmNBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  Group:                   external.metrics.k8s.io
  Group Priority Minimum:  100
  Service:
    Name:            keda-metrics-apiserver
    Namespace:       keda
    Port:            443
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2023-05-02T09:25:35Z
    Message:               all checks passed
    Reason:                Passed
    Status:                True
    Type:                  Available
Events:                    <none>
```

**Reply by FaraSys** [reply]
I used 
kubectl create namespace keda
helm install keda kedacore/keda --namespace keda -f values.yaml

```
# Default values for keda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  keda:
    repository: ghcr.io/kedacore/keda
    # Allows people to override tag if they don't want to use the app version
    tag:
  metricsApiServer:
    repository: ghcr.io/kedacore/keda-metrics-apiserver
    # Allows people to override tag if they don't want to use the app version
    tag:
  webhooks:
    repository: ghcr.io/kedacore/keda-admission-webhooks
    # Allows people to override tag if they don't want to use the app version
    tag:
  pullPolicy: Always

# Kubernetes cluster domain
clusterDomain: stk8s.example.com

crds:
  install: true
    
watchNamespace: ""

imagePullSecrets: []

operator:
  name: keda-operator
  replicaCount: 1
  # -- Affinity for pod scheduling https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/ for KEDA operator. Takes precedence over the `affinity` field
  affinity: {}
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #   - labelSelector:
    #       matchExpressions:
    #       - key: app
    #         operator: In
    #         values:
    #         - keda-operator
    #     topologyKey: "kubernetes.io/hostname"

metricsServer:
  replicaCount: 1
  # use ClusterFirstWithHostNet if `useHostNetwork: true` https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
  dnsPolicy: ClusterFirst
  useHostNetwork: false
  # -- Affinity for pod scheduling https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/ for Metrics API Server. Takes precedence over the `affinity` field
  affinity: {}
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #   - labelSelector:
    #       matchExpressions:
    #       - key: app
    #         operator: In
    #         values:
    #         - keda-operator-metrics-apiserver
    #     topologyKey: "kubernetes.io/hostname"

webhooks:
  enabled: false # This value will be removed in keda v2.12
  name: keda-admission-webhooks
  replicaCount: 1
  # -- Affinity for pod scheduling https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/ for KEDA operator. Takes precedence over the `affinity` field
  affinity: {}
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #   - labelSelector:
    #       matchExpressions:
    #       - key: app
    #         operator: In
    #         values:
    #         - keda-operator
    #     topologyKey: "kubernetes.io/hostname"
  failurePolicy: Ignore

upgradeStrategy:
  operator: {}
    # type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 1
    #   maxSurge: 1
  metricsApiServer: {}
    # type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 1
    #   maxSurge: 1
  webhooks: {}
    # type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 1
    #   maxSurge: 1

podDisruptionBudget: {}
  # operator:
  #   minAvailable: 1
  #   maxUnavailable: 1
  # metricServer:
  #   minAvailable: 1
  #   maxUnavailable: 1
  # webhooks:
  #   minAvailable: 1
  #   maxUnavailable: 1

# -- Custom labels to add into metadata
additionalLabels:
  {}
  # foo: bar

# -- Custom annotations to add into metadata
additionalAnnotations:
  {}
  # foo: bar

podAnnotations:
  keda: {}
  metricsAdapter: {}
  webhooks: {}
podLabels:
  keda: {}
  metricsAdapter: {}
  webhooks: {}

rbac:
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: keda-operator
  # Specifies whether a service account should automount API-Credentials
  automountServiceAccountToken: true
  # Annotations to add to the service account
  annotations: {}

podIdentity:
  activeDirectory:
    # Set to the value of the Azure Active Directory Pod Identity
    # See https://keda.sh/docs/concepts/authentication/#azure-pod-identity
    # This will be set as a label on the KEDA Pod(s)
    identity: ""
  azureWorkload:
    # Set to true to enable Azure Workload Identity usage.
    # See https://keda.sh/docs/concepts/authentication/#azure-workload-identity
    # This will be set as a label on the KEDA service account.
    enabled: false
    # Set to the value of the Azure Active Directory Client and Tenant Ids
    # respectively. These will be set as annotations on the KEDA service account.
    clientId: ""
    tenantId: ""
    # Set to the value of the service account token expiration duration.
    # This will be set as an annotation on the KEDA service account.
    tokenExpiration: 3600
  aws:
    irsa:
      # Set to true to enable AWS IAM Roles for Service Accounts (IRSA).
      enabled: false
      # Sets the token audience for IRSA.
      # This will be set as an annotation on the KEDA service account.
      audience: "sts.amazonaws.com"
      # Set to the value of the ARN of an IAM role with a web identity provider.
      # This will be set as an annotation on the KEDA service account.
      roleArn: ""
      # Sets the use of an STS regional endpoint instead of global.
      # Recommended to use regional endpoint in almost all cases.
      # This will be set as an annotation on the KEDA service account.
      stsRegionalEndpoints: "true"
      # Set to the value of the service account token expiration duration.
      # This will be set as an annotation on the KEDA service account.
      tokenExpiration: 86400

# Set this if you are using an external scaler and want to communicate
# over TLS (recommended). This variable holds the name of the secret that
# will be mounted to the /grpccerts path on the Pod
grpcTLSCertsSecret: ""

# Set this if you are using HashiCorp Vault and want to communicate
# over TLS (recommended). This variable holds the name of the secret that
# will be mounted to the /vault path on the Pod
hashiCorpVaultTLS: ""

logging:
  operator:
    ## Logging level for KEDA Operator
    # allowed values: 'debug', 'info', 'error', or an integer value greater than 0, specified as string
    # default value: info
    level: debug
    # allowed values: 'json' or 'console'
    # default value: console
    format: console
    ## Logging time encoding for KEDA Operator
    # allowed values are 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'
    # default value: rfc3339
    timeEncoding: rfc3339
  metricServer:
    ## Logging level for Metrics Server
    # allowed values: '0' for info, '4' for debug, or an integer value greater than 0, specified as string
    # default value: 0
    level: 4

  webhooks:
    ## Logging level for KEDA Operator
    # allowed values: 'debug', 'info', 'error', or an integer value greater than 0, specified as string
    # default value: info
    level: info
    # allowed values: 'json' or 'console'
    # default value: console
    format: console
    ## Logging time encoding for KEDA Operator
    # allowed values are 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'
    # default value: rfc3339
    timeEncoding: rfc3339

securityContext:
  operator:
    capabilities:
      drop:
      - ALL
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
  metricServer:
    capabilities:
      drop:
      - ALL
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
  webhooks:
    capabilities:
      drop:
      - ALL
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault

podSecurityContext:
  operator:
    runAsNonRoot: true
    # runAsUser: 1000
    # runAsGroup: 1000
    # fsGroup: 1000
  metricServer:
    runAsNonRoot: true
    # runAsUser: 1000
    # runAsGroup: 1000
    # fsGroup: 1000
  webhooks:
    runAsNonRoot: true
    # runAsUser: 1000
    # runAsGroup: 1000
    # fsGroup: 1000

service:
  type: ClusterIP
  portHttp: 80
  portHttpTarget: 8080
  portHttps: 443
  portHttpsTarget: 6443

  annotations: {}

# We provides the default values that we describe in our docs:
# https://keda.sh/docs/latest/operate/cluster/
# If you want to specify the resources (or totally remove the defaults), change or comment the following
# lines, adjust them as necessary, or simply add the curly braces after 'operator' and/or 'metricServer'
# and remove/comment the default values
resources:
  operator:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 100Mi
  metricServer:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 100Mi
  webhooks:
    limits:
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 10Mi
nodeSelector: {}

tolerations: []

# -- Pod Topology Constraints https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
topologySpreadConstraints: {}
  # operator: []
  # metricsServer: []
  # webhooks: []

# -- Affinity for pod scheduling https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/ for both KEDA operator and Metrics API Server
affinity: {}
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #   - labelSelector:
  #       matchExpressions:
  #       - key: app
  #         operator: In
  #         values:
  #         - keda-operator
  #         - keda-operator-metrics-apiserver
  #     topologyKey: "kubernetes.io/hostname"

## Optional priorityClassName for KEDA Operator and Metrics Adapter
priorityClassName: ""

## The default HTTP timeout in milliseconds that KEDA should use
## when making requests to external services. Removing this defaults to a
## reasonable default
http:
  timeout: 3000
  keepAlive:
    enabled: true
  minTlsVersion: TLS12

## Extra KEDA Operator and Metrics Adapter container arguments
extraArgs:
  keda: {}
  metricsAdapter: {}

## Extra environment variables that will be passed onto KEDA operator and metrics api service
env:
# - name: ENV_NAME
#   value: 'ENV-VALUE'

# Extra volumes and volume mounts for the deployment. Optional.
volumes:
  keda:
    extraVolumes: []
      #      - name: root
      #secret:
      #    secretName: root.crt
    extraVolumeMounts: []
      #  - name: root
      #  mountPath: /custom/ca/
  metricsApiServer:
    extraVolumes: []
      # - name: root
      #  secret:
      #    secretName: root.crt
    extraVolumeMounts: []
      #- name: root
      #  mountPath: /custom/ca/
  webhooks:
    extraVolumes: []
    extraVolumeMounts: []

prometheus:
  metricServer:
    enabled: false
    port: 9022
    portName: metrics
    path: /metrics
    serviceMonitor:
      # Enables ServiceMonitor creation for the Prometheus Operator
      enabled: false
      jobLabel:
      targetLabels: []
      podTargetLabels: []
      port: metrics
      targetPort:
      interval:
      scrapeTimeout:
      relabellings: []
      additionalLabels: {}
    podMonitor:
      # Enables PodMonitor creation for the Prometheus Operator
      enabled: true
      interval:
      scrapeTimeout:
      namespace:
      additionalLabels: {}
      relabelings: []
  operator:
    enabled: false
    port: 8080
    serviceMonitor:
      # Enables ServiceMonitor creation for the Prometheus Operator
      enabled: false
      jobLabel:
      targetLabels: []
      podTargetLabels: []
      port: metrics
      targetPort:
      interval:
      scrapeTimeout:
      relabellings: []
      additionalLabels: {}
    podMonitor:
      # Enables PodMonitor creation for the Prometheus Operator
      enabled: false
      interval:
      scrapeTimeout:
      namespace:
      additionalLabels: {}
      relabelings: []
    prometheusRules:
      # Enables PrometheusRules creation for the Prometheus Operator
      enabled: false
      namespace:
      additionalLabels: {}
      alerts:
        []
        # - alert: KedaScalerErrors
        #   annotations:
        #     description: Keda scaledObject {{ $labels.scaledObject }} is experiencing errors with {{ $labels.scaler }} scaler
        #     summary: Keda Scaler {{ $labels.scaler }} Errors
        #   expr: sum by ( scaledObject , scaler) (rate(keda_metrics_adapter_scaler_errors[2m]))  > 0
        #   for: 2m
        #   labels:
  webhooks:
    enabled: false
    port: 8080
    serviceMonitor:
      # Enables ServiceMonitor creation for the Prometheus webhooks
      enabled: false
      jobLabel:
      targetLabels: []
      podTargetLabels: []
      port: metrics
      targetPort:
      interval:
      scrapeTimeout:
      relabellings: []
      additionalLabels: {}
    prometheusRules:
      # Enables PrometheusRules creation for the Prometheus Operator
      enabled: false
      namespace:
      additionalLabels: {}
      alerts: []

certificates:
  autoGenerated: false
  secretName: kedaorg-certs       
  mountPath: /certs
  certManager:
    enabled: false
    # If generateCA is false, the secret with the CA
    # has to be annotated with 'cert-manager.io/allow-direct-injection: "true"'
    generateCA: false
      #    caSecretName: "kedaorg-ca"
    # Add labels/annotations to secrets created by Certificate resources
    secretTemplate: {}
      # annotations:
      #   my-secret-annotation-1: "foo"
      #   my-secret-annotation-2: "bar"
      # labels:
      #   my-secret-label: foo

permissions:
  metricServer:
    restrict:
      secret: false
  operator:
    restrict:
      secret: false
```
certificates:
  autoGenerated: false
  secretName: kedaorg-certs       
  mountPath: /certs
I create self sing cert and create Secret kedaorg-certs.
