### DISCUSSION TITLE
Failed to patch Objects Status with Conditions

### DISCUSSION THREAD

**Discussion by ademariag** [kedacore/keda#4542] [Q&A / Need Help] [answered]
I have just started playing with Keda so my current knowledge is limited. 

I have installed the latest version of Keda in my cluster using the yaml files. and applied it using ArgoCD. 

```
I0504 11:54:33.783127       1 welcome.go:34] keda_metrics_adapter "msg"="Starting metrics server" 
I0504 11:54:33.783226       1 welcome.go:35] keda_metrics_adapter "msg"="KEDA Version: 2.10.1" 
I0504 11:54:33.783232       1 welcome.go:36] keda_metrics_adapter "msg"="Git Commit: 8adb70e97a08a4690613eef4c4f00391e44e1603" 
I0504 11:54:33.783237       1 welcome.go:37] keda_metrics_adapter "msg"="Go Version: go1.19.7" 
I0504 11:54:33.783242       1 welcome.go:38] keda_metrics_adapter "msg"="Go OS/Arch: linux/amd64" 
```

All Keda related services are happily running:

```
NAME                                      READY   STATUS    RESTARTS   AGE
keda-admission-8575448894-l6z8f           1/1     Running   0          11d
keda-metrics-apiserver-6cf766ff5f-995jc   1/1     Running   0          11d
keda-operator-849d96c486-tqzkj            1/1     Running   0          141m
```

I am testing a ScaledObject for a deployment, the ScaledObject configuration is:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app.kapicorp.dev/component: ligand-properties
    name: ligand-properties
  name: ligand-properties
  namespace: dev
spec:
  minReplicaCount: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ligand-properties
  triggers:
    - metadata:
        value: '50'
      metricType: Utilization
      type: cpu
```

I am getting the following errors and I do not understand how to interpret them:

```
2023-05-15T17:43:47Z    ERROR   Failed to patch Objects Status with Conditions  {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"ligand-properties","namespace":"dev"}, "namespace": "dev", "name": "ligand-properties", "reconcileID": "613d66a0-f9b2-475d-b1d5-c8c9e95b3000", "error": "scaledobjects.keda.sh \"ligand-properties\" not found"}
2023-05-15T17:43:47Z    ERROR   Reconciler error        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"ligand-properties","namespace":"dev"}, "namespace": "dev", "name": "ligand-properties", "reconcileID": "613d66a0-f9b2-475d-b1d5-c8c9e95b3000", "error": "scaledobjects.keda.sh \"ligand-properties\" not found"}
```

I check the clusterrole for Keda and it looks ok.

The actual target deployment is running ok:

```
kubectl -n dev get deployments/ligand-properties
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
ligand-properties   10/10   10           10          67d
```

Would you help me understand what's the issue?
