### DISCUSSION TITLE
allowIdleConsumers is set to True and Deployment still doesn't scale to MaxReplicaCount

### DISCUSSION THREAD

**Discussion by pelegz** [kedacore/keda#4595] [Q&A / Need Help] [answered]
Hello, I'm using KEDA for Autoscaling a Deployment based on Kafka Lag. The topic has 1 partition.
This is my ScaledObject YAML:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example-scaledobject
spec:
  scaleTargetRef:
    name: example
  cooldownPeriod: 900
  pollingInterval: 30
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka.development:9092
        consumerGroup: example-ms
        offsetResetPolicy: earliest
        topic: example_complete
        allowIdleConsumers: "true"
        lagThreshold: "1"
```
**Expected Behavior:**

When triggered, there are around 30 messages. the Deployment should scale to maxReplicaCount which is 5.

**Actual Behavior:**

The Deployment only scales up to 1, which is the number of the partition.

Thanks!
