### DISCUSSION TITLE
Escalation by kafka events

### DISCUSSION THREAD

**Discussion by bryanhermass** [kedacore/keda#4654] [Q&A / Need Help] [answered]
Hello, good day. I have an existential doubt. I'm running tests with Keda and Kafka, but I have a question. For example, if I configure lagThreshold: '250' (assuming the consumer has 4 topics), as I understand it, does this mean that Keda will wait for an average of 1,000 messages to scale [1,000/4=250]? Is this correct ? Or will it wait for a lag of 1,000 to scale?

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer
  namespace: default
spec:
  scaleTargetRef:
    name: consumer
  pollingInterval: 30
  minReplicaCount: 1
  maxReplicaCount: 12
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: "host:9092"
      consumerGroup: "consumer-group"
      lagThreshold: "250"
      excludePersistentLag: 'false'
  advanced:              
    restoreToOriginalReplicaCount: false             
    horizontalPodAutoscalerConfig:                
      behavior:                                      
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
```
