### DISCUSSION TITLE
The "activationLagThreshold" parameter is not functioning.

### DISCUSSION THREAD

**Discussion by bryanhermass** [kedacore/keda#4688] [Q&A / Need Help]
Hello !!

I have a question. I've been testing Keda for a couple of weeks to scale based on events with Kafka, but it seems that the `activationLagThreshold: <'value'>` is not working correctly. As I understand it, this parameter scales between 0 and 1 when the minimum number of replicas is 0. However, I have the following metrics showing that this is not functioning properly. For example, I can have 3 messages in the queue, and the pod may go 30 minutes without scaling to 1. I have a case where it remained unscaled from around 06:00 PM until 09:00 AM the next day, as shown in the following image: 

(The top graph shows the lag, and the bottom graph shows the number of pods.)

Here we can see that starting from around 06:00 PM, there is a lag of 3 messages in the queue, and Keda keeps the HPA at 0. There are no pods until 09:00 AM the next day.

![image](https://github.com/kedacore/keda/assets/104916498/d33ace7b-3a5e-44d9-a943-93f116655298)

ScaleObject configuration

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-app
  namespace: default
spec:
  scaleTargetRef:
    name: consumer-deployment
  pollingInterval: 5
  minReplicaCount: 0
  maxReplicaCount: 12
  cooldownPeriod:  15
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: "host"
      consumerGroup: "consumer-group"
      lagThreshold: "133"
      excludePersistentLag: 'false'
      activationLagThreshold: '1'
  advanced:              
    restoreToOriginalReplicaCount: false             
    horizontalPodAutoscalerConfig:                
      behavior:                                      
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
```
I'm not sure if I'm mistaken in the operation or if I'm doing something wrong.

Greetings!
