### DISCUSSION TITLE
Kafka offset out of sync cause Keda to never scale down our services

### DISCUSSION THREAD

**Discussion by m4nu56** [kedacore/keda#4738] [General] [answered]
# Describe the issue

I don't think this is a "keda issue" but I do think this community will be able to help me solve this problem.

We've got 2 services configured to scale with Keda (v2.6.1, we're upgrading to 2.11 this week) with a Kafka trigger. Config is pretty basic: 
```yaml
spec:
  cooldownPeriod: 300
  maxReplicaCount: 8
  minReplicaCount: 1
  pollingInterval: 30
  scaleTargetRef:
    name: my-service
  triggers:
    - metadata:
        allowIdleConsumers: 'false'
        bootstrapServers: kafka-svc-kafka-external-bootstrap.strimzi.svc:9092
        consumerGroup: my-consumer-group
        lagThreshold: '1'
        offsetResetPolicy: earliest
        scaleToZeroOnInvalidOffset: 'false'
        topic: my-topic
      type: kafka
```

And we can see in the consumer group metadata on the broker that one of the partition doesn't have any offset commited: 

```
kafka-consumer-groups --bootstrap-server kafka-svc-kafka-external-bootstrap.strimzi.svc:9092 --group my-consumer-group --describe

GROUP                                    TOPIC                           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                                                HOST            CLIENT-ID
my-consumer-group my-topic 5          294             294             0               my-service-kafka-listener-c1da66b6-b202-425a-a121-45f97caf9d8f /10.1.36.27     my-service-kafka-listener
my-consumer-group my-topic 2          -               53              -               my-service-kafka-listener-3e87e280-29bf-4137-b093-035b817793e8 /10.1.36.27     my-service-kafka-listener
my-consumer-group my-topic 6          285             285             0               my-service-kafka-listener-d4c35629-3e74-4f47-aff9-0a3c0ab94974 /10.1.36.27     my-service-kafka-listener
my-consumer-group my-topic 1          516             516             0               my-service-kafka-listener-32b56b37-a434-49ba-9a02-6544409aaba3 /10.1.36.11     my-service-kafka-listener
my-consumer-group my-topic 7          332             332             0               my-service-kafka-listener-ddf73e47-f5ee-45f1-9aea-b25edbb603f3 /10.1.36.27     my-service-kafka-listener
my-consumer-group my-topic 3          102             102             0               my-service-kafka-listener-8dc22a15-0901-44a3-ad01-cccdb305962c /10.1.36.25     my-service-kafka-listener
my-consumer-group my-topic 0          480             480             0               my-service-kafka-listener-0b883fa6-6cb9-477a-a088-5e3adc262ae0 /10.1.36.27     my-service-kafka-listener
my-consumer-group my-topic 4          247             247             0               my-service-kafka-listener-bdb10815-020d-476f-b130-f1f3ec7a7504 /10.1.36.27     my-service-kafka-listener
```

We can see in “debug” logs of keda-operator that the lag for partition 2 is 53 due to the current-offset of this partition for this group being unsync. 

I know for sure that these messages have been properly handled and I have no reason to believe they have not been committed afterwards. 

We are encountering this issue with our 2 services running with Keda and in most of our environments where we deploy these. All in AKS. 

Would you have any clue at where I could start looking at to pinpoint the root cause of this issue ? 

Thanks a lot
