### DISCUSSION TITLE
KEDA behavior during Kafka consumer group rebalancing

### DISCUSSION THREAD

**Discussion by pelegz** [kedacore/keda#4742] [Q&A / Need Help]
Hello,

We are using KEDA to scale an application based on Kafka Lag. this is our scaledObject:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    meta.helm.sh/release-name: some-release
    meta.helm.sh/release-namespace: development
  name: some-deployment
  namespace: development
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment
spec:
  cooldownPeriod: 7200
  maxReplicaCount: 5
  minReplicaCount: 0
  scaleTargetRef:
    name: some-deployment
  triggers:
    - metadata:
        allowIdleConsumers: 'true'
        bootstrapServers: kafka.development:9092
        consumerGroup: app-group
        lagThreshold: '1'
        offsetResetPolicy: latest
        topic: some_kafka_topic_complete
      type: kafka
```
when Lag is at least 1 on the topic, KEDA successfully scales the deployment to our desired maxReplicaCount which is 5.

After some time when all pods finish consuming all messages from the topic, we encounter a rebalance due to a failed heartbeat:

```
Heartbeat failed for group app-group because it is rebalancing"
Revoking previously assigned partitions frozenset({TopicPartition(topic='some_kafka_topic_complete', partition=3)}) for group app-group
(Re-)joining group app-group
Joined group 'app-group' 
Setting newly assigned partitions {TopicPartition(topic='some_kafka_topic_complete', partition=4)} for group app-group
```

I know isn't related to KEDA but what happens is the deployment scales down to 1 before all consumers are assigned with new partitions, thus all of the jobs our pods are trying to run are aborted and pods shut down.

After the cooldownPeriod ends, the deployment scales down to 0.

**Without KEDA:**
All 5 pods are up, all pods consume the messages from the topic, rebalance is happening and finishes successfully and the jobs finish successfully.

Will appreciate any thoughts,
Thanks.
