### DISCUSSION TITLE
ScaledObject configuration for AWS SQS using LocalStack

### DISCUSSION THREAD

**Discussion by tashogeorgiev** [kedacore/keda#4797] [Q&A / Need Help] [answered]
I am trying to set up a scaler which will fire my pod when there are messages in an SQS queue in my AWS LocalStack, but when I try to apply my settings. I get the error:
```
2023-07-14T10:48:00Z    ERROR   scale_handler   error getting scale decision    {"scaledObject.Namespace": "default", "scaledObject.Name": "aws-sqs-queue-scaledobject", "scaler": "awsSqsQueueScaler", "error": "RequestError: send request failed\ncaused by: Post \"http://localhost:4566/\": net/http: invalid header field value for \"Authorization\""}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
        /workspace/pkg/scaling/scale_handler.go:588
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:236
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:175
``` 

Here is my service.yaml file:

```
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
data:
  AWS_ACCESS_KEY_ID: access_key_value
  AWS_SECRET_ACCESS_KEY: secret_access_key_value
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: aws-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter: awsAccessKeyId
      name: aws-credentials
      key: AWS_ACCESS_KEY_ID
    - parameter: awsSecretAccessKey
      name: aws-credentials
      key: AWS_SECRET_ACCESS_KEY   
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: a-native-00001-deployment
  minReplicaCount: 0  
  maxReplicaCount: 5  
  pollingInterval: 10 
  cooldownPeriod:  25 
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
        name: aws-auth
    metadata:
      queueURL: http://localhost:4566/000000000000/queue-name
      queueLength: "5"
      awsRegion: "eu-west-1"
      awsEndpoint: "http://localhost:4566"
      identityOwner: pod
``` 

I've referenced the documentation from [https://keda.sh/docs/2.11/scalers/aws-sqs/](url) but no result.

An important thing to note is that the localstack is running in a docker container, maybe the host I.P should be changed? I have tried using `host.docker.internal` instead of `localhost`, but again it doesn't work.

How can I set up the scaler to use the queue from my localstack?
