### DISCUSSION TITLE
why keda doesn't scale up extra pods after trigger for a long time.

### DISCUSSION THREAD

**Discussion by hexiong0802** [kedacore/keda#4810] [Q&A / Need Help]
Here is my ScaledObject yaml config:

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: maicedata
  name: scaled-auth
spec:
  scaleTargetRef:
    name:  auth         # Mandatory. Must be in the same namespace as the ScaledObject
  pollingInterval:  5                            # Optional. Default: 30 seconds
  cooldownPeriod:   360                              # Optional. Default: 300 seconds
  idleReplicaCount: 0                                # Optional. Default: ignored, must be less than minReplicaCount 
  minReplicaCount:  1                                # Optional. Default: 0
  maxReplicaCount:  10                              # Optional. Default: 100
  fallback:                                          # Optional. Section to specify fallback options
    failureThreshold: 3                              # Mandatory if fallback section is included
    replicas: 2                                      # Mandatory if fallback section is included
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: false        # Optional. Default: false
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
        # 减少扩容抖动
        scaleUp:
          stabilizationWindowSeconds: 15
  triggers:
    - type: prometheus
      metricType: Value
      metadata:
        serverAddress: https://prom.idatatlas.com
        namespace: maicedata
        metricName: auth-prom-metric
        activationThreshold: "-1"
        threshold: '0.8'
        # worker使用率
        query: sum(gunicorn_busy_workers{env="prod", exported_instance="k8s", role="auth"})/sum(gunicorn_total_workers{env="prod", exported_instance="k8s", role="auth"})
        authModes: "basic"
      authenticationRef:
        name: keda-prom-creds
```
![image](https://github.com/kedacore/keda/assets/90944636/3783cfbd-43e2-4a36-acfb-0569b5d8a7b6)

> The upper graph represents the gunicorn worker utilization.  
> The bottom graph represents the current pod‘s number 

When the query metric value is greater than threshold, It scales up one pod, but the query metric value lasts for a long time that is greater than threshold, keda doesn't scale up extra pods. Why???? I hope that keda continues to scale up extra pods when the query metric value is greater than threshold for 10s or a customize time
