### DISCUSSION TITLE
Metrics not using trigger name in AWS CloudWatch scaler

### DISCUSSION THREAD

**Discussion by steveratay** [kedacore/keda#4824] [Q&A / Need Help]
I have defined a scaler based on AWS CloudWatch which includes multiple triggers, each for a separate metric in CloudWatch.  They are defined as follows, using the name field which is documented as a trigger field here: https://keda.sh/docs/2.11/concepts/scaling-deployments/#triggers
```
  triggers:
  - type: aws-cloudwatch
    name: custom-name-1
    metadata:
      # details here are irrelevant and therefore excluded
  - type: aws-cloudwatch
    name: custom-name-2
    metadata:
      # details here are irrelevant and therefore excluded
```

However, when the HPA is created it looks like this, with a generic metric name, and I can't easily discern one metric from the other:
```
Metrics:                                       ( current / target )
  "s0-aws-cloudwatch" (target average value):  0 / 10k
  "s1-aws-cloudwatch" (target average value):  0 / 10k
```

This seems like a bug to me but it's clearly coded this was at https://github.com/kedacore/keda/blob/89fb01af8bbaf9e82d22b7bdfca1ec363d21de31/pkg/scalers/aws_cloudwatch_scaler.go#L297.  Looking through some of the other scalers I see a mix of some using the metric name and others not.  Can anyone explain why this is the case?  Shouldn't the scaler be using the name field if it's defined and only falling back to this generic naming scheme if there is no name defined?

Not sure if I should open this as a bug or not, so I figured I would start here.  Thanks!
