### DISCUSSION TITLE
KEDA Kafka-Scaler doesn't scale up deployment

### DISCUSSION THREAD

**Discussion by pelegz** [kedacore/keda#4872] [Q&A / Need Help]
Hello, I'm trying to use KEDA autoscaling with Kafka. This issue occurs on a newly created topic with no messages. This is my ScaledObject:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
spec:
  cooldownPeriod: 7200
  idleReplicaCount: 0
  maxReplicaCount: 5
  minReplicaCount: 5
  scaleTargetRef:
    name: some-ms
  triggers:
    - metadata:
        allowIdleConsumers: 'true'
        bootstrapServers: kafka.ms-ns:9092
        consumerGroup: ms
        lagThreshold: '1'
        offsetResetPolicy: latest
        scaleToZeroOnInvalidOffset: 'true'
        topic: some_ms_complete
      type: kafka
```
Upon deployment, my app scales down to zero as expected, as no messages are committed:
```kafka_scaler	invalid offset found for topic some_ms_complete in group ms and partition 3, probably no offset is committed yet. Returning with lag of 0
kafka_scaler	invalid offset found for topic some_ms_complete in group ms and partition 3, probably no offset is committed yet. Returning with lag of 0
kafka_scaler	invalid offset found for topic some_ms_complete in group ms and partition 0, probably no offset is committed yet. Returning with lag of 0
kafka_scaler	invalid offset found for topic some_ms_complete in group ms and partition 1, probably no offset is committed yet. Returning with lag of 0
kafka_scaler	invalid offset found for topic some_ms_complete in group ms and partition 2, probably no offset is committed yet. Returning with lag of 0
kafka_scaler	invalid offset found for topic some_ms_complete in group ms and partition 4, probably no offset is committed yet. Returning with lag of 0 
```
I then send messages to the topic:

<img width="577" alt="image" src="https://github.com/kedacore/keda/assets/128046227/8897664d-ef55-4a61-8568-80ba52655faa">

And....still, KEDA returns lag of 0 and deployment doesn't scale up.
However, when I set offsetResetPolicy to earliest, it works but I wouldn't like to change this behavior.

Thanks in advance,
