### DISCUSSION TITLE
Configuring (minReplicaCount > 0) on azure-servicebus trigger without warm-up time | Tackling CrashLoopBackOff

### DISCUSSION THREAD

**Discussion by engage-deepakagarwal** [kedacore/keda#4873] [Q&A / Need Help]
Hello,
I am working on a use case where I need to setup first couple of containers running (minReplicaCount = 2) to avoid warm up time when working on messages from azure service bus. As load increases, it can scale out to max specified number. The code in the container is such that it works on the incoming message and when completed it exits. 

Below is sample KEDA configuration file for this - 
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sample-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1                            
    kind: deployment                                
    name: sample-scale-deployment
  pollingInterval: 2                               
  cooldownPeriod:  10                              
  minReplicaCount: 2                        
  maxReplicaCount: 5                     
  advanced:                                         
    restoreToOriginalReplicaCount: false            
    horizontalPodAutoscalerConfig:                  
      behavior:                                     
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: azure-servicebus
    metadata:      
      topicName: sampletopic
      subscriptionName: samplesubscription
      messageCount: "1"
    authenticationRef:
      name: trigger-auth-service-bus 
```

The issue with this is - if there are no messages in the service bus, 2 containers will always start and since there are no messages to process, it will just exit and kubelet assumes this as failure responding with CrashLoopBackOff status and restarts with an exponential pattern which is expected.

The 2 containers continues to restarts with exponential strategy until there is a message. However, when the message comes, due to exponential back-off time, it doesn't get picked-up immediately to process which defeats the purpose of keeping minReplicas in first place. 

Appreciate your thoughts on this use case / scenario and how to approach this? Have you come across any such scenario in the past and does KEDA / K8s have any out of the box or custom configurations to deal with this?

Thanks!
