### DISCUSSION TITLE
github runner

### DISCUSSION THREAD

**Discussion by BrahamiRabah** [kedacore/keda#4886] [Q&A / Need Help]
currently i am using keda to scale my github runners on my kubernetes clusters but it seems that once no more than one job is running at a time, the scaled job is not triggering a new runner and is waiting for the first pipeline to run finish to pass to second and create a new runner

**Comment by BrahamiRabah** [comment]
```
      spec:
        containers:
          - envFrom:
              - secretRef:
                  name: secret-github-agents
              - configMapRef:
                  name: configmap-github-agents
            image: agents/linux:2023
            imagePullPolicy: IfNotPresent
            name: github-agent
            resources:
              limits:
                cpu: 5
                memory: 10Gi
            securityContext:
              privileged: true
        nodeSelector:
          workload: compute_intensive
        priorityClassName: high-priority
        restartPolicy: Never
        serviceAccountName: sa-github-agents
        tolerations:
          - effect: NoSchedule
            key: compute_intensive
            operator: Equal
            value: 'true'
  maxReplicaCount: 25
  minReplicaCount: 0
  pollingInterval: 5
  rollout:
    propagationPolicy: background
    strategy: gradual
  scalingStrategy:
    strategy: default
  successfulJobsHistoryLimit: 0
  triggers:
    - authenticationRef:
        name: github-trigger-auth
      metadata:
        githubAPIURLFromEnv: GH_URL
        owner: XXXXXXXX
        reposFromEnv: GH_REPOS
        runnerScope: org
      type: github-runner
```
this is my actuel config
