### DISCUSSION TITLE
Azure Monitor scaler reports no timeseries as errors

### DISCUSSION THREAD

**Discussion by MO2k4** [kedacore/keda#4895] [Q&A / Need Help]
Hi 🤞

i can see many errors in my keda logs regarding the azure monitor scaler if there is no data available.

```json
{
   "type": "ScaledObject",
   "namespace": "default", 
   "name": "service-api-http", 
   "error": "error getting azure monitor metric requests/rate: got metric result for Microsoft.Insights/requests/rate and aggregate type AVERAGE without timeseries"
}
```

Is there a way around this error or is this something i have to live with? i thought it might be related to this issue #699 

my configuration for the scaledObject looks like this

```yaml
- type: azure-monitor
  metadata:
    resourceURI: Microsoft.Insights/components/{{ .Values.Scale.componentName }}
    tenantId: {{ .Values.Scale.tenantId }}
    subscriptionId: {{ .Values.Scale.subscriptionId }}
    resourceGroupName: {{ .Values.Scale.resourceGroupName }}
    metricName: requests/rate
    metricFilter: cloud/roleName eq '{{ .Values.Scale.roleName }}'
    metricAggregationType: Average
    metricAggregationInterval: "0:1:0"
    targetValue: "4"
  authenticationRef:
    name: azure-monitor-trigger-auth
```
