### DISCUSSION TITLE
ScaledJob accurate strategy unexpected behaviour

### DISCUSSION THREAD

**Discussion by tomikonio** [kedacore/keda#4947] [Q&A / Need Help]
Hi,
We using keda with rabbitmq.
This is our flow once a message appears in the queue and a job is created:
- Read message
- ACK message
- Process
- Finish

We have a strange thing happening **right after a job has finished**:
Even though there is no message in the queue, keda creates a new job.
It does this every time a job is finished.

Configuration:

```yaml
    spec:
      failedJobsHistoryLimit: 5
      jobTargetRef:
        backoffLimit: 6
        completions: 1
        parallelism: 1
......................................
      maxReplicaCount: 3
      minReplicaCount: 0
      rollout:
        strategy: gradual
      scalingStrategy:
        multipleScalersCalculation: max
        strategy: accurate
      successfulJobsHistoryLimit: 5
      triggers:
        - authenticationRef:
            name: some-name
          metadata:
            mode: QueueLength
            protocol: amqp
            queueName: someQueue
            value: "1"
```

We have previously switched from `default` to `accurate` strategy (thank you @joelsmith) because we want keda to create a new job if there is a message in the queue and another job is already running - (processing an older, already deleted message)

Thanks :)
