### DISCUSSION TITLE
Unable to connect to Elasticache I/O timeout

### DISCUSSION THREAD

**Discussion by MaharshPatelBluescape** [kedacore/keda#4950] [Q&A / Need Help]
I'm facing similar issue as https://github.com/kedacore/keda/issues/2903 I'm unable to connect to Elasticache due to I/O timeout my Elasticache has AUTH Token-based access.

## Expected Behavior
Able to connect to elasticache

## Actual Behavior
```connection to redis failed: read tcp 10.64.70.17:39788->10.64.74.13:6379: i/o timeout```

## ScaledObject
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  namespace: devperf
spec:
  scaleTargetRef:
    name: <deployment_name>
  triggers:
  - type: redis
    metadata:
      enableTLS: "true"
      address: "master.<name>.<identifier>.use2.cache.amazonaws.com:6379"
      password: "<auth_token>"
      listName: "list-name"
      listLength: "10"
```

### KEDA Version
`2.8.1`

### Kubernetes Version
`1.23`

**Comment by zroubalik** [comment]
The `password` field is not valid in the metadata, you need to use TriggerAuthentication and refer a secret: https://keda.sh/docs/2.8/scalers/redis-lists/#authentication-parameters

**Comment by MaharshPatelBluescape** [comment]
Hey @zroubalik , thanks for your reply. I did try TriggerAuthentication but that didn't work. Here is the updated info

## ScaledObj.yml
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  namespace: devperf
spec:
  scaleTargetRef:
    name: <deployment_name>
  triggers:
  - type: redis
    metadata:
      enableTLS: "true"
      address: "master.<name>.<identifier>.use2.cache.amazonaws.com:6379"
      listName: "list-name"
      listLength: "10"
    authenticationRef:
      name: keda-trigger-auth-redis-secret
```
## TriggerAuth.yml
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-redis-secret
  namespace: devperf
spec:
  secretTargetRef:
  - parameter: authToken
    name: redis-auth-secret
    key: authToken
```

## Creation of Secret
`kubectl create secret generic redis-auth-secret --from-literal=authToken=<my_auth_token>`

## Expected Behavior
Able to connect to elasticache

## Actual Behavior
```connection to redis failed: NOAUTH Authentication required.```
