### DISCUSSION TITLE
How to use Redis Scaler with TLS authentication？

### DISCUSSION THREAD

**Discussion by xuhjbj** [kedacore/keda#4972] [Q&A / Need Help]
### Proposal

Hi,I am new to keda. for redis scaler https://keda.sh/docs/2.11/scalers/redis-lists/, is there any detail examples for how to enable the enableTLS  ？

I have to create a TriggerAuthentication linking the the secret where the certificates are, and use it for my ScaledObject.I already have the certificate in a secret.
But from the doc,there are only some parameters ,there is no any further guide to implement that :
```
enableTLS - Allow a connection to a redis queue using tls. (Values: true, false, Default: false, Optional)
unsafeSsl - Used for skipping certificate check e.g: using self-signed certs. (Values: true,false, Default: false, Optional, This requires enableTLS: true)
```

### Use-Case

With Jorge Turrado's confirmation with the code to ensure that it's a a feature gap.

### Is this a feature you are interested in implementing yourself?

No

### Anything else?

 "error": "connection to redis failed: dial tcp 10.152.183.27:6378: i/o timeout".

**Comment by madyarini** [comment]
for enableTLS, the value is "true" or "false"
```
    triggers:
    - authenticationRef:
        name: my-trigger-auth
      metadata:
        enableTLS: "true"
        listLength: "15"
        listName: queue:my_queue
      type: redis
```
