### DISCUSSION TITLE
Always be over provisioned based on message in a SQS queue

### DISCUSSION THREAD

**Discussion by yatanasov-hs** [kedacore/keda#5046] [Q&A / Need Help] [answered]
We are scaling based on queue messages and have the requirement to always be over provisioned by 3 pods.
Our pod can process 3  messages at a time. I though I can use scalingModifiers but not clear what target means. E.g.:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaledobject-foo
spec:
  advanced:
    scalingModifiers:
      formula: queuename + 3
      target: "3"
  maxReplicaCount: 10
  minReplicaCount: 0
  scaleTargetRef:
    name: foo
  triggers:
  - metadata:
      awsRegion: us-east-2
      identityOwner: operator
      queueLength: "3"
      queueURL: queue-url
    name: queuename
    type: aws-sqs-queue
```

This results in:
2 pods when there are 3 messages in the queue
1 pod when there are 0 messages in the queue.

Any help is well appreciated.
