### DISCUSSION TITLE
Scale to one instance when the deployment changes

### DISCUSSION THREAD

**Discussion by davidgengenbach** [kedacore/keda#5054] [Q&A / Need Help]
When we have no load, we use KEDA to scale to zero instances.
However, when we change a deployment, we need to have it start at least once (optional: in the best case the instances run until they pass the healthchecks).
How can we achieve this using KEDA?

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: some-scaledobject
spec:
  scaleTargetRef:
    kind: Deployment
    name: some-deployment
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 10
  fallback:
    failureThreshold: 1
    replicas: 1
  triggers:
    - type: rabbitmq
      metadata:
        queueName: some-queue
        mode: QueueLength
        operation: "sum"
        value: "1"
        activationValue: "0"
```

Thanks in advance 🥳
