### DISCUSSION TITLE
Failed Trigger Logic With Multiple Triggers

### DISCUSSION THREAD

**Discussion by alex-staroselsky-vizio** [kedacore/keda#5059] [Q&A / Need Help]
For keda `v2.7.2` if a ScaledObject has two triggers, first/top being a `prometheus` trigger and second/last/subsequent being a `cpu` trigger, if the `prometheus` trigger fails because of issues with prometheus, will the `cpu` trigger still evaluate as a backup or will it effectively short circuit at the failed `prometheus` trigger.

Example warning:

```
Warning  KEDAScalerFailed         56s                    keda-operator  Get "http://prometheus:9090/api/v1/query?query=blah&time=2023-10-06T19:54:02Z": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Example status when describing the ScaledObject:

```yaml
status:
  conditions:
  - message: Some triggers defined in ScaledObject are not working correctly
    reason: PartialTriggerError
    status: Unknown
    type: Ready
  - message: Scaling is performed because triggers are active
    reason: ScalerActive
    status: "True"
    type: Active
  - message: No fallbacks are active on this scaled object
    reason: NoFallbackFound
    status: "False"
    type: Fallback
```
