### DISCUSSION TITLE
keda-operator  error creating kafka client: kafka: client has run out of available brokers to talk to: EOF   , keda-operator  failed to ensure HPA is correctly created for ScaledObject

### DISCUSSION THREAD

**Discussion by Elias-Swais** [kedacore/keda#5065] [Q&A / Need Help]
i have this yaml file :
```
apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: karavan
data:
  sasl: "cGxhaW50ZXh0"
  username: "V1VDM0ZZUFVZWUdQWVE3Rw=="
  password: "YWZDOFhodVlHais1SmdqWklnemJHMEZDZ0xmUkY3dkg1WjRlV05KUzN4U3FIQmx5bTFDYXZIUzlaNjJ3eElhQQ=="
  tls: "ZW5hYmxl"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: karavan
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-secrets
    key: sasl
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: keda-kafka-secrets
    key: password
  - parameter: tls
    name: keda-kafka-secrets
    key: tls
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: karavan
spec:
  scaleTargetRef:
    name: s9wl00s
  pollingInterval: 30
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: pkc-q9z57.uaenorth.azure.confluent.cloud:9092
      consumerGroup: my-group       # Make sure that this consumer group name is the same one as the one that is consuming topics
      topic: test-topic
      # Optional
      lagThreshold: "5"
      offsetResetPolicy: latest
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
      ```
```
which when i apply through kubectl works perfectly , it creates the scaled object and everything,
when i try to create the scaled object through code, it returns the error above in the title,
im assuming that it is a problem with the username or password or how i handle them , here 

```
private String encodeStringBase64(String text){
        byte[] encodedValue = Base64.getEncoder().encode(text.getBytes());
        return new String(encodedValue);
    }
    public void createKafkaSecret(KafkaRequest request, String projectId){
        try{

            String sasl = encodeStringBase64("plaintext");
            String username = encodeStringBase64(request.getUsername());
            String password = encodeStringBase64(request.getPassword());
            String tls = encodeStringBase64("enable");

            Secret kafkaSecret = new SecretBuilder()
                    .withNewMetadata()
                    .withName(projectId + "-kafka-secret")
                    .endMetadata()
                    .addToData("sasl",sasl)
                    .addToData("username",username)
                    .addToData("password",password)
                    .addToData("tls",tls)
                    .build();
                    ```
