### DISCUSSION TITLE
Github Keda Scaler with Github App: "error parsing GitHub Runner metadata: no personalAccessToken given"

### DISCUSSION THREAD

**Discussion by jordanabakerafs** [kedacore/keda#5133] [Q&A / Need Help]
A) Is this supported in AzureGov - adding this up front, since it can tend to be an issue.

I am setting up the Keda scaler for Github runners using a github app.  I've set my YAML up like so:

``` 
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: github-trigger-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter: appKey
      name: github-auth-keda
      key: appKey
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: github-runner-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: ghrunnerwin
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: github-runner
    metadata:
      githubAPIURL: "https://api.github.com"
      owner: "<scrubbed org name>"
      runnerScope: "repo"
      repos: "test-aks-runners"
      targetWorkflowQueueLength: "1"
      applicationId: "<scrubbed app id>"
      installationId: "<scrubbed install id>"
    authenticationRef:
     name: github-trigger-auth
```
The github app is created and installed to our org.  The github app key file is base64 encoded and stored as github-auth-keda.

After pushing the yaml, I check the scaler with ` kubectl describe scaledObject/github-runner-scaledobject ` and I get back the following indicating it's looking for a personalAccessToken - which I cannot use in my environment.  I've checked my YAML and the docs (https://keda.sh/docs/2.12/scalers/github-runner) 100 times over.  Is there something I'm missing?

```
Events:
  Type     Reason                   Age                From           Message
  ----     ------                   ----               ----           -------
  Warning  KEDAScalerFailed         1s (x12 over 11s)  keda-operator  error parsing GitHub Runner metadata: no personalAccessToken given       
  Warning  ScaledObjectCheckFailed  1s (x12 over 11s)  keda-operator  Failed to ensure HPA is correctly created for ScaledObject
  ```
