### DISCUSSION TITLE
KEDA failed to create new HPA resource for Azure servicebus topic trigger function hosted on AKS

### DISCUSSION THREAD

**Discussion by RakeshSharnagate-eaton** [kedacore/keda#5168] [Q&A / Need Help]
I want to scale the Azure Servicebus trigger function hosted on AKS using KEDA but the scaling is not working. Below are the configuration details:

ScaledObject.yaml

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: device-command-scheduler
  namespace: device-command-scheduler
  labels:
    app: device-command-scheduler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: device-command-scheduler-deployment
  pollingInterval: 5
  cooldownPeriod: 5
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      topicName: {{.Values.CronTopicName}}
      subscriptionName: {{.Values.CronSubscriptionName}}
      connectionFromEnv: ServiceBusConnectionString
      messageCount: "5" # Optional. Count of messages to trigger scaling on. Default: 5 messages
      activationMessageCount: "2"
  - type: azure-servicebus
    metadata:
      topicName: {{.Values.OneTimeTopicName}}
      subscriptionName: {{.Values.OneTimeSubscriptionName}}
      connectionFromEnv: ServiceBusConnectionString
      messageCount: "5" # Optional. Count of messages to trigger scaling on. Default: 5 messages
      activationMessageCount: "2"
  - type: azure-servicebus
    metadata:
      topicName: {{.Values.SunTopicName}}
      subscriptionName: {{.Values.SunSubscriptionName}}
      connectionFromEnv: ServiceBusConnectionString
      messageCount: "5" # Optional. Count of messages to trigger scaling on. Default: 5 messages
      activationMessageCount: "2"
```

Deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-command-scheduler-deployment
  namespace: device-command-scheduler
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0
  selector:
    matchLabels:
      app: device-command-scheduler
  template:
    metadata:
      labels:
        app: device-command-scheduler
    spec:     
      containers:
      - name: device-command-scheduler
        image: "{{ .Values.imageRepository }}:{{ .Chart.AppVersion }}"
        envFrom: 
        - secretRef:
            name: device-command-schedulerconfig
        - configMapRef:
            name: configmap-scheduler-ingestion
        resources:
          limits:
            memory: "2000Mi"
            cpu: "1000m"
          requests:
            memory: "1000Mi"
            cpu: "500m"  
   
      imagePullSecrets:
      - name: pullscheduler
```
**Expected Behavior**
---
KEDA creates HPA object.

**Actual Behavior**
---
KEDA cannot create HPA object.

```
Name:         device-command-scheduler
Namespace:    device-command-scheduler
Labels:       app=device-command-scheduler
              app.kubernetes.io/managed-by=Helm
              scaledobject.keda.sh/name=device-command-scheduler
Annotations:  meta.helm.sh/release-name: device-command-scheduler
              meta.helm.sh/release-namespace: device-command-scheduler
API Version:  keda.sh/v1alpha1
Kind:         ScaledObject
Metadata:
  Creation Timestamp:  2023-11-03T18:14:50Z
  Finalizers:
    finalizer.keda.sh
  Generation:  5
  Managed Fields:
    API Version:  keda.sh/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizer.keda.sh":
        f:labels:
          f:scaledobject.keda.sh/name:
    Manager:      Go-http-client
    Operation:    Update
    Time:         2023-11-03T18:14:50Z
    API Version:  keda.sh/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:originalReplicaCount:
        f:scaleTargetGVKR:
          .:
          f:group:
          f:kind:
          f:resource:
          f:version:
        f:scaleTargetKind:
    Manager:      Go-http-client
    Operation:    Update
    Subresource:  status
    Time:         2023-11-03T18:14:50Z
    API Version:  keda.sh/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app:
          f:app.kubernetes.io/managed-by:
      f:spec:
        .:
        f:cooldownPeriod:
        f:maxReplicaCount:
        f:minReplicaCount:
        f:pollingInterval:
        f:scaleTargetRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
        f:triggers:
    Manager:         helm
    Operation:       Update
    Time:            2023-11-08T07:57:35Z
  Resource Version:  222123970
  UID:               c43d2a7a-24fe-4f56-a3e4-426226b993b4
Spec:
  Cooldown Period:    5
  Max Replica Count:  10
  Min Replica Count:  1
  Polling Interval:   5
  Scale Target Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         device-command-scheduler-deployment
  Triggers:
    Metadata:
      Connection From Env:  ServiceBusConnectionString
      Entity Type:          topic
      Message Count:        5
    Type:                   azure-servicebus
Status:
  Conditions:
    Message:               failed to ensure HPA is correctly created for ScaledObject
    Reason:                ScaledObjectCheckFailed
    Status:                False
    Type:                  Ready
    Message:               ScaledObject check failed
    Reason:                UnknownState
    Status:                Unknown
    Type:                  Active
    Status:                Unknown
    Type:                  Fallback
    Status:                Unknown
    Type:                  Paused
  Original Replica Count:  1
  Scale Target GVKR:
    Group:            apps
    Kind:             Deployment
    Resource:         deployments
    Version:          v1
  Scale Target Kind:  apps/v1.Deployment
Events:
  Type     Reason                   Age                     From           Message
  ----     ------                   ----                    ----           -------
  Warning  KEDAScalerFailed         5m9s (x402 over 4d13h)  keda-operator  error parsing azure service bus metadata: no service bus entity type set
  Warning  ScaledObjectCheckFailed  5m9s (x416 over 4d13h)  keda-operator  failed to ensure HPA is correctly created for ScaledObject
```
**Specifications**
---
- Keda Version: 2.11.2
- Azure Kubernetes Service: 1.25.5
- Scaler: Azure Service Bus
