### DISCUSSION TITLE
[RabbitMQ] Reduce number of connections from keda HPA

### DISCUSSION THREAD

**Discussion by MatheusGeiger** [kedacore/keda#5188] [General] [answered]
Hello everyone, a time ago we change the default HPA for the cluster to KEDA hpa for our consumers who that use the RabbitMQ and it working perfectly.

Now looking the rabbitmq painel with most preciousness we have double connection "per consumer" one the consumer and other the hpa for this consumer. 

This behavior and implementation makes the number of connections duplicates, and looking this the resource usage from the cluster increase too.

Is possible or exists one approach to reduce the number of connections?

HPA Example Receipt
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    deploymentName: monopoly-consumer-customer-configuration-deployment
  name: monopoly-consumer-customer-configuration-hpa
  namespace: production
spec:
  maxReplicaCount: 10
  minReplicaCount: 0
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: monopoly-consumer-customer-configuration-deployment
  triggers:
    - authenticationRef:
        name: keda-frizzy-cobalt-angelfish-trigger-auth-rabbitmq-conn
      metadata:
        mode: QueueLength
        protocol: amqp
        queueName: monopoly.customer-configuration.v1
        value: '100'
      type: rabbitmq
```

Number of connections from `keda` user
<img width="669" alt="Screenshot 2023-11-16 at 09 36 13" src="https://github.com/kedacore/keda/assets/22987079/1a5a21e6-f50b-4154-a3c5-8bbd62974434">
