### DISCUSSION TITLE
KEDA: Kubernetes HPA Based on External Metrics from Goldilocks API

### DISCUSSION THREAD

**Discussion by tppalani** [kedacore/keda#5301] [Q&A / Need Help]
Hi Team,

Hi Team,

I have installed Goldilocks inside the EKS cluster and am able to access the Goldilocks dashboard. I have used port forwarding to access the Goldilocks dashboard from the browser.

Now coming to KEDA, I'm planning to define the ScaledObject type API. I was just wondering if KEDA will support external triggers to fetch the information from the Goldilocks API URL.

```
triggers:
- type: external
  metadata:
    scalerAddress: goldilocks-service:8080
```
