### DISCUSSION TITLE
globPattern in Azure Blob Storage

### DISCUSSION THREAD

**Discussion by just-another-dev88** [kedacore/keda#5368] [Q&A / Need Help]
We tried using KEDA scaler for Azure Blob Storage and used globPattern for trigger, however that doesn't seem to work.

```yml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-processing
  namespace: dev
  labels: {}
spec:
  scaleTargetRef:
    name: app-processing
  minReplicaCount:  1
  maxReplicaCount:  3
  triggers:
  - type: azure-blob
    metadata:
      blobContainerName:  app-processing
      connectionFromEnv: EnvironmentConfig
      globPattern: "**/**/uploads/**/*.+(csv|xls|xlsx)"
      blobCount: '5'
```

my question, is the globPattern intended to be used this way?
