### DISCUSSION TITLE
facing issue while installing KEDA 2.10.0 on EKS 1.25 cluster

### DISCUSSION THREAD

**Discussion by chaithraPadmar** [kedacore/keda#5418] [Q&A / Need Help]
hi,

Am trying to install KEDA 2.10.0 on EKS 1.25 cluster
while installing the KEDA helm chart ; the keda-operator fails for certs related issues

could you kindly help me with below values config if i want to load a self signed certs into secrete and use it in KEDA 2.10.0 intall

```yaml
certificates:
  # -- Enables the self generation for KEDA TLS certificates inside KEDA operator
  autoGenerated: true
  # -- Secret name to be mounted with KEDA TLS certificates
  secretName: kedaorg-certs
  # -- Path where KEDA TLS certificates are mounted
  mountPath: /certs
  certManager:
    # -- Enables Cert-manager for certificate management
    enabled: false
    # -- Generates a self-signed CA with Cert-manager.
    # If generateCA is false, the secret with the CA
    # has to be annotated with `cert-manager.io/allow-direct-injection: "true"`
    generateCA: true
    # -- Secret name where the CA is stored (generatedby cert-manager or user given)
    caSecretName: "kedaorg-ca"
```
   ---------------------------

My queries are as below:-
in the above values what should be kedaorg-certs and "kedaorg-ca" if am using a self signed certs
the certs should be mounted to what path; if i load a secret generated using tls; it looks for ca.crt and i get that error
if i comment the secrete name ; helm fails

so what kind of secrete one has to generate and how to implement; could you kindly brief out

Regards
Chaithra
