### DISCUSSION TITLE
RabbitMQ Scaler with env trigger authentication not working

### DISCUSSION THREAD

**Discussion by jackson-chris** [kedacore/keda#5430] [Q&A / Need Help] [answered]
I'm trying to configure the RabbitMQ Scaler in an environment running Keda 2.11.x but the scaledobject is failing to become ready, when describing the scaled object I see:
```
  Warning  KEDAScalerFailed         2m40s (x19 over 24m)  keda-operator  error parsing rabbitmq metadata: no host setting given
  Warning  ScaledObjectCheckFailed  2m40s (x19 over 24m)  keda-operator  failed to ensure HPA is correctly created for ScaledObject
```
The configuration I am using is below:
```
  apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: foo
spec:
  env:
  - name: RABBITMQ_MANAGEMENT_URL
    parameter: host
```
and
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: foo
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 15
            type: Percent
            value: 100
          stabilizationWindowSeconds: 60
        scaleUp:
          policies:
          - periodSeconds: 15
            type: Percent
            value: 100
          - periodSeconds: 15
            type: Pods
            value: 4
          selectPolicy: Max
          stabilizationWindowSeconds: 0
  cooldownPeriod: 120
  maxReplicaCount: 8
  minReplicaCount: 1
  pollingInterval: 15
  scaleTargetRef:
    name: foo
  triggers:
  - metadata:
      mode: QueueLength
      protocol: http
      queueName: merge
      value: "5"
    type: rabbitmq
  - authenticationRef:
      name: foo
    metadata:
      mode: MessageRate
      protocol: http
      queueName: merge
      value: "100"
    type: rabbitmq
```
  
Based upon what I read in the [docs](https://keda.sh/docs/2.12/concepts/authentication/#environment-variables) I assumed this should work since in the deployment I'm looking to scale I have an environment variable named `RABBITMQ_MANAGEMENT_URL` with the required host string for the scaler. 

I know instead I can use:
```
  triggers:
  - metadata:
      hostFromEnv: RABBITMQ_MANAGEMENT_URL
```
when defining the `ScaledObject` and it becomes ready but I'm curious why my initial approach using `TriggerAuthentication` didn't work?
