### DISCUSSION TITLE
azure-pipelines: scaler kills agents in use

### DISCUSSION THREAD

**Discussion by zayacb** [kedacore/keda#5492] [Q&A / Need Help] [answered]
Hello,
I'm testing keda v2.13 with our self-hosted azure build agents (they are deployed on aws eks v1.25.16)

After some tests I noticed that some jobs fail with the following error:
`##[error]The agent has received a shutdown signal. This can happen when the agent service is stopped, or a manually started agent is canceled.`

Is there anything I can do to prevent this?

resources I deployed: 
```
apiVersion: v1
kind: Secret
metadata:
  name: pipeline-auth
data:
  personalAccessToken: 'token'
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pipeline-trigger-auth
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: pipeline-auth
      key: personalAccessToken
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-pipelines-scaledobject
spec:
  scaleTargetRef:
    name: azdevops-deployment
  minReplicaCount: 1
  maxReplicaCount: 7
  triggers:
  - type: azure-pipelines
    metadata:
      poolName: "pool-name"
      organizationURLFromEnv: "AZP_URL"
    authenticationRef:
     name: pipeline-trigger-auth
```
