### DISCUSSION TITLE
using the rabbitmq scaler, why does it scale up to max if there are no messages?

### DISCUSSION THREAD

**Discussion by Loki-Afro** [kedacore/keda#5509] [General]
hi there,

i'm trying to figure out why after all messages in a queue have been processed without reaching the `maxReplicaCount` it still goes up to `maxReplicaCount` instead of scaling down

what i want:
- scale to 0 if there are no messages in certain queue
- scale maximum up to 40, if there are messages in the queue (it doesn't need to be abruptly 40)
- scale down of there are no messages in the queue

some extra info: 
- usually there are no messages in the queue, they get created via another job, like every few hours a few thousands up to many thousands
- each messages takes way under a second to process
- prefetch count is set to 25
- in my test scenario there are ~2700 messages, so really not much

this is my scaled object:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: api-ldap-worker-scaledobject
  namespace: bc-6559
  labels:
    app: api-worker
spec:
  scaleTargetRef:
    name: api-worker-deployment
  idleReplicaCount: 0
  minReplicaCount: 1
  maxReplicaCount: 40
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: sync_ldap
      mode: QueueLength
      value: "1"
    authenticationRef:
      name: rabbitmq-trigger-auth
```

here is what i observed:
- scale up to 1
- after 30 seconds scale up to 4
- all messages are processed already (also no non-acknowledged are left)
- 30 seconds after it has been scaled up to 4 it scales it up to 8
- 30 seconds later 16
- 30 seconds later 32
- 30 seconds later 40
- 30 seconds later 0 

now my question: why is it not scaling back to 0, if there are no messages left?
