### DISCUSSION TITLE
Creation of ScaledObject - FAILURE - admission webhook "vscaledobject.kb.io" denied the request: no matches for kind "DeploymentConfig" in version "apps/v1" -

### DISCUSSION THREAD

**Discussion by rahulakkina** [kedacore/keda#5510] [Q&A / Need Help]
Trying to configure a new ScaledObject for the first time on a OpenShift 4.10+ namespace using Custom Metrics Autoscaler(KEDA)=
2.11.2-322 (Provided by RedHat)

```
kind: ScaledObject
apiVersion: keda.sh/v1alpha1
metadata:
  name: prometheus-audit-scaledobject
  namespace: sample-namespace
spec:
  cooldownPeriod: 1200
  maxReplicaCount: 1
  minReplicaCount: 0
  pollingInterval: 30
  scaleTargetRef:   
    name: audit   
    kind: Deployment
  triggers:
    - metadata:     
        serverAddress: http://prometheus-service:9090    
        threshold: '1'
        activationThreshold: '0'
        namespace: 'sample-namespace'
        query: sum(rate(kafka_consumer_group_ConsumerLagMetrics_Value{topic="audit-events", name="OffsetLag", namespace="sample-namespace", groupId="audit-service"}[1m]))
        authModes: "basic"
      type: prometheus
      authenticationRef:
        name: keda-prometheus-credentials
```

When We're trying apply the following we're receiving an error as below

```
An error occurred
admission webhook "vscaledobject.kb.io" denied the request: no matches for kind "DeploymentConfig" in version "v1"
```

Tried to set kind: ReplicationController which doesn't help either. Have gone through existing Admin Webhook conditions discussed in the [page](https://keda.sh/docs/2.11/concepts/admission-webhooks/) and can confirm 

- The scaled workload (scaledobject.spec.scaleTargetRef) is already autoscaled by another other sources (other ScaledObject or HPA).
- CPU and/or Memory trigger are used and the scaled workload doesn’t have the requests defined. This rule doesn’t apply to all the workload types, only to Deployment and StatefulSet.
  > Can confirm that there isn't any HPA running against the DeploymentConfig that was targeted.
- CPU and/or Memory trigger are the only used triggers and the ScaledObject defines minReplicaCount:0. This rule doesn’t apply to all the workload types, only to Deployment and StatefulSet.
 > Can confirm that there were no triggers applied
- In the case of multiple triggers where a name is specified, the name must be unique (it is not allowed to have multiple triggers with the same name)
 > Can confirm that the name is unique.

Would like to understand possible cause of the issue and ways through which we can mitigate it.

**Comment by zroubalik** [comment]
Would be better if you ask directly on Red Hat's channels, we don't support Custom Metrics Autoscaler. What is supiscious that it is trying to evalutate `DeploymentConfig` but the scaleTarget is k8s `Deployment`.

@joelsmith @jkyros FYI

**Comment by joelsmith** [comment]
This should be 
```
scaleTargetRef:
  name: audit
  apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
```
