### DISCUSSION TITLE
HPA is not showing correct in type Memory

### DISCUSSION THREAD

**Discussion by Ravikapadne** [kedacore/keda#5551] [Q&A / Need Help]
Hi Team,

I am experiencing an issue with a KEDA ScaledObject that is configured to scale a deployment based on memory utilization. The ScaledObject is intended to trigger scaling when memory usage reaches 90% of the available memory. However, the Horizontal Pod Autoscaler (HPA) created by KEDA is showing unexpected memory metrics.

The memory utilization target appears to be interpreted as 13503764070400m/3865470566400m, which seems incorrect. The m suffix suggests milli-units, but the values are orders of magnitude larger than expected.

**Expected Behavior:**

values should show in percentage (%) for memory

**KEDA HPA:**

```
>> k get hpa/keda-hpa-pscore-worker-scaledobject
NAME                                  REFERENCE                  TARGETS                      MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-pscore-worker-scaledobject   Deployment/pscore-worker   13435478016/3865470566400m   1         2         2          22m
```
KEDA Manifest:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pscore-worker-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: pscore-worker
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  120 # Optional. Default: 300 seconds
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 2 # Optional. Default: 100
  triggers:
  - type: memory
    metricType: Utilization
    metadata:
      value: "90"

```

KEDA Version: 2.13
Kubernetes Version: 1.27
Scaler(s): Memory

PFA scaledObject created by the Keda

[scaledobject.txt](https://github.com/kedacore/keda/files/14459606/scaledobject.txt)
