### DISCUSSION TITLE
If I set minReplicaCount to 0 in the ScaledObject why is the HorizontalPodAutoscaler minReplicas set to 1?

### DISCUSSION THREAD

**Discussion by ecerulm** [kedacore/keda#5585] [General] [answered]
My ScaledObject has `idleReplicaCount` and `minReplicaCount` set to 0 

```
spec:
  idleReplicaCount: 0
  minReplicaCount: 0
  maxReplicaCount:3
```
but the HPA generated by KEDA has `minReplicas: 1` , why is that?  is that the expected behaviour? 

I know keda is reading the values because if I set `minReplicaCount: 2` the HPA gets updated to `minReplicas: 2`, but if change to `minReplicaCount: 0` then the HPA gets `minReplicas: 1` 

For my setup it looks like KEDA tries to scale down the deployment to 0 replicas, and immediately after it scales from 0 to 1 (I'm assuming it's because of the HPA).

**Comment by zroubalik** [comment, marked as answer]
HPA by default doesn’t support min = 0. Feel free to ignore, ScaledObject is the important thing here. KEDA manages 0-1 scaling. https://keda.sh/docs/2.13/concepts/#architecture

**Reply by ecerulm** [reply]
Then I don't understand what is happening, my ScaledObject  has 

``` 
  spec:
    idleReplicaCount: 0
    maxReplicaCount: 7
    minReplicaCount: 0
    scaleTargetRef:
      name: nginx-deployment
    triggers:
    - metadata:
        desiredReplicas: "0"
        end: 0 17 * * *
        start: 5 13 * * *
        timezone: Europe/Stockholm
      type: cron
``` 

but I can see that  the deployment is deployment is scaled down to 0 and then back to 1 right away (I thought because of the HPA)

```
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  12m   deployment-controller  Scaled up replica set nginx-deployment-57d84f57dc to 1
  Normal  ScalingReplicaSet  12m   deployment-controller  Scaled down replica set nginx-deployment-57d84f57dc to 0 from 1
  Normal  ScalingReplicaSet  11m   deployment-controller  Scaled up replica set nginx-deployment-57d84f57dc to 1 from 0 
```

the HPA shows `the desired replica count is less than the minium replica count` which I though it mean that HPA is forcing it to be 1: 
```
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from external metric s0-cron-Europe-Stockholm-513xxx-017xxx(&LabelSelector{MatchLabels:map[strin
g]string{scaledobject.keda.sh/name: nginx-deployment,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  True    TooFewReplicas    the desired replica count is less than the minimum replica count
```
