### DISCUSSION TITLE
Delay [Pause] scaling during deployment rollout

### DISCUSSION THREAD

**Discussion by GoaMind** [kedacore/keda#5594] [Q&A / Need Help]
Good day,

Is there any way to set Keda on pause during deployment rollout? Or at least do not take newly created pods into calculation within X amount of time?

Reason:
- some applications use CPU above average during startup, but once they are fully "initialised" - usage come back to normal
- this means autoscaler with default config will have a snowball effect and put autoscaler on max, when regular rollout service deployment is happening. 

It is not a problem when service has max 4 replicas. But when service has 40 replicas, and before deployment worked on 5 replicas, then after rollout deploy - amount of replicas rapidly increased to 40 and then after `stabilizationWindowSeconds` passed, it starts to scale service to same amount of replicas as it was before deploy.

I heard about [params](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) `--horizontal-pod-autoscaler-cpu-initialization-period` and `--horizontal-pod-autoscaler-initial-readiness-delay`, but they seems not working, as with default value, HPA starts to scale up right after deployment starts

Example:
![2024-03-12 17-32-05 - KEDA Monitoring (DoTT) - All regions overview - K8s Resource Management - Dashboards - Grafana ](https://github.com/kedacore/keda/assets/1936252/3136d775-cdd2-46ce-a310-100385d7d65c)

What I'm looking for is either to:
- skipping new pods from scaling calculation for 10 minutes
- or put KEDA on pause, and then auto-unpause in 10 minutes (but there is no auto-unpausing 😄 [yet?] )

Regards,
Evgeny

**Comment by GoaMind** [comment]
Just wanted to share one finding. 
After implementing scaleUp policies
```yaml
              scaleUp:
                stabilizationWindowSeconds: 120
                selectPolicy: Min
                policies:
                  - type: Pods
                    value: 4
                    periodSeconds: 60
                  - type: Percent
                    value: 10
                    periodSeconds: 60
```
We observe that every deployment in peak hours affect performance, because scaling starts from 1 and it slows. Is there a way, that with new deployment scaling set to `previous` replicas count right away without takin `stabilizationWindowSeconds` into consideration?

Deploy happens without `replicas` property specification (which means it defaults to 1). Before policies implementation, scaling up happened lightning fast and thus this problem was not visible.
![2024-04-26 15-46-52 - Image ](https://github.com/kedacore/keda/assets/1936252/63ab6f0e-9a6b-4ed7-a511-892d4fb3de0d)

Yes, another way to specify `replicas` property in `Deployment` object and then allow HPA to scale it to necessary / desired value.
But what value we should put? Current value we have in cluster?
