### DISCUSSION TITLE
GitHub Runner Scaler does not trigger execution if workflow has a sleep statement and waits for the previous execution to complete

### DISCUSSION THREAD

**Discussion by anandanthony** [kedacore/keda#5604] [General] [answered]
We have the following GitHub workflow:

```yaml
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Wait for 60 seconds
        run: sleep 60
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
```

We have a scaled job that gets triggered in the subsequent polling interval when we the workflow is queued. Though, if we add another workflow when the previous execution on step -`sleep 60` then the new workflow does not trigger an execution until the previous one completes. Additonally, we noticed that if we start don't have the sleep and just run additional workflows then executions are created in the subsequent polling intervals correctly.

To isolate the issue, we also created a scaled job with trigger type as `azure-queue` and could see that the scaled job created executions every polling interval (if there is a message in the queue), irrespective of whether the previous execution is still running or is waiting due to a sleep operation.

Is this behavior very specific to GitHub runners and could it be addressed with settings for the scaled job.

Our scaling strategy is default, with min-max executions as 0-10.
