### DISCUSSION TITLE
KEDA Scaling not triggering for Kafka topic - Metrics showing 0 messages

### DISCUSSION THREAD

**Discussion by usmansiddiqui6** [kedacore/keda#5636] [Q&A / Need Help]
We are trying to get a KEDA scaling implemented on our Springboot service that consumes messages from a Kafka topic. We have SSL enabled on the topic and have the following configuration.

```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-kafka-credentials
  namespace: namespace-dev
spec:
  secretTargetRef:
    - parameter: key
      name: consumer-dev-secret
      key: key
    - parameter: cert
      name: consumer-dev-secret
      key: cert
    - parameter: keyPassword
      name: consumer-dev-secret
      key: keyPassword
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-consumer-dev
  labels:
    app: consumer-dev
  namespace: namespace-dev
spec:
  scaleTargetRef:
    kind: Deployment
    name: consumer-dev
  pollingInterval: 30   # 30 seconds
  cooldownPeriod:  300  # 300 seconds
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: kafka #network feed
      metadata:
        bootstrapServers: corkfk-kafka-0,corkfk-kafka-1,corkfk-kafka-2
        consumerGroup: com__consumer
        topic: com_feed_dev
        lagThreshold: '10' #default is 10
        tls: "enable"
        unsafeSsl: "true"
      authenticationRef:
        name: keda-kafka-credentials
```

It seems that our metrics are not even picking up the messages are that being pushed to the topic. Is there something we are missing here?
