### DISCUSSION TITLE
A parameter time for IdleReplicaCount

### DISCUSSION THREAD

**Discussion by miltlima** [kedacore/keda#5780] [Ideas]
Hey guys!

Basically, I use KEDA to scale some deployments to 0, and I think the idle replicaCount parameter could have another parameter for time, for example if I size my minimum replica to 1 and set the idle replica to 0 after the cooldown time, there should be a time in seconds for the idle replica to go to 0.

```yaml
  pollingInterval:  30                                     
  cooldownPeriod:   300                                    
  idleReplicaCount: 0
  idleTimeCooldown: 40                                
  minReplicaCount:  1 
```

Regards!
