### DISCUSSION TITLE
KEDA does not scale to 0

### DISCUSSION THREAD

**Discussion by OrfeasfilMLAB** [kedacore/keda#5861] [Q&A / Need Help]
Hi there,

I have a question. The configuration YAML file for the ScaledObject is the following:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 1
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prom-stack-kube-prometheus-prometheus.monitor.svc.cluster.local:9090
      metricName: sample_gauge
      threshold: '100'
      query: avg(sample_gauge)
      metricType: Value
```

I have setup up the prometheus and i get query the sample_gauge parameter. The problem is that even if the `avg(sample_counter)` is below the threshold (100) (for example the `avg(sample_gauge)` is equal to 10) no scale down to zero occurs. For example, only one pod exposes the metric `sample_gauge`, and describing the `hpa` KEDA creates you can see:

```
Name:                                      keda-hpa-nginx-scaledobject
Namespace:                                 default
Labels:                                    app.kubernetes.io/managed-by=keda-operator
                                           app.kubernetes.io/name=keda-hpa-nginx-scaledobject
                                           app.kubernetes.io/part-of=nginx-scaledobject
                                           app.kubernetes.io/version=2.14.0
                                           scaledobject.keda.sh/name=nginx-scaledobject
Annotations:                               <none>
CreationTimestamp:                         Wed, 05 Jun 2024 12:52:54 +0300
Reference:                                 Deployment/nginx-deployment
Metrics:                                   ( current / target )
  "s0-prometheus" (target average value):  10 / 100
Min replicas:                              1
Max replicas:                              10
Deployment pods:                           1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from external metric s0-prometheus(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:
 nginx-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:           <none>

```
Another weird thing is that when i set the metric `sample_gauge` equal to 0 (so the `avg(sample_gauge)` is equal to 0) then scale down to 0 occurs. This is super weird. The expected behavior is to scale down to zero when the metric is below the threshold.... right??

I use `Kubernetes 1.27`.

TIny Question: Why to use KEDA instead of the native `HPAScaleToZero` feature of Kubernetes?
