### DISCUSSION TITLE
Multiple SWS ScaledObjects not working

### DISCUSSION THREAD

**Discussion by yapjinkun** [kedacore/keda#5863] [Q&A / Need Help] [answered]
Hi,

I'm trying to setup multiple sqs endpoints, each sqs endpoint will have it's own deployment target under same EKS cluster.

However, KEDA only works when I only have 1 scaledobject, if I created more than 1, all scaledObject will stopped working until I deleted and remain only 1 scaledobject in my cluster. 

Below are my scaledobject yaml files

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-app-1 
  minReplicaCount: 1  
  maxReplicaCount: 100
  pollingInterval: 30
  cooldownPeriod:  10
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-aws-credentials
    metadata:
      queueURL: https://sqs.ap-southeast-1.amazonaws.com/123456/KEDA-test.fifo
      queueLength: "2"
      awsRegion: ap-southeast-1
      identityOwner: operator
``` 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject-alt
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-app-2
  minReplicaCount: 1  
  maxReplicaCount: 100
  pollingInterval: 30 
  cooldownPeriod:  10 
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-aws-credentials
    metadata:
      queueURL: https://sqs.ap-southeast-1.amazonaws.com/123456/KEDA-test2.fifo
      queueLength: "3"
      awsRegion: ap-southeast-1
      identityOwner: operator
```

Is this a limitation/bug/something i missed out.
