### DISCUSSION TITLE
I can't work out how to configure Redis Lists trigger for Celery queues with priorities

### DISCUSSION THREAD

**Discussion by bumper-jorge-pino** [kedacore/keda#5868] [Q&A / Need Help]
I'm currently using Redis as a broker for Celery asynchronous tasks. Before implementing any priorities to the tasks I had Keda running successfully. Here my trigger setup:

```
  triggers:
  - type: redis
    metadata:
      address: [my_redis_host]
      listName: celery
      listLength: 100
```

Since we have implemented priorities to the tasks, queues are now split into 4 different queues with different names. The highest priority queue will be named celery, and the the other queues will have a separator (by default x06x16) and their priority number appended to the queue name.

```
['celery', 'celery\x06\x163', 'celery\x06\x166', 'celery\x06\x169']
```

I do wonder if `listName` parameter could accept a list of queues and do the sum of items to determine the total number of tasks queued.

Any suggestions or help will be very welcome.

Regards.
Jorge
