### DISCUSSION TITLE
Is it possible to use TriggerAuthentication podIdentity with external scalers?

### DISCUSSION THREAD

**Discussion by karpikpl** [kedacore/keda#5879] [Q&A / Need Help] [answered]
Something like this - I'm using Keda 2.11.1

```yaml
# Create KEDA scaled object to scale order processor application.
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-cosmosdb-auth
  namespace: cosmosdb-order-processor
spec:
  podIdentity:
    provider: azure-workload
    identityId: 00000-00000-00000-00000
---    
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cosmosdb-order-processor-scaledobject
  namespace: cosmosdb-order-processor
spec:
  pollingInterval: 20
  scaleTargetRef:
    name: cosmosdb-order-processor
  triggers:
    - type: external
      authenticationRef:
        name: azure-cosmosdb-auth # authenticationRef would need either podIdentity or define a connection parameter
      metadata:
        scalerAddress: cosmosdb-scaler.cosmosdb-order-processor:4050
        endpoint: https://{cosmos}.documents.azure.com:443/ # update as per your environment
        databaseId: StoreDatabase
        containerId: OrderContainer
        LeaseEndpoint: https://{cosmos}.documents.azure.com:443/ # update as per your environment
        leaseDatabaseId: StoreDatabase
        leaseContainerId: OrderProcessorLeases
        processorName: OrderProcessor

```
