### DISCUSSION TITLE
[Scaled Object] Scaling based on multiple metrics

### DISCUSSION THREAD

**Discussion by MnLujan** [kedacore/keda#5884] [Q&A / Need Help]
Hey, I'm implementing a ScaledObject to scale our services based on various metrics obtained from GCP via Stackdriver. I have a total of 3 metrics from `stackdriver`. In a specific scenario, I need to divide two metrics using the `scalingModifiers` feature. The third metric is latency, which I see from the KEDA operator logs is being fetched successfully and reaches the configured target value, but the service never scales. Is this a limitation of KEDA? Should I add any logic within `scalingModifiers` to enable scaling? I'm sharing the ScaledObject definition for better context. Thanks for the help.

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: keda-master-web
  name: **-keda-scaledobject
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
spec:
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name:
  pollingInterval: 60
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    restoreToOriginalReplicaCount: true
    scalingModifiers:
      formula: "ceil(request_per_minute/current_replicas)" 
      target: "160"
      metricType: Value
  triggers:
    - type: "gcp-stackdriver"
      name: request_per_minute
      authenticationRef:
        name: **-keda-trigger-authentication
      metadata:
        projectId: ****
        filter: 'metric.type="istio.io/service/server/request_count" ...
        targetValue: "160"
        activationTargetValue: "0"
        alignmentPeriodSeconds: "60"
        credentialsFromEnv: "GOOGLE_APPLICATION_CREDENTIALS"
        aligmentAligner: sum
        aligmentReducer: none
      metricType: Value
      useCachedMetrics: true
    - type: "gcp-stackdriver"
      name: current_replicas
      authenticationRef:
        name: *-keda-trigger-authentication
      metadata:
        projectId: ***
        filter: 'metric.type="prometheus.googleapis.com/kube_horizontalpodautoscaler_status_current_replicas/gauge" .... activationTargetValue: "0"                        
        alignmentPeriodSeconds: "60"                        
        credentialsFromEnv: "GOOGLE_APPLICATION_CREDENTIALS" 
        aligmentAligner: sum
      metricType: Value
      useCachedMetrics: true
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
    - type: "gcp-stackdriver"
      name: responses_latency
      authenticationRef:
        name: ***-keda-trigger-authentication
      metadata:
        projectId: ****
        filter: 'metric.type="istio.io/service/server/response_latencies" ...'
        activationTargetValue: "0"                        
        alignmentPeriodSeconds: "60"                        
        credentialsFromEnv: "GOOGLE_APPLICATION_CREDENTIALS" 
        alignmentAligner: "percentile_95"
        valueIfNull: "0.0"
        targetValue: "2500" #millisecond
      metricType: Value
      useCachedMetrics: true
```

Also, I share the keda-operator logs: 

```
scale_handler	Reading metrics from cache	{"scaledObject.Namespace": "", "scaledObject.Name": "", "scaler": "responses_latency", "metricName": "s3-gcp-stackdriver-***", "metricsRecord": {"IsActive":true,"Metric":[{"metricName":"s3-gcp-stackdriver-***","metricLabels":null,"timestamp":"2024-06-13T14:16:37Z","value":"15155200m"}],"ScalerError":null}}

```
