### DISCUSSION TITLE
Can autoscaling work with KEDA using Prometheus and Cron target

### DISCUSSION THREAD

**Discussion by kadhamecha-conga** [kedacore/keda#5891] [Q&A / Need Help] [answered]
hi ,

can Keda autoscaling work with two target ?
is below spec correct to achieve  the goal ?

```
- apiVersion: keda.sh/v1alpha1
    kind: ScaledObject
    metadata:
      name: example-app-scale
    spec:
      maxReplicaCount: 10
      minReplicaCount: 1
      scaleTargetRef:
        kind: Deployment
        name: example-app
      triggers:
      - type: prometheus
        metadata:
          serverAddress: http://prometheus.monitoring:9090
          metricName: http_requests_total
          threshold: "100"
          query: sum(rate(http_requests_total{job="example-app"}[2m]))
      - type: cron
        metadata:
          timezone: US/Eastern
          start: "0 6 * * 6"
          end: "0 0 * * 0"
          desiredReplicas: "1"      
      advanced:
        horizontalPodAutoscalerConfig:
          behavior:
            scaleDown:
              stabilizationWindowSeconds: 1800


```
thanks.
