### DISCUSSION TITLE
KEDA with docker desktop and Azure Service bus connection string for Trigger Authentication

### DISCUSSION THREAD

**Discussion by brijesh-1111** [kedacore/keda#5951] [Q&A / Need Help] [answered]
I need some help configuring KEDA in my local docker desktop for service bus trigger function. It is all working tested in Azure AKS but I like to setup the same in my local Docker Desktop.

In AKS, we use Managed workload identity but I believe that is not quite possible in Docker Desktop local environment (with Visual Studio Identity) so, I like to use the connection string approach. I hope that is possible and I tried it but unfortunately, It is not working for me.

Here is my yaml if someone can suggest where I am wrong.

It is giving me an error message: **0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.**

```
apiVersion: v1
kind: Secret
metadata:
  name: mygate-secret
  namespace: mygate-function
data:
  servicebus-connectionstring: xxxxxx
---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mygate-auth
  namespace: mygate-function
spec:
  secretTargetRef:
  - parameter: connection
    name: mygate-secret
    key: servicebus-connectionstring
---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mygatefunction-customerpropertystatuschange-scaledobject
  namespace: mygate-function
spec:
  scaleTargetRef:
    name: mygatefunction-customerpropertystatuschange-deployment
  minReplicaCount: 0
  maxReplicaCount: 1
triggers:
- type: azure-servicebus
  metadata:
    namespace: mygate
    subscriptionName: customerproperty-statuschangeevent-processor
    topicName: customerproperty-statuschangeevent
  authenticationRef:
    name: mygatefunction-customerpropertystatuschange-auth
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygatefunction-customerpropertystatuschange-deployment
  namespace: mygate-function
  labels:
    app: mygatefunction-customerpropertystatuschange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mygatefunction-customerpropertystatuschange
    spec:
      containers:
      - name: mygatefunction-customerpropertystatuschange
        image: mygatefunction-customerpropertystatuschange:latest
        envFrom:
        - secretRef:
            name: mygate-secret
```
