### DISCUSSION TITLE
Trigger scaling of multiple Deployment with the same Kafka metrics

### DISCUSSION THREAD

**Discussion by alessio1983lx** [kedacore/keda#6006] [Q&A / Need Help] [answered]
Hi, here is my scaled object:
```

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
spec:
  scaleTargetRef:
    name: nginx-deployment 
  pollingInterval: 5
  cooldownPeriod: 10
  minReplicaCount: 0
  maxReplicaCount: 1
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka-kafka-bootstrap.default.svc.cluster.local:9092
      consumerGroup: cli-group
      topic: topic1
      scaleToZeroOnInvalidOffset: "true"
      offsetResetPolicy: earliest
      lagThreshold: "1"
```

It scales the nginx-deployment deployment to replica 1 when there is a message on the kafka topic, it scale to zero when it is consumed by a consumer in the consumer group kafka-cli

If i want to trigger  the scaler to more than one Deployment with that metric, should i just create other scaled objects with different name, target deployment and same trigger? Or is there another best practice?

Thanks for the replies

Bye!
