### DISCUSSION TITLE
error inspecting ActiveMQ queue size: invalid character '<' looking for beginning of value

### DISCUSSION THREAD

**Discussion by andretapxure** [kedacore/keda#6067] [Q&A / Need Help]
Hi! I have keda with activemq 6.1.2. My configuration file is bellow. When I try to deploy the keda sacaledobject, I have error on logs like
```2024-08-12T15:01:49Z	ERROR	scale_handler	error getting scale decision	{"scaledObject.Namespace": "qa-rj", "scaledObject.Name": "dfe-engines-processamento-scaledobject", "scaler": "activeMQScaler", "error": "error inspecting ActiveMQ queue size: invalid character '<' looking for beginning of value"}```
------
My Keda configuration
```
apiVersion: v1
kind: Secret
metadata:
  name: activemq-secret
  namespace: qa-rj
type: Opaque
data:
  activemq-password: ACTIVEMQ_PASSWORD
  activemq-username: ACTIVEMQ_USERNAME
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-activemq
  namespace: qa-rj
spec:
  secretTargetRef:
  - parameter: username
    name: activemq-secret
    key: activemq-username
  - parameter: password
    name: activemq-secret
    key: activemq-password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dfe-engines-processamento-scaledobject
  namespace: qa-rj
spec:
  scaleTargetRef:
    name: dfe-engines-processamento 
  pollingInterval: 5
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 18
  fallback:
    failureThreshold: 3
    replicas: 1
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      name: keda-hpa-dfe-engines-processamento
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
            - type: Percent
              value: 50
              periodSeconds: 60
  triggers:
  - type: activemq
    metadata:
      managementEndpoint: "10.0.3.39:8160"
      destinationName: "tapxure_queue"
      brokerName: "localhost"
      targetQueueSize: "50"
    authenticationRef:
      name: trigger-auth-activemq

```
