### DISCUSSION TITLE
RabbitMQ HTTP Protocol Scaler Deprecation

### DISCUSSION THREAD

**Discussion by SeWieland** [kedacore/keda#6071] [General]
The RabbitMQ team announced the [deprecation of the managment API metrics](https://www.rabbitmq.com/blog/2021/08/21/4.0-deprecation-announcements#disable-metrics-delivery-via-the-management-api--ui) a while ago and I think it would be worth noting this somewhere in the docs.

If your RabbitMQ configaration contains the line `deprecated_features.permit.management_metrics_collection`, the KEDA scaler may not be able to retrieve its metrics anymore.

New scaling strategies should therefore ideally be based on the prometheus scaler directly.

**Comment by JorTurFer** [comment]
I'm not fully sure if we are affected by this as we use the administrative API. Should I see any error/warning when using the current api with latest rabbitmq versions?

**Reply by JorTurFer** [reply]
I've tested it and you're right. This can be a problem for the scaler as Prometheus metrics need to be aggregated, and it can also produce a lack of features (like the regex).
Maybe we could request the metrics directly to the Prometheus exporter and aggregate them somehow. 
@zroubalik @tomkerkhove WDYT?

**Comment by SeWieland** [comment]
I think it's not worth overthinking the probelm.
Marking the HTTP scaler for rabbitmq as deprecated with a big warning and showing an alternative might just be enough.
It will help others not implementing solutions that are based on a deprecated feature and will be not working quite soon.

Example:

old trigger

```yaml
triggers:
  - type: rabbitmq
    name: queueLengthTrigger
    metricType: AverageValue
    metadata:
      excludeUnacknowledged: "false"
      mode: QueueLength
      operation: sum
      queueName: ^Do(SomeThing|AnotherThing)$
      useRegex: "true"
      value: "10"
```

new trigger

```yaml
triggers:
  - type: prometheus
    name: queueLengthTrigger
    metricType: AverageValue
    metadata:
      query: sum(rabbitmq_queue_messages{queue=~"^Do(SomeThing|AnotherThing)$"})
      serverAddress: http://prometheus.prometheus.svc.cluster.local:9090
      threshold: "10"
```
