### DISCUSSION TITLE
KEDA Metrics 404 page not found

### DISCUSSION THREAD

**Discussion by itsham-sajid** [kedacore/keda#6074] [Q&A / Need Help]
KEDA Version: [v2.15.0](https://github.com/kedacore/keda/releases/tag/v2.15.0)
Kubernetes version: 1.29.7

We’re trying to expose the KEDA operator Prometheus metrics so we can get information on KEDA, when the scaler is active, paused, scaler metrics values, number of errors for each scaler etc.. https://keda.sh/docs/2.15/operate/prometheus/
 
From the KEDA Helm chart [values](https://github.com/kedacore/charts/blob/main/keda/values.yaml
) for enabling metrics we’ve added the following configuration:  

```
metricsServer:
  replicaCount: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
                - keda-operator-metrics-apiserver
          topologyKey: "kubernetes.io/hostname"
  logging:
    operator:
      level: debug
      format: console
      timeEncoding: rfc3339
      stackTracesEnabled: false
    metricServer:
      level: 4
      stderrthreshold: ERROR
  prometheus:
    metricServer:
      enabled: false
      port: 8080
      portName: metrics
      serviceMonitor:
        enabled: true
        port: metrics
        interval: "30s"
        scrapeTimeout: "10s"
        scheme: http
    operator:
      enabled: false
      port: 8080
      serviceMonitor:
        enabled: false
        port: metrics
        interval: "30s"
        scrapeTimeout: "10s"
        scheme: http
```

But when connecting to the cluster using Lens, from the pod keda-operator-metrics-apiserver if I enable port forwarding on the port metrics:8080/TCP  I get 404 page not found when trying to access the url.
