### DISCUSSION TITLE
Combine multiple triggers as "AND" instead

### DISCUSSION THREAD

**Discussion by ArzelaAscoIi** [kedacore/keda#6086] [Q&A / Need Help] [answered]
We are using keda to scale deployments based on a queue length. For efficiency reasons it would be very helpful to pause the upscaling of this job based on the number of replicas/pods of a deployment. (If there is no pod available, it means that the application that reads the data went idle and we therefore want to pause scaling up of the jobs 

I tried this as a very rough sketch: https://github.com/kedacore/keda/compare/main...ArzelaAscoIi:keda:feat/compositeScaler?expand=1 . A composition scaler that takes the SQS and Kubernetes workload scaler and only scales if  both would scale. 

however, for us it would be easier if it would be possible to do something like this: 

```
triggerOperation: 'AND' # THIS IS NEW <- simply tells keda how to evaluate the triggers. 
triggerEvaluater: 'MIN' #Alternative: always assume that the min of both should be the used one 
triggers:
- type: kubernetes-workload
  metadata:
    podSelector: 'app=backend'
    value: '0.5'
    activationValue: '3.1'
- type: aws-sqs-queue
  metadata:
    # Required: queueURL or queueURLFromEnv. If both provided, uses queueURL
    queueURL: https://sqs.eu-west-1.amazonaws.com/account_id/QueueName
    queueURLFromEnv: QUEUE_URL # Optional. You can use this instead of `queueURL` parameter
    queueLength: "5"  # Default: "5"
    # Required: awsRegion
    awsRegion: "eu-west-1"
    # Optional: awsEndpoint
    awsEndpoint: ""
    # DEPRECATED: This parameter is deprecated as of KEDA v2.13 and will be removed in v3. Optional # Optional. Default: pod
    identityOwner: pod | operator
```

Is there a smart way to combine triggers like this ? Or is it the suggested way to implement a custom scaler ? (
