### DISCUSSION TITLE
Cooldowns when using Cron scaler

### DISCUSSION THREAD

**Discussion by lauri-leirost** [kedacore/keda#6105] [Q&A / Need Help]
Hello, 

I have a long running nginx deployment that I'd like to scale down during nights. I have the following configuration and it works just fine.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaling-for-nginx
spec:
  scaleTargetRef:
    name: nginx
  pollingInterval: 30
  initialCooldownPeriod: 60
  cooldownPeriod: 120
  minReplicaCount: 0
  triggers:
    - type: cron
      metadata:
        timezone: Europe/London
        start: 0 7 * * 1-5
        end: 0 22 * * 1-5
        desiredReplicas: "1"
```

However as our CI system might run during the night and as a part of that it would `kubectl apply` the above nginx deployment (and other components) and wait for them all to be in running state. The behaviour I have observed is that Keda will scale the nginx deployment to zero in unpredictable time (anywhere from 5 to 50 seconds). I can't see the `initialCooldownPeriod` or `cooldownPeriod` fields affecting this. Is there any way of reliably delaying the downscaling to zero for example to 10 minutes since applying the deployment?
