### DISCUSSION TITLE
Metrics not exported?

### DISCUSSION THREAD

**Discussion by ngc4579** [kedacore/keda#6109] [Q&A / Need Help]
The provided Grafana [dashboard](https://github.com/kedacore/keda/blob/main/config/grafana/keda-dashboard.json) features metrics like `keda_scaler_detail_errors_total` and others, prefixed `keda_`.

In contrast to that, the metrics endpoints of the operator and metrics server deployments do not seem to provide those metrics.

The only metrics I see when asking the `/metrics` endpoints are

- `keda_build_info` and
- various `keda_internal_` prefixed metrics.

Keda deployed via Helm Chart, config:

```yaml
...
prometheus:
  metricServer:
    enabled: true
    serviceMonitor:
      enabled: true
  operator:
    enabled: true
    serviceMonitor:
      enabled: true
  webhooks:
    enabled: true
    serviceMonitor:
      enabled: true
```

Any hints on this?
