### DISCUSSION TITLE
KEDA not able to scale pods based on GPU metrics

### DISCUSSION THREAD

**Discussion by Vijaygawate** [kedacore/keda#6133] [Q&A / Need Help]
I am using below configs for scaled object, in which I want to scale HPA based on GPU metrics,
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: gpu-dcgmproftester-deployment-scaledobject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gpu-api
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-operated.prometheus:9090/
      metricName: DCGM_FI_DEV_GPU_UTIL
      threshold: "10"
      query: sum(avg_over_time(DCGM_FI_DEV_GPU_UTIL{pod=~"gpu-api-.*"}[10s])) 
```
My GPU utilization is over 10% i.e 28% but still KEDA didn't scale pods
I have checked, HPA logs it says, validmetricfound, and dont see any error.
Can anyone help me here? how can I troubleshoot this? I want to check why it is not scaling up
