### DISCUSSION TITLE
KEDA Deployment Not Found

### DISCUSSION THREAD

**Discussion by tusharvaswani714** [kedacore/keda#6137] [Q&A / Need Help]
Hey everyone. I have this RunnerDeployment resource:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
    annotations:
        karpenter.sh/do-not-evict: "true"
    name: actions-runner-deployment
    namespace: actions
spec:
    template:
        spec:
            labels:
                - self-hosted-linux
            organization: SecondBrainLabs-SBL
            resources:
                requests:
                    cpu: 1500m
                    memory: 2000Mi
```

and I have this keda scaled object for that RunnerDeployment resource:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
    name: actions-runner-scaled-object
    namespace: actions
spec:
    scaleTargetRef:
        apiVersion: actions.summerwind.dev/v1alpha1
        kind: RunnerDeployment
        name: actions-runner-deployment
    minReplicaCount: 0
    maxReplicaCount: 1
    triggers:
        - type: github-runner
          metadata:
              githubApiURL: "https://api.github.com/"
              owner: "SecondBrainLabs-SBL"
              runnerScope: "org"
              targetWorkflowQueueLength: "1"
          authenticationRef:
              name: actions-runner-trigger-auth
```

Even though scaleTargetRef looks correct it's not scaling down to 0. These are the logs I see:

```
2024-09-05T12:37:53Z	ERROR	ScaledObject doesn't have correct scaleTargetRef specification	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"actions-runner-scaled-object","namespace":"actions"}, "namespace": "actions", "name": "actions-runner-scaled-object", "reconcileID": "83a4d871-7f02-4b19-a8cf-fd74507e26e1", "error": "runnerdeployments.actions.summerwind.dev \"actions-runner-deployment\" not found"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:194
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
```

If anyone could help that will be great.
Thanks
