### DISCUSSION TITLE
Azure Pipeline Scaler with Key Vault Trigger Authentication

### DISCUSSION THREAD

**Discussion by haithamshahin333** [kedacore/keda#6139] [Q&A / Need Help] [answered]
Hello,

Any way someone can clarify how exactly the personalAccessToken manifests itself in the scaled job agent? I'm getting an "AZP_TOKEN" missing error, but I'm not sure if the personalAccessToken parameter from the trigger authentication which is using Azure Key Vault is being injected as an environment variable.

https://keda.sh/docs/2.15/scalers/azure-pipelines/

Key Vault Trigger Authentication:

```yaml
azureKeyVault:                                          # Optional.
  vaultUri: {key-vault-address}                         # Required.
  credentials:                                          
    clientId: {azure-ad-client-id}                      
    clientSecret:                                      
      valueFrom:                                        
        secretKeyRef:                                  
          name: {k8s-secret-with-azure-ad-secret}     
          key: {key-within-the-secret}                  
    tenantId: {azure-ad-tenant-id}                      
  cloud:                                            
    type: AzureUSGovernmentCloud.
  secrets:                                             
  - parameter:  personalAccessToken 
    name: pat                      
```
