### DISCUSSION TITLE
keda error parsing azure Pipelines metadata:

### DISCUSSION THREAD

**Discussion by mshetsyan** [kedacore/keda#6152] [General]
my scaled object can't pare the devops organization name when i use trigger type   azure-pipelines
here is my error message from keda-operator.

2024-09-11T18:38:27Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"onehub-scaledobject","namespace":"agents-test1"}, "namespace": "agents-test1", "name": "onehub-scaledobject", "reconcileID": "1c673b28-2c44-4287-bf67-4ac97dd6d68b", "error": "error parsing azure Pipelines metadata: failed to extract organization name from organizationURL"}

and here is my scaledobect's yaml manifes

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaledobject
  namespace: agents-test1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: agent
  minReplicaCount: 2
  maxReplicaCount: 5
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: '{POOL_ID}'
      organizationURLFromEnv: https://dev.azure.com/{MY-Organization}
      personalAccessTokenFromEnv: {PAT}
```

**Comment by glaucius** [comment]
I'm facing same issue man, tryied a lot of times and same results. if you could fix it, please, post here

**Reply by ismarhadzic-os** [reply]
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-devops-deploy-agent-scaler
  namespace: azure-devops
spec:
  scaleTargetRef:
    name: azure-devops-deploy-agent  # Name of your Deployment
  pollingInterval: 15                 # Check every 30 seconds
  cooldownPeriod: 180                 # Wait for 3 minutes before scaling down
  minReplicaCount: 0
  maxReplicaCount: 3
  triggers:
    - type: azure-pipelines
      metadata:
        organizationURLFromEnv: "AZP_URL"
        poolName: "DeployPool"
        poolID: "12"
        targetPendingRequests: "1"  # Scale up when there’s 1 or more pending jobs
      authenticationRef:
        name: azure-devops-pat-auth-deploy
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-devops-pat-auth-deploy
  namespace: azure-devops
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: azure-devops-pat
      key: AZP_TOKEN
    - parameter: organizationURL
      name: azure-devops-org
      key: AZP_URL
```
