### DISCUSSION TITLE
Azure Devops Pipeline Bug

### DISCUSSION THREAD

**Discussion by glaucius** [kedacore/keda#6164] [General] [answered]
Hey guys, I'm having an issue to deploy a scaler for my Azure Devops pool

1 - yaml manifest

````
apiVersion: v1
kind: Secret
metadata:
  name: pipeline-auth
  namespace: azuredevops
data:
  personalAccessToken: "{my_pat_with_base64}"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pipeline-trigger-auth
  namespace: azuredevops
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: pipeline-auth
      key: personalAccessToken
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-pipelines-scaledobject
  namespace: azuredevops
spec:
  scaleTargetRef:
    name: azuredevops
  minReplicaCount: 1
  maxReplicaCount: 5 
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: "146"
      organizationURLFromEnv: "https://dev.azure.com/MyOrg"
    authenticationRef:
     name: pipeline-trigger-auth
```

2 - Error log:
2024-09-13T20:15:07Z    ERROR   Reconciler error        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"azure-pipelines-scaledobject","namespace":"azuredevops"}, "namespace": "azuredevops", "name": "azure-pipelines-scaledobject", "reconcileID": "b333e2a4-9343-4af6-8d24-7791b7c9f68d", "error": "error parsing azure Pipelines metadata: failed to extract organization name from organizationURL"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227

3 - Scaled object description

Name:         azure-pipelines-scaledobject
Namespace:    azuredevops
Labels:       scaledobject.keda.sh/name=azure-pipelines-scaledobject
Annotations:  <none>
API Version:  keda.sh/v1alpha1
Kind:         ScaledObject
Metadata:
  Creation Timestamp:  2024-09-13T20:06:54Z
  Finalizers:
    finalizer.keda.sh
  Generation:        5
  Resource Version:  9500137
  UID:               5093fdd5-3dac-43be-a629-c5cce9d8c7f1
Spec:
  Max Replica Count:  5
  Min Replica Count:  1
  Scale Target Ref:
    Name:  azuredevops
  Triggers:
    Authentication Ref:
      Name:  pipeline-trigger-auth
    Metadata:
      Organization URL From Env:  https://dev.azure.com/MyOrg
      Pool ID:                    146
    Type:                         azure-pipelines
Status:
  Conditions:
    Message:               failed to ensure HPA is correctly created for ScaledObject
    Reason:                ScaledObjectCheckFailed
    Status:                False
    Type:                  Ready
    Message:               ScaledObject check failed
    Reason:                UnknownState
    Status:                Unknown
    Type:                  Active
    Status:                Unknown
    Type:                  Fallback
    Status:                Unknown
    Type:                  Paused
  Original Replica Count:  0
  Scale Target GVKR:
    Group:            apps
    Kind:             Deployment
    Resource:         deployments
    Version:          v1
  Scale Target Kind:  apps/v1.Deployment
Events:
  Type     Reason                   Age                 From           Message
  ----     ------                   ----                ----           -------
  Warning  ScaledObjectCheckFailed  15m (x12 over 15m)  keda-operator  failed to ensure HPA is correctly created for ScaledObject
  Warning  KEDAScalerFailed         10m (x18 over 15m)  keda-operator  error parsing azure Pipelines metadata: failed to extract organization name from organizationURL

I tried a lot of times, deleting everything and creating again, but allways same error.

thanks !!!!!
