### DISCUSSION TITLE
KEDA is not scaling beyond one replica using azure storage queue

### DISCUSSION THREAD

**Discussion by led94** [kedacore/keda#6167] [Q&A / Need Help]
Hi there! 

I am having an issue when trying to scale from azure storage queue, seems like it is not properly calculating the messages on the queue and it never goes beyond 1 replica. 

Here is my scaled object 
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-so
  namespace: digitalafe-24246-dev
spec:
  scaleTargetRef:
    name: nginx
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  30 # Optional. Default: 300 seconds
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: azure-queue
    metadata:
      queueName: catfish22
      # Does not seen to work: Target value for queue length passed to the scaler.
      # so below, if there are 9 messages, 3 pods should be created
      queueLength: '3'
      activationQueueLength: '0'
      connectionFromEnv: CONNECTION_STRING
      accountName: gjmfunky2
      cloud: AzurePublicCloud
```

If there are no messages on the queue it properly scales to 0, but once I add messages it goes to one and never scales beyond it, I have tested with 15 messages but it just stays on 1.

The deployment is just an nginx deployment (I am doing a PoC to see if it works) and has nothing special to it 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: digitalafe-24246-dev
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        sidecar.istio.io/inject: "false"              
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
        resources: 
          requests:
            cpu: 1
            memory: 64Mi
          limits:
            cpu: 1
            memory: 64Mi
        env: 
        - name: FOO
          value: BAR
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: gjm-keda
              key: CONNECTION_STRING
```
              
The keda version I have is 2.13.0, I am working on AKS, and my kubernetes version is 1.30.3. On the logs I do not see any errors, just this when I started the test

```json
2024-09-16T16:45:17Z	INFO	scaleexecutor	Successfully updated ScaleTarget	{"scaledobject.Name": "queue-so", "scaledObject.Namespace": "digitalafe-24246-dev", "scaleTarget.Name": "nginx", "Original Replicas Count": 0, "New Replicas Count": 1}
2024-09-16T16:45:47Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"queue-so","namespace":"digitalafe-24246-dev"}, "namespace": "digitalafe-24246-dev", "name": "queue-so", "reconcileID": "b06001fa-0c3a-43ae-890e-366360c67934"}
```

Let me know if I can share anything else.
