### DISCUSSION TITLE
"error": "error parsing metric API metadata: no username given"

### DISCUSSION THREAD

**Discussion by itsham-sajid** [kedacore/keda#6234] [Q&A / Need Help] [answered]
I've setup the Metrics API KEDA scaler but I'm having issues with getting the basic credentials to work. From the KEDA  operator logs I keep getting this error "error": "error parsing metric API metadata: no username given" 

So below is the secrets I've created

```
apiVersion: v1
kind: Secret
metadata:
  name: keda-metric-api-secret
  namespace: default
data:
  username: "NDYxgfdfgd44w"
  password: "Z2xjX2V5SXlJaXdpYmlJNkluUmxjM1F"

---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-metric-api-creds
  namespace: default
spec:
  secrets:
    - parameter: username
      name: keda-metric-api-secret
      key: username
    - parameter: password
      name: keda-metric-api-secret
      key: password
```
This is the trigger:

            {
              type = "metrics-api"
              metadata = {
                url            = "API URL goes here"
                targetValue    = "10000"
                valueLocation  = "data.result[0].value[1]"
                authMode       = "basic"
              }
              authenticationRef = {
                name = "keda-metric-api-creds"
              }
            }

But from the Keda Operator Logs I get this error:

```
2024-10-11T12:54:39Z	ERROR	scale_handler	error resolving auth params	{"type": "ScaledObject", "namespace": "default", "name": "devscaler", "triggerIndex": 1, "error": "error parsing metric API metadata: no username given"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
	/workspace/pkg/scaling/scalers_builder.go:99
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).performGetScalersCache
	/workspace/pkg/scaling/scale_handler.go:357
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalersCacheForScaledObject
	/workspace/pkg/scaling/scale_handler.go:290
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
	/workspace/pkg/scaling/scale_handler.go:430
github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
	/workspace/pkg/metricsservice/server.go:48
github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
	/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:99
google.golang.org/grpc.(*Server).processUnaryRPC
	/workspace/vendor/google.golang.org/grpc/server.go:1369
google.golang.org/grpc.(*Server).handleStream
	/workspace/vendor/google.golang.org/grpc/server.go:1780
google.golang.org/grpc.(*Server).serveStreams.func2.1
	/workspace/vendor/google.golang.org/grpc/server.go:1019
```

The API and credentials have been tested separately and they do work.

**Comment by rickbrouwer** [comment, marked as answer]
Hello,

In the `TriggerAuthentication` you use `secrets` in stead of `secretTargetRef`.
Here is an correct example:

```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-metric-api-creds
  namespace: default
spec:
  secretTargetRef:
    - parameter: username
      name: keda-metric-api-secret
      key: username
    - parameter: password
      name: keda-metric-api-secret
      key: password
```
