### DISCUSSION TITLE
Getting 509 error from RabbitMQ

### DISCUSSION THREAD

**Discussion by shahar-kela** [kedacore/keda#6281] [Q&A / Need Help]
I have an *.my-domain.private ca/intermidiate.crt.pem, server/star.my-domain.private.key.pem and server/star.my-domain.private.crt.pem.
On the secret I put the intermidiate on ca
cert is server/star.my-domain.private.crt.pem and key is server/star.my-domain.private.key.pem
host is amqps://user:password@brokers.my-domain.private:5671/
and this is my keda details
```
apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
  namespace: actors
data:
  host: YW1xcHM6Ly9E
...
  tls: ZW5hYmxl
  ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVUVENDQXpXZ0F3SUJBZ0lMQkFBQUFBQUJSRTd3TmpFd0RRWUpLb1pJa
...  
cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxVENDQWIyZ0F3SUJBZ0lKQU1kVDVVN0liV0NTTUEwR0NTcUdTSWIzRFF
...  
key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9
...
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: actors
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
    - parameter: tls
      name: keda-rabbitmq-secret
      key: tls
    - parameter: ca
      name: keda-rabbitmq-secret
      key: ca
    - parameter: cert
      name: keda-rabbitmq-secret
      key: cert
    - parameter: key
      name: keda-rabbitmq-secret
      key: key

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.name }}
  minReplicaCount: 1
  maxReplicaCount: 15
  pollingInterval: 120  
  cooldownPeriod:  300
  triggers:
  - type: rabbitmq
    metadata:
      protocol: auto
      queueName: importer
      mode: QueueLength
      value: "20"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
```

Not sure why the keda-operator on namespace keda return error 509 
what i'm doing wrong here?
