### DISCUSSION TITLE
Help with DataDog + HPA - averageValue has strange value + `m` suffix

### DISCUSSION THREAD

**Discussion by VasilKostov-Tide** [kedacore/keda#6401] [Q&A / Need Help]
Hi,
currently experiencing issues with figuring out how to propert configure a DataDog integration for HPA on memory usage.
The following is part of the configuration
```
  triggers:
    - type: datadog
      metricType: AverageValue
      authenticationRef:
        kind: ClusterTriggerAuthentication
        name: keda-trigger-auth
      metadata:
        query: sum:kubernetes.memory.usage{kube_service:myService} / sum:kubernetes.memory.limits{kube_service:omyService}
        queryValue: '75'
        age: '60'
        timeWindowOffset: '90'
```

For some reason when checking on `keda-hpa` scaled object I see a confusing value + `m`

```
currentMetrics:
    - external:
        current:
          averageValue: 794m
        metric:
          name: s0-datadog-sum-kubernetes-memory-usage
          selector:
            matchLabels:
              scaledobject.keda.sh/name: myService
      type: External
```

Could you advise what might be wrong here?
