### DISCUSSION TITLE
using PROMQL with GCP STACKDRIVER

### DISCUSSION THREAD

**Discussion by polo871209** [kedacore/keda#6439] [Q&A / Need Help] [answered]
Hi community, 

I am able to run the example query in gcp metric explorer with PROMQL

```
sum(
  rabbitmq_queue_messages{vhost="example", queue!~"^(celeryev\\..*|.*\\.pidbox)$"}
  + rabbitmq_queue_messages_unacked{vhost="example", queue!~"^(celeryev\\..*|.*\\.pidbox)$"}
)
/ 
sum(
  rabbitmq_queue_consumers{vhost="example", queue="celery"}
)
```

I want to add this promql to scaler object like this

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-worker
  minReplicaCount: 1
  maxReplicaCount: 30
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 180
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "75"
    - type: memory
      metadata:
        type: Utilization
        value: "70"
    - type: gcp-stackdriver
      authenticationRef:
        name: keda-trigger-auth-gcp-credentials
      metadata:
        projectId: xxx
        metricName: "queue_pressure"
        filter: |
          sum(
            rabbitmq_queue_messages{vhost="example", queue!~"^(celeryev\\..*|.*\\.pidbox)$"}
            + rabbitmq_queue_messages_unacked{vhost="example", queue!~"^(celeryev\\..*|.*\\.pidbox)$"}
          )
          /
          sum(
            rabbitmq_queue_consumers{vhost="example", queue="celery"}
          )
        targetValue: "3500"
        alignmentPeriod: "60s"
        queryWindow: "5m"
```

But I got the following error:

```txt
Warning  KEDAScalerFailed    32m (x2 over 32m)  keda-operator  rpc error: code = InvalidArgument desc = Field filter had an invalid value of "sum(
skip the flowing line...
```

How can i construct such PROMQL with GCP metrics? or it's not possible now?
