### DISCUSSION TITLE
Use of ClusterTriggerAuthentication with datadog cluster agent proxy

### DISCUSSION THREAD

**Discussion by ademar59** [kedacore/keda#6444] [Q&A / Need Help]
Hi

We currently use Datadog Api call with keda and have sometimes connections issues that provide fallback settings and useless scale up.
We are trying to use cluster agent as proxy https://arapulido.github.io/blog/2024/08/19/keda-cluster-agent/.

Datadog and Keda are deployed in the same namespace,  applications in others.
I try to use a ClusterTriggerAuthentication (not documented for cluster agent) as we use for Datadog API.

The goals is to set a clustertriggerauth with a secret in keda namespace.

And create datadogmetric and scaledobject in application namespaces (depended on application need).

But when i deployed my scaledobject i have this error:
_**error parsing Datadog metadata: no datadogNamespace key given**_

this error comes from clustertriggerauth and secret

is clustertriggerauth supported ?

**Comment by nirgilboa** [comment]
Yes, in my experience `ClusterTriggerAuthentication` is supported and configured similarly to `TriggerAuthentication`
The `datadogNamespace` is expected on the `ClusterTriggerAuthentication` resource, and points to a value in a `Secret`

**Comment by MrMarkW** [comment]
I was able to get ClusterTriggerAuthentication to work.

I had to deploy these resources (assuming namespace: keda)

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-metrics
  namespace: keda

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-metrics-reader
rules:
  - apiGroups:
      - external.metrics.k8s.io
    resources:
      - "*"
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-metrics-reader
subjects:
  - kind: ServiceAccount
    name: external-metrics
    namespace: keda
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-config
  namespace: keda
data:
  datadogNamespace: datadog
  datadogMetricsService: datadog-cluster-agent-metrics-server
  unsafeSsl: "true"
  authMode: bearer

---
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: datadog-cluster-agent
spec:
  boundServiceAccountToken:
    - parameter: token
      serviceAccountName: external-metrics
  configMapTargetRef:
    - parameter: datadogNamespace
      name: datadog-config
      key: datadogNamespace
    - parameter: unsafeSsl
      name: datadog-config
      key: unsafeSsl
    - parameter: authMode
      name: datadog-config
      key: authMode
    - parameter: datadogMetricsService
      name: datadog-config
      key: datadogMetricsService
```

Then updated my Keda helm chart config

```
permissions:
  operator:
    restrict:
      # allows boundServiceAccountToken for keda namespace to be used in ClusterTriggerAuthentication
      serviceAccountTokenCreationRoles:
        - name: external-metrics
          namespace: keda
```

Example Scaledobject used with it:

```
--- 
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMetric
metadata:
  name: nginx-ingress-requests
  namespace: ingress-nginx
spec:
  query: max:nginx_ingress.nginx.requests.total{kube_namespace:ingress, clustername:my-cluster, kube_service:ingress-nginx-controller}

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  scaleTargetRef:
    name: ingress-nginx-controller
  pollingInterval: 15
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 8
  triggers:
    - type: datadog
      metricType: Value
      metadata:
        useClusterAgentProxy: "true"
        datadogMetricName: "nginx-ingress-requests"
        datadogMetricNamespace: "ingress-nginx"
        targetValue: "20"
      authenticationRef:
        name: datadog-cluster-agent
        kind: ClusterTriggerAuthentication
      useCachedMetrics: true
    - metadata:
        value: "100"
      metricType: Utilization
      type: cpu
    - metadata:
        value: "45"
      metricType: Utilization
      type: memory
```
