### DISCUSSION TITLE
Elasticsearch scaler issue - IRSA Auth

### DISCUSSION THREAD

**Discussion by lalbinati** [kedacore/keda#6535] [Q&A / Need Help] [answered]
Hi,

I am currently exploring the possibility of using keda to escalate based on an opensearch query.
I've read the documentation and I believe I'm doing things right but I think I might've hit a wall.

Main blocker right now is that I am not using plain auth, I'm trying to use IRSA to authenticate the OS query and its not working, or the elasticsearch scaler does not support it.

I have a working microservice which uses IRSA to access the opensearch domain, that part works fine.

Here's what I tried.
- I added keda-operator service acct in the trust relationship of the role used with IRSA.
- I've defined a TriggerAuthentication object with this content:
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: irsa-test
  namespace: default
spec:
  podIdentity:
    provider: aws
    identityOwner: workload
``` 

- Finally, I added a new trigger to an existing ScaledObject for the mentioned microservice, and I'm referencing the TriggerAuth name using authenticationRef.name.

I'm getting this error:
2025-02-07T20:29:19Z    ERROR   scale_handler   error resolving auth params     {"type": "ScaledObject", "namespace": "default", "name": "xxxx-xxxx", "triggerIndex": 2, "error": "error parsing elasticsearch metadata: both username and password must be provided when addresses is used"}

Am I missing something or elasticsearch scaler does not support this yet?

Regards,
Luis
