### DISCUSSION TITLE
Grace period between trigger and scaling to 0

### DISCUSSION THREAD

**Discussion by blenzi** [kedacore/keda#6557] [General]
Hello, I am using a GPU to process typically few minute jobs that are triggered asynchronously (using redis). The pod takes several minutes to initialize and at the same time is expensive to keep idle for too long. So I would like to launch the pod when a new job arrives and, after the end of the processing, wait 30 minutes before scaling it down to 0, in case a new job arrives in between. Is there a mechanism to set this "grace period" (the cooldown period does not seem to do the job as the pod is killed and relaunched if a new trigger arrives)

**Comment by rickbrouwer** [comment]
Yes, there is. It's called `stabilizationWindowSeconds`.

For example:
```
spec:
  scaleTargetRef:
    name: my-deployment
  pollingInterval: 30
  cooldownPeriod: 30
  minReplicaCount:  0
  maxReplicaCount: 7
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 1800
```

More info: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#stabilization-window
