### DISCUSSION TITLE
MongoDB does not trigger scaling

### DISCUSSION THREAD

**Discussion by dmitrizzle** [kedacore/keda#6621] [Q&A / Need Help] [answered]
I've set up KEDA `2.16.1` on my Digital Ocean managed k8s `1.32.1-do.0`. This is the status that I get when I check `scaledobject`: 

![Screenshot 2025-03-13 at 10 40 08 AM](https://github.com/user-attachments/assets/684e6597-9849-49fb-b2f1-7569cd5ac222)

There appears to be no obvious issues in logs (happy to share more) but scaling isn't working.

Here's the YAML I used for `scaledobject`:

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mongodb-job
spec:
  scaleTargetRef:
    name: film-q-deployment
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
    - type: mongodb
      metadata:
        connectionStringFromEnv: DATABASE_URI
        dbName: "app-db"
        collection: "job-queue"
        query: '{ "status": "waiting" }'
        queryValue: "1"
      authenticationRef:
        name: mongodb-trigger
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mongodb-trigger
spec:
  secretTargetRef:
    - parameter: connectionString
      name: env-secrets
      key: DATABASE_URI
```
Note that I'm using `sealed-secrets` to store my MongoDB (Atlas) connection string.

Not sure where I should look next to fix this. Can anyone advise?

**Comment by dmitrizzle** [comment, marked as answer]
I think I figured this out and I'd like to share what I learned.

My confusion was with the `queueValue`. My objective was to start scaling when the `{ "status": "waiting" }` query in MongoDB returned one or more documents. However, it appears that KEDA looks at this value and starts scaling after the number of returned documents is greater than `queueValue` (which, in this case, means 2 or greater). Also, unfortunately, setting `queryValue` to 0 does not work either, presumably because of how this value is used in calculations.

I'm new to k8s and KEDA so missing the above context made the job confusing. Eventually, I came across a solution that involves using `scalingModifiers` to achieve what I wanted:

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  ...
spec:
  ...
+  advanced:
+    scalingModifiers:
+      formula: "(waitroom + 1)" # Modifies computed scaled value by adding +1
+      target: "1" # The final computed value matches 1 per replica
  triggers:
    - type: mongodb
+      name: waitroom
      metadata:
        connectionStringFromEnv: DATABASE_URI
        ...
        query: '{ "status": "waiting" }'
        queryValue: "1"
      authenticationRef:
        name: mongodb-trigger
```
