### DISCUSSION TITLE
error: admission webhook "vscaledobject.kb.io" denied the request

### DISCUSSION THREAD

**Discussion by davidshen84** [kedacore/keda#6717] [Q&A / Need Help] [answered]
Hi,

I have a ScaledObject which worked in v2.16.1.

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
    validations.keda.sh/hpa-ownership: "true"
  finalizers:
  - finalizer.keda.sh
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
    scaledobject.keda.sh/name: test
  name: test
  namespace: test
spec:
  cooldownPeriod: 300
  fallback:
    behavior: static
    failureThreshold: 3
    replicas: 1
  idleReplicaCount: 0
  maxReplicaCount: 1
  minReplicaCount: 1
  pollingInterval: 480
  scaleTargetRef:
    name: test
  triggers:
  - authenticationRef:
      name: cred
    metadata:
      subscriptionName: test
      value: "10"
      valueIfNull: "0"
    type: gcp-pubsub
```

But after upgrading to keda v2.17, I got an Admission Webhook error like the following:

```
admission webhook "vscaledobject.kb.io" denied the request: at least one trigger (that is not cpu or memory) has to have the `AverageValue` type for the fallback to be enabled
```

I checked the Fallback section between [v2.16](https://keda.sh/docs/2.16/reference/scaledobject-spec/#fallback) and [v2.17](https://keda.sh/docs/2.17/reference/scaledobject-spec/#fallback), and they look the same, except the *behavior* part.

I also check the gpc-pub-sub trigger, https://keda.sh/docs/2.17/scalers/gcp-pub-sub/, and I could not find an *AverageValue* related metric.
