### DISCUSSION TITLE
Keda multi triggers

### DISCUSSION THREAD

**Discussion by alexandreMegel** [kedacore/keda#6788] [Q&A / Need Help]
Hi!

To give you some context, I have a Java spring application that is deployed in our kubernetes cluster to run jobs. I'd like to use Keda so that the application is up only when there are jobs to run.

Here's my KEDA configuration:

````
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaledobject-jobserver
  namespace: jump-recette
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jump-recette-jobserver
  idleReplicaCount: 0
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  pollingInterval: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: jump-recette-kafka-controller-headless.jump-recette.svc.cluster.local:9092
      consumerGroup: worker
      topic: workern
      offsetResetPolicy: 'earliest'
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-monitoring-prometheus.monitoring.svc.cluster.local:9090/
      query: "max_over_time(spring_batch_job_active_seconds_active_count{container='jobserver', namespace='jump-recette'}[10m])"
      activationThreshold: "1"
      threshold: "1"
      ignoreNullValues: "true"
````

What I'd like to have: the spring server starts when there's a message in my Kafka queue, and the server shuts down once the server job has no more jobs to run. The server starts up fine, but the problem I'm having is that the server shuts down every time after 10 minutes. It looks like Keda isn't taking my Prometheus trigger into account (it just checks if there are any jobs running). Do you have any idea what's wrong with my Keda configuration? Thank you!

**Comment by rickbrouwer** [comment]
Hi!

In the created HorizontalPodAutoscaler yaml.
What value do you see in the `status` by `averageValue`?

Example:

```
status:
  lastScaleTime: '2025-05-20T06:06:53Z'
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
    - type: External
      external:
        metric:
          name: s0-prometheus
          selector:
            matchLabels:
              scaledobject.keda.sh/name: deployment
        current:
          averageValue: 576117m
```

**Reply by alexandreMegel** [reply]
Here's the HorizontalPodAutoscaler  yaml when I launch a job:

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/managed-by: keda-operator
    app.kubernetes.io/name: keda-hpa-scaledobject-jobserver
    app.kubernetes.io/part-of: scaledobject-jobserver
    app.kubernetes.io/version: 2.17.0
    scaledobject.keda.sh/name: scaledobject-jobserver
  name: keda-hpa-scaledobject-jobserver
  namespace: jump-recette
  ownerReferences:
  - apiVersion: keda.sh/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ScaledObject
    name: scaledobject-jobserver
    uid: 998cc8ba-b39b-429b-8a30-f26ad53d4a8b
spec:
  maxReplicas: 1
  metrics:
  - external:
      metric:
        name: s0-kafka-workern
        selector:
          matchLabels:
            scaledobject.keda.sh/name: scaledobject-jobserver
      target:
        averageValue: "10"
        type: AverageValue
    type: External
  - external:
      metric:
        name: s1-prometheus
        selector:
          matchLabels:
            scaledobject.keda.sh/name: scaledobject-jobserver
      target:
        averageValue: "1"
        type: AverageValue
    type: External
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jump-recette-jobserver
status:
  conditions:
  - lastTransitionTime: "2025-05-19T12:10:40Z"
    message: recent recommendations were higher than current one, applying the highest
      recent recommendation
    reason: ScaleDownStabilized
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2025-05-20T07:15:05Z"
    message: 'the HPA was able to successfully calculate a replica count from external
      metric s1-prometheus(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:
      scaledobject-jobserver,},MatchExpressions:[]LabelSelectorRequirement{},})'
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2025-05-19T12:59:45Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentMetrics:
  - external:
      current:
        averageValue: "0"
      metric:
        name: s0-kafka-workern
        selector:
          matchLabels:
            scaledobject.keda.sh/name: scaledobject-jobserver
    type: External
  - external:
      current:
        averageValue: "1"
      metric:
        name: s1-prometheus
        selector:
          matchLabels:
            scaledobject.keda.sh/name: scaledobject-jobserver
    type: External
  currentReplicas: 1
  desiredReplicas: 1
```

And then the yaml just after the job server scales to 0 after 10 minutes even a job was currently running

```
status:
  conditions:
  - lastTransitionTime: "2025-05-19T12:10:40Z"
    message: the HPA controller was able to get the target's current scale
    reason: SucceededGetScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2025-05-20T07:26:51Z"
    message: scaling is disabled since the replica count of the target is zero
    reason: ScalingDisabled
    status: "False"
    type: ScalingActive
  - lastTransitionTime: "2025-05-19T12:59:45Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentMetrics: null
  desiredReplicas: 0
```
