### DISCUSSION TITLE
KEDA External Scaling scale up with multiple policies

### DISCUSSION THREAD

**Discussion by markodjunev** [kedacore/keda#6804] [Ideas]
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scaledobject
  namespace: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicaCount: 5
  maxReplicaCount: 50
  pollingInterval: 15
  cooldownPeriod: 300
  fallback:
    failureThreshold: 3
    replicas: 5
  advanced:
    horizontalPodAutoscalerConfig:
      name: nginx-hpa
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 600
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 60
          policies:
            - type: Pods
              value: 5
              periodSeconds: 60
            - type: Pods
              value: 1
              periodSeconds: 12
          selectPolicy: Max
  triggers:
    - type: memory
      metricType: Utilization
      metadata:
        value: "85"
    - type: external
      metadata:
        scalerAddress: externalservice.test.svc.cluster.local:6001
        small: "5"
        medium: "10"
        large: "25"
```
        
        
We have the following issue, the external scaler triggers **large** metric and our nginx should have 25 replicas. However we stuck at 21 replicas and we cannot reach 25 replicas. I think that's because of our policy which is increasing 5 pods per 1 minute and 21 + 5 > 25 so we don't execute trigger. For this reason I added second policy:

```
        - type: Pods
          value: 1
          periodSeconds: 12
```
          
Now again we have the same issue because the **selectPolicy** can be **Max**, **Min** or **Disabled**. I want to scale up 5 pods per minute and if it's not possible to scale up 1 pod per 12 seconds. Do you know if this can happen? If it's not possible, I think it is a good idea for a feature request.

It's very important for us if the have 21, 24 or 25 replicas on this metric.
