### DISCUSSION TITLE
What's the effect of metricType on generated HPA

### DISCUSSION THREAD

**Discussion by sirish-bajpai** [kedacore/keda#6830] [Q&A / Need Help]
I am trying to scale on a prometheus query:

`sum(jvm_memory_commited_bytes{jvm_memory_type="heap"})/sum(jvm_memory_limit_bytes{jvm_memory_type="heap"})`

Basically if the total heap committed by an app increases above a ratio over total heap available for the app, scaling up should occur.
I was expecting the hpa to scale on this metric as is. But it takes the average value by dividing this scaler with number of pods.
Setting the metricType = "Value" seem to have no effect. HPA insists on averaging with pod count.
I would like to understand what effect setting the metricType has on hpa?
How can I modify the query or the scaledobject config to get the intended effect?

**Comment by haiyang-dev** [comment]
Hi @sirish-bajpai ，

You can reference my config,
```
triggers:
    - type: Prometheus
      metricType: Value
      metadata:
        serverAddress: http://prometheus-service.ets-intraday-qe.svc.cluster.local:9091
        metricName: container_cpu_usage_seconds_total
        threshold: "75"
        query: <PromQL>
```


please note the metricType is same level as metadata, I put it in metadata before, so it doesn't work.
