### DISCUSSION TITLE
Unable to create resource scaledobjects on a namespace

### DISCUSSION THREAD

**Discussion by wamak9** [kedacore/keda#862] [General] [answered]
Hi, After deploying keda with the default values provided under the /deploy 
I tried to deploy a helm chart with below yaml, 
I keep getting 
`
Error: release autoscalingdemo failed: scaledobjects.keda.k8s.io is forbidden: User "system:serviceaccount:svfb:tiller" cannot create resource "scaledobjects" in API group "keda.k8s.io" in the namespace "svfb"
`

I have tiller installed with helm version 2.11.
Also havent made any changes to role definitions
Let me know if you need additional information ?
Not sure if this should go under issue or discussion ?

scaledobjects yaml file : 

```yaml
{{- if .Values.metricautoscaling.enabled }}
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {{ template "application.name" . }}-kedascaler
  labels:
    app: {{ template "application.name" . }}
    deploymentName: {{ template "application.name" . }}
spec:
  scaleTargetRef:
    deploymentName: {{ template "application.name" . }}
  pollingInterval: 15  # Optional. Default: 30 seconds
  cooldownPeriod:  30 # Optional. Default: 300 seconds
  minReplicaCount: {{ .Values.replicaCount }}   # Optional. Default: 0
  maxReplicaCount: {{ .Values.metricautoscaling.maxReplicaCount }} # Optional. Default: 100
  triggers:
  - type: {{ .Values.metricautoscaling.type }}
    metadata:
      # Required
      serverAddress: {{ .Values.metricautoscaling.serverAddress }}
      metricName: {{ .Values.metricautoscaling.metricName }}
      threshold: {{ .Values.metricautoscaling.threshold }}
      query: {{ .Values.metricautoscaling.query }}
{{- end }}
```
