### DISCUSSION TITLE
Is there way to make a custom scalar?

### DISCUSSION THREAD

**Discussion by divyanshu16** [kedacore/keda#869] [General]
I want to trigger hpa when the number of documents counts in mongo collection is over the threshold but I could not find relevant scalar [here](https://keda.sh/docs/1.4/scalers/) for mongo.

Is there a way to include an external service endpoint which can be used to trigger the hpa.

triggers in helm yaml for `ScaledObject` could look like this roughly
```
triggers:
    - type: custom
      metadata:
        serverAddress: http://<mongo-server-ip>:<port>/counts
        threshold: 10
```
