### DISCUSSION TITLE
Kafka Scaler Issue

### DISCUSSION THREAD

**Discussion by shashiik** [kedacore/keda#875] [Q&A / Need Help] [answered]
Hi,

I am running into an issue with the Kafka scaler. I am setting the `lagThreshold` to 1000. I am pushing one message to the Kafka topic, and my Kubernetes deployment is scaling up from 0 to 1 replica.

I might be mistaken, but I assumed the `lagThreshold` field was the minimum number of messages in a Kafka topic needed before scaling the deployment to 1 replica. Is this a correct assumption?

If not, is there a way to trigger the replica scaling from 0 -> 1 only after reaching a _minimum_ threshold of Kafka messages in the topic?

Thanks!

**Comment by tomkerkhove** [comment, marked as answer]
It should only scale when there are 1000 messages indeed but I think it's scaling to 1 because there was no work to process. If there is a constant of <1000 messages only one instance will be around but when it goes > 1000 it will do 1->n scaling.

We scale to 0 to save resources if there is no work to process but as soon as there is one message we'll help you process that and go back to 0.

**Reply by shashiik** [reply]
@tomkerkhove 

Thanks for the explanation. My understanding of `lagThreshold` was not correct then. My goal is to reduce memory/cpu resources from idling/under-utilized deployments by only triggering 0->1 when certain # of messages are ready to process.

As a workaround I have created a new field `minimumThreshold`, which will be the minimum number of messages in a topic before scaling the deployment from 0 -> 1.

```
triggers:
    - type: kafka
      metadata:
        bootstrapServers: <kafka-servers>
        consumerGroup: *consumer-group*
        topic: *topic*
        lagThreshold: '1000'
        minimumThreshold: '1000' // New field
```

In the `IsActive` method in `kafka_scaler.go`, I am summing the total # of messages across all partitions, and if that value is greater than `minimumThreshold`, only then return true from IsActive. This solutions is working perfectly for my needs.

If others would find something like this useful for their applications, I can create a pull request with these changes.
