### DISCUSSION TITLE
SQS scaler not finding trigger authentication credentials

### DISCUSSION THREAD

**Discussion by Woody1193** [kedacore/keda#876] [Q&A / Need Help]
I have a Keda deployment that I've been trying to get to work for about a month now. At the moment, my scaler looks like this:

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {service-name}-scaler
spec:
  scaleTargetRef:
    deploymentName: {service-name}
    containerName: {service-name}
  pollingInterval: 30
  cooldownPeriod:  600
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-authentication
    metadata:
      queueURL: https://sqs.ap-northeast-1.amazonaws.com/{AWS ID}/{Queue-name}
      queueLength: "1"
      awsRegion: "ap-northeast-1"
      identityOwner: pod
```

The associated trigger authentication and secret are:

```
apiVersion: v1
kind: Secret
metadata:
  name: keda-secrets
data:
  AWS_ACCESS_KEY_ID: {base64-encoded-string}
  AWS_SECRET_ACCESS_KEY: {base64-encoded-string}
  KEDA_ROLE_ARN: {base64-encoded-string}

---

apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-authentication
spec:
  env:
  - parameter: awsRegion
    name: AWS_REGION
  - parameter: awsAccessKeyID
    name: AWS_ACCESS_KEY_ID
  - parameter: awsSecretAccessKey
    name: AWS_SECRET_ACCESS_KEY
  - parameter: awsRoleArn
    name: KEDA_ROLE_ARN
  secretTargetRef:
  - parameter: awsRoleArn
    name: keda-secrets
    key: KEDA_ROLE_ARN
```

I understand that the `KEDA_ROLE_ARN` value is repeated here; I left both for debugging purposes. The order of deploying this is as follows:
1. Install common environment variables (this is where the `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `KEDA_ROLE_ARN` values are stored. The `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` values are listed as `AWS_ACCESS_KEY_ID_ASSUME` and `AWS_SECRET_ACCESS_KEY_ASSUME` respectively in the file and will assume their appropriate values on the container. Again, these are duplicated for debugging purposes. I would prefer to use these values rather than a separate secret.
2. Install Keda pods with Helm
3. Deploy the `keda-secrets` secret and the `keda-trigger-authentication` trigger authentication
4. Deploy the container that should be scaled. This is where the `AWS_ACCESS_KEY_ID_ASSUME` value will assume the name of `AWS_ACCESS_KEY_ID` and the `AWS_SECRET_ACCESS_KEY_ASSUME` value will assume the name of `AWS_SECRET_ACCESS_KEY` and where the `AWS_REGION` value is defined.
5. The scaled object is deployed

For some reason, I keep getting an error from AWS when the scaler attempts to scale saying that there are no credential providers in the chain. It appears that the AWS credentials are not being sent. What am I doing wrong here?
