### ISSUE TITLE
aws_cloudwatch_scaler - http invalid header field value

### ISSUE THREAD

**Issue by cachila** [kedacore/keda#1067]
Hello, after deploying the autoscaler based on aws-cloudwatch sqs number of messages, the TARGET column on `kubectl get hpa` shows `<unknown>/3` and no deployment scales. 

On the keda-operator log this error is shown so I guess it's something related to that:
`{"level":"error","ts":1598467409.1905313,"logger":"aws_cloudwatch_scaler","msg":"Failed to get output","error":"RequestError: send request failed\ncaused by: Post \"https://monitoring.us-east-1.amazonaws.com/\": net/http: invalid header field value \"AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXXXXX/20200826/us-east-1/monitoring/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=XXXXXXXXXXXXXXXXXXXXX\" for key Authorization","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/zroubali/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/kedacore/keda/pkg/scalers.(*awsCloudwatchScaler).GetCloudwatchMetrics\n\tkeda/pkg/scalers/aws_cloudwatch_scaler.go:249\ngithub.com/kedacore/keda/pkg/scalers.(*awsCloudwatchScaler).IsActive\n\tkeda/pkg/scalers/aws_cloudwatch_scaler.go:185\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).handleScaleDeployment\n\tkeda/pkg/handler/scale_loop.go:119\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).handleScale\n\tkeda/pkg/handler/scale_loop.go:45\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).HandleScaleLoop\n\tkeda/pkg/handler/scale_loop.go:28"}`

## Expected Behavior
Deployment scales and `kubectl get hpa` shows correct info.

## Actual Behavior
`kubectl get hpa` shows `<unknown>/3` and no deployment scales.

## Steps to Reproduce the Problem

Here is my configuration file:

```
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
data:
  AWS_ACCESS_KEY_ID: XXXXXXXXXXXXXX
  AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXXXXXX
---
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID     # Required.
    name: aws-secrets        # Required.
    key: AWS_ACCESS_KEY_ID        # Required.
  - parameter: awsSecretAccessKey # Required.
    name: aws-secrets        # Required.
    key: AWS_SECRET_ACCESS_KEY    # Required.
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: worker-sqs-queue-scaledobject
  labels:
    tier: api
spec:
  scaleTargetRef:
    deploymentName: worker
  triggers:
  - type: aws-cloudwatch
    metadata:
      namespace: AWS/SQS
      dimensionName: QueueName
      dimensionValue: staging-queue
      metricName: ApproximateNumberOfMessagesVisible
      targetMetricValue: "3"
      minMetricValue: "0"
      awsRegion: "us-east-1"
    authenticationRef:
      name: keda-trigger-auth-aws-credentials

```
## Specifications

  - **KEDA Version:**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"1da71a35d52fa82847fd61c3db20c4f95d283977", GitTreeState:"clean", BuildDate:"2020-07-15T21:59:26Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
  - **Platform & Version:**
Azure Kubernetes Services
  - **Kubernetes Version:** 
1.16.13
  - **Scaler(s):**
AWS CloudWatch

**Comment by engyishere** [comment]
Same issue here.

Installed everything yesterday with helm. 

`{"level":"error","ts":1599157802.9904482,"logger":"aws_cloudwatch_scaler","msg":"Failed to get output","error":"RequestError: send request failed\ncaused by: Post \"https://monitoring.us-east-1.amazonaws.com/\": net/http: invalid header field value \"AWS4-HMAC-SHA256 Credential=\\xxx\\xxx\\xxxx]\\xxx\\xxx\\xxxxx\\xxxxx/xxxxx/xxxxx/monitoring/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\" for key Authorization","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/zroubali/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/kedacore/keda/pkg/scalers.(*awsCloudwatchScaler).GetCloudwatchMetrics\n\tkeda/pkg/scalers/aws_cloudwatch_scaler.go:249\ngithub.com/kedacore/keda/pkg/scalers.(*awsCloudwatchScaler).IsActive\n\tkeda/pkg/scalers/aws_cloudwatch_scaler.go:185\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandle`

**Comment by cachila** [comment]
@engyishere I had to deploy ScaledObject with
```
  triggers:
  - type: aws-cloudwatch
    metadata:
      namespace: AWS/SQS
      dimensionName: QueueName
      dimensionValue: staging-queue
      metricName: ApproximateNumberOfMessagesVisible
      metricStat: Maximum
      metricStatPeriod: "30"
      targetMetricValue: "200"
      minMetricValue: "1"
      awsRegion: "us-east-1"
      awsAccessKeyID: AWS_ACCESS_KEY_ID
      awsSecretAccessKey: AWS_SECRET_ACCESS_KEY
```
These **AWS_ACCESS_KEY_ID** and **AWS_SECRET_ACCESS_KEY** are the env variable names on the scaleTargetRef.deploymentName deployment. For example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
...
...
        env:
        - name: AWS_ACCESS_KEY_ID
          value: XXXXXXXXXXXXXXXX
        - name: AWS_SECRET_ACCESS_KEY
          value: XXXXXXXXXXXXXX
```

Hope this helps

**Comment by engyishere** [comment]
@cachila  Thanks for taking time to get back to me. Are you using v2  for deployment of keda or 1.5.0.


This is the changes i have made and i am currently using v2  to test the new release if that resolves the issue. if possible send the files please. 

`apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-cloudwatch-queue-scaledobject
  namespace: default
  labels:
    app: engy-worker-edo
spec:
  scaleTargetRef:
    name: engy-worker-edo
    deploymentName: engy-worker-edo
  pollingInterval: 10
  cooldownPeriod: 300
  minReplicaCount: 3
  maxReplicaCount: 8  
  triggers:
  - type: aws-cloudwatch
    metadata:
      namespace: AWS/SQS
      dimensionName: QueueName
      dimensionValue: keda
      metricName: ApproximateNumberOfMessagesVisible
      targetMetricValue: "20"
      minMetricValue: "0"
      awsRegion: "us-east-1"
      awsAccessKeyID: AWS_ACCESS_KEY_ID
      awsSecretAccessKey: AWS_SECRET_ACCESS_KEY      
    authenticationRef:
      name: keda-trigger-auth-aws-credentials`

**Comment by engyishere** [comment]
forgot to mention that AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY  are defined as env variables in deployment .

**Comment by cachila** [comment]
This is the ScaledObject file. Is this what you want me to share?

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaled-object
  labels:
    deploymentName: php-deployment
spec:
  scaleTargetRef:
    deploymentName: worker # must be in the same namespace as the ScaledObject
  pollingInterval: 30 
  cooldownPeriod: 90
  minReplicaCount: 1
  maxReplicaCount: 100
  triggers:
  - type: aws-cloudwatch
    metadata:
      namespace: AWS/SQS
      dimensionName: QueueName
      dimensionValue: staging-queue
      metricName: ApproximateNumberOfMessagesVisible
      metricStat: Maximum
      metricStatPeriod: "30"
      targetMetricValue: "200"
      minMetricValue: "1"
      awsRegion: "us-east-1"
      awsAccessKeyID: AWS_ACCESS_KEY_ID
      awsSecretAccessKey: AWS_SECRET_ACCESS_KEY

```

**Comment by mavenishere** [comment]
Not working for me. Here's what i am doing.


- helm to install keda.
- Created a secret to store AWS Creds.
- Created a deployment with env 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehush-worker-edo
  labels:
    app: ehush
spec:
  selector:
    matchLabels:
      app: ehush
  template:
    metadata:
      labels:
        app: ehush
    spec:
      containers:
      - name: ehush
        image: nginx:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: keda-aws-secrets
              key: AWS_ACCESS_KEY_ID        
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: keda-aws-secrets
              key: AWS_SECRET_ACCESS_KEY          
```

- Created ScaledObject , no trigger authentication. scaledobject file as you have provided.
```
keda-hpa-ehush-worker-edo   Deployment/ehush-worker-edo   <unknown>/20 (avg)   1         10        1          11m
```

HPA creates the minimum required pod but there is not scaling whatsoever. In keda operator logs, no mention of  polling Cloudwatch metrics.

Is there something i am missing? Does your setup work properly with cloudwatch metrics?

**Comment by mavenishere** [comment]
Update: Trigger for AWS SQS working just fine but for Cloudwatch still an issue.

If possible, please attach all files for me to compare. maybe i am still missing something.

**Comment by cachila** [comment]
I'm not using a Secret, just the file I posted previously and a Deployment pretty much like yours but env values directly there like I posted before.

If AWS SQS is working, I have no clue why Cloudwatch is not.

**Comment by XavierGeerinck** [comment]
SQS is not working here neither for me :( same issue, deployed as shown and it posts ` Post \"https://sqs.eu-west-1.amazonaws.com/\": net/http: invalid header field value \"AWS4-HMAC-SHA256 Credential`

**Comment by zroubalik** [comment]
@XavierGeerinck is this something that was fixed by #1332 and we can close this one?

**Comment by XavierGeerinck** [comment]
@zroubalik no this is unrelated sadly enough. SQS doesn't work at all for me, the bug fix I did was something I just found... when utilizing the SQS scaler the error as shown in my previous comment shows up.

**Comment by oleksdiam** [comment]
@XavierGeerinck I've got the same errors. There was a mistake with encoding of secrets: the trailed '\n' has been included in the hashed value.
Everything has become well when I hashed values correctly:
`echo -n 'AKIASOMEAWSACCESSKEID'  | base64`

**Comment by ahmelsayed** [comment]
I'm unable to repro this using the following 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
  namespace: keda-test
stringData:
  AWS_ACCESS_KEY_ID: <value>
  AWS_SECRET_ACCESS_KEY: <value>
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: keda-test
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID     # Required.
    name: test-secrets            # Required.
    key: AWS_ACCESS_KEY_ID        # Required.
  - parameter: awsSecretAccessKey # Required.
    name: test-secrets            # Required.
    key: AWS_SECRET_ACCESS_KEY    # Required.
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: keda-test
spec:
  scaleTargetRef:
    name: sqs-worker
  pollingInterval: 10
  cooldownPeriod: 20
  triggers:
  - type: aws-cloudwatch
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      namespace: AWS/SQS
      dimensionName: QueueName
      dimensionValue: ahmels-sqs-keda
      metricName: ApproximateNumberOfMessagesVisible
      metricStat: Maximum
      metricStatPeriod: "30"
      targetMetricValue: "200"
      minMetricValue: "1"
      awsRegion: "us-west-2"
      # remove authenticationRef if using this method. 
      # awsAccessKeyIDFromEnv: AWS_ACCESS_KEY_ID
      # awsSecretAccessKeyFromEnv: AWS_SECRET_ACCESS_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-worker
  namespace: keda-test
  labels:
    app: sqs-worker
spec:
  selector:
    matchLabels:
      app: sqs-worker
  template:
    metadata:
      labels:
        app: sqs-worker
    spec:
      containers:
      - name: sqs-worker
        image: docker.io/ahmelsayed/sqs:1
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: test-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: test-secrets
              key: AWS_SECRET_ACCESS_KEY
```

note that `awsAccessKeyID` and `awsSecretAccessKey` are now `awsAccessKeyIDFromEnv` and `awsSecretAccessKeyFromEnv`. See v2 breaking change here https://github.com/kedacore/keda/releases/tag/v2.0.0 

I'll close this issue based on that.
