### ISSUE TITLE
The TARGET result is not match with prometheus

### ISSUE THREAD

**Issue by helloworlde** [kedacore/keda#1134]
When I use prometheus as datasource, the hpa result looks different with prometheus result.

My config is :

```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: demo-api
  namespace: develop
spec:
  scaleTargetRef:
    deploymentName: demo-api
    namespace: develop
  pollingInterval: 5
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.local
        metricName: http_requests_per_min
        threshold: '10'
        query: sum(rate(http_server_requests_seconds_count{application="demo-api", dc="one"}[1m]))
```

## Actual Behavior

```bash
kubectl get hpa -n develop
NAME                REFERENCE             TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-demo-api   Deployment/demo-api   74100m/10 (avg)   1         10        10         7m27s
```

## Expected Behavior
Result should be about 744, not the 74100m, looks like not handle the result when has `.`

![image](https://user-images.githubusercontent.com/13172836/92697941-6db18200-f37e-11ea-8c6b-8ad7f4705198.png)

## Specifications

  - **KEDA Version:** *1.5.0*
  - **Platform & Version:** *CentOS 7*
  - **Kubernetes Version:** *1.16*
