### ISSUE TITLE
Service Bus Scaler fails with = in connection String

### ISSUE THREAD

**Issue by rangp** [kedacore/keda#1181]
I'm not sure about the root cause, but when setting up my scaler, I find the following error message in the log

`azure_servicebus_scaler	error	{"error": "failed parsing connection string due to unmatched key value separated by '='"}`

Upon investigating I found that my SharedAccessKey contains a "=" since it is base64 encoded by default. I suspect that this could be the problem, as I copied the connection string right from the azure portal and it works fine when connecting via ServiceBusExplorer

## Steps to Reproduce the Problem

My template for the ScaledObject

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.app.name }}-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: StatefulSet
    name: {{ .Values.app.name }}
  maxReplicaCount: 10
  minReplicaCount: 1
  triggers:
  - type: azure-servicebus
    metadata:
      topicName: my-topic
      subscriptionName: general-subscription
      connectionFromEnv: SERVICEBUS_CONNECT
      queueLength: "4000"
```

where SERVICEBUS_CONNECT looks like

`Endpoint=sb://my-bus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=somethingBase64WhichHasAPaddingOf=;EntityPath=my-topic`

## ExpectedBehaviour

I would expect the connection string to be valid, since it can be parsed by the service bus explorer and the c# SDK likewise. 

## Specifications

  - **KEDA Version:** *2.0.0 beta*
  - **Platform & Version:** *Azure Kubernetes Service*
  - **Kubernetes Version:** *1.17.9*
  - **Scaler(s):** *Azure Service Bus*
