### ISSUE TITLE
Avoid exception when CRD doesn't follow Pod spec shape

### ISSUE THREAD

**Issue by anggao** [kedacore/keda#1194]
## Expected Behavior
KEDA should be able to scale custom resources as long as the target CR defines /scale subresource

## Actual Behavior
For [SeldonDeployment CR ](https://github.com/SeldonIO/seldon-core/blob/master/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go) 

Got the following exception 

```
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90
2020-09-24T02:52:10.360Z        ERROR   controller      Reconciler error        {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "name": "agao-test-keda", "namespace": "default",
"error": "no containers found"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:237
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90
```

It seems there is a requirement for the shape the CR as well https://github.com/kedacore/keda/blob/v2/pkg/scaling/scale_handler.go#L349 ? 

## Steps to Reproduce the Problem

  1. Install KEDA
  2. Deploy a ScaledObject
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: agao-test-keda
spec:
  scaleTargetRef:
    apiVersion: machinelearning.seldon.io/v1
    kind: SeldonDeployment
    name: agao-test
  pollingInterval: 15                                # Optional. Default: 30 seconds
  cooldownPeriod:  30                               # Optional. Default: 300 seconds
  minReplicaCount: 0                                 # Optional. Default: 0
  maxReplicaCount: 100                               # Optional. Default: 100
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.istio-system.svc.cluster.local:9090
      metricName: access_frequency
      threshold: '3'
```
  3. View operator logs

## Specifications

  - **KEDA Version:** v2.0.0-beta
  - **Kubernetes Version:** v1.17.5
  - **Scaler(s):** Prometheus
