### ISSUE TITLE
ResolveContainerEnv does not consider interdependent environment variables

### ISSUE THREAD

**Issue by rangp** [kedacore/keda#1197]
This is a follow up of #1181 . Turns out my connection string cannot be parsed because I am setting it up using [interdependent environment variables](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/)

My setup looks like this:
    
```
      env:
        - name: SERVICEBUS_CONNECT_GENERAL
          valueFrom:
            secretKeyRef:
              name: service-bus
              key: connectionString
        - name: SERVICEBUS_CONNECT
          value: $(SERVICEBUS_CONNECT_GENERAL);EntityPath=my-topic
```

Which I use, since I have around 20 topics and do not want to maintain 20 different secrets, as the connection string is always the same. The concept is supported from a kubernetes point of view, but apparantly the function `ResolveContainerEnv `does not consider interdependent variables.

## Expected Behavior

The connection string is extracted from the environment like it is done in kubernetes

## Actual Behavior

the connection string is extracted as `$(SERVICEBUS_CONNECT_GENERAL);EntityPath=my-topic` and can thus cannot be parsed.

## Specifications

KEDA Version: 2.0.0 beta
Platform & Version: Azure Kubernetes Service
Kubernetes Version: 1.17.9
Scaler(s): Azure Service Bus
