### ISSUE TITLE
(error) WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by alash3al** [kedacore/keda#1243]
We have a redis-based queue (`zset` listType) in one of our apps and we consume from it very quickly, the case is
the code [here](https://github.com/kedacore/keda/blob/071d5a0732c547cf58199fab0772fcee5c9efc85/pkg/scalers/redis_scaler.go#L168) is trying to detect the type of key, when it returns none (redis returns none if the set is empty), then the code deals with it as `list`, so it executes `llen` on it, but between the detection and the `llen` there may be a new item get pushed into the zset, so the type is now `zset` and not none.

- I think the type of the list should be predefined in the configuration under the name `listType` i.e:

```yml
triggers:
- type: redis
  metadata:
    address: localhost:6379 # Required host:port format
    addressFromEnv: REDIS_HOST # Required host:port format
    passwordFromEnv: REDIS_PASSWORD
    listName: mylist # Required
    listType: zset ##### I think this will help
    listLength: "5" # Required
    enableTLS: "false" # optional
    databaseIndex: "0" # optional
```

- or we can convert the main purpose of the function into a lua script that is executed atomically in the redis server?

What do you think? Am I wrong?

sorry if there were any typo in the description
