### ISSUE TITLE
Provide support for Kustomize

### ISSUE THREAD

**Issue by kmr0877** [kedacore/keda#1278]
- Be able to customize yaml files without modifying the original yaml file. Kustomize helps achieve this with greater simplicity 
- Kustomize is extremely good at cases where helm can be real pain, few such scenarios can be found with detailed examples in [here](https://itnext.io/helm-is-not-enough-you-also-need-kustomize-82bae896816e)

**Comment by zroubalik** [comment]
Well we are using Kustomize currently, what exactly are you missing?

**Comment by charandas** [comment]
The deploy docs shares the helm path, the operator hub (openshift) path, and the one using a yaml manifests.

A kustomization offering is slightly different from offering a single yaml as it will contain a root kustomization alongside the individual kube resources. From that point of view, @kmr0877's ask seems legit here.

**Comment by tomkerkhove** [comment]
So it's more a documentation and release artifact ask then?

**Comment by charandas** [comment]
It's probably this one we are after: https://github.com/kedacore/keda/blob/main/config/default/kustomization.yaml

So it does look like kustomize is already in use, and this becomes merely a documentation task; the release artifact part being taken care of by git tags.

**Comment by tomkerkhove** [comment]
@zroubalik Can we automatically edit and attach this as a new artifact as well?

**Comment by zroubalik** [comment]
@tomkerkhove that artifact is basically a template that needs processing (setting versions and patches). Not sure what exactly @charandas would like to see. 

@charandas Could you please draft a PR with resources you'd like to see as part of our release?

**Comment by charandas** [comment]
@zroubalik it's very little customization on top of what you are offering, basically the tags which could be set using 'kustomize edit set image'.

Currently, I am having to refer to the tag twice like so:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The source kustomizations currently don't set the image correctly on release tags, and use `main` instead
resources:
  - https://github.com/kedacore/keda/config/default?ref=v2.2.0

images:
  - name: ghcr.io/kedacore/keda
    newTag: 2.2.0
  - name: ghcr.io/kedacore/keda-metrics-apiserver
    newTag: 2.2.0
```
