### ISSUE TITLE
Support metadata labels in ScaledJob template

### ISSUE THREAD

**Issue by mykola-ivadolabs** [kedacore/keda#1311]
in version 2.0 `metadata` portion of ScaledJob `template` is ignored so it is impossible to setup a label for job to be created

### Use-Case

To support managed identity in AKS, a label "aadpodidbinding" has to be added to the object that needs pods to be running under managed identity. 

To use ScaledJob to create pods that run under managed identity, ScaledJob should support `metadata` section when defining job template.

 

### Specification

Allow adding labels to pod template using `metadata` section

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {scaled-job-name}
spec:
  jobTargetRef:
    template:
       metadata:
          labels:
            aadpodidbinding: "myidentity"
      spec:
         ...
```

**Comment by julienperignon** [comment]
This was supported in version 1.5 through scaledobject. Not sure why this got removed in version 2 ...

**Comment by zroubalik** [comment]
ScaledObject is mirroing labels to the created HPA: 
https://github.com/kedacore/keda/blob/50bec808f8b4656922797e4bcb7c2b61fabd6d0e/controllers/hpa.go#L67-L69

Would this help you?

**Comment by julienperignon** [comment]
> `ScaledObject` is mirroing labels to the created `HPA`:
> https://github.com/kedacore/keda/blob/50bec808f8b4656922797e4bcb7c2b61fabd6d0e/controllers/hpa.go#L67-L69
> 
> Would similar solution for `ScaledJob` help you?
> 
> And as a temporary workaround you can disable proxy injection on the namespace.

Yeah something similar would work. I have 0 knowledge of Go unfortunately so not really able to submit a PR for this.

Unfortunately my jobs are in the same namespace s my microservices so cannot disable injection at the namespace level.

**Comment by Kesudan** [comment]
We have run into the same issue and having to go back to 1.5 as this is a show stopper for us, unless there is any other way of assigning labels for ScaledJob in 2.0?

**Comment by zroubalik** [comment]
Reopening, since the problem is not fully solved: https://github.com/kedacore/keda/pull/1322#issuecomment-736348450

**Comment by pplavetzki** [comment]
I've been testing this for a few hours and it seems that the metadata isn't being deserialized to the ScaledJob object.  When I submit a scaledjob like this:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: redis-sampler-7
spec:
  jobTargetRef:
    parallelism: 1                            
    completions: 1                            
    activeDeadlineSeconds: 1000                
    backoffLimit: 5                           # Specifies the number of retries before marking this job failed. Defaults to 6
    template:
      metadata:
        labels:
          name: "job-pod"
          work: "full"
        annotations:
          sidecar.istio.io/inject: "false"
          do.something.dot.com: "true"
      spec:
        containers:
        - name: redis-client
          image: redis-client:v0.0.1
          env:
          - name: REDIS_HOST
            value: "redis-svc"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_LIST
            value: "mylist"
  pollingInterval: 30                         # Optional. Default: 30 seconds
  successfulJobsHistoryLimit: 5               # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 5                   # Optional. Default: 100. How many failed jobs should be kept.
  maxReplicaCount: 100                        # Optional. Default: 100
  triggers:
  - type: redis
    metadata:
      address: redis-svc.keda-sample.svc.cluster.local:6379 # ormat must be host:port
      listName: mylist # Required
      listLength: "5" # Required
      enableTLS: "false" # optional
      databaseIndex: "0" # optional
```
The resulting `kubectl get scaledjob ...` returns

```
...
spec:
  failedJobsHistoryLimit: 5
  jobTargetRef:
    activeDeadlineSeconds: 1000
    backoffLimit: 5
    completions: 1
    parallelism: 1
    template:
      metadata: {}
      spec:
        containers:
        - env:
          - name: REDIS_HOST
            value: redis-svc
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_LIST
            value: mylist
          image: redis-client:v0.0.1
          name: redis-client
```
I've looked at the api and tried debugging through it but can't seem to find why the metadata isn't being deserialized correctly.  If someone points me to the correct location I can try to fix and create the PR.

Cheers!
