### ISSUE TITLE
RabbitMQ - Unacked Messages

### ISSUE THREAD

**Issue by XavierGeerinck** [kedacore/keda#1325]
I am currently seeing that unacknowledged messages are not being seen by the KEDA RabbitMQ scaler, disallowing the Deployment to scale out towards more pods.

My testing flow goes like this:

1. Create Kubernetes Deployment
2. Deploy KEDA ScaledObject config
3. Expose port `3500` (DAPR RabbitMQ Binding specific)
4. Post a message through HTTP and 3500 on RabbitMQ

All of the above works and I see the messages appearing, the queue filling up and the Pod starting to process the messages! Just the KEDA part of out-scaling is not working here which I think might be due to the unacked messages

I am also tagging @yaron2 because I'd love to check if this is a Dapr related issue that should actually acknowledge the message if it's sent through the input binding?

## Expected Behavior

When running KEDA with RabbitMQ Scaler, I would expect to see an out-scale happen from as soon as the `queueLength` threshold is met

## Actual Behavior

Nothing

## Steps to Reproduce the Problem

  1. Create KEDA RabbitMQ deployment with AMQP endpoint
  2. Publish messages through [dapr.io](https://dapr.io) binding

## Specifications

  - **KEDA Version:** v2.0 
  - **Platform & Version:** 
  - **Kubernetes Version:** Kubernetes 1.18, AWS hosted, service accounts are there, no errors in metric server
  - **Scaler(s):** RabbitMQ

## Files

*deploy-keda.yaml*

```yaml
# https://keda.sh/docs/2.0/scalers/rabbitmq-queue/
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: d-on-demand-scaler
  namespace: default
  labels:
    app: d-on-demand
    deploymentName: d-website-scraper-on-demand
spec:
  scaleTargetRef:
    name: d-on-demand
  minReplicaCount: 1
  maxReplicaCount: 4
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 5 # Optional. Default: 300 seconds
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://user:******@rabbitmq.default.svc.cluster.local:5672/
      queueName: rabbitmq-input
      queueLength: '2' # After how many do we scale up?
```
