### ISSUE TITLE
SQS scaler not scaling when setup using role based authentication 

### ISSUE THREAD

**Issue by NikitaGandhi** [kedacore/keda#1408]
When setting up KEDA scaler using AWS service account role based access as documented [here](https://keda.sh/docs/2.0/scalers/aws-sqs/), it scales down deployment to 0 but then doesn't scale deployment even there are messages in a queue. Also there is no clear example for how to setup SQS scaler using role based authentication.

keda Config file
```
---
apiVersion: v1
kind: Secret
metadata:
  name: keda-secrets
data:
  SERVICE_ACCOUNT_ROLE_ARN: <SECRET>

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
spec:
  secretTargetRef:
  - parameter: awsRoleArn
    name: keda-secrets
    key: SERVICE_ACCOUNT_ROLE_ARN

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
spec:
  scaleTargetRef:
    name: keda-aws-sqs-example
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-trigger-auth-aws-credentials
      metadata:
        queueURL: "my_queue_url"
        queueLength: "5"
        awsRegion: "ap-southeast-2"
```

and deployment config file
```
---
# Service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-example-sa
  annotations:
    eks.amazonaws.com/role-arn: "my-service-account-role-arn"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keda-example-role
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keda-example-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-example-role
subjects:
  - kind: ServiceAccount
    name: keda-example-sa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-aws-sqs-example
spec:
  selector:
    matchLabels:
      service: keda-aws-sqs-example
  template:
    metadata:
      labels:
        service: keda-aws-sqs-example
    spec:
      serviceAccountName: keda-example-sa
      containers:
      - image: <container-image>
        name: keda-aws-sqs-example
        env:
        - name: AWS_DEFAULT_REGION
          value: "ap-southeast-2"
       ...
```

## Expected Behaviour
This should work same as Credential based authentication.

## Actual Behavior
no scaling activity when setup using role based authentication 

## Specifications

  - **KEDA Version:** 2.0.0
  - **Platform & Version:** AWS EKS 1.16
  - **Kubernetes Version:** 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
  - **Scaler(s):** *AWS SQS Scaler*
