### ISSUE TITLE
Unable to get Azure Service Bus subscription ActiveMessageCount

### ISSUE THREAD

**Issue by aminebizid** [kedacore/keda#146]
My deployment don't scale because no metrics from Azure Service Bus

```bash
k -n hpa get hpa
NAME                REFERENCE             TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-consumer   Deployment/consumer   <unknown>/80%   1         10        1          3m
```

No errors on keda
```bash
k -n keda logs -f keda-keda-edge-584dd6ccc6-km8j6
time="2019-05-06T20:24:00Z" level=info msg="Deleted HPA with namespace hpa and name keda-hpa-consumer"
time="2019-05-06T20:24:13Z" level=info msg="Watching ScaledObject: hpa/azure-servicebus-queue-scaledobject"
time="2019-05-06T20:24:13Z" level=info msg="Created HPA with namespace hpa and name keda-hpa-consumer"
```

# My bus
- topicName: testk8s
- subscriptionName: testk8ssub
- I created a policy called demorule under the topic with Manage rights

# My secret
```bash
export SERVICEBUS_CONNECTION_STRING="Endpoint=sb://xxx.servicebus.windows.net/;SharedAccessKeyName=demorule;SharedAccessKey=xxx;EntityPath=testk8s"

k -n hpa create secret generic servicebuskey --from-literal=sb-connection-string=$SERVICEBUS_CONNECTION_STRING
```

# My consumer deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: aminrbizid/servicebus-topic:1.0.0
        args: ["testk8s", "testk8ssub"]
        env:
          - name: SERVICEBUS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: servicebuskey
                key: sb-connection-string
    
```

# My ScaledObject
```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-servicebus-queue-scaledobject
  namespace: hpa
spec:
  scaleTargetRef:
    deploymentName: consumer
  pollingInterval: 5
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 10 # Optional. Default: 100
  triggers:
  - type: azure-servicebus
    metadata:
      # Required: queueName OR topicName and subscriptionName
      # queueName: functions-sbqueue
      # or
      topicName: testk8s
      subscriptionName: testk8ssub
      # Required
      connection: SERVICEBUS_CONNECTION_STRING
      # Optional
      queueLength: "30" # default 5
```

Could you please give me the az command you use to get the connection string.
The connection string I use works with my consumer.

Could you please also add the error in logs if keda is unable to get the ActiveMessageCount.

**Comment by lee0c** [comment]
I believe you want to set the connection value in your ScaledObject to the secret key, not the name of the container's environment variable.

Additionally, ScaledObjects need a label that sets the deploymentName:
```yaml
metadata:
  name: azure-servicebus-queue-scaledobject
  label:
    deploymentName: consumer
```

**Comment by aminebizid** [comment]
@lee0c I did the changes as you mentionned
I tried
```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-servicebus-queue-scaledobject
  namespace: hpa
  label:
    deploymentName: consumer
spec:
  scaleTargetRef:
    deploymentName: consumer
  pollingInterval: 5
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 10 # Optional. Default: 100
  triggers:
  - type: azure-servicebus
    metadata:
      # Required: queueName OR topicName and subscriptionName
      # queueName: functions-sbqueue
      # or
      topicName: testk8s
      subscriptionName: testk8ssub
      # Required
      connection: servicebuskey
      # Optional
      queueLength: "30" # default 5

```

then 
```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-servicebus-queue-scaledobject
  namespace: hpa
  label:
    deploymentName: consumer
spec:
  scaleTargetRef:
    deploymentName: consumer
  pollingInterval: 5
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 10 # Optional. Default: 100
  triggers:
  - type: azure-servicebus
    metadata:
      # Required: queueName OR topicName and subscriptionName
      # queueName: functions-sbqueue
      # or
      topicName: testk8s
      subscriptionName: testk8ssub
      # Required
      connection: sb-connection-string
      # Optional
      queueLength: "30" # default 5

```

but still not work
And I get a strange behaviour because the HPA is looking for a CPU metrics

```bash
k -n hpa describe hpa keda-hpa-consumer
Name:                                                  keda-hpa-consumer
Namespace:                                             hpa
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Tue, 07 May 2019 00:02:10 +0200
Reference:                                             Deployment/consumer
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 80%
Min replicas:                                          1
Max replicas:                                          10
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: no metrics returned from resource metrics API
Events:
  Type     Reason                        Age               From                       Message
  ----     ------                        ----              ----                       -------
  Warning  FailedComputeMetricsReplicas  1m (x12 over 4m)  horizontal-pod-autoscaler  failed to get cpu utilization: missing request for cpu
  Warning  FailedGetResourceMetric       1m (x13 over 4m)  horizontal-pod-autoscaler  missing request for cpu
```
