### ISSUE TITLE
[Scaler] Azure Storage Blobs

### ISSUE THREAD

**Issue by pushthat** [kedacore/keda#154]
Is it plan to subscribe to event grid to get event from Azure Storage blobs ?

Also, what do you think the metadata will look like ?

**Comment by jeffhollan** [comment]
Yes my hope here is that the Azure Storage blob trigger will leverage Event Grid to activate / deactivate.  I'm not quite sure the right way to expose a custom metric to drive 1:n scaling though.  I'm not quite sure if there's a clean way to track that - but I need to understand more how we do 1:n scaling in the Azure Functions service.

If I had to guess the metadata would be something like:

```yaml
metadata:
  connection: storageSecretConnectionString
  containerName: myContainer
```

However we'd also likely need some metadata that would map to the Event Grid info.  I'm wondering here if the easiest answer to not have to expose an endpoint from K8s would be wire up a storage queue.... but I'm not sure what happens to the queue messages.  A few questions here we've got to sort out.  But metadata could end up looking something like

```yaml
metadata:
  connection: storageSecretConnectionString
  containerName: myContainer
  eventGridQueueName: myEventQueue
  eventGridConnectionString: storageSecretConnectionString
```

**Comment by tomkerkhove** [comment]
Just some small nitpicking but it should be the following to align with Grid terminology
```
metadata:
  connection: storageSecretConnectionString
  containerName: myContainer
  eventGridTopicName: myEventTopic
  eventGridAuthKey: eventGridAuthenticationKey
```

I'm also not sure if we know this information as it's abstracted for us, we only wee that for custom topics.
