### ISSUE TITLE
Forbidden listing resource statefulsets at the cluster scope

### ISSUE THREAD

**Issue by dbarentine** [kedacore/keda#1554]
Fresh install of KEDA 2.1 using Helm and I tried to create a ScaledObject for a StatefulSet but I get the following error:
**ScaledObject doesn't have correct scaleTargetRef specification**

I verified that the statefulset did exist though. I then looked at the log for the keda-operator and saw the following:

2021-02-02T00:49:45.145Z	INFO	controllers.ScaledObject	Reconciling ScaledObject	{"ScaledObject.Namespace": "identitymanager-dev", "ScaledObject.Name": "oneimtest-hpa"}
E0202 00:49:45.152664       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:serviceaccount:extension-system:keda-operator" cannot list resource "statefulsets" in API group "apps" at the cluster scope

The scaledobject looks like:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: im-hpa
  namespace: im-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: im-apiserver
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: 70
  - type: memory
    metadata:
      type: Utilization
      value: 80
```
Adding a cluster role and rolebinding for the serviceaccount does fix the issue immediately though.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-operator-statefulsets
rules:
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-operator-statefulsets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-operator-statefulsets
subjects:
  - kind: ServiceAccount
    name: keda-operator
    namespace: extension-system
```
