### ISSUE TITLE
Not being able to update ScalinJob jobTemplate metadata 

### ISSUE THREAD

**Issue by connatix-cradulescu** [kedacore/keda#1560]
Hi,

I am trying to add a certain label and annotation to a job template but I am not able to do that. Here is my configuration:
```
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: keda-scaling-{{ .Release.Namespace }}
        annotations:
          sidecar.istio.io/inject: "false"
      spec:
        containers:
    ------
```
Here is the result in cluster:
```
 spec:
    failedJobsHistoryLimit: 1
    jobTargetRef:
      backoffLimit: 4
      template:
        metadata: {}
        spec:
          containers:
``` 

From the format, this would be the logical choice but seems the CRD is ignoring my setup. 

Any advice please, on how I can update the metadata?
