### ISSUE TITLE
Provide support for AAD Pod Identity

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#161]
Provide support for AAD Pod Identity to make it easier to authenticate to certain Azure workloads.

https://github.com/Azure/aad-pod-identity#getting-started

**Comment by tomkerkhove** [comment]
@jeffhollan I would consider this as required for v1.0

**Comment by jeffhollan** [comment]
Could this be used as a connection mechanism for the Service Bus scaler? Can I think of it like Managed Identities for Azure Resources, but in Kubernetes?

**Comment by tomkerkhove** [comment]
That is correct @jeffhollan - AAD Pod Identity allows you to assign AD Apps to Pods which will use MSI ([concept](https://github.com/Azure/aad-pod-identity/blob/master/docs/design/concept.md))

This would allow us to connect to Azure Storage, Monitor, et al without using secrets.

**Comment by yaron2** [comment]
Important to note this only works for clusters running in **Azure**.

**Comment by tomkerkhove** [comment]
That's a good point, I was just reading about that.

Are there plans to support this kind of things via some sort of vendor plugins or so? It would be really good to be able to opt-in for this.

**Comment by yaron2** [comment]
Unfortunately its coupled to metadata coming from Azure VMs for aks/aks-engine.

**Comment by tomkerkhove** [comment]
This is decoupled from Keda by using the framework and handled by AAD Pod Identity for us, all we would need to do is provide the capability to choose to use ADAL instead.

**Comment by yaron2** [comment]
Yep.

**Comment by lee0c** [comment]
@jeffhollan This is something we will actually need for the current customer's setup to get to production. Having secrets stored on the cluster isn't doable for security reasons & all authentication & secret management is done with MSI. Is this on your radar as something that will be implemented?

**Comment by tomkerkhove** [comment]
I consider this a v1.0 requirement

**Comment by asavaritayal** [comment]
Capturing the discussion from standup - this shouldn't be a blocker but we'd like to align it with the v1.0 release in order to cater to multiple customer scenarios.

**Comment by lee0c** [comment]
To follow up from standup, it is a blocker in cases where there are enterprise security restrictions to keep in mind. Our customer case had very stringent security & would need their design to pass review (by people who may not be familiar with namespacing). In a scenario where the rest of the application is working through Pod ID, it is highly preferable to have KEDA fit that story to meet security expectations.

**Comment by lee0c** [comment]
@jeffhollan @anirudhgarg My next two weeks will be fairly busy but I'm willing to look into this & potentially put in a PR if you're alright with a bit of delay 😄

**Comment by tomkerkhove** [comment]
I fully agree, but I think we should not underestimate the impact of adding that because:
- How will the AD App be configured? Part of the KEDA deployment I presume?
- Will you enforce using that for all ScaledObjects that support Azure AD Auth, or will it be configurable on the ScaledObject?

**Comment by lee0c** [comment]
Not sure on the first question - I'm guessing that most if not all of the set up would be left to the user, since it's unlikely only KEDA would need that set up. To the second, I would assume it would be configurable - for any given ScaledObject you could choose to opt in to pod id & provide pod ID client details. I need to look into it more though!

**Comment by jeffhollan** [comment]
Yes @lee0c that would be awesome if you could help tackle.  And to clarify thinking being this isn't a blocker to 1.0 (meaning it may come a little further down in the backlog from priority POV) but absolutely agree this feature would be a blocker for some customers adopting KEDA.  So would be awesome to get some help to get this in even sooner than some of the other work items on @Aarthisk and others.

And yes I'm wondering if there could be some flag on the ScaledObject -- maybe at the metadata level -- to let it know to not look in secrets / env for the connectionString but rather leverage pod identity.  We can't enforce it for all ScaledObjects because some like RabbitMQ, Redis, AWS SQS will never really support AAD Identity I imagine.

**Comment by patnaikshekhar** [comment]
@jeffhollan @lee0c @yaron2 I've created a pull request that includes new fields to support Azure AD Pod Identity for Azure Storage Queue.

**Comment by tomkerkhove** [comment]
Thanks for your PR @patnaikshekhar!

Before we move forward I'd love to challenge the suggestion to use `metadata` for indicating this as this is a more general concept than trigger concepts.

Would it make sense to introduce a section called `trigger.authentication` for this?

This would allow us to keep the trigger metadata purely on the trigger while the authentication node describes *how* to authenticate and allow users to define how and where it is.

### Sample

```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-queue-po-id-scaledobject
  namespace: keda-aad-pod-id
  labels:
    deploymentName: keda-aad-pod-id
spec:
  scaleTargetRef:
    deploymentName: keda-aad-pod-id
  triggers:
  - type: azure-queue
    metadata:
      queueName: keda-test
      accountName: kedastoragequeuetest
      queueLength: "5"
    authentication:
      method: azureMsi | secret | env
      secretRef:
         name: my-keda-secret # only when method is 'secret'
         name: my-keda-secret # only when method is 'secret'
      env:
         name: my-env-with-secret # only when method is 'env'
         containerName: my-container# only when method is 'env'
```
