### ISSUE TITLE
Auditing failed of request: encoding failed: no kind "Scale" is registered for version "apps/v1"

### ISSUE THREAD

**Issue by wiseelf** [kedacore/keda#1646]
### Report

I see a lot of warnings in kube-apiserver logs about 'no kind "Scale" is registered for version "apps/v1"'
Probably these warnings can lead to increased apiserver latency.

### Expected Behavior

No errors/warnings
How to avoid such errors/warnings to appear?

### Actual Behavior

A lot of warnings in kube-apiserver logs:
```
W0302 11:11:54.459345       1 request.go:161] Auditing failed of  request: encoding failed: no kind "Scale" is registered for version "apps/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"
```

At the same time in keda-operator logs I see this event:
```
2021-03-02T11:11:54.467Z    INFO    scaleexecutor   Successfully updated ScaleTarget    {"scaledobject.Name": "react-worker", "scaledObject.Namespace": "iris-react", "scaleTarget.Name": "react-worker-cli", "Original Replicas Count": 0, "New Replicas Count": 1}
```

### Steps to Reproduce the Problem

1. EKS cluster 1.18/1.19
2. deployment with apiVersion: apps.v1
3. ScaledObject with metrics-api scaler.

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-cli
    envSourceContainerName: worker-cli
  pollingInterval: 30
  cooldownPeriod:  120
  minReplicaCount: 0
  maxReplicaCount: 10
  advanced:
    restoreToOriginalReplicaCount: false
  triggers:
  - type: metrics-api
    metadata:
      targetValue: "50"
      url: https://api.endpoint.com/queue/
      valueLocation: "main_queue.value"
```

### Logs from KEDA operator

```
2021-03-02T11:11:54.467Z    INFO    scaleexecutor   Successfully updated ScaleTarget    {"scaledobject.Name": "react-worker", "scaledObject.Namespace": "iris-react", "scaleTarget.Name": "react-worker-cli", "Original Replicas Count": 0, "New Replicas Count": 1}
```

### KEDA Version

2.1.0

### Kubernetes Version

1.19

### Platform

Amazon Web Services

### Scaler Details

metrics-api
