### ISSUE TITLE
Issue in Keda with Metric API

### ISSUE THREAD

**Issue by arjaiswa** [kedacore/keda#1655]
I have used below scaled object. Whenever This is getting value from URL and value > target value then its performing scale up and as well as its deleting the same pod.
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaledobject
  namespace: default
spec:
  minReplicaCount: 0
  cooldownPeriod:  10
  pollingInterval: 3
  scaleTargetRef:
    name: dummy
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://20.69.201.225:8080/stats/"
        valueLocation: 'worker.task'
```

Events :
```
73s         Normal    SuccessfulCreate               replicaset/dummy       (combined from similar events): Created pod: dummy-twhcg
58s         Normal    SuccessfulDelete               replicaset/dummy       (combined from similar events): Deleted pod: dummy-nsv9t
10m         Normal    SuccessfulCreate               replicaset/dummy       Created pod: dummy-k42vz
10m         Normal    SuccessfulDelete               replicaset/dummy       Deleted pod: dummy-k42vz
10m         Normal    SuccessfulCreate               replicaset/dummy       Created pod: dummy-l2qm9
10m         Normal    SuccessfulDelete               replicaset/dummy       Deleted pod: dummy-l2qm9
10m         Normal    SuccessfulCreate               replicaset/dummy       Created pod: dummy-b5vv4
10m         Normal    SuccessfulDelete               replicaset/dummy       Deleted pod: dummy-b5vv4
10m         Normal    SuccessfulCreate               replicaset/dummy       Created pod: dummy-4tzbb
10m         Normal    SuccessfulDelete               replicaset/dummy       Deleted pod: dummy-4tzbb
```
