### ISSUE TITLE
Metrics API scaler does not support Quantities

### ISSUE THREAD

**Issue by devjoes** [kedacore/keda#1667]
### Report

The metrics API is unable to process Quantities (even simple numeric ones.) This is because they are serialized to strings. KEDA actually returns Quantities itself so this scaler would no be able to process them either.

### Expected Behavior

I receive an API response like this:

```
{"foo":"123"}
```

I am able to reference it like this

```
  triggers:
  - type: metrics-api
    metadata:
      targetValue: "0"
      url: "https://blah"
      valueLocation: "foo"
```

### Actual Behavior

The error:
valueLocation must point to value of type number got: String

### Steps to Reproduce the Problem

1.Make/use an API that returns quantities
2.Point the metrics API scaler at it
3.Observe error

### Logs from KEDA operator

```
example
```

### KEDA Version

2.1.0

### Kubernetes Version

1.17

### Platform

Any

### Scaler Details

metrics-api

PR will be raised to fix issue in a minute
