### ISSUE TITLE
[Azure Function] Remove jobs and related pods when work is done

### ISSUE THREAD

**Issue by andrekiba** [kedacore/keda#1736]
### Report

I have an Azure Function that processes one message at a time.
The processing takes 5-10 minutes (maybe more) so we diced to use the `ScaledJob` approach.
This is the configuration of the `ScaledJob`:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: assembler-job
spec:
  jobTargetRef:
    parallelism: 1                # [max number of desired pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    completions: 1                # [desired number of successfully finished pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    activeDeadlineSeconds: 3600   # Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
    backoffLimit: 1               # Specifies the number of retries before marking this job failed. Defaults to 6
    ttlSecondsAfterFinished: 100
    template:
      spec:
        containers:
          - env:
              - name: ASPNETCORE_ENVIRONMENT
                value: Development
              - name: AzureWebJobsServiceBus
                valueFrom:
                  secretKeyRef:
                    name: assembler-job
                    key: AzureWebJobsServiceBus
              - name: AzureWebJobsStorage
                valueFrom:
                  secretKeyRef:
                    name: assembler-job
                    key: AzureWebJobsStorage
            image: <azure function image here>
            name: assembler-job
            ports:
              - containerPort: 80
                protocol: TCP
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
        restartPolicy: Never
  pollingInterval: 10    
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 3
  maxReplicaCount: 10
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: <queue name here>
        messageCount: '1'
      authenticationRef:
        name: trigger-auth-asb
```

The idea of `messageCount=1` in the trigger is to create one job (and pod) for each new message.
The scale-up is ok...the problem is the scale-down...
Is it something related to the concept of job "completion"??

### Expected Behavior

Remove the pod/s and the job when completed.

### Actual Behavior

Pods related to jobs remains in Running without a reason.

### Steps to Reproduce the Problem

1. Setup a ScaledJob triggered by an AzureServiceBus queue
2. Each job creates 1 pod (parallelism=1, completions=1) with an Azure Function 
3. Each job processes only one message that takes 5-10 minutes
4. The message is processed correctly, in pod log everything is ok and the function terminates correctly
5. The pod remains in Running after the work is done 

### Logs from KEDA operator

```
example
```

### KEDA Version

2.2.0

### Kubernetes Version

1.18

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus
