### ISSUE TITLE
Scale to zero with cron trigger

### ISSUE THREAD

**Issue by dorroddorrod** [kedacore/keda#1757]
### Report

Hi !,
I'm running few k8s dev cluster and i would like to scale few deployments to 0 during the weekend to save some costs.
I used the cron trigger to schedule a scale down but nothing really happen
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-to-zero
  namespace: default
spec:
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 30
  scaleTargetRef:
    name: my-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Jerusalem
      start: 18 * * * *
      end: 30 * * * *
      desiredReplicas: "0"
```

I probably didn't configure something right.. didnt find any doc's regarding this use-case 

### Expected Behavior

The number of replicas should decrease to 0

### Actual Behavior

Nothing

### Steps to Reproduce the Problem

1. Apply the above yaml file and watch the number of pods that are running 

### KEDA Version

2.2.0

### Kubernetes Version

1.16

### Platform

Amazon Web Services

### Scaler Details

Cron
