### ISSUE TITLE
Unable to scale to more than 1 replica

### ISSUE THREAD

**Issue by benjaminhuo** [kedacore/keda#1804]
### Report

I am unable to scale my dapr nodejs deployment to more than 1 pod even after I scaled my producer python app to 2 or 4 or 8 replicas, the replicas of the nodejs deployment is alway up to 1, scaling between 0 and 1 is always possible .  

There’re remaining kafka messages for a while after I scale the python producer app to 0. 

Here is my code https://github.com/benjaminhuo/quickstarts/tree/master/bindings/deploy

### Expected Behavior

Scale to more than one pod when kafka  consumer lag goes above the threshold

### Actual Behavior

unable to scale my dapr nodejs deployment to more than 1 pod 

### Steps to Reproduce the Problem

1. Install Dapr and KEDA
2. Install Dapr kafka binding like below：
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sample-topic
spec:
  type: bindings.kafka
  version: v1
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: my-cluster-kafka-0.my-cluster-kafka-brokers.default.svc:9092
  # consumer configuration: topic and consumer group
  - name: topics
    value: sample
  - name: consumerGroup
    value: group1
  # publisher configuration: topic
  - name: publishTopic
    value: sample
  - name: authRequired
    value: "false"
```
3. Install nodejs consumer and python producer
```
kubectl apply -f ndoe.yaml
kubectl apply -f python.yaml
```
4. Apply keda scaler like below
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: bindings-nodeapp
  pollingInterval: 5
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 30
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: my-cluster-kafka-0.my-cluster-kafka-brokers.default.svc:9092
      consumerGroup: group1
      topic: sample
      # Optional
      lagThreshold: "1"
      offsetResetPolicy: latest
```
5. scale the python producer to 4 replicas
6. The nodejs consumer remains 1 replica
7. scale the python replica to 0, the  nodejs consumer will remain active because there're remaining kafka msg 
8. consumer and producer code is in https://github.com/benjaminhuo/quickstarts/tree/master/bindings/nodeapp https://github.com/benjaminhuo/quickstarts/tree/master/bindings/pythonapp

### Logs from KEDA operator

```
No errors
```

### KEDA Version

2.2.0

### Kubernetes Version

1.18

### Platform

Other

### Scaler Details

Kafka
