### ISSUE TITLE
ScaledObject type Cron with Min Replicas

### ISSUE THREAD

**Issue by msfidelis** [kedacore/keda#1807]
### Proposal

Configs in `metadata.end` of cron scheduler type to not set desired replicas to 0, just adjust to deployment default value. 

`defaultReplicas` or `minReplicas` to scale after the warm up period ends. 

### Use-Case

Pre-warming deployments at certain times to prepare for access and periods

**Comment by tomkerkhove** [comment]
Hi, can you clarify what you want to achieve, please?

Because from what you are describing, it sounds like you are describing what our Cron scaler does.

It scales a target to a given amount of replicas based on the schedule.

**Comment by JorTurFer** [comment]
Maybe @msfidelis was talking about [this](https://github.com/kedacore/keda/blob/main/pkg/scalers/cron_scaler.go#L22). 
Basically, we are scaling to 1 when we are out of the cron active time. Would it be nice if we support the selection of the amount of the replicas in case of active period and in case of inactive period?

**Comment by tomkerkhove** [comment]
The case of inactive is most probably covered by https://github.com/kedacore/keda/pull/1958 which is now in v2.4

**Comment by JorTurFer** [comment]
Nice!

**Comment by msfidelis** [comment]
I'm sorry for delay. I found the solution for my problem. I need create a pre-warmup for predictive throughput and return to normal capacity after that.

To Keda don't set my tasks to 0 after `cron` triggers ends, i just set `minReplicaCount` to my default replica count.

```yaml
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example-app-warm-up
  namespace: example-app
spec:
  scaleTargetRef:
    name: example-app
  minReplicaCount: 10
  maxReplicaCount: 30
  triggers:
  - type: cron
    metadata:
      timezone: America/Sao_Paulo
      start: 00 00 * * *
      end: 00 06 * * *
      desiredReplicas: "30"
```

I'm sorry for the time the issue stay open and I appreciate your attention, folks!
