### ISSUE TITLE
Azure Blob Scaler fails when using multiple triggers with different blobPrefixes

### ISSUE THREAD

**Issue by MattJeanes** [kedacore/keda#1815]
### Report

The metricName uniqueness is not adequate when using multiple scalers with the same `blobContainerName` but a different `blobPrefix`

The current code only uses `blobContainerName` for uniqueness when it should include blobPrefix: https://github.com/kedacore/keda/blob/v2.2.0/pkg/scalers/azure_blob_scaler.go#L153

### Expected Behavior

The scaler should work correctly without error

### Actual Behavior

The scaler does not work , status of the ScaledObject shows:

```yaml
status:
  conditions:
    - message: Failed to ensure HPA is correctly created for ScaledObject
      reason: ScaledObjectCheckFailed
      status: 'False'
      type: Ready
    - message: ScaledObject check failed
      reason: UnkownState
      status: Unknown
      type: Active
  originalReplicaCount: 
```

### Steps to Reproduce the Problem

1. Create a ScaledObject with multiple blob triggers using the same blobContainerName but a different blobPrefix:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-scaled-function-scaler
spec:
  scaleTargetRef:
    name: my-scaled-function
  triggers:
    - metadata:
        blobContainerName: mycontainer
        blobPrefix: folder1
        connectionFromEnv: AzureWebJobsStorage
      type: azure-blob
    - metadata:
        blobContainerName: mycontainer
        blobPrefix: folder2
        connectionFromEnv: AzureWebJobsStorage
      type: azure-blob
```
2. The ScaledObject fails to work correctly

### Logs from KEDA operator

```log
2021-05-20T00:05:22.235Z	INFO	controllers.ScaledObject	Reconciling ScaledObject	{"ScaledObject.Namespace": "my-namespace", "ScaledObject.Name": "my-scaled-function-scaler"}
2021-05-20T00:05:22.236Z	INFO	controllers.ScaledObject	Creating a new HPA	{"ScaledObject.Namespace": "my-namespace", "ScaledObject.Name": "my-scaled-function-scaler", "HPA.Namespace": "my-namespace", "HPA.Name": "keda-hpa-my-scaled-function-scaler"}
2021-05-20T00:05:22.236Z	ERROR	controllers.ScaledObject	Failed to create new HPA resource	{"ScaledObject.Namespace": "my-namespace", "ScaledObject.Name": "my-scaled-function-scaler", "HPA.Namespace": "my-namespace", "HPA.Name": "keda-hpa-my-scaled-function-scaler", "error": "metricName azure-blob-mycontainer defined multiple times in ScaledObject my-scaled-function-scaler, please refer the documentation how to define metricName manually"}
github.com/kedacore/keda/v2/controllers.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/scaledobject_controller.go:316
github.com/kedacore/keda/v2/controllers.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/scaledobject_controller.go:204
github.com/kedacore/keda/v2/controllers.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/scaledobject_controller.go:160
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:244
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90
2021-05-20T00:05:22.236Z	ERROR	controllers.ScaledObject	Failed to ensure HPA is correctly created for ScaledObject	{"ScaledObject.Namespace": "my-namespace", "ScaledObject.Name": "my-scaled-function-scaler", "error": "metricName azure-blob-mycontainer defined multiple times in ScaledObject my-scaled-function-scaler, please refer the documentation how to define metricName manually"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:244
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90
2021-05-20T00:05:22.249Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "name": "my-scaled-function-scaler", "namespace": "my-namespace", "error": "metricName azure-blob-mycontainer defined multiple times in ScaledObject my-scaled-function-scaler, please refer the documentation how to define metricName manually"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.5/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90
```

### KEDA Version

2.2.0

### Kubernetes Version

1.20

### Platform

Microsoft Azure

### Scaler Details

Azure Blob
