### ISSUE TITLE
Allow HPA minReplicas other than 1 while still scaling to 0

### ISSUE THREAD

**Issue by philipp94831** [kedacore/keda#1838]
### Proposal

We currently have a scenario where we need to scale our deployments to 0 or have at least, e.g., 5 replicas available. We were not able to achieve this by overriding the HPA scale behavior. [In the code](https://github.com/kedacore/keda/blob/29febffc1ec32f41836082c587ba860b7c59d3cd/controllers/hpa.go#L215), the HPA minReplicas are always set to 1 if we want to scale to 0.

Therefore, we propose to be able to explicitly configure HPA minReplicas.

### Use-Case

We are running Kafka Streams apps on Kubernetes and automatically scale them using KEDA. If there is no message lag, we can safely scale to 0. However, when process messages, we use Kafka Streams state stores, which are loaded into the memory of our pods. Because the resources of a single pod are insufficient, we replicate our deployment and thus distribute the state and require less resources per pod.

**Comment by tomkerkhove** [comment]
Ha interesting so basically you want to have a minimum of 5 replicas, but when there is no work you want to scale to 0. So basically decoupling the min replica count from the scale to 0.

Is that a good summary?

**Comment by philipp94831** [comment]
@tomkerkhove That is exactly what we want! :-)

**Comment by zroubalik** [comment]
That's viable ask, are you willing to contribute this?

**Comment by philipp94831** [comment]
> That's viable ask, are you willing to contribute this?

I am not experienced with developing in Go/Kubernetes modules so if you had the time to do it, I'd prefer that. However, I would have a look at it if you won't be able to work on it in the near future

**Comment by zroubalik** [comment]
Unfortunately I can't promise anything :) So let's see.

**Comment by philipp94831** [comment]
Do you have some hints maybe? Is it as simple as introducing a new config option and use it [her](https://github.com/kedacore/keda/blob/29febffc1ec32f41836082c587ba860b7c59d3cd/controllers/hpa.go#L215) if configured?

**Comment by zroubalik** [comment]
It is not just that, but the loop logic needs to be modified as well. 

@philipp94831 OK, so ping me in two weeks and I'll let you know if I am able to implement this in near future.

**Comment by ChayanBansal** [comment]
Hey @zroubalik, can you please point out the loop where modifications need to be made along with some changes [here](https://github.com/kedacore/keda/blob/29febffc1ec32f41836082c587ba860b7c59d3cd/controllers/hpa.go#L211). I would glad if I could contribute. Hoping its not too complex! :)

**Comment by zroubalik** [comment]
@ChayanBansal it might not be needed, but we need to be sure that the loop in here is working correctly with the new feature: https://github.com/kedacore/keda/blob/29febffc1ec32f41836082c587ba860b7c59d3cd/pkg/scaling/executor/scale_scaledobjects.go#L19

I mean setting the right number of replicas etc, I've been very briefly checking that and it should work as it is implemented currently, but I am not sure.

Would be really great if you can contribute this! Thanks :)

**Comment by philipp94831** [comment]
Hi @ChayanBansal, I really appreciate that you would like to contribute to this! Do you think you will be able to implement this? If so, how long do you estimate it to take?

**Comment by philipp94831** [comment]
> It is not just that, but the loop logic needs to be modified as well.
> 
> @philipp94831 OK, so ping me in two weeks and I'll let you know if I am able to implement this in near future.

Hi @zroubalik, do you think you will be able to implement this in the near future?

**Comment by zroubalik** [comment]
@philipp94831 I will give it a try :)

**Comment by zroubalik** [comment]
I am thinking how should we expose this configuration in ScaledObject [spec](https://keda.sh/docs/2.3/concepts/scaling-deployments/#scaledobject-spec), wrt naming and UX. `scaleToZero` boolean field?

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example-so
spec:
  scaleTargetRef:
    name:  target
  pollingInterval: 30                        
  cooldownPeriod:  300                            
  scaleToZero: true/false
  minReplicaCount: 5                     
  maxReplicaCount: 100  
```

@philipp94831 @tomkerkhove WDYT?

**Comment by philipp94831** [comment]
I like that :-) I assume that scaleToZero will be true by default? Or at least if `minReplicaCount` is 0? So that nothing changes for users that used `minReplicaCount: 0`

**Comment by zroubalik** [comment]
Yeah, exactly. Let's wait what Tom's opinion is :)

**Comment by zroubalik** [comment]
The only concern I have, if this field  should be "hidden' in `spec.advanced` section.

**Comment by tomkerkhove** [comment]
Advanced or so might make sense since by default we should recommend scale to zero indeed;

What about `allowScaleToZero` or `useScaleToZero` though? Otherwise it's not clear what the intent is, maybe? (I think things through too much 😂)

**Comment by zroubalik** [comment]
What about `alwaysScaleToZero` ?

**Comment by tomkerkhove** [comment]
Doesn't that imply it will always be scaled to 0? 😁

**Comment by zroubalik** [comment]
Fair enough 🤷‍♂️ 😅  But you can look at it this way: always scale to zero, even if minReplicas is > 0 ...

I don't know 😄

**Comment by svmaris** [comment]
I think the new `allowScaleToZero`  of `scaleToZero` boolean in the spec will cause confusion and allows for weird combinations. What if `minReplicas` is set to `0`, but `scaleToZero` is `false`?

Wouldn't it be better to keep the meaning of `minReplicas: 0` to be "allow scale to zero" and introduce a new field that specifies the minimum number of replicas you want to have running when there's actually work to be done? Like for example `initialReplicas` / `defaultReplicas` / `baselineReplicas` ?

**Comment by zroubalik** [comment]
> I think the new `allowScaleToZero` of `scaleToZero` boolean in the spec will cause confusion and allows for weird combinations. What if `minReplicas` is set to `0`, but `scaleToZero` is `false`?

The ScaledObject will be validated and returns error in this case.

> 
> Wouldn't it be better to keep the meaning of `minReplicas: 0` to be "allow scale to zero" and introduce a new field that specifies the minimum number of replicas you want to have running when there's actually work to be done? Like for example `initialReplicas` / `defaultReplicas` / `baselineReplicas` ?

I was thinking about similar approach using `initialReplicas`, but then we will need to cover cases where `minReplicas != 0` for example:
```
minReplicas = 2
initialReplicas = 5 
maxReplicas = 10
```
And IMHO that's way more complex logic that would need to be changed in KEDA, but checking that right know.

**Comment by tomkerkhove** [comment]
`allowScaleToZero` of `scaleToZero` are fine for me

**Comment by zroubalik** [comment]
So the question is, whether we want to support: 
- scale to zero with `minReplicas > 0 `: 
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example-so
spec:
  scaleTargetRef:
    name:  target                
  minReplicaCount: 5                     
  maxReplicaCount: 100  
  advanced:
    (always)scaleToZero: true/false
```
- arbitrary `minReplicas` with `initialReplicas` approach, allowing more flexibility:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example-so
spec:
  scaleTargetRef:
    name:  target                
  minReplicaCount: 2
  initialReplicaCount: 5                   
  maxReplicaCount: 100  
```
or 
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example-so
spec:
  scaleTargetRef:
    name:  target                
  minReplicaCount: 0
  initialReplicaCount: 5                   
  maxReplicaCount: 100  
```

**Comment by svmaris** [comment]
I think baselineReplicas is a better name, because I think otherwise people can assume that the number of replicas can/will drop *below* 5 replicas if there's work to do (but not enough to warrant 5 replicas). My point was mainly about the semantic meaning of minReplicas.

**Comment by philipp94831** [comment]
Hi @zroubalik, any update on this? :-)

**Comment by tomkerkhove** [comment]
I think he was mainly waiting for me but I forgot to circle back on this, sorry about that!

If we take a step back on what we want to achieve it is defining how many instances we want to have when there is no work to be done.

I think `baseline`/`base` is a bit too ambiguous but `initial` implies that it is only at the beginning. What about `idle`? Although that might be odd as well to some.

**Comment by svmaris** [comment]
> If we take a step back on what we want to achieve it is defining how many instances we want to have when there is no work to be done.

IMHO we already have that in the form of `minReplicaCount`. The use case here is that we want to define the minimum number of replicas when there *is* work to be done. But maybe this use case is a bit too exotic to support directly.

I was thinking: Would it be possible to take the use case described in #692, which is probably a bit more "generic" (scale down to 0 when there's no work, but scale up immediately when there's work to be done, but not enough to reach the threshold) and make it so that it support the use case described in this issue as well? Perhaps by defining a `replicaCountIncrement` that defines by how many replicas it should scale up at the same time?


```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: my-kafka-processor-keda
spec:
  scaleTargetRef:
    deploymentName: my-kafka-processor
  pollingInterval: 30
  minReplicaCount: 0
  replicaCountIncrement: 5
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: awesome.servicebus.windows.net:9093
      consumerGroup: my-kafka-worker
      topic: my-topic
      lagThreshold: "100"
      startThreshold: "1"
```

The above basically means:

 * Scale to zero when there's no work to be done
 * Scale up when there's at least 1 message in the queue
 * Scale up by increments of 5 replicas at a time

The `replicaCountIncrement` could be used to make sure there's a replica running in each availability zone for example (using anti-affinity rules).

**Comment by philipp94831** [comment]
> The above basically means:
> 
> * Scale to zero when there's no work to be done
> * Scale up when there's at least 1 message in the queue
> * Scale up by increments of 5 replicas at a time

While scaling up by increments of 5 would allow us to immediately scale from 0 to 5, it would also mean that the next step would be 10 replicas while it would be preferable for us to still then scale normally, i.e., 6 as the next step

**Comment by zroubalik** [comment]
> > The above basically means:
> > 
> > * Scale to zero when there's no work to be done
> > * Scale up when there's at least 1 message in the queue
> > * Scale up by increments of 5 replicas at a time
> 
> While scaling up by increments of 5 would allow us to immediately scale from 0 to 5, it would also mean that the next step would be 10 replicas while it would be preferable for us to still then scale normally, i.e., 6 as the next step

Yeah, that's a different use case completely.

**Comment by zroubalik** [comment]
> I think he was mainly waiting for me but I forgot to circle back on this, sorry about that!
> 
> If we take a step back on what we want to achieve it is defining how many instances we want to have when there is no work to be done.
> 
> I think `baseline`/`base` is a bit too ambiguous but `initial` implies that it is only at the beginning. What about `idle`? Although that might be odd as well to some.

@tomkerkhove it is not about number of instances when there is no work to be done, that's clear -> `minReplicaCount`

It is about the inital number of replicas (if min is 0) that should be set when there is some work to do, so instead of scaling to 1 it should scale for example to 5.

**Comment by tomkerkhove** [comment]
> not about the number of instances when there is no work to be done, that's clear -> `minReplicaCount`

That's if you think about how it is today, but if you ignore that and think purely conceptually I think we have it wrong today and `idle` feels better but it is what it is.

**Comment by svmaris** [comment]
> That's if you think about how it is today, but if you ignore that and think purely conceptually I think we have it wrong today and idle feels better but it is what it is.

Are you proposing to add a new field `idleReplicaCount` that defaults to the value of `minReplicaCount` when not defined and "changes" the meaning of `minReplicaCount` when it *is* defined, but has a different value? So that:

```yaml
  minReplicaCount: 5
  maxReplicaCount: 20
```

means "Scale to 5 when there's no work" (`idleReplicaCount` is set to 5 implicitly in this case)

and

```yaml
  idleReplicaCount: 0
  minReplicaCount: 5
  maxReplicaCount: 20
```

means "Scale to 0 when there's no work, but scale to a minimum of 5 when there *is* work" ?

**Comment by zroubalik** [comment]
Yeah, the other proposal is to not change the meaning of `minReplicaCount`, something like this:

```yaml
  minReplicaCount: 0
  initialReplicaCount: 5
  maxReplicaCount: 20
```
Or the new property could be named `baseReplicaCount` as suggested above.
