### ISSUE TITLE
Allow scalers to be dynamically pluggable

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#184]
Today each scaler has to be included in the KEDA release.  That means if you wanted to use a custom or specific scaler for your events, you'd have to fork our project.  Would be nice to implement some way to discover or plugin custom scalers

/cc @asavaritayal FYI

**Comment by jeffhollan** [comment]
Discussed this some in our weekly KEDA sync.  It doesn't appear there is a very easy way to do reflection around new pluggable components you could reference in KEDA and dynamically discover.  Main thinking is you'd have to deploy some "service" that could communicate with KEDA over gRPC or something and call it that way.

**Comment by patnaikshekhar** [comment]
Proposal
---
This is a proposal for the gRPC interface between external scalers and KEDA.

**Advantages**

1. New scalers can be created independently to changes in core​. When scalers / dependent libararies are updated they won't effect core.
2. Support creating scalers in multiple languages (nodejs, c#, etc) to allow for missing functionality in the go SDK – example Cosmos DB Change feed​
3. Adding third party libraries to Keda Core is increasing the size of the code base. The compiled keda-core binary now includes dependencies for Kafka, Redis, Azure Queue, Service Bus, etc

**Architecture**

The scale handler communicates with the external scaler over a gRPC interface. The external scaler acts as a gRPC server and the scaler within KEDA acts as a client. When a scale object of trigger type "external" is created, the scaler uses the service URI field of the scale object to figure out the location of the gRPC service and call the corresponding methods. The service will also use TLS to ensure that sensitive information such as credentials are encrypted in transit.

**Scaled Object for an External Scaler**

This is a sample scaled object for an external scaler. The *serviceURI* is one of the primary fields in the interface. It points to the URI for the external scaler. In addition to the serviceURI, a *tlsCertFile* can also be passed that contains the name of the TLS certificate to be used to secure the interaction.

```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  namespace: keda-redis-test
  labels:
    deploymentName: keda-redis-node
spec:
  scaleTargetRef:
    deploymentName: keda-redis-node
  triggers:
  - type: external
    metadata:
      serviceURI: redis-external-scaler-service:8080
      address: REDIS_HOST # Required host:port format
      password: REDIS_PASSWORD
      listName: mylist # Required
      listLength: "5" # Required
```

**Example Implementation**

An example implementation of an external scaler can be found [here](https://github.com/patnaikshekhar/KEDA-External-Scaler-Example)

**Interface Summary**
 
**New()** - Used to inform the external scaler that a new instance of a scaler should be created with the passed parameters​
**GetMetricsSpec()** - Return the External Metrics spec containing the metric name and target average value. Used to generate the HPA.​
**IsActive()** - Returns a Boolean value to indicate whether the Keda should scale the deployment to zero​
**GetMetrics()** - Get the current state of the metrics​
**Close()** - Remove the namespace/name from being monitored

**Full Interface**

```proto
syntax = "proto3";

package externalscaler;

import "google/protobuf/empty.proto";

service ExternalScaler {
    rpc New(NewRequest) returns (google.protobuf.Empty) {}
    rpc IsActive(ScaledObjectRef) returns (IsActiveResponse) {}
    rpc GetMetricSpec(ScaledObjectRef) returns (GetMetricSpecResponse) {}
    rpc GetMetrics(GetMetricsRequest) returns (GetMetricsResponse) {}
    rpc Close(ScaledObjectRef) returns (google.protobuf.Empty) {}
}

message ScaledObjectRef {
    string name = 1;
    string namespace = 2;
}

message NewRequest {
    ScaledObjectRef scaledObjectRef = 1;
    map<string, string> metadata = 2;
}

message IsActiveResponse {
    bool result = 1;
}

message GetMetricSpecResponse {
    repeated MetricSpec metricSpecs = 1;
}

message MetricSpec {
    string metricName = 1;
    int64 targetSize = 2;
}

message GetMetricsRequest {
    ScaledObjectRef scaledObjectRef = 1;
    string metricName = 2;
}

message GetMetricsResponse {
    repeated MetricValue metricValues = 1;
}

message MetricValue {
    string metricName = 1;
    int64 metricValue = 2;
}
```
