### ISSUE TITLE
READY AND ACTIVE fields of ScaledJob are empty when we run "kubectl get sj"

### ISSUE THREAD

**Issue by Shubham82** [kedacore/keda#1849]
### Report

When worked with ScaledJob i have noticed that it doesn't show the  `**READY**`  and   `**ACTIVE**`   status when we run `kubectl get sj` In both before and after the scaling. It always blank.

Before scaling
```
$ kubectl get sj
NAME          MAX   TRIGGERS   AUTHENTICATION    READY   ACTIVE   AGE
mongodb-job   100   mongodb    mongodb-trigger                    7s
```
After scaling
```
$ kubectl get sj
NAME          MAX   TRIGGERS   AUTHENTICATION    READY   ACTIVE   AGE
mongodb-job   100   mongodb    mongodb-trigger                    112s
```
Here is the Secrets, TriggerAuthentication and ScaledJob yamls which i have used to test it:

Secrets:
```
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  connect: bW9uZ29kYjovL3Rlc3RfdXNlcjp0ZXN0X3Bhc3N3b3JkQG1vbmdvZGItc3ZjLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvdGVzdA==
```
TriggerAuthentication:
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mongodb-trigger
spec:
  secretTargetRef:
  - parameter: connectionString
    name: mongodb-secret
    key: connect

```
ScaledJob:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: mongodb-job
spec:
  jobTargetRef:
    template:
      spec:
       containers:
       - name: pi
         image: perl
         command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
  pollingInterval: 20
  maxReplicaCount: 100
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 10
  triggers:
    - type: mongodb
      metadata:
        dbName: test
        collection: test_collection
        query: '{"region":"eu-1","state":"running","plan":"planA"}'
        queryValue: "1"
        metricName: "global-metric"
      authenticationRef:
        name: mongodb-trigger
```

### Expected Behavior

When we run `kubectl get sj` then it should show   `**READY**`  and   `**ACTIVE**`  status in both before and after scaling.
There status value would be: True, False, Unknown  depending upon the scaling just like we have in  ScaledObject.

### Actual Behavior

When we run `kubectl get sj` then it doesn't show   `**READY**`  and   `**ACTIVE**` status in both before and after scaling.

### Steps to Reproduce the Problem

1. Set-up minikube v1.18.1
2. Deploy mongodb.
3. Create secrets and TA with above yaml and apply it.
4. Create ScaledJob with above yaml's and apply it.
5. Check READY and ACTIVE Status before and after scaling by running kubectl get sj 

### Logs from KEDA operator

No error

### KEDA Version

2.3.0

### Kubernetes Version

1.20

### Platform

Other
