### ISSUE TITLE
milli values scale incorrectly

### ISSUE THREAD

**Issue by agolomoodysaada** [kedacore/keda#186]
I'm using the kafka ScaledObject. The HPA sees milli values incorrectly scaling them too high up.
In my case lagThreshold is set to "1". And the HPA sees the target as `1438m/1 (avg)`.
What's strange is that it's scaling up replicas to the max possible number based as though it's "1438/1" which is definitely incorrect!
Change the target from "1" to "1000" seems to fix the issue? This is definitely a bug though. 

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: myapp
  labels:
    deploymentName: myapp # must be in the same namespace as the ScaledObject
spec:
  scaleTargetRef:
    deploymentName: myapp # must be in the same namespace as the ScaledObject
  pollingInterval: 10  # Optional. Default: 30 seconds
  cooldownPeriod:  10 # 60 # Optional. Default: 300 seconds
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 20 # Optional. Default: 100
  triggers:
  - type: kafka
    metadata:
      brokerList: kafka-kafka-headless.kafka:9092
      consumerGroup: myconsumergroup
      topic: mytopic
      lagThreshold: "1"
```
