### ISSUE TITLE
ScaledJob with Cron trigger does not scale down on completion

### ISSUE THREAD

**Issue by jordenk** [kedacore/keda#1893]
### Report

ScaledJob with cron trigger does not limit itself to a single, successful job execution.

I think the completions in steps to reproduce should limit this to a single job execution.

### Expected Behavior

The scaledJob executes on a cron trigger. After the triggered job completes n times, where n is `completions: n`, the job should no longer be triggered.

### Actual Behavior

The scaledJob executes on a cron trigger. Jobs are triggered every 30 seconds until the scaledJob ends.

`spec.triggers[0].metadata.end`

In this case, the job has successfully completed. `completions: 1` is exceeded.

### Steps to Reproduce the Problem

1. Deploy a scaledjob of the form:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: scaled-job-name
  namespace: example
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  maxReplicaCount: 1
  triggers:
  - type: cron
    metadata:
      timezone: America/New_York
      start: 54 13 * * *
      end: 59 13 * * *
      desiredReplicas: "1"
  jobTargetRef:
    parallelism: 1
    completions: 1
    backoffLimit: 3
    activeDeadlineSeconds: 3600
    template:
      spec:
        restartPolicy: OnFailure
        serviceAccountName: example-account
        containers:
        - name: example-curl
          image: curlimages/curl:7.77.0
          args:
          - "-s"
          - "-XPOST"
          - "-H"
          - "Content-Type: application/json"
          - "http://username:password@target-host:9099/path"
          - "--max-time"
          - "10.0"
```
2. Wait until the scaled job schedule executes. The job will execute every 30 seconds.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.2.0

### Kubernetes Version

1.18

### Platform

Amazon Web Services
