### ISSUE TITLE
staefulset not scaled 

### ISSUE THREAD

**Issue by avdhoot** [kedacore/keda#1940]
### Report

keda not able to scale StatefulSet even triggers condition meet. Check attached screen shot where threshold beyond the trigger(75) in keda metrics but StatefulSet not have scaled  .

![image](https://user-images.githubusercontent.com/1314627/124735641-da13f800-df33-11eb-9bcc-e67cf7831a60.png)


### Expected Behavior

After crossing threshold StatefulSet should have scaled.   

### Actual Behavior

After crossing threshold StatefulSet not scaled.   

### Steps to Reproduce the Problem

1.
2.
3.


### Logs from KEDA operator

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fluentd-logs
  namespace: fluent
spec:
  scaleTargetRef:
    name: fluentd-logs
    kind: StatefulSet
  pollingInterval: 30
  minReplicaCount: 2
  maxReplicaCount: 10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          policies:
          - periodSeconds: 60
            type: Pods
            value: 1
        scaleDown:
          stabilizationWindowSeconds: 900
          policies:
          - periodSeconds: 300
            type: Pods
            value: 1
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-infra.prometheus.svc.cluster.local:9090
      metricName: (namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate
      query:  avg(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace="fluent", container_name="fluentd"}) * 100
      threshold: '75
```
```
Name:                                                                                                                                                                                                                             keda-hpa-fluentd-logs
Namespace:                                                                                                                                                                                                                        fluent
Labels:                                                                                                                                                                                                                           app.kubernetes.io/managed-by=keda-operator
                                                                                                                                                                                                                                  app.kubernetes.io/name=keda-hpa-fluentd-logs
                                                                                                                                                                                                                                  app.kubernetes.io/part-of=fluentd-logs
                                                                                                                                                                                                                                  app.kubernetes.io/version=2.2.0
                                                                                                                                                                                                                                  scaledObjectName=fluentd-logs
Annotations:                                                                                                                                                                                                                      <none>
CreationTimestamp:                                                                                                                                                                                                                Wed, 07 Jul 2021 14:44:08 +0530
Reference:                                                                                                                                                                                                                        StatefulSet/fluentd-logs
Metrics:                                                                                                                                                                                                                          ( current / target )
  "prometheus-http---prometheus-infra-prometheus-svc-cluster-local-9090-(namespace_pod_name_container_name-container_cpu_usage_seconds_total-sum_rate{namespace=\"fluent\", container_name=\"fluentd\"}" (target average value):  46 / 75
Min replicas:                                                                                                                                                                                                                     2
Max replicas:                                                                                                                                                                                                                     10
Behavior:
  Scale Up:
    Stabilization Window: 0 seconds
    Select Policy: Max
    Policies:
      - Type: Pods  Value: 1  Period: 60 seconds
  Scale Down:
    Stabilization Window: 900 seconds
    Select Policy: Max
    Policies:
      - Type: Pods  Value: 1  Period: 300 seconds
StatefulSet pods:   2 current / 2 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from external metric prometheus-http---prometheus-infra-prometheus-svc-cluster-local-9090-(namespace_pod_name_container_name-container_cpu_usage_seconds_total-sum_rate{namespace="fluent", container_name="fluentd"}(&LabelSelector{MatchLabels:map[string]string{scaledObjectName: fluentd-logs,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:           <none>

```

### KEDA Version

2.2.0

### Kubernetes Version

1.19

### Platform

Amazon Web Services

### Scaler Details

prometheus

### Anything else?

_No response_
