### ISSUE TITLE
Multiple pods spin up for ActiveMQ Artemis Scalar

### ISSUE THREAD

**Issue by amitherlekar** [kedacore/keda#1964]
### Report

The issue is already reported for Azure Storage Queue. I am facing the same issue for ActiveMQ Artemis scalar with `ScaledJob`.

It is clearly explained here: https://github.com/kedacore/keda/issues/525#issuecomment-576249275

### Expected Behavior

I expected KEDA to trigger only once per message added to the queue, resulting in 1 pod per message.

### Actual Behavior

Currently, KEDA spawns a pod each time the pollingInterval has passed. This results in pods being spawned every minute until the maxReplicaCount has been reached. Next to that, due to Artemis autoscaling feature, additional nodes will be provisioned to handle the extra pods.

### Steps to Reproduce the Problem

```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: orchestrator-job
spec:
  triggers:
    - type: artemis-queue
      metadata:
        managementEndpoint: "activemq-svc.default.svc.cluster.local:8161"
        queueName: "orchestrator"
        queueLength: "1"
        brokerName: "amq"
        brokerAddress: "orchestrator"
      authenticationRef:
        name: trigger-auth-amq-artemis
  pollingInterval: 5
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10
  jobTargetRef:
    parallelism: 1
    completions: 1
    template:
      spec:
          securityContext:
            runAsUser: 2000
            fsGroup: 2000
            runAsNonRoot: false
          containers:
           - name: orchestrator
             image: orchestrator:1.0
             imagePullPolicy: IfNotPresent
             resources:
                limits:
                  cpu: "1"
                  memory: 300Mi
                requests:
                  cpu: "0.3"
                  memory: 256Mi
             volumeMounts:
              - name: ssl-vol
                mountPath: "/certs"
                readOnly: true
             env:
               - name: PYTHONUNBUFFERED
                 value: "1"
               - name: AMQ_BROKER_ADDRESS
                 valueFrom:
                   configMapKeyRef:
                     name: amq-config
                     key: activemq_address
               - name: AMQ_BROKER_PORT
                 valueFrom:
                   configMapKeyRef:
                     name: amq-config
                     key: activemq_port
               - name: AMQ_BROKER_USERNAME
                 valueFrom:
                   secretKeyRef:
                     name: amq-creds
                     key: activemq_username
               - name: AMQ_BROKER_PASSWORD
                 valueFrom:
                   secretKeyRef:
                     name: amq-creds
                     key: activemq_password
          restartPolicy: Never
          volumes:
           - name: ssl-vol
             secret:
               secretName: amq-client-cert
    backoffLimit: 4

```

### Logs from KEDA operator

```
example
```

### KEDA Version

2.3.0

### Kubernetes Version

1.20

### Platform

Any

### Scaler Details

ActiveMQ Artemis

**Comment by zroubalik** [comment]
@TsuyoshiUshio FYI

**Comment by TsuyoshiUshio** [comment]
Hi @amitherlekar 
According to your definition file, you don't use scaling strategy. I don't know about ActiveMQ Artemis, however, if the behavior of the queue length is the same as Azure Storage Queue, we can use `accurate` strategy. Could you try it and share the result? If not, we need more investigation for the behavior of the ActiveMQ Artemis.

https://keda.sh/docs/2.3/concepts/scaling-jobs/

**Comment by amitherlekar** [comment]
Thank you for your response, @TsuyoshiUshio . I tried as you requested. I added `accurate` strategy in the manifest. Then I posted 1 message via ActiveMQ console.  This job takes about 20 seconds to process 1 message. By then I see multiple pods spin up. And from the logs I see multiple pods processing the same message.

Updated manifest.
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: orchestrator-job
spec:
  triggers:
    - type: artemis-queue
      metadata:
        managementEndpoint: "activemq-svc.default.svc.cluster.local:8161"
        queueName: "orchestrator"
        queueLength: "1"
        brokerName: "ROAD"
        brokerAddress: "orchestrator"
      authenticationRef:
        name: amq-trigger-auth
  pollingInterval: 5
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10
  scalingStrategy:
    strategy: "accurate"
  jobTargetRef:
    parallelism: 1
    completions: 1
    template:
      spec:
          securityContext:
            runAsUser: 2002
            fsGroup: 2002
            runAsNonRoot: false
          containers:
           - name: orchestrator
             image: orchestrator:1.0
             imagePullPolicy: IfNotPresent
             resources:
                limits:
                  cpu: "1"
                  memory: 300Mi
                requests:
                  cpu: "0.3"
                  memory: 256Mi
             volumeMounts:
              - name: ssl-vol
                mountPath: "/certs"
                readOnly: true
             env:
               - name: PYTHONUNBUFFERED
                 value: "1"
               - name: AMQ_BROKER_ADDRESS
                 valueFrom:
                   configMapKeyRef:
                     name: amq-config
                     key: activemq_address
               - name: AMQ_BROKER_PORT
                 valueFrom:
                   configMapKeyRef:
                     name: amq-config
                     key: activemq_port
               - name: AMQ_BROKER_USERNAME
                 valueFrom:
                   secretKeyRef:
                     name: amq-creds
                     key: activemq_username
               - name: AMQ_BROKER_PASSWORD
                 valueFrom:
                   secretKeyRef:
                     name: amq-creds
                     key: activemq_password
          restartPolicy: Never
          volumes:
           - name: ssl-vol
             secret:
               secretName: amq-client-cert
    backoffLimit: 4
```

Pods spinning up...

```shell
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS              RESTARTS   AGE
activemq-0                     1/1     Running             0          30h
orchestrator-job-g4jp8-hsdrg   0/1     ContainerCreating   0          0s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS              RESTARTS   AGE
activemq-0                     1/1     Running             0          30h
orchestrator-job-g4jp8-hsdrg   0/1     ContainerCreating   0          2s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS    RESTARTS   AGE
activemq-0                     1/1     Running   0          30h
orchestrator-job-g4jp8-hsdrg   1/1     Running   0          4s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS              RESTARTS   AGE
activemq-0                     1/1     Running             0          30h
orchestrator-job-g4jp8-hsdrg   1/1     Running             0          6s
orchestrator-job-gjpdj-cwr9g   0/1     ContainerCreating   0          1s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS    RESTARTS   AGE
activemq-0                     1/1     Running   0          30h
orchestrator-job-g4jp8-hsdrg   1/1     Running   0          8s
orchestrator-job-gjpdj-cwr9g   1/1     Running   0          3s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS    RESTARTS   AGE
activemq-0                     1/1     Running   0          30h
orchestrator-job-g4jp8-hsdrg   1/1     Running   0          10s
orchestrator-job-gjpdj-cwr9g   1/1     Running   0          5s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS    RESTARTS   AGE
activemq-0                     1/1     Running   0          30h
orchestrator-job-g4jp8-hsdrg   1/1     Running   0          12s
orchestrator-job-gjpdj-cwr9g   1/1     Running   0          7s
orchestrator-job-kp6xm-d7mdh   1/1     Running   0          2s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS    RESTARTS   AGE
activemq-0                     1/1     Running   0          30h
orchestrator-job-g4jp8-hsdrg   1/1     Running   0          13s
orchestrator-job-gjpdj-cwr9g   1/1     Running   0          8s
orchestrator-job-kp6xm-d7mdh   1/1     Running   0          3s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS    RESTARTS   AGE
activemq-0                     1/1     Running   0          30h
orchestrator-job-g4jp8-hsdrg   1/1     Running   0          15s
orchestrator-job-gjpdj-cwr9g   1/1     Running   0          10s
orchestrator-job-kp6xm-d7mdh   1/1     Running   0          5s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS    RESTARTS   AGE
orchestrator-job-vvqzk-zbjgb   0/1     Pending   0          3s
activemq-0                     1/1     Running   0          30h
orchestrator-job-g4jp8-hsdrg   1/1     Running   0          18s
orchestrator-job-gjpdj-cwr9g   1/1     Running   0          13s
orchestrator-job-kp6xm-d7mdh   1/1     Running   0          8s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS    RESTARTS   AGE
orchestrator-job-vvqzk-zbjgb   0/1     Pending   0          5s
activemq-0                     1/1     Running   0          30h
orchestrator-job-g4jp8-hsdrg   1/1     Running   0          20s
orchestrator-job-gjpdj-cwr9g   1/1     Running   0          15s
orchestrator-job-kp6xm-d7mdh   1/1     Running   0          10s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS    RESTARTS   AGE
orchestrator-job-vvqzk-zbjgb   0/1     Pending   0          7s
activemq-0                     1/1     Running   0          30h
orchestrator-job-g4jp8-hsdrg   1/1     Running   0          22s
orchestrator-job-gjpdj-cwr9g   1/1     Running   0          17s
orchestrator-job-kp6xm-d7mdh   1/1     Running   0          12s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS      RESTARTS   AGE
orchestrator-job-xmw4h-bft2l   0/1     Pending     0          12s
activemq-0                     1/1     Running     0          30h
orchestrator-job-g4jp8-hsdrg   0/1     Completed   0          37s
orchestrator-job-gjpdj-cwr9g   1/1     Running     0          32s
orchestrator-job-kp6xm-d7mdh   1/1     Running     0          27s
orchestrator-job-vvqzk-zbjgb   1/1     Running     0          22s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS      RESTARTS   AGE
orchestrator-job-tcfgn-r6wml   0/1     Pending     0          2s
activemq-0                     1/1     Running     0          30h
orchestrator-job-g4jp8-hsdrg   0/1     Completed   0          57s
orchestrator-job-gjpdj-cwr9g   0/1     Completed   0          52s
orchestrator-job-kp6xm-d7mdh   0/1     Completed   0          47s
orchestrator-job-vvqzk-zbjgb   0/1     Completed   0          42s
orchestrator-job-xmw4h-bft2l   1/1     Running     0          32s
orchestrator-job-kdth5-pb55p   1/1     Running     0          12s
orchestrator-job-sxj45-qwn6g   1/1     Running     0          7s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS      RESTARTS   AGE
orchestrator-job-fdrp8-mrmxc   0/1     Pending     0          4s
activemq-0                     1/1     Running     0          30h
orchestrator-job-xmw4h-bft2l   0/1     Completed   0          90s
orchestrator-job-kdth5-pb55p   0/1     Completed   0          70s
orchestrator-job-sxj45-qwn6g   0/1     Completed   0          65s
orchestrator-job-tcfgn-r6wml   0/1     Completed   0          60s
orchestrator-job-sqlck-sw5kr   0/1     Completed   0          44s
orchestrator-job-jtpl4-wxrnm   1/1     Running     0          24s
orchestrator-job-gjbmf-v99wp   1/1     Running     0          19s
orchestrator-job-2s288-v9rpp   1/1     Running     0          14s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS      RESTARTS   AGE
activemq-0                     1/1     Running     0          30h
orchestrator-job-kdth5-pb55p   0/1     Completed   0          84s
orchestrator-job-sxj45-qwn6g   0/1     Completed   0          79s
orchestrator-job-tcfgn-r6wml   0/1     Completed   0          74s
orchestrator-job-sqlck-sw5kr   0/1     Completed   0          58s
orchestrator-job-jtpl4-wxrnm   0/1     Completed   0          38s
orchestrator-job-gjbmf-v99wp   0/1     Completed   0          33s
orchestrator-job-2s288-v9rpp   1/1     Running     0          28s
orchestrator-job-fdrp8-mrmxc   1/1     Running     0          18s
[rouser@centralsystem analysis]$ minikube kubectl -- get pods --sort-by=.status.startTime
NAME                           READY   STATUS      RESTARTS   AGE
activemq-0                     1/1     Running     0          30h
orchestrator-job-sqlck-sw5kr   0/1     Completed   0          4m47s
orchestrator-job-jtpl4-wxrnm   0/1     Completed   0          4m27s
orchestrator-job-gjbmf-v99wp   0/1     Completed   0          4m22s
orchestrator-job-2s288-v9rpp   0/1     Completed   0          4m17s
orchestrator-job-fdrp8-mrmxc   0/1     Completed   0          4m7s
[rouser@centralsystem analysis]$
```

If there anything you want me to try, please let me know.
