### ISSUE TITLE
Problem with fetching Azure custom metric through Azure Monitor scaler

### ISSUE THREAD

**Issue by dymitrs** [kedacore/keda#1965]
### Discussed in https://github.com/kedacore/keda/discussions/1946

<div type='discussions-op-text'>

<sup>Originally posted by **dymitrs** July 10, 2021</sup>
Hi all, 
It seems that the Monitor scaler does not work with some custom metrics from Application Insights.
According to docs and the PR, Custom Metrics are supported after those changes https://github.com/kedacore/keda/pull/1883.

```
  triggers:
  - type: azure-monitor
    metadata:
      resourceURI: Microsoft.Insights/Components/app-insights
      subscriptionId: <...>
      tenantId: <...>
      resourceGroupName: <...>
      metricName: customMetrics/<metric name>
      metricNamespace: azure.applicationinsights
      metricAggregationInterval: "0:3:0"
      metricAggregationType: Count
      targetValue: "{{ .Values.scale_settings.target_value }}"
```
      
The autoscaler works fine for "default" metrics but for my custom one I'm getting this error and it fails - log from Keda operator pod:

```
ERROR   azure_monitor_scaler    error getting azure monitor metric      {"error": "error getting azure monitor metric customMetrics/<metric name>: got metric result for Microsoft.Insights/customMet
rics/<metric name> and aggregate type COUNT without timeseries"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).isScaledObjectActive
        /workspace/pkg/scaling/scale_handler.go:216
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
```
</div>

**Expected behavior:** 
Metrics are read from Azure.

**Actual behavior:**
Error getting metric.

**Steps to reproduce:**
1. Setup Monitor scaler.
2. Fetch custom metrics from Application Insights.

**KEDA Version:**
2.3.0
