### ISSUE TITLE
ScaledObject is not honoring the resource quota

### ISSUE THREAD

**Issue by endejoli** [kedacore/keda#1979]
### Report

I have the below resource quota configured in my project
```
kind: ResourceQuota
apiVersion: v1
metadata:
  name: dev-quota
  labels:
    quota-tier: Small
spec:
  hard:
    count/scaledjob.keda.sh: '1'
    count/scaledobject.keda.sh: '1'
```
But I am still able to create more than 1 scaledobject resource

```
oc get scaledobject
NAME                      SCALETARGETKIND   SCALETARGETNAME   MIN   MAX   TRIGGERS   AUTHENTICATION   READY   ACTIVE    AGE
mysql-scaledobject                          keda-example            4     mysql                       False   Unknown   2m16s
mysql-scaledobject-new1                     keda-example            4     mysql                       False   Unknown   5m10s
```

### Expected Behavior

Since quota defines the count as 1, it should not allow to create second scaledobject

### Actual Behavior

Able to create more than one scaledobject

### Steps to Reproduce the Problem

1. define the quota with above yaml
2. create multiple scaledobjects
3.

### Logs from KEDA operator

```

```

### KEDA Version

2.3.0

### Kubernetes Version

1.18

### Platform

Red Hat OpenShift
