### ISSUE TITLE
[Kafka Scaler] Kafka SASL SCRAM auth seems to not work with AWS MSK

### ISSUE THREAD

**Issue by dipen-epi** [kedacore/keda#1989]
### Report

When trying to authenticate with AWS Managed Streaming for Kafka secured with `SASL_SCRAM_512` authentication KEDA ScaledObject seems unable to communicate with cluster and gives the following error

```
{"ScaledObject.Namespace": "keda", "ScaledObject.Name": "kafka-scaledobject", "error": "error getting scaler for trigger #0: error creating kafka client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"}
```

Tried using KEDA version `1.4` and `2.3.0`.

### Expected Behavior

KEDA should be able to create a new ScaledObject Custom Resource and subsequently a HPA for scaling the target Deployment

### Actual Behavior

K8s cannot create the ScaledObject CR.

### Steps to Reproduce the Problem

1. Kafka Secrets and TriggerAuthentication manifest

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: default
data:
  sasl: ""
  username: ""
  password: ""
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: default
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-secrets
    key: sasl
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: keda-kafka-secrets
    key: password
```
2. ScaledObject manifest
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-msk-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-consumer
    # Required Name of the deployment we want to scale.
  pollingInterval: 10
  minReplicaCount: 0   #Optional Default 0
  maxReplicaCount: 10  #Optional Default 100
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: b-1.xxx.kafka.us-east-1.amazonaws.com:9096,b-2.xxx.kafka.us-east-1.amazonaws.com:9096,b-3.xxx.kafka.us-east-1.amazonaws.com:9096
      consumerGroup: keda_scaling_topic_group
      topic: keda_scaling_topic
      lagThreshold: "30" 
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
```

### Logs from KEDA operator

```
{"ScaledObject.Namespace": "keda", "ScaledObject.Name": "kafka-scaledobject", "error": "error getting scaler for trigger #0: error creating kafka client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"}
```

### KEDA Version

2.3.0

### Kubernetes Version

1.20

### Platform

Amazon Web Services

### Scaler Details

Kafka
