### ISSUE TITLE
Cron trigger does not support valid ranges

### ISSUE THREAD

**Issue by jyaworski** [kedacore/keda#2034]
### Report

Hello:

The fix for #1809 appears to have broken our cron setup. Checking for `-` removes some valid cron entries.

### Expected Behavior

Using the following, I would expect it to scale to 5 replicas in January, October, November, and December from 8:30 AM to 1:00 PM in the America/New_York TZ:

```
  - metadata:
      desiredReplicas: "5"
      end: 0 13 * 1,10-12 *
      start: 30 8 * 1,10-12 *
      timezone: America/New_York
    type: cron
```

### Actual Behavior

```
Warning  KEDAScalerFailed         10m (x504 over 42h)  keda-operator  error parsing cron metadata: error parsing start schedule. map[desiredReplicas:5 end:0 13 * 1,10-12 * start:30 8 * 1,10-12 * timezone:America/New_York]: range or hyphenated inputs are not allowed
```

### Steps to Reproduce the Problem

Apply any cron trigger with a range.

### KEDA Version

2.4.0

### Platform

Amazon Web Services

### Scaler Details

Cron
