### ISSUE TITLE
Add support to specify custom http timeout only for RabbitMQ Scaler

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#2053]
### Proposal

My proposal is to add the support to specify a specific timeout to use for each trigger when you are using RabbitMQ Scaler.
It could be something like this:
```yaml
triggers:
- type: rabbitmq
  metadata:
    host: amqp://localhost:5672/vhost # Optional. If not specified, it must be done by using TriggerAuthentication.
    ...
    httpTimeout: 10000 
```
In cases where it's not defined, `KEDA_HTTP_DEFAULT_TIMEOUT` should be used

### Use-Case

When you are using http protocol with regex, it could need more time than `KEDA_HTTP_DEFAULT_TIMEOUT` to get the response. It's possible to customize the timeout but only as a global customization. This could be enough in some cases but if you are using KEDA in several not related workloads, this could be a problem.

In our use case, our production RabbitMQ cluster has more than 1k queues, and it needs 5-10 in some cases to response with the queues which match the regex. If we want to use other scale, we would like to avoid having 15-30sec (arbitrary value) in other scalers which uses HTTP protocol

### Anything else?

I can do it :)
