### ISSUE TITLE
ScaledObject status Unknown

### ISSUE THREAD

**Issue by silasfrigo** [kedacore/keda#2101]
### Report

Our scaledObject status shows unknow
![image](https://user-images.githubusercontent.com/47428195/133782601-5fa35113-29fc-4bb9-b23b-c7490431a9da.png)
n

And keda logs shows the following:
```
{
   "ScaledObject.Namespace":"channels-integrations",
   "ScaledObject.Name":"ch-int-mercadolivre-orders-inbound-scaledobject",
   "error":"error getting scaler for trigger #0: error creating kafka client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"
}
``` 

### Expected Behavior

ScaledObject to show status and complete hpa creation.

### Actual Behavior

Status stays in unknown.

### Steps to Reproduce the Problem

1. Keda version 2.4
2. Create a TriggerAuthentication and a ScaledObject file
3. Deploy and apply changes.

### Logs from KEDA operator

```
{
   "ScaledObject.Namespace":"channels-integrations",
   "ScaledObject.Name":"ch-int-mercadolivre-orders-inbound-scaledobject",
   "error":"error getting scaler for trigger #0: error creating kafka client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"
}
```

### KEDA Version

2.4.0

### Platform

Other

### Scaler Details

Kafka

### Anything else?

We are using confluent cloud. 

Keda operator logs:
```
{
   "ScaledObject.Namespace":"channels-integrations",
   "ScaledObject.Name":"ch-int-mercadolivre-orders-inbound-scaledobject",
   "error":"error getting scaler for trigger #0: error creating kafka client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"
}
```

And ScaledObject  status show 'Unknown' state.
![image](https://user-images.githubusercontent.com/47428195/133780988-97513dac-78f4-4468-b84b-0253c07e1255.png)

keda version 2.4

```
apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: my-namespace
data:
  sasl: "plaintext as b64"
  username: "username as b64"
  password: "password as b64"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: my-namespace
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-secrets
    key: sasl
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: keda-kafka-secrets
    key: password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-scaled-object-name
  namespace: my-namespace
spec:
  scaleTargetRef:
    name: my-deployment-name
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 3
  pollingInterval: 10
  triggers:
  - type: kafka
    metadata:
      metricName: my-metric-name
      namespace: my-namespace
      bootstrapServers: our-broker-address.confluent.cloud:9092
      consumerGroup: consumer_group
      topic: my_topic
      lagThreshold: "10"
      offsetResetPolicy: earliest
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
```
