### ISSUE TITLE
Using 'Value' in CPU scaler results in an error (must set either a target raw value or a target utilization)

### ISSUE THREAD

**Issue by yogevyuval** [kedacore/keda#2200]
### Report

When using 'Value' in the CPU scaler (in addition to SQS scaler), the keda hpa can't be intiailized, and logs show error in K8s hpa. When switching back to "Utilization" instead of "Value" this seems to work, but it doesn't suit my usecase.

My configuration is as follows:
```
Spec:
  Cooldown Period:    60
  Max Replica Count:  2
  Min Replica Count:  0
  Polling Interval:   30
  Scale Target Ref:
    Name:  indexer
  Triggers:
    Metadata:
      Aws Region:      us-east-1
      Identity Owner:  operator
      Queue Length:    500
      Queue URL:       https://sqs.us-east-1.amazonaws.com/some-queue
    Type:              aws-sqs-queue
    Metadata:
      Type:   Value
      Value:  80
    Type:     cpu
```

And this is the outcome YAML in the HPA

```
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-a
  targetCPUUtilizationPercentage: 80
status:
  currentCPUUtilizationPercentage: 210
  currentReplicas: 2
  desiredReplicas: 2
  lastScaleTime: "2021-10-14T15:23:01Z"
```

### Expected Behavior

The autoscaler should have been created with the "Value" target

### Actual Behavior

The hpa fails to initialize / update

### Steps to Reproduce the Problem

1. Create an autoscaler with the attached config
2. Helm install
3. Check if HPA is created

### Logs from KEDA operator

```
ERROR controllers.ScaledObjebt Failed to update HPA {"ScaledObject.Namespace": "keda", "ScaledObject.Name": "service-a", "HPA.Namespace": "keda", "HPA.Name": "keda-hpa-service-a"}"

spec.metrics[0].resource.target.averageUtilization: Required value: must set either a target raw value or a target utilization].
```

### KEDA Version

2.4.0

### Kubernetes Version

1.20

### Platform

Amazon Web Services
