### ISSUE TITLE
AWS Cloudwatch autoscaler giving invalid value suffixed with m in the targets of the HorizontalPodAutoScaler

### ISSUE THREAD

**Issue by jeroenvandevelde** [kedacore/keda#2210]
### Report

CloudWatch Autoscaler giving sometimes value suffixed with m in the Targets when using ApproximateNumberOfMessagesVisible.
M suffixed Value: 102500m/100 (avg)
While it should be: 205/100

### Expected Behavior

When i do a kubectl get on the created HorizontalPodAutoscaler, i get the actual value not suffixed with m.
Example: 205/300 (avg)

### Actual Behavior

When i do a kubectl get on the created HorizontalPodAutoscaler, i get a value suffixed with m.
Example: 256250m/300 (avg)

### Steps to Reproduce the Problem

1. Deploy a KEDA 2.4.0 on EKS
2. Apply a cloudwatch Scaler

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-cloudwatch-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: deployment-name
  pollingInterval: 10  # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 2   # Optional. Default: 0
  maxReplicaCount: 5 # Optional. Default: 100
  triggers:
    - type: aws-cloudwatch
      metadata:
        namespace: AWS/SQS
        dimensionName: QueueName
        dimensionValue: "actual name of the queue"
        metricName: ApproximateNumberOfMessagesVisible
        awsRegion: "eu-west-1"
        targetMetricValue: "100"
        minMetricValue: "0"
        metricStatPeriod: "60"
        identityOwner: operator
        metricStat: "Sum"
```
3. Do a kubectl get HorizontalPodAutoscaler
4. Take a look at the value in Targets

### KEDA Version

2.4.0

### Kubernetes Version

1.17

### Platform

Amazon Web Services

### Scaler Details

Cloudwatch Scaler

### Anything else?

After a while it is mostly fixed.
If i wait long enough the value in the Targets of the HorizontalPodAutoScaler goes back to its normal value without m.
