### ISSUE TITLE
Google pubsub custom metrics support

### ISSUE THREAD

**Issue by Friedrich42** [kedacore/keda#2226]
### Proposal

As a devops, I want to be able to add custom metrics to my scaledobject like "Oldest unacked message age", which are provided by GCP metrics (stackdriver). The only trigger I can use now is subscriptionSize which is "Unacked message count" in GCP.

### Use-Case

I want to scale my deployment if there are a lot of delays in message processing.

**Comment by tomkerkhove** [comment]
Good suggestion, are you willing to contribute this?

**Comment by Friedrich42** [comment]
Yep, but I'll need some support to understand the project structure

**Comment by zroubalik** [comment]
@Friedrich42 you can check the source code https://github.com/kedacore/keda/blob/cabe4b5132a64d1eff1cecc35dc0c5d701cedc06/pkg/scalers/gcp_pub_sub_scaler.go#L156 

guides:
https://github.com/kedacore/keda/blob/main/CREATE-NEW-SCALER.md
https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md
https://github.com/kedacore/keda/blob/main/BUILD.md

or feel free to ask on `#keda` or `#keda-dev` Slack channel on https://slack.k8s.io/

**Comment by Friedrich42** [comment]
I think that there should be new parameter in metadata object named oldestUnackedMessageAge.

I wonder if it should be optional or required? Making it required seems unreasonable, because scaler object works without it as well, but what should the validation rules be if it will be optional? Should subscriptionSize be also optional, so user can select which metrics he needs for scaling?

Is there another scaler with several metrics, so I can take a look at it?

**Comment by zroubalik** [comment]
https://keda.sh/docs/2.4/scalers/rabbitmq-queue/ has 2 modes.

In this case we can make it optional, but then validate that user specified at least one of the metrics.  Do you think draft here how would the triggers spec look like and we can discuss on that?

**Comment by Friedrich42** [comment]
I think this should be ok enough

```yaml
triggers:
- type: gcp-pubsub
  metadata:
    subscriptionSize: "5" # Optional - Default is 5
    subscriptionName: "mysubscription" # Required
    credentialsFromEnv: GOOGLE_APPLICATION_CREDENTIALS_JSON # Required
```

**Comment by zroubalik** [comment]
@tomkerkhove WDYT?

**Comment by zroubalik** [comment]
@Friedrich42 or we can allow only one of the metrics to be specified in the spec. And if users would like to scale on both of them, they can define multiple triggers in the ScaledObject.

**Comment by tomkerkhove** [comment]
I like that proposal, for the rest it looks fine to me

**Comment by Friedrich42** [comment]
@zroubalik So I propose we do the same thing as in rabbitmq and we have mode field. Should look like this =>
```yaml
triggers:
- type: gcp-pubsub
  metadata:
    mode: "SubscriptionSize" # Required - either SubscriptionSize or OldestUnackedMessageAge
    subscriptionSize: "5" # Optional (active if mode is SubscriptionSize) - Default is 5
    oldestUnackedMessageAge: "1" # Optional (active if mode is OldestUnackedMessageAge) - Default is 10 (seconds)
    subscriptionName: "mysubscription" # Required
    credentialsFromEnv: GOOGLE_APPLICATION_CREDENTIALS_JSON # Required
```
