### ISSUE TITLE
keda conflict with ambassador

### ISSUE THREAD

**Issue by aminebizid** [kedacore/keda#225]
After installing Keda, [Ambassador](https://github.com/datawire/ambassador?files=1) stop working.
The issue is cauded by **v1beta1.custom.metrics.k8s.io**
```yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: {{ template "keda.fullname" . }}
    namespace: {{ .Release.Namespace }}
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```

as workaround to let ambassador works:
```bash
k -n keda delete apiservice v1beta1.custom.metrics.k8s.io
```

Why do we need custom.metrics in keda?
