### ISSUE TITLE
Rabbitmq Scaler with HashicorpVault TriggerAuth HPA no host setting given

### ISSUE THREAD

**Issue by seuf** [kedacore/keda#2254]
### Report

Hi,
I'm trying to configure keda to scale my deployment according to my rabbitmq queue length.

But the hpa created by keda is not working :
```
unable to get external metric apps/s0-rabbitmq-company-queue/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: my-application,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: error when getting scalers error getting scaler for trigger #0: error parsing rabbitmq metadata: no host setting given
```

I think there is a bug during TriggerAuth parameters merging with rabbitmq metdata config.

### Expected Behavior

Hpa using configred host from Trigger Auth

### Actual Behavior

Hpa metrics error :
```
 unable to fetch metrics from external metrics API: error when getting scalers error getting scaler for trigger #0: error parsing rabbitmq metadata: no host setting given
 ```

### Steps to Reproduce the Problem

I've configured a TriggerAuth like this  (tested with a ClusterTriggerAuthentication without success) :
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq
  namespace: default
spec:
  hashiCorpVault:
    address: https://vault.vault.svc:8200
    authentication: kubernetes
    role: keda
    mount: kubernetes
    credential:
      serviceAccount: /var/run/secrets/kubernetes.io/serviceaccount/token
    secrets:
    - parameter: host
      key: host
      path: /kv/data/rabbitmq/secret
```
and a Scaled object 
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-application
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-application
    envSourceContainerName: app-container
  pollingInterval: 60
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 5
  fallback:
    failureThreshold: 3
    replicas: 1
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      mode: QueueLength # QueueLength or MessageRate
      value: "100" # message backlog or publish/sec. target per instance
      queueName: company.queue
    authenticationRef:
      name: keda-trigger-auth-rabbitmq
```

### Logs from KEDA operator

I can see that keda is well connecting to my vault and fetching the secret 
```
2021-11-04T16:12:51.554Z	INFO	controllers.ScaledObject	Reconciling ScaledObject	{"ScaledObject.Namespace": "apps", "ScaledObject.Name": "my-application"}
2021-11-04T16:12:51.656Z	INFO	controllers.ScaledObject	Updated HPA according to ScaledObject	{"ScaledObject.Namespace": "apps", "ScaledObject.Name": "my-application", "HPA.Namespace": "default", "HPA.Name": "keda-hpa-my-application"}
```

### KEDA Version

2.4.0

### Kubernetes Version

1.20

### Platform

Google Cloud

### Scaler Details

Rabbitmq

### Anything else?

It works when configuring the rabbitmq host directly in the scaler config, but not when using TriggerAuth with HAshicorp Vault
