### ISSUE TITLE
RabbitMQ host secret password cannot contain '#' character

### ISSUE THREAD

**Issue by mbendtsen** [kedacore/keda#2287]
### Report

RabbitMQ password cannot contain `#` character.

### Expected Behavior

Password should be able to contain all characters supported by RabbitMQ

### Actual Behavior

The Keda scaledobject fails connecting to RabbitMQ

### Steps to Reproduce the Problem

1. Create a RabbitMQ user: monitor:password#20
2. Create a ScaledObject using an TriggerAuthentication and Secret
3. Trigger the autoscaling

``` yaml
# Source: forwarder/templates/scaler-object.yml
apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  host: YW1xcDovL21vbml0b3I6cGFzc3dvcmQjMjBAcmFiYml0bXEucmFiYml0bXEuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mi8= # amqp://monitor:password#20@rabbitmq.rabbitmq.svc.cluster.local:5672/
---  
# Source: forwarder/templates/scaler-object.yml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject-parser
  namespace: biot
spec:
  scaleTargetRef:
    name: consumer-service
  pollingInterval:  30   # Optional. Default: 30 seconds
  cooldownPeriod:   10   # Optional. Default: 300 seconds
  idleReplicaCount: 0    # Optional. Must be less than minReplicaCount
  minReplicaCount:  0    # Optional. Default: 0
  maxReplicaCount:  10   # Optional. Default: 100
  fallback:              # Optional. Section to specify fallback options
    failureThreshold: 3  # Mandatory if fallback section is included
    replicas: 3          # Mandatory if fallback section is included
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: gateway
      mode: QueueLength
      value: "1"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
---
# Source: forwarder/templates/scaler-object.yml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: biot
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
```

### Logs from KEDA operator

```
2021-11-15T14:57:19.579Z ERROR scalehandler Error getting scalers 
{
	"object": {
		"apiVersion": "keda.sh/v1alpha1",
		"kind": "ScaledObject",
		"namespace": "biot",
		"name": "rabbitmq-scaledobject-parser"
	},
	"error": "error getting scaler for trigger #0: error establishing rabbitmq connection: parse \"amqp://monitor:password\": invalid port \":password\" after host"
}
```

### KEDA Version

2.4.0

### Kubernetes Version

1.22

### Platform

Microsoft Azure

### Scaler Details

RabbitMQ
