### ISSUE TITLE
Provide an OpenTelemetry scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2353]
### Proposal

OpenTelemetry allows applications/vendors to push metrics to a collector or integrate it's own exporters in the app.

KEDA should provide an OpenTelemetry scaler which is used as an [exporter](https://opentelemetry.io/docs/collector/configuration/#exporters) so we can pull metrics and scale accordingly.

### Scaler Source

OpenTelemetry Metrics

### Scaling Mechanics

Scale based on returned metrics.

### Authentication Source

TBD

### Anything else?

OpenTelemetry Metrics are still in beta but going GA by end of the year.

Go SDK: https://github.com/open-telemetry/opentelemetry-go

**Comment by mknet3** [comment]
It's a really good improvement, I will have a look to see if I can help with this topic 🙂

**Comment by tomkerkhove** [comment]
Awesome, thank you!

**Comment by JorTurFer** [comment]
@mknet3 , ping me if you need help ;)

**Comment by mknet3** [comment]
just to confirm, I'm on it and I will help with this scaler

**Comment by tomkerkhove** [comment]
Great, thanks!

**Comment by mknet3** [comment]
Hi @tomkerkhove, I have had a look at this issue and I would like to clarify some things. AFAIK the goal of this issue is to provide an scaler based on metrics exported by an exporter configured in the collector. This exporter will expose metrics in a KEDA format to be read by the scaler. Quick question, does the exporter already exist or is there a plan to develop it? (I suppose will be in [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter)). This question is to figure out what will be the format of the exposed data to pull it in the scaler.

**Comment by tomkerkhove** [comment]
That would be part of the investigation but I think we'll need to build our own exporter to get the metrics in; or use the [gRPC OTEL exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter) / [HTTP OTEL exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter) as a starting point to push it to KEDA.

I'd prefer the latter approach to get started as we don't have a preference on the metric format, so OTEL is fine.

**Comment by JorTurFer** [comment]
@mknet3 prefer to keep it free for the moment because it's his first task with golang

**Comment by SushmithaVReddy** [comment]
Working on this

**Comment by tomkerkhove** [comment]
Before we go all in, might be good to post a proposal here @SushmithaVReddy to avoid having to redo things but think relying on OTEL exporter is best

**Comment by SushmithaVReddy** [comment]
@tomkerkhove Will KEDA be acting as a collector that gets metrics data from an exporter? Is the idea to create metrics using https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument and observe through hpa to scale accordingly? Slightly confused on the term exporter and collector w.r.t KEDA. Plausible solution looks like one where user has an exporter and exports metrics, keda connects to this exporter and gets metrics (collector?) for scaling decision based on the same metrics being mentioned in scaled object.

**Comment by SushmithaVReddy** [comment]
> Before we go all in, might be good to post a proposal here @SushmithaVReddy to avoid having to redo things but think relying on OTEL exporter is best

@tomkerkhove any thoughts on the scaled object here(ref below). The idea is to use OTEL (https://pkg.go.dev/go.opentelemetry.io/otel) and connect to the endpoint mentioned in the scaledobject and pull the metric value and compare to the threshold to scale.

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: opentelemetry-scaledobject
  namespace: keda
  labels:
    deploymentName: dummy
spec:
  maxReplicaCount: 12
  scaleTargetRef:
    name: dummy
  triggers:
    - type: opentelemetry
      metadata:
        exporter: http://otel-collector:4317
	  metrics:
         - metricName: http_requests_total
           threshold: '100'
      authenticationRef:
        name: authdata

I was also wondering about scenario's where users want to pull multiple metrics from their application and scale based on conditions on the metrics. Eg as below

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: opentelemetry-scaledobject
  namespace: keda
  labels:
    deploymentName: dummy
spec:
  maxReplicaCount: 12
  scaleTargetRef:
    name: dummy
  triggers:
    - type: opentelemetry
      metadata:
        exporter: http://otel-collector:4317
	  metrics:
         -  metricName: http_requests_total
             threshold: '100'
	     operator: greaterthan
	  - metricName: http_timeouts
	     threshold:  '5'
             operator: lesserthan
        query: http_requests_total and http_timeouts
      authenticationRef:
        name: authdata

Any ideas on what is the scope of the scalar we'll be building in terms of multiple metrics?

**Comment by tomkerkhove** [comment]
It's ok for me to use that package since that's the official SDK - Thanks for checking.

I don't see the difference between both proposals other than one vs multiple metrics though? Can you elaborate on it?

In terms of supporting multiple metrics - I'd argue that given we support multiple triggers it might be more aligned with other scalers to only support 1 metric per trigger to keep a consistent approach in KEDA. The only consideration I would have here is performance but I think we can manage that in the implementation. Thoughts @zroubalik @JorTurFer?

Based on that we'll need to review the YAML spec but in general I think it's ok; however if we use multiple levels then I would use `exporter.url` instead of `exporter` given we might need auth in the future or similar settings.

**Comment by SushmithaVReddy** [comment]
> It's ok for me to use that package since that's the official SDK - Thanks for checking.
> 
> I don't see the difference between both proposals other than one vs multiple metrics though? **Can you elaborate on it?**
> 
> In terms of supporting multiple metrics - I'd argue that given we support multiple triggers it might be more aligned with other scalers to only support 1 metric per trigger to keep a consistent approach in KEDA. The only consideration I would have here is performance but I think we can manage that in the implementation. Thoughts @zroubalik @JorTurFer?
> 
> Based on that we'll need to review the YAML spec but in general I think it's ok; however if we use multiple levels then I would use `exporter.url` instead of `exporter` given we might need auth in the future or similar settings.

Yes @tomkerkhove the proposals point out multiple metrics usage as you understood. I agree with the consistency over other scalars we have, but I'm concerned about how much value will our scaling add considering it can scale on a single metric where open-telemetry's  is majorly used to spit a lot of metrics.  

nitpick: If we have one metric/scaled object and user wants to scale based on multiple metrics and goes ahead and creates that many scaled objects, I wonder how we handle concurrent scenarios where multiple metrics will result in scaling (over scaling? because the scaled up instances could've been reused? )

**Comment by tomkerkhove** [comment]
It would be nice to also make the protocol configurable given OTEL supports both http and gRPC

**Comment by SushmithaVReddy** [comment]
> apiVersion: keda.sh/v1alpha1
> kind: ScaledObject
> metadata:
>   name: opentelemetry-scaledobject
>   namespace: keda
>   labels:
>     deploymentName: dummy
> spec:
>   maxReplicaCount: 12
>   scaleTargetRef:
>     name: dummy
>   triggers:
>     - type: opentelemetry
>       metadata:
>         exporter: http://otel-collector:4317
> 	  metrics:
>          - metricName: http_requests_total
>            threshold: '100'
>       authenticationRef:
>         name: authdata

Right, the below one makes sense? 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: opentelemetry-scaledobject
  namespace: keda
  labels:
    deploymentName: dummy
spec:
  maxReplicaCount: 12
  scaleTargetRef:
    name: dummy
  triggers:
    - type: opentelemetry
      metadata:
        exporter:
           protocol: grpc
           url: http://otel-collector:4317
	metric:
           name: http_requests_total
           threshold: '100'
        authenticationRef:
          name: authdata
      - type: opentelemetry
          metadata:
            exporter:
               protocol: grpc
               url: http://otel-collector:4317
            metric:
               name: http_errors
               threshold: '10'
          authenticationRef:
            name: authdata
```

**Comment by zroubalik** [comment]
Yeah, this is correct. Just one thing, the `metric.name` is related to otel?

**Comment by SushmithaVReddy** [comment]
> Yeah, this is correct. Just one thing, the `metric.name` is related to otel?

metric.name will be used to pull the metric. It should match with the name user have in their instrumented application.

**Comment by tomkerkhove** [comment]
Sounds good to me.

**Comment by markallanson** [comment]
Maybe I misunderstand something about this conversation, but given all pods in a replicaset will contain an otel collector, which one would the keda autoscaler talk to in order to make the decisions?

Also, how would you apply aggregates across metric labels?

**Comment by tomkerkhove** [comment]
KEDA will not manage the OTEL collector and is something you'd need to run separately next to KEDA/in your cluster.

Does that clarify it?

**Comment by markallanson** [comment]
Sorry maybe my question was not clear enough. 

If you have 10 pods, all of which have otel sidecars running, which will keda talk to? If just one, it won't have enough information to base scaling decisions. If it talks to all of them then how will it generate aggregates of the data across all?

**Comment by tomkerkhove** [comment]
There is no sidecar involved, there will be a separate deployment that KEDA integrates with through a Kubernetes service. End-users will have to bring their own OpenTelemetry Collector: https://opentelemetry.io/docs/collector/deployment/

**Comment by tomkerkhove** [comment]
Any update on this @SushmithaVReddy ?

**Comment by tomkerkhove** [comment]
Apparently @SushmithaVReddy no longer has time to unassigning

**Comment by raorugan** [comment]
This scaler work is not active at the moment. We will revisit this in the future. In the mean time if anyone is interested to pick this up please notify here so we know that you are working on this. Thanks for your contributions!

**Comment by Friedrich42** [comment]
I'm willing to help with this scaler. I will read these discussions couple more times, summarize everything in one comment and then start development.

**Comment by tomkerkhove** [comment]
Awesome, thank you @Friedrich42! Just so you know, KEDA 2.9 will ship in less than a month so be aware of that if you want to have it in there but no pressure from our side as 2.10 is fine as well.

**Comment by Friedrich42** [comment]
As far as I understood, please correct me if I'm wrong, user will have to deploy otel agent in cluster and this scaler will be consumer.

Config will look something like:

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: opentelemetry-scaledobject
  namespace: keda
  labels:
    deploymentName: dummy
spec:
  maxReplicaCount: 12
  scaleTargetRef:
    name: dummy
  triggers:
    - type: opentelemetry
      metadata:
           protocol: grpc
           exporter: http://otel-collector:4317
           metric: http_requests_total
           threshold: '100'
        authenticationRef:
          name: authdata
```

Question: how will authentication object look like for this scaler? Or are all auth objects the same?

Assumption: we will use only one metric from otel for scaler, correct me if I'm wrong
