### ISSUE TITLE
KEDA creates broken HPA object for a deployment when a depending secret is not ready

### ISSUE THREAD

**Issue by fivesheep** [kedacore/keda#2393]
### Report

We are using CSI secret store provider to sync external secrets as k8s secret, then have it injected as env variables, the secret itself won't be when the first pod being created and the csi secret provider downloads the remote secret and store it as k8s secret, in between of this process, there's a gap that the POD is up, but some of the container is still waiting for the secret to be synced, however, if we have keda scaleobject ref to this deployment, the keda operator will try to resolve the env secret which is referencing a secret not yet created, and it will fail with error `error resolving secrets for ScaleTarget: ...`

however, keda control won't stop here, instead, it will just log this error, and `continue`, which ends up creating a default hpa object based on cpu, regardless what the original scaleobject was configured, even worst, when the secret was synced later on (in a couple of secs), keda won't recreate a proper scale object, deleting the HPA object itself won't help either. the only way to solve it is to delete the scaleobject and recreate it. 

more detail is also provided in https://kubernetes.slack.com/archives/CKZJ36A5D/p1638919797328900

### Expected Behavior

Keda shall fail fast instead of creating a HPA which is not expected, or better, it shall be able to reconcile when the secret is ready.

### Actual Behavior

broken HPA is created, and cannot be recovered automatically

### Steps to Reproduce the Problem

1. apply the following deployment which is depending on a secrete not yet created
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        env:
          - name: INJECTED_SECRETS
            valueFrom:
              secretKeyRef: 
                name: my-test-secret
                key: data
        ports:
        - containerPort: 80
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scaledobject
spec:
  maxReplicaCount: 2
  minReplicaCount: 1
  pollingInterval: 15
  cooldownPeriod: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        metricName: nginx_http_requests_total
        threshold: '3'
        query: sum(rate(nginx_http_requests_total[2m]))
```

2. use `kubectl get scaleobject` and `kubectl get hpa` to observe the hpa spec, it's indicating a cpu based one, you might also find some error like the following from the scaleobject status: 
```
  - message: Scaling is not performed because triggers are not active
    reason: ScalerNotActive
    status: "False"
    type: Active
```

3. use `kubectl create secret generic  my-test-secret --from-literal=data=something` to create the secret that is needed by the deployment.  the deployment pod will be able to run properly in a couple of mins when it retried.

4. observe the scaleobject and hpa, they won't change

### Logs from KEDA operator

```
2021-12-07T23:08:04.757Z	ERROR	scalehandler	error resolving auth params	{"scalerIndex": 0, "object": {"apiVersion": "keda.sh/v1alpha1", "kind": "ScaledObject", "namespace": "showcase-foobar", "name": "foobar-deployment-scaledobject"}, "trigger": 0, "error": "error resolving secrets for ScaleTarget: error resolving secret name &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:foobar-backend-secret-5acc0069,},Key:data,Optional:nil,} for env INJECTED_SECRETS in namespace showcase-foobar"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs
	/workspace/controllers/keda/hpa.go:163
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:63
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:124
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:376
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:228
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:179
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227
```

### KEDA Version

2.5.0

### Kubernetes Version

1.21

### Platform

Any

### Anything else?

I am able to fix the issue by changing the `continue` to just return error from this line https://github.com/kedacore/keda/blob/main/pkg/scaling/scale_handler.go#L315
