### ISSUE TITLE
Selenium keda scaler doesn't support https for the url selenium grid graphql?

### ISSUE THREAD

**Issue by qalinn** [kedacore/keda#2419]
### Report

Hello, 

I have deployed selenium grid 4 on my eks using the k8s-deployment-full-grid.yaml file recommended on the selenium official documentation.
 I have installed keda using  the manifest and kubectl. 
I have applied the keda-scaler.yml file. 
I have two situations:
1. when I am deploying my selenium grid 4 with https(certificates), the keda scaler doesn't work properly. This means is not creating more pods if is necessary. I didn't see anything on the keda-operator pod logs.
2. when I am deploying my selenium grid 4 **without** https everything works correctly.

Do you know something about this? Do you have a workaround?

### Expected Behavior

The keda selenium scaler should work in both cases with  https (https://selenium.grid.test.com:4444/graphql) and without https(http://selenium.grid.test.com:4444/graphql).cases

### Actual Behavior

The keda selenium scaler doesn't work with  https (https://selenium.grid-test.com:4444/graphql) 

### Steps to Reproduce the Problem

1. I have deployed selenium grid 4 on my eks using the k8s-deployment-full-grid.yaml file recommended on the selenium official documentation (https://github.com/SeleniumHQ/docker-selenium#deploying-to-kubernetes).
2. I set on my selenium grid  to use https from aws:
```
#***************************************
#SELENIUM ROUTER
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-router
  namespace: selenium
  annotations:
    external-dns.alpha.kubernetes.io/hostname: selenium.grid-test.com
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:xxxxx:certificate/xxx-xxxx-xx--x-xxx
  labels:
    name: selenium-router
    component: "selenium-grid-4"
spec:
  type: LoadBalancer
  selector:
    app: selenium-router
  ports:
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444
```
 

### Logs from KEDA operator

```
example
```

### KEDA Version

2.5.0

### Kubernetes Version

1.21

### Platform

Amazon Web Services

### Scaler Details

selenium
