### ISSUE TITLE
Support custom formula for multiple metrics

### ISSUE THREAD

**Issue by or-shachar** [kedacore/keda#2440]
### Proposal

- KEDA metrics server knows how to get multiple metrics from various sources.
- Currently, the desired size computation works for each scaler individually and the final value is decided according to MAX.
- In real-world - sometimes you need to make decisions with more complex logic.

I think that a "Composed Scaler" that allows to put in a simple formula that references multiple other metrics - can be super useful.

This would make Keda a powerful tool not only for collecting external metrics but also for making smart decisions based on multiple conditions.

([discussed original here](https://github.com/kedacore/keda/discussions/2431))

### Use-Case

Here's a real-world problem: I have a backend process that consumes "write" tasks from a queue and persists them to DB. My DB has a single writer node that is CPU-bound. A task may implicit varying load on the CPU (depending on the content of the write).

I have 2 relevant metrics to determine the replica count:
```
q := queue-length
cpu := DB-writer CPU utilization
```

Composed metric formula: `ceil((1-cpu) * q)` can promise that replicas would grow if the queue is high but avoid growing if CPU is loaded. Right now the only option for me to do it is to create my own service that exposes that metric.

### Anything else?

In the [original discussion](https://github.com/kedacore/keda/discussions/2431), we started talking about how the ScaledObject spec would look like in the custom logic case.

First I suggested this:
```yaml
triggers:
  - type: composed
    metadata:
      metrics:
        q_length: 
          type: aws-cloudwatch
          metadata:
            namespace: AWS/SQS
            ... # SQS length
        cpu_util:
          type: aws-cloudwatch
          metadata:
            namespace: AWS/Neptune
            ... # neptune writer CPU
      formula: "ceil((1 - $cpu_util) * $q_length)"
      targetMetricValue: "5"
      minMetricValue: "0"

```

then @zroubalik suggested this (better IMO):
```yaml
scaledObject.spec:
  ...
  mutlipleTriggersCalculation:    ### we should find a better name for this probably
      formula: "ceil((1 - $cpu_util) * $q_length)"
      targetMetricValue: "5"
      minMetricValue: "0"
  triggers:
    - type: aws-cloudwatch
       name: q_length     ### name added here
       metadata:
            namespace: AWS/SQS
            ... # SQS length
    - type: aws-cloudwatch
       name: cpu_util       ### name added here
       metadata:
            namespace: AWS/Neptune
            ... # neptune writer CPU
```

Finally, it's valuable to read @tomkerkhove 's [comment](https://github.com/kedacore/keda/discussions/2431#discussioncomment-1905982) about it.

**Comment by dooferlad** [comment]
Having had a dig through the code, the I would be tempted by implementing this using a Go template. In pkg.provider.KedaProvider.GetExternalMetric` to a new `CalculateDerivedMetric` function that took the above scaledObject inputs would derive the right context object based on triggers and the formula field would be a template, which would be rendered using that context. Probably using https://masterminds.github.io/sprig/ so KEDA doesn't need to re-invent the wheel, you would end up with something like:

```yaml
scaledObject.spec:
  ...
  derivedMetric: # better name?
      formula: "ceil(mulf(subf(1 .cpu_util) .q_length))"
      targetMetricValue: "5"
      minMetricValue: "0"
  triggers:
    - type: aws-cloudwatch
       name: q_length
       metadata:
            namespace: AWS/SQS
            ... # SQS length
    - type: aws-cloudwatch
       name: cpu_util
       metadata:
            namespace: AWS/Neptune
            ... # neptune writer CPU
```

The implementation would be rendering that template and converting the resulting string representation into a number to send to the HPA.
