### ISSUE TITLE
CPU/Memory scalers should allow scaling to 0

### ISSUE THREAD

**Issue by loicmathieu** [kedacore/keda#2446]
### Proposal

There is legitimate use case where we want to have a CPU scaler and another one, and still want to scale to 0 (the other scaler will allow to scale back to 1).

For ex, you want to stop during closed hours your apps and want to scale based on CPU during open hours. For this you'll want to create a cron scaler and a cpu scaler.

As I understand, CPU scaler uses the default CPU autoscaling features, so scaling to 0 will means to remove the CPU condition from the HPA.

Idealy, as CPU is not a stable metric, we should be able to configure the threshold after which we decide that there is no more "traffic" on the CPU (for ex: 5%).

**Comment by tomkerkhove** [comment]
I've updated the issue name to include Memory scaler given that will be the same situation.

However, did you try doing this with the current version? In theory, if it doesn't meet your target value it should scale down to 0 but I might be wrong as it's been a while since I've used that one.

**Comment by loicmathieu** [comment]
@tomkerkhove yes, we did try it and it didn't scale to 0.
By the way, it's written in the documentation that it didn't work.

**Comment by zroubalik** [comment]
Yeah, it cannot work, because the CPU/Memory load is being calculated from the pod that the app is running, so if you have 0 replicas it can't do anything :)

@loicmathieu let's say we implement this and allow to scale to zero after some threshold (eg. the 5% you mentioned), how would the scale 0->1 work in this case?

**Comment by loicmathieu** [comment]
By another scaler, in my use case I have Kafka based scaler.
So this functionality should not be enabled by default, if you want scale to 0 and use a CPU/Mem scaler you must have another scaler and opt-in in the CPU/Mem scaler via a threshold.

Another use case is to idle you apps during closed hours, it's very convenient to save money on cloud deployment.

Why I think it's important is also that CPU/Mem scaler are "low level" scaler handled by k8s itself, so if Keda didn't work, they will still allow to scale. That's why I wanted to add a CPU scaler to have a fallback scaler if Keda didn't work (or cannot connect to my external Prom or my Kafka broker).

**Comment by JorTurFer** [comment]
Hi @loicmathieu 
For fallback scenarios, KEDA also supports a fallback configuration :)
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {scaled-object-name}
spec:
  ...
  fallback:                                          # Optional. Section to specify fallback options
    failureThreshold: 3                              # Mandatory if fallback section is included
    replicas: 6                                      # Mandatory if fallback section is included
  ...
  triggers:
  ...
```
using it, you could define the amount of replicas that you'd like to have in case of KEDA can't connect to the upstream, using CPU it's not necessary only for fallback situations
