### ISSUE TITLE
"kubectl get --raw" responses "Error from server: exactly one ScaledObject should match label" on multiple ScaledObjects

### ISSUE THREAD

**Issue by kandeshvari** [kedacore/keda#2456]
### Report

I have a `ScaledObject` with prometheus trigger

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: svc1-preview
  namespace: preview
  labels:
    app: svc1
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          preview-svc1
  pollingInterval:  60
  cooldownPeriod:   300
  minReplicaCount:  1
  maxReplicaCount:  10
  advanced:                                          
    horizontalPodAutoscalerConfig:                   
      behavior:                                      
        scaleDown:
          stabilizationWindowSeconds: 300
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.prometheus:9090
      metricName: svc1_preview_desired_replicas
      query: some_valid_metric{}
      threshold: '1'
```

After applying, I can succesfully request a metric value

```
$ kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/preview/s0-prometheus-svc1_preview_desired_replicas" | jq .
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {},
  "items": [
    {
      "metricName": "s0-prometheus-svc1_preview_desired_replicas",
      "metricLabels": null,
      "timestamp": "2022-01-09T17:51:19Z",
      "value": "0"
    }
  ]
}
```

After adding one more `ScaledObject` for another deployment 

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: svc2-preview
  namespace: preview
  labels:
    app: svc2
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          preview-svc2
  pollingInterval:  15
  cooldownPeriod:   300
  minReplicaCount:  1
  maxReplicaCount:  40
  advanced:                                          
    horizontalPodAutoscalerConfig:                   
      behavior:                                      
        scaleDown:
          stabilizationWindowSeconds: 300
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.prometheus:9090
      metricName: svc2_preview_desired_replicas
      query: another_valid_metric
      threshold: '1'
```

One more external metric appears in `external.metrics.k8s.io` list: 

```
$ kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1" | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "s0-prometheus-svc2_preview_desired_replicas",
      "singularName": "",
      "namespaced": true,
      "kind": "ExternalMetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "s0-prometheus-svc1_preview_desired_replicas",
      "singularName": "",
      "namespaced": true,
      "kind": "ExternalMetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```

But when I try to make the same request I got:
```
$ kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/preview/s0-prometheus-svc1_preview_desired_replicas" | jq .
Error from server: exactly one ScaledObject should match label 
```

### Expected Behavior

correct `ExternalMetricValueList` json should be returned or 404 response

### Actual Behavior

Message `Error from server: exactly one ScaledObject should match label` has been received

### Steps to Reproduce the Problem

1. Apply two different `ScaledObjects`
2. Request metric with as it stated in [doc](https://keda.sh/docs/2.5/operate/metrics-server/). For example, `kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/preview/s0-prometheus-svc1_preview_desired_replicas" | jq .` 

### Logs from KEDA operator

periodic records like
```
2022-01-09T17:54:33.429Z	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "svc1-preview", "namespace": "preview"}
2022-01-09T17:56:07.921Z	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "svc2-preview", "namespace": "preview"}
```

`keda-metrics-apiserver` logs:
```
E0109 17:55:11.045737       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"exactly one ScaledObject should match label "}: exactly one ScaledObject should match label 
I0109 17:55:21.560918       1 trace.go:205] Trace[688076105]: "List" url:/apis/external.metrics.k8s.io/v1beta1/namespaces/preview/s0-prometheus-svc2_preview_desired_replicas,user-agent:kube-controller-manager/v1.18.8 (linux/amd64) kubernetes/9f2892a/system:serviceaccount:kube-system:horizontal-pod-autoscaler,audit-id:98975da3-0ccb-4776-8aef-5d484103af95,client:127.0.0.1,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (09-Jan-2022 17:55:20.809) (total time: 751ms):
Trace[688076105]: ---"Listing from storage done" 751ms (17:55:21.560)
Trace[688076105]: [751.620851ms] [751.620851ms] END
```

### KEDA Version

2.5.0

### Kubernetes Version

1.18

### Platform

Amazon Web Services

### Scaler Details

prometheus

### Anything else?

This error message is returned on any combination of namespace and metric name instead of `404 Not found`
