### ISSUE TITLE
 keda controller enable verbose logging and debugging

### ISSUE THREAD

**Issue by aslom** [kedacore/keda#246]
How do I enable additional debugging and/or build version of keda controller I can debug?

I am gettign endless stream messages in keda operator logs (every second ...): 

```
time="2019-06-06T16:52:02Z" level=info msg="Watching ScaledObject: default/keda-scaled-alek5"
time="2019-06-06T16:52:02Z" level=info msg="Created HPA with namespace default and name keda-hpa-kafka-source-alek1-qmzn7"
time="2019-06-06T16:52:02Z" level=error msg="Error updating scaledObject (default/keda-scaled-alek5) status: Operation cannot be fulfilled on scaledobjects.keda.k8s.io \"keda-scaled-alek5\": the object has been modified; please apply your changes to the latest version and try again"
time="2019-06-06T16:52:03Z" level=error msg="Error updating scaledObject (default/keda-scaled-alek5) status: Operation cannot be fulfilled on scaledobjects.keda.k8s.io \"keda-scaled-alek5\": the object has been modified; please apply your changes to the latest version and try again"
...
```

```
(base) aslom@m keda-testing $ k get pods |grep kafka-source-alek1-qmzn7
kafka-source-alek1-qmzn7-545965cd74-29fsq   1/1     Running   0          13h
(base) aslom@m keda-testing $ k apply -f keda-scaled-object-kafka-source-alek5.yaml
scaledobject.keda.k8s.io/keda-scaled-alek5 configured
(base) aslom@m keda-testing $ cat keda-scaled-object-kafka-source-alek5.yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: keda-scaled-alek5
  namespace: default
  labels:
    deploymentName: kafka-source-alek1-qmzn7
spec:
  scaleTargetRef:
    deploymentName: kafka-source-alek1-qmzn7
  pollingInterval: 1  # Optional. Default: 30 seconds
  triggers:
  - type: kafka
    metadata:
      brokerList: my-cluster-kafka-brokers.kafka:9092
      consumerGroup: groupa4
      topic: alek1
```

Thank yo for any pointer/help in advance.
