### ISSUE TITLE
fix wiki kafka topicName to topic example

### ISSUE THREAD

**Issue by aslom** [kedacore/keda#247]
This is incorrect

```
triggers:
  - type: kafka
    metadata:
      brokerList: kafka.svc:9092
      consumerGroup: my-group
      topicName: test-topic
      lagThreshold: '5' 
```

it should be topic?

```
triggers:
  - type: kafka
    metadata:
      brokerList: kafka.svc:9092
      consumerGroup: my-group
      topic: test-topic
      lagThreshold: '5' 
```

https://github.com/kedacore/keda/wiki/ScaledObject-spec

The linked example is correct:

https://github.com/kedacore/keda/blob/master/examples/kafka_scaledobject.yaml
