### ISSUE TITLE
maxReplicaCount being ignored

### ISSUE THREAD

**Issue by JackSilk** [kedacore/keda#2479]
### Report

I have a ScaledObject monitoring a Kafka queue. I've set the maxReplicaCount value but I'm seeing the deployment scale well in excess of what I've set. 

The maximum doesn't appear to exceed partition count / (consumer count per service * instance)
The HPA reports Maximum Replicas to be 100

### Expected Behavior

The deployment to not scale past the maxReplicaCount

### Actual Behavior

The deployment is scaling past the maxReplicaCount

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.5.0

### Kubernetes Version

1.19

### Platform

Google Cloud

### Scaler Details

Kafka

### Anything else?

ScaledObject YAML:

`apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: integrity-scaling
spec:
  scaleTargetRef:
    name: integrity
  pollingInterval: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: {{ .Values.kafka.bootstrapServers }}
        consumerGroup: Integrity       # Make sure that this consumer group name is the same one as the one that is consuming topics
        topic: IntegrityRequest
        # Optional
        lagThreshold: "20"
        offsetResetPolicy: latest
        maxReplicaCount: "20"
`

**Comment by JorTurFer** [comment]
Hi @JackSilk 
Could you share your ScaledObject please (replacing sensible values if there are)?
It's weird because KEDA only passes the value from the ScaledObject to the HPA and is the HPA contoller which scales in/out.

Please also execute `kubectl describe hpa {yourHPA} -n {yourNamespace}` and paste the result here

**Comment by JorTurFer** [comment]
oh, wait
is your problem that the maximum amount of instances is less than the maximum you set?

**Comment by JackSilk** [comment]
ScaledObject YAML:
````
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: integrity-scaling
spec:
  scaleTargetRef:
    name: integrity
  pollingInterval: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: {{ .Values.kafka.bootstrapServers }}
        consumerGroup: Integrity
        topic: IntegrityRequest
        lagThreshold: "20"
        offsetResetPolicy: latest
        maxReplicaCount: "20"
`````

hpa:

````
Name:                                                  keda-hpa-integrity-scaling
Namespace:                                             e16ude
Labels:                                                app.kubernetes.io/managed-by=Helm
                                                       app.kubernetes.io/name=keda-hpa-integrity-scaling
                                                       app.kubernetes.io/part-of=integrity-scaling
                                                       app.kubernetes.io/version=2.5.0
                                                       scaledobject.keda.sh/name=integrity-scaling
Annotations:                                           <none>
CreationTimestamp:                                     Fri, 17 Dec 2021 16:41:54 +0000
Reference:                                             Deployment/integrity
Metrics:                                               ( current / target )
  "s0-kafka-IntegrityRequest" (target average value):  1728m / 2
Min replicas:                                          1
Max replicas:                                          100
Deployment pods:                                       22 current / 22 desired
Conditions:
  Type            Status  Reason               Message
  ----            ------  ------               -------
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
  ScalingActive   True    ValidMetricFound     the HPA was able to successfully calculate a replica count from external metric s0-kafka-IntegrityRequest(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: integrity-scaling,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  False   DesiredWithinRange   the desired count is within the acceptable range
Events:
  Type    Reason             Age                  From                       Message
  ----    ------             ----                 ----                       -------
  Normal  SuccessfulRescale  60m                  horizontal-pod-autoscaler  New size: 34; reason: All metrics below target
  Normal  SuccessfulRescale  55m                  horizontal-pod-autoscaler  New size: 31; reason: All metrics below target
  Normal  SuccessfulRescale  49m (x2 over 24d)    horizontal-pod-autoscaler  New size: 28; reason: All metrics below target
  Normal  SuccessfulRescale  43m (x198 over 24d)  horizontal-pod-autoscaler  (combined from similar events): New size: 25; reason: All metrics below target
  Normal  SuccessfulRescale  14m (x3 over 23d)    horizontal-pod-autoscaler  New size: 22; reason: All metrics below target
````

**Comment by JackSilk** [comment]
@JorTurFer 
> oh, wait
> is your problem that the maximum amount of instances reality is less than the maximum you set?

No I'm seeing that the maximum amount is higher than the maximum I've set

**Comment by JorTurFer** [comment]
I have seen the problem! :) 
You have a typo in the manifest, `maxReplicaCount` is not part of the triggers section, it should be at the same level of trigger. Something like this:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: integrity-scaling
spec:
  scaleTargetRef:
    name: integrity
  pollingInterval: 30
  maxReplicaCount: "20"
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: {{ .Values.kafka.bootstrapServers }}
        consumerGroup: Integrity
        topic: IntegrityRequest
        lagThreshold: "20"
        offsetResetPolicy: latest
```
