### ISSUE TITLE
`mode: QueueLength, value: "##"`  does not scale, but the legacy `queueLength: "##"` does.

### ISSUE THREAD

**Issue by PatrickGhosn** [kedacore/keda#2496]
### Report

When we use the new `rabbitmq` trigger configuration with `Keda 2.5`, it does not scale at all. 

```
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: testqueue
      mode: QueueLength
      value: "50"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn

```

However when we switch to the deprecated configuration, the scaling works fine.

```
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: testqueue
      queueLength: "50"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
```

### Expected Behavior

The scaling to work with the new configuration.

### Actual Behavior

It only works with the deprecated config.

### Steps to Reproduce the Problem

1. Use the new config
2. Test the scaling in the message queue
3. Switch to the old config
4. Test the scaling in the message queue

### Logs from KEDA operator

```
example
```

### KEDA Version

2.5.0

### Kubernetes Version

1.22

### Platform

Other

### Scaler Details

RabbitMQ

### Anything else?

The issue seems to be encountered by other people as well. I found the solution here:
https://stackoverflow.com/questions/70520404/keda-no-pods-are-scaling
https://stackoverflow.com/questions/67307036/keda-not-scaling-above-1-pod/67319005#67319005
