### ISSUE TITLE
ScaledObject ignoring triggers sometimes

### ISSUE THREAD

**Issue by chenele** [kedacore/keda#2570]
### Report

i have configured ScaledObject configuration to scale Statefulset based on pubsub metrics.

this is the configuration im using:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mysvc-scaledobject
  namespace: utils
spec:
  scaleTargetRef:
    name: mysvc
    kind: StatefulSet
  minReplicaCount: 3
  maxReplicaCount: 3
  triggers:
  - type: gcp-pubsub
    authenticationRef:
      name: mysvc-auth-gcp-credentials
    metadata:
      mode: "SubscriptionSize"
      value: "3"
      subscriptionName: "projects/myproj/subscriptions/mysubscription1"
  - type: gcp-pubsub
    authenticationRef:
      name: mysvc-auth-gcp-credentials
    metadata:
      mode: "SubscriptionSize"
      value: "1"
      subscriptionName: "projects/myproj/subscriptions/mysubscription2"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mysvc-auth-gcp-credentials
  namespace: utils
spec:
  podIdentity:
    provider: gcp
```

deployed on one Env worked OK, deploying it on Env2 it seems to ignore my triggeres configuration and defined the scale based on cpu. 

### Expected Behavior

I should see the HPA with the pubsub metrics.

**kubectl get hpa -n utils**
```
keda-hpa-mysvc-scaledobject   StatefulSet/mysvc         0/3 (avg), 0/1 (avg)   3         3         3          31m
```

**kubectl get scaledobject mysvc-scaledobject -o yaml -n utils**
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    meta.helm.sh/release-name: mysvc
    meta.helm.sh/release-namespace: utils
  creationTimestamp: "2022-01-27T14:22:47Z"
  finalizers:
  - finalizer.keda.sh
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    scaledobject.keda.sh/name: mysvc-scaledobject
  name: mysvc-scaledobject
  namespace: utils
  selfLink: /apis/keda.sh/v1alpha1/namespaces/utils/scaledobjects/mysvc-scaledobject
spec:
  maxReplicaCount: 3
  minReplicaCount: 3
  scaleTargetRef:
    kind: StatefulSet
    name: mysvc
  triggers:
  - authenticationRef:
      name: mysvc-auth-gcp-credentials
    metadata:
      mode: SubscriptionSize
      subscriptionName: projects/myproj/subscriptions/mysubscription2
      value: "3"
    type: gcp-pubsub
  - authenticationRef:
      name: mysvc-auth-gcp-credentials
    metadata:
      mode: SubscriptionSize
      subscriptionName: projects/myproj/subscriptions/mysubscription2
      value: "1"
    type: gcp-pubsub
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is not performed because triggers are not active
    reason: ScalerNotActive
    status: "False"
    type: Active
  - message: No fallbacks are active on this scaled object
    reason: NoFallbackFound
    status: "False"
    type: Fallback
  externalMetricNames:
  - s0-gcp-ps-projects-myproj-subscriptions-mysubscription1
  - s1-gcp-ps-projects-myproj-subscriptions-mysubscription2
  health:
    s0-gcp-ps-projects-myproj-subscriptions-mysubscription1:
      numberOfFailures: 0
      status: Happy
    s1-gcp-ps-projects-myproj-subscriptions-mysubscription2:
      numberOfFailures: 0
      status: Happy
  originalReplicaCount: 3
  scaleTargetGVKR:
    group: apps
    kind: StatefulSet
    resource: statefulsets
    version: v1
  scaleTargetKind: apps/v1.StatefulSet
```

### Actual Behavior

**kubectl get hpa -n utils**
`keda-hpa-mysvc-scaledobject   StatefulSet/mysvc          0%/80%    3         3         3          15m`

**kubectl get scaledobject mysvc-scaledobject -n utils -o yaml**
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    meta.helm.sh/release-name: mysvc
    meta.helm.sh/release-namespace: utils
  creationTimestamp: "2022-01-27T14:43:19Z"
  finalizers:
  - finalizer.keda.sh
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    scaledobject.keda.sh/name: mysvc-scaledobject
  name: mysvc-scaledobject
  namespace: utils
  selfLink: /apis/keda.sh/v1alpha1/namespaces/utils/scaledobjects/mysvc-scaledobject
spec:
  maxReplicaCount: 3
  minReplicaCount: 3
  scaleTargetRef:
    kind: StatefulSet
    name: mysvc
  triggers:
  - authenticationRef:
      name: mysvc-auth-gcp-credentials
    metadata:
      mode: SubscriptionSize
      subscriptionName: projects/myproj/subscriptions/mysubscription1
      value: "3"
    type: gcp-pubsub
  - authenticationRef:
      name: mysvc-auth-gcp-credentials
    metadata:
      mode: SubscriptionSize
      subscriptionName: projects/myproj/subscriptions/mysubscription2
      value: "1"
    type: gcp-pubsub
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is not performed because triggers are not active
    reason: ScalerNotActive
    status: "False"
    type: Active
  - status: Unknown
    type: Fallback
  originalReplicaCount: 3
  scaleTargetGVKR:
    group: apps
    kind: StatefulSet
    resource: statefulsets
    version: v1
  scaleTargetKind: apps/v1.StatefulSet
```

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
2022-01-27T14:48:41.310Z	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "mysvc-scaledobject", "namespace": "utils"}
2022-01-27T14:48:41.325Z	INFO	controller.scaledobject	Updated HPA according to ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "mysvc-scaledobject", "namespace": "utils", "HPA.Namespace": "utils", "HPA.Name": "keda-hpa-mysvc-scaledobject"}
```

### KEDA Version

2.5.0

### Kubernetes Version

1.19

### Scaler Details

PubSub
