### ISSUE TITLE
Prometheus ingress request count metric displayed as wrong unit 

### ISSUE THREAD

**Issue by jamesdowning-chip** [kedacore/keda#2596]
### Report

When using a trigger of type `prometheus` and in this case the `nginx_ingress_controller_requests` query, the HPA shows the current value as a memory unit rather than the query value.

E.G.:

`kubectl describe hpa <my-hpa> -n <namespace>`

```
Metrics:                                                          ( current / target )
  "s1-prometheus-nginx_ingress_requests" (target average value):  4715m / 10
```

### Expected Behavior

The actual value as returned by the external metrics API is displayed:

```
kubectl get --raw '/apis/external.metrics.k8s.io/v1beta1/namespaces/<namespace>/s1-prometheus-nginx_ingress_requests?labelSelector=scaledobject.keda.sh/name=app' | jq
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {},
  "items": [
    {
      "metricName": "s1-prometheus-nginx_ingress_requests",
      "metricLabels": null,
      "timestamp": "2022-02-04T15:26:33Z",
      "value": "32"
    }
  ]
}
```

### Actual Behavior

As described in the report, the value seems to be converted into a memory unit type rather than the actual value. However under the HPA seems to be using the true value. i.e. The above example however **doesn't** cause the HPA to scale the pods to the maximum replica value despite it being in the thousands.

### Steps to Reproduce the Problem

1. Create a `scaledObject` with a prometheus query such as:
```
triggers:
          type: prometheus
          metadata:
            serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
            metricName: nginx_ingress_requests
            threshold: '10'
            query: sum(rate(nginx_ingress_controller_requests{ingress="app-ingress",exported_namespace="<namespace>"}[2m]))
```
2.  Describe the subsequently created HPA resource
`kubectl describe hpa <my-hpa> -n <namespace>`

```
Metrics:                                                          ( current / target )
  "s1-prometheus-nginx_ingress_requests" (target average value):  4715m / 10
```

### Logs from KEDA operator

N/A

### KEDA Version

2.5.0

### Kubernetes Version

1.21

### Platform

Amazon Web Services

### Scaler Details

Prometheus

### Anything else?

This seems to occur randomly. I've installed the same manifests on multiple clusters and the value is correctly displayed
