### ISSUE TITLE
Keda Kafka Scaler not able to scale up

### ISSUE THREAD

**Issue by pchaudhary1** [kedacore/keda#2597]
### Report

Hi,

I am trying to use Keda's Kafka Scaler, but I see following error in the "keda-hpa-kafka-scaledobject" status.
The pods scale down to 0, but do not scale-up to the maxReplica count. 

Warning  FailedGetExternalMetric  4s (x76 over 6h22m)  horizontal-pod-autoscaler  unable to get external metric keda/s0-kafka-my-topic-1/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: kafka-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get s0-kafka-my-topic-1.external.metrics.k8s.io)

Below is my ScaledObject 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: keda
  labels:
    app: consumer
    deploymentName: consumer
spec:
  scaleTargetRef:
    name: consumer
  pollingInterval: 10
  cooldownPeriod: 15
  minReplicaCount: 2
  maxReplicaCount: 9
  idleReplicaCount: 0
  fallback:
    failureThreshold: 3
    replicas: 3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
          policies:
            - type: Percent
              value: 10
              periodSeconds: 10    
        scaleUp:
          stabilizationWindowSeconds: 10
          policies:
            - type: Percent
              value: 10
              periodSeconds: 10    
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: "xxx9092"
        consumerGroup: "test-consumer-group"
        topic: "my-topic-1"
        lagThreshold: "100"
      authenticationRef:
        name: keda-trigger-auth-kafka-credential
```

### Expected Behavior

The pods should scale up to the manReplicaCount count, in the above example it shld go all the way to 9

### Actual Behavior

The pods should scale up to the minReplicaCount count, in the above example it shld go all the way to 3.
When the lag is consumer it scales down to idleReplicaCount, in the above example i.e. 0

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

There are no errors in the Keda Operator log file.

### KEDA Version

2.6.0

### Kubernetes Version

1.23

### Platform

Google Cloud

### Scaler Details

Kafka
