### ISSUE TITLE
Allow IdleReplicaCount less than or equal to MinReplicaCount

### ISSUE THREAD

**Issue by khacminh** [kedacore/keda#2598]
### Proposal

Keda doesn't allow IdleReplicaCount to be **equal to** MinReplicaCount. Therefore, I cannot keep my service at the minimum resource.

---

Here is an example:

I cannot configure the ScaledObject like this:

```yaml
# invalid configuration
idleReplicaCount: 1
minReplicaCount: 1
maxReplicaCount: 5
```

I have to set it as:

```yaml
# valid configuration 1
idleReplicaCount: 0
minReplicaCount: 1
maxReplicaCount: 5
```

or

```yaml
# valid configuration 2
idleReplicaCount: 1
minReplicaCount: 2
maxReplicaCount: 5
```

---

- The first approach doesn't make the service always available
- The second approach creates the redundant replica. It could be a big deal for the expensive GPU machine
