### ISSUE TITLE
All externalMetricsNames with the same name broken if the data source for one of them is unavailable.

### ISSUE THREAD

**Issue by IvanDechovsky** [kedacore/keda#2599]
### Report

If you configure multiple ScaledObjects with the same `metricName` like so:
```
  triggers:
  - metadata:
      metricName: nginx_ingress_controller_requests
 ```
 but use different `serverAddress` and one of those data sources becomes unavailable, all of the scaled objects with that same `externalMetricName` break with the following error
 
 ```
   Warning  FailedComputeMetricsReplicas  22m (x2 over 22m)  horizontal-pod-autoscaler  invalid metrics (2 invalid out of 2), first error is: failed to get s0-prometheus-nginx_ingress_controller_requests external metric: unable to get external metric default/s0-prometheus-nginx_ingress_controller_requests/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: real,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get s0-prometheus-nginx_ingress_controller_requests.external.metrics.k8s.io)
```

### Expected Behavior

The expected behaviour would be that only the ScaledObject with the unavailable `serverAddress` to report the metrics unavailable error.

### Actual Behavior

All ScaledObjects with the same `externalMetricNames` report the same metrics unavailable error, regardless of the availability of their `serverAddress`

### Steps to Reproduce the Problem

1. Create two Scaled objects like so:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: real
  namespace: default
spec:
  maxReplicaCount: 5
  minReplicaCount: 2
  pollingInterval: 30
  scaleTargetRef:
    name: test
  triggers:
  - metadata:
      metricName: nginx_ingress_controller_requests
      query: |
        sum(
            rate(
                nginx_ingress_controller_requests{
                    exported_namespace="default",
                    exported_service="test",
                }[2m]
            )
        )
      serverAddress: http://kube-prometheus-stack-thanos-query-frontend.kube-system:9090/
      threshold: "7"
    type: prometheus
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fake
  namespace: default
spec:
  maxReplicaCount: 5
  minReplicaCount: 2
  pollingInterval: 30
  scaleTargetRef:
    name: test
  triggers:
  - metadata:
      metricName: nginx_ingress_controller_requests
      query: |
        sum(
            rate(
                nginx_ingress_controller_requests{
                    exported_namespace="default",
                    exported_service="test",
                }[2m]
            )
        )
      serverAddress: http://foo.bar:9090/
      threshold: "7"
    type: prometheus
```
2. Describe both `ScaledObject`
```
kubectl describe hpa keda-hpa-real
kubectl describe hpa keda-hpa-fake
```

3. You should see in both HPA the same error message
```
  Warning  FailedComputeMetricsReplicas  44m (x2 over 44m)  horizontal-pod-autoscaler  invalid metrics (2 invalid out of 2), first error is: failed to get s0-prometheus-nginx_ingress_controller_requests external metric: unable to get external metric default/s0-prometheus-nginx_ingress_controller_requests/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: real,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get s0-prometheus-nginx_ingress_controller_requests.external.metrics.k8s.io)
```

### Logs from KEDA operator

```
keda-operator-metrics-apiserver-7fc4c7974d-vs655 keda-operator-metrics-apiserver E0207 11:06:49.308417       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"No matching metrics found for s1-prometheus-nginx_ingress_controller_requests"}: No matching metrics found for s1-prometheus-nginx_ingress_controller_requests
```

### KEDA Version

2.6.0

### Kubernetes Version

1.21

### Platform

Amazon Web Services

**Comment by zroubalik** [comment]
@IvanDechovsky thanks for reporting this issue, we have indentified some problems with metric names and indexes in 2.6.0, even though this seems like a different issue. Are you able to try to reproduce the problem with images mentined here: https://github.com/kedacore/keda/issues/2592#issuecomment-1029900476

Thanks! feel free to ping me on slack for details.

**Comment by IvanDechovsky** [comment]
Hi, thanks for the quick response. Just switching to the images does not fix the issue for existing metric names but it does fix it if they were to be re-created or simply renamed ( to the same name). I guess that triggers them to be re-indexed and problem goes away.

Do you know when we can expect 2.6.1?

Do you know if there is a way to fix the problem for existing metrics without asking our dev teams to rename their `metricNames` or recreate their `ScaledObjects`?

**Comment by IvanDechovsky** [comment]
I may have been too quick to call it resolved. Upon further testing, I can still reproduce the problem with the `indexFix` images. In the current version a restart of keda also "ocassionally" removes the issue for a certain period of time.
The `externalMetricNames` with 2.6.0 and with `indexFix` stay the same so the problem with non unique metric names still persists.

**Comment by zroubalik** [comment]
@IvanDechovsky thanks for the confirmation, I will take a look on it.

**Comment by zroubalik** [comment]
@IvanDechovsky I haven't been able to reproduce the problem 🤔 I have 2 SO, with the same `metricName`, took down one service, the respective SO stopped working the other one was working correctly 🤷‍♂️

**Comment by IvanDechovsky** [comment]
Hey @zroubalik ,
I can consistently reproduce it on 2.6.0 and `indexFix` images. However, the key is to restart the keda-operator + keda-operator-metrics-server pods. The same way a restart of those pods can help fix the issues temporarily, it can also break working scaledobjects. 

@JorTurFer i just tested with different deployments and the result is the same.
```
keda-hpa-fake   Deployment/thanos-query            <unknown>/7 (avg), <unknown>/1 (avg)   2         50        2          82s
keda-hpa-real   Deployment/thanos-query-frontend   0/7 (avg), 500m/1 (avg)                2         50        2          82s
```
On initial inspection, it correctly detects the "real" hpa with working data source. However, if you describe it, you see the same error
```
  Warning  FailedComputeMetricsReplicas  45s   horizontal-pod-autoscaler  invalid metrics (2 invalid out of 2), first error is: failed to get s0-prometheus-nginx_ingress_controller_requests external metric: unable to get external metric thanos/s0-prometheus-nginx_ingress_controller_requests/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: real,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get s0-prometheus-nginx_ingress_controller_requests.external.metrics.k8s.io)
  ```

**Comment by JorTurFer** [comment]
could you share your ScaledObject literary how they are (only removing the secrets if they are)?

**Comment by IvanDechovsky** [comment]
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: real
  namespace: thanos
spec:
  maxReplicaCount: 50
  minReplicaCount: 2
  pollingInterval: 30
  scaleTargetRef:
    name: thanos-query-frontend
  triggers:
  - metadata:
      metricName: nginx_ingress_controller_requests
      query: |
        sum(
            rate(
                nginx_ingress_controller_requests{
                    exported_namespace="thanos",
                    exported_service="thanos-query-frontend",
                }[2m]
            )
        )
      serverAddress: http://kube-prometheus-stack-thanos-query-frontend.kube-system:9090/
      threshold: "7"
    type: prometheus
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fake
  namespace: thanos
spec:
  maxReplicaCount: 50
  minReplicaCount: 2
  pollingInterval: 30
  scaleTargetRef:
    name: thanos-query
  triggers:
  - metadata:
      metricName: nginx_ingress_controller_requests
      query: |
        sum(
            rate(
                nginx_ingress_controller_requests{
                    exported_namespace="fake",
                    exported_service="fake",
                }[2m]
            )
        )
      serverAddress: http://fake-foo-bar-thanos.kube-system:9090/
      threshold: "7"
    type: prometheus
```
