### ISSUE TITLE
SQS Scaler not scaling out

### ISSUE THREAD

**Issue by patnaikshekhar** [kedacore/keda#261]
I'm trying to use the SQS scaler. It does scale the deployment down to 0 but does not seem to be scaling out even after a number of messages are added to the queue. Full code is [here](https://github.com/patnaikshekhar/KEDA-AWS-SQS-Python). 

The following is the scaled object definition

```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: keda-aws-sqs-sample
spec:
  scaleTargetRef:
    deploymentName: keda-aws-sqs-python
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: <QUEUE_URL>
      region: "us-west-2"
      awsAccessKeyID: AWS_ACCESS_KEY_ID
      awsSecretAccessKey: AWS_SECRET_ACCESS_KEY
      queueLength: "5"
```

and this is the deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-aws-sqs-python
  namespace: keda-aws-sqs-sample
spec:
  selector:
    matchLabels:
      service: keda-aws-sqs-python
  replicas: 1
  template:
    metadata:
      labels:
        service: keda-aws-sqs-python
    spec:
      containers:
      - image: patnaikshekhar/keda-aws-sqs-python:1
        name: consumer
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: keda-aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: keda-aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: us-west-2
```

These are the logs from the Keda Controller Pod
time="2019-06-18T15:18:04Z" level=info msg="Watching ScaledObject: keda-aws-sqs-sample/aws-sqs-queue-scaledobject"
time="2019-06-18T15:18:06Z" level=info msg="Created HPA with namespace keda-aws-sqs-sample and name keda-hpa-keda-aws-sqs-python"
time="2019-06-18T15:18:06Z" level=info msg="Successfully scaled deployment (keda-aws-sqs-sample/keda-aws-sqs-python) to 0 replicas"
E0618 15:28:32.187004       1 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 1655; INTERNAL_ERROR
