### ISSUE TITLE
keda failed to create HPA object when Deployment has missing secretKeyRef (optional: true)

### ISSUE THREAD

**Issue by siva-27** [kedacore/keda#2658]
### Report

I have created an example deployment and tries to get the secret using `secretKeyRef` with a non existing secret using an optional true
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-env-pod
  labels:
    app: secret
spec:
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      containers:
      - name: mycontainer
        image: redis
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
                optional: true 
```
Deployment got created and I tried the below scaledobject to trigger the scaling
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject
spec:
  scaleTargetRef:
    name: secret-env-pod
  pollingInterval: 1
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
```

### Expected Behavior

Keda should create HPA object

### Actual Behavior

Keda failed to create the HPA Object

### Steps to Reproduce the Problem

1. Create the example deployment and scaledobject which I pasted above
2. Keda will failed to create HPA object and you can see the error by describing the scaledobject `Kubectl describe scaledobject cpu-scaledobject`

### Logs from KEDA operator

```
error resolving secrets for ScaleTarget: error resolving secret name &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:mysecret,},Key:username,Optional:*true,} for env SECRET_USERNAME in namespace default
```

### KEDA Version

2.6.0

### Kubernetes Version

1.21

### Scaler Details

CPU
