### ISSUE TITLE
[Question] Scale in chunks based on queue depth

### ISSUE THREAD

**Issue by brobichaud** [kedacore/keda#269]
I'm wondering if the intention is for KEDA to remain purely an event driven model? My scenario is a bit of a hybrid of event-driven and reactive, yet it feels close to the core design of KEDA.

An example: I'd like to tell KEDA to monitor my Azure Storage Queue and once the queue depth exceeds 10 scale a deployment out by 1 pod for every 5 messages above the 10 threshold. So if there were suddenly 40 messages in the queue it should add 6 pods. I could settle for not having that first threshold if necessary and just have it scale 1 pod for every X messages in the queue.

The background on our architecture is that we have somewhat variable length jobs (they take from 30 secs to sometimes > 30 minutes). To be very reactive we always keep 2 pods running, monitoring the queue. But at times the work comes in bursts and I'd like to scale out in a chunky way, not for every message because the pod can be rather resource intensive. We have a few different flavors of this basic design that the above featureset would over.

Is that far outside the design ambitions of this project?

**Comment by Aarthisk** [comment]
@brobichaud The scale for Azure Queues is fairly close to what you describe. You can modify the Scale object and set the queueLength' to be what you want. This is the per-pod message length at which HPA will spin up a new pod. The schema for the scaled object is here: https://github.com/kedacore/keda/wiki/ScaledObject-spec

**Comment by brobichaud** [comment]
I agree it is close, but really not close enough. I don't want to create a new pod for every pending message above a threshold, that would be way to aggressive. The most concise way to describe what I'm after is:

I want to create a new pod for every X pending messages above a threshold.

**Comment by Aarthisk** [comment]
@brobichaud ha I see. Thanks for the clarification. This is similar to the setting --horizontal-pod-autoscaler-tolerance. I don't think AKS lets us configure this per cluster but GKE might. I will leave this issue open for us to consider a tolerance value for metrics returned configurable in a scaled object.

**Comment by brobichaud** [comment]
I feel like I have misunderstood the core of how KEDA scales.

The core of what I'm after is something like this:
When my Azure Storage Queue exceeds X then start scaling out, making sure there is one pod for every Y queue messages above X. I also of course need a min and max pod count to scale between.

A real-world example for me is:
I run with 1-20 messages in my queue at any given time and 2 pods normally handling them fine. But suddenly 86 messages appear in my queue. I want to scale out so I have 1 pod for every 10 messages above that 20 threshold, so 7 more pods, or 9 total. I want to limit the min pod count at 2 and max at 10.

Can I make KEDA do this?

**Comment by Aarthisk** [comment]
@brobichaud The scaling by HPA is already chunky- and is not for every pending message. Have you tried your scenario with our existing scaler - depending on your consumer's speed this is the behavior you should see with Keda.

**Comment by asavaritayal** [comment]
Needs further discussion to evaluate for the 1.0 milestone.

**Comment by Aarthisk** [comment]
@@brobichaud  Did you get a chance to try out the Queue scaler? let us know if you run into any issues or have any feedback.

**Comment by brobichaud** [comment]
I am circling back to give keda a try and am having trouble getting things setup. @Aarthisk perhaps you can help me debug?

I've got keda installed on my AKS cluster. I should note I'm running Windows nodepools so I had to add a nodeAffinity to KedaScaleController.yaml so that it deploys to a linux nodepool. Here's a snippet of the modified yaml:

```
    spec:
      serviceAccountName: keda-operator
      affinity:
        nodeAffinity: # require scheduling on linux nodes
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - name: keda-operator
        image: kedacore/keda:latest
```

It seems to be running normally under the keda namespace:

```
C:\dev\keda>kubectl get pod -n keda
NAME                            READY   STATUS    RESTARTS   AGE
keda-operator-54c4ddd69-rghrc   1/1     Running   0          24m
```

Here's my ScaledObject definition:

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: dev-madras-embedder-scale
  labels:
    deploymentName: dev-madras-embedder
spec:
  scaleTargetRef:
    deploymentName: dev-madras-embedder
    containerName: embedder
  pollingInterval: 10  # Optional. Default: 30 seconds
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 5 # Optional. Default: 100
  triggers:
  - type: azure-queue
    metadata:
      queueName: kedascale
      queueLength: '5' # Optional. Queue length target for HPA. Default: 5 messages
      connection: MADRAS_PlatformStorageConnection
```

When I apply this I do not see an hpa object get created. Feels like I should based on documentation, but `kubectl get hpa` shows nothing but other hpa's I've created. If I insert a bunch of messages into my queue (enough to trigger scaling), I see no pod scaling.

I'm not sure how to look at what keda is doing, or not doing. Any thoughts?
