### ISSUE TITLE
Selenium Gird Scaler | Edge active sessions not being properly counted

### ISSUE THREAD

**Issue by Wolfe1** [kedacore/keda#2709]
### Report

Been working on getting a selenium grid 4 deployment working in AKS using Keda to scale. Chrome and Firefox have been no problem but scaling Edge browser pods seems to have a bug.

Currently using the following scaled-object:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-edge-scaledobject
  namespace: legion-selenium-grid
  labels:
    deploymentName: selenium-edge-node-deployment
spec:
  minReplicaCount: 0
  maxReplicaCount: 80
  scaleTargetRef:
    name: selenium-edge-node-deployment
  triggers:
    - type: selenium-grid
      metadata:
        url: 'https://selenium-grid-qe-tools.accruentsystems.com/graphql'
        browserName: 'MicrosoftEdge'
```

New sessions in the queue appear as 'MicrosoftEdge' and scale up just fine:
![image](https://user-images.githubusercontent.com/3010366/156442649-26035b95-0fe9-4828-bf48-8d7c32766b2a.png)

However, taking a look at the active sessions I noticed that the browserName on the active sessions becomes 'msedge':
![image](https://user-images.githubusercontent.com/3010366/156442825-8b2c64d1-7d18-4b90-b420-480d995e3ede.png)

Thus when it comes time for Keda to check for a scale-down event it sees that there are no active sessions and proceeds scale to 0.

### Expected Behavior

Keda detects that Edge pods are still in use and scales down gradually as needed.

### Actual Behavior

When scaling down Keda will remove all Edge pods regardless of current active sessions.

### Steps to Reproduce the Problem

1. Deploy selenium grid and Edge deployments
2. Apply scaled-object for edge (see description)
3. Can be done in a variety of ways but an easy way: Run a single long (10 minute +) test on selenium grid. Grid will scale up to allow your test to run but will eventually scale to 0 before your test can finish.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.6.1

### Kubernetes Version

1.21

### Platform

Microsoft Azure

### Scaler Details

Selenium Grid

### Anything else?

I am not in any way familiar with Go and am having issues deploying a local change to AKS but I believe all that really needs done here is a specific check for "MicrosoftEdge" as a browserName and then simply use the session-specific naming of 'msedge' in that situation.

Probably something like this (though im sure there is a more elegant way to put it). [Around line 225 in selenium_grid_scaler](https://github.com/kedacore/keda/blob/main/pkg/scalers/selenium_grid_scaler.go#L225):
```
var sessions = seleniumResponse.Data.SessionsInfo.Sessions
	for _, session := range sessions {
		var capability = capability{}
		var browserCapName = ""
		if browserName == "MicrosoftEdge" {
			browserCapName = "msedge"
		} else {
			browserCapName = browserName
		}
		if err := json.Unmarshal([]byte(session.Capabilities), &capability); err == nil {
			if capability.BrowserName == browserCapName {
				if strings.HasPrefix(capability.BrowserVersion, browserVersion) {
					count++
				} else if browserVersion == DefaultBrowserVersion {
					count++
				}
			}
		} else {
			seleniumGridLog.Error(err, fmt.Sprintf("Error when unmarshaling sessions info: %s", err))
		}
	}
```
