### ISSUE TITLE
Include RBAC permissions to custom resources in KEDA manifests

### ISSUE THREAD

**Issue by wmedlar** [kedacore/keda#2723]
### Proposal

KEDA should attach corresponding CRD permissions to the built-in `view`, `edit`, and `admin` ClusterRoles through [ClusterRole aggregation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles). Right now KEDA requires configuring permissions for its resources manually, introducing burden for cluster operators. Aggregation is a common pattern for applications that deploy CRDs (see [cert-manager](https://github.com/cert-manager/cert-manager/blob/1525026c999e8e1dbea367c8b2102ae7f8d86a6f/deploy/charts/cert-manager/templates/rbac.yaml#L413-L455) for an example) that reduces this burden and simplifies the installation process.

### Use-Case

As a cluster operator, I would like to provide KEDA as a platform service to application teams, using a permissions model that follows best practices by consuming built-in, least-privileged ClusterRoles.

### Anything else?

This is an example of the aggregated ClusterRoles that I apply manually after deploying KEDA.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - keda.sh
  resources:
  - clustertriggerauthentications
  - scaledjobs
  - scaledobjects
  - triggerauthentications
  verbs:
  - create
  - delete
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - keda.sh
  resources:
  - clustertriggerauthentications
  - scaledjobs
  - scaledobjects
  - triggerauthentications
  verbs:
  - get
  - list
  - watch
```
