### ISSUE TITLE
Keda not scaling deployment

### ISSUE THREAD

**Issue by denzhel** [kedacore/keda#2724]
### Report

I'm using this HPA config:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prod-us-west-1-service
spec:
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: prod-us-west-1-service
  pollingInterval: 5
  minReplicaCount: 12
  maxReplicaCount:  20
  fallback:
    failureThreshold: 3
    replicas: 12
  advanced:
      restoreToOriginalReplicaCount: false
      horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          selectPolicy: Max
  triggers:
     - type: prometheus
        metadata:
          serverAddress: X.Y.V.Z
          metricName: outbound_rabbitmq_notifications_queue_count
          query: 'max(avg_over_time(rabbitmq_queue_messages{queue="someQueue.notifications"}[5m]))'
          threshold: "100"
```

This is a screenshot from Grafana:
![image](https://user-images.githubusercontent.com/33213077/157213395-276a36be-b229-4ff4-9bb7-16807d6a4613.png)
This is a screenshot from Prometheus it self when running the query manually:
![image](https://user-images.githubusercontent.com/33213077/157213935-d318ec8e-7f69-4dc2-8087-4ab4c9a7f474.png)

### Expected Behavior

I expect Keda to scale my deployment

### Actual Behavior

As you can see HPA was not triggered and did not scale up
No errors were seen in logs

### Steps to Reproduce the Problem

1. Use the config I mentioned above
2. Use a prometheus metric that rabbitmq publishes with the amount of messages in queuee
3. Try to publish messages and turning off consumers for this queue
4. See that Keda will not scale the deployment

### Logs from KEDA operator

```
{"level":"info","ts":1646731800.4123747,"logger":"controller.scaledobject","msg":"Reconciling ScaledObject","reconciler group":"keda.sh","reconciler kind":"ScaledObject","name":"prod-us-west-1-SomeService","namespace":"prod-us-west-1"}
```

A lot of these ^

### KEDA Version

2.6.1

### Kubernetes Version

1.20

### Platform

Amazon Web Services

### Scaler Details

Prometheus
