### ISSUE TITLE
New Relic Scaler is not getting correct value from query

### ISSUE THREAD

**Issue by pragmaticivan** [kedacore/keda#2740]
### Report

Currently having issues using New Relic Queries properly. The current value does not match the response in New Relic
<img width="1702" alt="Screen Shot 2022-03-12 at 10 55 37 AM" src="https://user-images.githubusercontent.com/301291/158027202-f60ed0f1-b17d-400d-a237-446e57898184.png">
.

### Expected Behavior

The current value should match the current value in the query response.

### Actual Behavior

Getting way higher numbers there.

### Steps to Reproduce the Problem

1. Create ScaleObject:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: podinfo
spec:
  maxReplicaCount: 4
  pollingInterval: 3  # Optional. Default: 30 seconds
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  scaleTargetRef:
    name: podinfo
  triggers:
  - type: memory
    metadata:
      type: Utilization
      value: "50"
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
  - type: new-relic
    metadata:
      account: 'redacted'
      region: "US"
      nrql: "SELECT average(duration) from Transaction where appName='podinfo' TIMESERIES"
      noDataError: "true"
      threshold: '760'
    authenticationRef:
      name: keda-trigger-auth-new-relic
```
2. Inspect HPA:
```
Metrics:                                                  ( current / target )
  "s2-new-relic" (target average value):                  411774998 / 760
  resource memory on pods  (as a percentage of request):  23% (20907008) / 50%
  resource cpu on pods  (as a percentage of request):     3% (7m) / 50%
```

### Logs from KEDA operator

```
I0312 16:18:17.918903       1 request.go:665] Waited for 1.048067544s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/split.smi-spec.io/v1alpha1?timeout=32s
1.6471019025226653e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
1.6471019025248656e+09	INFO	setup	Running on Kubernetes 1.21+	{"version": "v1.21.5-eks-bc4871b"}
1.6471019025251207e+09	INFO	setup	Starting manager
1.647101902525153e+09	INFO	setup	KEDA Version: 2.6.1
1.6471019025251622e+09	INFO	setup	Git Commit: efca71d6bc770408468a9e1a4b3984f7136c0967
1.6471019025251691e+09	INFO	setup	Go Version: go1.17.3
1.6471019025251758e+09	INFO	setup	Go OS/Arch: linux/amd64
I0312 16:18:22.525447       1 leaderelection.go:248] attempting to acquire leader lease kube-system/operator.keda.sh...
1.6471019025254536e+09	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
1.647101902525443e+09	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
```

### KEDA Version

2.6.1

### Kubernetes Version

1.21

### Platform

Amazon Web Services

### Scaler Details

New Relic
