### ISSUE TITLE
Getting empty metric data with multiple dimensions in aws-cloudwatch trigger

### ISSUE THREAD

**Issue by dekelev** [kedacore/keda#2760]
### Report

Using the following `ScaledObject` config, I always get an empty metric data:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker
spec:
  scaleTargetRef:
    name: worker
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 30
  cooldownPeriod:  300
  triggers:
    - type: aws-cloudwatch
      authenticationRef:
        name: keda-auth
      metadata:
        namespace: AWS/AmazonMQ
        dimensionName: Broker;Queue
        dimensionValue: production;worker
        metricName: MessageCount
        metricStat: Average
        metricUnit: Count
        metricStatPeriod: '60'
        metricCollectionTime: '60'
        targetMetricValue: '10'
        minMetricValue: '0'
        awsRegion: us-east-1
```

Running the following query in CloudWatch UI with 1 minute period returns a number above 0:
`SELECT AVG(MessageCount) FROM "AWS/AmazonMQ" WHERE Broker = 'production' and Queue = 'worker'`

While `keda-operator` log repeatedly shows:
`aws_cloudwatch_scaler	empty metric data received, returning minMetricValue`

I've also tested the same config, but without the Queue dimension and I got a number above 0, so I know it works and that the issue has something to do with the multiple dimensions feature.

### Expected Behavior

Getting a number above 0 for the requested metric.

### Actual Behavior

Getting 0 for the requested metric.

### Steps to Reproduce the Problem

1.  Deploy a managed RabbitMQ - Amazon MQ
2. Deploy the `ScaledObject` config
3. Check `keda-operator` log

### Logs from KEDA operator

```
1.6473359324006155e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
1.6473359324026015e+09	INFO	setup	Running on Kubernetes 1.21+	{"version": "v1.21.5-eks-bc4871b"}
1.6473359324028835e+09	INFO	setup	Starting manager
1.6473359324029562e+09	INFO	setup	KEDA Version: 2.6.1
1.64733593240299e+09	INFO	setup	Git Commit: efca71d6bc770408468a9e1a4b3984f7136c0967
1.6473359324030223e+09	INFO	setup	Go Version: go1.17.3
1.6473359324030423e+09	INFO	setup	Go OS/Arch: linux/amd64
1.6473359324034576e+09	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
1.6473359324034605e+09	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
I0315 09:18:52.403596       1 leaderelection.go:248] attempting to acquire leader lease keda/operator.keda.sh...
I0315 09:19:36.449460       1 leaderelection.go:258] successfully acquired lease keda/operator.keda.sh
1.6473359764499505e+09	INFO	controller.scaledobject	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "source": "kind source: *v1alpha1.ScaledObject"}
1.647335976450036e+09	INFO	controller.scaledobject	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "source": "kind source: *v2beta2.HorizontalPodAutoscaler"}
1.6473359764500802e+09	INFO	controller.scaledobject	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject"}
1.6473359764505255e+09	INFO	controller.triggerauthentication	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication", "source": "kind source: *v1alpha1.TriggerAuthentication"}
1.6473359764505723e+09	INFO	controller.triggerauthentication	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication"}
1.6473359764506705e+09	INFO	controller.scaledjob	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob", "source": "kind source: *v1alpha1.ScaledJob"}
1.6473359764507174e+09	INFO	controller.scaledjob	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob"}
1.6473359764499505e+09	INFO	controller.scaledobject	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "source": "kind source: *v1alpha1.ScaledObject"}
1.647335976450036e+09	INFO	controller.scaledobject	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "source": "kind source: *v2beta2.HorizontalPodAutoscaler"}
1.6473359764500802e+09	INFO	controller.scaledobject	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject"}
1.6473359764505255e+09	INFO	controller.triggerauthentication	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication", "source": "kind source: *v1alpha1.TriggerAuthentication"}
1.6473359764505723e+09	INFO	controller.triggerauthentication	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication"}
1.6473359764506705e+09	INFO	controller.scaledjob	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob", "source": "kind source: *v1alpha1.ScaledJob"}
1.6473359764507174e+09	INFO	controller.scaledjob	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "ScaledJob"}
1.6473359764508784e+09	INFO	controller.clustertriggerauthentication	Starting EventSource	{"reconciler group": "keda.sh", "reconciler kind": "ClusterTriggerAuthentication", "source": "kind source: *v1alpha1.ClusterTriggerAuthentication"}
1.647335976450922e+09	INFO	controller.clustertriggerauthentication	Starting Controller	{"reconciler group": "keda.sh", "reconciler kind": "ClusterTriggerAuthentication"}
1.6473359765509717e+09	INFO	controller.triggerauthentication	Starting workers	{"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication", "worker count": 1}
1.647335976551054e+09	INFO	controller.scaledobject	Starting workers	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "worker count": 5}
1.6473359765512447e+09	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "worker, "namespace": "default"}
1.6473359765512555e+09	INFO	controller.clustertriggerauthentication	Starting workers	{"reconciler group": "keda.sh", "reconciler kind": "ClusterTriggerAuthentication", "worker count": 1}
1.6473360069127352e+09	INFO	aws_cloudwatch_scaler	empty metric data received, returning minMetricValue
1.6473360368981402e+09	INFO	aws_cloudwatch_scaler	empty metric data received, returning minMetricValue
1.647336066911557e+09	INFO	aws_cloudwatch_scaler	empty metric data received, returning minMetricValue
```

### KEDA Version

2.6.1

### Kubernetes Version

1.21

### Platform

Amazon Web Services

### Scaler Details

AWS CloudWatch
