### ISSUE TITLE
EventHub scaler cannot find checkpoint blob when using pod identity.

### ISSUE THREAD

**Issue by v-shenoy** [kedacore/keda#2781]
### Report

I have an EventHub Azure Function using the KEDA scaler setup as follows -
```yaml
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: eventhub-trigger-auth
  namespace: default
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: eventhub
  labels: {}
spec:
  scaleTargetRef:
    name: eventhub
  minReplicaCount: 0
  maxReplicaCount: 2
  pollingInterval: 10
  cooldownPeriod: 30
  triggers:
  - type: azure-eventhub
    metadata:
      direction: in
      eventHubNamespace: non-public-clouds-ns
      eventHubName: python-hub
      cardinality: many
      consumerGroup: $Default
      dataType: binary
      checkpointStrategy: azureFunction
      # connectionFromEnv: ehConnectionString
      storageConnectionFromEnv: AzureWebJobsStorage
    authenticationRef:
      name: eventhub-trigger-auth
---
```

The scaler is unable to find the blob storing the checkpoint and the deployment is always scaled to maximum number of replicas.

### Expected Behavior

The deployment should be scaled to the appropriate number of replicas as per the unprocessed event threshold specified in the ScaledObject defintion.

### Actual Behavior

The scaler is unable to find the blob storing the checkpoint and the deployment is always scaled to maximum number of replicas.

### Steps to Reproduce the Problem

1. Create an EventHub Azure Function using core tools.
2. Configure the ScaledObject to use TriggerAuthentication with pod identity.
3. Deploy the application along with the KEDA resources to an AKS cluster. 

### Logs from KEDA operator

``` 
1.6478669629715395e+09  ERROR   azure_eventhub_scaler   Blob container :  not found to use checkpoint strategy, getting unprocessed event count without checkpoint {"error": "-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.14.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=BlobNotFound) =====\nDescription=The specified blob does not exist.\nRequestId:1ed17a05-501e-0044-1222-3de429000000\nTime:2022-03-21T12:49:22.9703815Z, Details: \n   Code: BlobNotFound\n   GET https://nonpubliccloudsstorage.blob.core.windows.net/azure-webjobs-eventhub/non-public-clouds-ns/python-hub/$Default/1?timeout=61\n   Authorization: REDACTED\n   User-Agent: [Azure-Storage/0.14 (go1.17.3; linux)]\n   X-Ms-Client-Request-Id: [9ce91fe6-72a6-4904-6ff6-600223bda881]\n   X-Ms-Date: [Mon, 21 Mar 2022 12:49:22 GMT]\n   X-Ms-Version: [2020-04-08]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 404 The specified blob does not exist.\n   Content-Length: [215]\n   Content-Type: [application/xml]\n   Date: [Mon, 21 Mar 2022 12:49:22 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [9ce91fe6-72a6-4904-6ff6-600223bda881]\n   X-Ms-Error-Code: [BlobNotFound]\n   X-Ms-Request-Id: [1ed17a05-501e-0044-1222-3de429000000]\n   X-Ms-Version: [2020-04-08]\n\n\n"}
github.com/kedacore/keda/v2/pkg/scalers.(*azureEventHubScaler).GetUnprocessedEventCountInPartition
        /workspace/pkg/scalers/azure_eventhub_scaler.go:189
github.com/kedacore/keda/v2/pkg/scalers.(*azureEventHubScaler).IsActive
        /workspace/pkg/scalers/azure_eventhub_scaler.go:255
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive
        /workspace/pkg/scaling/cache/scalers_cache.go:87
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:149
```

### KEDA Version

Other

### Kubernetes Version

1.21

### Platform

Microsoft Azure

### Scaler Details

Azure EventHub

### Anything else?

The [getHubAndNamespace](https://github.com/kedacore/keda/blob/293d396778ea4e20456933dd43e8851b047852ae/pkg/scalers/azure/azure_eventhub.go#L81) method is used for [resolving](https://github.com/kedacore/keda/blob/293d396778ea4e20456933dd43e8851b047852ae/pkg/scalers/azure/azure_eventhub_checkpoint.go#L145) the blob path within the storage account.

When a connection string is specified eg. - 
`Endpoint=sb://eventhub-namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=secretKey123;EntityPath=eventhub-name`

It returns the namespace as `eventhub-namespace.servicebus.windows.net`

When using pod identity, it returns the namespace as specified in the ScaledObject trigger metadata which is `eventhub-namespace`
