### ISSUE TITLE
ClusterTriggerAuthentication to support headers so that accountId can be passed for NewRelic Scaler via authenticationRef

### ISSUE THREAD

**Issue by pragmaticivan** [kedacore/keda#2883]
### Proposal

```
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: newrelic
spec:
  secretTargetRef:
  - parameter: account
    name: keda-newrelic-creds
    key: account-number
  - parameter: queryKey
    name: keda-newrelic-creds
    key: api-key
```

### Use-Case

Have multiple New Relic accounts and want to be able to set, apiKey, account number and region in the cluster authentication so developers don't need to care about that.

This would also help with NewRelic promql, which requires an api-key in different ways.
