### ISSUE TITLE
Cannot connect to AWS ElastiCache Redis using TLS

### ISSUE THREAD

**Issue by mhemken-vts** [kedacore/keda#2903]
### Report

We cannot authenticate with ElastiCache Redis using the available connection parameters.

### Expected Behavior

We expect to authenticate with ElastiCache redis.

### Actual Behavior

We authenticate with ElastiCache using this URL:
`rediss://:<token>@master.<name>.<identifier>.use2.cache.amazonaws.com:6379`

When we specify `enableTls=True`:

```
│ Events:                                                                                                                                                                                 │
│   Type     Reason                   Age               From           Message                                                                                                            │
│   ----     ------                   ----              ----           -------                                                                                                            │
│   Warning  KEDAScalerFailed         3s (x11 over 8s)  keda-operator  connection to redis failed: NOAUTH Authentication required.                                                        │
│   Warning  ScaledObjectCheckFailed  3s (x11 over 8s)  keda-operator  Failed to ensure HPA is correctly created for ScaledObject                                                         │
```

When we specify `enableTls=False`:

```
│ Events:                                                                                                                                                                                 │
│   Type     Reason                   Age   From           Message                                                                                                                        │
│   ----     ------                   ----  ----           -------                                                                                                                        │
│   Warning  KEDAScalerFailed         2s    keda-operator  connection to redis failed: read tcp 10.2.151.197:51584->10.2.131.250:6379: i/o timeout                                        │
│   Warning  ScaledObjectCheckFailed  2s    keda-operator  Failed to ensure HPA is correctly created for ScaledObject                                                                     │
```

### Steps to Reproduce the Problem

1. Deploy ScaledObject with this yaml:
```
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: workload-name  
  labels:
    app: workload-name
    deploymentName: workload-name
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workload-name
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicaCount: 0
  maxReplicaCount: 100
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: redis
    metadata:
      address: "master.<name>.<identifier>.use2.cache.amazonaws.com:6379"
      password: "<password>"
      listName: list-name
      listLength: "100"
      #enableTLS: "true"
```
2. wait for error.

### Logs from KEDA operator

No logs.

### KEDA Version

2.6.1

### Kubernetes Version

1.21

### Platform

Amazon Web Services

### Scaler Details

redis, redis-cluster

### Anything else?

I am able to connect to a redis pod deployed in the same cluster without authentication enabled.

We install KEDA with `kubectl kustomize . | kubectl apply -f -`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "https://github.com/kedacore/keda//config/default/?ref=main"
```
