### ISSUE TITLE
Provide support for using SAS token in Service Bus scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2920]
### Proposal

Provide support for using [SAS token in Service Bus scaler](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas).

### Use-Case

Different scenario for authentication, similar to https://github.com/kedacore/keda/issues/2705

**Comment by SushmithaVReddy** [comment]
Working on this.

**Comment by SushmithaVReddy** [comment]
@tomkerkhove quick doubt - SAS authentication is currently handled if it's provided through the connection string. Are we looking at a provision to use SAS token other than through connection string?

**Comment by tomkerkhove** [comment]
If that's the case then we can close it, I thought we didn't support that yet.

Thanks for checking!

**Comment by zzhakhin** [comment]
@tomkerkhove @SushmithaVReddy I try to setup scaledObject with trigger "azure-servicebus" that uses SAS token(trigger authentication ---> k8s secret). At the current moment KEDA 2.6 doesn't support this feature. 

When I deploy the scaledObject with SAS token, I get ' "Endpoint" must not be empty' error message.

https://github.com/Azure/azure-amqp-common-go/blob/6b7304f631077f049a7249a2f36fe87e5c27b674/conn/conn.go#L100

Could you try to use new lib for Azure Service Bus we you can send SAS token as connection parameter?

https://github.com/Azure/azure-sdk-for-go/blob/241bdb849ce431e1a5e398a5649cde93149ee374/sdk/messaging/azservicebus/client.go#L92

**Comment by tomkerkhove** [comment]
@SushmithaVReddy Can you verify this please?

**Comment by SushmithaVReddy** [comment]
Hi @zzhakhin , are you using a key value pair like "connectionString" : " Endpoint=sb://<sb>.servicebus.windows.net;SharedAccessSignature=SharedAccessSignature sr=<sb>.servicebus.windows.net&sig=<base64-sig>&se=<expiry>&skn=<keyname>" in your trigger auth CRD referred in scaled object?

**Comment by zzhakhin** [comment]
Hi @SushmithaVReddy. These are my setup

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaledobject
  namespace: somenamespace
spec:
  scaleTargetRef:
    name: nameofpod
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 3
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: queue-name
      messageCount: "5"
    authenticationRef:
      name: worker-trigger-authentication
```
      
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: worker-trigger-authentication
  namespace: somenamespace
spec:
  secretTargetRef:
  - parameter: connection
    name: worker-queue-secret
    key: queue-connection-string
```
And I create secret with key:value

`queue-connection-string='SharedAccessSignature sr=https://servicebussand.servicebus.windows.net/queue-name&sig=<Signature>&se=<Unixtime>&skn=root'`
