### ISSUE TITLE
Autoscaler fails to get API response from API URL combined from Kubernetes service name and port

### ISSUE THREAD

**Issue by Tazovsky** [kedacore/keda#2926]
### Report

Autoscaler fails to get API response from API URL combined from kubernetes service name `scaling-api` and port `8000`:

```
1.650466389754813e+09	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "http-scaledobject-whoami", "scaledObject.Namespace": "ilmari-mihu", "scaleTarget.Name": "whoami", "error": "api returned 404"}
```

Command executed from Kubernetes POD returns API response correctly:

```
root@ggtips-7b95b67f6b-gh79n:/# curl http://scaling-api:8000/stats?name=whoami
{"name":"ilmari-mihu-whoami-web-9ab4060701404e59ffcd@kubernetescrd","is_busy":0,"availableServerCount":3,"freeServerCount":3,"timestamp":1650466631}
```

Kubernetes service configuration:

```
kind: Service
apiVersion: v1
metadata:
  name: scaling-api
  namespace: traefik
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: scaling-api
    protocol: TCP
  selector:
    app: api
  ```

`ScaledObject` configuration:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaledobject-ggtips
  namespace: traefik
  labels:
    deploymentName: ggtips
spec:
  maxReplicaCount: 12
  scaleTargetRef:
    name: ggtips
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://scaling-api:8000/stats?name=ggtips"
        valueLocation: 'freeServerCount'
 ```

### Expected Behavior

Autoscaler should be able to get response from API URL combined from Kubernetes service name and port, for example `http://scaling-api:8000/stats?name=whoami`

### Actual Behavior

Autoscaler is unable to query API:

```
1.650466389754813e+09	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "http-scaledobject-whoami", "scaledObject.Namespace": "ilmari-mihu", "scaleTarget.Name": "whoami", "error": "api returned 404"}
```

### Steps to Reproduce the Problem

-

### Logs from KEDA operator

```
root@ggtips-7b95b67f6b-gh79n:/# curl http://scaling-api:8000/stats?name=whoami
{"name":"ilmari-mihu-whoami-web-9ab4060701404e59ffcd@kubernetescrd","is_busy":0,"availableServerCount":3,"freeServerCount":3,"timestamp":1650466631}
```

### KEDA Version

2.6.1

### Kubernetes Version

1.23

### Platform

Amazon Web Services

**Comment by JorTurFer** [comment]
Hey @Tazovsky ,
I'd say that the problem is related with the serviceName that you are using. Please, use the service name and also the namespace for the url.  
The "long explanation" is all the pods inside the namespace, the service is enough, but KEDA is in its own namespace and your service is not available on it. That's why you can execute curl from the pod. The other option is creating the service in KEDA namespace as externalName service and there just redirect to the other using serviceName.namespace, but at the end of the day it's overkill for only avoiding the usage of serviceName.namespace in the trigger metadata.
Something like:
```yaml
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://scaling-api.traefik:8000/stats?name=ggtips"
        valueLocation: 'freeServerCount'
```
