### ISSUE TITLE
Datadog scaler: no matching metrics

### ISSUE THREAD

**Issue by sebanazarian** [kedacore/keda#2930]
### Report

I want scale a pod with metrics from datadog but I couldn't.

Describe of the scaled objet:

```bash
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-datadog-secret
  namespace: keda-test
spec:
  secretTargetRef:
  - parameter: apiKey
    name: datadog-secrets
    key: apiKey
  - parameter: appKey
    name: datadog-secrets
    key: appKey
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: datadog-scaledobject
  namespace: keda-test
spec:
  scaleTargetRef:
    apiVersion:    apps/v1                           
    kind:          Deployment                        
    name:          nginx-deployment-datadog                   
  pollingInterval:  5                               
  minReplicaCount:  1                                
  maxReplicaCount:  5                              
  triggers:
  - type: datadog
    metadata:
      query: "sum:kubernetes.pods.running{kube_namespace:keda-test,cluster_name:keda-cluster}"
      queryValue: "4"
      age: "10"
    authenticationRef:
      name: keda-trigger-auth-datadog-secret
      
```

Describe of the HPA:

```bash
Name:                                                               keda-hpa-datadog-scaledobject
Namespace:                                                          keda-test
Labels:                                                             app.kubernetes.io/managed-by=keda-operator
                                                                    app.kubernetes.io/name=keda-hpa-datadog-scaledobject
                                                                    app.kubernetes.io/part-of=datadog-scaledobject
                                                                    app.kubernetes.io/version=2.6.1
                                                                    scaledobject.keda.sh/name=datadog-scaledobject
Annotations:                                                        <none>
CreationTimestamp:                                                  Fri, 22 Apr 2022 21:04:39 -0300
Reference:                                                          Deployment/nginx-deployment-datadog
Metrics:                                                            ( current / target )
  "s0-datadog-sum-kubernetes-pods-running" (target average value):  <unknown> / 4
Min replicas:                                                       1
Max replicas:                                                       5
Deployment pods:                                                    1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric keda-test/s0-datadog-sum-kubernetes-pods-running/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: datadog-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-datadog-sum-kubernetes-pods-running
Events:
  Type     Reason                        Age                    From                       Message
  ----     ------                        ----                   ----                       -------
  Warning  FailedComputeMetricsReplicas  40m (x12 over 43m)     horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get s0-datadog-sum-kubernetes-pods-running external metric: unable to get external metric keda-test/s0-datadog-sum-kubernetes-pods-running/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: datadog-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-datadog-sum-kubernetes-pods-running
  Warning  FailedGetExternalMetric       2m51s (x159 over 43m)  horizontal-pod-autoscaler  unable to get external metric keda-test/s0-datadog-sum-kubernetes-pods-running/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: datadog-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-datadog-sum-kubernetes-pods-running
```

### Expected Behavior

No failure event on the HPA

Scaling pods with datadog metrics

### Actual Behavior

Failure event on the HPA.

The object does not scale

### Steps to Reproduce the Problem

1. kubectl create deployment nginx-deployment-datadog --image nginx -n keda-test
2. Apply  ScaledObject

### Logs from KEDA operator

Log keda-metrics-apiserver:
```
E0423 00:20:31.943388       1 provider.go:124] keda_metrics_adapter/provider "msg"="error getting metric for scaler" "error"="error getting metrics from Datadog: no Datadog metrics returned"  "scaledObject.Name"="datadog-scaledobject" "scaledObject.Namespace"="keda-test" "scaler"={}
E0423 00:20:31.943661       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no matching metrics found for s0-datadog-sum-kubernetes-pods-running"}: no matching metrics found for s0-datadog-sum-kubernetes-pods-running
E0423 00:20:47.135279       1 logr.go:270] keda_metrics_adapter/datadog_scaler "msg"="error getting metrics from Datadog" "error"="no Datadog metrics returned"
E0423 00:20:47.312257       1 logr.go:270] keda_metrics_adapter/datadog_scaler "msg"="error getting metrics from Datadog" "error"="no Datadog metrics returned"
```

### KEDA Version

2.6.1

### Kubernetes Version

1.21

### Platform

Amazon Web Services

### Scaler Details

Datadog

**Comment by JorTurFer** [comment]
Hi,
Sorry for the delay on response :(
Could you also share operator logs? Could this be already solved with latest changes in the scaler @arapulido ?

**Comment by sebanazarian** [comment]
Log keda-operator
```
1.6512754995241346e+09  INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
1.6512754995262947e+09  INFO    setup   Running on Kubernetes 1.21+     {"version": "v1.21.5-eks-bc4871b"}
1.6512754995265932e+09  INFO    setup   Starting manager
1.6512754995267165e+09  INFO    setup   KEDA Version: 2.6.1
1.6512754995267892e+09  INFO    setup   Git Commit: efca71d6bc770408468a9e1a4b3984f7136c0967
1.6512754995268617e+09  INFO    setup   Go Version: go1.17.3
1.6512754995269434e+09  INFO    setup   Go OS/Arch: linux/amd64
1.6512754995272608e+09  INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
1.651275499527264e+09   INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
I0429 23:38:19.527339       1 leaderelection.go:248] attempting to acquire leader lease keda/operator.keda.sh...
I0429 23:38:19.549377       1 leaderelection.go:258] successfully acquired lease keda/operator.keda.sh
1.6512754995498044e+09  INFO    controller.scaledobject Starting EventSource    {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "source": "kind source: *v1alpha1.ScaledObject"}
1.651275499549932e+09   INFO    controller.scaledobject Starting EventSource    {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "source": "kind source: *v2beta2.HorizontalPodAutoscaler"}
1.651275499550015e+09   INFO    controller.scaledobject Starting Controller     {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject"}
1.6512754995501623e+09  INFO    controller.triggerauthentication        Starting EventSource    {"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication", "source": "kind source: *v1alpha1.TriggerAuthentication"}
1.651275499550189e+09   INFO    controller.triggerauthentication        Starting Controller     {"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication"}
1.6512754995502841e+09  INFO    controller.scaledjob    Starting EventSource    {"reconciler group": "keda.sh", "reconciler kind": "ScaledJob", "source": "kind source: *v1alpha1.ScaledJob"}
1.651275499550324e+09   INFO    controller.scaledjob    Starting Controller     {"reconciler group": "keda.sh", "reconciler kind": "ScaledJob"}
1.651275499550438e+09   INFO    controller.clustertriggerauthentication Starting EventSource    {"reconciler group": "keda.sh", "reconciler kind": "ClusterTriggerAuthentication", "source": "kind source: *v1alpha1.ClusterTriggerAuthentication"}
1.651275499550482e+09   INFO    controller.clustertriggerauthentication Starting Controller     {"reconciler group": "keda.sh", "reconciler kind": "ClusterTriggerAuthentication"}
1.651275499951445e+09   INFO    controller.scaledjob    Starting workers        {"reconciler group": "keda.sh", "reconciler kind": "ScaledJob", "worker count": 1}
1.651275499951494e+09   INFO    controller.triggerauthentication        Starting workers        {"reconciler group": "keda.sh", "reconciler kind": "TriggerAuthentication", "worker count": 1}
1.651275499951445e+09   INFO    controller.scaledobject Starting workers        {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "worker count": 5}
1.6512754999515328e+09  INFO    controller.clustertriggerauthentication Starting workers        {"reconciler group": "keda.sh", "reconciler kind": "ClusterTriggerAuthentication", "worker count": 1}
1.6512756266299636e+09  INFO    controller.scaledobject Reconciling ScaledObject        {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "datadog-scaledobject", "namespace": "keda-test"}
1.6512756266299856e+09  INFO    controller.scaledobject Adding Finalizer for the ScaledObject   {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "datadog-scaledobject", "namespace": "keda-test"}
1.651275626672114e+09   INFO    controller.scaledobject Detected resource targeted for scaling  {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "datadog-scaledobject", "namespace": "keda-test", "resource": "apps/v1.Deployment", "name": "nginx-deployment-datadog"}
1.6512756266722133e+09  INFO    controller.scaledobject Creating a new HPA      {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "datadog-scaledobject", "namespace": "keda-test", "HPA.Namespace": "keda-test", "HPA.Name": "keda-hpa-datadog-scaledobject"}
1.6512756269615564e+09  INFO    controller.scaledobject Initializing Scaling logic according to ScaledObject Specification      {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "datadog-scaledobject", "namespace": "keda-test"}
1.6512756269721518e+09  INFO    controller.scaledobject Reconciling ScaledObject        {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "datadog-scaledobject", "namespace": "keda-test"}
1.6512756426162288e+09  INFO    controller.scaledobject Reconciling ScaledObject        {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "datadog-scaledobject", "namespace": "keda-test"}
```

**Comment by arapulido** [comment]
@sebanazarian The Datadog scaler has changed quite a bit between 2.6 and future 2.7. Can you maybe try with what's on main to see if you still get the issue? Thanks!

@JorTurFer when are we expecting a new keda release?

**Comment by JorTurFer** [comment]
> @JorTurFer when are we expecting a new keda release?

I'm not sure if this week or next week. I'd say that on 5th, but I don't remember the exact date

**Comment by JorTurFer** [comment]
I have checked last meeting notes and we aim to May 5th

**Comment by sebanazarian** [comment]
@JorTurFer @arapulido  perfect, I will try with Keda 2.7 and I will tell the news.


Thanks!

**Comment by sebanazarian** [comment]
Hi,

I tried Keda 2.7 with DatadogScaler and the deploy scaled. 

But I have a problem when I want scale with Datadog Scaler.

1. It takes a long time for scale
2. Sometimes it throws me the following error and it fixes itself

**KEDA VERSION 2.7**

**ScaledObject**
```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-datadog-secret
  namespace: keda-test
spec:
  secretTargetRef:
  - parameter: apiKey
    name: datadog-secrets
    key: apiKey
  - parameter: appKey
    name: datadog-secrets
    key: appKey
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: datadog-scaledobject
  namespace: keda-test
spec:
  scaleTargetRef:
    apiVersion:    apps/v1                           
    kind:          Deployment                        
    name:          nginx-deployment-datadog
  pollingInterval:  10                               
  minReplicaCount:  1                                
  maxReplicaCount:  3                             
  triggers:
  - type: datadog
    metadata:
      # Optional: (Value or AverageValue). Whether the target value is global or average per pod. Default: AverageValue
      # metricType: "Value"
      query: "sum:aws.sqs.approximate_number_of_messages_visible{region:us-east-1,queuename:keda-datadog}" #  prod-ds-list-ingestion-queue ga-xdr-migrate-4886 # keda-test #prod-ds-list-ingestion-queue
      queryValue: "2"
      # Optional: The time window (in seconds) to retrieve metrics from Datadog. Default: 90
      age: "120"
      # Optional: The metric value to return to the HPA if a metric value wasn't found for the specified time window
      # metricUnavailableValue: "0"

    authenticationRef:
      name: keda-trigger-auth-datadog-secret

```





**Log keda-metrics-apiserver**
```bash

E0517 03:05:22.333544       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"no matching metrics found for s0-datadog-sum-aws-sqs-approximate_number_of_messages_visible"}: no matching metrics found for s0-datadog-sum-aws-sqs-approximate_number_of_messages_visible
E0517 03:05:37.507403       1 logr.go:279] keda_metrics_adapter/datadog_scaler "msg"="error getting metrics from Datadog" "error"="no Datadog metrics returned for the given time window"
E0517 03:05:37.678856       1 logr.go:279] keda_metrics_adapter/datadog_scaler "msg"="error getting metrics from Datadog" "error"="no Datadog metrics returned for the given time window"
E0517 03:05:37.692443       1 provider.go:124] keda_metrics_adapter/provider "msg"="error getting metric for scaler" "error"="error getting metrics from Datadog: no Datadog metrics returned for the given time window"  "scaledObject.Name"="datadog-scaledobject" "scaledObject.Namespace"="keda-test" "scaler"={}
```


**Log Keda-operator**
```yaml
 1.6527567100243418e+09  ERROR   scalehandler    Error getting scale decision    {"scaledobject.Name": "datadog-scaledobject", "scaledObject.Namespace": "keda-test", "scaleTarget.Name": "nginx-deployment-datadog", "error": "no Datadog metrics returned for the given time window"}
```

**Describe ScaleObject**
```yaml

Name:         datadog-scaledobject
Namespace:    keda-test
Labels:       scaledobject.keda.sh/name=datadog-scaledobject
Annotations:  <none>
API Version:  keda.sh/v1alpha1
Kind:         ScaledObject
Metadata:
  Creation Timestamp:  2022-05-17T03:03:49Z
  Finalizers:
    finalizer.keda.sh
  Generation:  1
  Managed Fields:
    API Version:  keda.sh/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:maxReplicaCount:
        f:minReplicaCount:
        f:pollingInterval:
        f:scaleTargetRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
        f:triggers:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-05-17T03:03:49Z
    API Version:  keda.sh/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:health:
          .:
          f:s0-datadog-sum-aws-sqs-approximate_number_of_messages_visible:
            .:
            f:numberOfFailures:
            f:status:
    Manager:      keda-adapter
    Operation:    Update
    Time:         2022-05-17T03:04:05Z
    API Version:  keda.sh/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizer.keda.sh":
        f:labels:
          .:
          f:scaledobject.keda.sh/name:
      f:status:
        .:
        f:conditions:
        f:externalMetricNames:
        f:lastActiveTime:
        f:originalReplicaCount:
        f:scaleTargetGVKR:
          .:
          f:group:
          f:kind:
          f:resource:
          f:version:
        f:scaleTargetKind:
    Manager:         keda
    Operation:       Update
    Time:            2022-05-17T03:07:19Z
  Resource Version:  25126705
  UID:               3ed34aa4-cd8b-42df-8d1b-e8da62115c09
Spec:
  Max Replica Count:  3
  Min Replica Count:  1
  Polling Interval:   10
  Scale Target Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         nginx-deployment-datadog
  Triggers:
    Authentication Ref:
      Name:  keda-trigger-auth-datadog-secret
    Metadata:
      Age:          120
      Query:        sum:aws.sqs.approximate_number_of_messages_visible{region:us-east-1,queuename:keda-datadog}
      Query Value:  2
    Type:           datadog
Status:
  Conditions:
    Message:  Triggers defined in ScaledObject are not working correctly
    Reason:   TriggerError
    Status:   False
    Type:     Ready
    Message:  Scaling is not performed because triggers are not active
    Reason:   ScalerNotActive
    Status:   False
    Type:     Active
    Message:  No fallbacks are active on this scaled object
    Reason:   NoFallbackFound
    Status:   False
    Type:     Fallback
  External Metric Names:
    s0-datadog-sum-aws-sqs-approximate_number_of_messages_visible
  Health:
    s0-datadog-sum-aws-sqs-approximate_number_of_messages_visible:
      Number Of Failures:  23
      Status:              Failing
  Last Active Time:        2022-05-17T03:07:59Z
  Original Replica Count:  1
  Scale Target GVKR:
    Group:            apps
    Kind:             Deployment
    Resource:         deployments
    Version:          v1
  Scale Target Kind:  apps/v1.Deployment
Events:
  Type     Reason              Age                  From           Message
  ----     ------              ----                 ----           -------
  Normal   KEDAScalersStarted  10m                  keda-operator  Started scalers watch
  Warning  KEDAScalerFailed    8m18s                keda-operator  error when retrieving Datadog metrics: Get "https://api.datadoghq.com/api/v1/query?from=1652756619&query=sum%3Aaws.sqs.approximate_number_of_messages_visible%7Bregion%3Aus-east-1%2Cqueuename%3Akeda-datadog%7D&to=1652756739": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Normal   ScaledObjectReady   6m35s (x3 over 10m)  keda-operator  ScaledObject is ready for scaling
  Warning  KEDAScalerFailed    10s (x55 over 10m)   keda-operator  no Datadog metrics returned for the given time window
```

Thanks!!!!!
