### ISSUE TITLE
[Scaler Spec] Change Scaler specification to provide more flexible authentication mechanisms

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#297]
We have a couple of issues where we'd like to be more flexible in the way we authenticate with scalers and where they are configured.

This issue tracks this discussion and will be used in the technical meeting to revise the current ScalerObject specification to support this.

Relates to #263 & #161

**Comment by tomkerkhove** [comment]
A technical discussion on this is being organized. If you want to participate, please [fill in this Doodle](https://doodle.com/poll/gxnxq4texw6av3mf) which lists some proposed slots.

Please include your email address in the Doodle or write to kerkhove.tom@gmail.com so I can send the invite.

**Comment by tomkerkhove** [comment]
I think the last required people I'd like to have on the call are @jeffhollan @anirudhgarg	 @yaron2 	but don't feel obliged.

**Comment by tomkerkhove** [comment]
A meeting is scheduled for Tuesday 23rd of July at 6:00 PM UTC / 11:00 AM (PDT).

**Comment by tomkerkhove** [comment]
Our current proposal is to introduce `authentication` which allows you to configure the mapping between trigger parameters (such as connection string, client id and/or client secret) across a variety of providers.

It's up to the trigger to clearly document the required parameters and provide validation around them.

```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-queue-po-id-scaledobject
  namespace: keda-aad-pod-id
  labels:
    deploymentName: keda-aad-pod-id
spec:
  scaleTargetRef:
    deploymentName: keda-aad-pod-id
  triggers:
  - type: azure-queue
    metadata:
      queueName: keda-test
      accountName: kedastoragequeuetest
      queueLength: "5"
    authentication:
      azureMsi: true # false by default
      secretRef: #Should be replaced with official secretKeyRef spec
      - parameter: awsClientSecret # Defined per trigger
        name: my-keda-secret-entity
        key: azure-storage-connectionstring
        namespace: my-keda-namespace # Optional, in case you want to point to KEDA namespace or namespace of deployment
      env:
      - parameter: awsClientId # Defined per trigger
        name: my-env-with-secret
        containerName: my-container
```

More on it tomorrow during the community standup.
