### ISSUE TITLE
Introduce metric aggregation/alignment in GCP Stackdriver scaler

### ISSUE THREAD

**Issue by ritmas** [kedacore/keda#3008]
### Proposal

It's crucial to have ability applying aggregation/alignment on GCP Stackdriver metric in order to both fetch less data from GCP API and get exactly what you need.

For instance, `aggregator` and `aligner` would be useful:

```yaml
triggers:
- type: gcp-stackdriver
  metadata:
    projectId: my-project-id
    filter: 'metric.type="loadbalancing.googleapis.com/https/backend_latencies" AND resource.type="https_lb_rule" AND resource.label.forwarding_rule_name="k8s2-..."'
    aggregator: 'mean | sum | 95th_percentile | etc.'
    aligner: 'delta | sum | 95th_percentile | etc.'
    targetValue: '10' # latency in ms
    credentialsFromEnv: GOOGLE_APPLICATION_CREDENTIALS_JSON
```
