### ISSUE TITLE
Prefix for 'goSDK' checkpoint strategy for Azure Event Hub scalter

### ISSUE THREAD

**Issue by brainslush** [kedacore/keda#3022]
### Proposal

I suggest to add the possibility to define a prefix for the 'goSDK' checkpoint strategy in the trigger specification of the Azure Event Hub scaler.

e.g.
``` 
triggers:
- type: azure-eventhub
  metadata:
    connectionFromEnv: EVENTHUB_CONNECTIONSTRING_ENV_NAME
    storageConnectionFromEnv: STORAGE_CONNECTIONSTRING_ENV_NAME
    consumerGroup: $Default
    unprocessedEventThreshold: '64'
    blobContainer: 'name_of_container'
    goSdkPrefix: 'someDir/dapr-dapreventhubname-daprconsumergroup-'
    checkpointStrategy: goSdk
``` 

The search path for the checkpoint file would look like:
`https://myaccount.blob.core.windows.net/name_of_container/someDir/dapr-dapreventhubname-daprconsumergroup-0`

### Use-Case

Allows usage of Keda together with DAPR and Azure Event Hub. 
Dapr creates files on the blob storage which are named
`{blobContainer}/dapr-{topic}-{consumerGroup}-{partitionId}` .
Keda on the other hand looks for
`{blobContainer}/{partiotionId}`.

### Anything else?

Even though I don't know go yet I would try myself on a PR.

**Comment by tomkerkhove** [comment]
There are two options here, we can do either or both:
1. Support a prefix/format, potentially requiring value injection as shown above
2. Support `dapr` checkpointing, but then this same problem might come up later on with another product

Thoughts @kedacore/keda-core-contributors?

**Comment by brainslush** [comment]
I would go with the value injection approach as it leaves room for customization.

**Comment by tomkerkhove** [comment]
That is a good option, but doing both might be good as well given every Dapr end-user would otherwise have to do this customization which is less trivial from a UX standpoint.

**Comment by brainslush** [comment]
A suggestion:

```
triggers:
- type: azure-eventhub
  metadata:
    connectionFromEnv: EVENTHUB_CONNECTIONSTRING_ENV_NAME
    storageConnectionFromEnv: STORAGE_CONNECTIONSTRING_ENV_NAME
    consumerGroup: $Default
    unprocessedEventThreshold: '64'
    blobContainer: 'name_of_container'
    goSdkTemplate: 'dapr'
    checkpointStrategy: goSdk
```
-> `{blobContainer}/dapr-{topic}-{consumerGroup}-{partitionId}`

```
triggers:
- type: azure-eventhub
  metadata:
    connectionFromEnv: EVENTHUB_CONNECTIONSTRING_ENV_NAME
    storageConnectionFromEnv: STORAGE_CONNECTIONSTRING_ENV_NAME
    consumerGroup: $Default
    unprocessedEventThreshold: '64'
    blobContainer: 'name_of_container'
    goSdkTemplate: 'prefix'
    goSdkPrefix: 'someDir/somePrefix-'
    checkpointStrategy: goSdk
```
-> `{blobContainer}/someDir/somePrefix-{partitionId}`
