### ISSUE TITLE
Add support to customize HPA name

### ISSUE THREAD

**Issue by aviadlevy** [kedacore/keda#3057]
### Proposal

Add new field to allow custom hpa name (and not just `keda-hpa-<name>`)  

### Use-Case

For example: 
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    ...
  labels:
    ...
  name: ...
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      hpaName: my-prsonal-hpa-name
```

Then keda will generate hpa named `my-prsonal-hpa-name`

### Anything else?

If you're thinking it's a good proposal, I would like to try implement it myself and open PR 🙏
