### ISSUE TITLE
KEDA Servicebus scaler HPA metric showing incorrect value

### ISSUE THREAD

**Issue by teebu** [kedacore/keda#3095]
### Report

![image](https://user-images.githubusercontent.com/5531844/171279683-f3af5c37-a15f-40ad-b6f8-8181da36fcc6.png)
I submit 1000 messages to service bus, and check the metrics.

### Expected Behavior

It should be a number like `1000 / 5` to indicate how many message are currently in the queue/topic.

### Actual Behavior

Shows a large number like `14704m / 5`

### Steps to Reproduce the Problem

Using azure generated deploy, I set the scaled object config as follows:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sb-testing
  namespace: cloudfunctions
  labels: {}
spec:
  scaleTargetRef:
    name: sb-testing
  pollingInterval: 5
  minReplicaCount: 0
  maxReplicaCount: 20
  triggers:
  - type: azure-servicebus
    metadata:
      direction: in
      topicName: sb-keda
      subscriptionName: sb-keda-sub
      connectionFromEnv: sbtriggertesting_SERVICEBUS
---
```

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Kubernetes Version

1.23

### Scaler Details

Azure Service Bus
