### ISSUE TITLE
ScaledObject ready condition changed will not fix HPA in some situation

### ISSUE THREAD

**Issue by champly** [kedacore/keda#3096]
### Report

ScaledObject:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  finalizers:
  - finalizer.keda.sh
  generation: 8
  labels:
    app: aabb-ab007
  name: aabb-ab007
  namespace: default
  ownerReferences:
  - apiVersion: basefeatures.symcn.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: BaseFeature
    name: aabb-ab007
    uid: f9ef1592-b164-4c55-a518-4eb01b832cce
spec:
  fallback:
    failureThreshold: 5
    replicas: 2
  maxReplicaCount: 3
  minReplicaCount: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aabb-ab007
  triggers:
  - metadata:
      app: aabb-ab007
      metricName: QPS
      scalerAddress: keda-external.default.svc:8080
      targetSize: "200"
    metricType: AverageValue
    name: QPS
    type: external
  - metadata:
      app: aabb-ab007
      value: "51"
    metricType: Utilization
    name: cpu
    type: cpu
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is performed because triggers are active
    reason: ScalerActive
    status: "True"
    type: Active
  - message: No fallbacks are active on this scaled object
    reason: NoFallbackFound
    status: "False"
    type: Fallback
  externalMetricNames:
  - s0-QPS
  health:
    s0-qps:
      numberOfFailures: 0
      status: Happy
  lastActiveTime: "2022-06-01T03:21:46Z"
  originalReplicaCount: 1
  resourceMetricNames:
  - cpu
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment

```

If my own `keda-external` service offline, `Keda metrics-apiserver` logic will update HPA resource current metrics, and will trigger `Keda operator` Reconcile to update `HPA.Spec`. And then, the `keda-external` service online, `Keda operator` just update `ScaledObject` Ready condition, but if the CPU metrics is zero, HPA resource will not modify, so `ScaledObject` will not fix `HAP` resource.

### Expected Behavior

Will auto fix `HPA` resource when the `keda-external` service back to normal.

### Actual Behavior

If the CPU metrics is zero always, the `HPA` resouce will not update.

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Kubernetes Version

1.20

### Platform

Any
