### ISSUE TITLE
Disabling scaledown is ignored

### ISSUE THREAD

**Issue by bakoontz2** [kedacore/keda#3140]
### Report

Kubernetes docs provide a means by which scaledowns can be disabled:

```
      behavior:
        scaleDown:
          selectPolicy: Disabled
```
However, ScaledObject doesn't seem to support this:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-scaledobject
spec:
  scaleTargetRef:
    name: test-keda-deploy
  pollingInterval: 30
  cooldownPeriod: 0
  #idleReplicaCount: 0
  minReplicaCount: 0
  maxReplicaCount: 1
  advanced:
    horizontalPodAutoScalerConfig:
      behavior:
        scaleDown:
          selectPolicy: Disabled
```

### Expected Behavior

The expected behavior is that a triggering event would scale up to 1 pod, but once that triggering event was removed from the queue, scaledown to 0 would be disabled.

### Actual Behavior

When the event queue is empty, the selectPolicy: Disabled directive is ignored and the pod count is scaled down to 0.

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Kubernetes Version

1.21

### Platform

Microsoft Azure

### Scaler Details

Azure Scaler Bus
