### ISSUE TITLE
Kafka scaler reports small number when some partitions are empty

### ISSUE THREAD

**Issue by 3schwartz** [kedacore/keda#3149]
### Report

In our cluster I have enabled a Kafka trigger. 

```
  triggers:
  - metadata:
      bootstrapServers: kafka:9092
      consumerGroup: some-group
      lagThreshold: "200"
      offsetResetPolicy: earliest
      topic: some-topic
    type: kafka
```

The topic have 100 partitions and only some with messages. The scaler reported 1836m/200  but there wasn't any lag on the consumer group.

After I had publish messages to all partitions the scaler ended up reported correct metric - hence reported zero lag after consumer had consumed all messages.

### Expected Behavior

Lag amount reported in HPA should be zero - like the true lag of the consumer group.

### Actual Behavior

Small lag amount was seen in the HPA which should be zero.

### Steps to Reproduce the Problem

1. Topic with 100 partitions
2. Only some partitions with messages

### Logs from KEDA operator

Only stable logs like below are reported.

```
1.654784800052318e+09   INFO    controller.scaledobject Reconciling ScaledObject        {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "some-scaler-scale", "namespace": "some-namespace"}
```

### KEDA Version

2.6.1

### Kubernetes Version

1.21

### Platform

Microsoft Azure

### Scaler Details

Kafka
