### ISSUE TITLE
Keda HPA scaling not working

### ISSUE THREAD

**Issue by kevin-staiger** [kedacore/keda#3155]
Hi I have an application that is scaling on kafka lag and my configuration is

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
    deploymentName: {{ .Chart.Name }}
spec:
  scaleTargetRef:
    deploymentName: {{ .Chart.Name }}
  pollingInterval: {{ .Values.autoscale.keda.pollingInterval }}
  cooldownPeriod:  {{ .Values.autoscale.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.replicas.min }}
  maxReplicaCount: {{ .Values.replicas.max }}
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: {{ .Values.autoscale.keda.kafkaBrokers }}
        consumerGroup: {{ .Values.autoscale.keda.consumerGroupToMonitor }}
        topic: {{ .Values.autoscale.keda.topicToMonitor }}
        lagThreshold: "{{  .Values.autoscale.keda.lagThreshold }}"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 2400
          policies:
            - type: Pods
              value: 1
              periodSeconds:  1200
        scaleUp:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 4
              periodSeconds: 60
```
   
I'm expecting that the max amount of pods that can be scaled down in a 20 min period to be 1 but i am consistently seeing it scale by more than one instance in a much faster time frame which is creating 'flapping' and spikes to my downstream calls due to constant scaling

events 

New size: 6; reason: All metrics below target
Source
horizontal-pod-autoscaler
Count
1
Sub-object
Last seen
2022-06-10T10:43:09-07:00

New size: 11; reason: All metrics below target
Source
horizontal-pod-autoscaler
Count
1
Sub-object
Last seen
2022-06-10T10:42:54-07:00

New size: 8; reason: All metrics below target
Source
horizontal-pod-autoscaler
Count
1
Sub-object
Last seen
2022-06-10T10:36:28-07:00

New size: 10; reason: All metrics below target
Source
horizontal-pod-autoscaler
Count
1
Sub-object
Last seen
2022-06-10T10:29:01-07:00

Am i missing something to avoid scaling so much?
