### ISSUE TITLE
PredictKube scaler ignores metricName value

### ISSUE THREAD

**Issue by vivekjainx86** [kedacore/keda#3180]
### Report

While using PredictKube scaler, I observed that it ignores given metricName value, and uses pre-defined prefix ([here](https://github.com/kedacore/keda/blob/2698fe1f47c100ef9b5ed4cdaa6c0359174e12f9/pkg/scalers/predictkube_scaler.go#L204)) . Because of this, the metric is not uniquely identified if I use multiple predictKube scalers.

Example:
```
- authenticationRef:
      kind: ClusterTriggerAuthentication
      name: predictkube-auth-secret
    metadata:
      historyTimeWindow: 7d
      metricName: web_predicted_requests_per_second_per_pod
      predictHorizon: 2h
      prometheusAddress: http://<prometheus-url>:9090
      query: <prometheus-query>
      queryStep: 5m
      threshold: "15"
    metricType: AverageValue
    type: predictkube
```

### Expected Behavior

It should set metric name as: `s0-predictkube-web_predicted_requests_per_second_per_pod` 

### Actual Behavior

It sets metric name as: `s0-predictkube-predictkube_metric`

### Steps to Reproduce the Problem

To reproduce the issue, you can use predictkube scaler in scaledobject, and see externalMetricName in scaledobject's status.

### KEDA Version

2.7.1

### Kubernetes Version

1.21

### Scaler Details

Predictkube

### Anything else?

I will make change and raise the PR.
