### ISSUE TITLE
Scaling of pods is pausing abruptly sometimes 

### ISSUE THREAD

**Issue by bjethwan** [kedacore/keda#3272]
### Report

I got below config

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: "removed"
spec:
  scaleTargetRef:
    deploymentName: "removed"
  minReplicaCount: 0
  cooldownPeriod:  30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: "removed"
      metricName: no_of_agents
      threshold: '2'
      query: no_of_agents 
      disableScaleToZero: 'true' 
```

And I had Prometheus reporting no_of_agents as 34, so I was expecting up to 17 pods, but looking at KEDA logs KEDA said that it's saling to 15 pods, so I thought it will create another couple of pods in next poll, but the next 2 pods came after 15mins. There were no pending pods, and enough number of Azure AKS nodes.

What is wrong here?

### Expected Behavior

I was expecting 17 pods in about 30 seconds ...default poll time. 

### Actual Behavior

After 15 pods, it took more than 15mins for next 2 pods to get created.
Check the KEDA HPA spec, it has some timestamp
[hpa.yml.zip](https://github.com/kedacore/keda/files/8966995/hpa.yml.zip)

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: keda-hpa-autoscale-transactbatchservice
  namespace: autoscale
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2022-06-09T08:12:31Z","reason":"ReadyForNewScale","message":"recommended
      size matches current size"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2022-06-23T06:11:24Z","reason":"ValidMetricFound","message":"the
      HPA was able to successfully calculate a replica count from external metric
      no_of_agents(\u0026LabelSelector{MatchLabels:map[string]string{deploymentName:
      autoscale-transactbatchservice,},MatchExpressions:[]LabelSelectorRequirement{},})"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2022-06-23T06:11:54Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"External","external":{"metricName":"no_of_agents","metricSelector":{"matchLabels":{"deploymentName":"autoscale-transactbatchservice"}},"currentValue":"0","currentAverageValue":"2"}}]'
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"External","external":{"metricName":"no_of_agents","metricSelector":{"matchLabels":{"deploymentName":"autoscale-transactbatchservice"}},"targetAverageValue":"2"}}]'
  creationTimestamp: "2022-06-09T08:12:16Z"
  labels:
    app.kubernetes.io/managed-by: keda-operator
    app.kubernetes.io/name: keda-hpa-autoscale-transactbatchservice
    app.kubernetes.io/version: 1.5.0
spec:
  maxReplicas: 100
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoscale-transactbatchservice
status:
  currentReplicas: 17
  desiredReplicas: 17
  lastScaleTime: "2022-06-23T06:55:52Z"
```

### Steps to Reproduce the Problem

Not sure

### Logs from KEDA operator

```
example
```

### KEDA Version

1.5.0

### Platform

Microsoft Azure

### Scaler Details

Prometheus
