### ISSUE TITLE
Support fields in scalers for identification

### ISSUE THREAD

**Issue by dogzzdogzz** [kedacore/keda#3302]
### Proposal

Can KEDA scaler support some fields like ```name``` or ```labels``` for identification ?
It's very common that one scaledObject or job has multiple triggers for same scaler like prometheus or cron but just with different queries or conditions. Currently all KEDA scalers don't have fields for identification, this limitation makes us difficult to dynamically manage the triggers by some script or operator.

### Use-Case

Our script periodically checks the events from calendar, if there is a new event scheduled in 2pm today for example, the script will add a new cron trigger to scaledobject for scaling, and remove it if event is finished. Without some fields for identification we only can manage the multiple cron triggers in an ugly way, compare the value of start/end parameters of all existing cron triggers, if exactly matches to the one for expired event, then remove it. With the identifiable fields we can just easily search the name or labels, remove it if matched

```yaml
triggers:
- type: cron
  metadata:
    name: daily_scaling_morning
    timezone: Asia/Kolkata
    start: 30 8 * * *
    end: 45 9 * * *
    desiredReplicas: "10"
- type: cron
  metadata:
    name: special_event_jul_1_noon
    labels:
      event_type: all_subscribers
    timezone: Asia/Kolkata
    start: 30 12 1 7 *
    end: 30 13 1 7 *
    desiredReplicas: "20"
- type: cron
  metadata:
    name: special_event_jul_1_evening
    labels:
      event_type: prime_subscribers
    timezone: Asia/Kolkata
    start: 30 18 1 7 *
    end: 45 20 1 7 *
    desiredReplicas: "20"
```
