### ISSUE TITLE
Azure Pipelines Scaler - private CA issue

### ISSUE THREAD

**Issue by RPM8887** [kedacore/keda#3309]
### Report

When using KEDA with an onprem/privately hosted Azure DevOps Server instance with HTTPS enabled signed by a private CA operator is unable to connect to the provided endpoint:
`error parsing azure Pipelines metadata: Get \"[https://xxxx.private.int/tfs/XYZ/_apis/distributedtask/pools?poolName=k8s-pool-test\":](https://xxxx.private.int/tfs/XYZ/_apis/distributedtask/pools?poolName=k8s-pool-test\%22:) x509: certificate signed by unknown authority"`

From what I've seen in the past, similar issues have already been reported for other scalers (eg.: RabbitMQ: https://github.com/kedacore/keda/issues/967). Any easy way of maybe injecting trusted CAs into the operator so that all scalers support them?

### Expected Behavior

Request successful

### Actual Behavior

Request fails because of untrusted certificate

### Steps to Reproduce the Problem

1. Configure Azure Pipelines ScalableObbject against an Azure DevOps instance that uses a privately signed certificate
2. Review operator logs

### Logs from KEDA operator

`error parsing azure Pipelines metadata: Get \"[https://xxxx.private.int/tfs/XYZ/_apis/distributedtask/pools?poolName=k8s-pool-test\":](https://xxxx.private.int/tfs/XYZ/_apis/distributedtask/pools?poolName=k8s-pool-test\%22:) x509: certificate signed by unknown authority"`

### KEDA Version

2.7.0

### Kubernetes Version

1.22

### Platform

Any

### Scaler Details

Azure DevOps Pipeline

**Comment by RPM8887** [comment]
ended up injecting the needed certificates from a configmap as a volume:
````
        volumeMounts:
        - name: certificates
          mountPath: /etc/ssl/certs/certs.pem
          subPath: private_ca
          readOnly: false
````
          
````
      volumes:
        - name: certificates
          configMap:
            name: certificates  
````
