### ISSUE TITLE
Blob container : 'name' not found to use checkpoint strategy, getting unprocessed event count without checkpoint

### ISSUE THREAD

**Issue by vickithedeveloper** [kedacore/keda#3441]
### Report

We are using custom function app within AKS cluster for processing data coming from the Azure Event Hub. The function app is written in python and is designed to consume the data from input event hub, transform the data and write it to an output event hub. As it’s an AKS based deployment we create a container image out of the function app definition.

For up scaling and downscaling the function app with respect to incoming load we are using the KEDA framework.

KEDA 2.7.1 is installed in the cluster using helm charts using the below command

helm install keda kedacore/keda --set podIdentity.activeDirectory.identity=aks_app_pod_identity --namespace aksNamepsace

Note –The above-mentioned pod identity has access to only input event hub and output event hub.

When we deploy the container to the AKS cluster, we are getting following exception randomly. 

1.6588329349315152e+09  ERROR   azure_eventhub_scaler   Blob container : azure-webjobs-eventhub not found to use checkpoint strategy, getting unprocessed event count without checkpoint  {"error": "-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=BlobNotFound) =====\nDescription=The specified blob does not exist.\nRequestId:0\nTime:2022-07-26T10:55:34.9302898Z, Details: \n 
  Code: BlobNotFound\n   GET https://stAccountName.blob.core.windows.net/azure-webjobs-eventhub/ehNamespace.servicebus.windows.net/ehName /$default/checkpoint/0?timeout=61\n   Authorization: REDACTED\n   User-Agent: [Azure-Storage/0.15 (go1.17.9; linux)]\n   X-Ms-Client-Request-Id: [4a67]\n   X-Ms-Date: [Tue, 26 Jul 2022 10:55:34 GMT]\n   X-Ms-Version: [2020-10-02]\n   --------------------------------------------------------------------------------\n   RESPONSE 
Status: 404 The specified blob does not exist.\n   Content-Length: [215]\n   Content-Type: [application/xml]\n   Date: [Tue, 26 Jul 2022 10:55:34 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [7]\n   X-Ms-Error-Code: [BlobNotFound]\n   X-Ms-Request-Id: [0]\n   X-Ms-Version: [2020-10-02]\n\n\n"}   

#########################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
  labels:
    app: functionAppTest
spec:
  replicas: 0
  selector:
    matchLabels:
      app: functionAppTest
  template:
    metadata:
      labels:
        app: functionAppTest
        aadpodidbinding : podid
    spec:
      containers:
      - name: envar-demo-container
        image: imagePath
        resources:
         requests:
          memory: "250Mi"
          cpu: "100m"
         limits:
          memory: "500Mi"
          cpu: "200m"
        env:
        - name: KEDA_SERVICEBUS_AUTH_MODE
          value: ConnectionString
        - name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
          value: Endpoint=sb://namepsace.servicebus.windows.net/;SharedAccessKeyName=default;SharedAccessKey=key123;EntityPath=eventHUbname
        - name: KEDA_SERVICEBUS_QUEUE_NAME
          value: orders
        - name: AzureWebJobsStorage
          value: "DefaultEndpointsProtocol=https;AccountName=stAccount;AccountKey=123;EndpointSuffix=core.windows.net"
        - name: AzureEventHubConnectionString
          value: connectionString1
        - name: outputEHConnectionString
          value connectionString2
################################################################
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-test-scaler
  namespace: aks_app_namespace
spec:
  scaleTargetRef:
    name: eh-function-app-perf
  minReplicaCount: 5  
  maxReplicaCount: 10
  pollingInterval: 1 # How frequently we should go for metrics (in seconds)
  cooldownPeriod:  25 # How many seconds should we wait for downscale  
  triggers:
  - type: azure-eventhub
    metadata:
      namespace: namespaceName
      storageConnectionFromEnv: AzureWebJobsStorage
      connectionFromEnv: AzureEventHubConnectionString
      checkpointStrategy: blobMetadata
      blobContainer: azure-webjobs-eventhub
      queueLength: '10'
      eventHubNamespace: ehNamespaceName
      eventHubName: ehName
    authenticationRef:
      name: trigger-auth-service-bus-orders
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-service-bus-orders
spec:
  secretTargetRef:
  - parameter: connection
    name: secrets-order-management
    key: servicebus-order-management-connectionstring
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-order-management
  labels:
    app: app-test
data:
  servicebus-order-management-connectionstring: byte encoded value

### Expected Behavior

KEDA is expected to scale the function app from 5 to 10 pods depending on the data flow in the input event hub.

### Actual Behavior

The function app is getting deployed successfully in the AKS cluster and scaler object is spinning up 5 pods on deployment. But further scaling from 5 to 10 pods is not being seen.

### Steps to Reproduce the Problem

1. create a sample function app to read the data from event hub and dump to an output event hub. Create a container for the function app.
2. Deploy the app using the deployment yaml file using "kubectl" command.
3. Deploy scaled the object using "kubectl" apply command.
4.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Kubernetes Version

1.22

### Platform

Microsoft Azure

**Comment by v-shenoy** [comment]
The scaled object definition seems to be incorrect. If you want to use connection strings for both the event hub, and the storage account, maybe a definition like follows should be used instead.
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: eh-function-app-scaler-perf
  namespace: delta-gdpp-preprocess-dev
spec:
  scaleTargetRef:
    name: eh-function-app-perf
  minReplicaCount: 5
  maxReplicaCount: 500
  pollingInterval: 1
  cooldownPeriod: 25
  triggers:
    - type: azure-eventhub
      metadata:
        # Event Hub scaler doesn't have properties namespace or queueLength in its trigger metadata. 
        # eventHubNamespace, eventHubName - these properties are only required when using pod identity.
        # When using connection strings, KEDA will infer them.
        storageConnectionFromEnv: AzureWebJobsStorage
        connectionFromEnv: AzureEventHubConnectionString
        checkpointStrategy: blobMetadata
        blobContainer: azure-webjobs-eventhub
        unprocessedEventThreshold: '10'

```

When configuring KEDA with helm you set the pod identity label, but you are not using pod identity anywhere in your trigger auth resource. 

The following is a bit of an assumption, but looking at this part -
```yaml
- name: KEDA_SERVICEBUS_AUTH_MODE
value: ConnectionString
- name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
value: Endpoint=sb:/
```

Was this used as a reference -  https://github.com/kedacore/sample-dotnet-worker-servicebus-queue
and then not correctly changed to replace service bus with event hub?

**Comment by v-shenoy** [comment]
The scaled object definition seems to be incorrect. If you want to use connection strings for both the event hub, and the storage account, maybe a definition like follows should be used instead.
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: eh-function-app-scaler-perf
  namespace: <namespace>
spec:
  scaleTargetRef:
    name: eh-function-app-perf
  minReplicaCount: 5
  maxReplicaCount: 500
  pollingInterval: 1
  cooldownPeriod: 25
  triggers:
    - type: azure-eventhub
      metadata:
        # Event Hub scaler doesn't have properties namespace or queueLength in its trigger metadata. 
        # eventHubNamespace, eventHubName - these properties are only required when using pod identity.
        # When using connection strings, KEDA will infer them.
        storageConnectionFromEnv: AzureWebJobsStorage
        connectionFromEnv: AzureEventHubConnectionString # This needs to end with EntityPath=<hub-name>
        checkpointStrategy: blobMetadata
        blobContainer: azure-webjobs-eventhub
        unprocessedEventThreshold: '10'

```

When configuring KEDA with helm you set the pod identity label, but you are not using pod identity anywhere in your trigger auth resource. 

The following is a bit of an assumption, but looking at this part -
```yaml
- name: KEDA_SERVICEBUS_AUTH_MODE
value: ConnectionString
- name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
value: Endpoint=sb:/
```

Was this used as a reference -  https://github.com/kedacore/sample-dotnet-worker-servicebus-queue
and then not correctly changed to replace service bus with event hub?
