### ISSUE TITLE
Introduce new time-window trigger

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#3566]
### Proposal

Introduce new time-window trigger which allows you to scale based on a defined time window.

We could use inspiration from the [kube-green project](https://kube-green.dev/docs/real-usecase/node-downscale/):
```yaml
triggers:
- type: time-window
  weekdays: "Mo-Fri"
  start: "08:00"
  end: "20:00"
  timezone: Asia/Kolkata  # The acceptable values would be a value from the IANA Time Zone Database.
```

The `cron` scaler uses `desiredReplicas` but I believe it should just rely on min/max replica defined on the ScaledObject/ScaledJob.

This trigger should replace the `cron` scaler which is confusing in how it scales as end-users tend to think it behaves like jobs.

### Use-Case

Scale workloads based on a time window.
