### ISSUE TITLE
Keda HPA is creating and immediately terminating pods

### ISSUE THREAD

**Issue by teebu** [kedacore/keda#3578]
### Report

I have a function that scales based on a topic. It gets created and immediately terminates the newly created pods. 

I send 1000 messages to topic to try to get it to scale.

### Expected Behavior

Create pod, finish work.

### Actual Behavior

Created pods are immediately terminated.

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Kubernetes Version

1.22

### Platform

Microsoft Azure

### Scaler Details

azure-servicebus

### Anything else?

snippet from HPA
```
 conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2022-08-22T20:30:40Z'
      reason: SucceededRescale
      message: the HPA controller was able to update the target scale to 4
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2022-08-22T20:30:40Z'
      reason: ValidMetricFound
      message: >-
        the HPA was able to successfully calculate a replica count from external
        metric
        s0-azure-helloworld-topic(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:
        hello-world,},MatchExpressions:[]LabelSelectorRequirement{},})
    - type: ScalingLimited
      status: 'True'
      lastTransitionTime: '2022-08-22T20:31:27Z'
      reason: ScaleUpLimit
      message: >-
        the desired replica count is increasing faster than the maximum scale
        rate
```
It's strange that the same config when I apply manually using kubectl apply -f deploy.yaml (with secret, deploy, scaled obj) vs using argoCD, it actually works as expected and scales fine. 

Removing from Deployment, `spec.replicas`, also makes it work as expected.
```
spec:
     replicas: 1 # <-
```

This is the first time I encountered this.

I wonder if ArgoCD is trying to sync and is fighting with Keda.
