### ISSUE TITLE
[azure-data-explorer-scaler] Same metric name with multiple scaled object defined

### ISSUE THREAD

**Issue by cdlliuy** [kedacore/keda#3588]
### Report

We had multiple scaling metrics with azure-data-explorer-scaler when the metric extracted from the same azure-data-explorer-db, but from different query. 

i.e  I created a trigger using metricName "metric-A"  to run query "query-A", then "metric-B" with run with "query-B"
```
  triggers:
  - authenticationRef:
      name: kusto-trigger-auth
    metadata:
      databaseName: azure-data-explorer-dbName
      endpoint:  azure-data-explorer-dbUrl
      metricName:  metric-A
      query: |
        <azure-data-explorer-query-A>
      threshold: "10"
    type: azure-data-explorer
  - authenticationRef:
      name: kusto-trigger-auth
    metadata:
      databaseName: azure-data-explorer-dbName
      endpoint:  azure-data-explorer-dbUrl
      metricName:  metric-B
      query: |
        <azure-data-explorer-query-B>
      threshold: "10"
    type: azure-data-explorer
```

With current implementation,   both of the scaled object has the same metric name:
```
  externalMetricNames:
  - s0-azure-data-explorer-dbName
  - s1-azure-data-explorer-dbName
```
It is hard to remember the exactly query purpose with the `externalMetricNames`, which bring troubles with monitoring. 

### Expected Behavior

I would like to suggest to add the orignal metadata.metricName in the final externalMetricNames, i.e. s0-metricName-A-azure-data-explorer-dbName in above example

### Actual Behavior

```
  externalMetricNames:
  - s0-azure-data-explorer-dbName
  - s1-azure-data-explorer-dbName
```

### Steps to Reproduce the Problem

See above description

### Logs from KEDA operator

```
example
```

### Scaler Details

azure-data-explorer-scaler

### Anything else?

I will raise a PR to address this issue
