### ISSUE TITLE
ScaledObject minReplicaCount Default is not working as described.

### ISSUE THREAD

**Issue by v1ferrarij** [kedacore/keda#3603]
### Report

I believe I have found a bug / issue with the ScaledObject value minReplicaCount.

I created a ScaledObject where I did not complete the value minReplicaCount as on your website it states that this defaults to 0:

![image](https://user-images.githubusercontent.com/94917970/186894452-d26b95ef-789f-487b-b529-60596c773f86.png)

I was having issue's with my deployment as it was never scaling down to 0 even though there was no activity on the Service Bus, I looked into the ScaledObject using 

```kubectl describe ScaledObject xxxxx```

I found that the minReplicaCount was not being set by default.

I then amended my ScaledObject and explicitly added the value:

```minReplicaCount: 0```

This fixed my issue, when I explicitly added this value, my deployment's were scaling as expected.

### Expected Behavior

minReplicaCount is SET to 0 by default.

### Actual Behavior

minReplicaCount is not being set to 0 by default.

### Steps to Reproduce the Problem

1. Created a ScaledObject without specifying minReplicaCount.
2. See if deployment is scaled to 0 by default.

### KEDA Version

2.7.1

### Kubernetes Version

1.22

### Platform

Microsoft Azure

### Scaler Details

Service Bus

**Comment by tomkerkhove** [comment]
Can you define what you mean with this please?

> I found that the minReplicaCount was not being set by default.

Is that based on the describe output? If so, that's normal given the default is used internally AFAIK.

**Comment by v1ferrarij** [comment]
> Can you define what you mean with this please?
> 
> > I found that the minReplicaCount was not being set by default.
> 
> Is that based on the describe output? If so, that's normal given the default is used internally AFAIK.

Your documentation states that this input is optional and the default value is 0.

![image](https://user-images.githubusercontent.com/94917970/186896953-6063edbf-356e-4d30-a0c1-555ab1b8adea.png)

I have found that this is not being set to 0 unless you specify it in your code.

code that does not work, deployments ARE NOT scaled down to 0.

```yaml
    apiVersion: apps/v1
    kind: Deployment
    name: xxxxx
      pollingInterval: 30
      cooldownPeriod: 90
      idleReplicaCount: 0
      maxReplicaCount: 1
```

working code, deployments ARE scaled down to 0.

```yaml
    apiVersion: apps/v1
    kind: Deployment
    name: xxxxx
      pollingInterval: 30
      cooldownPeriod: 90
      idleReplicaCount: 0
      maxReplicaCount: 1
      minReplicaCount: 0
```
