### ISSUE TITLE
metrics-api trigger giving averageValue Invalid value

### ISSUE THREAD

**Issue by cdennison** [kedacore/keda#3669]
### Report

Here's my deployment yaml

For non-arm you can use just "nginx" for image

Trying to use this trigger: https://keda.sh/docs/2.8/scalers/metrics-api/

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-keda-charlie
  namespace: tsew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-keda-charlie
  template:
    metadata:
      labels:
        app: nginx-keda-charlie
    spec:
      containers:
      - name: nginx-keda-charlie
        image: arm64v8/nginx
        imagePullPolicy: Always
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaledobject
  namespace: tsew
  labels:
    deploymentName: nginx-keda-charlie
spec:
  scaleTargetRef:
    name:        nginx-keda-charlie
  triggers:
    - type: metrics-api
      metadata:
        metricType: Value
        targetValue: "1"
        url: "http://mockbin.org/bin/9cb318e0-e8d8-4dc5-a18f-f6135a0e2d4a"
        valueLocation: 'tasks'
```

### Expected Behavior

Nginx to be scaled to 3 instances

### Actual Behavior

The main error appears to be this:

"HorizontalPodAutoscaler.autoscaling \"keda-hpa-http-scaledobject\" is invalid: spec.metrics[0].external.target.averageValue: Invalid value: resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:\"0\", Format:\"DecimalSI\"}: must be positive"

> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2022-09-14T19:59:54Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"http-scaledobject","namespace":"tsew"}, "namespace": "tsew", "name": "http-scaledobject", "reconcileID": "a7d1c215-a585-4a65-b85d-ba1152746edf", "error": "HorizontalPodAutoscaler.autoscaling \"keda-hpa-http-scaledobject\" is invalid: spec.metrics[0].external.target.averageValue: Invalid value: resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:\"0\", Format:\"DecimalSI\"}: must be positive"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234

> 

### Steps to Reproduce the Problem

1. install minikube v1.26.1 on OSX
2. Install KEDA like this kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.8.0/keda-2.8.0.yaml
3. kubectl apply -f deployment.yaml

### Logs from KEDA operator

```
2022-09-14T19:59:54Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"http-scaledobject","namespace":"tsew"}, "namespace": "tsew", "name": "http-scaledobject", "reconcileID": "a7d1c215-a585-4a65-b85d-ba1152746edf"}
2022-09-14T19:59:54Z	INFO	Creating a new HPA	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"http-scaledobject","namespace":"tsew"}, "namespace": "tsew", "name": "http-scaledobject", "reconcileID": "a7d1c215-a585-4a65-b85d-ba1152746edf", "HPA.Namespace": "tsew", "HPA.Name": "keda-hpa-http-scaledobject"}
2022-09-14T19:59:54Z	ERROR	Failed to create new HPA in cluster	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"http-scaledobject","namespace":"tsew"}, "namespace": "tsew", "name": "http-scaledobject", "reconcileID": "a7d1c215-a585-4a65-b85d-ba1152746edf", "HPA.Namespace": "tsew", "HPA.Name": "keda-hpa-http-scaledobject", "error": "HorizontalPodAutoscaler.autoscaling \"keda-hpa-http-scaledobject\" is invalid: spec.metrics[0].external.target.averageValue: Invalid value: resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:\"0\", Format:\"DecimalSI\"}: must be positive"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:378
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:235
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:186
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
```

### KEDA Version

2.8.0

### Kubernetes Version

1.25

### Platform

Other

### Scaler Details

metrics-api
