### ISSUE TITLE
Kafka scaler undocumented bootstrapServersFromEnv is not working

### ISSUE THREAD

**Issue by alon-mo** [kedacore/keda#3675]
Hi, does anyone knows whether this functionality actually works or not?

My deployment is as follows:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-ns
   .
   .
   .
spec:  
    spec:     
      containers:
        - name: my-container          
          env:            
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-kafka-url:9094
          .
          .
          .
```

and I set my ScaledObject as follows:

```yaml
triggers:
    - authenticationRef:
        name: my-auth-ref
      metadata:
        bootstrapServersFromEnv: KAFKA_BOOTSTRAP_SERVERS
        consumerGroup: my-consumer-group
        lagThreshold: '100'
        offsetResetPolicy: earliest
        version: 2.4.0
      type: kafka
```

but the environment variable value is not picked as expected.

I would appreciate any assistance on this. Thanks!

_Originally posted by @alon-mo in https://github.com/kedacore/keda/issues/1329#issuecomment-1250240879_
