### ISSUE TITLE
ScaledJob fails to support repeated containerPort with different names in container template

### ISSUE THREAD

**Issue by zd9KgA** [kedacore/keda#3676]
### Report

In the definition of a ScaledJob.spec.jobTargetRef.template.containers, I'd expect to be able to state something like this:

```
          ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          - containerPort: 8080
            name: probes
            protocol: TCP
```

That is, to refer to the same physical port by different names (e.g., metrics and probes in the given example). This works for a Pod, and I did not find any restriction why the same PodSpec shouldn't work in the definition of a ScaledJob.

Unless I am missing something here (see: https://github.com/kedacore/keda/discussions/3658), I believe that this is a bug.

### Expected Behavior

Accept a `PodSpec` with repeated containerPort configuration as long as the naming differs (as it works in `Deployment`).

### Actual Behavior

scaledjobs.keda.sh "<name>-scaledjob" was not valid:
* spec.jobTargetRef.template.spec.containers[0].ports[1]: Duplicate value: map[string]interface {}{"containerPort":8080, "protocol":"TCP"}

### Steps to Reproduce the Problem

1. Deploy a ScaledJob into a namespace
2. Use `kubectl edit` to add the above ports section
3. Try to save and exit

### Logs from KEDA operator

No specific message related to the update attempt (as described above).

### KEDA Version

2.8.1

### Kubernetes Version

1.23

### Platform

Other
