### ISSUE TITLE
Azure DevOps Scaler as Job scales out spuriously and orphans pipeline stages

### ISSUE THREAD

**Issue by trimbleAdam** [kedacore/keda#3679]
### Report

Using the ScaledJob means of autoscaling Azure DevOps self-hosted agents, we see that the ScaledJob is creating a bunch of pods that are listening for jobs to run, a couple of which are actually running pipeline stages/steps.
We end up with our maximum number of jobs/pods, but most are not doing anything.

### Expected Behavior

A pipeline which requires 2 agents will create 2 k8s jobs, each of which will create 1 pod which immediately runs the 2 stages, and upon completion, terminates the jobs/pods. 
Subsequent stages will then do the same, creating 1 agent per stage, completing the entire stage, then terminating the Job/Pod/Agent upon completion.

### Actual Behavior

The pipeline triggers the scale-out for the 2 agents needed for the first 2 stages, then instead of 2 Jobs/Pods, we see the scaler continue creating Jobs/Pods that aren't attached to any pipeline stage/step, but simply sit there idle until the activeDeadlineSeconds threshold is met, whereupon the scaler terminates the Jobs/Pods and recreates them over and over.

### Steps to Reproduce the Problem

1. Create an AzDo agent pool and create a ScaledJob for the same. Set maxReplicaCount to 100, activeDeadlineSeconds to 2 hours, scalingStrategy to accurate.
2. Trigger pipeline with many parallel stages with long running steps (~30 minutes or more)
3. Note that the scaler will continue creating agent Jobs/Pods, but none of them will pick up any work.

### Scaler Details

Azure Pipelines

**Comment by JorTurFer** [comment]
Hey,
Sorry but KEDA isn't the responsible for scheduling jobs in agents. I mean, KEDA get the pending agent pool queue and spawn  k8s jobs based on the pool queue. It's the agent who has to register itself, and do whatever is needed to get the jobs from AzDO. 
What do you see in the logs from not working agents? Could you share your ScaledJob?

**Comment by trimbleAdam** [comment]
> Hey, Sorry but KEDA isn't the responsible for scheduling jobs in agents. I mean, KEDA get the pending agent pool queue and spawn k8s jobs based on the pool queue. It's the agent who has to register itself, and do whatever is needed to get the jobs from AzDO. What do you see in the logs from not working agents? Could you share your ScaledJob?

Understood. What we need is to know _why_ the scaler is doing this.  We originally tried to use the Deployment model with ScaledObject, but scale-in would wind up occurring on pods which were running jobs still, so we thought that ScaledJob would be better for this, coz you get a 1:1 between agent and item-in-queue.

All the non-working agents bootstrap in the normal way, and we see "Listening for jobs..."

I have kicked off the pipeline, which should be using 2 agents ATM, but we see 5 job/pod
<img width="808" alt="image" src="https://user-images.githubusercontent.com/38919772/191080318-e4553c0a-914f-4ed0-9c7e-f80ea0f79dcd.png">

Their resource usage is the giveaway that there are pods sitting there doing nothing (idle pods use 1m CPU and ~80MiB ram):
<img width="812" alt="image" src="https://user-images.githubusercontent.com/38919772/191081057-eb8c5376-b3bc-4794-8730-0bc8720172f7.png">

Listening for jobs:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/38919772/191080549-4d08f789-6224-4fb0-acc7-fec1178b69e3.png">

This error could be the core of the issue: 
```
keda-operator-5cc44d6948-w684m keda-operator 2022-09-19T16:29:41.298Z     ERROR   azure_pipelines_scaler  error)  {"type": "ScaledJob", "namespace": "fm-k8s-private-agent-mem-pool", "name": "fm-k8s-private-agent-mem-pool", "error": "Get \"https://dev.azure.com/FOOO/_apis/distributedtask/pools/90/jobrequests\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
keda-operator-5cc44d6948-w684m keda-operator github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).getScaledJobMetrics
keda-operator-5cc44d6948-w684m keda-operator      /workspace/pkg/scaling/cache/scalers_cache.go:263
keda-operator-5cc44d6948-w684m keda-operator github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledJobActive
keda-operator-5cc44d6948-w684m keda-operator      /workspace/pkg/scaling/cache/scalers_cache.go:125
keda-operator-5cc44d6948-w684m keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
keda-operator-5cc44d6948-w684m keda-operator      /workspace/pkg/scaling/scale_handler.go:286
keda-operator-5cc44d6948-w684m keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
keda-operator-5cc44d6948-w684m keda-operator      /workspace/pkg/scaling/scale_handler.go:149
```
How do we go about increasing the timeout to talk to the AzDo backend?

Here is the ScaledObject definition:
```
apiVersion: v1
items:
- apiVersion: keda.sh/v1alpha1
  kind: ScaledJob
  metadata:
    name: fm-k8s-private-agent-mem-pool
    namespace: fm-k8s-private-agent-mem-pool
  spec:
    failedJobsHistoryLimit: 10
    jobTargetRef:
      activeDeadlineSeconds: 7200
      parallelism: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            envFrom:
            - configMapRef:
                name: fm-k8s-private-agent-mem-pool-config
            image: xxx:0.0.19
            imagePullPolicy: Always
            name: fm-k8s-private-agent-mem-pool
            resources:
              limits:
                cpu: "2"
                memory: 8Gi
              requests:
                cpu: "2"
                memory: 8Gi
          nodeSelector:
            lifecycle: ciMem
          restartPolicy: Never
          serviceAccount: fm-k8s-private-agent-mem-pool
          serviceAccountName: fm-k8s-private-agent-mem-pool
          terminationGracePeriodSeconds: 30
    maxReplicaCount: 100
    pollingInterval: 30
    scalingStrategy:
      strategy: accurate
    successfulJobsHistoryLimit: 1
    triggers:
    - authenticationRef:
        name: fm-k8s-private-agent-mem-pool-trigger-auth
      metadata:
        organizationURLFromEnv: AZP_URL
        poolID: "90"
      type: azure-pipelines
```

**Comment by JorTurFer** [comment]
Are you able to see them in the AzDO UI? The error you are seeing is related with AzDO API, maybe it's there the issue, but KEDA doesn't assign the jobs to the agents, so even if you don't have that timeout, you will continue with your issue.
You can increase the global KEDA timeout using the env `KEDA_HTTP_DEFAULT_TIMEOUT` https://keda.sh/docs/2.2/operate/cluster/#http-timeouts

**Comment by trimbleAdam** [comment]
> Are you able to see them in the AzDO UI? The error you are seeing is related with AzDO API, maybe it's there the issue, but KEDA doesn't assign the jobs to the agents, so even if you don't have that timeout, you will continue with your issue. You can increase the global KEDA timeout using the env `KEDA_HTTP_DEFAULT_TIMEOUT` https://keda.sh/docs/latest/operate/cluster/#http-timeouts

Ya, we can see the agents in the AzDO UI, both agents working on something, and the rest of the idle agents:
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/38919772/191086180-4c766bc3-823c-4c98-bf1f-012c7f69d23c.png">

**Comment by trimbleAdam** [comment]
We _are_ trying to leverage ScaledJob controllers in multiple namespaces; could be need to bump up the number of reconcilers re: https://keda.sh/docs/2.8/operate/cluster/#configure-maxconcurrentreconciles-for-controllers?

**Comment by JorTurFer** [comment]
I can see that KEDA is working because you have multiple instances. KEDA doesn't have any control over how the agents take the jobs from AzDO

**Comment by Eldarrin** [comment]
I'll run some tests here and see if I can duplicate it

**Comment by Eldarrin** [comment]
If you run curl -u user:pat https://dev.azure.com/FOO/_apis/distributedtask/pools/90/jobrequests it should spin up an agent for each item in that list that has value.n.results = nil

**Comment by theadzik** [comment]
If you wandered in here because you have the same problem you need to set

```yaml
spec:
  triggers:
    - type: azure-pipelines
      metadata:
        activationTargetPipelinesQueueLength: "1"
```

By default `activationTargetPipelinesQueueLength` is 0 so KEDA just scales the job to max possible value. 

https://keda.sh/docs/2.13/scalers/azure-pipelines/#trigger-specification
