### ISSUE TITLE
keda cant connect to Nats monitoring endpoint

### ISSUE THREAD

**Issue by Barney241** [kedacore/keda#3723]
### Report

My keda scaler cant connect to nats monitoring endpoint.

### Expected Behavior

Keda connects to monitoring endpoint

### Actual Behavior

i get this error 

```
scaledobject nats-jetstream-scaledobject] Get "[http://nats:8222/jsz?acc=$G&consumers=true&config=true":](http://nats:8222/jsz?acc=$G&consumers=true&config=true%22:) context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[event: horizontalpodautoscaler keda-hpa-nats-jetstream-scaledobject] unable to get external metric default/s0-nats-jetstream-keda/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: nats-jetstream-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-nats-jetstream-keda
[event: scaledobject nats-jetstream-scaledobject] Get "[http://nats:8222/jsz?acc=$G&consumers=true&config=true":](http://nats:8222/jsz?acc=$G&consumers=true&config=true%22:) context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[event: scaledobject nats-jetstream-scaledobject] Get "[http://nats:8222/jsz?acc=$G&consumers=true&config=true":](http://nats:8222/jsz?acc=$G&consumers=true&config=true%22:) context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[event: scaledobject nats-jetstream-scaledobject] Get "[http://nats:8222/jsz?acc=$G&consumers=true&config=true":](http://nats:8222/jsz?acc=$G&consumers=true&config=true%22:) context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[event: scaledobject nats-jetstream-scaledobject] Get "[http://nats:8222/jsz?acc=$G&consumers=true&config=true":](http://nats:8222/jsz?acc=$G&consumers=true&config=true%22:) context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[event: horizontalpodautoscaler keda-hpa-nats-jetstream-scaledobject] unable to get external metric default/s0-nats-jetstream-keda/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: nats-jetstream-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-nats-jetstream-keda
[event: scaledobject nats-jetstream-scaledobject] Get "[http://nats:8222/jsz?acc=$G&consumers=true&config=true":](http://nats:8222/jsz?acc=$G&consumers=true&config=true%22:) context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[event: horizontalpodautoscaler keda-hpa-nats-jetstream-scaledobject] unable to get external metric default/s0-nats-jetstream-keda/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: nats-jetstream-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-nats-jetstream-keda
[event: scaledobject nats-jetstream-scaledobject] Get "[http://nats:8222/jsz?acc=$G&consumers=true&config=true":](http://nats:8222/jsz?acc=$G&consumers=true&config=true%22:) context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[event: horizontalpodautoscaler keda-hpa-nats-jetstream-scaledobject] unable to get external metric default/s0-nats-jetstream-keda/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: nats-jetstream-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-nats-jetstream-keda
[event: scaledobject nats-jetstream-scaledobject] Get "[http://nats:8222/jsz?acc=$G&consumers=true&config=true":](http://nats:8222/jsz?acc=$G&consumers=true&config=true%22:) context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[event: horizontalpodautoscaler keda-hpa-nats-jetstream-scaledobject] unable to get external metric default/s0-nats-jetstream-keda/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: nats-jetstream-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: no matching metrics found for s0-nats-jetstream-keda
```

### Steps to Reproduce the Problem

My scaler config:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nats-jetstream-scaledobject
spec:
  pollingInterval: 10   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 30  # Optional. Default: 100
  scaleTargetRef:
    name: keda-sub
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "nats:8222"
        account: "$G"
        stream: "keda"  
        consumer: "testGroup"
        lagThreshold: "10"
        activationLagThreshold: "15"
```

I am deploying nats using tilt and helm

```
helm_remote('nats',
            repo_name='nats2',
            repo_url='https://nats-io.github.io/k8s/helm/charts',
            set=[
            'nats.jetstream.enabled=true',
            'natsbox.enabled=false',
            'cluster.enabled=false'
            ]
)
```

### Logs from KEDA operator

```
example
```

### KEDA Version

Other

### Kubernetes Version

1.24

### Platform

Other

### Scaler Details

nats jetstream
