### ISSUE TITLE
MaxreplicaCount doesn't seems to work properly with Keda Job

### ISSUE THREAD

**Issue by hugogirard** [kedacore/keda#3744]
### Report

I am sending messages to an Azure storage queue, for every message I see one job is created in K8s. So, this part it's working without any problem.

For example, if I sent 10 messages to the queue this will create 10 jobs in K8s.  I would like to have a max replica of 5 jobs at the time no matters how many messages are in the queue.

Even with setting the maxReplicaCount to 5 seems it's not happening; I have 1 job per message in the queue.

Here my YAML definition

```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: node-job-scaler
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: nodejob
          image:  acruyhxkgvwutmbk.azurecr.io/nodejob:latest
          imagePullPolicy: Always
          env:
            - name: COSMOS_ENDPOINT
              value: 
            - name: COSMOS_KEY 
              value: 
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: 
        restartPolicy: Never  
    parallelism: 1                            # [max number of desired pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    completions: 1                            # [desired number of successfully finished pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    activeDeadlineSeconds: 600                #  Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
    backoffLimit: 1                           # Specifies the number of retries before marking this job failed. Defaults to 6
  pollingInterval: 30                         # Optional. Default: 30 seconds
  successfulJobsHistoryLimit: 5               # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 5                   # Optional. Default: 100. How many failed jobs should be kept.
  minReplicaCount: 0
  maxReplicaCount: 5                          # Optional. Default: 100
  triggers:
  - type: azure-queue
    metadata:
      queueName: job
      queueLength: '1'
      connectionFromEnv: AZURE_STORAGE_CONNECTION_STRING
```

Here my code in Nodejs

```
const FibonacciRepository = require('./Repository/FibonacciRepository');
const CalculusService = require('./Services/CalculusService');
const { v4: uuidv4 } = require('uuid');
const { QueueServiceClient } = require("@azure/storage-queue");

(async ()  => {

    const calculusService = new CalculusService();
    const fibonacciRepository = new FibonacciRepository();
    
    const queueName = "job";
    const connectionString = process.env.AZURE_STORAGE_CONNECTION_STRING;
    
    const queueServiceClient = QueueServiceClient.fromConnectionString(connectionString);
    
    const queueClient = queueServiceClient.getQueueClient(queueName);
    
    const receivedMessages = await queueClient.receiveMessages();

    if (receivedMessages.receivedMessageItems.length === 0) {
        console.log(`No message to process`);
        return;
    }

    const message = receivedMessages.receivedMessageItems[0];

    // Decode encoded base64 message
    const buff = new Buffer.from(message.messageText, 'base64');
    const text = buff.toString('utf-8');

    console.log("Dequeuing message: ", text);
            
    // Calculate fibonnaci sequence
    const fib = calculusService.calculateFibonacciSequence(text);
    
    console.log(`Fibonacci result: ${fib}`);

    const newItem = {
        id: uuidv4(),
        seq: message.messageText,
        result: fib
    };
    
    await fibonacciRepository.add(newItem);
    
    await queueClient.deleteMessage(message.messageId, message.popReceipt);

})();
```
```



class CalculusService {
    calculateFibonacciSequence(seq) {

        let i;
        let fib = [0,1];
    
        for (i = 2; i <= seq; i++) {
            fib[i] = fib[i - 2] + fib[i - 1];
        }    

        return fib;
    }
}

module.exports = CalculusService;
```

```
const CosmosClient = require('@azure/cosmos').CosmosClient;
const Config = require('../config')();

class FibonacciRepository {

    constructor(){
        const endpoint = Config.cosmosEndpoint;
        const key = Config.cosmosKey;
        const client = new CosmosClient({ endpoint, key });

        const database = client.database(Config.cosmosDatabaseId);
        this.container = database.container(Config.cosmosContainerId);
    }

    async add(item) {
        const { resource: createdItem } = await this.container.items.create(item);
        return createdItem;
    }
}

module.exports = FibonacciRepository;
```
Package.json
```
{
  "name": "job",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node server"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@azure/cosmos": "^3.17.1",
    "@azure/storage-queue": "^12.10.0",
    "dotenv": "^16.0.3",
    "express": "^4.18.1",
    "uuid": "^9.0.0"
  }
}

```

### Expected Behavior

I would expect even if I had 10 messages in the queue no more than 5 jobs at the time are created.

### Actual Behavior

Right now, I see one Keda Job per message in the queue.  I sent 10 messages, and 10 jobs were created even with the maxReplicaCount = 5.

### Steps to Reproduce the Problem

1.  Deploy Keda
2.  Create a job that read one message at the time from the queue and process it
3.  Deploy the job with the YAML provided above
4.  Send 10 messages in the queue.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.8.1

### Kubernetes Version

1.23

### Platform

Microsoft Azure

### Scaler Details

Azure Storage Queue
