### ISSUE TITLE
Test if upgrading to KEDA v2.9 will break existing scaler due to HPA apiVersion changes.

### ISSUE THREAD

**Issue by v-shenoy** [kedacore/keda#3745]
Steps -

1. Have a K8s cluster `v1.23`. 
2. Install KEDA `v2.8` via Helm.
3. Deploy a ScaledObject, this will create an HPA from the apiVersion - `autoscaling/v2beta2`
4. Upgrade KEDA via Helm to `v2.9` (or the `main` tag).
5. Make sure nothing breaks.

**Comment by JorTurFer** [comment]
just to clarify, is this a bug or a pending task?
I have just tried and it works, I have deployed a ScaledObject with KEDA v2.8.1 and once the HPA was created and the workload is scaling, I have deployed `main` tag and it works. No error logs in operator nor metrics-server

**Comment by JorTurFer** [comment]
f**k, I misunderstood the title (long day...)
I'd say that the test is done @v-shenoy , I have done it because I understood this issue as a bug 😄

**Comment by v-shenoy** [comment]
> f**k, I misunderstood the title (long day...) I'd say that the test is done @v-shenoy , I have done it because I understood this issue as a bug 😄

Ooh, thanks for doing it, makes my life easier :P @JorTurFer 
So, to clarify, when you create a ScaledObject on KEDA < = `v2.8.1`, it creates an underlying HPA of the `apiVersion` - `autoscaling/v2beta` 

When you update the KEDA to >= `v2.9.0`, does it delete the existing HPA and create a new one from `autoscaling/v2`?

**Comment by JorTurFer** [comment]
> When you update the KEDA to >= `v2.9.0`, does it delete the existing HPA and create a new one from `autoscaling/v2`?

No, internally the API server translates it AFAIK, in my cluster I don't have it duplicated, maybe @zroubalik can explain this better

**Comment by tomkerkhove** [comment]
The main question is: Once you've installed 2.9; what is the API version of the HPA?

The idea is to see if it migrates to lates API version, otherwise there will be issues in the future when `v2beta` will be removed regardless of us enforcing a Kubernetes version.

Context: https://docs.google.com/document/d/1zdwD6j86GxcCe5S5ay9suCO77WPrEDnKSfuaI24EwM4/edit

**Comment by v-shenoy** [comment]
So, I installed `v2.8.1` on my Kubernetes cluster `v1.23`
```
2022-10-12T07:11:38Z    INFO    setup   Running on Kubernetes 1.23      {"version": "v1.23.8"}
2022-10-12T07:11:38Z    INFO    setup   Starting manager
2022-10-12T07:11:38Z    INFO    setup   KEDA Version: 2.8.1
```

and created a ScaledObject with Kubernetes Workload trigger. The underlying HPA that was created was from `autoscaling/v2`. 

I even created an HPA directly using YAML 
```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```

```bash
~/hpa-test ➜  kctl apply -f hpa.yaml
deployment.apps/nginx-deployment created
Warning: autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
horizontalpodautoscaler.autoscaling/php-apache created
```

But the underlying created HPA is still in `autoscaling/v2`
```bash
~/hpa-test ➜  kctl get hpa php-apache -o=jsonpath='{.apiVersion}'
autoscaling/v2%
```
