### ISSUE TITLE
o11y: add Prometheus metric for scaledObject condition array

### ISSUE THREAD

**Issue by erikkn** [kedacore/keda#3758]
### Proposal

The `scaledObject` object has a `condition` attribute that shows an array of conditions the object has passed through. An example:

```
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is performed because triggers are active
    reason: ScalerActive
    status: "True"
    type: Active
  - message: No fallbacks are active on this scaled object
    reason: NoFallbackFound
    status: "False"
    type: Fallback
```

I would like to add a Prometheus metric for this which in the core is very similar to the HPA condition metric `kube_horizontalpodautoscaler_status_condition` ([here](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/horizontalpodautoscaler-metrics.md)).

What do you guys think? I am happy to pick this one up when it receives positive feedback from the community.

### Use-Case

Show health of `scaledObjects` and alerting
