### ISSUE TITLE
Service bus connection string not detected when referred as secret referencec

### ISSUE THREAD

**Issue by SusheelReddy00** [kedacore/keda#3780]
### Report

As per document connectionFromEnv refers to the environment variable of a K8 deployment from which the Keda object would obtain the connection string. However this does not work when environment variable is a secret reference.

It works only when the connection string is added as a plan variable

### Expected Behavior

Secret referenced environment connection string should be usable by scaledobjects

### Actual Behavior

Scaledobjects are not able to connect to Service bus and throws the below error

```
ERROR	azure_servicebus_scaler	error	{"type": "ScaledObject", "namespace": "service", "name": "my-risk-service-risk-required", "error": "request failed: 401 SubCode=40103: Invalid authorization token signature"}
```

### Steps to Reproduce the Problem

1. Create a deployment with service bus connection string stored as a secret reference like below

```
        - name: ServiceBus__ConnectionString
          valueFrom:
            secretKeyRef:
              name: servicebus
              key: connection
```
2. Create a scaled object with target reference to the secret referecned environment variable
```
spec:
  cooldownPeriod: 300
  idleReplicaCount: 0
  maxReplicaCount: 100
  minReplicaCount: 1
  pollingInterval: 30
  scaleTargetRef:
    name: risk-service-deployment
  triggers:
    - metadata:
        connectionFromEnv: ServiceBus__ConnectionString
        messageCount: '100'
        namespace: test-sb
        subscriptionName: testsubscription
        topicName: risk.countries.received
      type: azure-servicebus
```

### Logs from KEDA operator

```
azure_servicebus_scaler	error	{"type": "ScaledObject", "namespace": "service", "name": "my-risk-service-risk-required", "error": "request failed: 401 SubCode=40103: Invalid authorization token signature"}
```

### KEDA Version

2.8.0

### Kubernetes Version

< 1.23

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus

### Anything else?

I have tested that this works when connection string is added as plain variable but does not work when added as secret reference.
