### ISSUE TITLE
Issue with scaling to more than 1 replica

### ISSUE THREAD

**Issue by Fouz** [kedacore/keda#3855]
I have a deployment with 0 replicas i’m trying with keda to be able to scale out the replicas from 0 and back based on a metric that measures the latency, having keda scaledobject spec as follows

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sidekiq-scaledobject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sidekiq
  minReplicaCount: 0
  maxReplicaCount: 4
  cooldownPeriod: 30 
  pollingInterval: 30
  fallback:                                          
    failureThreshold: 2                            
    replicas: 2
  triggers:
    - type: prometheus
      metricType: Value
      metadata:
        serverAddress: http://prometheus:9090 
        metricName: sidekiq_queue_latency_seconds 
        query: rate(sidekiq_queue_latency_seconds{job="job1",name=~"queue1"[1m]})
        threshold: "60"
```
the issue is it stops scaling at 1 replica after it reaches threshold so I guess it’s an issue with the hpa not able to scale from 1 to N, the hpa status :
```jsx
NAME      REFERENCE            TARGETS       MINPODS MAXPODS REPLICAS 
keda-hpa  Deployment/sidekiq   0/60   1       4          1
```
```jsx
Reference:                                                       Deployment/sidekiq
Metrics:                                                         ( current / target )
  "s0-prometheus-sidekiq_queue_latency_seconds" (target value):  0 / 60
Min replicas:                                                    1
Max replicas:                                                    4
Deployment pods:                                                 1 current / 1 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from external metric s0-prometheus-sidekiq_queue_latency_seconds(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: sidekiq-scaledobject,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  True    TooFewReplicas    the desired replica count is less than the minimum replica count
Events:           <none>
```

## Specifications

  - **KEDA Version:** *2.8.2*
  - **Kubernetes Version:** *1.22*
  - **Scaler(s):** *prometheus*
