### ISSUE TITLE
Support multiple cron schedules within one cron scheduler or make the end field optional

### ISSUE THREAD

**Issue by hochuenw-dd** [kedacore/keda#3877]
### Proposal

Hi team, 
Does it make sense to make the end field in the cron scaler optional? https://github.com/kedacore/keda/blob/main/pkg/scalers/cron_scaler.go#L99
When the end field is empty, the controller will just set the replicas to `desiredReplicas`, and leave it there. 
Or even better, does it make sense to support multiple schedules within one cron scheduler? I figure it could be hard to implement the isActive function if we make the end field optional.
### Use-Case

This makes configs cleaner if users want to use multiple crons. 
Before (note how we want to make sure the previous scaler's end match the current scaler's start):
```
  triggers:
  - type: cron
    metadata:
      timezone: America/Los_Angeles
      start: 39 * * * *
      end: 41 * * * *
      desiredReplicas: "2"
  - type: cron
    metadata:
      timezone: America/Los_Angeles
      start: 41 * * * *
      end: 43 * * * *
      desiredReplicas: "4"
  - type: cron
    metadata:
      timezone: America/Los_Angeles
      start: 43 * * * *
      end: 45 * * * *
      desiredReplicas: "6"
  - type: cron
    metadata:
      timezone: America/Los_Angeles
      start: 45 * * * *
      end: 47 * * * *
      desiredReplicas: "8"
  - type: cron
    metadata:
      timezone: America/Los_Angeles
      start: 47 * * * *
      end: 49 * * * *
      desiredReplicas: "10"
```
After (if we make end field optional):
```
  triggers:
  - type: cron
    metadata:
      timezone: America/Los_Angeles
      start: 39 * * * *
      desiredReplicas: "2"
  - type: cron
    metadata:
      timezone: America/Los_Angeles
      start: 41 * * * *
      desiredReplicas: "4"
  - type: cron
    metadata:
      timezone: America/Los_Angeles
      start: 43 * * * *
      desiredReplicas: "6"
  - type: cron
    metadata:
      timezone: America/Los_Angeles
      start: 45 * * * *
      desiredReplicas: "8"
  - type: cron
    metadata:
      timezone: America/Los_Angeles
      start: 47 * * * *
      desiredReplicas: "10"
```
After (if we support multiple schedules within one cron scheduler):
```
  triggers:
  - type: cron
    metadata:
      timezone: America/Los_Angeles
      schedules:
        - start: 39 * * * *
          desiredReplicas: "2"
        - start: 41 * * * *
          desiredReplicas: "4"
        - start: 43 * * * *
          end: 45 * * * * (optional)
          desiredReplicas: "4"
           ...
```

Questions:

Happy to submit a PR if the team think either proposal makes sense.
