### ISSUE TITLE
metric selector for already existed metrics

### ISSUE THREAD

**Issue by yuvalweber** [kedacore/keda#3886]
### Proposal

prometheus-adapter has a nice feature that can reduce the load and ammount of metrics in kuberenetes cluster.
you can create external metric like this: 

```
externalRules:
- seriesQuery: '{__name__="sqs_queue_messages",name!=""}'
  metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (queue_name)
  resources:
    overrides: { namespace: {resource: "namespace"} }
```
and then it creates an external metric with label selector for each queue (in the example above)
```
"items": [
    {
      "metricName": "sqs_queue_messages",
      "metricLabels": {
        "__name__": "sqs_queue_messages",
        ...
        "queue_name": "temp-queue"
      },
      "timestamp": "2019-11-07T21:14:44Z",
      "value": "0"
    },
    {
      "metricName": "sqs_queue_messages",
      "metricLabels": {
        "__name__": "sqs_queue_messages",
        ...
        "queue_name": "random-queue"
      },
      "timestamp": "2019-11-07T21:14:44Z",
      "value": "0"
    }
  ]
```
after that you can create an hpa and select this metric on the specific label.
I like this Idea a lot cause you reduce the number of metrics necessary to create and second of all you reduce the amount of queries you create to prometheus.
### Use-Case
very useful for the prometheus scaler.
This mechanism can also be mimic to other scalers to remove the load they create
