### ISSUE TITLE
KEDA not working with Redis when minReplicaCount is zero

### ISSUE THREAD

**Issue by michaelkira** [kedacore/keda#3918]
### Report

KEDA not working with Redis when minReplicaCount is zero while it works when minReplicaCount is 1. My keda version is 2.8.1.
We found KEDA will scale down replica from 1 to 0 when there is no message in the redis queue while it will not scale up back to 1 when we put new message into redis queue.

Here is my config
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:  
  finalizers:
  - finalizer.keda.sh
  labels:
    deploymentName: 
    scaledobject.keda.sh/name: 
  name: 
  namespace: 
spec:
  maxReplicaCount: 4
  minReplicaCount: 0
  scaleTargetRef:
    name: 
  triggers:
  - authenticationRef:
      name: 
    metadata:
      addressFromEnv: someaddress
      databaseIndex: "2"
      enableTLS: "true"
      listLength: "1"
      listName: default
      passwordFromEnv: somepassword
    type: redis
```

### Expected Behavior

When redis queue is not empty, scale replica from 0 to 1

### Actual Behavior

once the replica reach 0 it won't scale up.
If we set mini replica to 1, it works correctly.

### Steps to Reproduce the Problem

1. set scale object using redis
2. waiting replica scale down to 0
3. add message into redis, and no replica is created.

### Logs from KEDA operator

There is not much usefully information I find in KEDA operator
I can see 
2022-11-17T15:08:47Z	INFO	Successfully finalized ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"dummy","namespace":"dummy"}, "namespace": "dummy", "name": "dummy", "reconcileID": "e01c16b2-ef3f-4a39-9149-c2d64ff8fc0c"}
And then no logs for it anymore

### KEDA Version

2.8.1

### Platform

Microsoft Azure
