### ISSUE TITLE
Continued Issue 3609 : Scale to zero with cron triggers

### ISSUE THREAD

**Issue by vipulp86** [kedacore/keda#3956]
### Report

We cannot achieve cron based scale in to zero with Keda. We tried setting up minReplicaCount to 0(which is by default value) and desiredReplicaCount to 0 with cron expreissions. When we apply scaledobject definition, keda is scaling in pods to 0 outside cron start/end window. 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-deployment-keda
spec:
  minReplicaCount: 0
  scaleTargetRef:
    name: nginx-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Kolkata
      start: 0 0 * * 6 ## At 00:00 on Saturday
      end: 0 0 * * 7 ## At 00:00 on Sunday
      desiredReplicas: "0"
```

------

With minReplicaCount to 1 and desiredReplicaCount to 0 with cron expressions, pod doesn't scale in to 0 even during cron window(this is because minReplicaCount is set to 1 and its definitely conflicting with desiredReplicaCount). 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-deployment-keda
spec:
  minReplicaCount: 1
  scaleTargetRef:
    name: nginx-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Kolkata
      start: 0 0 * * 6 ## At 00:00 on Saturday
      end: 0 0 * * 7 ## At 00:00 on Sunday
      desiredReplicas: "0"
```

### Expected Behavior

Keda should scale in to desiredReplicaCount to 0 during cron schedule window and once window completes, should bring back to original number of replicas of deployment/stateful sets.

### Actual Behavior

We cannot achieve cron based scale in to zero with Keda. We tried setting up minReplicaCount to 0(which is by default value) and desiredReplicaCount to 0 with cron expreissions. When we apply scaledobject definition, keda is scaling in pods to 0 outside cron start/end window. 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-deployment-keda
spec:
  minReplicaCount: 0
  scaleTargetRef:
    name: nginx-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Kolkata
      start: 0 0 * * 6 ## At 00:00 on Saturday
      end: 0 0 * * 7 ## At 00:00 on Sunday
      desiredReplicas: "0"
```

------

With minReplicaCount to 1 and desiredReplicaCount to 0 with cron expressions, pod doesn't scale in to 0 even during cron window(this is because minReplicaCount is set to 1 and its definitely conflicting with desiredReplicaCount). 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-deployment-keda
spec:
  minReplicaCount: 1
  scaleTargetRef:
    name: nginx-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Kolkata
      start: 0 0 * * 6 ## At 00:00 on Saturday
      end: 0 0 * * 7 ## At 00:00 on Sunday
      desiredReplicas: "0"
```

### Steps to Reproduce the Problem

Mentioned above.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.0

### Kubernetes Version

1.24

### Platform

Microsoft Azure

### Scaler Details

Cron
