### ISSUE TITLE
Error : failed to extract organization name from organizationURL

### ISSUE THREAD

**Issue by shzshi** [kedacore/keda#3980]
### Report

I am setting the azure pipeline scaler for first time , I had installed keda version 2.7.1 and created the scaleobject and TriggerAuthentication using below yaml file , but I am getting error

```
apiVersion: v1
kind: Secret
metadata:
  name: pipeline-auth
data:
  personalAccessToken: <PAT_TOKEN>
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pipeline-trigger-auth
  namespace: devops
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: pipeline-auth # pipeline-auth
      key: personalAccessToken # personalAccessToken
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-pipelines-scaledobject
  namespace: devops
spec:
  scaleTargetRef:
    name: azdevops-deployment-keda
  minReplicaCount: 1
  maxReplicaCount: 5 
  cooldownPeriod: 3
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: "1"
      organizationURLFromEnv: "AZP_URL"
    authenticationRef:
     name: pipeline-trigger-auth

```
### Expected Behavior

scaledObjects should be not failing

### Actual Behavior

I can see error in the keda operator 

2022-12-07T19:25:31Z	ERROR	controller.scaledobject	Reconciler error	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "azure-pipelines-scaledobject", "namespace": "devops", "error": "error parsing azure Pipelines metadata: failed to extract organization name from organizationURL"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227

### Steps to Reproduce the Problem

1. installed keda with helm chart
2. created scaledobject and TriggerAuthentication

### Logs from KEDA operator

```
example
```
2022-12-07T19:25:31Z	ERROR	controller.scaledobject	Reconciler error	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "azure-pipelines-scaledobject", "namespace": "devops", "error": "error parsing azure Pipelines metadata: failed to extract organization name from organizationURL"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227

### KEDA Version

2.7.1

### Kubernetes Version

1.23

### Platform

Microsoft Azure

### Scaler Details

azure pipeline
