### ISSUE TITLE
ScaledObject with New Relic trigger causing go panic

### ISSUE THREAD

**Issue by barclayadam** [kedacore/keda#4016]
### Report

I have a `ScaledObject` with a New Relic trigger. Upon creating this scaler `keda-operator` pod logs a panic and restarts. It is then required to remove the `finalizer` from this object to be able to delete it to allow the operator to continue to work.

### Expected Behavior

`ScaledObject` is reconciled and no errors

### Actual Behavior

keda-operator panics

### Steps to Reproduce the Problem

Created `TriggerAuthentication`:

````yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: trigger-new-relic
  namespace: apps-frontend
spec:
  secretTargetRef:
    - key: queryKey
      name: keda-new-relic-trigger-auth
      parameter: queryKey
    - key: account
      name: keda-new-relic-trigger-auth
      parameter: account
    - key: region
      name: keda-new-relic-trigger-auth
      parameter: region
````

Create `ScaledObject`:

````yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  finalizers:
    - finalizer.keda.sh
  generation: 1
  labels:
    app: smtp-inbound
    app.kubernetes.io/managed-by: pulumi
    name: smtp-inbound
    scaledobject.keda.sh/name: smtp-inbound-scaler-opened-connections
  name: smtp-inbound-scaler-opened-connections
  namespace: apps-frontend
status:
  conditions:
    - message: ScaledObject is defined correctly and is ready for scaling
      reason: ScaledObjectReady
      status: 'True'
      type: Ready
    - status: Unknown
      type: Active
    - status: Unknown
      type: Fallback
  externalMetricNames:
    - s0-new-relic
  hpaName: keda-hpa-smtp-inbound-scaler-opened-connections
  originalReplicaCount: 4
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment
spec:
  maxReplicaCount: 12
  minReplicaCount: 4
  scaleTargetRef:
    name: smtp-inbound
  triggers:
    - authenticationRef:
        name: trigger-new-relic
      metadata:
        nrql: SELECT derivative(opened_connections, 2 minutes) FROM Metric
        threshold: '100'
      type: new-relic
````

### Logs from KEDA operator

```
2022-12-15T13:56:59Z	INFO	Initializing Scaling logic according to ScaledObject Specification	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"sent-items-update-scaler","namespace":"apps-frontend"}, "namespace": "apps-frontend", "name": "sent-items-update-scaler", "reconcileID": "b56e2043-175e-444f-8262-f2d767e522c1"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x585a40]

goroutine 402 [running]:
github.com/go-logr/logr.Logger.Error({{0x0, 0x0}, 0xc000cb36b0}, {0x3c58f00, 0xc000f5c3c0}, {0x35c9274, 0x14}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/go-logr/logr@v1.2.3/logr.go:279 +0x80
github.com/kedacore/keda/v2/pkg/scalers.(*newrelicScaler).IsActive(0xc000dbcec0, {0x3cae988, 0xc000859b80})
	/workspace/pkg/scalers/newrelic_scaler.go:147 +0x7b
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive(0xc00004c0a0, {0x3cae988, 0xc000859b80}, 0xc000c6d600)
	/workspace/pkg/scaling/cache/scalers_cache.go:89 +0xef
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers(0xc00065a230, {0x3cae988, 0xc000859b80}, {0x34e3ec0, 0xc000c6d600}, {0x3c8b6e8, 0xc0010adcd0})
```

### KEDA Version

2.8.0

### Kubernetes Version

1.23

### Platform

Microsoft Azure

### Scaler Details

New Relic
