### ISSUE TITLE
Redis Queue trigger not discovered

### ISSUE THREAD

**Issue by Zonalds** [kedacore/keda#4021]
### Report

I'm not entirely sure this is a bug but I have this issue where the Redis queue count isn't being detected. Connection seems to work fine. 

Regardless of the size of the redis queue, the target remains 0/10
`NAME                                                                        REFERENCE              TARGETS      MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/keda-hpa-redis-scaledobject-rogue     Deployment/reacher     0/10 (avg)   2         100000    2          61m
`

I have my queue built with `https://www.npmjs.com/package/bull` and created a queue this way: 

```
export const parseVideoMetadata =
    new Queue('rogue', `redis://${redis}:6379`);
```

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject-rogue
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: rogue
  pollingInterval: 15
  cooldownPeriod: 200
  maxReplicaCount: 100000
  minReplicaCount: 2
  triggers:
    - type: redis
      metadata:
        address: redis.default.svc.cluster.local:6379
        # username: redis_user
        enableTLS: "false"
        listName: rogue
        listLength: "10"

```

Any idea what I could be doing wrong? 

### Expected Behavior

Scales with increase in redis queue count

### Actual Behavior

Not increasing

### Steps to Reproduce the Problem

1. Use bull to create queue
2. Copy the sample configuration above
3. apply

### Logs from KEDA operator

```
example
```

### KEDA Version

2.8.1

### Kubernetes Version

1.25

### Platform

Other

### Scaler Details

Redis Queue
