### ISSUE TITLE
Add 'platformName' to selenium-grid scaler metadata structure

### ISSUE THREAD

**Issue by gifflet** [kedacore/keda#4038]
### Proposal

Currently, the selenium grid scaler only supports browserName and browserVersion capabilities in trigger metadata. This results  in the impossibility of configuring a trigger for tests targeting specific platforms like Windows 10, Windows 11, etc.

### Use-Case

If the **platformName** capability were supported it would be possible to configure a trigger like this:
```yml
triggers:
  - type: selenium-grid
    metadata:
      url: 'http://selenium-hub:4444/graphql'
      browserName: 'chrome'
      browserVersion: '108.0'
      unsafeSsl: 'true',
      platformName: 'Windows 10'
```

### Anything else?

The possibility of defining the platformName would make sense if it were possible to run a virtual machine, equivalent to the platform defined in the capability platformName, in the pod. In Linux this is possible through the native feature called KVM (Kernel-based Virtual Machine). That is, the operating strategy would be to make this resource available to the linux container (through /dev/kvm) and within the container use qemu, for example, to run the virtual machine.
