### ISSUE TITLE
Job restarts when operator restarts

### ISSUE THREAD

**Issue by shalev123d** [kedacore/keda#4041]
### Report

Hello,
I'm not sure if this behavior is expected - 
When executing long running jobs (using ScaledJob objects), if the keda-operator pod restarts for any reason (manual / node switch / any other reason) the Job restarts as well.

In my example we're using an SQS scaler, and spawning up a Job that processes that message.

This is an issue since it stops the processing of the message if anything happens to the keda-operator pod.

### Expected Behavior

Job will continue running regardless of the keda-operator pod state.

### Actual Behavior

Job is restarting

### Steps to Reproduce the Problem

1. Define a ScaledJob that listens to some (AWS) SQS queue
2. Send a message to that queue so the Job will be created by KEDA
3. Kill the keda-operator pod, which then K8S will schedule a new one
4. Notice that the Job created by KEDA will be killed as well and start a new one

### Logs from KEDA operator

Nothing to show because the operator restarts (beside setup logs).

### KEDA Version

2.9.1

### Kubernetes Version

1.23

### Platform

Amazon Web Services

### Scaler Details

SQS

### Anything else?

Using EKS 1.23 / Cilium as CNI

The definition of the ScaledJob - 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: keda-test-scaledjob
  namespace: default
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: koala-reader
          image: busybox
          command: ["sleep","1d"]
        dnsPolicy: ClusterFirst
        restartPolicy: Never
    backoffLimit: 4
  triggers:
  - type: aws-sqs-queue
    metadata:
      identityOwner: operator
      queueURL: https://sqs.us-east-1.amazonaws.com/XXX/keda-test
      queueLength: "1"
      awsRegion: us-east-1
```
