### ISSUE TITLE
Is it possible to combine multiple k8s secrets into single value in TriggerAuthentication

### ISSUE THREAD

**Issue by oleg-ku-32768** [kedacore/keda#4048]
### Proposal

I have following secret:
```
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-database-credentials
data:
  username: ...
  password: ...
```

### Use-Case

I want to combine values into new one:
`host: amqp://$(username):$(password)@rbtmq.default.svc.cluster.local:5672`

### Anything else?

If it's possible, may I have an example, please?
