### ISSUE TITLE
Clarity required on how scaleout is handled for servicebus scaler

### ISSUE THREAD

**Issue by SusheelReddy00** [kedacore/keda#4077]
### Discussed in https://github.com/kedacore/keda/discussions/4064

<div type='discussions-op-text'>

<sup>Originally posted by **SusheelReddy00** January  1, 2023</sup>
Have been following the document to configure scaling for pods when there are N number of messages in Servicebus.

https://keda.sh/docs/2.9/scalers/azure-service-bus/

Which configuration decides how and when to achieve the max number of replica? I understand the min replica is achieved whenever a threshold is hit which is the minimum number of message count set as threshold.

I am currently noticing a behavior that whenever a threshold is hit, keda scales up and then terminates multiple pods by maintaining only the "minumum" number of minreplica pod count in running state. I dont understand how is the scale out count calcuated here.
```
spec:
  scaleTargetRef:
    name: service-deployment
  pollingInterval:  30                              
  cooldownPeriod:   300                                                     
  minReplicaCount: 1   
  maxReplicaCount:  100                            
  fallback:                                        
    failureThreshold: 3                        
    replicas: 6                                  
  triggers:
  - type: azure-servicebus
    metadata:
      topicName: testtopic
      subscriptionName: testsub
      namespace: service
      messageCount: 100
    authenticationRef:
        name: trigger-auth-service-bus   
```
I was hoping or expeciting a scaleout feature where a scaleout or increase in pods have some step scaling available rather than continually scaling up and terminating
</div>
