### ISSUE TITLE
unable to establish sasl connection to aws msk cluster

### ISSUE THREAD

**Issue by QualoZe0t** [kedacore/keda#4089]
### Report

Hi,
i am trying to deploy scaledObject using by sasl but getting errors in keda-operator (see below). I am not aware of wrong yaml or atleast unable to find error as connection using port 9092(plaintext) was working without any issue

### Expected Behavior

ScaledObject have to be created properly

### Actual Behavior

```
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-01-11T10:44:41Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-kafka-scaledobject","namespace":"data"}, "namespace": "data", "name": "keda-kafka-scaledobject", "reconcileID": "c6b5b3c3-2469-49a6-a27f-c37492f0bf31", "error": "error creating kafka client: kafka: client has run out of available brokers to talk to: unexpected EOF"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
```

### Steps to Reproduce the Problem

1. created secret
```
apiVersion: v1
kind: Secret
metadata:
  name: keda-msk-data
  namespace: data
data:
  sasl: "scram_sha512"
  username: "test"
  password: "test"
  ```
  TLS= is not defined so by default should be disabled
2. created triggerauth
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: data
spec:
  secretTargetRef:
  - parameter: username
    name: keda-msk-data
    key: username
  - parameter: password
    name: keda-msk-data
    key: password
  - parameter: sasl
    name: keda-msk-data
    key: sasl
```
3. created scaledObject
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-kafka-scaledobject
  namespace: data
spec:
  scaleTargetRef:
    name: kafka-test
  pollingInterval: 30
  minReplicaCount: 1
  maxReplicaCount: 5
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka-cluster:9096
      consumerGroup: kinesis-adapter
      topic: lhe-lake-party-fact-party
      lagThreshold: "2"
      offsetResetPolicy: latest
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
```

### Logs from KEDA operator

```
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-01-11T10:44:41Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-kafka-scaledobject","namespace":"data"}, "namespace": "data", "name": "keda-kafka-scaledobject", "reconcileID": "c6b5b3c3-2469-49a6-a27f-c37492f0bf31", "error": "error creating kafka client: kafka: client has run out of available brokers to talk to: unexpected EOF"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
```

### KEDA Version

2.8.1

### Kubernetes Version

< 1.23

### Platform

Amazon Web Services

### Scaler Details

Kafka
