### ISSUE TITLE
scaleTargetRef : Add label or enable regex for deploymentName

### ISSUE THREAD

**Issue by nleconte-csgroup** [kedacore/keda#4188]
### Proposal

I would like to be able to configure the target of the scaleTargetRef part for a deployment with a regex for the name or with label. For e.g. below with a regex:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          nginx-*
[...]
```

And below with label:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    label:         spring-group-id=nginx-part1
[...]
```

### Use-Case

We are using spring cloud data flow (SCDF) in our environment and the operational team often updates the deployment in SCDF. The behaviour of SCDF is to add a suffix at the end of the deployment and incrementing it each time it is updated. 

For e.g. if I updated 15 times the deployment, it would be named `nginx-v16` and if I update it once more, it would be named `nginx-v17`. 

So each time I want to update the deployment, I also have to update the nginx `ScaledObject` to match the new name.

If we could use regex for the deployment's name or label instead, it would be better.

### Is this a feature you are interested in implementing yourself?

No
