### ISSUE TITLE
Keda Dashboard with Grafana shows empty values

### ISSUE THREAD

**Issue by tshaiman** [kedacore/keda#4198]
### Report

when installing the lastest Keda Version (2.9.3) we see no data coming to grafana.

configuration on the values.yaml : 

```
prometheus:
  metricServer:
    enabled: true
    port: 9022
    portName: metrics
    path: /metrics
    podMonitor:
      # Enables PodMonitor creation for the Prometheus Operator
      enabled: true
      interval:
      scrapeTimeout:
      namespace:
      additionalLabels: {}
      relabelings: []
  operator:
    enabled: true
    port: 8080
    podMonitor:
      # Enables PodMonitor creation for the Prometheus Operator
      enabled: true
      interval:
      scrapeTimeout:
      namespace:
      additionalLabels: {}
      relabelings: []
      
```
![image](https://user-images.githubusercontent.com/512709/216815162-15148be9-88f8-41a1-b869-c11cc1555bbb.png)

Prometheus + Grafana are installed and configured correctly since we do see metrics coming from the same cluster + dashboards are operative. 

![image](https://user-images.githubusercontent.com/512709/216815257-94985300-24ab-42f6-b0e7-5840ca7228ad.png)

### Expected Behavior

- should see the keda dashboards

### Actual Behavior

- all data from the same clsuter is empty

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.9.3

### Kubernetes Version

1.24

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus
