### ISSUE TITLE
Autoscaling not happening as per scale-up policy

### ISSUE THREAD

**Issue by Vishwavijet** [kedacore/keda#4204]
### Report

Hi Team,
Facing this below issue:
**Keda version: 2.7.1
EKS version: 1.22**

```
Scaleup policies:
scaleup:
    policies:
      - periodseconds: 15
        type: Pods
        value: 2
      - periodseconds: 15
        type: Percent
        value: 10
    selectpolicy: Max
    stabilizationWindowSeconds: 60
 triggers:
    - metadata:
        value: "65"
      metricType: Utilization
      type: cpu
```
**Issue:**
When the current no of replicas is 2 and threshold is breaching cpu utilization of 65% scaling is being triggered. But scaling happens to bring up only 1 pod instead of 2 as per the scaleup policy. The above mentioned behaviour of scaleup is happening.

### Expected Behavior

As per the policy defined, it should bring up 2 static pods as the threshold is breached. If the current repliacas reach more than 21 then 10% of it i.e 2.1=~3 pods should be scaled.

### Actual Behavior

Only one pod is being scaled irrespective of static 2 pods defined.

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Kubernetes Version

< 1.23

### Platform

Amazon Web Services
