### ISSUE TITLE
prometheus scaler: support list of custom headers and custom auth

### ISSUE THREAD

**Issue by prashant-shahi** [kedacore/keda#4206]
### Proposal

Provide support for custom headers to be included in each queries in Prometheus scalar.

New prometheus scaler configuration being the `customHeaders` metadata:

Sample:
```yaml
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
spec:
  triggers:
  - type: prometheus
    metadata:
      customHeaders: X-Client-Id=cid,X-Tenant-Id=tid,X-Organization-Id=oid
      authModes: "custom"
    authenticationRef:
      name: keda-prom-creds
---
kind: Secret
metadata:
  name: keda-prom-secret
data:
  customAuthHeader: "X-AUTH-TOKEN"
  customAuthValue: "auth-token"
---
kind: TriggerAuthentication
metadata:
  name: keda-prom-creds
spec:
  secretTargetRef:
    - parameter: customAuthHeader
      name: keda-prom-secret
      key: customAuthHeader
    - parameter: customAuthValue
      name: keda-prom-secret
      key: customAuthValue
```

### Use-Case

Custom headers can be helpful for various reasons:
- identification of tenant or organization in cloud environment
- identifier for the client or customer

Custom auth header can be useful for authentication and authorization purposes with any custom header name and value.

### Is this a feature you are interested in implementing yourself?

Yes

### Anything else?

Apart from authentication part, I see that only `x-Scope-OrgID` header is available, which is specific to querying multi tenant Cortex or Mimir.

That could be supported via `customHeaders` metadata as well.
