### ISSUE TITLE
Unable to get kubeconfig

### ISSUE THREAD

**Issue by Duri9292** [kedacore/keda#4214]
### Report

After installation via HELM, the PODs cannot start because they cannot find kubeconfig.

### Expected Behavior

Successful deployment of keda-operator and keda-operator-metric.

### Actual Behavior

The PODs are restarting with Error message below

### Steps to Reproduce the Problem

1. Install KEDA using HELM
2.
3.

### Logs from KEDA operator

```
ERROR	controller-runtime.client.config	unable to get kubeconfig	{"error": "invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable", "errorCauses": [{"error": "no configuration has been provided, try setting KUBERNETES_MASTER environment variable"}]}
sigs.k8s.io/controller-runtime/pkg/client/config.GetConfigOrDie
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go:153
main.main
	/workspace/main.go:120
runtime.main
	/usr/local/go/src/runtime/proc.go:250
```

### KEDA Version

2.9.2

### Kubernetes Version

1.23

### Platform

Microsoft Azure

### Anything else?

The HELM installation was successful. The only added setting to the deployment configuration is:

`
spec:
          securityContext:
            readOnlyRootFilesystem: true
`

I tried to set KUBE_CONFIG_PATH=~/.kube/config but no luck.

**Comment by JorTurFer** [comment]
Hello,
There isn't any kubeconfig inside a pod. Pods use the service account token to authenticate themselves in the API server. Have you modified the service account or the deployment to not inject the token into the pod?

**Comment by Duri9292** [comment]
Hello @JorTurFer thank you for your reply. Our AKs policy is disabling automounting the service account by default but the keda service account is there.

deployment configuration for: keda-operator and keda-operator-metrics-apiserver
```
      serviceAccountName: keda-operator
      serviceAccount: keda-operator
      automountServiceAccountToken: false
```

keda-operator service account is present and we did not change anything.

The installation was done by these steps:
- install via helm
- set securityContext

No further configuration.

securityContext for keda deployments
```
securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsUser: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
```
