### ISSUE TITLE
Make GCP PubSub Scaler more flexible

### ISSUE THREAD

**Issue by ken8203** [kedacore/keda#4243]
### Proposal

Recently we are adopting KEDA due to its rich scalers, which are fantastic. 

There are a bunch of workloads that need to be scaled by GCP PubSub. One of metrics we used is `pubsub.googleapis.com/subscription/pull_ack_request_count`, which is not supported by KEDA.

According to the current design, if we want to add support to new metrics[^1], what we do is mostly like https://github.com/kedacore/keda/pull/4239.

Thus, in order to make it more flexible, I would like to propose a new way for `pubsubScaler`. Perhaps we don't need to hardcode metrics, instead, we convert the `mode` defined in the `ScaledObject` CRD.

For example, it is the scaled object manifest below.

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example
  triggers:
  - type: gcp-pubsub
    metricType: Value
    metadata:
      mode: PullAckRequestCount
      subscriptionName: example
      value: "10"
```

Simply convert `PullAckRequestCount` (camel case) to `pull_ack_request_count` (snake case), and concatenate it with `pubsub.googleapis.com/subscription/`, then we get the full metric name.

I'm not sure if it's a good design. Need to discuss this with the community. 

BTW, another concern is that it's hard to define default values in this way, people won't use default values in real cases though. Maybe it's okay to give an arbitrary number, e.g. 5.

[^1]: https://cloud.google.com/monitoring/api/metrics_gcp#gcp-pubsub

### Is this a feature you are interested in implementing yourself?

Yes
