### ISSUE TITLE
Scaledobject fallback not working as expected when prometheus trigger is failing

### ISSUE THREAD

**Issue by lwebbz** [kedacore/keda#4249]
### Report

When using prometheus as a trigger for a Scaledobject I've run into some unexpected behaviour where the number of replicas of a deployment will oscillate between the `minReplicaCount` and `fallback.replicas` despite the status of the trigger consistently being in the failing state. Furthermore the `keda_scaler_metrics_value` consistently returns a value of 0 instead of fallback.replicas when the trigger is failing, this is different to the cron scaler for example which will fallback to the correct number of replicas specified by `fallback.replicas` when given an invalid timezone.

Here are the manifests I've been using to test this. Note that `spec.triggers.metadata.query` is invalid since the promQL `rate` function requires an argument and in this example I haven't provided it with one. This consistently produces a 400 bad request to get the scaler to fail

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-scaledobject-test
spec:
  scaleTargetRef:
    name: keda-fallback-deployment-test     
  minReplicaCount:  1                            
  maxReplicaCount:  20                         
  fallback:                                      
    failureThreshold: 3             
    replicas: 5                                
  triggers:
    - type: prometheus
      metadata:
        metricName: test-fallback-metric
        query:  rate() 
        serverAddress:  http://thanos-prometheus-thanos-querier.telemetry:10902/metrics
        threshold: '1'
        namespace: 'telemetry'
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-fallback-deployment-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keda-fallback-test
  template:
    metadata:
      labels:
        app: keda-fallback-test
    spec:
      containers:
      - name: keda-fallback-test
        image: nginx
        resources:
          requests:
            memory: 150Mi
            cpu: 150m
          limits:
            memory: 1000Mi
            cpu: 250m
```

### Expected Behavior

Deployment scales to `fallback.replicas` i.e. 5 pods and then stays at 5 replicas.

### Actual Behavior

1. Deployment will scale to 5 pods i.e. fallback.replicas. 
2. Within the next 3 minutes the deployment will scale down to 1 pod i.e. `minReplicaCount`
3. Repeat cycle after 30 seconds

### Steps to Reproduce the Problem

1. Deploy the scaledobject and deployment as stated in the report section above but change the prometheus serverAddress to your server address
2. Observe the number of pods in the deployment fluctuate

### Logs from KEDA operator

Deployment state 1:
```
➜  ~ k get deployments -n keda
NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
keda-fallback-deployment-test     5/5     5            5           4d1h
keda-operator                     1/1     1            1           302d
keda-operator-metrics-apiserver   1/1     1            1           302d
```
Deployment state 2:
```
➜  ~ k get deployments -n keda
NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
keda-fallback-deployment-test     1/1     1            1           4d1h
keda-operator                     1/1     1            1           302d
keda-operator-metrics-apiserver   1/1     1            1           302d
```

KEDAScalerFailed event which is as expected because I've used a bad query
```
 ~ k get events -n keda
63s         Warning   KEDAScalerFailed          scaledobject/keda-scaledobject-test                       prometheus query api returned error. status: 400 response: {"status":"error","errorType":"bad_data","error":"1:1: parse error: expected 1 argument(s) in call to \"rate\", got 0"}
```

This metric returns 0 instead of fallback.replicas (5)
```
➜  ~ kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/keda/s0-prometheus-test-fallback-metric?labelSelector=scaledobject.keda.sh%2Fname%3Dkeda-scaledobject-test"

{"kind":"ExternalMetricValueList","apiVersion":"external.metrics.k8s.io/v1beta1","metadata":{},"items":[{"metricName":"s0-prometheus-test-fallback-metric","metricLabels":null,"timestamp":"2023-02-17T11:25:58Z","value":"0"}]}
```

Can see that the status of the scaler is `Failing`
```
➜  ~ k get scaledobjects.keda.sh -n keda keda-scaledobject-test -o yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{},"name":"keda-scaledobject-test","namespace":"keda"},"spec":{"fallback":{"failureThreshold":3,"replicas":5},"maxReplicaCount":20,"minReplicaCount":1,"scaleTargetRef":{"name":"keda-fallback-deployment-test"},"triggers":[{"metadata":{"metricName":"test-fallback-metric","namespace":"telemetry","query":"rate()","serverAddress":"http://thanos-prometheus-thanos-querier.telemetry:10902/metrics","threshold":"1"},"type":"prometheus"}]}}
  creationTimestamp: "2023-02-13T10:22:35Z"
  finalizers:
  - finalizer.keda.sh
  generation: 73
  labels:
    scaledobject.keda.sh/name: keda-scaledobject-test
  name: keda-scaledobject-test
  namespace: keda
  resourceVersion: "463687104"
  uid: c3e59326-71e3-4c49-b1a9-06291cb50509
spec:
  fallback:
    failureThreshold: 3
    replicas: 5
  maxReplicaCount: 20
  minReplicaCount: 1
  scaleTargetRef:
    name: keda-fallback-deployment-test
  triggers:
  - metadata:
      metricName: test-fallback-metric
      namespace: telemetry
      query: rate()
      serverAddress: http://thanos-prometheus-thanos-querier.telemetry:10902/metrics
      threshold: "1"
    type: prometheus
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is not performed because triggers are not active
    reason: ScalerNotActive
    status: "False"
    type: Active
  - message: At least one trigger is falling back on this scaled object
    reason: FallbackExists
    status: "True"
    type: Fallback
  externalMetricNames:
  - s0-prometheus-test-fallback-metric
  health:
    s0-prometheus-test-fallback-metric:
      numberOfFailures: 33
      status: Failing
  hpaName: keda-hpa-keda-scaledobject-test
  lastActiveTime: "2023-02-17T11:00:54Z"
  originalReplicaCount: 10
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment
```

Desired HPA metric is 1 instead of 5
```
~ k describe hpa -n keda keda-hpa-keda-scaledobject-test
Name:                                                           keda-hpa-keda-scaledobject-test
Namespace:                                                      keda
Labels:                                                         app.kubernetes.io/managed-by=keda-operator
                                                                app.kubernetes.io/name=keda-hpa-keda-scaledobject-test
                                                                app.kubernetes.io/part-of=keda-scaledobject-test
                                                                app.kubernetes.io/version=2.8.2
                                                                scaledobject.keda.sh/name=keda-scaledobject-test
Annotations:                                                    <none>
CreationTimestamp:                                              Mon, 13 Feb 2023 10:22:35 +0000
Reference:                                                      Deployment/keda-fallback-deployment-test
Metrics:                                                        ( current / target )
  "s0-prometheus-test-fallback-metric" (target average value):  0 / 1
Min replicas:                                                   1
Max replicas:                                                   20
Deployment pods:                                                5 current / 1 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    SucceededRescale  the HPA controller was able to update the target scale to 1
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from external metric s0-prometheus-test-fallback-metric(&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: keda-scaledobject-test,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  True    TooFewReplicas    the desired replica count is less than the minimum replica count
Events:
  Type     Reason                   Age                   From                       Message
  ----     ------                   ----                  ----                       -------
  Normal   SuccessfulRescale        105s (x1889 over 4d)  horizontal-pod-autoscaler  New size: 1; reason: All metrics below target
```

### KEDA Version

2.8.2

### Kubernetes Version

< 1.23

### Platform

Amazon Web Services

### Scaler Details

Prometheus
