### ISSUE TITLE
EventHub plugin reports strange values periodically

### ISSUE THREAD

**Issue by ilya-scale** [kedacore/keda#4250]
### Report

I have connected KEDA to event hub

```yml
      spec:
        minReplicaCount: 2
        maxReplicaCount: 8
      triggers:
      - type: azure-eventhub
        metadata:
          storageAccountName: myaccount
          blobContainer: checkpoints
          eventHubNamespace: mynamespace
          eventHubName: myhub
          consumerGroup: myconsumer
          checkpointStrategy: blobMetadata
          unprocessedEventThreshold: "5000"
```

There seem to be a number of issues with the connection:

1. The connection seems to work but I often get very strange values. I monitor them via grafana and prometheus monitor.
The value is negative and extremely low:

![image](https://user-images.githubusercontent.com/105273784/219648250-e2d0350b-ac81-4799-8aa6-c1205868586f.png)

2. I also get these logs every 10 seconds or even more often:

2023-02-17T11:58:41Z    INFO    Reconciling ScaledObject        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"xxx","namespace":"xxx"}, "namespace": "xxx", "name": "data-ingest-iot", "reconcileID": "e272cdaa-8474-421e-9ca4-9fae7bda42f4"}

Which is probably strange since the default check period is every 30 seconds. I have a service bus trigger on another ScaledObject and neither of these things happen (no logs for reconciling, no "off" values either)

3. It seems that the value of the metric is capped at unprocessedEventThreshold * maxReplicaCount as very often I get value 40000 which is quite strange. So I think the value should not be capped. The value itself seems to be off as well, somewhat like in the point 1. but I cannot see it since it is capped.

### Expected Behavior

1. There should not be any values that are "off"
2. There probably should not be reconciling every 10 seconds in the log (not sure about that)
3. There should not be any "cap" on the metric value

### Actual Behavior

1. Strange values appear periodically
2. Logs indicate that probably something is wrong
3. The value of the metric is capped

### Steps to Reproduce the Problem

1. Create an eventhub with some messages coming through
2. Register trigger with the details posted above
3. Run for some time and observe this behaviour

P.S. The negative value does not seem to happen in every environment where I run k8s.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.9.3

### Kubernetes Version

1.24

### Platform

Microsoft Azure

### Scaler Details

EventHubs
