### ISSUE TITLE
Support scaling to Zero with combine of Cron and cpu/mem scaler

### ISSUE THREAD

**Issue by vumdao** [kedacore/keda#4269]
### Proposal

My scaled object
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app
spec:
  maxReplicaCount: 10
  minReplicaCount: 0
  scaleTargetRef:
    kind: Deployment
    name: app
  triggers:
    - metadata:
        desiredReplicas: "2"
        end: 0 21 * * *
        start: 30 7 * * *
        timezone: Asia/Ho_Chi_Minh
      type: cron
    - metadata:
        value: "85"
      metricType: Utilization
      type: cpu
```

I would like to scale my deployment to Zero but the cpu/mem scaler prevents that

Proposal from @zroubalik: `we can allow scale to 0, in case there are multiple triggers not just cpu/mem and the activation will be driven by the non-cpu/mem scaler.`

### Is this a feature you are interested in implementing yourself?

No
