### ISSUE TITLE
TriggerAuthentication cannot read secretTargetRef from other namespace although KEDA_CLUSTER_OBJECT_NAMESPACE set

### ISSUE THREAD

**Issue by SimonSchmid** [kedacore/keda#4272]
### Report

Hello all,

According to the documentation (https://keda.sh/docs/2.9/concepts/authentication/#environment-variables), a `TriggerAuthentication` can deployed in a different namespace than the secret referring to via `secretTargetRef`. This is not working for me.

I have deployed the following to `namespaceA`:
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth
spec:
  secretTargetRef:
    - parameter: username
      name: my-secret
      key: username
    - parameter: password
      name: my-secret
      key: password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kedartemis-consumer-scaled-object
spec:
  scaleTargetRef:
    name: ...
  triggers:
    - type: artemis-queue
      metadata:
        ...
      authenticationRef:
        name: trigger-auth
``` 

The secret `my-secret` is deployed to `namespaceB`. Also, in `namespaceB` the keda operator is running which has the environment variable `KEDA_CLUSTER_OBJECT_NAMESPACE` set to `namespaceB`.

Am I misunderstanding the docs or is there some bug?

I got it working when using a `ClusterTriggerAuthentication` instead (as the operator is running in the same namespace as the secret) but I would prefer using a `TriggerAuthentication`.

Thanks for any insights in advance!

### Expected Behavior

`secretTargetRef` referencing the secret in the other namespace set via `KEDA_CLUSTER_OBJECT_NAMESPACE`

### Actual Behavior

operator failing with `"error": "error parsing artemis metadata: username cannot be empty"`

### Steps to Reproduce the Problem

See report.

### Logs from KEDA operator

```
2023-02-22T17:45:49Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"kedartemis-consumer-scaled-object","namespace":"namespaceA"}, "namespace": "namespaceA", "name": "kedartemis-consumer-scaled-object", "reconcileID": "2c845aea-9fad-4ec7-bfa1-d9ee224dc7d9", "error": "error parsing artemis metadata: username cannot be empty"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
```

### KEDA Version

2.8.2

### Kubernetes Version

< 1.23

### Platform

Other
