### ISSUE TITLE
SQS scaleOnInFlight not being respected

### ISSUE THREAD

**Issue by miklapko** [kedacore/keda#4276]
### Report

We have our ScaledObject configured as such:

```
spec:
  cooldownPeriod: 180
  maxReplicaCount: 2000
  minReplicaCount: 100
  pollingInterval: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $DEPLOYMENT
triggers:
    - metadata:
        awsRegion: $REGION
        identityOwner: operator
        queueLength: '2'
        queueURL: >-
          $QUEUE_URL
        scaleOnInFlight: 'true'
      type: aws-sqs-queue
```

KEDA is not scaling the deployment based on in-flight message count (AWS API is reporting the value correctly). It only looks at messages available, and we verified it by changing queueLength - 1 instead of 2 indeed causes KEDA to scale twice as high, but only if there are messages available.

As soon as messages available reach 0, no matter how many messages are in-flight (tested with 200-2000), KEDA will not scale unless messages available starts going up again.

This results in frequent and steep peaks and lows in scaling.

What is also weird is that it was working as expected before, and started behaving incorrectly when we added more ScaledObjects / ScaledJobs (not many, around 8) to this cluster.

We have tried recreating ScaledObject and restarting / redeploying KEDA completely, no dice. We're running EKS K8S 1.22 and are planning to upgrade, however, again, it worked as expected for some time. I haven't seen any specific fixes in newer versions / any similar issues open or closed.

### Expected Behavior

Expected to see KEDA keeping up with in-flight message counter and keep, for example, deployment replicas at 250 for ~500 messages in-flight and 0 messages available.

### Actual Behavior

KEDA does not keep up with messages in-flight and scales deployment to minimum.

### Steps to Reproduce the Problem

1. Deploy KEDA 2.8.1
2. Deploy a ScaledObject with aforementioned config and deployment to scale.
3. Have another ScaledObject / Deployment with `scaleOnInFlight` set to `false`.
4. Have an SQS queue with constant ~200-2000 messages in-flight and coming in consistently.

### Logs from KEDA operator

Nothing suspicious / no errors in logs, tried debug level as well.

### KEDA Version

2.8.1

### Kubernetes Version

< 1.23

### Platform

Amazon Web Services

### Scaler Details

SQS
