### ISSUE TITLE
GCP workload identity not working

### ISSUE THREAD

**Issue by NishikaDeSilva** [kedacore/keda#4278]
### Report

When using podIdentity for scaledobject triggerauthentication, gives an error of
```
rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.list denied (or the resource may not exist)
```
even though the permission `roles/monitoring.viewer` is given to gcp account associated with the pod.

### Expected Behavior

No errors in `scaledobjects.keda.sh` with gcp workload identity

### Actual Behavior

I'm using keda 2.8 for application scaling based on gcp pubsub. I tried using workload identity. Even though I've provided the pods WI gcp service account with `roles/monitoring.viewer` permissions, it fails with following error

```
keda-operator-c6bccb5f6-t4hgm keda-operator 2023-02-25T11:33:52Z	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "pubsub-test-scaledobject", "scaledObject.Namespace": "pubsub-test", "scaleTarget.Name": "pubsub-test", "error": "rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.list denied (or the resource may not exist)."}
keda-operator-c6bccb5f6-t4hgm keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
keda-operator-c6bccb5f6-t4hgm keda-operator 	/workspace/pkg/scaling/scale_handler.go:277
keda-operator-c6bccb5f6-t4hgm keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
keda-operator-c6bccb5f6-t4hgm keda-operator 	/workspace/pkg/scaling/scale_handler.go:149
```

But when I used the same service account json credentials it works.

This is the keda configurations for gcp workload identity.

**TriggerAuthentication**
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: gcp-pubsub-credentials
spec:
  podIdentity:
    provider: gcp
```
**ScaledObject**
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pubsub-test-scaledobject
  namespace: pubsub-test
spec:
  minReplicaCount: 1
  maxReplicaCount: 5
  scaleTargetRef:
    name: pubsub-test
  triggers:
  - type: gcp-pubsub
    metadata:
      mode: "SubscriptionSize"
      value: "5"
      subscriptionName: "echo-read"
    authenticationRef:
      name: gcp-pubsub-credentials
```
**deployment**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pubsub-test
  name: pubsub-test
  namespace: pubsub-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-test
  template:
    metadata:
      labels:
        app: pubsub-test
    spec:
      serviceAccount: pubsub-test
      containers:
      - image: gcr.io/google-samples/pubsub-sample:v1
        imagePullPolicy: IfNotPresent
        name: pubsub
```

### Steps to Reproduce the Problem

Use above manifests with keda 2.8.

### Logs from KEDA operator

```
keda-operator-c6bccb5f6-t4hgm keda-operator 2023-02-25T11:33:52Z	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "pubsub-test-scaledobject", "scaledObject.Namespace": "pubsub-test", "scaleTarget.Name": "pubsub-test", "error": "rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.list denied (or the resource may not exist)."}
keda-operator-c6bccb5f6-t4hgm keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
keda-operator-c6bccb5f6-t4hgm keda-operator 	/workspace/pkg/scaling/scale_handler.go:277
keda-operator-c6bccb5f6-t4hgm keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
keda-operator-c6bccb5f6-t4hgm keda-operator 	/workspace/pkg/scaling/scale_handler.go:149
```

### KEDA Version

2.8.2

### Kubernetes Version

< 1.23

### Platform

Google Cloud
