### ISSUE TITLE
Scaledjobs does not work for triggerauthentication with keyvault

### ISSUE THREAD

**Issue by JonasCordsen** [kedacore/keda#4321]
### Report

When using scaledjob using triggerauthentication with keyvault.
The trigger is not able to retrieve the secret from the key vault.

### Expected Behavior

Expected trigger to pickup secret from key vault

### Actual Behavior

No trigger is working.
Log reporting:

2023-03-04T12:12:25Z    ERROR   scalehandler    Error trying to read secret from Azure Key Vault        {"type": "ScaledJob", "namespace": "azure-devops", "name": "azure-devops-scaled-job", "triggerAuthRef.Name": "trigger-auth", "secret.Name": "personalAccessToken", "secret.Version": "c88b50a2078b4a5a99a01bae66db62db", "error": "azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://<VaultNme>.vault.azure.net/secrets/personalAccessToken/***?api-version=7.0: StatusCode=404 -- Original Error: adal: Refresh request failed. Status Code = '404'. Response body: no azure identity found for request clientID \n Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net"}

### Steps to Reproduce the Problem

Trigger:
```

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth
spec:
  azureKeyVault:
    podIdentity:
      identityId: '<clientID for identity>'
      provider: azure-workload
    secrets:
      - parameter: personalAccessToken
        name: personalAccessToken
        version: <secretversion>
    vaultUri: https://<vaultname>.vault.azure.net/

```
### Logs from KEDA operator

```
2023-03-04T12:12:25Z    ERROR   scalehandler    Error trying to read secret from Azure Key Vault        {"type": "ScaledJob", "namespace": "azure-devops", "name": "azure-devops-scaled-job", "triggerAuthRef.Name": "trigger-auth", "secret.Name": "personalAccessToken", "secret.Version": "***", "error": "azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://<VaultNme>.vault.azure.net/secrets/personalAccessToken/***?api-version=7.0: StatusCode=404 -- Original Error: adal: Refresh request failed. Status Code = '404'. Response body: no azure identity found for request clientID \n Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net"}
```

### KEDA Version

2.9.3

### Kubernetes Version

1.26

### Platform

Microsoft Azure

### Scaler Details

azure-pipeline

**Comment by JorTurFer** [comment]
Hi,
It looks like you have any error with them managed identity that you are using:
`no azure identity found for request clientID`
Could the issue come from there? I guess that you have federated both identities (default identity and the identity you have given), right?

**Comment by JonasCordsen** [comment]
Hey
I have testes some different ways, both with azure and azure-workload types, none seem to work.

Are you saying that I should be able to use Azure key vault, and a managed identity in the triggerauthentication when using scaled job?

I have tested that the pod identity it self should be b fine with the test app from microsoft guides:
```
apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    aadpodidbinding: $POD_IDENTITY_NAME
spec:
  containers:
  - name: demo
    image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
    args:
      - --subscriptionid=$SUBSCRIPTION_ID
      - --clientid=$IDENTITY_CLIENT_ID
      - --resourcegroup=$IDENTITY_RESOURCE_GROUP
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux
```
