### ISSUE TITLE
Rolling CAs not working in 2.9

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [kedacore/keda#4330]
### Report

We have a working configuration for 2.8.
When we try to use the same configuration with 2.9 accessing the bootstrap-servers with our CAs fail:

We use:
```yaml
spec:
  triggers:
  - authenticationRef:
      name: creds
```

with:

```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: creds
  namespace: ns
spec:
  secretTargetRef:
  - key: tls
    name: secret
    parameter: tls
  # list of all cas that are currently active
  - key: root-ca-new.pub.crt
    name: tracking-cas
    parameter: ca
  - key: foo.crt
    name: signing
    parameter: cert
  - key: private-key
    name: private-key
    parameter: key
  - key: password
    name: private-key
    parameter: keyPassword
```

### Expected Behavior

Either it should work or at least the error should indicate what I need to change in the config.

### Actual Behavior

Error is:

```
2023-03-07T12:07:47Z	ERROR	scalehandler	error resolving auth params	{"scalerIndex": 0, "object": {"apiVersion": "keda.sh/v1alpha1", "kind": "ScaledObject", "namespace": "analyzing-joreetz", "name": "controller"}, "error": "error creating kafka client: kafka: client has run out of available brokers to talk to: 3 errors occurred:\n\t* x509: certificate signed by unknown authority\n\t* x509: certificate signed by unknown authority\n\t* x509: certificate signed by unknown authority\n"}
```

### Steps to Reproduce the Problem

Use a config with multiple CAs in a file.

### Logs from KEDA operator

Stacktrace to above error message is:

```
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
/workspace/pkg/scaling/scale_handler.go:543
```

### KEDA Version

2.9.3

### Kubernetes Version

1.25

### Platform

Google Cloud

### Scaler Details

Kafka

### Anything else?

Seems like multiple CAs were supported before but now just one is picked.
