### ISSUE TITLE
Reconcile doesn't fire sometimes after adding a finalizer

### ISSUE THREAD

**Issue by ahmelsayed** [kedacore/keda#437]
@zroubalik I'm not sure what the issue is here, and I might need your help. 

I have 2 nightly tests that deploy those yamls ([test 1](https://github.com/kedacore/keda/blob/master/tests/scalers/azure-queue.test.ts#L103-L159), [test 2](https://github.com/kedacore/keda/blob/master/tests/scalers/azure-queue-trigger-auth.test.ts#L109-L172)) 

In test 1 the ScaledObject looks like this

```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: test-scaledobject
  labels:
    deploymentName: test-deployment
spec:
  scaleTargetRef:
    deploymentName: test-deployment
  pollingInterval: 5
  maxReplicaCount: 4
  cooldownPeriod: 10
  triggers:
  - type: azure-queue
    metadata:
      queueName: queue-name
      connection: AzureWebJobsStorage
```

and in test 2 it looks like this

```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: test-scaledobject
  labels:
    deploymentName: test-deployment
spec:
  scaleTargetRef:
    deploymentName: test-deployment
  pollingInterval: 5
  maxReplicaCount: 1
  cooldownPeriod: 10
  triggers:
  - type: azure-queue
    authenticationRef:
      name: azure-queue-auth
    metadata:
      queueName: queue-name
```

In the first call for `Reconcile()`
https://github.com/kedacore/keda/blob/99b674c68c0d7b912c3fb2d99fab01b59ebebef4/pkg/controller/scaledobject/scaledobject_controller.go#L91

It matches this condition. 
https://github.com/kedacore/keda/blob/99b674c68c0d7b912c3fb2d99fab01b59ebebef4/pkg/controller/scaledobject/scaledobject_controller.go#L134-L139

`.addFinalizer` calls `Update` on the ScaledObject, then this branch returns. I'm assuming that update should trigger another `Reconcile()` call. And it does for test 1, **but not test 2**. 

I'm not sure what the difference is.

this change will fix it 

```diff
if !contains(scaledObject.GetFinalizers(), scaledObjectFinalizer) {
	if err := r.addFinalizer(reqLogger, scaledObject); err != nil {
		return reconcile.Result{}, err
	}
-	return reconcile.Result{}, nil
+	return reconcile.Result{Requeue: true}, nil
}
```

Though it'll trigger Reconcile twice for test 1. I don't see anything in the logs. Not sure if you might know what the issue is. if not I can debug through the operator-sdk
