### ISSUE TITLE
Unable to fetch metrics from external metrics API: Internal error occurred: DatadogMetric is invalid

### ISSUE THREAD

**Issue by lejlapri1** [kedacore/keda#4415]
### Report

When deploying KEDA using a Datadog Scaler, the HPA created by KEDA returns 
`ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric infra-integ/s0-datadog-avg-nginx-net-request_per_s/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: dummy-app-flagger,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: Internal error occurred: DatadogMetric is invalid, err: Global error (all queries) from backend` and the target value is always `<unknown>`

`kubectl describe hpa keda-hpa-dummy-app-flagger`
<img width="779" alt="Screen Shot 2023-03-30 at 2 30 06 PM" src="https://user-images.githubusercontent.com/122904429/228969109-bbb38904-c915-4898-becf-fae06395242f.png">

`kubectl describe datadogmetric dcaautogen-56cd4bb9dd5640062b98461f22b0da37904cf7`
<img width="919" alt="Screen Shot 2023-03-30 at 2 30 22 PM" src="https://user-images.githubusercontent.com/122904429/228969132-81c21db3-ef7d-43fc-b2a6-475a79546a0c.png">

The scaled object:
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-datadog-secret
  namespace: infra-integ
spec:
  secretTargetRef:
    # Required: API key for your Datadog account
  - parameter: apiKey
    name: keda-datadog-vault-secret
    key: apiKey
    # Required: APP key for your Datadog account
  - parameter: appKey
    name: keda-datadog-vault-secret
    key: appKey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keda-datadog-vault-secret
  namespace: infra-integ
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-infra
    kind: ClusterSecretStore
  target:
    name: keda-datadog-vault-secret
  dataFrom:
  - extract:
      key: keda/datadog
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dummy-app-flagger
  namespace: infra-integ
spec:
  scaleTargetRef:
    name: dummy-app-flagger
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 5
  triggers:
  - type: datadog
    metricType: "AverageValue"
    metadata:
      age: "120"
      query: "avg:nginx.net.request_per_s{*}"
      queryValue: "1"
      metricUnavailableValue: "0"
    authenticationRef:
      name: keda-trigger-auth-datadog-secret
```

The datadog cluster agent is configured to use the datadog metrics provider: 

```
clusterAgent:
  admissionController:
    enabled: false
  tokenExistingSecret: datadog-cluster-token
  createPodDisruptionBudget: true
  metricsProvider:
    enabled: true
    useDatadogMetrics: true
```

We have tried using KEDA v2.7.0, 2.6.1, and 2.6.0 and see the same error with each version.

When following the [Datadog docs to create an HPA](https://docs.datadoghq.com/containers/guide/cluster_agent_autoscaling_metrics/?tab=operator#autoscaling-with-datadogmetric-queries), we are able to get metrics and see scaling

### Expected Behavior

Be able to get metrics returned from Datadog and scale appropriately

### Actual Behavior

Error parsing the metric name and therefore unable to return a metric value to the HPA

### Steps to Reproduce the Problem

1. Install KEDA v2.10 with the default values.yaml
2. Create the scaled object with the datadog, trigger authentication, and deploy
3. `kubectl describe hpa keda-hpa-dummy-app-flagger` and `kubectl describe datadogmetric dcaautogen-56cd4bb9dd5640062b98461f22b0da37904cf7`

### Logs from KEDA operator

Log from cluster agent

KEDA 2.10.0:

```
clusterAgent:
  metricsProvider:
    useDatadogMetrics: true
```

```
2023-03-28 22:14:41 UTC | CLUSTER | ERROR | (pkg/clusteragent/externalmetrics/provider.go:116 in GetExternalMetric) | ExternalMetric query failed with error: DatadogMetric is invalid, err: Global error (all queries) from backend
2023-03-28 22:14:56 UTC | CLUSTER | ERROR | (pkg/clusteragent/externalmetrics/provider.go:116 in GetExternalMetric) | ExternalMetric query failed with error: DatadogMetric is invalid, err: Global error (all queries) from backend
2023-03-28 22:14:59 UTC | CLUSTER | ERROR | (pkg/util/kubernetes/autoscalers/datadogexternal.go:74 in queryDatadogExternal) | Error while executing metric query avg:s0-datadog-avg-nginx-net-request_per_s{scaledobject.keda.sh/name:dummy-app-flagger}.rollup(30): API returned error: Error parsing query:
unable to parse avg:s0-datadog-avg-nginx-net-request_per_s{scaledobject.keda.sh/name:dummy-app-flagger}.rollup(30): Rule 'scope_expr' didn't match at '-datadog-avg-nginx-n' (line 1, column 7).
2023-03-28 22:14:59 UTC | CLUSTER | ERROR | (pkg/clusteragent/externalmetrics/metrics_retriever.go:81 in retrieveMetricsValues) | Unable to fetch external metrics: Error while executing metric query avg:s0-datadog-avg-nginx-net-request_per_s{scaledobject.keda.sh/name:dummy-app-flagger}.rollup(30): API returned error: Error parsing query:
unable to parse avg:s0-datadog-avg-nginx-net-request_per_s{scaledobject.keda.sh/name:dummy-app-flagger}.rollup(30): Rule 'scope_expr' didn't match at '-datadog-avg-nginx-n' (line 1, column 7).
2023-03-28 22:15:11 UTC | CLUSTER | ERROR | (pkg/clusteragent/externalmetrics/provider.go:116 in GetExternalMetric) | ExternalMetric query failed with error: DatadogMetric is invalid, err: Global error (all queries) from backend
```

When trying KEDA 2.7 and without a `DatadogMetric` object by setting:
```
clusterAgent:
  metricsProvider:
    useDatadogMetrics: false
```

```
2023-03-30 17:48:25 UTC | CLUSTER | ERROR | (pkg/util/kubernetes/autoscalers/autoscalers.go:108 in inspectHPAv2) | cannot build external metric value for HPA infra-integ/keda-hpa-dummy-app-flagger, skipping: metric name "s0-datadog-avg-nginx-net-request_per_s" is invalid
```

There are no errors in the operator: 

```
1.6801999269360688e+09	INFO	controller.scaledobject	Creating a new HPA	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "dummy-app-flagger", "namespace": "infra-integ", "HPA.Namespace": "infra-integ", "HPA.Name": "keda-hpa-dummy-app-flagger"}
1.680199927214943e+09	INFO	controller.scaledobject	Initializing Scaling logic according to ScaledObject Specification	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "dummy-app-flagger", "namespace": "infra-integ"}
1.6801999272298207e+09	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "dummy-app-flagger", "namespace": "infra-integ"}
1.6801999422434523e+09	INFO	controller.scaledobject	Reconciling ScaledObject	{"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "dummy-app-flagger", "namespace": "infra-integ"}
```

### KEDA Version

2.10.0

### Kubernetes Version

1.24

### Platform

Amazon Web Services

### Scaler Details

Datadog

### Anything else?

We've tried adjusting the `age` and the `metricUnavailableValue` as well and have had no luck.
