### ISSUE TITLE
Unable to get access Keda service in docker for windows desktop

### ISSUE THREAD

**Issue by VenkateshSrini** [kedacore/keda#442]
I have created the attached deployment.yaml file. When I do a kubectl -f <deploy.yaml> the service is getting created but not the external load balancing ip. Could you please let me know what is wron in this. I generated this using the below command only
`func kubernetes deploy --name petshoporders --registry <your-docker-registry-name> --dry-run > deploy.yaml`

deploy.yaml file is as below

```
data:
  AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
apiVersion: v1
kind: Secret
metadata:
  name: petshoporders
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: petshoporders-http
  namespace: default
  annotations:
    osiris.deislabs.io/enabled: true
    osiris.deislabs.io/deployment: petshoporders-http
spec:
  selector:
    app: petshoporders-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petshoporders-http
  namespace: default
  labels:
    app: petshoporders-http
  annotations:
    osiris.deislabs.io/enabled: true
    osiris.deislabs.io/minReplicas: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petshoporders-http
  template:
    metadata:
      labels:
        app: petshoporders-http
    spec:
      containers:
      - name: petshoporders-http
        image: venkateshsrini3/petshoporders
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: GetProducts
        - name: AzureFunctionsJobHost__functions__1
          value: SaveProducts
        envFrom:
        - secretRef:
            name: petshoporders
---
```
