### ISSUE TITLE
KEDA unable to access AmazonMQ ActiveMQ REST API

### ISSUE THREAD

**Issue by yuvals41** [kedacore/keda#4440]
### Report

We're integrating KEDA into our EKS cluster and using AmazonMQ with the ActiveMQ engine. We're facing issues with KEDA not being able to access the ActiveMQ REST API. Whenever we try to access the Jolokia API endpoint (https://<my-amazonmq-broker-url>:8162/api/jolokia), we're being redirected to the main page.

### Expected Behavior

keda will get the queue size and thus scale the pods

### Actual Behavior

we get this error that the response probably is the main page 
```2023-04-09T15:37:16Z ERROR scale_handler error getting metric for scaler {"scaledObject.Namespace": "keda", "scaledObject.Name": "service-scaledobject", "scaler": "activeMQScaler", "error": "error inspecting ActiveMQ queue size: invalid character '<' looking for beginning of value"}```

### Steps to Reproduce the Problem

1. open an amazonmq with activemq engine
2. try to connect the keda pod inside an eks cluster to the activemq

### Logs from KEDA operator

```
2023-04-09T15:37:16Z ERROR scale_handler error getting metric for scaler {"scaledObject.Namespace": "keda", "scaledObject.Name": "service-scaledobject", "scaler": "activeMQScaler", "error": "error inspecting ActiveMQ queue size: invalid character '<' looking for beginning of value"}
```

### KEDA Version

2.10.0

### Kubernetes Version

1.24

### Platform

Amazon Web Services

### Scaler Details

hpa

**Comment by JorTurFer** [comment]
hi,
Could you share your ScaledObject? I'm not an expert about ActiveMQ, but being redirected when you request `https://xxxxxxx:8162/api/jolokia` sound weird :/. Is your application able to access, or it doesn't access either?

**Comment by tomkerkhove** [comment]
This might be because we do not support [Amazon MQ](https://aws.amazon.com/amazon-mq/) yet, at least it's the first time I hear about it.

**Comment by tomkerkhove** [comment]
Next to Jorge his question, would you mind sharing more logs please?

**Comment by jalonsoa** [comment]
sorry .. any news on amazonmq support ? .. I can't see this issue in the roadmap.

**Comment by JorTurFer** [comment]
> sorry .. any news on amazonmq support ? .. I can't see this issue in the roadmap.

The issue was closed due to OP inactivity. I'd suggest creating another issue to track your case. Actually, it should work and the only info about now working is the issue but the OP didn't answer anything

**Comment by stv-io** [comment]
.. if this helps ..

AmazonMQ for ActiveMQ does not expose the api (I haven't found any official docs, but there was a clear mention of it in https://stackoverflow.com/questions/62474796/enable-jmx-for-amazon-mq)

An alternative approach for queue-based scaling, which uses the same metrics exposed from AmazonMQ via cloudwatch, would be to use the [AWS cloudwatch scaler](https://keda.sh/docs/2.12/scalers/aws-cloudwatch/)

The below worked for me. Granting the keda-operator cloudwatchmetrics:get permissions. It is relatively slow to react, to the default 

```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: aws-credentials
  namespace: activemq-keda-scaling
spec:
  podIdentity:
    provider: aws-eks
    identityOwner: keda
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: activemq-consumer-scaler
  namespace: activemq-keda-scaling
  labels:
    app: activemq-consumer
spec:
  scaleTargetRef:
    name: activemq-consumer
  maxReplicaCount: 200
  minReplicaCount: 1
  cooldownPeriod: 60
  pollingInterval: 30
  triggers:
    - type: aws-cloudwatch
      metadata:
        awsRegion: "eu-west-1"
        namespace: "AWS/AmazonMQ"
        metricName: "QueueSize"
        dimensionName: "Broker,Queue"
        dimensionValue: "prod-public-active-mq-2,load-testing-queue"
        targetMetricValue: "100"
        minMetricValue: "0"
        metricCollectionTime: "60"
        metricStatPeriod: "60"
        identityOwner: operator
```
