### ISSUE TITLE
Browser Pods close randomly when scaling Selenium Grid with KEDA, causing System.NullReferenceException

### ISSUE THREAD

**Issue by chandupranayp** [kedacore/keda#4443]
### Report

I am experiencing an issue when scaling a Kubernetes Selenium Grid using KEDA. The Chrome/Edge pods close randomly, and Selenium scripts fail with a "System.NullReferenceException: Object reference not set to an instance of an object." exception. Interestingly, this issue does not occur when I execute the scripts without KEDA.

### Expected Behavior

The Chrome/Edge pods should not close randomly and the Selenium scripts should execute successfully without encountering a System.NullReferenceException.

### Actual Behavior

The Chrome/Edge pods close randomly during the execution of Selenium scripts, leading to a "System.NullReferenceException: Object reference not set to an instance of an object." exception.

### Steps to Reproduce the Problem

1. Running a batch of 30 to 40 selenium scripts with different actions like Click, SendKeys, Selecting checkboxes and navigating between the pages on a Kubernetes Selenium Grid using KEDA
2.  Approx. 60% of my scripts randomly fail with System.NullReferenceException.

3. Below are the configurations made

###########  kedaSeleniumTriggers ########### 
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-chrome-scaledobject
  namespace: selenium-dev
  labels:
    deploymentName: selenium-chrome-node
spec:
  maxReplicaCount: 15
  scaleTargetRef:
    name: selenium-chrome-node
  triggers:
    - type: selenium-grid
      metadata:
        url: 'https://selenium.dev.in.nbfc.dev/graphql'
        browserName: 'chrome'
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-firefox-scaledobject
  namespace: selenium-dev
  labels:
    deploymentName: selenium-firefox-node
spec:
  maxReplicaCount: 5
  scaleTargetRef:
    name: selenium-firefox-node
  triggers:
    - type: selenium-grid
      metadata:
        url: 'https://selenium.dev.in.nbfc.dev/graphql'
        browserName: 'firefox'
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-edge-scaledobject
  namespace: selenium-dev
  labels:
    deploymentName: selenium-edge-node
spec:
  maxReplicaCount: 10 
  scaleTargetRef:
    name: selenium-edge-node
  triggers:
    - type: selenium-grid
      metadata:
        url: 'https://selenium.dev.in.nbfc.dev/graphql'
        browserName: 'MicrosoftEdge'
        sessionBrowserName: 'msedge'
```

 ###########  values-dev.yaml ########### 
```yaml
global:
  seleniumGrid:
    imageTag: 4.8.0-20230131
    nodesImageTag: 4.8.0-20230131
    imagePullSecret: ""

isolateComponents: false

ingress:
  enabled: true
  className: ""
  annotations: {}
  hostname: selenium-grid.local
  tls: []

busConfigMap:
  name: selenium-event-bus-config
  annotations: {}

components:

  router:
    imageName: selenium/router

    imagePullPolicy: IfNotPresent
    imagePullSecret: ""

    annotations: {}
    port: 4444
    livenessProbe:
      enabled: true
      path: /readyz
      initialDelaySeconds: 10
      failureThreshold: 10
      timeoutSeconds: 10
      periodSeconds: 10
      successThreshold: 1
    readinessProbe:
      enabled: true
      path: /readyz
      initialDelaySeconds: 12
      failureThreshold: 10
      timeoutSeconds: 10
      periodSeconds: 10
      successThreshold: 1
    resources: {}
    serviceType: ClusterIP
    loadBalancerIP: ""
    serviceAnnotations: {}
    tolerations: []
    nodeSelector: {}
    priorityClassName: ""

  distributor:
    imageName: selenium/distributor

    imagePullPolicy: IfNotPresent
    imagePullSecret: ""

    annotations: {}
    port: 5553
    resources: {}
    serviceType: ClusterIP
    serviceAnnotations: {}
    tolerations: []
    nodeSelector: {}
    priorityClassName: ""

  eventBus:
    imageName: selenium/event-bus

    imagePullPolicy: IfNotPresent
    imagePullSecret: ""

    annotations: {}
    port: 5557
    publishPort: 4442
    subscribePort: 4443
    resources: {}
    serviceType: ClusterIP
    serviceAnnotations: {}
    tolerations: []
    nodeSelector: {}
    priorityClassName: ""

  sessionMap:
    imageName: selenium/sessions

    imagePullPolicy: IfNotPresent
    imagePullSecret: ""

    annotations: {}
    port: 5556
    resources: {}
    serviceType: ClusterIP
    serviceAnnotations: {}
    tolerations: []
    nodeSelector: {}
    priorityClassName: ""

  sessionQueue:
    imageName: selenium/session-queue

    imagePullPolicy: IfNotPresent
    imagePullSecret: ""

    annotations: {}
    port: 5559
    resources: {}
    serviceType: ClusterIP
    serviceAnnotations: {}
    tolerations: []
    nodeSelector: {}
    priorityClassName: ""

  extraEnvironmentVariables:

  extraEnvFrom:

hub:
  imageName: selenium/hub
  imagePullPolicy: IfNotPresent
  imagePullSecret: ""

  annotations: {}
  labels: {}
  publishPort: 4442
  subscribePort: 4443
  port: 4444
  livenessProbe:
    enabled: true
    path: /readyz
    initialDelaySeconds: 10
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
  readinessProbe:
    enabled: true
    path: /readyz
    initialDelaySeconds: 12
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
  extraEnvironmentVariables:
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "86400"
    - name: SE_NODE_SESSION_TIMEOUT
      value: "600"
  extraEnvFrom:
  resources: {}
  serviceType: ClusterIP
  loadBalancerIP: ""
  serviceAnnotations: {}
  tolerations: []
  nodeSelector: {}
  priorityClassName: ""

chromeNode:
  enabled: true

  deploymentEnabled: true

  replicas: 0
  imageName: selenium/node-chrome
  imagePullPolicy: IfNotPresent
  imagePullSecret: ""

  ports:
    - 5555
  seleniumPort: 5900
  seleniumServicePort: 6900
  annotations: {}
  labels: {}
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "1"
  tolerations: []
  nodeSelector: {}
  hostAliases:
  extraEnvironmentVariables:
    - name: SE_SCREEN_WIDTH
      value: "1920"
    - name: SE_SCREEN_HEIGHT
      value: "1080"
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "86400"
    - name: SE_NODE_SESSION_TIMEOUT
      value: "600"
  extraEnvFrom:
  service:
    enabled: true
    type: ClusterIP
    annotations: {}
  dshmVolumeSizeLimit: 2Gi
  priorityClassName: ""

  startupProbe: {}
  terminationGracePeriodSeconds: 300
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh", "-c", "curl --request POST 'localhost:5555/se/grid/node/drain' --header 'X-REGISTRATION-SECRET;'; tail --pid=$(pgrep -f '[n]ode --bind-host false --config /opt/selenium/config.toml') -f /dev/null; sleep 30s"]

  extraVolumeMounts: []

  extraVolumes: []

firefoxNode:
  enabled: true

  deploymentEnabled: true

  replicas: 0
  imageName: selenium/node-firefox
  imagePullPolicy: IfNotPresent
  imagePullSecret: ""

  ports:
    - 5555
  seleniumPort: 5900
  seleniumServicePort: 6900
  annotations: {}
  labels: {}
  tolerations: []
  nodeSelector: {}
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "1"
  hostAliases:
  extraEnvironmentVariables:
    - name: SE_SCREEN_WIDTH
      value: "1920"
    - name: SE_SCREEN_HEIGHT
      value: "1080"
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "86400"
    - name: SE_NODE_SESSION_TIMEOUT
      value: "600"
  extraEnvFrom:
  service:
    enabled: true
    type: ClusterIP
    annotations: {}
  dshmVolumeSizeLimit: 2Gi
  priorityClassName: ""

  startupProbe: {}
  terminationGracePeriodSeconds: 300
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh", "-c", "curl --request POST 'localhost:5555/se/grid/node/drain' --header 'X-REGISTRATION-SECRET;'; tail --pid=$(pgrep -f '[n]ode --bind-host false --config /opt/selenium/config.toml') -f /dev/null; sleep 30s"]

  extraVolumeMounts: []

  extraVolumes: []

edgeNode:
  enabled: true

  deploymentEnabled: true

  replicas: 0
  imageName: selenium/node-edge
  imagePullPolicy: IfNotPresent
  imagePullSecret: ""

  ports:
    - 5555
  seleniumPort: 5900
  seleniumServicePort: 6900
  annotations: {}
  labels: {}
  tolerations: []
  nodeSelector: {}
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "1"
  hostAliases:
  extraEnvironmentVariables:
    - name: SE_SCREEN_WIDTH
      value: "1920"
    - name: SE_SCREEN_HEIGHT
      value: "1080"
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "86400"
    - name: SE_NODE_SESSION_TIMEOUT
      value: "600"
  extraEnvFrom:
  service:
    enabled: true
    type: ClusterIP
    annotations:
      hello: world
  dshmVolumeSizeLimit: 2Gi
  priorityClassName: ""

  startupProbe: {}
  terminationGracePeriodSeconds: 300
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh", "-c", "curl --request POST 'localhost:5555/se/grid/node/drain' --header 'X-REGISTRATION-SECRET;'; tail --pid=$(pgrep -f '[n]ode --bind-host false --config /opt/selenium/config.toml') -f /dev/null; sleep 30s"]

  extraVolumeMounts: []

  extraVolumes: []

customLabels: {}
```
########## We use the following helm command to deploy Selenium ##########

helm upgrade --install selenium-grid docker-selenium/selenium-grid --set isolateComponents=false --set ingress.enabled=false -n selenium-dev --values values-dev.yaml

### Logs from KEDA operator

```
example
```

### KEDA Version

2.10.0

### Kubernetes Version

1.24

### Platform

Microsoft Azure

### Scaler Details

Selenium KEDA scaler

### Anything else?

Selenium Grid version: 4.8.3 (revision b19b418e60)
OS Arch: amd64
OS Name: Linux
OS Version: 5.4.0-1098-azure

The issue is noticed with previous version of KEDA and selenium grid as well. 

I also logged an issue under SeleniumHQ/docker-selenium regarding the same: https://github.com/SeleniumHQ/docker-selenium/issues/1800
