### ISSUE TITLE
Azure Service bus namespace cannot be pulled from TriggerAuthentication

### ISSUE THREAD

**Issue by Mikel-Landa** [kedacore/keda#4469]
### Report

From the documentation, I was expecting to be able to add metada parameters to the trigger from the triggerauthentication resource. However, when I define the TA with secretRef: 
  ```
secretTargetRef:
  - key: service-bus-namespace
    name: commons
    parameter: namespace
```

and the SO with this trigger:
 ```
 triggers:
    - authenticationRef:
        name: service-bus
      metadata:
        cloud: AzurePublicCloud
        messageCount: '1'
        queueName: sbq-lookup
      type: azure-servicebus

```

the SO event is: KEDAScalerFailed    error parsing azure service bus metadata: namespace are required when using pod identity

### Expected Behavior

I expected to be able to inject the namespace to the SO object from the TA definition, but was not able to.

### Actual Behavior

When defining the SO object with the Azure Service Bus scaler, unless I specify the namespace at creation time, the SO will fail.

### Steps to Reproduce the Problem

1. Create a TA object with a parameter referencing the namespace for a Service Bus namespace
2. Create a SO object. Define queueName but not namespace for the servicebus trigger and reference the TA.
3. SO should output the same event as described above

### Logs from KEDA operator

```
2023-04-24T15:10:38Z    ERROR   scale_handler   error resolving auth params     {"type": "ScaledObject", "namespace": "allocation-functions", "name": "lookup", "scalerIndex": 0, "error": "error parsing azure service bus metadata: namespace are required when using pod identity"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
        /workspace/pkg/scaling/scalers_builder.go:81
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).performGetScalersCache
        /workspace/pkg/scaling/scale_handler.go:352
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
        /workspace/pkg/scaling/scale_handler.go:273
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
        /workspace/pkg/scaling/scale_handler.go:547
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
        /workspace/pkg/scaling/scale_handler.go:228
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
        /workspace/pkg/scaling/scale_handler.go:167
```

### KEDA Version

2.10.1

### Kubernetes Version

1.25

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus

### Anything else?
Keda version is actually 2.10.2, but the selector didn´t have the option.
