### ISSUE TITLE
Scaling to one replica more than Kafka topic partitions

### ISSUE THREAD

**Issue by dinonazlicsyntio** [kedacore/keda#4483]
### Report

I used Keda to scale the Kafka consumer workload based on Kafka metrics. The consumer was reading messages from Kafka topic with 5 partitions. Kafka trigger used 'lagThreshold' with a value set to 5 as a scaling metric and had the 'allowIdleConsumers' property set to false. 
In certain situations, HPA would scale to 6 replicas for a short period (< 1 minute), one replica more than Kafka topic partitions.
Since this isn't expected behavior or isn't mentioned elsewhere in the documentation, I would like to clarify the situation.

To be more precise, I could separate scaling in 4 scenarios:
- when the producer was shut down, scaling was as expected and consumer was scaled to 0
- when producer was configured to produce somewhat slower, scaling was as expected and consumer was scaled to >= 1 && < 5
- when producer was configured to produce much faster, scaling was as expected and consumer was scaled to 5 

- however, when the producer was configured with a throughput that caused the consumer to scale somewhere between 4 & 5 replicas (constantly changing), sometimes 6 replicas appeared to be active

### Expected Behavior

At all times, scaling should be constrained with an upper limitation equal to the number of Kafka topic partitions.

### Actual Behavior

Instead of the maximum number of replicas at any given time being 5, HPA would occasionally scale to 6. HPA would downscale to 5 or less within a shorter period of time (< 1 minute).

<img width="492" alt="scaling465646" src="https://user-images.githubusercontent.com/105198890/234832216-08026473-b751-4a6c-8911-3a1c7df17187.png">

### Steps to Reproduce the Problem

1. Set consumer processing time to 200 milliseconds and provide a topic with 5 partitions (in ConfigMap)
2. deploy ConfigMap and consumer Deployment
3. deploy ScaledObject
4. Start producer locally with processing time set to 600 milliseconds
5. observe deployments number of replicas

**ConfigMap**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-configmap
data:
  PROCESSING_TIME: "200"
  KAFKA_ADDRESS: "<KAFKA_IP:PORT>"
  KAFKA_TOPIC: "keda-topic"
  GROUP_ID: "keda-group"
```

**Consumer Deployment**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer-container
          image: dinonazlic/kafka-consumer:latest
          envFrom:
            - configMapRef:
                name: consumer-configmap
```

**ScaledObject**
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaled
spec:
  scaleTargetRef:
    name: consumer-deployment
  # cooldownPeriod: 30
  maxReplicaCount:  10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: <KAFKA_IP:PORT>
        consumerGroup: keda-group
        topic: keda-topic
        lagThreshold: '5'
```

**Consumer source code**
```
package main

import (
	"context"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	kafka "github.com/segmentio/kafka-go"
)

func getKafkaReader(kafkaURL, topic, groupID string) *kafka.Reader {
	brokers := strings.Split(kafkaURL, ",")
	return kafka.NewReader(kafka.ReaderConfig{
		Brokers:  brokers,
		GroupID:  groupID,
		Topic:    topic,
		MinBytes: 10e3, // 10KB
		MaxBytes: 10e6, // 10MB
	})
}

func main() {
	// get kafka reader using environment variables.
	processingTime, _ := strconv.Atoi(os.Getenv("PROCESSING_TIME"))
	kafkaAddress := os.Getenv("KAFKA_ADDRESS")
	topic := os.Getenv("KAFKA_TOPIC")
	groupID := os.Getenv("GROUP_ID")

	reader := getKafkaReader(kafkaAddress, topic, groupID)

	defer reader.Close()

	fmt.Println("start consuming ... !!")
	for {
		m, err := reader.ReadMessage(context.Background())
		if err != nil {
			fmt.Printf(err.Error())
			continue
		}
		time.Sleep(time.Duration(processingTime) * time.Millisecond)
		fmt.Printf("message at topic:%v partition:%v offset:%v	%s = %s\n", m.Topic, m.Partition, m.Offset, string(m.Key), string(m.Value))
	}
}

```

**Producer source code**
```
package main

import (
	"fmt"
	"log"
	"os"
	"strconv"
	"time"

	"github.com/Shopify/sarama"
)

func main() {
	// Load env variables
	processingTime, _ := 600
	kafkaAddress := <KAFKA_IP:PORT>
	topic := "keda-topic" 

	// Configure the producer
	config := sarama.NewConfig()
	config.Producer.Partitioner = sarama.NewRoundRobinPartitioner
	config.Producer.RequiredAcks = sarama.WaitForAll
	config.Producer.Return.Successes = true

	// Create a new sync producer
	client, err := sarama.NewClient([]string{kafkaAddress}, config)
	if err != nil {
		log.Fatalln("Failed to create a client:", err)
	}

	producer, err := sarama.NewSyncProducerFromClient(client)
	if err != nil {
		log.Fatalln("Failed to create producer:", err)
	}
	defer producer.Close()

	i := 0
	ticker := time.NewTicker(time.Duration(processingTime) * time.Millisecond)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			i++

			// Create a new message to send
			message := &sarama.ProducerMessage{
				Topic: topic,
				Value: sarama.StringEncoder("message ID: " + string(rune(i))),
			}

			// Send the message
			partition, offset, err := producer.SendMessage(message)
			if err != nil {
				log.Fatalln("Failed to send message:", err)
			}

			// Print the message content
			fmt.Printf("Message with id=%d, sent to partition %d at offset %d\n", i, partition, offset)
		}
	}
}

```

### KEDA Version

2.10.1

### Kubernetes Version

1.25

### Platform

Microsoft Azure

### Scaler Details

Kafka
