### ISSUE TITLE
Pods created by KEDA ScaledJob linger around in Terminated state

### ISSUE THREAD

**Issue by eugen-nw** [kedacore/keda#4536]
### Report

All pods created by KEDA's ScaledJob linger around in `kubectl get pods -o wide` output after the program in the Container finishes.

### Expected Behavior

I'd expect that the Pods that are in Terminated state to disappear, but they do not.  They linger as well in the ACI instance in the 'Succeeded' state.  I experience the disappearing behavior using KEDA scale-out going the route of ScaledObject.

### Actual Behavior

Kubectl keeps showing all ScaledJob generated pods which are in Terminated state.

### Steps to Reproduce the Problem

I'm certain that I'm missing something obvious, perhaps someone had already solved this problem?  Regretfully I could not find any solution on the web.  I'm prototyping using Jobs to handle long running processes.  I'm in the habit of calling `kubectl get pods -o wide` to check on the current state of the Deployment-type scale-outs; if that command shows me all the Pods that are in their Terminated state, that check will become unusable really soon.

AKS 1.25.6
KEDA 2.10.2
The Containers run on the virtual-node-aci-linux virtual node.

The Pods are created by a ScaledJob, do some very light processing and the program exits.  Each Pod contains only one Container.  Kubectl shows successively the Pending, Running and Terminated statuses.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.10.1

### Kubernetes Version

1.26

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus

### Anything else?
Workarounds:
- to filter out the "Terminated" Pods: `kubectl get pods -o wide | select-string -Pattern 'Terminated' -NotMatch`
- to hide them in ACI add the highlighted filter below.  For bonus points click on "Manage view" and save it.
![image](https://github.com/kedacore/keda/assets/15199814/e8b63dd0-dd09-4848-a8f3-b307ce007763)
- to delete all Pods created by the Job run the following command.  Regretfully I could not find a way to filter also on the Status field as that information does not seem to be present: `az container list --query "[?contains(name, <your unique identifier>)].[name]"  --output table | foreach {az container delete --name $_  --resource-group <hardcode your RG name> --yes}`

**Comment by JorTurFer** [comment]
Hi
Could you share your ScaledJob? If you execute the same job but as a job, what happens? Do the pods the same? This looks related with the job itself more than with KEDA because KEDA creates the jobs, but the pod status isn't managed by KEDA

**Comment by eugen-nw** [comment]
Thanks very much for looking into this!  It's right below.  Let me figure out how to make a Job out of it - I'm new to this, I'd used only Deployments in the past.
```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: aks-aci-genericdev-runner-linux
  labels:
    app: aks-aci-genericdev-runner-linux
    deploymentName: aks-aci-boldiq-genericdev-runner-linux
spec:
  jobTargetRef:
    template:
      spec:
        containers:  # this section is identical as for a "kind: Deployment"
        - name: boldiq-genericdev-runner-linux
          image: <removed>
          imagePullPolicy: Always
          resources:
            requests:
              memory: 6G
              cpu: 2
            limits:
              memory: 6G
              cpu: 2
          env:
          - name: KEDA_SERVICEBUS_CONNECTIONSTRING_LINUX
            value: <removed>
        tolerations:
          - key: virtual-kubelet.io/provider
            operator: Exists
          - key: azure.com/aci
            effect: NoSchedule
        imagePullSecrets:
          - name: docker-registry-secret-linux
        nodeName: virtual-node-aci-linux
  pollingInterval: 1  # 1 second polling for max. responsiveness
#  minReplicaCount: 2  # keeping two instances running permanently in order to improve low loads' performance
  triggers:
  - type: azure-servicebus
#    metricType: Value // The default AverageValue with messageCount: '1' starts up a new Container for each Message in the Queue.  We want that for responsiveness.
    metadata:
      queueName: requests
      connectionFromEnv: KEDA_SERVICEBUS_CONNECTIONSTRING_LINUX
      messageCount: '1'
```

**Comment by eugen-nw** [comment]
I suspect there's also a KEDA component in this.  If I run `kubectl delete -f <above YAML file>` then the `kubectl get pods -o wide` command no longer shows any of the KEDA spawn Pods that have the Terminated Status.  The are still present in ACI in the 'Succeeded' state.

At any rate, I'll see on Monday how to go about configuring a KEDA job.  Could you please share an example that may accelerate my work?

**Comment by eugen-nw** [comment]
This is what I've observed running the Pod using the script below:
1. startup & run, nothing special.  ACI (Azure Container Instances) reflected the state reported by `kubectl`
2. after completion `kubectl` showed "Terminated" and ACI displayed "Running".  Clicking on the Container -> Settings -> Container I was seeing the "Killing" event.
3. The Container disappears from ACI, `kubectl` still lists it as "Terminated".

```
apiVersion: batch/v1
kind: Job
metadata:
  name: aks-aci-genericdev-runner-linux
  labels:
    app: aks-aci-genericdev-runner-linux
    deploymentName: aks-aci-boldiq-genericdev-runner-linux
spec:
  template:
    spec:
      containers:  # this section is identical as for a "kind: Deployment"
      - name: boldiq-genericdev-runner-linux
        image: <removed>
        imagePullPolicy: Always
        resources:
          requests:
            memory: 6G
            cpu: 2
          limits:
            memory: 6G
            cpu: 2
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule
      imagePullSecrets:
        - name: docker-registry-secret-linux
      nodeName: virtual-node-aci-linux
      restartPolicy: Never
  backoffLimit: 4
```

**Comment by JorTurFer** [comment]
Hi,
Sorry for the slow response, I have been checking it deeper.
Do you see "Terminated" or "Terminating"? "Terminated" isn't a pod phase, it's a container state (which shouldn't be displayed as `kubectl get pods -o wide` output).

Other question, how many pods in that state do you see?  As default, KEDA keeps 100 succeeded jobs and 100 failed as history:
![image](https://github.com/kedacore/keda/assets/36899226/34c262c2-4f21-41b8-962c-cc56ae941469)

If you want that KEDA removes them faster, you can set those values with the desired amount of jobs, for example to not keep any job after finishing:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: aks-aci-genericdev-runner-linux
  labels:
    app: aks-aci-genericdev-runner-linux
    deploymentName: aks-aci-boldiq-genericdev-runner-linux
spec:
  jobTargetRef:
    ..job template...
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  pollingInterval: 1  # 1 second polling for max. responsiveness
#  minReplicaCount: 2  # keeping two instances running permanently in order to improve low loads' performance
  triggers:
  ...triggers...
```
