### ISSUE TITLE
Service Bus Scaler has issues with the minReplicaCount parameter

### ISSUE THREAD

**Issue by eugen-nw** [kedacore/keda#4541]
### Report

This parameter is documented as below.  Yet it does not seem to be operational.

> The min number of jobs that is created by default. This can be useful to avoid bootstrapping time of new jobs. If minReplicaCount is greater than maxReplicaCount, minReplicaCount will be set to maxReplicaCount.

### Expected Behavior

1. If I set it to 2 for example, there will be 2 Jobs always available.
2. If I set it in the script the Jobs scaling will work.  For the example above, if the count of Messages in the Queue exceeds 2, new Jobs will be started.

### Actual Behavior

Setting `minReplicaCount: 2` in the Job's script, after having deployed it I've noticed:
1. No new Containers were created automatically.  I were expecting to see 2 of them.
2. Sending Messages to the Queue did not create any Containers.  I'd have expected to see one Container being created for each Message I sent to the Queue.

### Steps to Reproduce the Problem

Below is the YAML script that I'm experimenting with:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: aks-aci-genericdev-runner-linux
  labels:
    app: aks-aci-genericdev-runner-linux
    deploymentName: aks-aci-boldiq-genericdev-runner-linux
spec:
  jobTargetRef:
    template:
      spec:
        containers:  # this section is identical as for a "kind: Deployment"
        - name: boldiq-genericdev-runner-linux
          image: <removed>
          imagePullPolicy: Always
          resources:
            requests:
              memory: 6G
              cpu: 2
            limits:
              memory: 6G
              cpu: 2
          env:
          - name: KEDA_SERVICEBUS_CONNECTIONSTRING_LINUX
            value: <removed>
        tolerations:
          - key: virtual-kubelet.io/provider
            operator: Exists
          - key: azure.com/aci
            effect: NoSchedule
        imagePullSecrets:
          - name: docker-registry-secret-linux
        nodeName: virtual-node-aci-linux
  pollingInterval: 1  # 1 second polling for max. responsiveness
  minReplicaCount: 2  # keeping two instances running permanently in order to improve low loads' performance
  triggers:
  - type: azure-servicebus
#    metricType: Value // The default AverageValue with messageCount: '1' starts up a new Container for each Message in the Queue.  We want that for responsiveness.
    metadata:
      queueName: requests
      connectionFromEnv: KEDA_SERVICEBUS_CONNECTIONSTRING_LINUX
      messageCount: '1'
```

AKS 1.25.6
KEDA 2.10.2
The Containers run on the virtual-node-aci-linux virtual node.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.10.1

### Kubernetes Version

1.25

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus
