### ISSUE TITLE
Job-based Service Bus Scaler scales to too many instances

### ISSUE THREAD

**Issue by eugen-nw** [kedacore/keda#4554]
### Report

Say that I configure KEDA with minReplicaCount > 0.  If I send Messages to the Queue, that causes KEDA to create as many new Pods as how many Messages there are in the Queue, with no regard to the count of Jobs that are always running, i.e. those created by the minReplicaCount > 0,

### Expected Behavior

Let's say that I configure KEDA to have 2 Jobs running permanently.  If I send 5 Messages to the Queue, I'd expect KEDA to create only 3 new Pods  Instead it is creating 5 new Pods, so they match the count of Messages in the Queue.  Below is the scaling behavior that the documentation at https://keda.sh/docs/2.9/concepts/scaling-jobs/ states.

![image](https://github.com/kedacore/keda/assets/15199814/03e410e9-cd75-4dbf-b221-68f64fc3a095)

### Actual Behavior

Please see above.

### Steps to Reproduce the Problem

1. Configure a KEDA Job deployment in a manner similar to the script below.
```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: aks-aci-boldiq-workforce-gozen-dev
  labels:
    app: aks-aci-boldiq-workforce-gozen-dev
    deploymentName: aks-aci-boldiq-workforce-gozen-dev
spec:
  jobTargetRef:
    template:
      spec:
        containers:  # this section is identical as for a "kind: Deployment"
        - image: <removed>
          imagePullPolicy: Always
          name: boldiq-workforce-gozen-dev
          resources:
            requests:
              memory: 8G
              cpu: 4
            limits:
              memory: 8G
              cpu: 4
          env:
          - name: KEDA_SERVICEBUS_CONNECTIONSTRING_GOZEN_DEV
            value: <removed>
        nodeSelector:
          kubernetes.io/os: windows
        tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule
        imagePullSecrets:
          - name: docker-registry-secret
        nodeName: virtual-kubelet
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  pollingInterval: 1  # 1 second polling for max. responsiveness
  minReplicaCount: 2  # keeping two instances running permanently in order to improve low loads' performance
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
#    metricType: Value // The default AverageValue with messageCount: '1' starts up a new Container for each Message in the Queue.  We want that for responsiveness.
    metadata:
      queueName: gozen-dev-requests
      connectionFromEnv: KEDA_SERVICEBUS_CONNECTIONSTRING_GOZEN_DEV
      messageCount: '1'
```
2. Deploy the script and check the count of Pods created.  Should be 2.

3. Send N Messages into the Queue.

4. Check the count of Pods created.  It will be N + 2.

### Logs from KEDA operator

Please email edaroczy@boldiq.com for the .ZIP file.

### KEDA Version

2.10.1

### Kubernetes Version

1.25

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus

### Anything else?

AKS 1.25.6
KEDA 2.10.2
The Containers run on the virtual-node-aci-linux virtual node.
