### ISSUE TITLE
Keda is scaling down all the previously scaled pods, when there is change to the Scaled object targetMetricValue 

### ISSUE THREAD

**Issue by vthiruveedhi** [kedacore/keda#4578]
### Keda is scaling down all the previously scaled pods, when there is a change to the Scaled object targetMetricValue file.

We are using EKS  cluster and deployed Keda via helm version keda-2.10.2
```
NAME	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART      	APP VERSION
keda	keda     	1       	2023-05-10 10:54:21.954269 -0400 EDT	deployed	keda-2.10.2	2.10.1
```

And we added a Scaled object to our helm chart, which queries CLoudwatch metric of a target group and we set out the request count as the targetMetricValue.

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bidder-verizon-dsp-bidder
spec:
  scaleTargetRef:
    name: prod-dsp-verizon-dsp-bidder 
  minReplicaCount:  1
  fallback:                                          # Optional. Section to specify fallback options
    failureThreshold: 2                              # Mandatory if fallback section is included
    replicas: 6 
  advanced:
    restoreToOriginalReplicaCount: false 
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          - type: Pods
            value: 4
            periodSeconds: 15
          selectPolicy: Max    
  triggers:
  - type: aws-cloudwatch
    metadata:
      expression: SELECT SUM("RequestCountPerTarget") FROM SCHEMA("AWS/ApplicationELB", TargetGroup) WHERE TargetGroup = 'targetgroup/k8s-proddspv-proddspv-ce1fc9d807/2dfc230a0b38125b'
      targetMetricValue: "95000"
      minMetricValue: "1"
      awsRegion: "us-east-1"
      identityOwner: operator

```
The Scaled object is perfectly pulling the metrics from the CLoudWatch 
```
 status:
    conditions:
    - message: ScaledObject is defined correctly and is ready for scaling
      reason: ScaledObjectReady
      status: "True"
      type: Ready
    - message: Scaling is performed because triggers are active
      reason: ScalerActive
      status: "True"
      type: Active
    - message: No fallbacks are active on this scaled object
      reason: NoFallbackFound
      status: "False"
      type: Fallback
    externalMetricNames:
    - s0-aws-cloudwatch
    health:
      s0-aws-cloudwatch:
        numberOfFailures: 0
        status: Happy
    hpaName: keda-hpa-bidder-verizon-dsp-bidder
    lastActiveTime: "2023-05-26T18:46:46Z"
    originalReplicaCount: 1
    scaleTargetGVKR:
      group: apps
      kind: Deployment
      resource: deployments
      version: v1
    scaleTargetKind: apps/v1.Deployment
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
 **and we see the pods and nodes beings scaled appropriately** 

```
NAME                                 REFERENCE                                TARGETS               MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-bidder-verizon-dsp-bidder   Deployment/prod-dsp-verizon-dsp-bidder   2287984m/4500 (avg)   1         100       8          166m
```
```
(⎈ |arn:aws:eks:us-east-1:323874082174:cluster/prod-dsp-bidder-verizon:prod-dsp-verizon)vthiruveedhi@vthiruveedhi-MacBook-Pro dsp-bidder-verizon % kgp
NAME                                          READY   STATUS    RESTARTS   AGE
prod-dsp-verizon-dsp-bidder-7f9678bb6-4f5nf   0/1     Running   0          2m37s
prod-dsp-verizon-dsp-bidder-7f9678bb6-76x2p   0/1     Running   0          3m7s
prod-dsp-verizon-dsp-bidder-7f9678bb6-9t7ct   0/1     Running   0          3m7s
prod-dsp-verizon-dsp-bidder-7f9678bb6-bnsz8   0/1     Running   0          2m37s
prod-dsp-verizon-dsp-bidder-7f9678bb6-cchcz   0/1     Running   0          3m7s
prod-dsp-verizon-dsp-bidder-7f9678bb6-d9dnl   0/1     Running   0          3m7s
prod-dsp-verizon-dsp-bidder-7f9678bb6-jjnfz   1/1     Running   0          34m
prod-dsp-verizon-dsp-bidder-7f9678bb6-ztknt   0/1     Running   0          2m52s
```
**but**  whenever we change the targetMetricValue and deploy via helm or manually edit the Scaled object manifest,the old pods will be terminated and new ones will be created instead of letting a few old pods run. It starts pods from scratch again.
```
(⎈ |arn:aws:eks:us-east-1:323874082174:cluster/prod-dsp-bidder-verizon:prod-dsp-verizon)vthiruveedhi@vthiruveedhi-MacBook-Pro dsp-bidder-verizon % kgp
NAME                                          READY   STATUS              RESTARTS   AGE
prod-dsp-verizon-dsp-bidder-7f9678bb6-4f5nf   0/1     Terminating         0          3m10s
prod-dsp-verizon-dsp-bidder-7f9678bb6-76x2p   0/1     Terminating         0          3m40s
prod-dsp-verizon-dsp-bidder-7f9678bb6-9t7ct   0/1     Terminating         0          3m40s
prod-dsp-verizon-dsp-bidder-7f9678bb6-bnsz8   0/1     Terminating         0          3m10s
prod-dsp-verizon-dsp-bidder-7f9678bb6-cchcz   0/1     Terminating         0          3m40s
prod-dsp-verizon-dsp-bidder-7f9678bb6-d9dnl   0/1     Terminating         0          3m40s
prod-dsp-verizon-dsp-bidder-7f9678bb6-jjnfz   1/1     Running             0          34m
prod-dsp-verizon-dsp-bidder-7f9678bb6-ll7tv   0/1     ContainerCreating   0          9s
prod-dsp-verizon-dsp-bidder-7f9678bb6-lmdgw   0/1     ContainerCreating   0          9s
prod-dsp-verizon-dsp-bidder-7f9678bb6-q98dv   0/1     Pending             0          9s
prod-dsp-verizon-dsp-bidder-7f9678bb6-t8g67   0/1     Pending             0          9s
prod-dsp-verizon-dsp-bidder-7f9678bb6-ztknt   0/1     Terminating         0          3m25s
```

### Expected Behavior

The old pods should be in a running state and only a few pods should be terminated or created depending on the HPA  targetMetricValue. so the request can still be distributed between the pods. 

### Actual Behavior

All the running pods scaled by the HPA are terminated and new pods are created every time we change the value in  targetMetricValue.

### Steps to Reproduce the Problem

1. Install KEda via helm
2. Install an application with alb ingress ( which will create the target group )
3. Use the above Scaledobject  ( update the target group) 
4. Update the targetMetricValue 
5. Monitor the pods

### Logs from KEDA operator

```
example
```

### KEDA Version

None

### Kubernetes Version

1.26

### Platform

Amazon Web Services

### Scaler Details

Cloudwatch
