### ISSUE TITLE
I ran into a bug about kube-prometheus not automatically adding nodes when scaledobject resource objects are used with keda

### ISSUE THREAD

**Issue by lvdb-wuzihong** [kedacore/keda#4580]
### Report

This bug is about ScaledObject not being able to trigger automatic node additions based on Prometheus query results.

### Expected Behavior

Solve this problem and help see why.

### Actual Behavior

![scaleobject_describe](https://github.com/kedacore/keda/assets/129603508/8166b5aa-b605-4a1a-ae43-b7003e8ef472)
This seems normal, and I tested an autoscaling feature using hey -m GET -n 20000 http://10.110.89.174.
```
[root@master01 keda]# kubectl get svc
NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes          ClusterIP   10.96.0.1       <none>        443/TCP   293d
metrics-flask-app   ClusterIP   10.110.89.174   <none>        80/TCP    89m
```
```
[root@master01 keda]# cat scaled-object.yaml
apiVersion: keda.sh/v1alpha1
# Custom CRD provisioned by the Keda operator
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
spec:
  scaleTargetRef:
    # target our deployment
    name: metrics-flask-app
  # Interval to when to query Prometheus
  pollingInterval: 15
  # The period to wait after the last trigger reported active
  # before scaling the deployment back to 1
  cooldownPeriod: 30
  # min replicas keda will scale to
  # if you have an app that has an dependency on pubsub
  # this would be a good use case to set it to zero
  # why keep your app running if your topic has no messages?
  minReplicaCount: 1
  # max replicas keda will scale to
  maxReplicaCount: 20
  advanced:
    # HPA config
    # Read about it here: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 50
              periodSeconds: 10
  triggers:
    - type: prometheus
      metadata:
        # address where keda can reach our prometheus on
        serverAddress: http://192.168.111.100:30090
        # metric on what we want to scale
        metricName: request_count_total
        # if treshold is reached then Keda will scale our deployment
        threshold: "0.01"
        query: sum(rate(request_count_total[1m]))
```
```
[root@master01 keda]# kubectl get svc
NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes          ClusterIP   10.96.0.1       <none>        443/TCP   293d
metrics-flask-app   ClusterIP   10.110.89.174   <none>        80/TCP    91m
```
```
[root@master01 keda]# cat /opt/k
k8s_prom/       keda/           kubernetes_dev/
```
```
[root@master01 keda]# cat /opt/k
k8s_prom/       keda/           kubernetes_dev/
```
```
[root@master01 keda]# cat /opt/k8s_prom/metrics-app/
Dockerfile              main.py                 metrics-flask-app.yaml
```
```
[root@master01 keda]# cat /opt/k8s_prom/metrics-app/
Dockerfile              main.py                 metrics-flask-app.yaml
```
```
[root@master01 keda]# cat /opt/k8s_prom/metrics-app/metrics-flask-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
      # 声明Prometheus采集
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/lvdoubing/flask-app:v1
        imagePullPolicy: IfNotPresent
        name: web
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-flask-app
  labels:
    run: metrics-flask-app
spec:
  ports:
  - port: 80
    name: web
    protocol: TCP
    targetPort: 80
  selector:
    app: flask-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      run: metrics-flask-app
  endpoints:
  - port: web
`
```
Prometheus has also obtained relevant indicators.

### Steps to Reproduce the Problem

1. deploy kube-prometheus
2.deploy a test app 
```
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
      # 声明Prometheus采集
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/lvdoubing/flask-app:v1
        imagePullPolicy: IfNotPresent
        name: web
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-flask-app
  labels:
    run: metrics-flask-app
spec:
  ports:
  - port: 80
    name: web
    protocol: TCP
    targetPort: 80
  selector:
    app: flask-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      run: metrics-flask-app
  endpoints:
  - port: web
`
```
3. deploy the keda:2.10.1 and deploy scaledobject
```
`[root@master01 keda]# cat scaled-object.yaml
apiVersion: keda.sh/v1alpha1
# Custom CRD provisioned by the Keda operator
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
spec:
  scaleTargetRef:
    # target our deployment
    name: metrics-flask-app
  # Interval to when to query Prometheus
  pollingInterval: 15
  # The period to wait after the last trigger reported active
  # before scaling the deployment back to 1
  cooldownPeriod: 30
  # min replicas keda will scale to
  # if you have an app that has an dependency on pubsub
  # this would be a good use case to set it to zero
  # why keep your app running if your topic has no messages?
  minReplicaCount: 1
  # max replicas keda will scale to
  maxReplicaCount: 20
  advanced:
    # HPA config
    # Read about it here: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 50
              periodSeconds: 10
  triggers:
    - type: prometheus
      metadata:
        # address where keda can reach our prometheus on
        serverAddress: http://192.168.111.100:30090
        # metric on what we want to scale
        metricName: request_count_total
        # if treshold is reached then Keda will scale our deployment
        threshold: "0.01"
        query: sum(rate(request_count_total[1m]))
`
```

### Logs from KEDA operator

```
example
```

### KEDA Version

2.10.1

### Kubernetes Version

1.24

### Platform

Other

### Scaler Details

Prometheus
