### ISSUE TITLE
[NATS JetStream] Allow dynamically pull AccountID from a secret

### ISSUE THREAD

**Issue by martin31821** [kedacore/keda#4586]
### Proposal

I propose a change to the Nats JetStream scaler, where the account ID can be specified from an external resource, such as a secret. 

### Use-Case

I'm running a NATS Cluster with several (dynamically created) tenants, running with a self-designed authentication server (github.com/deinstapel/nats-jwt-operator), where the Account IDs are not known in advance. My Operator dynamically creates NATS tenants and accounts with a kubernetes CRD and writes the account IDs into the .status of the CRD as well as to a secret.

I would like to be able to tell KEDA to scale based on these accounts, so I can include KEDA in my CD pipeline.

### Is this a feature you are interested in implementing yourself?

Yes

### Anything else?

Example:

Currently existing code:

```yaml
triggers:
- type: nats-jetstream
  metadata:
    natsServerMonitoringEndpoint: "nats.nats.svc.cluster.local:8222"
    account: "$G"
```

Possible new implementation:

```yaml
triggers:
- type: nats-jetstream
  metadata:
    natsServerMonitoringEndpoint: "nats.nats.svc.cluster.local:8222"
    accountRef:
      secretName: "my-accountSecret"
      secretKey: "account-id"
```
