### ISSUE TITLE
Error 401 in Azure service bus autoscaler

### ISSUE THREAD

**Issue by rmacian** [kedacore/keda#4656]
### Report

I am  configuring a ScaledObject with azure-servicebus-auth . If I configure the connection parameter with a RootManaged key I get a 401 error

Instead If I use a specific key for the queue it works:

`Normal  KEDAScalersStarted  55s  keda-operator  Started scalers watch`

The difference between both connection strings is that the specifickey has a EntityPath argument that the RootManagedKey doesn't have

```
Endpoint=sb://my-msg.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XXXX=
Endpoint=sb://my-msg.servicebus.windows.net/;SharedAccessKeyName=nt-qa-msg-queue-policy;SharedAccessKey=XXXX=;EntityPath=my_queue
```
Is possible to use the same key for all my queues and not have to create a new queue for every queue?

### Expected Behavior

The RootManagedKey should be able to read metrics for all queues in my instance

### Actual Behavior
```bash
--------------------------------------------------------------------------------
RESPONSE 401: 401 Unauthorized
ERROR CODE: 401
--------------------------------------------------------------------------------
<Error><Code>401</Code><Detail>claim is empty or token is invalid. TrackingId:3c65c64b-b2db-4873-9781-68335d9cea25_G42, SystemTracker:my-msg.servicebus.windows.net:my_queue, Timestamp:2023-06-07T13:47:30</Detail></Error>
apiVersion: keda.sh/v1alpha1
```
### Steps to Reproduce the Problem

1. Create a secret with 'connection' param with the connection string of a RootManaged key to service bus encrypted in base64 
2. Create a TriggerAuthentication with a ref to the secret above
3. Create a Scaledobject with azure-servicebus-auth

### Logs from KEDA operator

```
2023-06-07T14:05:29Z	ERROR	azure_servicebus_scaler	error getting service bus entity length	{"type": "ScaledObject", "namespace": "my-namepsace", "name": "scaled-transactions-api", "error": "GET https://my-msg.servicebus.windows.net/my_msg_queue\n--------------------------------------------------------------------------------\nRESPONSE 401: 401 Unauthorized\nERROR CODE: 401\n--------------------------------------------------------------------------------\n<Error><Code>401</Code><Detail>claim is empty or token is invalid. TrackingId:ce7947ec-b9e7-4f78-8764-720f0cb593bf_G42, SystemTracker:my-msg.servicebus.windows.net:my_msg_queue, Timestamp:2023-06-07T14:05:29</Detail></Error>\n--------------------------------------------------------------------------------\n"}
github.com/kedacore/keda/v2/pkg/scalers.(*azureServiceBusScaler).GetMetricsAndActivity
	/workspace/pkg/scalers/azure_servicebus_scaler.go:262
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
	/workspace/pkg/scaling/cache/scalers_cache.go:140
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:578
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:228
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:167
2023-06-07T14:05:29Z	ERROR	scale_handler	error getting scale decision	{"scaledObject.Namespace": "my-namespace", "scaledObject.Name": "scaled-transactions-api", "scaler": "azureServiceBusScaler", "error": "GET https://my-msg.servicebus.windows.net/my_msg_queue\n--------------------------------------------------------------------------------\nRESPONSE 401: 401 Unauthorized\nERROR CODE: 401\n--------------------------------------------------------------------------------\n<Error><Code>401</Code><Detail>claim is empty or token is invalid. TrackingId:ce7947ec-b9e7-4f78-8764-710f0cb593bf_G42, SystemTracker:my-msg.servicebus.windows.net:my_msg_queue, Timestamp:2023-06-07T14:05:29</Detail></Error>\n--------------------------------------------------------------------------------\n"}
```

### KEDA Version

2.10.1

### Kubernetes Version

1.25

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus

### Anything else?

I have opened a ticket with Azure support and they have told me that perhaps the way keda is connecting is wrong or the api-version is outdated:

```
Gateway could not validate the authentication token. TrackingId: 0bafd493-d138-4fb6-9624-32cd6f243385_G24, Absolute Uri: https://my-msg.servicebus.windows.net/my_msg_queue?api-version=2021-05, Details: ExceptionId: cdc6fcd6-7653-4214-a56e-696356bab99e-Microsoft.ServiceBus.AuthorizationFailedException: InvalidSignature: The token has an invalid signature.
```

related issue:

https://github.com/kedacore/keda/issues/2117

**Comment by JorTurFer** [comment]
I missed this issue for a long time IDK why, sorry 😞 
I think that it can be done perfectly because we are already doing it for EventHub Scaler 
https://github.com/kedacore/keda/blob/ee81112c9fa47b3bee0907d56365aac1ed291e5d/pkg/scalers/azure_eventhub_scaler.go#L206-L219

We should add some code like above in the ServiceBus Scaler. Are you willing to contribute with the feature?

**Comment by v-shenoy** [comment]
Huh, that's interesting. Because in the [docs](https://keda.sh/docs/2.11/scalers/azure-service-bus/) we only mention the namespaced connection strings, not scoped to an entity. 

In fact, I tested it with a `RootManagedSharedAccessKey` and it is working fine for me (also with v2.10.1).

**Comment by v-shenoy** [comment]
The project is using `v1.4.0` of the `github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus` package. It uses the `NewClientFromConnectionString` method to create the admin client ([link](https://github.com/kedacore/keda/blob/1f4a685ad19ed9b8b42037aaf91cfd1d518460a8/pkg/scalers/azure_servicebus_scaler.go#L297C1-L298C80)). 

From the [docs](https://github.com/Azure/azure-sdk-for-go/blob/sdk/messaging/azservicebus/v1.4.0/sdk/messaging/azservicebus/admin/admin_client.go#L43), you can see that it supports connection strings both for a namespace and for entities. 
![image](https://github.com/kedacore/keda/assets/38671299/2f1ad042-2a2e-4450-8196-5e8265d258df)

**Comment by v-shenoy** [comment]
I just tested this again. These are the objects in my cluster -
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 20m
            memory: 32Mi
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
---
apiVersion: v1
kind: Secret
metadata:
  name: alpine-secret
type: Opaque
stringData:
  SERVICEBUS_CONNECTION_STRING: "Endpoint=sb://kedasbtest.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<key>"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: alpine-ta
spec:
  secretTargetRef:
  - parameter: connection
    name: alpine-secret
    key: SERVICEBUS_CONNECTION_STRING
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: alpine-so
spec:
  scaleTargetRef:
    name: alpine
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 2000
  fallback:
    failureThreshold: 5
    replicas: 100
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 15
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: testqueue
      messageCount: '1'
    authenticationRef:
      name: alpine-ta
```


I also tried using `data` with the base64 encoded string instead of `stringData`
```
apiVersion: v1
kind: Secret
metadata:
  name: alpine-secret
type: Opaque
data:
  SERVICEBUS_CONNECTION_STRING: "<base64-encoded-conn-string>"
```
And everything is working as expected.
