### ISSUE TITLE
unexpected cron scaling issue when start / end are defined with different days

### ISSUE THREAD

**Issue by rubroboletus** [kedacore/keda#4677]
### Report

We wanna to scale our deployments / statefulsets from 0 replicas to bigger number (3) during working days from 6:30AM to 10:10PM.  We have used following setup:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-node-chrome
  namespace: selenium-hub
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  cooldownPeriod: 300
  fallback:
    failureThreshold: 3
    replicas: 3
  idleReplicaCount: 0
  maxReplicaCount: 3
  minReplicaCount: 0
  pollingInterval: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: selenium-node-chrome
  triggers:
  - metadata:
      desiredReplicas: "3"
      end: 10 22 * * *
      start: 30 6 * * 1-5
      timezone: Europe/Prague
    type: cron
```

The problem is, that during working days from Mon to Fri, pods are correctly started, but they did not stop on Friday, as expected, and keep running till Sunday 22:10.

### Expected Behavior

We expect, that using this definition for cron, pods will start (scale up to 3 replicas) each working day at 6:30 and stop (scale down to 0 replicas) daily at 22:10.

### Actual Behavior

During working days from Mon to Fri, pods are correctly started, but they did not stop on Friday, as expected, and keep running till Sunday 22:10.

### Steps to Reproduce the Problem

1. define any statefulset / deployment
2. define scaledobject from our example
3. wait till friday night

### Logs from KEDA operator

```
example
```

### KEDA Version

2.10.0

### Kubernetes Version

1.26

### Platform

Amazon Web Services

### Scaler Details

cron

**Comment by JorTurFer** [comment]
Hi,
You are right!, I can reproduce the issue and it's because in this code:
https://github.com/kedacore/keda/blob/2234a6f30df6b9fa83a1b88f1aa609ebee846983/pkg/scalers/cron_scaler.go#L164-L174

as the next start is on Monday and next end is today, the first case is rejected, but as current time is before end time, the scaler thinks that it's in active period. TBH, I don't see an easy solution from code pov because there are multiple "end periods" without any "starting period", but I can suggest a workaround. if you set the ending cron for the same days that the starting cron, the problem will be solved:
```
  - metadata:
      desiredReplicas: "3"
      end: 10 22 * * 1-5
      start: 30 6 * * 1-5
      timezone: Europe/Prague

```
