### ISSUE TITLE
host.json functions array does not get applied

### ISSUE THREAD

**Issue by Janus88** [kedacore/keda#473]
I specified 2 of 19 functions of my project to be executed in host.json functions array:

{
  "version": "2.0",
  "functions": [ "Function1", "AvisWEVorgaengeImportieren" ]
}

## Expected Behavior
Only the 2 specified functions will run

## Actual Behavior
All 19 functions run on deployed container. Running locally in docker works like expected

## Steps to Reproduce the Problem

  1. Create 2 or more functions
  2. Specify in host.json --> functions[] which function to run
  3. Generate deploy.yml:
       --> func kubernetes deploy --name lvstimerfunctions --registry __dockerrepository__ --pull-secret cubedocker --csharp --secret-name lvstimerfunctions --dry-run > deploy.yml
  4. Publish deploy.yml in Kubernetes cluster

## Generated deploy.yml

Content:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lvstimerfunctions
  namespace: __KubernetesNamespace__
  labels:
    app: lvstimerfunctions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lvstimerfunctions
  template:
    metadata:
      labels:
        app: lvstimerfunctions
    spec:
      containers:
      - name: lvstimerfunctions
        image: __dockerrepository__/lvstimerfunctions
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: Archivierung
        - name: AzureFunctionsJobHost__functions__1
          value: ArtikelLagerbestandAbgleich
        - name: AzureFunctionsJobHost__functions__2
          value: AvisWEFreigabe
        - name: AzureFunctionsJobHost__functions__3
          value: AvisWEFreigabeBerichteVerschicken
        - name: AzureFunctionsJobHost__functions__4
          value: AvisWEVorgaengeImportieren
        - name: AzureFunctionsJobHost__functions__5
          value: BestaendeMitMengeNullLoeschen
        - name: AzureFunctionsJobHost__functions__6
          value: CheckTransportmittelOhneVorgang
        - name: AzureFunctionsJobHost__functions__7
          value: CubeSQLBestandAbgleich
        - name: AzureFunctionsJobHost__functions__8
          value: Function1
        - name: AzureFunctionsJobHost__functions__9
          value: LagerbestandAbgleich
        - name: AzureFunctionsJobHost__functions__10
          value: LagerbewegungenRueckmeldung
        - name: AzureFunctionsJobHost__functions__11
          value: LieferscheineB2BErledigtWegschreiben
        - name: AzureFunctionsJobHost__functions__12
          value: LieferscheineB2BOffenWegschreiben
        - name: AzureFunctionsJobHost__functions__13
          value: LieferscheineSchichtleistungBerechnen
        - name: AzureFunctionsJobHost__functions__14
          value: LieferscheinReservierungenBerichtigen
        - name: AzureFunctionsJobHost__functions__15
          value: LieferscheinStornoanfragenVerarbeiten
        - name: AzureFunctionsJobHost__functions__16
          value: LieferscheinVersandstatusUebersichtWegschreiben
        - name: AzureFunctionsJobHost__functions__17
          value: SchnittpunktRoutenBerechnen
        - name: AzureFunctionsJobHost__functions__18
          value: SendungenAbschliessen
        - name: AzureFunctionsJobHost__functions__19
          value: VorgangKategorieUserLeistungBerechnen
        envFrom:
        - secretRef:
            name: lvstimerfunctions
      imagePullSecrets:
      - name: cubedocker
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: lvstimerfunctions
  namespace: __KubernetesNamespace__
  labels:
    deploymentName: lvstimerfunctions
spec:
  scaleTargetRef:
    deploymentName: lvstimerfunctions
  minReplicaCount: 1
  maxReplicaCount: 1
  triggers:
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 0 1 * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 0 3 * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 * * * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 */3 * * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 * * * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 30 3 * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 0 */3 * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 30 3 * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 0 0 * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 0 3 * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 */1 * * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 0 * * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 0 * * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 30 * * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 45 3 * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 * * * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 0 * * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 0 3 * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 * * * * *
      name: myTimer
  - type: timertrigger
    metadata:
      type: timerTrigger
      schedule: 0 30 2 * * *
      name: myTimer
```
