### ISSUE TITLE
Provide CloudEvent design proposal to extend KEDA

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#479]
Provide CloudEvent that are emitted by the runtime so that customers can extend KEDA.

Events that come to mind are:
- `New Trigger Authentication Created`
- `Deployment Scaled to Zero`
- `New Scaled Object Created`
- Information on scaling action
- Information about new scaled object referencing existing trigger authentication

Only concern I have is that folks could go through the Kubernetes eventing approach to get the information, but if we would emit it ourselves we could make it more user friendly rather than having to figure this out via the Kube way

## Tasklist

- [x] Create proposal
- [x] Agree on proposal
- [x] Define list of events & payloads to emit
- [ ] Implement
- [ ] Document

**Comment by tomkerkhove** [comment]
Thoughts @jeffhollan?

**Comment by zroubalik** [comment]
We should definitely implement the Kuberenetes eventing approach (created https://github.com/kedacore/keda/issues/530). This could be lower priority item.

**Comment by tomkerkhove** [comment]
Thanks for that! Since Kubernetes doens't support CloudEvents (yet), I would leverage this as a seperate component as well to make it easier to integrate with other products/tools that are not Kubernetes event specific.

See https://github.com/kubernetes/kubernetes/issues/85544 for CloudEvents support in Kubernetes.

**Comment by tomkerkhove** [comment]
The reason for that is that, for most scenarios you'd want to react on these events, and these workloads are not always in Kubernetes. If we only support Kubernetes events how it is today, events are stuck inside the cluster so they are, in my opinion, often pointless.

If we have CloudEvents, we can just forward them to things like Azure Event Grid and take it from there.

**Comment by tomkerkhove** [comment]
I will provide a more thorough proposal before we start on this.

**Comment by tomkerkhove** [comment]
My goal with this issue is to allow end-users to subscribe to events emitted by KEDA that provide them insights into what is going on.

These should serve several purposes such as:
- Allow for autoscaling awareness (scaling)
- Allow for automated notifications for incidents (errors, misconfiguration)
- ...

> **But, but, Kubernetes events?!**
> Today, we already offer cluster events but the use-case for these are different since they live in the cluster and are hard to use outside of it unless you use something such as [Kubernetes Event Exporter](https://github.com/opsgenie/kubernetes-event-exporter) and parse the raw events which is clunky given there is no standard way of writing those events

From a high-level perspective, KEDA will be doing 3 things:

1. Scale workloads in a single namespace across one or more namespaces
2. Provide Kubernetes events inside the cluster that can be used through the typical tooling (CLI, UIs, ...)
3. Emit events to endpoints inside/outside the cluster that are [CloudEvents](http://cloudevents.io/)-compliant

![Picture1](https://user-images.githubusercontent.com/4345663/145172657-0500068f-490b-4ba2-b2d7-dfbb74e88248.png)

## Proposal

My first idea was that we could easily add this as an endpoint to which KEDA can push events, but this will quickly become a bottleneck for end-users that have numerous namespaces and want to have more control on who is allowed to receive what events:

- Cluster admins/operators will want to have events for scaling in all namespaces
- App devs/operators will only be interested in the events for their applications

While every team *could* do the filtering on their own, this is a waste of compute.

I believe it would be ideal if we introduce a new `EventSink` CRD (name is just proposal) which is scoped to the whole cluster (admin operators) or namespaces (app operators):

```yaml
apiVersion: keda.sh/v1alpha1
kind: EventSink # Or ClusterEventSink
metadata:
  name: operations-cross-cluster-events
spec:
  # Support regular webhook endpoints over HTTP
  webhook:
    uri: http://foo.bar
    authentication:
      apiKey:
        headerName: x-api-key
        valueFrom:
            secretKeyRef:
             name: secrets-operations-events
             key: webhook-api-key
  # We can add integration with other systems more easily, following TriggerAuthentication
  # This can be cloud providers, platforms, products, ...
  # ...
```

KEDA will then emit events to every `EventSink`, where appropriate.

If we should use our operator or another container for this to remove the burden/load off of our operator is something we can discuss.
