### ISSUE TITLE
keda-operator-metrics-apiserver does not listen on metrics port

### ISSUE THREAD

**Issue by schmidt-i** [kedacore/keda#4794]
### Report

After installation of keda 2.11.1 we receive a TargetDown alert for the keda-operator-metrics-apiserver. 
This is the cmd-line how the apiserver is started: 
`/usr/local/bin/keda-adapter --port=8080 --secure-port=6443 --logtostderr=true --metrics-service-address=keda-operator.blueprint.svc.cluster.local:9666 --client-ca-file=/certs/ca.crt --tls-cert-file=/certs/tls.crt --tls-private-key-file=/certs/tls.key --cert-dir=/certs --v=0`

We are using the helm chart to deploy keda and have enabled the metrics endpoint for the metricsServer and the operator: 
```
  values:
    certificates:
      certManager:
        enabled: true
    logging:
      operator:
        format: json
    prometheus:
      metricServer:
        enabled: true
        podMonitor:
          enabled: true
      operator:
        enabled: true
        podMonitor:
          enabled: true

```

However any connection to port 8080 (metrics port) is refused on the keda-operator-metrics-apiserver.

### Expected Behavior

keda-operator-metrics-apiserver exposes metrics on the metrics port (8080) and /metrics

### Actual Behavior

Connection refused on port 8080

### Steps to Reproduce the Problem

1. Install keda 2.11.1
2. Enable prometheus metrics for the metricServer
3. Connect to the metrics endpoint

### Logs from KEDA operator

```
example
```

### KEDA Version

2.11.1

### Kubernetes Version

1.26

### Platform

Microsoft Azure
