### ISSUE TITLE
Scaling Deployments doesn't work: unable to retrieve the complete list of server APIs

### ISSUE THREAD

**Issue by porscheme** [kedacore/keda#4808]
### Report

- Scaling Deployment doesn't work

### Expected Behavior

Deployment must be scaled based on the Azure-Blob storage

### Actual Behavior

Its giving below error
```unable to get client for deployments': unable to get full preferred group-version-resource for deployments.apps: failed to get API group resources: unable to retrieve the complete list of server APIs: apps/: converting (v1.APIGroup) to (v1.APIResourceList): unknown conversion```

### Steps to Reproduce the Problem

All below steps are done in one single K8S namespace
1. Install KEDA
```
- helm repo add kedacore https://kedacore.github.io/charts
- helm install -f keda.values.yaml keda kedacore/keda -n graph
```
2. Deploy the 'graphqueryfrontdoor' application
3. Create ScaledObject object
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: graphfd-scaler
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
    autoscaling.keda.sh/paused-replicas: "0"
  namespace: graph
spec:
  scaleTargetRef:
    name: graphqueryfrontdoor
    kind: Deployment
    apiVersion: apps/v1
  pollingInterval: 10
  idleReplicaCount: 0
  cooldownPeriod: 20
  minReplicaCount: 1
  maxReplicaCount: 3
  fallback:
    failureThreshold: 3
    replicas: 1
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: azure-blob
    name: graphqueryfrontdoor-trigger
    metadata:
      blobContainerName: keda
      accountName: mystorageaccount
      blobCount: "1"
      blobPrefix: ""
      cloud: Private
      endpointSuffix: blob.core.windows.net
      connectionFromEnv: SCALEDOBJECT_CONN_STRING
```

### Logs from KEDA operator

```
2023-07-17T19:39:13Z	ERROR	target resource doesn't expose /scale subresource	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"graphqueryfrontdoor-scaler","namespace":"graph"}, "namespace": "graph", "name": "graphqueryfrontdoor-scaler", "reconcileID": "4b77223d-1614-49bd-a37b-2155ab8f9e58", "resource": "apps/v1.Deployment", "name": "graphqueryfrontdoor", "error": "unable to get client for deployments.apps: unable to get full preferred group-version-resource for deployments.apps: failed to get API group resources: unable to retrieve the complete list of server APIs: apps/: converting (v1.APIGroup) to (v1.APIResourceList): unknown conversion"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).checkTargetResourceIsScalable
	/workspace/controllers/keda/scaledobject_controller.go:334
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:238
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:177
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:314
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226
```

### KEDA Version

2.11.1

### Kubernetes Version

1.26

### Platform

Microsoft Azure

### Scaler Details

azure-blob
