### ISSUE TITLE
why keda doesn't scale up extra pods after trigger for a long time.

### ISSUE THREAD

**Issue by hexiong0802** [kedacore/keda#4811]
### Report

Here is my ScaledObject yaml config:

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: maicedata
  name: scaled-auth
spec:
  scaleTargetRef:
    name:  auth         # Mandatory. Must be in the same namespace as the ScaledObject
  pollingInterval:  5                            # Optional. Default: 30 seconds
  cooldownPeriod:   360                              # Optional. Default: 300 seconds
  idleReplicaCount: 0                                # Optional. Default: ignored, must be less than minReplicaCount 
  minReplicaCount:  1                                # Optional. Default: 0
  maxReplicaCount:  10                              # Optional. Default: 100
  fallback:                                          # Optional. Section to specify fallback options
    failureThreshold: 3                              # Mandatory if fallback section is included
    replicas: 2                                      # Mandatory if fallback section is included
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: false        # Optional. Default: false
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
        # 减少扩容抖动
        scaleUp:
          stabilizationWindowSeconds: 15
  triggers:
    - type: prometheus
      metricType: Value
      metadata:
        serverAddress: https://xx.xxx.xxx
        namespace: xxxxx
        metricName: auth-prom-metric
        activationThreshold: "-1"
        threshold: '0.8'
        # worker使用率
        query: sum(gunicorn_busy_workers{env="prod", exported_instance="k8s", role="auth"})/sum(gunicorn_total_workers{env="prod", exported_instance="k8s", role="auth"})
        authModes: "basic"
      authenticationRef:
        name: keda-prom-creds
```
![image](https://github.com/kedacore/keda/assets/90944636/3783cfbd-43e2-4a36-acfb-0569b5d8a7b6)

> The upper graph represents the gunicorn worker utilization.  
> The bottom graph represents the current pod's number 

When the query metric value is greater than threshold, It scales up one pod, but the query metric value lasts for a long time that is greater than threshold, keda doesn't scale up extra pods. Why???? I hope that keda continues to scale up extra pods when the query metric value is greater than threshold for 10s or a customized time 

### Expected Behavior

 I hope that keda continues to scale up extra pods when the query metric value is greater than threshold for 10s or a customized time 

### Actual Behavior

keda doesn't continue to scale up pods.

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

None

### Kubernetes Version

None

### Platform

None

**Comment by JorTurFer** [comment]
Hello
What KEDA version are you using? 
Could you share KEDA operator logs?

**Comment by hexiong0802** [comment]
> 

keda:2.9.1 
operator has no special logs.

**Comment by hexiong0802** [comment]
> Hello What KEDA version are you using? Could you share KEDA operator logs?

keda:2.9.1
operator has no special logs.

**Comment by JorTurFer** [comment]
something in KEDA metrics server logs?
Are you scrapping prometheus metrics exposed by KEDA? Could you shared the chart for `keda_scaler_metrics_value` during the same period?

**Comment by hexiong0802** [comment]
> 

the chart is 
![image](https://github.com/kedacore/keda/assets/90944636/304ab6f4-eb6f-48e7-99cd-e4873207e822)


I scrap the metric that is exposed by my Prometheus on-premises. The yellow line is the threshold. 

```yaml
  triggers:
    - type: prometheus
      metricType: Value
      metadata:
        serverAddress: https://xx.xxx.xxx
```
I specific the URL in the triggers config zone.
