### ISSUE TITLE
Deployment Update Scaler to better support scale from 0 to 1

### ISSUE THREAD

**Issue by kangteng525** [kedacore/keda#4883]
### Proposal

**Problem Statement**
Normally there are a large number of unused testing applications occupying capacity. We need a way to scale these applications down to zero when not in use, while still allowing users to easily scale them back up on demand.

The existing Prometheus scaler can scale the pools down to zero, but runs into issues scaling back up from zero since the CPU metric will always be zero when there are no replicas.

One potential solution is to use TPS as a trigger to scale up from 0 to 1. However, this is too reactive - TPS would come after testing starts, when we want the 1st replica already available.

We need a more proactive solution to scale the unused pools up from 0 to 1 before testing begins.

**Proposal**
The proposal is to introduce a new scaler in KEDA, aimed at scaling deployments based on the updates in the deployments. 

The scaler will be active when there's a recent update to the deployment, and be inactive if there has been no update in the last N days. Meanwhile it should not impact normal scale up / down based on other metrics.

### Scaler Source

Deployment

### Scaling Mechanics

**Activation phase** 

When the IsActive method is called, check the lastTransitionTime of the latest conditions of target
If the lastTransitionTime is within the recentUpdateThreshold days, return true; otherwise, return false.

**Scaling phase** 

When GetMetrics is called, always return 1.
The GetMetricSpecForScaling method will return a MetricSpec that is used as HPA spec for the specified deployment. To avoid blocking normal scale up, the threshold in this MetricSpec should be 0.5. 

### Authentication Source

N/A

**Comment by JorTurFer** [comment]
Hi
I'm not getting the use case totally. You'd like to have an scaler that enables your workload for X time after the last update, but just to scale it from 0 to 1, not from 1 to N. 
Something like an activator for X time after the last update, but setting always 1 instance, right?

**Comment by kangteng525** [comment]
Hi Jorge,

Yes, this scaler will only be responsible for Activation phase, scale from 0 to 1 if any updates introduced to the target deployment.

And Scaling from 1 to N will be handled by other scalers such as prometheus, while this scaler should not block other scalers to scale during Scaling phase.

Possible spec after introducing this scaler:

```
cooldownPeriod: 2592000 // 30 days
triggers:
- authenticationRef:
    kind: ClusterTriggerAuthentication
    name: keda-prom-creds
  metadata:
    authModes: basic
    metricName: CPU
    query: XXXXXX
    serverAddress: XXXXX
    threshold: "25.0"
    activationThreshold: "1.0"
  metricType: Value
  type: prometheus
- metadata:
    recentUpdateThreshold: "1"
  metricType: Value
  type: activeTarget
```
