### ISSUE TITLE
Support totaling length of multiple redis lists/regex for Redis List scaler

### ISSUE THREAD

**Issue by madyarini** [kedacore/keda#4907]
### Proposal

Hi, I'm trying to scale sidekiq using KEDA
I have different queues handled by a type of sidekiq worker pod
```
queue:work1
queue:work2
```
how do i able to say, if the list of jobs in both queues averaging 20, trigger the scaledobject ?
if i do this
```
triggers:
- listName: queue:work1
   listLength: 10
- listName: queue:work2
   listLength: 10
```
this means if either average is 10, trigger the scaled object right? its not an aggregation of the average of both queues
it would be great if the scaler supports regex to allow this use case

### Use-Case

Scale Sidekiq pro workers using KEDA that's managing different queues

### Is this a feature you are interested in implementing yourself?

No
