### ISSUE TITLE
New Caching mechanism 

### ISSUE THREAD

**Issue by yuvalweber** [kedacore/keda#4919]
### Proposal

I have an Idea but I want to hear your opinion regarding it.
Right now we have the ability to cache metric values till the polling interval by caching them on the keda operator.
We can specify the field **usecachedMetrics**
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cache-scale-example
  namespace: default
spec:
  scaleTargetRef:
    kind: StatefulSet
    name: cache-workload
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 60
  triggers:
    - type: prometheus
      metadata:
        serverAddress: https://prometheus:9090
        query: sum(http_request_total)
        threshold: "1000"
        ignoreNullValues: "false"
      useCachedMetrics: true
```

This is good in normal and small clusters , but in large clusters where you could have multiple metric-server pods activated in load balancing mode (`--enable-aggregator-routing=true`) then it can make a massive impact on the operator (which needs to respond to many requests heading from different metric servers).

I was wondering if maybe we can give users the ability to use some kind of external cache - They can point to redis they maybe have on the cloud or memcached they have deployed on some kind of pod and by that reducing the amount of requests that the operator gets to retrieve value from cache.

### Use-Case

I think this Idea could help us to motivate more users in production to use this because we bring them more stable mechanism and other resources that they can trust on

### Is this a feature you are interested in implementing yourself?

Maybe
