### ISSUE TITLE
Find CRD with wrong apiVersion "apps/v1"

### ISSUE THREAD

**Issue by dazuimao1990** [kedacore/keda#4924]
### Report

When I create ScaledObject for a CRD GameServerSet which belong to apiVersion "game.kruise.io/v1alpha1" with command `kubectl apply -f demo.yaml`, I get wrong message : 
```
Error from server (no matches for kind "GameServerSet" in version "apps/v1"): error when creating "2048.yaml": admission webhook "vscaledobject.kb.io" denied the request: no matches for kind "GameServerSet" in version "apps/v1"
```
But I have already define `spec.scaleTargetRef.apiVersion: game.kruise.io/v1alpha1`.  The yaml is here:
```yaml
apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
metadata:
  name: gss-2048
  namespace: game-demo
spec:
  replicas: 2
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
  gameServerTemplate:
    spec:
      containers:
        - image:  cr-xxx/2048:v1.0
          name: app-2048
          volumeMounts:
            - name: shared-dir
              mountPath: /var/www/html/js
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi
        - image: cr-xxx/2048-sidecar:v1.0
          name: sidecar
          args:
            - bash
            - -c
            - rsync -aP /app/js/* /app/scripts/ && while true; do echo 11;sleep 2; done
          volumeMounts:
            - name: shared-dir
              mountPath: /app/scripts
      volumes:
        - name: shared-dir
          emptyDir: {}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: gss-2048
  namespace: game-demo
spec:
  scaleTargetRef:
    name: gss-2048
    apiVersion: game.kruise.io/v1alpha1
    kind: GameServerSet
  pollingInterval: 30
  minReplicaCount: 0
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 45
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
  triggers:
    - type: external
      metricType: AverageValue
      metadata:
        scalerAddress: kruise-game-external-scaler.kruise-game-system:6000
```

### Expected Behavior

Maybe KEDA should find crd in right apiVersion.

### Actual Behavior

KEDA find my crd in default apiVersion

### Steps to Reproduce the Problem

1. Install OKG https://openkruise.io/zh/kruisegame/introduction
2. Install KEDA (2.10.1/2.11)
3. Apply my yaml

### Logs from KEDA operator

```
2023-09-01T12:18:40Z	ERROR	scaledobject-validation-webhook	Failed to parse Group, Version, Kind, Resource from HPA	{"hpaName": "game-hpa", "apiVersion": "apps/v1", "kind": "GameServerSet", "error": "no matches for kind \"GameServerSet\" in version \"apps/v1\""}
github.com/kedacore/keda/v2/apis/keda/v1alpha1.verifyHpas
	/workspace/apis/keda/v1alpha1/scaledobject_webhook.go:131
github.com/kedacore/keda/v2/apis/keda/v1alpha1.validateWorkload
	/workspace/apis/keda/v1alpha1/scaledobject_webhook.go:99
github.com/kedacore/keda/v2/apis/keda/v1alpha1.(*ScaledObject).ValidateCreate
	/workspace/apis/keda/v1alpha1/scaledobject_webhook.go:59
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*validatingHandler).Handle
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator.go:71
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:169
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go:98
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1
	/workspace/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:60
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2109
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
	/workspace/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:146
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2109
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
	/workspace/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:108
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2109
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2487
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1991
```

### KEDA Version

2.10.1

### Kubernetes Version

1.24

### Platform

None
