### ISSUE TITLE
QueueName not correctly encoded in Solace PubSub+ Scaler

### ISSUE THREAD

**Issue by sueltschi-sbb** [kedacore/keda#4936]
### Report

The 'queueName' Value in https://keda.sh/docs/2.11/scalers/solace-pub-sub/ isn't URL decoded in https://github.com/kedacore/keda/blob/main/pkg/scalers/solace_scaler.go#L248

This leads to problems when a queue name contains a slash (e.g. messages/large) because it leads to an invalid path when calling the SEMP Rest API resulting in a "400 Bad Request" response.

A workaround for now is to manually URL-encode the queueName value

### Expected Behavior

The queueName should be correctly URL-encoded

### Actual Behavior

Queue names containing a slash lead to "400 Bad Request" responses from the SEMP endpoint

### Steps to Reproduce the Problem

1. create a queue containing a slash in the name (e.g. 'messages/large')
2. create a solace-event-queue trigger for this queue
3. observe that the trigger fails to execute with a "400 Bad Request" message

### KEDA Version

None

### Kubernetes Version

None

### Platform

Red Hat OpenShift

**Comment by JorTurFer** [comment]
Interesting. The scaler should encode the queue name automatically, but it looks like it's not doing it.
Are you willing to fix it? This is the code where the endpoint is calculated, we need to url encode the queue before generating the url: https://github.com/kedacore/keda/blob/main/pkg/scalers/solace_scaler.go#L248-L255

**Comment by sueltschi-sbb** [comment]
Thank you @dttung2905 for fixing this so fast!

**Comment by JorTurFer** [comment]
@sueltschi-sbb , we aim to cut a release at the end of the month. You can expect the fix there

**Comment by AndreKoepke** [comment]
@JorTurFer I think that problem was not resolved. I'm using v2.17.2 and it produces always "semp request http status code: 400 - 400 Bad Request".


**Edit**
My bad, the workound is not working. I tried to encode the name with helm.

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaler
spec:
  scaleTargetRef:
    name: deploymentName
    kind: 'deployment'
  minReplicaCount: 1
  triggers:
    - type: solace-event-queue
      metadata:
        solaceSempBaseURL: https://capaplanner-capaworkunit-dev-internal.messaging.solace.cloud:943
        messageVpn: TmsCapaplannerCapaworkunit
        ###
        ### This is the (not working) workaround
        ### 
        queueName: '{{ urlquery "yourQueueName" }}'  
        ### 
        ### 
        ### 
        messageCountTarget: '50' 
      authenticationRef:
        name: auth
```
