### ISSUE TITLE
MongoDB Scaler: Inconsistent Behavior with Connection Parameters

### ISSUE THREAD

**Issue by mukeshpanch14** [kedacore/keda#4963]
When using the MongoDB scaler, there seems to be inconsistent behavior related to connection parameters. Depending on whether I provide a connection string or specify the host, username, and password individually, I encounter different issues.

**Expected Behavior:**
The MongoDB scaler should consistently handle connection parameters whether a connection string or individual host, username, and password parameters are provided. It should not prompt for unnecessary information and should gracefully handle cases where a password is provided.

**Steps to Reproduce:**

1. **Scenario 1: Using Connection String**

    a. Attempt to configure the MongoDB scaler with only a connection string as a parameter.
    b. Observe whether it prompts for host and password, even when a connection string is provided.

2. **Scenario 2: Using Host, Username, and Password**

    a. Attempt to configure the MongoDB scaler with host, username, and password parameters. 
    b. Observe whether it correctly accepts the provided password or raises an error stating that no password was provided.

**Current Behavior:**

1. When using a connection string as a parameter, the scaler metadata and error log as following:
```
metadata:
      connectionString: mongodb://dbwriter:dbwriter@mongo:27017
      dbName: test
      collection: panch
      query: "{}"
      queryValue: "1"
      desiredReplicas: "2"
```
error: 
![image](https://github.com/kedacore/keda/assets/20277114/152d488d-33fe-4355-8599-6deea3e7cffe)

2. When specifying the host, username, and password parameters, the scaler [describe the specific issue or behavior here].
```
 metadata:
      host: mongo
      port: "27017"
      username: <username>
      password: <password>
      dbName: test
      collection: panch
      query: "{}"
      queryValue: "1"
      desiredReplicas: "2"
```
error: 
![image](https://github.com/kedacore/keda/assets/20277114/75e831cc-9997-4f74-9815-dc05ad11c01a)

**Comment by JorTurFer** [comment]
Hello,
I think that the issues are related with a misconfiguration. We don't accept secrets as part of metadata section because it's not a sensitive API, so depending on what values you set, KEDA tries to parse the non-sensitive info from the metadata and shows different messages based on the missing fields for each case (which it's totally normal because KEDA assumes that if you have set the host, you will use username and password instead of connectionString).

In the scaler docs, there are come values with the suffix `FromEnv` within metadata section. You can use them to specify the environment variable **from the scaled workload** where the value is stored. This allows you to not having to use TriggerAuthentication because if you already have the values in the workload, KEDA can read them from there. For example, imagine that your scaled workload has the connection string in an environment variable called `MONGODB_CONNSTRING`, you can define your trigger as:
```yaml
metadata:
  connectionStringFromEnv: MONGODB_CONNSTRING
  dbName: test
  collection: panch
  query: "{}"
  queryValue: "1"
```
You can do the same using the approach of host+port+username+password. In this case if your workload has an env `MONGODB_PASSWORD`:
```yaml
 metadata:
  host: mongo
  port: "27017"
  username: myUser
  passwordFromEnv: MONGODB_PASSWORD
  dbName: test
  collection: panch
  query: "{}"
  queryValue: "1"
```

The other option, is setting a TriggerAuthentication for passing those values from a sensitive source (such as secrets, external vaults, etc). You can see an example [in the scaler docs](https://keda.sh/docs/2.11/scalers/mongodb/#example). This example uses a TriggerAuthentication to read the connection string from a secret.

In no case you can place the secrets directly in the triggers[].metadata section, because ScaledObject/ScaledJob aren't sensitive APIs, so we don't allow to store sensitive data there (and that's we don't read sensitive data from there).

As this is a misconfiguration rather than a KEDA issue, I close this issue as **not planned**, but feel free to give all the extra information that you think it's required if you still think that it's something related with KEDA.
