### ISSUE TITLE
Deployment scaled to 0 due to inactivity even when minReplicaCount >= 1

### ISSUE THREAD

**Issue by dagvl** [kedacore/keda#4995]
### Report

The docs at https://keda.sh/docs/2.11/concepts/scaling-deployments/#managing-activation--scaling-thresholds say:
> ⚠️ NOTE: If the minimum replicas is >= 1, the scaler is always active and the activation value will be ignored.

However, with keda 2.11.2 we see that this is not always true. If a ScaledObject has:
```yaml
idleReplicaCount: 0
minReplicaCount: 2
``` 
and use the `cron` trigger, the Deployment ends up scaled to 0 when the `cron` trigger is inactive which is unexpected based on the docs. 

### Expected Behavior

Given that `minReplicaCount: 2`, I expect the activation value to be ignored as per docs

### Actual Behavior

It scales the deployment to 0 when the cron trigger is inactive. 

### Steps to Reproduce the Problem

Example with keda 2.11.2.

Install keda with: `helm upgrade --install keda kedacore/keda --namespace keda --version 2.11.2 --create-namespace`

Create nginx deployment and scaledobject:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx
spec:
  scaleTargetRef:
    name: nginx-deployment
  idleReplicaCount: 0
  maxReplicaCount: 5
  minReplicaCount: 2
  pollingInterval: 30
  cooldownPeriod: 0
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 0
  triggers:
  - type: cron
    metadata:
      timezone: "America/Los_Angeles"
      start: "0,10,20,30,40,50 * * * *"
      end: "5,15,25,35,45,55 * * * *"
      desiredReplicas: "3"
```

### Logs from KEDA operator

```
keda-operator-5bb4454c97-vswjr keda-operator 2023-09-24T18:45:24Z	DEBUG	scale_handler	Getting metrics and activity from scaler	{"scaledObject.Namespace": "default", "scaledObject.Name": "nginx", "scaler": "cronScaler", "metricName": "s1-cron-America-Los_Angeles-0,10,20,30,40,50xxxx-5,15,25,35,45,55xxxx", "metrics": [{"metricName":"s1-cron-America-Los_Angeles-0,10,20,30,40,50xxxx-5,15,25,35,45,55xxxx","metricLabels":null,"timestamp":"2023-09-24T18:45:24Z","value":"1"}], "activity": false, "scalerError": null}
keda-operator-5bb4454c97-vswjr keda-operator 2023-09-24T18:45:24Z	INFO	scaleexecutor	Successfully set ScaleTarget replicas count to ScaledObject idleReplicaCount	{"scaledobject.Name": "nginx", "scaledObject.Namespace": "default", "scaleTarget.Name": "nginx-deployment", "Original Replicas Count": 1, "New Replicas Count": 0}
keda-operator-5bb4454c97-vswjr keda-operator 2023-09-24T18:45:24Z	DEBUG	events	Deactivated apps/v1.Deployment default/nginx-deployment from 1 to 0	{"type": "Normal", "object": {"kind":"ScaledObject","namespace":"default","name":"nginx","uid":"fd7102ce-acf8-4bd4-a1be-5a706f770ade","apiVersion":"keda.sh/v1alpha1","resourceVersion":"208928"}, "reason": "KEDAScaleTargetDeactivated"}

### KEDA Version

2.11.2

### Kubernetes Version

1.25

### Platform

Other

### Scaler Details

cron

### Anything else?

_No response_
