### ISSUE TITLE
Azure Pipeline scaler unsafeSsl support

### ISSUE THREAD

**Issue by mihaico** [kedacore/keda#5040]
### Proposal

In the case of an Azure DevOps (ADO) Server deployment with a self-signed certificate, the azure_pipeline_scaler fails to validate the ADO `poolID/poolName` with the classic:
```
tls: failed to verify certificate: x509: certificate signed by unknown authority
```
Adding support for the `unsafeSsl` flag in azure_pipeline_scaler would at least enable usage with Azure DevOps Server with a self signed certificate.

In the future adding support for importing CA certificates would be helpful.

### Use-Case

Support azure_pipeline_scaler in the case of Azure DevOps Server deployment with self-signed certificate.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by zroubalik** [comment]
The `unsafeSsl` option should be used only for testing purposes.

If you have your own signed cert, than you can import that in KEDA: https://keda.sh/docs/2.12/operate/security/#register-your-own-ca-in-keda-operator-trusted-store

**Comment by JorTurFer** [comment]
I think that importing the CA is the way to go

**Comment by mihaico** [comment]
Thanks for the hint. This also works for me, for a really fast setup ended up adapting the [manifest ](https://github.com/kedacore/keda/releases/download/v2.12.0/keda-2.12.0.yaml) following the similar helm values (helm charts are more difficult to import in in my org):

```
kubectl edit deployment keda-operator -n keda
spec:
  ...
  template:
    ...  
    spec:
      containers:
      - name: keda-operator
        ...
        volumeMounts:
        ...
        - mountPath: /custom/ca/root.ca
          name: custom
          readOnly: true
          subPath: root.ca
      volumes:
      ...
      - name: custom
        secret:
          items:
          - key: ca.crt
            path: root.ca
          secretName: root-ca
```

Closing.
