### ISSUE TITLE
Issue with GCP PubSub scaledObject

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#5093]
### Discussed in https://github.com/kedacore/keda/discussions/4751

<div type='discussions-op-text'>

<sup>Originally posted by **raghu-manne** June 29, 2023</sup>
I am trying to test out keda with GCP pubsub andd the getting below error. Any insights where am i doing wrong?
`2023-06-29T11:26:13Z    ERROR   Reconciler error        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"test","namespace":"default"}, "namespace": "default", "name": "test", "reconcileID": "5b54cc98-02bf-4dea-a270-125a70a957b5", "error": "HorizontalPodAutoscaler.autoscaling \"keda-hpa-test\" is invalid: spec.metrics[0].external.target.averageValue: Invalid value: resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:\"0\", Format:\"DecimalSI\"}: must be positive"}
`
My scaledobject looks like this

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pubsub-test
  namespace: default
spec:
  scaleTargetRef:
    name: consume-pubsub-messages #Target Workload Name
  triggers:
  - type: gcp-pubsub
    authenticationRef:
      name: test
    metadata:
      subscriptionName: "keda-test-subscription" # Required
````

Scaledobject events says this
```
Events:
  Type     Reason                   Age                    From           Message
  ----     ------                   ----                   ----           -------
  Warning  ScaledObjectCheckFailed  2m6s (x16 over 4m50s)  keda-operator  failed to ensure HPA is correctly created for ScaledObject
```</div>
