### ISSUE TITLE
Challenge: Efficent Scaling Down and Message Redistribution with Kafka Scaler

### ISSUE THREAD

**Issue by juanidufourc** [kedacore/keda#5096]
### Report

Hello,

I'm experiencing an issue with Keda that I'd like to discuss and understand better. I appreciate any guidance, solutions, or ideas to address it.

## Context

In our environment, we have workers consuming messages from a Kafka cluster. These workers run daily, but the message count in the Kafka cluster varies significantly from one day to the next (e.g., 5000 messages one day and 100,000 messages the next). To dynamically scale workers based on the Kafka message load, we've implemented Keda, and the scaling up works perfectly.

The issue arises with the scaling down. Once we reach the maximum number of workers, Keda starts to remove workers when the Kafka message count decreases. While this makes sense, the problem is that the removed workers were in the process of processing messages, necessitating a redistribution of messages among the remaining workers. This significantly slows down the process as the redistribution temporarily halts processing in Kafka. As the message count decreases, this situation repeats and becomes more problematic.
![image](https://github.com/kedacore/keda/assets/28546635/f136136d-d3b5-4535-ace2-39ace6c3cde6)

Here is the ScaledObject that we are using for this worker:
```
apiVersion: keda.sh/v1alpha1
 kind: ScaledObject
 metadata:
   labels:
     argocd.argoproj.io/instance: api-prod
     scaledobject.keda.sh/name: kafka-scaledobject
   name: kafka-scaledobject
   namespace: api
 spec:
   maxReplicaCount: 50
   minReplicaCount: 1
   pollingInterval: 30
   scaleTargetRef:
     name: <name>
   triggers:
   - metadata:
       bootstrapServers: <endpoints>
       consumerGroup: <name>
       lagThreshold: "250"
       offsetResetPolicy: latest
       topic: <topic_name>
     type: kafka
   - metadata:
       bootstrapServers: <endpoints>
       consumerGroup: <name>
       lagThreshold: "201"
       offsetResetPolicy: latest
       topic: <topic_name>
     type: kafka
```

## Investigation

We've noticed that the Kafka Scaler we are using (see [here](https://keda.sh/docs/2.12/scalers/apache-kafka/#trigger-specification)) is limited in addressing this issue.

### Potential Solutions

1. **Set a Custom Timeout**: One option we've considered is configuring a custom timeout for workers to prevent premature removal. However, due to the variability in message counts, this could lead to worker inactivity when the load is low.

2. **Creation of a Custom Keda Scaler**: Another solution we've explored is the possibility of creating a custom Keda Scaler. This could enable us to monitor messages in Kafka topics and scale down only when there are no pending messages to process. However, we're unsure about the complexity of this solution and if there's a simpler alternative.

## Questions

- Has anyone encountered a similar issue with Keda and has any experience or solutions to share?
- Is there an alternative solution we may not have considered?

We appreciate any guidance, suggestions, or recommendations for efficiently addressing this problem.

Thank you!

### Expected Behavior

We expect that when Keda scales down the number of workers due to a decrease in the message count in the Kafka cluster, it does so in a way that minimizes disruption. Specifically, we anticipate that Keda would:

1- Scale down workers when the workload decreases, but do so in a manner that allows existing workers to complete their current message processing tasks.

2- Avoid immediate termination of workers with in-progress tasks, ensuring that messages being processed are not abruptly halted.

3- Provide an efficient mechanism for redistributing messages from the scaled-down workers to the remaining ones to minimize processing interruptions.

### Actual Behavior

However, in the current configuration, the behavior we are observing is as follows:

1- When Keda scales down workers due to a reduced message count in Kafka, it immediately terminates workers that may still be processing messages.

2- This leads to an interruption in message processing and a subsequent redistribution of messages among the remaining workers.

3- The frequent interruptions and redistributions significantly slow down the overall processing pipeline, especially as the message count continues to decrease.

These observations highlight the need for a more efficient scaling down process in Keda to ensure minimal disruption when the workload decreases.

### Steps to Reproduce the Problem

If you can reproduce a similar setup of the described above I think you will be able to reproduce the problem.

### Logs from KEDA operator

I don't have any logs of Keda because the behavior is the expected one.

### KEDA Version

2.7.1

### Kubernetes Version

1.25

### Platform

Amazon Web Services

### Scaler Details

Kafka
