### ISSUE TITLE
Github Runner Scaler - Authorization Header Is Not Properly Constructed In Azure Kubernetes Service.

### ISSUE THREAD

**Issue by jordanrbaker** [kedacore/keda#5112]
### Report

Also posted in AKS -https://github.com/Azure/AKS/issues/3961

Note: any values in < > were just values I scrubbed from the post, they are populated in the actual deployment.  I triple checked.

I am using the Github Scaler introduced in 2.10 (https://keda.sh/docs/2.10/scalers/github-runner/), after setting up the scaler, trigger references and secrets, the scaler fails to connect to github.  Logs show this error, indicating the Authorization header is not being passed correctly:

` Get "https://api.github.com/repos/jordanrbaker/<repo>/actions/runs": net/http: invalid header field value for "Authorization" `

### Expected Behavior

The Authorization header should be constructed correctly to enable a functional call to the api.

### Actual Behavior

The scaledObject fails due to the API call to the Github API failing when the token is base64 encoded, as is required by the ` data ` object.

` Get "https://api.github.com/repos/jordanrbaker/<repo>/actions/runs": net/http: invalid header field value for "Authorization" `

### Steps to Reproduce the Problem

**To Reproduce**
1. Set up baseline AKS Cluster, one linux nodepool, one windows server 22 node pool.
2. Enable the KEDA scaler addon
3. Generate your github PAT and base64 encode it with the following powershell code:

``` 
$Text = "<your token>"
$Bytes = [System.Text.Encoding]::Unicode.GetBytes($Text)
$EncodedText =[Convert]::ToBase64String($Bytes)
$EncodedText
```

5. Set up the scaler as indicated in the instructed linked above.
6. Check the kubeevent logs to validate that the scaler is failing to connect.

### Logs from KEDA operator

` Get "https://api.github.com/repos/jordanrbaker/<repo>/actions/runs": net/http: invalid header field value for "Authorization" `

### KEDA Version

2.10.1

### Kubernetes Version

1.26

### Platform

Microsoft Azure

### Scaler Details

Github Runner Scaler

### Anything else?

- Changing ` data ` to ` stringData ` and passing the unencoded token results in success, the scaler works as expected.
- Leveraging Azure Container Apps, I set up the same thing (deployed the same image, deployed the same scaler - success).

Deployment YAML:

Runner Deployment YAML (Scrubbed):

``` 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghrunnerwin
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: runner    
  template:
    metadata:
      labels:
       environment: runner
    spec:
      containers:
      - name: winrunner22
        image: <acr>.azurecr.io/images/win22ephem:latest        
        ports:
        - containerPort: 443
        env:
        - name: GH_OWNER
          value: "<owner>"
        - name: GH_REPOSITORY
          value: "<repo>"
        - name: GH_TOKEN
          value: "<pat>"
```

KEDA Scaler YAML (Scrubbed):

```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-auth
data:
  personalAccessToken: <pat>
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: github-trigger-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: github-auth
      key: personalAccessToken
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: github-runner-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: ghrunnerwin
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: github-runner
    metadata:
      githubAPIURL: "https://api.github.com"
      owner: <owner>
      runnerScope: repo
      repos:<repo>
      labels: "Windows"
      targetWorkflowQueueLength: "1"
    authenticationRef:
     name: github-trigger-auth          
```
