### ISSUE TITLE
Add Eager mode for ScaledJobs

### ISSUE THREAD

**Issue by junekhan** [kedacore/keda#5114]
### Proposal

KEDA doesn't scale up job number to the max according to[ this piece of description and information around](https://keda.sh/docs/2.11/concepts/scaling-jobs/#:~:text=Number%20of%20the%20Scale%3A%20The%20number%20of%20the%20job%20that%20is%20created.). But in our case, we want to launch as many jobs as possible and keep the queue as empty. So, can we have an Eager mode in addition so users like me can shorten the waiting time in general?

### Use-Case

We want to launch as many jobs as possible and keep the queue as empty.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by SpiritZhou** [comment]
Which scaler do you use? I think set the para queueLength on queue scaler can shorten the time.

**Comment by junekhan** [comment]
```
  triggers:
    - type: rabbitmq
      metadata:
        queueName: queue
        hostFromEnv: RABBITMQ_URL
        mode: QueueLength
        value: "1"
---
```
@SpiritZhou Thanks for your reply. We configured the scaler as above.
Increasing the `queueLength` seems unacceptable to us since it keeps pods running as long as these pods haven't consumed as many messages as the number assigned to `queueLength`. It means that allocated resources for these pods won't be recycled, although we hope the cluster can scale down once there's no incoming message.

**Comment by zroubalik** [comment]
What is your ScaledJob config? What do you set as a maxReplicaCount?

**Comment by junekhan** [comment]
```yaml
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: worker
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: worker
      spec:
        containers:
          - name: worker
            image: worker-image
            imagePullPolicy: Always
            resources:
              requests:
                memory: "4Gi"
                cpu: "1"
            env:
              - name: WORKER_TYPE
                value: pilot
              - name: RB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: rabbitmq-instance-default-user
                    key: username
              - name: RB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: rabbitmq-instance-default-user
                    key: password
              - name: RABBITMQ_URL
                value: amqp://$(RB_USERNAME):$(RB_PASSWORD)@rabbitmq-instance.arc:5672
        restartPolicy: Never
    backoffLimit: 1
  pollingInterval: 10 # Optional. Default: 30 seconds
  maxReplicaCount: 10 # Optional. Default: 100
  successfulJobsHistoryLimit: 0 # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 5 # Optional. Default: 100. How many failed jobs should be kept.
  triggers:
    - type: rabbitmq
      metadata:
        queueName: woker_queue
        hostFromEnv: RABBITMQ_URL
        mode: QueueLength
        value: "1"
```

@zroubalik Basically like this.
