### ISSUE TITLE
Interface to easily install and manage external scalers

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#5117]
### Proposal

When users want to use [external triggers](https://keda.sh/docs/2.12/scalers/external/) in KEDA, they usually need to provide connection information in the trigger metadata:
```yaml
- type: external
  metadata:
    scalerAddress: external-scaler-service:8080
    caCert : /path/to/tls/ca.pem
    tlsCertFile: /path/to/tls/cert.pem # Deprecated. https://github.com/kedacore/keda/issues/4549
    tlsClientCert: /path/to/tls/cert.pem
    tlsClientKey: /path/to/tls/key.pem
    unsafeSsl: false

    // ACTUAL TRIGGER CONFIG STARTS HERE
    activationThreshold: 10
    threshold: 20
    fooConfig: true
    barConfig: false
    ...
```

Let's provide an interface (CRD?), where administrators can install external scalers to KEDA on a cluster level. This external trigger will define a name (that is unique and don't collide with built-in triggers), for example foo
Users can then just easily reference this external scaler as a built in one and provide only needed config (and don't need to specify external trigger connection settings). 
For example, let's see an example of external trigger `my-awesome-trigger`:
1. Let's define this CRD once (created in keda namespace)
```yaml
apiVersion: triggers.keda.sh/v1
kind: ExternalTriggerRegistration
metadata:
  name: my-awesome-trigger
spec:
 metadata:
    scalerAddress: external-scaler-service:8080
    caCert: /path/to/tls/ca.pem
    tlsCertFile: /path/to/tls/cert.pem  # Note: This field is deprecated. 
    tlsClientCert: /path/to/tls/cert.pem
    tlsClientKey: /path/to/tls/key.pem
    unsafeSsl: false
  authenticationRef:
   my-ta

```

2. users then can reference this trigger like this in their SO/SJ:
```yaml
- type: my-awesome-trigger
  metadata:
    activationThreshold: 10
    threshold: 20
    fooConfig: true
    barConfig: false
    ...
```

### Use-Case

Simplified management of external scalers

### Is this a feature you are interested in implementing yourself?

Maybe
