### ISSUE TITLE
Can't connect to rabbitmq

### ISSUE THREAD

**Issue by qnapnickchang** [kedacore/keda#5127]
### Report

Config:
```yaml
`apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: default
data:
  host: YW1xcDovL3FjbG91ZDoxcWF6MndzeEByYWJiaXRtcS1oZWFkbGVzcy5yYWJiaXRtcT

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-auth-conn
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-secret
      key: host

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
  name: test-pod
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: test-pod
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 2
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      name: test-pod
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: test
      mode: QueueLength
      value: "100"
    authenticationRef:
      name: rabbitmq-auth-conn`
```

### Expected Behavior

Connect to Rabbitmq and Authentication

### Actual Behavior

no host setting given

### Steps to Reproduce the Problem

1. set secret
2. set triggerauthentication
3. set scaledobject

### Logs from KEDA operator

```bash
{"level":"error","ts":"2023-10-26T02:23:52Z","logger":"scale_handler","msg":"error resolving auth params","type":"ScaledObject","namespace":"default","name":"test","scalerIndex":0,"error":"error parsing rabbitmq metadata: no host setting given","stacktrace":"github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers\n\t/workspace/pkg/scaling/scalers_builder.go:83\ngithub.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).performGetScalersCache\n\t/workspace/pkg/scaling/scale_handler.go:366\ngithub.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache\n\t/workspace/pkg/scaling/scale_handler.go:280\ngithub.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState\n\t/workspace/pkg/scaling/scale_handler.go:570\ngithub.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers\n\t/workspace/pkg/scaling/scale_handler.go:241\ngithub.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop\n\t/workspace/pkg/scaling/scale_handler.go:180"}
```

### KEDA Version

2.12.0

### Kubernetes Version

1.25

### Platform

Amazon Web Services

### Scaler Details

rabbitmq
