### ISSUE TITLE
delete "selectPolicy: Disabled" from ScaledObject behavior policies but the related HPA object isn't updated

### ISSUE THREAD

**Issue by AndyEWang** [kedacore/keda#5129]
### Report

To delete "selectPolicy: Disabled" from the existed ScaledObject behavior policies but the related HPA object still has "selectPolicy: Disabled".
```
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 2
      selectPolicy: Disabled
      stabilizationWindowSeconds: 100
    scaleUp:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 3
      selectPolicy: Disabled
      stabilizationWindowSeconds: 80
```

### Expected Behavior

To delete "selectPolicy: Disabled" from ScaledObject and the related HPA object should also be updated to delete "selectPolicy: Disabled". Finally, the related HPA object should have default selectPolicy.

### Actual Behavior

To delete "selectPolicy: Disabled" from ScaledObject but the related HPA object isn't updated.

### Steps to Reproduce the Problem

1. create a ScaledObject without "selectPolicy" and wait for its HPA object to generate
2. update this ScaledObject with "selectPolicy: Disabled"
3. wait for the related HPA object to update with "selectPolicy: Disabled"
4. delete "selectPolicy: Disabled" from this ScaledObject 
5. the related HPA object still has "selectPolicy: Disabled" and never update with default selectPolicy.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.8.2

### Kubernetes Version

< 1.23

### Platform

Other

**Comment by tomkerkhove** [comment]
It looks like you are running 2.8.2, any chance you can try again on KEDA 2.11 or 2.12?

**Comment by AndyEWang** [comment]
@tomkerkhove can keda 2.12 work on k8s 1.22?

**Comment by MuhtasimTanmoy** [comment]
While reproducing this issue with keda 2.12 and k8s 1.21 with kind and following [this](https://github.com/kedacore/keda/blob/main/BUILD.md), I am stuck after this command `make deploy` with this error. 

```
Unable to attach or mount volumes: unmounted volumes=[certificates], unattached volumes=[kube-api-access-cf2tr certificates]: timed out waiting for the condition
```

Any insight?

**Comment by AndyEWang** [comment]
It seems that KEDA 2.12 requires 'kubeVersion >=v1.23.0-0'. 
From helm chart,
```
appVersion: 2.12.0
kubeVersion: '>=v1.23.0-0'
```

**Comment by Tunguska55** [comment]
I'm noticing this also happens with behavior as a whole. 

Example scaledObject spec:
```
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior: {}
  fallback:
    failureThreshold: 3
    replicas: 1
  maxReplicaCount: 10
  minReplicaCount: 1
  pollingInterval: 30
```

This resulting HPA still has behavior set with a previous config:
```
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Pods
          value: 4
          periodSeconds: 15
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
```
