### ISSUE TITLE
GitHub Runner Scaler scale only one pod

### ISSUE THREAD

**Issue by arunalakmal** [kedacore/keda#5163]
### Report

I'm trying to integrate the GitHub Runner scaler with our self-hosted runner running on Kubernetes (Not ARC). It's a custom implementation but scaling capability is there. Runner identified as a CRD. I have setup Keda and created the below scaler. It works fine with a one job even though there are many jobs are in the pending state (I checked with a single workflow in a one repo). 

I set the `targetWorkflowQueueLength: "1"` and as per my understanding if there is a one job pending runner should be scaled and new runner should be able to start the job. It always works with the first job but not for any pending jobs after that. 

Here is the configuration in my `ScaledObject`.

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaled-tc-runnner
  namespace: runners
spec:
  scaleTargetRef:
    apiVersion: operators.xxxx.com/v1alpha1
    kind: GitHubRunners 
    name:  github-runners
  pollingInterval:  30 
  cooldownPeriod:   300 
  idleReplicaCount: 0  
  minReplicaCount:  1   
  maxReplicaCount:  100  
  fallback:       
    failureThreshold: 3   
    replicas: 6          
  advanced:        
    restoreToOriginalReplicaCount: true
  triggers:
  - type: github-runner
    metadata:
      githubAPIURL: "https://api.github.com"
      owner: "arunalakmal"
      runnerScope: "repo"
      repos: "reponame"
      labels: "my-runner"
      targetWorkflowQueueLength: "1" 
      applicationID: "xxxxxx"
      installationID: "xxxxx"      
    authenticationRef:
      name: github-trigger-auth
```

I don't see any errors in the Keda operator or the HPA other than the scaled message. 

the entry in the Keda Operator
```
2023-11-07T11:08:42Z	INFO	scaleexecutor	Successfully updated ScaleTarget	{"scaledobject.Name": "scaled-runnner", "scaledObject.Namespace": "runners", "scaleTarget.Name": "github-runners", "Original Replicas Count": 0, "New Replicas Count": 1}
```

### Expected Behavior

Scale up the runner and new pod pick up the new job. I tested it with a single repo and one workflow with more than 10 pending jobs in the Actions workflow.

### Actual Behavior

it works only with one and the first pod from 0 to 1

### Steps to Reproduce the Problem

1. I installed Keda with helm
2. Not sure how runner can be deployed to produce the bug as it's a custom implementation. But it supported the scaling and scale subresource is there. `kubectl scale githubrunners --replicas=10` works really well. 

### Logs from KEDA operator

```
2023-11-07T11:08:42Z	INFO	scaleexecutor	Successfully updated ScaleTarget	{"scaledobject.Name": "scaled-runnner", "scaledObject.Namespace": "runners", "scaleTarget.Name": "github-runners", "Original Replicas Count": 0, "New Replicas Count": 1}
```

### KEDA Version

2.12.0

### Kubernetes Version

1.26

### Platform

Microsoft Azure

### Scaler Details

GitHub Runner Scaler
