### ISSUE TITLE
Bubble Up vault errors to ScaledObject Events

### ISSUE THREAD

**Issue by BojanZelic** [kedacore/keda#5190]
### Proposal

Any errors in vault TriggerAuth configurations such as permissions or connectivity problems make it confusing to debug. Since the vault configuration lies within each ScaledObject, it could bubble up more descriptive errors when it's misconfigured instead of having to parse keda logs to find the root cause.

### Use-Case

For example; when defining a ScaledObject and a TriggerAuth with an incorrect params;
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
spec:
...
  - authenticationRef:
      kind: TriggerAuthentication
      name: my-trigger-auth
    metadata:
...
    type: kafka
```
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
...
spec:
  hashiCorpVault:
    address: my-vault-server
    authentication: kubernetes
    credential:
      serviceAccount: /var/run/secrets/kubernetes.io/serviceaccount/token
    mount: cluster
    role: keda-triggerauth
    secrets:
    - key: MY_PASSWORD_KEY
      parameter: password
      path: secret_v2/data/my-secret-path
    - key: MY_USERNAME_KEY
      parameter: username
      path: secret_v2/data/my-secret-path

```

& lets say that our user can't auth to vault because of some permission issues and we get the following:

```
2023-11-16T21:28:40Z    ERROR   scale_handler   error authenticate to Vault     {"type": "ScaledObject", "namespace": "my-namespace", "name": "my-scaled-object", "triggerAuthRef.Name": "my-trigger-auth", "error": "Error making API request.\n\nURL: PUT https://my-vault-server/v1/auth/cluster/login\nCode: 403. Errors:\n\n* permission denied"}
2023-11-16T21:28:40Z    ERROR   Reconciler error        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"my-scaled-object","namespace":"my-namespace"}, "namespace": "my-namespace", "name": "my-scaled-object", "reconcileID": "2e5660bd-9d71-46ee-9b93-23141af2f92d", "error": "error parsing kafka metadata: no username given"}
```

this gives us the following Events on the ScaledObject
```
Warning  KEDAScalerFailed         38s (x17 over 6m6s)    keda-operator  error parsing kafka metadata: no username given
```

it's a confusing error message to debug; it would be easier if it exposed the direct error from vault:
ex:
```
Warning  KEDAScalerFailed         38s (x17 over 6m6s)    keda-operator  Error making API request.\n\nURL: PUT https://my-vault-server/v1/auth/cluster/login\nCode: 403. Errors:\n\n* permission denied
```

### Is this a feature you are interested in implementing yourself?

Yes
