### ISSUE TITLE
KEDA operator fails silently on invalid AWS credentials

### ISSUE THREAD

**Issue by nielstenboom** [kedacore/keda#5199]
### Report

When you deploy a KEDA operator in an AWS EKS cluster with faulty credentials then the pod fails silently instead of going into CrashLoop

### Expected Behavior

I would expect the pod to crash with a non-zero exit code since it does not have any valid credentials to properly function

### Actual Behavior

The operator silently fails in its sync loop spawning error logs.

### Steps to Reproduce the Problem

1. Deploy KEDA in a AWS EKS cluster
2. Set authentication mechanism through an eks annotation on the serviceAccount and provide a non-existent account ID:

```yaml
  serviceAccount:
    create: true
    name: keda-operator
    automountServiceAccountToken: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::{NON EXISTENT ACCOUNT ID HERE}:role/keda-operator-role
```
3. Now you'll see the KEDA operator fail silently

### Logs from KEDA operator

```
2023-11-21T16:19:08Z	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "redacted", "scaledObject.Namespace": "redacted", "scaleTarget.Name": "redacted", "error": "WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.eu-west-1.amazonaws.com/id/1234567\n\tstatus code: 400, request id: 1234567"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149
```

### KEDA Version

2.8.1

### Kubernetes Version

1.23

### Platform

Amazon Web Services

### Scaler Details

AWS SQS
