### ISSUE TITLE
 KEDA authenticating with Azure returned 401 response

### ISSUE THREAD

**Issue by galiacheng** [kedacore/keda#5203]
### Report

I followed [Integrate KEDA with your Azure Kubernetes Service cluster](https://learn.microsoft.com/en-us/azure/azure-monitor/containers/integrate-keda) to create scalers. But got error like the following ouput:

```
2023-11-24T07:56:16Z    ERROR   scale_handler   error getting metric for scaler {"scaledObject.Namespace": "sample-domain1-ns", "scaledObject.Name": "azure-managed-prometheus-scaler", "scaler": "prometheusScaler", "error": "prometheus query api returned error. status: 401 response: {\"status\":\"error\",\"errorType\":\"Unauthorized\",\"error\":\"Request does not contain an Authorization Header. RequestId: cdf5aeed646f4bd3bac28d27f740af2b\"}"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
        /workspace/pkg/scaling/scale_handler.go:522
github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
        /workspace/pkg/metricsservice/server.go:47
github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
        /workspace/pkg/metricsservice/api/metrics_grpc.pb.go:99
google.golang.org/grpc.(*Server).processUnaryRPC
        /workspace/vendor/google.golang.org/grpc/server.go:1376
google.golang.org/grpc.(*Server).handleStream
        /workspace/vendor/google.golang.org/grpc/server.go:1753
google.golang.org/grpc.(*Server).serveStreams.func1.1
        /workspace/vendor/google.golang.org/grpc/server.go:998
```

The KEDA operator is running:

```shell
$ kubectl get pod -n keda
NAME                                             READY   STATUS    RESTARTS   AGE
keda-admission-webhooks-7fcc448785-mhb5v         1/1     Running   0          44m
keda-operator-7f4cd6667f-dlnwd                   1/1     Running   0          44m
keda-operator-metrics-apiserver-c8649d49-w86zw   1/1     Running   0          44m
```

YAML file to create scaler:

```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-managed-prometheus-trigger-auth
  namespace: sample-domain1-ns
spec:
  podIdentity:
      provider: azure-workload
      identityId: 6b882164-64ee-43dc-93bd-xxxxxxxxxxx
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-managed-prometheus-scaler
  namespace: sample-domain1-ns
spec:
  scaleTargetRef:
    apiVersion: weblogic.oracle/v1
    kind: Cluster
    name: sample-domain1-cluster-1
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: prometheus
    metadata:
      serverAddress: https://wls-prometheus-m2nz.eastus.prometheus.monitor.azure.com
      metricName: webapp_config_open_sessions_high_count
      query: sum(webapp_config_open_sessions_high_count{app="testwebapp"}[1m]) # Note: query must return a vector/scalar single element response
      threshold: '2'
      activationThreshold: '1'
    authenticationRef:
      name: azure-managed-prometheus-trigger-auth
```

### Expected Behavior

The scaler should work correctly.

### Actual Behavior

401 error: "Request does not contain an Authorization Header".

### Steps to Reproduce the Problem

See https://learn.microsoft.com/en-us/azure/azure-monitor/containers/integrate-keda

### Logs from KEDA operator

```
example
```

### KEDA Version

2.12.0

### Kubernetes Version

1.26

### Platform

Microsoft Azure

### Scaler Details

Prometheus
