### ISSUE TITLE
Azure Service Bus scaler cannot get queue length

### ISSUE THREAD

**Issue by tr1et** [kedacore/keda#5227]
### Report

Using KEDA in Azure AKS with Azure Service Bus, on an existing queue with active messages, Azure Service Bus scaler cannot get queue length and fallback to `fallback.replicas`.
Some other scalers like Cron, CPU, Memory worked properly.

### Expected Behavior

Azure Service Bus scaler should be able to get queue length and scale pods base on it.

### Actual Behavior

Azure Service Bus scaler couldn't get queue length and throw error `invalid queue runtime properties: no CountDetails element`.

### Steps to Reproduce the Problem

1. Create Azure Service Bus namespace, queue and add message into queue
2. Install KEDA with Helms
3. Create ScaledObject with Azure Service Bus scaler.
4. ScaledObject has error event `invalid queue runtime properties: no CountDetails element`. KEDA operator has error and fallback to default replicas.

### Logs from KEDA operator

```
2023-11-29T10:42:58Z	ERROR	azure_servicebus_scaler	error getting service bus entity length	{"type": "ScaledObject", "namespace": "dev", "name": "xxx-service", "error": "invalid queue runtime properties: no CountDetails element"}
github.com/kedacore/keda/v2/pkg/scalers.(*azureServiceBusScaler).GetMetricsAndActivity
	/workspace/pkg/scalers/azure_servicebus_scaler.go:262
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
	/workspace/pkg/scaling/cache/scalers_cache.go:139
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
	/workspace/pkg/scaling/scale_handler.go:508
github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
	/workspace/pkg/metricsservice/server.go:47
github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
	/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:99
google.golang.org/grpc.(*Server).processUnaryRPC
	/workspace/vendor/google.golang.org/grpc/server.go:1343
google.golang.org/grpc.(*Server).handleStream
	/workspace/vendor/google.golang.org/grpc/server.go:1737
google.golang.org/grpc.(*Server).serveStreams.func1.1
	/workspace/vendor/google.golang.org/grpc/server.go:986
2023-11-29T10:42:58Z	INFO	fallback	Suppressing error, falling back to fallback.replicas	{"scaledObject.Namespace": "dev", "scaledObject.Name": "xxx-service", "suppressedError": "invalid queue runtime properties: no CountDetails element", "fallback.replicas": 2}
2023-11-29T10:42:58Z	ERROR	azure_servicebus_scaler	error getting service bus entity length	{"type": "ScaledObject", "namespace": "dev", "name": "xxx-service", "error": "invalid queue runtime properties: no CountDetails element"}
github.com/kedacore/keda/v2/pkg/scalers.(*azureServiceBusScaler).GetMetricsAndActivity
	/workspace/pkg/scalers/azure_servicebus_scaler.go:262
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
	/workspace/pkg/scaling/cache/scalers_cache.go:129
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
	/workspace/pkg/scaling/scale_handler.go:508
github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
	/workspace/pkg/metricsservice/server.go:47
github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
	/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:99
google.golang.org/grpc.(*Server).processUnaryRPC
	/workspace/vendor/google.golang.org/grpc/server.go:1343
google.golang.org/grpc.(*Server).handleStream
	/workspace/vendor/google.golang.org/grpc/server.go:1737
google.golang.org/grpc.(*Server).serveStreams.func1.1
	/workspace/vendor/google.golang.org/grpc/server.go:986
```

### KEDA Version

2.12.1

### Kubernetes Version

1.27

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus

### Queue
![image](https://github.com/kedacore/keda/assets/13586514/2e237041-5a06-41ee-a8f1-45622a665f21)

### ScaledObject
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: xxx-service-blue
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xxx-service-blue
  pollingInterval: 15
  minReplicaCount: 1
  maxReplicaCount: 10
  fallback:
    failureThreshold: 3
    replicas: 2
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      name: xxx-service
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 600
          policies:
            - type: Pods
              value: 1
              periodSeconds: 120
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 100
              periodSeconds: 60
            - type: Pods
              value: 2
              periodSeconds: 60
          selectPolicy: Max
  triggers:
    # Parametric scaling
    - type: azure-servicebus
      metadata:
        messageCount: "10"
        queueName: xxx_check_queue
        connectionFromEnv: SERVICE_BUS_ENDPOINT
    - type: cpu
      metricType: AverageValue
      metadata:
        value: "1500m"
    - type: memory
      metricType: AverageValue
      metadata:
        value: "1.5Gi"
```
