### ISSUE TITLE
Multiple pods spawned on a single message in the Azure Storage Queue

### ISSUE THREAD

**Issue by JoooostB** [kedacore/keda#525]
## Description
I’ve been using KEDA Jobs to execute a rather CPU-intensive job based on an Azure Storage Queue trigger. However, due to it needing quite some resources, this sometimes means the cluster itself has to scale by provisioning extra nodes in order to be able to assign the necessary resources and start the job. Because this takes some time (we're talking minutes here), extra jobs for the same message in the queue start to spawn in a pending state; resulting in another scale up of nodes. This goes on until the maximum amount of pods is reached. 

## Expected Behavior
I expected KEDA to trigger only once per message added to the queue, resulting in 1 pod per message.

## Actual Behavior
Currently, KEDA spawns a pod each time the `pollingInterval` has passed. This results in pods being spawned every minute until the `maxReplicaCount` has been reached. Next to that, due to Azure's Autoscaling feature, additional nodes will be provisioned to handle the extra pods.

## Steps to Reproduce the Problem

1. Create the following ScaledObject that requires many resources and contains a job that runs for hours/days:
```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: consumer
  namespace: default
spec:
  scaleType: job
  pollingInterval: 60
  maxReplicaCount: 100
  cooldownPeriod: 30
  jobTargetRef:
    parallelism: 1
    completions: 1
    backoffLimit: 1
    template:
      spec:
        containers:
        - name: consumer
          image: registry.gitlab.xxx.com/consumer:latest
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: AzureWebJobsStorage
              valueFrom:
                secretKeyRef:
                  name: az-queue-secret
                  key: AzureWebJobsStorage
            - name: QUEUE_NAME
              value: consumer-test
  triggers:
  - type: azure-queue
    metadata:
      queueName: consumer-test
      queueLength: '1'
      connection: AzureWebJobsStorage # Based on secret
```
  2. Add a message to the queue
  3. Notice that multiple pods get spawned on only one message when insufficient resources are available and Azure needs to autoscale the node-pool.

## Specifications

  - **Version:**  v1.0.0
  - **Platform:** Azure Kubernetes Service 1.14.8
  - **Scaler(s):** Azure Storage Queue (see yaml above)

How would I be able to force KEDA to only trigger once per message added to the queue?

**Comment by balchua** [comment]
Looking at the code, I don't think there is a way.  Perhaps the job scaler first check how many `Job` are not completed/failed before starting a new `Job`.  
This will mean that the job must dequeue the message when it is done and not before.

**Comment by JoooostB** [comment]
Will this be a potential feature or should I look into alternatives?

**Comment by balchua** [comment]
I am trying to work on this one.  Should we just set `maxScale` to be `maxScale - runningJobs`.  This should limit the scaling.
If we want to have one message per job, this would mean that the `queueLength` must be `1`.

**Comment by JoooostB** [comment]
Many thanks @balchua, your explanation to resolve this issue sounds completely valid to me. Love to see that you've already submitted a pull request. Looking forward to it being merged :). If I can do anything in terms of documentation or something else; please let me know.

**Comment by balchua** [comment]
@JoooostB the pr has been merged.  Can help test it?  It might be in the master tag.
`docker pull kedacore/keda:master`

**Comment by JoooostB** [comment]
@balchua I've been running it for a few days based on a custom build from your repo. The main issue seems to be resolved, no extra pods are spawned on the same message. However, when more messages enter the queue, the amount of pods/jobs never exceeds 1. 

```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: queue-job
  namespace: default
spec:
  scaleType: job
  pollingInterval: 5
  maxReplicaCount: 10
  cooldownPeriod: 30
  jobTargetRef:
    parallelism: 10
    completions: 1
    backoffLimit: 1
    template:
      spec:
        containers:
        - name: queue
          image: registry.gitlab.xxx.nl/k8s/queue:slim
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: AzureWebJobsStorage
              valueFrom:
                secretKeyRef:
                  name: az-queue-secret
                  key: AzureWebJobsStorage
            - name: QUEUE_NAME
              value: queue-test
        imagePullSecrets:
        - name: gitlab-registry
  triggers:
  - type: azure-queue
    metadata:
      queueName: queue-test
      queueLength: '1'
      connection: AzureWebJobsStorage # Based on secret
```
Do you have any suggestions?
