### ISSUE TITLE
Review required RBAC permissions

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/keda#5261]
### Report

Currently, KEDA operator has permissions in cluster RBAC which aren't required
For example:
```yaml
- apiGroups:
  - ""
  resources:
  - configmaps
  - configmaps/status
  - events
  verbs:
  - '*'
```
AFAIK, KEDA doesn't need * over configMaps across all the cluster. We should revisit all the permissions and check if they are really required or not
