### ISSUE TITLE
Unexpected Access of Secrets by KEDA in Target Deployments

### ISSUE THREAD

**Issue by shmuelarditi** [kedacore/keda#5272]
### Report

After setting **permissions.operator.restrict.secret** in the helm chart as part of security enforcements, I have encountered an issue where KEDA seems to be attempting to access secrets that are referenced by the target deployments or rollouts, even though these secrets are not directly referenced in KEDA resources themselves.

### Expected Behavior

KEDA should only access secrets that are explicitly referenced in its own resources, such as those defined in ScaledObject or TriggerAuthentication, and not automatically attempt to access secrets referenced in the target deployments or rollouts.

### Actual Behavior

KEDA attempting to access secrets that are referenced by the target deployments or rollouts

### Steps to Reproduce the Problem

1. Set up a ScaledObject with KEDA, referencing a specific deployment or rollout.
2. In the target deployment, include references to certain Kubernetes secrets.
3. Observe that KEDA attempts to access these secrets, despite them not being referenced in the ScaledObject or related KEDA resources.

### Logs from KEDA operator

2023-12-10T10:06:55Z    ERROR    scale_handler    error resolving auth params    {"type": "ScaledObject", "namespace": "customers", "name": "squadron-squadron-3kcjh7-scaledobject", "scalerIndex": 0, "error": "error resolving secrets for ScaleTarget: error reading secret ref &SecretEnvSource{LocalObjectReference:LocalObjectReference{Name:squadron-secrets,},Optional:nil,} on namespace customers: secret \"squadron-secrets\" not found"}

### KEDA Version

2.11.0

### Kubernetes Version

1.27

### Platform

Google Cloud

### Scaler Details

Prometheus 

### Anything else?

We do not have any secrets in our KEDA resources, the only secrets references are in the rollouts/deployments.

here are the yamls, for rollout, scaledObject:

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-rollout
  namespace: customers
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        squadron.elementor.cloud/gen: "0"
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      priorityClassName: squadron-priority
      containers:
      - name: squadron
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ['node', '-r', 'source-map-support/register', 'dist/index.js']
        terminationMessagePath: "/dev/kubernetes/termination-log"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: health
          containerPort: 8081
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /health/live
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /health/ready
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        {{- range $storage := .Values.storage }}
        - mountPath: /mnt/customers/{{ $storage.name }}
          name: nfs-{{ $storage.name }}
        {{- end }}
        - mountPath: {{ .Values.wpAgentModulesPath }}
          name: wp-agent-modules
        - name: squadrons
          mountPath: {{ .Values.squadron_path }}/{{ .Release.Name }}
        - name: file-system
          mountPath: {{ .Values.logsRoot }}
        - name: shared-stack
          mountPath: {{ .Values.sharedStackMount }}
        env:
        - name: SQUADRON_ID
          value: {{ .Release.Name }}
        - name: SQUADRONS_DIR_PATH
          value: {{ .Values.squadron_path }}
        - name: LOGS_ROOT
          value: {{ .Values.logsRoot }}
        - name: WP_AGENT_MODULES_PATH
          value: {{ .Values.wpAgentModulesPath }}
        - name: LICENSE_V2_BASE_SERVER
          value: {{ .Values.license_v2_base_server }}
        - name: ACCOUNT_BASE_SERVER
          value: {{ .Values.account_base_server }}
        - name: CONTROL_PROXY_URL
          value: {{ .Values.controlProxyUrl }}
        - name: INVENTORY_MANAGER_URL
          value: {{ .Values.inventoryManagerUrl | replace "ENV_PL" .Values.el_env }}
        - name: SHARED_STACK_MOUNT
          value: {{ .Values.sharedStackMount }}
        - name: ELEMENTOR_AUTHENTICATION_JWT_PUBLIC_KEY
          value: {{ .Values.elementorAuthenticationJwtPublicKey }}
        - name: LOGIN_WITH_ELEMENTOR_REDIRECT_URL
          value: {{ .Values.loginWithElementorRedirectUrl }}
        envFrom:
        - secretRef:
            name: squadron-secrets
        {{- if .Values.resources }}
        resources: 
          {{- toYaml .Values.resources | nindent 12 -}}
        {{- end}}
      - name: log-agent
        image: gcr.io/stackdriver-agents/stackdriver-logging-agent:1.8.5
        resources:
          requests:
            cpu: "50m"
            memory: 150M
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_CONTAINER
          value: squadron
        - name: FLUENTD_ARGS
          value: -c /etc/fluentd-config/fluentd.conf
        volumeMounts:
        - name: config-volume
          mountPath: /etc/google-fluentd/config.d   
        - name: file-system
          mountPath: {{ .Values.logsRoot }}
        - name: k8s-labels
          mountPath: /k8s
        - mountPath: /etc/google-fluentd/google-fluentd.conf
          subPath: google-fluentd.conf
          name: default-config-volume  
      volumes:
      {{- range $storage := .Values.storage }}
      - name: nfs-{{ $storage.name }}
        persistentVolumeClaim:
          claimName: "squadron-pvc-{{ $storage.name }}-customers-{{ $.Release.Name }}"
      {{- end }}
      - name: wp-agent-modules
        persistentVolumeClaim:
          claimName: "squadron-pvc-wpam-modules-{{ $.Release.Name }}"
          readOnly: true
      - name: shared-stack
        persistentVolumeClaim:
          claimName: "squadron-pvc-shared-stack-{{ $.Release.Name }}"
          readOnly: true
      - name: file-system
        emptyDir: {}
      - name: squadrons
        hostPath:
          path: {{ .Values.squadron_path }}/{{ .Release.Name }}
      - name: config-volume
        configMap:
          name: squadron-{{ .Release.Name }}-fluentd-config
      - name: default-config-volume
        configMap:
          name: squadron-{{ .Release.Name }}-fluentd-gcp-main-config
      - name: k8s-labels
        downwardAPI:
          items:
            - path: labels
              fieldRef:
                fieldPath: metadata.labels
      enableServiceLinks: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      canaryMetadata:
        annotations:
          experiment: canary
        labels:
          experiment: canary
      stableMetadata:
        annotations:
          experiment: stable
        labels:
          experiment: stable
      maxSurge: "25%"
      maxUnavailable: 0
      {{- if .Values.experiment }}
      steps:
      - setWeight: 50
      - pause:
          duration: {{ .Values.experiment.duration }}m
      - analysis:
          templates:
          - templateName: always-fail-{{ .Release.Name }}
      {{- end }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: squadron-{{ .Release.Name }}-scaledobject
  namespace: customers
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ .Release.Name }}-rollout
  pollingInterval: 10 # Optional. Default: 30 seconds
  minReplicaCount: {{ .Values.minReplicaCount }}
  maxReplicaCount: {{ .Values.maxReplicaCount }}
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "80"
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        threshold: "80"
        query: sum(squadron_fpm_pool_active_processes{squadron_id="{{ .Release.Name }}"})
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        threshold: "3"
        query: |
          (
            sum(rate(nginx_ingress_controller_request_duration_seconds_sum{ingress="{{ .Release.Name }}", namespace="customers", status=~"[2-4].."}[1m])) / 
            sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress="{{ .Release.Name }}", namespace="customers", status=~"[2-4].."}[1m]))
          ) * count(kube_pod_status_phase{phase="Running",pod=~"{{ .Release.Name }}-rollout.*", namespace="customers"} == 1)
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 300
          policies:
          - type: Pods
            value: 1
            periodSeconds: 120
        scaleDown:
          stabilizationWindowSeconds: 1800
          policies:
          - type: Pods
            value: 1
            periodSeconds: 60

```
