### ISSUE TITLE
keda-operator : kafka metadata: no username given

### ISSUE THREAD

**Issue by spajanj** [kedacore/keda#5287]
### Report

Getting the below error message from keda-operator  kafka metadata: no username given. Passed  the value properly in TriggerAuthentication. Still we are getting the below error from keda operator
 error parsing kafka metadata: no username given 

### Expected Behavior

NAME                   SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   TRIGGERS       AUTHENTICATION                              READY   ACTIVE   FALLBACK   AGE
kafka-scaledobject   apps/v1.Deployment      sim-ap-api-dev    3     5     kafka      keda-trigger-auth-kafka-credential              True    True     False      24s

### Actual Behavior

NAME                 SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   TRIGGERS   AUTHENTICATION                       READY   ACTIVE    FALLBACK   PAUSED    AGE
kafka-scaledobject   apps/v1.Deployment   sim-ap-api-dev    3     5     kafka      keda-trigger-auth-kafka-credential   False   Unknown   Unknown    Unknown   10m

### Steps to Reproduce the Problem

1. Keda Kafka Secrets

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
type: Opaque  
data:
  sasl: cGxhaW50ZXh0Cg==
  tls: ZW5hYmxlCg==
  username: *****************
  password: *****************
  apcertificate: **********
  apkey: ************
```
2.  TriggerAuthentication
```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
spec:
  secretTargetRef:
    - parameter: username
      name: keda-kafka-secrets
      key: username
    - parameter: password
      name: keda-kafka-secrets
      key: password
    - parameter: cert
      name: keda-kafka-secrets
      key: apcertificate
    - parameter: key
      name: keda-kafka-secrets
      key: apkey
```
3. Scaled Object:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
spec:
  scaleTargetRef:
    name: sim-ap-api-dev
  pollingInterval: 30
  minReplicaCount: 3
  maxReplicaCount: 5
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: server:9094
        consumerGroup: ap.group
        topic: event.payment.internal.int
        lagThreshold: '20'
        offsetResetPolicy: latest
        sasl: plaintext
        tls: enable
      authenticationRef:
        name: keda-trigger-auth-kafka-credential
```

### Logs from KEDA operator

KEDA Operator logs:

```bash
2023-12-13T22:14:16Z    ERROR   Reconciler error        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"kafka-scaledobject","namespace":"default"}, "namespace": "default, "name": "kafka-scaledobject", "reconcileID": "0fcb97ed-9e8f-4589-b708-df9e777e2803", "error": "error parsing kafka metadata: no username given"}
```

### KEDA Version

2.12.1

### Kubernetes Version

1.25

### Platform

Amazon Web Services

### Scaler Details

Apache Kafka

### Anything else?

Tried multiple option, keep on getting the same error. Could you please provide your comments to resolve this issues.
