### ISSUE TITLE
SharedResourceWarning in AKS

### ISSUE THREAD

**Issue by joudaon** [kedacore/keda#5298]
### Report

When installing KEDA with ArgoCD, I get SharedResourceWarning warning.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-keda
  namespace: argocd
  labels:
    app_type: applicationset
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys:
          - server
        generators:
          - clusters:
              values:
                addonChart: keda
                # anything not staging or prod use this version
                addonChartVersion: 2.11.2
                addonChartRepository: https://kedacore.github.io/charts
              selector:
                matchExpressions:
                  - key: enable_keda
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: pre
              values:
                addonChartVersion: 2.11.2
          - clusters:
              selector:
                matchLabels:
                  environment: pro
              values:
                addonChartVersion: 2.11.2
  template:
    metadata:
      name: "addon-{{.name}}-{{.values.addonChart}}-{{.values.addonChartVersion}}"
      labels:
        app_type: addon
        addon_name: keda
    spec:
      project: default
      sources:
        - repoURL: '{{ .values.addonChartRepository}}'
          targetRevision: '{{ .values.addonChartVersion}}'
          chart: '{{ .values.addonChart}}'
          helm:
            releaseName: keda
            parameters:
              - name: cluster_name
                value: '{{ .name }}'
            values: |-
              webhooks:
                enabled: false              
      destination:
        name: '{{ .name }}'
        namespace: keda
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
```

### Expected Behavior

I should not get any SharedResourceWarning 

### Actual Behavior

I see SharedResourceWarning 

> CustomResourceDefinition/clustertriggerauthentications.keda.sh is part of applications argocd/addon-argocd-dev-cluster-keda-2.11.2 and keda
> CustomResourceDefinition/scaledjobs.keda.sh is part of applications argocd/addon-argocd-dev-cluster-keda-2.11.2 and keda
> CustomResourceDefinition/scaledobjects.keda.sh is part of applications argocd/addon-argocd-dev-cluster-keda-2.11.2 and keda
> CustomResourceDefinition/triggerauthentications.keda.sh is part of applications argocd/addon-argocd-dev-cluster-keda-2.11.2 and keda
> 

### Steps to Reproduce the Problem

1. Deploy ApplicationSet with ArgoCD

### Logs from KEDA operator

N/A

### KEDA Version

2.11.2

### Kubernetes Version

1.26

### Platform

Microsoft Azure
