### ISSUE TITLE
Keda-kafka - scaledobject reports healthy despite not creating hpa resource

### ISSUE THREAD

**Issue by markallanson** [kedacore/keda#5312]
### Report

When a scaledobject was created, it was unable to communicate with Kafka, so did not create a HPA. Despite this, the scaledobject reports as Ready, meaning systems such as ArgoCD report it as healthy instead of degraded.

The scaledobject status reports `type: Ready` despite being in an error state.

```
  conditions:
    - message: failed to ensure HPA is correctly created for ScaledObject
      reason: ScaledObjectCheckFailed
      status: 'False'
      type: Ready
```

This failed due to a kafka connectivity error `error creating kafka client: kafka: client has run out of available brokers to talk to: unexpected EOF`

### Expected Behavior

The most recent status for the CRD should report as an error state when the HPA cannot be created for any reason.

### Actual Behavior

The most recent status for the CRD is reporting as "Ready"

### Steps to Reproduce the Problem

1. Deploy a scaledobject while a kafka broker is unavailable?

### KEDA Version

2.11.2

### Kubernetes Version

1.25

### Platform

Any

### Scaler Details

Kafka
