### ISSUE TITLE
Workload scaled up and down repeatedly when using scalingModifiers and fallback if only 1 trigger is failing

### ISSUE THREAD

**Issue by RRethy** [kedacore/keda#5409]
### Report

When using 2 or more triggers and a scalingModifier (e.g. max(trigger_1, trigger_2)), if the scalingModifier has `metricType: Value` and at least 1 trigger has `metricType: Value`, then when that trigger fails the workload is scaled back and forth between `minReplicas` and `fallback.replicas`. The `fallback` value in the `-owide` for the scaledobject also switches between `true` and `false` repeatedly.

### Expected Behavior

I would expect it to not scale up and down repeatedly. Ideally, it would scale to fallback.

### Actual Behavior

It scales the workload up and down.

### Steps to Reproduce the Problem

Here's a repo with setup.sh to set things up, https://github.com/RRethy/keda-issue-minimum-reproducible-2.

The `Fallback` field in the `-owide` for ScaledObject will switch between `true` and `false` repeatedly.
The replica count for the deployment will go back and forth between 3 and 12 repeatedly.

Here's a manifest that can be applied, then just watch the deployment and scaledobject with `-owide -w`.

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: myscaledobject
  namespace: foobar
spec:
  scaleTargetRef:
    kind: Deployment
    name: mydeployment
  fallback:
    failureThreshold: 4
    replicas: 12
  advanced:
    scalingModifiers:
      formula: "max(trigger_1, trigger_2)"
      metricType: Value
      target: "1"
      activationTarget: "0"
  pollingInterval: 30
  minReplicaCount: 3
  maxReplicaCount: 30
  triggers:
  - type: prometheus
    name: trigger_1
    metricType: Value
    metadata:
      serverAddress: http://fake.svc.cluster.local:9090
      threshold: "1"
      activationThreshold: "0"
      query: >
        max(mymetric1{}[2m])
  - metadata:
      podSelector: name=busybox
      value: "1"
    name: trigger_2
    # this can be any trigger that is valid
    # Initially I encountered this using metricType:Value for a prometheus trigger
    # kubernetes-workload is only used so it can be setup easily
    type: kubernetes-workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: foobar
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          args:
            - while true; do sleep 30; done;
          command:
            - /bin/bash
            - -c
            - --
          image: ubuntu:latest
          imagePullPolicy: Always
```

### Logs from KEDA operator

Available in https://github.com/RRethy/keda-issue-minimum-reproducible-2.

### KEDA Version

2.13.0

### Kubernetes Version

1.27

### Platform

Other

### Scaler Details

Prometheus and kubernetes-workload. When I first encountered this I was using two prometheus triggers with `metricType: Value`.

### Anything else?

cc. @gauron99
