### ISSUE TITLE
MySQL Scaled job now working with TriggerAuthentication

### ISSUE THREAD

**Issue by ferrandinand** [kedacore/keda#5416]
### Report

MySQL Scaled job is not able to get variables from a TriggerAuthentication

### Expected Behavior

I expect that password and other configs are configured from a TriggerAuthentication CR grabbing the config from a secret

### Actual Behavior

Keda complains about variables required not present if configured in a TriggerAuthentication

### Steps to Reproduce the Problem

1. Run the following code Keda waits for a required missing host parameter
```
---
apiVersion: v1
data:
  mysql_conn_str: WVdSdGFXNDZjMlJtWkhOb...tZWFJoWW1GelpTMHg=
kind: Secret
metadata:
  name: mysql-secrets
  namespace: module-cwh-test3
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mysql-auth
  namespace: module-cwh-test3
spec:
  secretTargetRef:
  - key: mysql_conn_str
    name: mysql-secrets
    parameter: connectionString
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: myscaled-job 
  namespace: module-cwh-test3    
spec:
  jobTargetRef:
    parallelism: 1                            
    completions: 1                            
    activeDeadlineSeconds: 600              
    backoffLimit: 6 
    template:
      spec:
        restartPolicy: Never
        containers:
        - image: public.ecr.aws/unicc/ubuntu-tooling:stable
          name: tooling
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mysql-secrets
  triggers:
    - type: mysql
      authenticationRef:
        name: mysql-auth
      metadata: 
        queryValue: "1"
        query: "SELECT COUNT(*) FROM notifications WHERE state='QUEUED'"
```
```
  Warning  KEDAScalerFailed      1s (x11 over 6s)  scale-handler  error parsing MySQL metadata: missing required field in scaler config: no host given
  Warning  ScaledJobCheckFailed  1s (x11 over 6s)  keda-operator  Failed to ensure ScaledJob is correctly created
```       

2. Introducing the host in the secret and in the triggerauth does not make any difference
```
---
apiVersion: v1
data:
  mysql_conn_str: WVdSdGFXNDZjMlJtWkhOb...tZWFJoWW1GelpTMHg=
  host: ZGF0Y...cy5hbWF6b25hd3MuY29t
kind: Secret
metadata:
  name: mysql-secrets
  namespace: module-cwh-test3
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mysql-auth
  namespace: module-cwh-test3
spec:
  secretTargetRef:
  - key: mysql_conn_str
    name: mysql-secrets
    parameter: connectionString
  - key: host
    name: mysql-secrets
    parameter: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: myscaled-job 
  namespace: module-cwh-test3    
spec:
  jobTargetRef:
    parallelism: 1                            
    completions: 1                            
    activeDeadlineSeconds: 600              
    backoffLimit: 6 
    template:
      metadata:
        labels:
          run: ubuntu-tooling-lap
      spec:
        restartPolicy: Never
        containers:
        - image: public.ecr.aws/unicc/ubuntu-tooling:stable
          name: tooling
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mysql-secrets
  triggers:
    - type: mysql
      authenticationRef:
        name: mysql-auth
      metadata: 
        queryValue: "1"
        query: "SELECT COUNT(*) FROM notifications WHERE state='QUEUED'"
```
```
  Warning  KEDAScalerFailed      104s (x18 over 12m)  scale-handler  error parsing MySQL metadata: missing required field in scaler config: no host given
  Warning  ScaledJobCheckFailed  104s (x18 over 12m)  keda-operator  Failed to ensure ScaledJob is correctly created
```

3.- Configuring the host as a var works for host but waits for password parameter 
```
... omitting secret

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mysql-auth
  namespace: module-cwh-test3
spec:
  secretTargetRef:
  - key: mysql_conn_str
    name: mysql-secrets
    parameter: connectionString
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: myscaled-job 
  namespace: module-cwh-test3    
spec:
  jobTargetRef:
    parallelism: 1                            
    completions: 1                            
    activeDeadlineSeconds: 600              
    backoffLimit: 6 
    template:
      metadata:
        labels:
          run: ubuntu-tooling-lap
      spec:
        restartPolicy: Never
        containers:
        - image: public.ecr.aws/unicc/ubuntu-tooling:stable
          name: tooling
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mysql-secrets
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "300m"
              memory: "256Mi"
  triggers:
    - type: mysql
      authenticationRef:
        name: mysql-auth
      metadata: 
        host: database-1.c3hwsnntysui.eu-west-1.rds.amazonaws.com
        dbName: database-1
        port: "3306"
        username: admin
        queryValue: "1"
        query: "SELECT COUNT(*) FROM notifications WHERE state='QUEUED'"
```
```
  Warning  ScaledJobCheckFailed  3s (x20 over 12m)   keda-operator  Failed to ensure ScaledJob is correctly created
  Warning  KEDAScalerFailed      3s (x6 over 10m)    scale-handler  error parsing MySQL metadata: no password given
```
4. Configuring the password as env var works as expected

### Logs from KEDA operator

Error no host given
```
2024-01-19T15:43:38Z	ERROR	Reconciler error	{"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "ScaledJob": {"name":"myscaled-job","namespace":"module-cwh-test3"}, "namespace": "module-cwh-test3", "name": "myscaled-job", "reconcileID": "68dc9b5f-3c24-4772-a810-516cc73b6f73", "error": "error parsing MySQL metadata: missing required field in scaler config: no host given"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
2024-01-19T15:44:14Z	INFO	Reconciling ScaledJob	{"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "ScaledJob": {"name":"myscaled-job","namespace":"modu
```

Error no password given
```
2024-01-19T15:49:33Z	ERROR	Failed to ensure ScaledJob is correctly created	{"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "ScaledJob": {"name":"myscaled-job","namespace":"module-cwh-test3"}, "namespace": "module-cwh-test3", "name": "myscaled-job", "reconcileID": "eb6a6edd-fccd-498f-b1ca-39d4ec238fb4", "error": "error parsing MySQL metadata: no password given"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledJobReconciler).Reconcile
	/workspace/controllers/keda/scaledjob_controller.go:149
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
2024-01-19T15:49:33Z	ERROR	Reconciler error	{"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "ScaledJob": {"name":"myscaled-job","namespace":"module-cwh-test3"}, "namespace": "module-cwh-test3", "name": "myscaled-job", "reconcileID": "eb6a6edd-fccd-498f-b1ca-39d4ec238fb4", "error": "error parsing MySQL metadata: no password given"}
```

### KEDA Version

2.12.1

### Kubernetes Version

Other

### Platform

Amazon Web Services

### Scaler Details

MySQL

**Comment by JorTurFer** [comment]
Hello,
Could you confirm that your `connectionString` follows this format? `user:password@tcp(mysql:3306)/stats_db`
If your connection doesn't follow that format, you will have to provide ALL the connection parameters. I mean, connection string and auth parameters are mutually exclusive, so if you set connection string other authentication parameters aren't read. You can see the logic here:
https://github.com/kedacore/keda/blob/072fcf09ed0259b4e78f1173a6fc5fe9cdadcf4a/pkg/scalers/mysql_scaler.go#L98-L106

**Comment by ferrandinand** [comment]
Hi @JorTurFer thanks for your help.
Yes the connection string in the secret follows that format. Even I face a similar error (not able to parse variable from a TriggerAuthentication) using the connectionString example present in the mysql scaler documentation.

If I modify the secret to use exactly the same base64 secret. I get the following error:
```
  Warning  KEDAScalerFailed      8s (x12 over 18s)  scale-handler  error parsing MySQL metadata: missing required field in scaler config: no host given
  Warning  ScaledJobCheckFailed  8s (x12 over 18s)  keda-operator  Failed to ensure ScaledJob is correctly created
```
I would expect anything like, not able to connect to mysql

This is the k8s config I am trying to make work:
```
---
apiVersion: v1
data:
  # base64 encoded value of mysql connectionString of format user:password@tcp(mysql:3306)/stats_db
  mysql_conn_str: dXNlckB0Y3AobXlzcWw6MzMwNikvc3RhdHNfZGI=
kind: Secret
metadata:
  name: mysql-secrets
  namespace: module-cwh-test3
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mysql-auth
  namespace: module-cwh-test3
spec:
  secretTargetRef:
  - key: mysql_conn_str
    name: mysql-secrets
    parameter: connectionString
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: myscaled-job 
  namespace: module-cwh-test3    
spec:
  jobTargetRef:
    parallelism: 1                            
    completions: 1                            
    activeDeadlineSeconds: 600              
    backoffLimit: 6 
    template:
      spec:
        restartPolicy: Never
        containers:
        - image: public.ecr.aws/unicc/ubuntu-tooling:stable
          name: tooling
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mysql-secrets
  triggers:
    - type: mysql
      authenticationRef:
        name: mysql-auth
      metadata: 
        queryValue: "1"
        query: "SELECT COUNT(*) FROM notifications WHERE state='QUEUED'"
```
