### ISSUE TITLE
Unable to communicate with nodes where keda-operator-metrics-apiserver is running

### ISSUE THREAD

**Issue by DanTulovsky** [kedacore/keda#5425]
### Expected Behavior

This is on GKE. On any node that the keda-operator-metrics-apiserver ends up on, we are no longer able to communicate with it properly.  The error returned (for example, from trying to connect to the node via kubectl) is:

```
 tls: failed to verify certificate: x509: cannot validate certificate for 10.0.0.124 because it doesn't contain any IP SANs"
```

The metrics-apiserver is running with the following (seemingly relevant) configs:

```
   volumes:
    - name: certificates
     secret:
      secretName: kedaorg-certs
      defaultMode: 420
...
     volumeMounts:
      - name: certificates
       readOnly: true
       mountPath: /certs
...
     args:
      - /usr/local/bin/keda-adapter
...
      - --client-ca-file=/certs/ca.crt
      - --tls-cert-file=/certs/tls.crt
      - --tls-private-key-file=/certs/tls.key
      - --cert-dir=/certs
```

Can you please advise on what is happening?

Thank you
Dan

### Actual Behavior

Please see above.

### Steps to Reproduce the Problem

1. Bring up keda.  Find the node keda-operator-metrics-apiserver is running on.
2. Try to connect to the node using kubectl.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.12.1

### Kubernetes Version

1.27

### Platform

Google Cloud
