### ISSUE TITLE
AWS Secrets Manager for authentication gets context canceled

### ISSUE THREAD

**Issue by zm-alex** [kedacore/keda#5428]
### Report

We have encounter error logs in the AWS Secrets Manager authentication method when using a Cluster Trigger Authentication.

The error seems to indicate that the retrieval of the secrets are getting cancel before it can retrieve the secrets. This seems to happen sporadically.

### Expected Behavior

To be able to consistently retrieve the secrets without errors.

### Actual Behavior

The operator gets errors in retrieving the secrets from AWS secrets manager with an error message of request canceled. This behavior happens sporadically.

### Steps to Reproduce the Problem

1.  Create an IAM role with GetSecretValue action
2. Provide the IAM role as an annotation for the service account to use IRSA
3. Configure a ClusterTriggerAuthentication to use the secrets from AWS Secrets Manager

### Logs from KEDA operator

```
2024-01-23T18:55:55Z    ERROR   scale_handler   Error getting credentials       {"type": "ScaledObject", "namespace": "namespace", "name": "topic-discovery-metric-api-scaledobject", "error": "operation error Secrets Manager: GetSecretValue, get identity: get credentials: request canceled, context canceled"}
github.com/kedacore/keda/v2/pkg/scaling/resolver.(*AwsSecretManagerHandler).Read
        /workspace/pkg/scaling/resolver/aws_secretmanager_handler.go:60
github.com/kedacore/keda/v2/pkg/scaling/resolver.resolveAuthRef
        /workspace/pkg/scaling/resolver/scale_resolvers.go:344
github.com/kedacore/keda/v2/pkg/scaling/resolver.ResolveAuthRefAndPodIdentity
        /workspace/pkg/scaling/resolver/scale_resolvers.go:183
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers.func1
        /workspace/pkg/scaling/scalers_builder.go:72
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).refreshScaler
        /workspace/pkg/scaling/cache/scalers_cache.go:151
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
        /workspace/pkg/scaling/cache/scalers_cache.go:135
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
        /workspace/pkg/scaling/scale_handler.go:743
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState.func1
        /workspace/pkg/scaling/scale_handler.go:628

```

```
2024-01-23T18:55:55Z    ERROR   scale_handler   error trying to read secret from Aws Secret Manager     {"type": "ScaledObject", "namespace": "namespace", "name": "topic-discovery-metric-api-scaledobject", "triggerAuthRef.Name": "amq-keda-credentials", "secret.Name": "devops/eks/dev/us-east-1/app-keda-amdev-user", "secret.Version": "", "secret.VersionStage": "", "error": "operation error Secrets Manager: GetSecretValue, get identity: get credentials: request canceled, context canceled"}
github.com/kedacore/keda/v2/pkg/scaling/resolver.resolveAuthRef
        /workspace/pkg/scaling/resolver/scale_resolvers.go:346
github.com/kedacore/keda/v2/pkg/scaling/resolver.ResolveAuthRefAndPodIdentity
        /workspace/pkg/scaling/resolver/scale_resolvers.go:183
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers.func1
        /workspace/pkg/scaling/scalers_builder.go:72
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).refreshScaler
        /workspace/pkg/scaling/cache/scalers_cache.go:151
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
        /workspace/pkg/scaling/cache/scalers_cache.go:135
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
        /workspace/pkg/scaling/scale_handler.go:743
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState.func1
        /workspace/pkg/scaling/scale_handler.go:628

```

### KEDA Version

2.13.0

### Kubernetes Version

1.23

### Platform

Amazon Web Services

### Scaler Details

metrics-api

**Comment by JorTurFer** [comment]
Based on the stack trace, the request is cancelled by the caller so I'm not sure if this is related with AWS Secret manager or something before. Could you give us more context about the case?
How many secrets are you recovering? Do you have network issues? Any other strange log entry?

@zroubalik , @geoffrey1330 , do you have any idea?

**Comment by geoffrey1330** [comment]
I will look into this error and report any feedings here.

**Comment by zm-alex** [comment]
@geoffrey1330 sorry, I was out a couple of weeks, sure here it is

```
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: amq-keda-credentials
spec:
  awsSecretManager:
    podIdentity:
      provider: aws
    region: us-east-1
    secrets:
      - name: devops/eks/dev/us-east-1/user
        parameter: username
      - name: devops/eks/dev/us-east-1/password
        parameter: password
```

Our IAM role has the following policy

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "secretsmanager:GetSecretValue",
            "Effect": "Allow",
            "Resource": "arn:aws:secretsmanager:*:*:secret:devops/eks/*",
            "Sid": "GetSecretValueSecretsManager"
        }
    ]
}
```

Trust relationship

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::0000000000:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/000000000000000000000"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/000000000000000000000:sub": "system:serviceaccount:keda:keda-operator",
                    "oidc.eks.us-east-1.amazonaws.com/id/000000000000000000000:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

For our scaledobject, we're using the metrics-api scaler reference to the CTA

```
  triggers:
    - authenticationRef:
        kind: ClusterTriggerAuthentication
        name: amq-keda-credentials
      metadata:
        authMode: basic
        targetValue: '1'
        url: http://service.app.svc.cluster.local:8899/api/v2/get_remain
        valueLocation: data.topic.0.group.0.value
      type: metrics-api
```

Thanks!
