### ISSUE TITLE
gcp-pubsub throwing "could not find stackdriver metric"

### ISSUE THREAD

**Issue by ddlenz** [kedacore/keda#5429]
### Report

After updating to 2.13.0, gcp_pub_sub_scaler repeatedly throws "error getting metric" and scale_handler throws "error getting scale decision" with "could not find stackdriver metric with query fetch pubsub_subscription" with unacked messages and failure to scale.

### Expected Behavior

keda scales application from zero

### Actual Behavior

keda fails to scale application from zero

### Steps to Reproduce the Problem

1. create gcp-pubsub scaler
2. publish a message to trigger the scaler
3. check unacked messages and logs

### KEDA Version

2.13.0

### Kubernetes Version

Other

### Platform

Google Cloud

### Scaler Details

gcp pubsub

### Anything else?

kubernetes version 1.28.3-gke.1203001

**Comment by JorTurFer** [comment]
Hello,
Does it work on previous versions? Could you share your ScaledObject?

**Comment by FrancoisPoinsot** [comment]
I am having the exact same issue.
Same keda version
Kubernetes 1.26
Similar error log.
Also with gcp pubsub scaler.
Can also play the query successfuly in Google Metric Explorer.

I had to rollback to 2.12.1 because we had issue with some workload not scaling up. 
That is what we detected originaly.

**Comment by JorTurFer** [comment]
So, does it work in KEDA v2.12.1 and not in KEDA v2.13.0?

**Comment by ekaputra07** [comment]
Hi, first of all, thanks for this great project!

But facing same issue here, I'm using:
```
KEDA v2.13.0 / GKE Autopilot / Pub/Sub
```

My ScaledObject:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: some-name
spec:
  scaleTargetRef:
    name: some-name
  triggers:
    - type: gcp-pubsub
      authenticationRef:
        name: trigger-authentication-dev
        kind: ClusterTriggerAuthentication
      metadata:
        mode: NumUndeliveredMessages
        value: "5"
        activationValue: "0"
        subscriptionName: projects/my-project/subscriptions/my-sub
```

The error:
```bash
2024-01-31T04:53:00Z	ERROR	gcp_pub_sub_scaler	error getting metric	{"type": "ScaledObject", "namespace": "default", "name": "some-name", "metricType": "pubsub.googleapis.com/subscription/num_undelivered_messages", "error": "could not find stackdriver metric with query fetch pubsub_subscription | metric 'pubsub.googleapis.com/subscription/num_undelivered_messages' | filter (resource.project_id == 'my-project' && resource.subscription_id == 'my-sub') | within 1m"}
```
---

I copy-pasted the query I found in error message and run it on GCP's Metrics Explorer:
![iScreen Shoter - 2024013110828997 PM](https://github.com/kedacore/keda/assets/1094221/f018bfd2-f0b0-4692-a4b8-eb7dee3d41e2)

**Things that I noticed are:**
- using `within 1m` the query **sometime** return result, but **most of the time it doesn't**
- using higher time range for example `within 5m` **always** working (return result)

---

Based on its [documentation](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-pubsub), it says:

> **subscription/num_undelivered_messages**
> Number of unacknowledged messages (a.k.a. backlog messages) in a subscription. Sampled every 60 seconds. After sampling, **data is not visible for up to 120 seconds**.

Those might not related, but I'm just trying to provide data as much as possible and hopefully they helps to debug the situation.

---

**And based on the scaler code, looks like we mark it as an Error if stackdriver doesn't return value.**
https://github.com/kedacore/keda/blob/cd57dd9525dc8c25e95a42524701045bb4fdef14/pkg/scalers/gcp/gcp_stackdriver_client.go#L291

**Comment by FrancoisPoinsot** [comment]
Some more context about what happened.

I have 8 gcp-pubsub scaledObject.
5 with `minReplicaCount:0` .
3 with `minReplicaCount:1` .

When we upgraded keda to 2.13.0, all 5 deployements targeted by scaledobject with  `minReplicaCount:0`  started to have scaling issue.
They were scaled down to 0. No matter how many pods existed.

Those with `minReplicaCount:1` seems unaffected.
So I am wondering if the problem is specificaly related to the **Activation phase**.

I am trying to get a reproduction scenario. 

here is a basic manifest.
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-francois
  namespace: test-francois
spec:
  maxReplicaCount: 5
  minReplicaCount: 0
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-francois
  triggers:
  - authenticationRef:
      kind: ClusterTriggerAuthentication
      name: keda-clustertrigger-auth-gcp-credentials
    metadata:
      mode: SubscriptionSize
      subscriptionName: test-francois-sub
      value: "4"
    type: gcp-pubsub
```

You need to publish manually in the topic in question. Don't need to ack any message. Just use the value to scale up/down any random deployment.

Using this I can reproduce having an error log in keda-operator.
Also I get a steady increase in `keda_scaler_errors` metric.
Also, watching the generated hpa, this is what I see:
```
NAME                     REFERENCE                  TARGETS     MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-test-francois   Deployment/test-francois   2/4 (avg)   1         5         1          117m
keda-hpa-test-francois   Deployment/test-francois   <unknown>/4 (avg)   1         5         1          117m
```
Roughly 1/3 of the entries show the target with `<unknown>`

However this setup is not enough to reproduce the issue above. The deployement is not being scaled down to 0.
But I wonder if that is just a matter of how frequent those error shows up.
