### ISSUE TITLE
Issues running azure pipelines trigger with ScaledJob

### ISSUE THREAD

**Issue by chrismilson** [kedacore/keda#5451]
### Report

I tried to create a ScaledJob with a trigger for azure-pipelines. It would fail with "error parsing azure Pipelines metadata: no organizationURL given".

### Expected Behavior

I expected the ScaledJob to become ready.

### Actual Behavior

The ScaledJob failed to become ready, and the controller would output the error: "error parsing azure Pipelines metadata: no organizationURL given"

### Steps to Reproduce the Problem

1. Create a TriggerAuthentication for an "azure-workload" type podIdentity
2. Create a ScaledJob with an azure-pipelines trigger

### Logs from KEDA operator

```
2024-01-31T20:03:38Z    ERROR   Failed to ensure ScaledJob is correctly created {"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "ScaledJob": {"name":"test","namespace":"buildagent"}, "namespace": "buildagent", "name": "test", "reconcileID": "***", "error": "error parsing azure Pipelines metadata: no organizationURL given"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledJobReconciler).Reconcile
        /workspace/controllers/keda/scaledjob_controller.go:150
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
```

### KEDA Version

2.13.0

### Kubernetes Version

1.27

### Platform

Microsoft Azure

### Scaler Details

Azure Pipelines

### Anything else?

I tried creating a ConfigMap the organizationUrl to add to the TriggerAuthentication, but still got the same issue. I also tried using `organizationURLFromEnv: AZP_URL`, as I had specified the `AZP_URL` environment variable in the jobTargetRef, but this also failed.

**Comment by JorTurFer** [comment]
Could you share your ScaledJob? (you can remove sensitive data)

**Comment by chrismilson** [comment]
Sure

<details>
<summary>TriggerAuthentication/ScaledJob manifest</summary>

```yaml
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: test
  namespace: buildagent
spec:
  podIdentity:
    provider: azure-workload
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: test
  namespace: buildagent
spec:
  jobTargetRef:
    template:
      spec:
        initContainers:
        - name: get-token
          image: <image with az cli>
          imagePullPolicy: Always
          command: 
          - powershell
          - -Command
          - |
            az login `
              --service-principal `
              -u *** `
              --federated-token $(cat C:\k8s-token\token) `
              --tenant *** `
              --allow-no-subscriptions

            $azdo_token = az account get-access-token `
              --resource "https://management.core.windows.net/" `
              --query accessToken `
              --output tsv

            $azdo_token > /azdo-token/token
          volumeMounts:
          - name: azdo-token
            mountPath: /azdo-token
          - name: k8s-token
            mountPath: /k8s-token
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
        containers:
        - name: agent
          image: <buildagent image>
          imagePullPolicy: Always
          env:
          - name: AZP_URL
            value: https://dev.azure.com/<organization-name>/
          - name: AZP_POOL
            value: ***
          - name: AZP_TOKEN_FILE
            value: /azdo-token/token
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          volumeMounts:
          - name: azdo-token
            mountPath: /azdo-token
        volumes:
        - name: azdo-token
          emptyDir: {}
        - name: k8s-token
          projected:
            sources:
            # service account with federated azure identity
            - serviceAccountToken:
                path: token
                expirationSeconds: 7200
                audience: api://AzureADTokenExchange
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: azure-pipelines
    metadata:
      poolName: ***
    authenticationRef:
      name: test
```
</details>

**Comment by JorTurFer** [comment]
You need to specify the organization url too in trigger metadata:
```
triggers:
  - type: azure-pipelines
    metadata:
      poolName: ***
      organizationURLFromEnv: AZP_URL
    authenticationRef:
      name: test
```

What error do you see when you set it?
