### ISSUE TITLE
Introduce tolerance setting in ScaleObject

### ISSUE THREAD

**Issue by SpiritZhou** [kedacore/keda#5486]
### Proposal

Introduce a horizontal-pod-autoscaler-tolerance setting in ScaledObject, such as:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: testso
  namespace: test
spec:
  scaleTargetRef:
    name: sut
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        tolerance: 0.5
  triggers:
  - type: cpu
    metadata:
      type: Utilization 
      value: "60"
```
 
We created a ScaledObject with a CPU trigger and set the value to 80%, but the pod did not scale out even though the CPU metric met the target of 80%. We found that the root cause was a globally-configurable tolerance of 0.1 by default, and the pod would only be scaled out if the metric exceeded 88%. However, we believe that this behavior is not very reasonable for the following reasons:
1. If we set the CPU trigger value to 90%, the final value will be 99%, which means the pod will never scale out even if the CPU is fully utilized.
2. This global configuration, horizontal-pod-autoscaler-tolerance, can only be set in the control manager, which is difficult to configure in some environments.
3. This tolerance value is not obvious, and there are no hints in the ScaledObject, which can be misleading to users.

We hope that this configuration can be added to the ScaledObject so that users can configure and check it more easily.
Additionally, we have found it difficult to change the controller manager's configuration from the KEDA side. Would it be possible to request Kubernetes community to improve this behavior in HPA based on these KEDA user cases?

### Is this a feature you are interested in implementing yourself?

Yes
