### ISSUE TITLE
KEDAScalerFailed with metrics-api error requesting metrics endpoint: Get "": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by cesarqdt** [kedacore/keda#5503]
### Report

KEDA stoped working and scaling jobs using the metrics-api scaler. The only message I can see in the events is a warning:
```
0s          Warning   KEDAScalerFailed     scaledjob/worker-dyn-0   error requesting metrics endpoint: Get "http://flask.production.svc.cluster.local:5080/count_queued_datasets": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
0s          Warning   KEDAScalerFailed     scaledjob/worker-dyn-0   error requesting metrics endpoint: Get "http://flask.production.svc.cluster.local:5080/count_queued_datasets": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
0s          Warning   KEDAScalerFailed     scaledjob/worker-dyn-0   error requesting metrics endpoint: Get "http://flask.production.svc.cluster.local:5080/count_queued_datasets": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

The endpoint is reachable and producing a json object which has the fields needed for the metrics-api to work. This has been working with no problemas before yesterday that we started seeing this error.

The metrics-api trigger is defined as follow:
```
  triggers:
  - metadata:
      targetValue: "1"
      url: http://flask.production.svc.cluster.local:5080/count_queued_datasets
      valueLocation: required_pods_pool_0
    type: metrics-api
```

### Expected Behavior

KEDA scale based on the metrics-api.

### Actual Behavior

```
0s          Warning   KEDAScalerFailed     scaledjob/worker-dyn-0   error requesting metrics endpoint: Get "http://flask.production.svc.cluster.local:5080/count_queued_datasets": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
0s          Warning   KEDAScalerFailed     scaledjob/worker-dyn-0   error requesting metrics endpoint: Get "http://flask.production.svc.cluster.local:5080/count_queued_datasets": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
0s          Warning   KEDAScalerFailed     scaledjob/worker-dyn-0   error requesting metrics endpoint: Get "http://flask.production.svc.cluster.local:5080/count_queued_datasets": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Steps to Reproduce the Problem

1. Install KEDA via Helm
2. setup a scaled job with metrics-api, use this trigger:
```
  triggers:
  - metadata:
      targetValue: "1"
      url: http://flask.production.svc.cluster.local:5080/count_queued_datasets
      valueLocation: required_pods_pool_0
    type: metrics-api
``` 
You can mock an api that returns {"required_pods_pool_0": 10}
3. Test and check the error

### Logs from KEDA operator

```
example
```

### KEDA Version

2.13.0

### Kubernetes Version

1.26

### Platform

Microsoft Azure

### Scaler Details

metrics-api
