### ISSUE TITLE
KEDA doesn't validate empty array of triggers

### ISSUE THREAD

**Issue by SpiritZhou** [kedacore/keda#5520]
### Report

When ```triggers``` is set with an empty array in ScaledObject, KEDA doesn't validate this empty value and will create a default HPA with a default 80% averageUtilization CPU resource. This can mislead users.

Here is the yaml example:
```
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
spec:
  scaleTargetRef:
    name: sut
  pollingInterval: 30
  minReplicaCount: 3
  maxReplicaCount: 5
  triggers: []
```

BTW, KEDA will block creation if the value of ```triggers``` is empty.

### Expected Behavior

Block this creation of ScaledObject if ```triggers``` is set with an empty array.

### Actual Behavior

ScaledObject is created normally and a default HPA will also be created.

### Steps to Reproduce the Problem

1. Create an ScaledObject with an empy-array triggers.
2. A CPU-resource HPA will be created soon.

### KEDA Version

2.13.0

### Kubernetes Version

1.27

### Platform

Other

**Comment by vinod827** [comment]
> When `triggers` is set with an empty array in ScaledObject, KEDA doesn't validate this empty value and will create a default HPA with a default 80% averageUtilization CPU resource. This can mislead users.
hmmm....that's interesting. From where this 80% of averageUtilization for CPU is coming in the HPA?

**Comment by SpiritZhou** [comment]
> > When `triggers` is set with an empty array in ScaledObject, KEDA doesn't validate this empty value and will create a default HPA with a default 80% averageUtilization CPU resource. This can mislead users.
> 
> hmmm....that's interesting. From where this 80% of averageUtilization for CPU is coming in the HPA?

It's K8s default behavior. When I create an HPA directly without metrics spec, k8s will create an HPA 80% of averageUtilization for CPU resource.

HPA example:
```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sut
  minReplicas: 1
  maxReplicas: 10
```
