### ISSUE TITLE
KEDA not working with Redis and ScaleType: Job

### ISSUE THREAD

**Issue by vigneshraaj** [kedacore/keda#554]
KEDA not working with Redis and ScaleType: Job. Here is my configuration based on keda-redis sample (https://github.com/patnaikshekhar/KEDA-Redis-Sample) 

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  namespace: keda-redis-test
spec:
  scaleType: job
  jobTargetRef:
    template:
      metadata:
        labels:
          service: keda-redis-test-node
      spec:
        containers:
        - image: patnaikshekhar/keda-redis-node:1
          name: consumer
          env:
          - name: REDIS_HOST
            value: redis-master.keda-redis-test.svc.cluster.local:6379
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password
          - name: LIST_NAME
            value: mylist
  triggers:
  - type: redis
    metadata:
      address: REDIS_HOST # Required host:port format
      password: REDIS_PASSWORD
      listName: mylist # Required
      listLength: "5" # Required
```

## Expected Behavior
When no messages are awaiting processing, no jobs are created.
When a message arrives on the queue, KEDA creates a job.
When the job starts running, it pulls a single message and processes it to completion.
As additional messages arrive, additional jobs are created. Each job processes a single message to completion.

## Actual Behavior
no jobs are getting created

## Steps to Reproduce the Problem

  1. LPUSH mylist message1 message2 message3 message4 message5 message6
  2. kubectl get jobs -n keda-redis-test -w

## Specifications

  - **Version:** *keda-1.1.0*
  - **Platform:** *mac, debian*
  - **Scaler(s):** *redis*
