### ISSUE TITLE
Cannot create HPA object when Deployment has missing ConfigMap (optional: true)

### ISSUE THREAD

**Issue by tomislater** [kedacore/keda#555]
I want to scale my deployment based on RabbitMQ Queue. I cannot do that, because my deployment tries to get envs from non existing `ConfigMap`:

```
apiVersion: apps/v1
kind: Deployment
...
containers:
  ...
envFrom:
  - configMapRef:
    name: {{ template "my-chart.fullname" . }}
  - configMapRef:
    name: {{ .Release.Name }}
    optional: true
  - secretRef:
    name: {{ template "my-chart.name" . }}-database-credentials
    optional: true
...
```

`ScaledObject`:

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject-test
  namespace: my-namespace
  labels:
    deploymentName: my-deployment
spec:
  scaleTargetRef:
    deploymentName: my-deployment
  triggers:
  - type: rabbitmq
    metadata:
      host: RABBITMQ_URL
      queueName: my-queue
      queueLength: "10"
```

`{{ .Release.Name}}`, this one is missing, but it is fine (`optional: true`). Deployment of course works, but for some reason I have got such exception in `keda-operator`.

```
{"level":"error","ts":1579762904.277517,"logger":"controller_scaledobject","msg":"Failed to create new HPA resource","Request.Namespace":"my-namespace","Request.Name":"rabbitmq-scaledobject-test","HPA.Namespace":"my-namespace","HPA.Name":"keda-hpa-my-deployment","error":"error resolving secrets for deployment: error reading config ref &ConfigMapEnvSource{LocalObjectReference:LocalObjectReference{Name:missing-config-map,},Optional:*true,} on namespace my-namespace/: ConfigMap \"missing-config-map\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/ahmed/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/kedacore/keda/pkg/controller/scaledobject.(*ReconcileScaledObject).reconcileDeploymentType\n\tkeda/pkg/controller/scaledobject/scaledobject_controller.go:203\ngithub.com/kedacore/keda/pkg/controller/scaledobject.(*ReconcileScaledObject).Reconcile\n\tkeda/pkg/controller/scaledobject/scaledobject_controller.go:146\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/ahmed/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/ahmed/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/ahmed/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/ahmed/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/ahmed/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/ahmed/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88"}
```

## Expected Behavior
KEDA creates HPA object.

## Actual Behavior
KEDA cannot create HPA object.

## Steps to Reproduce the Problem

  1. Create a deployment in which you try to get envs from missing `ConfigMap` (with `optional: true`)
  2. Create `ScaledObject` object
  3. Keda cannot create HPA, because one `ConfgMap` is missing (but, this is fine, we use it to override some envs if we need to do that). It works with `Deployment`.

## Specifications

  - **Version:** *1.1.0*
  - **Platform:** *AWS; Kubernetes 1.14.8*
  - **Scaler(s):** *RabbitMQ Queue*
