### ISSUE TITLE
Broken link wiki/ScaledObject-spec and kubeval issue

### ISSUE THREAD

**Issue by asears** [kedacore/keda#557]
https://github.com/kedacore/keda/wiki/ScaledObject-spec - the link is broken.

Also kubeval is throwing errors with 404 not found for https://kubernetesjsonschema.dev/master-standalone/scaledobject-keda-v1alpha1.json.

Could someone update (or provide correct links to update and I will if I can get wiki access?)

## Expected Behavior
No 404s

## Actual Behavior
404s

## Steps to Reproduce the Problem

  1. Hit the page
  2. 404s

**Comment by tomkerkhove** [comment]
Wiki is pending deletion: #460

**Comment by asears** [comment]
I ran the kubeval utility on a keda configuration file.  Perhaps this isn't the most recent api version, should be backwards compatible though.

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: my-scaler
  labels:
    app: my-app
    deploymentName: my-app
spec:
  scaleTargetRef:
    deploymentName: my-app
  minReplicaCount: 0 
  maxReplicaCount: 1
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: myqueue
      connection: KEDA_SB_QUEUE_CONNECTIONSTRING
      queueLength: '1'
```
