### ISSUE TITLE
Non default address for redis scaler does not work.

### ISSUE THREAD

**Issue by dustin-decker** [kedacore/keda#560]
When address is provided in the ScaledObject metadata, this error occurs:
```error getting scaler for trigger #0: error parsing redis metadata: no address given. Address should be in the format of host:port```

This is due to a bug in the address parsing.

## Expected Behavior

I expect that the address is read from metadata.

## Actual Behavior

The addressed is parsed as if it was not provided.

## Steps to Reproduce the Problem

  1. Set a metadata address for a redis scaler

## Specifications

  - **Version:** 1.1.0
  - **Platform:** 
  - **Scaler(s):** redis

**Comment by abdennour** [comment]
The issue is still persistent with `image: docker.io/kedacore/keda:1.4.1`

These are the logs of **keda-operator** 

```
"error":"error getting scaler for trigger #0: error parsing redis metadata: no address given or host given. Address should be in the format of host:port or you should provide both host and port",
```

While, this is my scaledObject triggers

 ```sh
  spec:
    cooldownPeriod: 30
    maxReplicaCount: 10
    minReplicaCount: 1
    pollingInterval: 15
    scaleTargetRef:
      deploymentName: queue-worker-academy-laravel
    scaleType: deployment
    triggers:
    - metadata:
        databaseIndex: "0"
        enableTLS: "false"
        address: redis-master.apps-system:6379
        listLength: "3"
        listName: queues:default
      type: redis
```

I tried also to replace `address` field by two fields: `host` and `port`  ( as suggested in logs above)

 ```
  spec:
    cooldownPeriod: 30
    maxReplicaCount: 10
    minReplicaCount: 1
    pollingInterval: 15
    scaleTargetRef:
      deploymentName: queue-worker-academy-laravel
    scaleType: deployment
    triggers:
    - metadata:
        databaseIndex: "0"
        enableTLS: "false"
        host: redis-master.apps-system
        port: "6379"
        listLength: "3"
        listName: queues:default
      type: redis
```

Same error. Nothing work
