### ISSUE TITLE
Scalers for Azure Function Apps running under AKS are not really supported - although the documentation make it seem like they

### ISSUE THREAD

**Issue by SOFSPEEL** [kedacore/keda#5627]
### Report

So have a function app and deploy it to aks via .yaml file using the func tooling as follows:

`func kubernetes deploy --name processtransaction --registry blah --dry-run >deploy-processtransaction.yaml`

Below is an excerpt of the .yaml produced, here are the myriad of problems:

- There is no **timertrigger** scaler support in keda
- There is no durable function/orchestration support, and here I'm making some assumptions, if I was designing scaler support for Function apps, it would have to know whether a long-running orchestration has completed or not. i.e. before you can scale down you have to know whether the orchestration has completed or not.
- The documentation gives you the impression that Azure function apps are supported: https://learn.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda
- The tooling gives you the impression that scaling is supported, i.e. why would the tooling create a **timertrigger** if it wasn't supported by keda (either by built-in or external scaler)
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: procreqs
  labels: {}
spec:
  scaleTargetRef:
    name: procreqs
  triggers:
  - type: cosmosdbtrigger
    metadata:
      connection: CosmosConnection
      leaseContainerName: leases
      leaseContainerPrefix: '%AZURE_FUNCTIONS_ENVIRONMENT%'
      containerName: ProcessingRequest
      databaseName: FundraisingGateway
      leaseDatabaseName: FundraisingGateway
  - type: timertrigger
    metadata:
      schedule: 0 0 0/1 * * *
  - type: timertrigger
    metadata:
      schedule: 0 10/20 * * * *
---

```

### Expected Behavior

1. that scaling is supported under aks, and that orchestrations are part of that support. i.e. I would guess that 90% of fn apps use orchestration.

1. that the documentation is improved and mentions orchestrations and the support (or lack thereof) for orchestrations. Orchestrations to me are a show stopper as basically in my mind scaling doesn't work unless it supports orchestrations.

1. If you really do not support scaling to not have the tooling generate stuff like **timertrigger** as I'm sure this has sent many a deleloper like myself down a black hole either thinking that scaling is supported (when its not) or trying to fix (the unfixable). Note that I may not have made the decision to convert my fn app to run under aks without proper scaler support. 

1. Provide a timeline for when scaling will be supported.

### Actual Behavior

Scaling doesn't work, like for example the **timertrigger** mentioned above and orchestrations, meaning that pods don't scale up or down.

### Steps to Reproduce the Problem

1. Run func on a function app with timertrigger kicking off an orchestration. Deploy it to aks.
2. Watch no scaling will occur, what should happen is that replicas should go to zero, when timer not running, then scale up, then scale down when orchestration completes.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.11.2

### Kubernetes Version

1.26

### Platform

Microsoft Azure

### Scaler Details

timertrigger, cosmostrigger

### Anything else?

If nothing else it would be nice to know if my understanding of how things should work are correct and if correct when/if these concerns will be addressed?
