### ISSUE TITLE
Trying to integrate with Azure Managed Prometheus but getting Unauthorised issue

### ISSUE THREAD

**Issue by KasyapG** [kedacore/keda#5628]
### Report

I followed [Integrate KEDA with your Azure Kubernetes Service cluster](https://learn.microsoft.com/en-us/azure/azure-monitor/containers/integrate-keda) to create scalers.

And while following these we are unable to add the Lable or environments information to Keda.

[attcloud@dev-31467-muelsoft-poc-cmd-vm-01 ~]$ kubectl get pods -n keda
NAME                                                         READY   STATUS    RESTARTS        AGE
keda-admission-58445797d8-jbj47           1/1         Running   0               3d21h
keda-metrics-apiserver-674bb75f7-q6vjl   1/1         Running   0               3d21h
keda-operator-9b754d5b4-gx8wt              1/1        Running   2 (3h43m ago)   3d20h

As per the instructions in the issue resolution https://github.com/kedacore/keda/issues/5203, it says that Keda should have the below environments, however we have already installed Keda 2.10, so can we add these variables and Label values by updating the Keda-operator pod? If not where exactly these details to be updated once the Keda is already installed.

![image](https://github.com/kedacore/keda/assets/88187095/728ecb22-1559-4256-8cc2-f6e581579d0d)

Below is the scaled object I have tried. Please review and add comments if this requires any changes as well.
```
              apiVersion: keda.sh/v1alpha1
              kind: TriggerAuthentication
              metadata:
                name: azure-managed-prometheus-trigger-auth
              spec:
                podIdentity:
                    provider: azure-workload
              ----
              apiVersion: keda.sh/v1alpha1
              kind: ScaledObject
              metadata:
                name: azure-managed-prometheus-scaler
                namespace: 60486a51-7039-4f45-b1be-a0069c86f864
              spec:
                scaleTargetRef:
                  name: test-sample-keda-hpa
                minReplicaCount: 1
                maxReplicaCount: 4
                triggers:
                - type: prometheus
                  metadata:
                    serverAddress: prometheus.monitor.azure.com
                    metricName: access_frequency
                    query: sum((nginx_ingress_controller_requests{service="test-sample-keda-hpa"}))
                    threshold: '1'
              #      activationThreshold: '5.5'
                  authenticationRef:
                    name: azure-managed-prometheus-trigger-auth
```

### Expected Behavior

Keda-operator to have the Workload identity details and connection to be established..

### Actual Behavior

Getting 410 error and the scaledobject shows unknown value as it could not connect.

![image](https://github.com/kedacore/keda/assets/88187095/fb4385cc-c894-48d4-bd48-756d00306217)

### Steps to Reproduce the Problem

See https://learn.microsoft.com/en-us/azure/azure-monitor/containers/integrate-keda

### Logs from KEDA operator

```
2024-03-26T15:02:00Z    ERROR   scale_handler   error getting metric for scaler {"scaledObject.Namespace": "60486a51-7039-4f45-b1be-a0069c86f864", "scaledObject.Name": "azure-managed-prometheus-scaler", "scaler": "prometheusScaler", "error": "prometheus query api returned error. status: 401 response: {\"status\":\"error\",\"errorType\":\"Unauthorized\",\"error\":\"Request does not contain an Authorization Header. RequestId: 61c3955156434f37a4f8c787fff6636f\"}"}

```

### KEDA Version

2.10.0

### Kubernetes Version

1.27

### Platform

Microsoft Azure

### Scaler Details

prometheus
