### ISSUE TITLE
 Enhance Security and Self-Service by Allowing Service Account Specification in Target Namespace for Workload Identity

### ISSUE THREAD

**Issue by abelhoula** [kedacore/keda#5630]
### Proposal

Allow the **TriggerAuthentication** resource in KEDA to specify a service account from the target namespace for workload identity, enhancing security and enabling a self-service model for managing scaling resources.

### Use-Case

In multi-tenant Kubernetes environments, teams often manage their own namespaces and the resources within them, including service accounts. The current approach, where KEDA uses a service account from the keda-operator namespace for scaling operations, presents a challenge for these teams. It limits their ability to apply namespace-specific security policies or manage the lifecycle of these accounts independently. By allowing the specification of a service account in the target namespace, teams would gain the ability to manage their scaling operations more securely and autonomously.

### Is this a feature you are interested in implementing yourself?

Yes

### Anything else?

This proposal aims to strike a balance between security, flexibility, and operational efficiency in managing scaling operations with KEDA. I believe that implementing this feature will benefit many users operating in environments with strict security policies and those who advocate for a more self-service oriented approach to resource management.

**Comment by zroubalik** [comment]
I like this a lot, actually it is the area we want to improve for a long time. I am looking forward to see your take on this.

**Comment by JorTurFer** [comment]
Honestly, I like the idea but AFAIK, the only way to address it at this moment (due to how kubernetes works) it granting permissions to KEDA for requesting service account tokens (because the federations work based on the service account token), which is something I'm strongly against as it allows KEDA to bypass any RBAC in the cluster.

I'm happy with this feature if we find a way to get that token without requiring the permissions for requesting service account tokens by code.

**Comment by JorTurFer** [comment]
> we assumed the operator would create tokens as needed when using Workload Identity.

Yeah, the operator handles token generation for SDKs, but not for k8s. K8s tokens must be handled or provided by users atm. I don't have enough knowledge about this specific topic, so maybe you can help me with this question: Is there any way in k8s to limit the service account token which can be requested? I mean, I know that using RBAC I can create a role like this:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-namespace
  name: keda-role-token-requester
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
```
But this allows to request a token in behalf on any service account within `my-namespace`. This can be safe enough for users with a service account by namespace, but other use cases deploy multiple service accounts into the same namespaces, and this role can potentially allows to KEDA to assume any of them, which can be risky.

I like the idea behind this change, but I want to be 100% sure about the security implications and caveats of it (and we have to document them pretty well if we continue and add this feature)

**Comment by Richard87** [comment]
We could leverage the rules `resourceNames` in the cluster role:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-role-token-requester
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
  resourceNames: ["keda-app"]
```
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources

I Just tested this:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-test
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-app
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-role-token-requester
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
    resourceNames: ["keda-app"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-role-token-requester
subjects:
  - kind: ServiceAccount
    name: keda-test
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-role-token-requester
```

Then to test it, I created a token for the `keda-test` service account `k create token keda-test`, and used that to create tokens for `keda-app`

Works great for keda-app:
```http
POST https://API-SERVER:443/api/v1/namespaces/default/serviceaccounts/keda-app/token
Authorization: Bearer <CREATED TOKEN>
Accept: application/json
Content-Type: application/json

{
  "kind": "TokenRequest",
  "apiVersion": "authentication.k8s.io/v1",
  "spec": {
    "audiences": ["api://AzureADTokenExchange"],
    "expirationSeconds": 3600
  }
}
```

Forbidden for default sa:
```http
POST https://API-SERVER:443/api/v1/namespaces/default/serviceaccounts/default/token
Authorization: Bearer <CREATED TOKEN>
Accept: application/json
Content-Type: application/json

{
  "kind": "TokenRequest",
  "apiVersion": "authentication.k8s.io/v1",
  "spec": {
    "audiences": ["api://AzureADTokenExchange"],
    "expirationSeconds": 3600
  }
}
```

**Comment by JorTurFer** [comment]
I ❤️  the idea! I didn't know that RBAC supports `resourceNames` and it's exactly what I meant. 
We can keep this disabled as default and clearly document the way to enable it (the extra RBAC required) and the possible risks and just bring the power to cluster admins to configure if they will allow this and in which terms.

@tomkerkhove @zroubalik WDYT?

**Comment by JorTurFer** [comment]
any update?

**Comment by Richard87** [comment]
Bump :)

**Comment by Richard87** [comment]
bump

**Comment by JorTurFer** [comment]
I guess that this has been abandoned :(

**Comment by Richard87** [comment]
Yup, looks like it, would have been a great addition for multi tenancy though

**Comment by btwseeu78** [comment]
The problem is the how we want to serve , workload identity comes under pod identity in keda, it is possible to generate token via workload identity even if the service account is in diff namespace as long as keda can generate the satoken against it.
 but the problem is will it be a new auth or it will be under podIdentity.

```
podIdentity:
    provider: gcp
    saName: 
    saNamespace:
    projectId:
    gkeClusterName:

```

similar implementation is used in external-secrets operator. which lets you do it on user end.

will it be appropriate to use like this under podIdentity or be misleading ?

**Comment by btwseeu78** [comment]
Just to add more this how GCP handles it , the main motive here is , users of the keda should manage their own sa,roles and access the resources

**Comment by dronenb** [comment]
**Proposal: let pod-identity providers authenticate as the target workload via a custom-audience `boundServiceAccountToken`**

Building on this issue, here's a security-first design that reuses a primitive KEDA already has (`boundServiceAccountToken`, #6272).

**Problem.** Today the pod-identity providers authenticate to the external identity system as the **KEDA operator's** identity, not the scaled workload's. In a multi-tenant cluster this means every tenant's scaler effectively authenticates as one shared operator identity, which is difficult to isolate, scope, and audit per-tenant. Teams that manage their own namespaces cannot bind cloud/IdP trust to their *own* Kubernetes service account.

**Proposal.** Allow each pod-identity provider to consume a **`boundServiceAccountToken`** for a **target-namespace** service account and use that token to authenticate to the provider via standard **Workload Identity Federation** (i.e. exchange the projected Kubernetes SA token with the external IdP/STS). The external system then sees the **workload's** Kubernetes identity, so federation and trust are scoped per-tenant rather than to the shared operator.

**Prerequisite: `boundServiceAccountToken` needs a caller-selectable audience.** This is required and not currently possible. `GenerateBoundServiceAccountToken` sets only `ExpirationSeconds` in the `TokenRequestSpec`; `Audiences` is left empty, so the minted token carries the kube-apiserver's default audience (e.g. `https://kubernetes.default.svc`). Federation exchanges validate the token's `aud` claim against a configured provider audience, so a default-audience token won't be accepted. The `BoundServiceAccountToken` CRD (currently just `parameter` + `serviceAccountName`) should gain an `audience` field wired into `TokenRequestSpec.Audiences`:

```yaml
boundServiceAccountToken:
- parameter: token
  serviceAccountName: my-workload-sa
  audience: <identity-provider-audience>
```

**Related: consider a per-auth token expiry too.** Secondary to the audience change, the token's expiry is currently a single cluster-wide operator env var (`KEDA_BOUND_SERVICE_ACCOUNT_TOKEN_EXPIRY`, default `1h`, clamped to `1h`–`6h`) applied uniformly to every mint; there is no per-`TriggerAuthentication` control. Federation flows may want shorter, least-privilege token lifetimes per workload, or need to satisfy an IdP's max-lifetime policy. An optional per-auth `expirationSeconds` (wired into the same `TokenRequestSpec`) would round this out, though it's not a hard blocker the way audience is.

**Why this is secure and self-service.** No cluster-wide `serviceaccounts/token` grant is needed. Bound-token minting is authorized by RBAC in the **target namespace**, so a tenant opts in by creating a namespaced `Role` + `RoleBinding` in *their own* namespace, granting the `keda-operator` service account token-creation for *their* SA only:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keda-operator-token-creator
  namespace: my-namespace
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
  resourceNames: ["my-workload-sa"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keda-operator-token-creator-binding
  namespace: my-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-operator-token-creator
subjects:
- kind: ServiceAccount
  name: keda-operator
  namespace: keda
```

This keeps KEDA's default cluster-wide capability at zero (no `allowAllServiceAccountTokenCreation`), confines the blast radius to the tenant's own namespace, and is fully revocable by the tenant. Platform teams that prefer central management can still generate these Roles via the chart's existing `serviceAccountTokenCreationRoles`, but it should not be a prerequisite.

**Suggested sequencing:**

1. Add a caller-selectable `audience` field to `boundServiceAccountToken` (foundational).
2. Wire it into the pod-identity providers so they federate as the target workload's service account.

Happy to help refine or test this.

**Comment by wozniakjan** [comment]
I think this would be a solid addition @dronenb, to either 2.21 (scheduled to be released in September) or 2.22 (December / January).

> Allow each pod-identity provider to consume a boundServiceAccountToken for a target-namespace service account and use that token to authenticate to the provider via standard Workload Identity Federation (i.e. exchange the projected Kubernetes SA token with the external IdP/STS).

how does the pod-identity provider know to federate with the bound token from `boundServiceAccountToken`? Right now users set for example
```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: my-auth
  namespace: my-ns
spec:
  podIdentity:
    provider: gcp
```
this authenticates as keda-operator SA to GCP STS. In the future they will get an option to set both `podIdentity` as well as `boundServiceAccountToken`?
```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:  
  name: my-auth
  namespace: my-ns
spec:
  podIdentity:
    provider: gcp
  boundServiceAccountToken:
  - parameter: token
    serviceAccountName: my-workload-sa
    audience: <identity-provider-audience>
```
which is expected to use GCP STS, but with `my-ns/my-workload-sa` SA and `<identity-provider-audience>`?
