### ISSUE TITLE
Kafka Transactions, commit markers and excludePersistentLag

### ISSUE THREAD

**Issue by smcbn** [kedacore/keda#5675]
### Report

Hi,

I am attempting to use the Keda apache-kafka scaler to scale from 0-1 and from 1-0. CPU Utilization controls from 1+.

I am using Kafka Transactions and exactly once processing in my applications.

Kafka Transactions use a commit marker in the kafka log and it has an offset. Applications cannot consume this offset and cannot commit that offset when all data is processed.

Therefore I am left with a lag of 1 for each partition.

The Keda apache-kafka scaler is detecting this lag and keeping 1 replica running.

The documentation for `excludePersistentLag` suggests that when it is set to `true` it should work this scenario but it is not.

> excludePersistentLag - When set to true, the scaler will exclude partition lag for partitions which current offset is the same as the current offset of the previous polling cycle. This parameter is useful to prevent scaling due to partitions which current offset message is unable to be consumed

Does `excludePersistentLag` only work for scaling from 1+ and not from 1->0?

Scaled Object:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "false"
  name: application
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 30
            type: Pods
            value: 1
          - periodSeconds: 60
            type: Percent
            value: 20
          selectPolicy: Max
          stabilizationWindowSeconds: 300
        scaleUp:
          policies:
          - periodSeconds: 30
            type: Pods
            value: 1
          - periodSeconds: 60
            type: Percent
            value: 20
          selectPolicy: Max
          stabilizationWindowSeconds: 120
    restoreToOriginalReplicaCount: true
  cooldownPeriod: 300
  fallback:
    failureThreshold: 10
    replicas: 1
  idleReplicaCount: 0
  maxReplicaCount: 20
  minReplicaCount: 0
  pollingInterval: 30
  scaleTargetRef:
    apiVersion: apps/v1
    envSourceContainerName: application
    kind: Deployment
    name: application
  triggers:
  - metadata:
      activationLagThreshold: "0"
      allowIdleConsumers: "false"
      bootstrapServers: kafka.namespace.svc.cluster.local:9092
      consumerGroup: app_consumer
      excludePersistentLag: "true"
      lagThreshold: "9999999999"
      limitToPartitionsWithLag: "true"
      offsetResetPolicy: earliest
      scaleToZeroOnInvalidOffset: "false"
      topic: app_input_topic
    name: app_topic_lag
    type: kafka
  - metadata:
      type: Utilization
      value: "20"
    name: cpu_utilisation
    type: cpu
```

I have confirmed that the above scaled object works fine with non-transactional kafka data, but that's because there is no commit marker at the end and therefore no lag.

### Expected Behavior

The apache-kafka scaler should 

> exclude partition lag for partitions which current offset is the same as the current offset of the previous polling cycle

So when an application using kafka transactions cannot consume the commit marker it can then scale back down to 0.

### Actual Behavior

Kafka commit markers remain uncommittable by applications, meaning a lag persists on the partitions. This detected lag persists and the deployment never scaled back down to zero.

### Steps to Reproduce the Problem

1. Create a new/clean topic in the kafka broker
2. Configure the ScaledObject definition above to use that topic
3. Have a kafka producer produce transactional messages onto that kafka topic
4. Watch the deployment scale up due to lag. The deployments kafka consumer will consume that data (it does not need to be a transactional consumer)
5. Once the data is processed check the lag on the partitions for the topic and notice they have a lag of `1`
6. Wait 5-10 minutes and note that the deployment is still at 1 replica.

Once this is reproduced you can show it working with non-transaction data:

1. Create a new/clean topic in the kafka broker
2. Configure the ScaledObject definition above to use that topic
3. Have a kafka producer produce **non-**transactional messages onto that kafka topic
4. Watch the deployment scale up due to lag.
5. Once the data is processed check the lag on the partitions for the topic and notice there is no lag.
6. Wait 5-10 minutes and note that the deployment has scaled down to 0.

### KEDA Version

2.13.0

### Kubernetes Version

None

### Platform

Amazon Web Services

### Scaler Details

apache-kafka
