### ISSUE TITLE
Autoscaling stopped working because of TLS issue

### ISSUE THREAD

**Issue by monotek** [kedacore/keda#5683]
### Report

We use Keda 2.13.1 and CertManager to issue our TLS certs.

We recently noticed that autoscaling of our workloads, via prometheus trigger, stopped working.

The keda created hpa had the following events:

```
the HPA was unable to compute the replica count: unable to get external
metric
postman/s0-prometheus/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name:
postman,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to
fetch metrics from external metrics API: the server was unable to return
a response in the time allotted, but may still be processing the request
(get s0-prometheus.external.metrics.k8s.io)
```

The metric itself could be queried without problems.

The logs of all 3 keda-metrics-apiserver pods had errors like this:

```
W0410 11:34:19.738975 1 logging.go:59] [core] [Channel #1 SubChannel #5] grpc: addrConn.createTransport failed to connect to {Addr: "keda-operator.keda.svc.cluster.local:9666", ServerName: "keda-operator.keda.svc.cluster.local:9666", }. Err: connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of \"x509: invalid signature: parent certificate cannot sign this kind of certificate\" while trying to verify candidate authority certificate \"keda-operator\")"
```

The certifcate created by the cert-manager issuer was valid and was not renewed recently.

After restarting keda-metrics-apiserver deployment it worked again.

### Expected Behavior

Autoscaling works

### Actual Behavior

Autoscaling stopped working

### Steps to Reproduce the Problem

Not sure

### Logs from KEDA operator

```
example
```

### KEDA Version

2.13.1

### Kubernetes Version

1.28

### Platform

Microsoft Azure

### Scaler Details

Prometheus

**Comment by JorTurFer** [comment]
hum... It seems that the certificate isn't hot reloaded on changes. I think that we have to add a watcher for the cert files and restart the server in case of changes :/

**Comment by monotek** [comment]
But im pretty sure the cert did not change. Her the status of the cert:


```
status:
  conditions:
  - lastTransitionTime: "2023-12-04T14:08:02Z"
    message: Certificate is up to date and has not expired
    observedGeneration: 2
    reason: Ready
    status: "True"
    type: Ready
  notAfter: "2025-04-04T06:08:03Z"
  notBefore: "2024-04-04T06:08:03Z"
  renewalTime: "2024-08-03T22:08:03Z"
  revision: 2

```

So the only thing i can think of are pod restarts because of node updates or maybe short k8s api downtime?
