### ISSUE TITLE
Kafka Trigger Not Respecting `pollingInterval`

### ISSUE THREAD

**Issue by r-priyam** [kedacore/keda#5695]
### Report

I have passed the `pollingInterval` to the `Scaled Object` but that's not working	

### Expected Behavior

Keda should check for the lag each 5 seconds in Kafka.

### Actual Behavior

Lag is being checked randomly.

### Steps to Reproduce the Problem

Set up a Kafka scaler based on the below scaled object:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
   ...
  name: foo
spec:
  cooldownPeriod: 300
  fallback:
    failureThreshold: 3
    replicas: 5
  idleReplicaCount: 0
  maxReplicaCount: 5
  minReplicaCount: 1
  pollingInterval: 5
  scaleTargetRef:
    name: foo
  triggers:
  - metadata:
      activationLagThreshold: "1"
      bootstrapServers: kafka-cluster-strimzi-cluster-kafka-bootstrap.infra:9092
      consumerGroup: foo
      lagThreshold: "20"
      topic: ...
    type: kafka
```

### KEDA Version

2.11.2

### Kubernetes Version

1.29

### Platform

Amazon Web Services

### Scaler Details

Kafka
