### ISSUE TITLE
AWS Aurora RDS/Postgres connection issues

### ISSUE THREAD

**Issue by vs-dsva** [kedacore/keda#5723]
### Report

In an EKS cluster the connection to AWS Aurora RDS/Postgres fails with multiple failure scenarios. It either complains of host missing from connection string or or generates sa SASL authentication error.

### Expected Behavior

Scaler connects to the database and polls the table in order to launch a scaled Job

### Actual Behavior

Multiple authentication errors/connection string considered malformed

## Connection string malformed

1. Create a PostgreSQL trigger with the following content:
```yaml
    triggers:
      - metadata:
          connection: "postgresql://<user>:<password>@<host>.<cluster>.eu-west-1.rds.amazonaws.com:5432/<database>?sslmode=disable"
          query: "select count(*) from u_hrm.u_hrmqueue where u_queue_status = 0;"
          targetQueryValue: '1'
        type: postgresql
```
2. Apply the ScaledJob with `kubectl apply -f scaledjob.yaml`
3. The logs will display:
![image](https://github.com/kedacore/keda/assets/72201489/4bb216bb-1056-4388-bb31-26ec48c9fb9f)

## SASL issue
1. Create a PostgreSQL trigger for a ScaledJob with the following content
```yaml
    triggers:
      - metadata:
          userName: <user>
          password: <password>
          host: <host>.<cluster>.eu-west-1.rds.amazonaws.com
          port: "5432"
          dbName: <database>
          sslmode: disable
          query: "select count(*) from u_hrm.u_hrmqueue where u_queue_status = 0;"
          targetQueryValue: '1'
        type: postgresql
```
2. Apply the ScaledJob with `kubectl apply -f scaledjob.yaml`
3. The logs will display:
![image](https://github.com/kedacore/keda/assets/72201489/dff02f16-4f8e-4cf5-81e1-fecd5276d6ab)

### Logs from KEDA operator

```
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
2024-04-23T04:00:30Z	ERROR	Error getting scalers	{"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "ScaledJob": {"name":"uq-hrm-salary-calculation","namespace":"customer1"}, "namespace": "customer1", "name": "uq-hrm-salary-calculation", "reconcileID": "f27fd6ee-41e5-4677-b481-b5b91fd34785", "error": "error establishing postgreSQL connection: failed to connect to `host=<host>.<cluster>.rds.amazonaws.com user=<user> database=<database>`: failed SASL auth (FATAL: password authentication failed for user \"<user>\" (SQLSTATE 28P01))"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledJobReconciler).reconcileScaledJob
	/workspace/controllers/keda/scaledjob_controller.go:194
github.com/kedacore/keda/v2/controllers/keda.(*ScaledJobReconciler).Reconcile
	/workspace/controllers/keda/scaledjob_controller.go:148
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
2024-04-23T04:00:30Z	ERROR	Failed to ensure ScaledJob is correctly created	{"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "ScaledJob": {"name":"uq-hrm-salary-calculation","namespace":"customer1"}, "namespace": "customer1", "name": "uq-hrm-salary-calculation", "reconcileID": "f27fd6ee-41e5-4677-b481-b5b91fd34785", "error": "error establishing postgreSQL connection: failed to connect to `host=<host>.<cluster>.eu-west-1.rds.amazonaws.com user=<user> database=<database>`: failed SASL auth (FATAL: password authentication failed for user \"<user>\" (SQLSTATE 28P01))"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledJobReconciler).Reconcile
	/workspace/controllers/keda/scaledjob_controller.go:150
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
2024-04-23T04:00:30Z	ERROR	Reconciler error	{"controller": "scaledjob", "controllerGroup": "keda.sh", "controllerKind": "ScaledJob", "ScaledJob": {"name":"uq-hrm-salary-calculation","namespace":"customer1"}, "namespace": "customer1", "name": "uq-hrm-salary-calculation", "reconcileID": "f27fd6ee-41e5-4677-b481-b5b91fd34785", "error": "error establishing postgreSQL connection: failed to connect to `host=<host>.<cluster>.eu-west-1.rds.amazonaws.com user=<user> database=<database>`: failed SASL auth (FATAL: password authentication failed for user \"u932c32\" (SQLSTATE 28P01))"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
```

### KEDA Version

2.13.1

### Kubernetes Version

1.29

### Platform

Amazon Web Services

### Scaler Details

PostgreSQL

### Anything else?

AWS Aurora RDS is using Postgres 16.1
