### ISSUE TITLE
ScaledJobs labels are not being applied to child jobs

### ISSUE THREAD

**Issue by Riverlution** [kedacore/keda#5739]
### Report

I have a number of ScaledJobs that I want to spawn jobs from with the same label.
The documentation for ScaledJobs says I can achieve this by adding a label to the scaledjob definition:
"# Optional. ScaledJob labels are applied to child Jobs"

When I do this, I'm not seeing this label applied to the jobs spawned from the ScaledJob. The labels are instead applied to the Pods under the job.

Not sure if this is intentional and the documentation is incorrect, or if the documentation is incorrect and the intent was to have Pods inherit these labels. 

Is this something that can be addressed?

### Expected Behavior

The labels applied to a ScaledJob are applied to child jobs as described in the documentation

### Actual Behavior

The labels applied to a ScaledJob are applied to child jobs' pods.

### Steps to Reproduce the Problem

1.Create a ScaledJob with a label defined. 

### KEDA Version

2.13.1

### Kubernetes Version

< 1.28

### Platform

Microsoft Azure

### Scaler Details

Redis

**Comment by JorTurFer** [comment]
Hello,
I can't reproduce the issue, when I set this ScaledJob:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    k8slens-edit-resource-version: v1alpha1
    test: jorge
```
The created jobs have the labels:
```yaml
kind: Job
metadata:
  labels:
    app.kubernetes.io/managed-by: keda-operator
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test
    app.kubernetes.io/version: main
    k8slens-edit-resource-version: v1alpha1
    scaledjob.keda.sh/name: test
    test: jorge
```
