### ISSUE TITLE
GCP Pub/Sub Scaler reports negative metric values

### ISSUE THREAD

**Issue by rc-bryanlinebaugh** [kedacore/keda#5774]
### Report

We have configured the GCP Pub/Sub Scaler to scale our deployments based on the reported "SubscriptionSize" of the configured Pub/Sub Subscription. We have experienced frequent reporting of **negative** metric values by the underlying `HorizontalPodAutoscaler` resource for each `ScaledObject`.

The reported negative values seems to be having the adverse affect of incorrectly scaling down our deployments.

Examples:

<img width="206" alt="image" src="https://github.com/kedacore/keda/assets/105881954/01e0cc0b-9012-44cb-9b66-fb7b48330e32">

```bash
NAME↑                                                  REFERENCE                                                TARGETS                              MINPODS                  MAXPODS                   REPLICAS                   AGE
keda-hpa-gcp-log-ingest-go-foo1234567                  Deployment/gcp-log-ingest-go-foo1234567                  -3795005m/50 (avg)                   50                       2500                      1194                       12d
```

Scaler Config:

```YAML
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 600
            type: Percent
            value: 5
          stabilizationWindowSeconds: 600
        scaleUp:
          policies:
          - periodSeconds: 60
            type: Percent
            value: 100
          stabilizationWindowSeconds: 100
  cooldownPeriod: 300
  fallback:
    failureThreshold: 5
    replicas: 200
  maxReplicaCount: 2500
  minReplicaCount: 50
  pollingInterval: 10
  scaleTargetRef:
    name: ...
  triggers:
  - authenticationRef:
      name: ...
    metadata:
      activationValue: "0"
      aggregation: sum
      mode: SubscriptionSize
      subscriptionName: ...
      value: "50"
    type: gcp-pubsub
```

### Expected Behavior

There should not be any negative values reported for the `HorizontalPodAutoscaler` metric.

### Actual Behavior

Observed the `HorizontalPodAutoscaler` consistently reporting negative values.

### Steps to Reproduce the Problem

1. Create a GCP Pub/Sub Topic and Subscription.
2. Register GCP Pub/Sub Scaler with a similar configuration.
3. Consistently publish messages to the Subscription.
4. Observe metric values reported by the configured HPA resource.

### KEDA Version

2.13.0

### Kubernetes Version

1.28

### Platform

Amazon Web Services

### Scaler Details

GCP Pub/Sub
