### ISSUE TITLE
Github Runner Scaler doesn't trigger until all job environments are approved

### ISSUE THREAD

**Issue by jamesgrogantech** [kedacore/keda#5788]
### Report

I am using GitHub environments for deployment with rules setup to protect the GitHub actions from running the deployment to production without approval. I am using the GitHub Runner scaler to trigger a self hosted runner to start. The trigger is only sent once the approval has gone ahead despite the development environment not having any approval rules. 

These are two separate jobs like this:

```yaml
on:
  workflow_dispatch:

jobs:
  migrate-dev:
    runs-on: self-hosted
    environment: dev <- This environment has no protection rules
    steps: .....
  migrate-prod:
    runs-on: self-hosted
    environment: production <- This environment requires approval before deployment
    steps: .....
```

I am running my self hosted runner on an Azure Container App Job which makes use of the KEDA Github Runner Scaler

### Expected Behavior

I expect the first job (on the development environment) to trigger immediately and then the production environment to wait until it's been approved before triggering.

### Actual Behavior

The trigger isn't happening for either jobs until the approval rule has been satisfied.

### Steps to Reproduce the Problem

1. Setup a GitHub Action with two jobs.
2. Setup two GitHub environments one with protection rules one without.
3. Assign the environments to the GitHub Action jobs
4. Trigger the action
5. Wait for the trigger - it won't come through
6. Approve one of the jobs - the trigger will start

### Logs from KEDA operator

```
N/A
```

### KEDA Version

2.12.1

### Kubernetes Version

None

### Platform

Microsoft Azure

### Scaler Details

Github Runner Scaler
