### ISSUE TITLE
Could not find stackdriver metric with query fetch pubsub_subscription - Google Cloud Platform‎ Pub/Sub

### ISSUE THREAD

**Issue by rcng6514** [kedacore/keda#5855]
### Report

We seem to have the same problem as #5452 we believe since upgrading to 2.14.0. Infrequently Keda throwing that it cannot find a metric that matches that filter. GCP audit logs show no failed auth or perms issues.
In a 7 day window we observed 863 instances of this error

### Expected Behavior

Metric query returned consistently

### Actual Behavior

Metric query inconsistently returned with the following error: `could not find stackdriver metric with query fetch pubsub_subscription`

### Steps to Reproduce the Problem

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    meta.helm.sh/release-name: <name>
    meta.helm.sh/release-namespace: <namespace>
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: <name>
    helm.toolkit.fluxcd.io/namespace: <namespace>
    scaledobject.keda.sh/name: <name>
  name: <name>
  namespace: <namespace>
spec:
  cooldownPeriod: 10
  maxReplicaCount: 3
  minReplicaCount: 1
  pollingInterval: 1
  scaleTargetRef:
    name: <target>
  triggers:
  - authenticationRef:
      name: <auth>
    metadata:
      mode: SubscriptionSize
      subscriptionName: projects/<project>/subscriptions/<sub>
      value: "50000"
    type: gcp-pubsub
```

### Logs from KEDA operator

```
2024-05-30T18:04:43Z	ERROR	gcp_pub_sub_scaler	error getting metric	{"type": "ScaledObject", "namespace": "blah", "name": "blah", "metricType": "pubsub.googleapis.com/subscription/num_undelivered_messages", "error": "could not find stackdriver metric with query fetch pubsub_subscription | metric 'pubsub.googleapis.com/subscription/num_undelivered_messages' | filter (resource.project_id == 'blah' && resource.subscription_id == 'blah') | within 2m"}
```

### KEDA Version

2.14.0

### Kubernetes Version

1.28

### Platform

Google Cloud

### Scaler Details

Google Cloud Platform‎ Pub/Sub

### Anything else?

Poll interval if reduced to 5 seconds reduces errors seen but does not eliminate them
