### ISSUE TITLE
Scale applications based on a PostgreSQL

### ISSUE THREAD

**Issue by nkartem** [kedacore/keda#5862]
### Report

**error establishing postgreSQL connection: failed to connect to `host=postgresql.dev.svc.cluster.local user=postgres database=keda`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))**

```
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzcw== # Base64 encoded value of 'pass'
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app: postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: keda
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgredb
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:6.18
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
          volumeMounts:
            - name: pgadmindata
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmindata
          emptyDir: {}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: postgresql-scaledobject
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: whisper-deployment
  pollingInterval: 60    # Check metrics every 60 seconds
  cooldownPeriod:  30    # Wait 30 seconds after scaling down
  maxReplicaCount: 12    # Maximum of 12 replicas
  triggers:
  - type: postgresql
    metadata:
      userName: "postgres"
      passwordFromEnv: POSTGRES_PASSWORD
      host: postgresql.dev.svc.cluster.local
      port: "5432"
      dbName: keda
      sslmode: disable
      query: "SELECT count(*) FROM task_instance WHERE status='pending'"
      targetQueryValue: "10"
      activationTargetValue: "4" # Start scaling when there are at least 4 pending tasks
```

If I connect whith PgAdmin all is good.
![image](https://github.com/kedacore/keda/assets/16717725/103d689e-a6bb-4810-b7a9-dfcf4624f6f6)

### Expected Behavior

All must work

### Actual Behavior

I deploy all objects in k8s (EKS) only  ScaledObject  postgresql-scaledobject not working
![image](https://github.com/kedacore/keda/assets/16717725/b470fc1d-650a-447b-95f1-cd9d75c50630)
objects

### Steps to Reproduce the Problem

1.-
2.-
3.-

### Logs from KEDA operator

```
example
```

### KEDA Version

2.14.0

### Kubernetes Version

1.29

### Platform

Amazon Web Services
