### ISSUE TITLE
Allow nested metadata properties

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#590]
Creating as this came up as a request during a standup.  Some scalers like Azure Monitor may require a number of metadata options to configure, and today we require metadata be a flat list:

(hypothetical example)
```yaml
metadata:
  connectionName:
  connectionType:
  connectionSubscription:
  metricType:
  metricName:
  metricThreshold:
```

We could consider allowing nesting or other ways to more easily define like:

```yaml
metadata:
  connection:
    name:
    type:
    subscription:
  metric:
    type:
    name:
    threshold:
```

Open for discussion and upvotes 👍
