### ISSUE TITLE
An unreachable external scaler makes another scaler's metrics unavailable

### ISSUE THREAD

**Issue by tlorreyte** [kedacore/keda#5914]
### Report

When several scalers are configured, one of which is external and unreachable, the others no longer supply their metrics despite their availability. 

### Expected Behavior

I think it would be preferable to have the scalers' metrics available to ensure a fallback case if ever the external scaler is broken or no longer responds.

### Actual Behavior

For example, with a scaleObject like this one: 

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {scaled-object-name}
  namespace: {scaled-object-namespace}
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
            - periodSeconds: 15
              type: Percent
              value: 100
          stabilizationWindowSeconds: 120
        scaleUp:
          stabilizationWindowSeconds: 60
  maxReplicaCount: 10
  minReplicaCount: 1
  pollingInterval: 15
  scaleTargetRef:
    apiVersion: {apiVersion-of-target-resource}
    kind: {kind-of-target-resource}
    name: {name-of-target-resource}
  triggers:
    - metadata:
        scalerAddress: 'external-scaler.svc.cluster.local.:9090'
      type: external
    - metadata:
        activationThreshold: '0'
        query: >-
          avg(rate(business_metric{container="{container-of-target-resource}"}[30s]))
        serverAddress: >-
          http://prometheus:9090
        threshold: '10'
      metricType: Value
      type: prometheus
    - metadata:
        value: '80'
      metricType: Utilization
      type: cpu
```

If `external-scaler.svc.cluster.local.:9090` is unreachable, prometheus scaler become unactive in the hpa pov with a warning event : 

```
  Warning  FailedGetExternalMetric   horizontal-pod-autoscaler  unable to get external metric {container-of-target-resource}/s0-prometheus/&LabelSelector{MatchLabels:map[string[]string{scaledobject.keda.sh/name: {scaledObject-name},},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: rpc error: code = Unknown desc = error when getting metric values metric:s0-prometheus encountered error
  Warning  FailedComputeMetricsReplicas  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 2), first error is: failed to get s0-prometheus external metric value: failed to get external metric s0-prometheus: unable to get external metric {scaledObject-name}/s0-prometheus/&LabelSelector{MatchLabels:map[string[]string{scaledobject.keda.sh/name: {scaledObject-name},},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: rpc error: code = Unknown desc = error when getting metric values metric:s0-prometheus encountered error
```

### Steps to Reproduce the Problem

1. Have a scaledObject with an external scaler and a prometheus scaler for ex
2. Make unreachable the external one

### Logs from KEDA operator

From Keda Operator, the logs indicate that the external scaler is unreachable. What's normal.
```
{"level":"error","ts":"2024-06-27T08:04:28Z","logger":"external_scaler","msg":"error","type":"ScaledObject","namespace":"{scaledObject-namespace}","name":"{scaledObject-name}","error":"rpc error: code = Unavailable desc = last connection error: connection error: desc = \"transport: Error while dialing: dial tcp: lookup external-scaler.svc.cluster.local. on x.x.x.x:53: no such host\"","stacktrace":"github.com/kedacore/keda/v2/pkg/scalers.(*externalScaler).GetMetricSpecForScaling\n\t/workspace/pkg/scalers/external_scaler.go:175\ngithub.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricSpecForScalingForScaler\n\t/workspace/pkg/scaling/cache/scalers_cache.go:113\ngithub.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics\n\t/workspace/pkg/scaling/scale_handler.go:480\ngithub.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics\n\t/workspace/pkg/metricsservice/server.go:48\ngithub.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler.func1\n\t/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:106\ngithub.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).Start.(*ServerMetrics).UnaryServerInterceptor.UnaryServerInterceptor.func6\n\t/workspace/vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/server.go:22\ngithub.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler\n\t/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:108\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/workspace/vendor/google.golang.org/grpc/server.go:1369\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/workspace/vendor/google.golang.org/grpc/server.go:1780\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1\n\t/workspace/vendor/google.golang.org/grpc/server.go:1019"}
{"level":"error","ts":"2024-06-27T08:04:28Z","logger":"scale_handler","msg":"error getting metric spec for the scaler","scaledObject.Namespace":"{scaledObject-namespace}","scaledObject.Name":"{scaledObject-name}","scaler":"externalScaler","error":"got empty metric spec","stacktrace":"github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics\n\t/workspace/pkg/scaling/scale_handler.go:483\ngithub.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics\n\t/workspace/pkg/metricsservice/server.go:48\ngithub.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler.func1\n\t/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:106\ngithub.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).Start.(*ServerMetrics).UnaryServerInterceptor.UnaryServerInterceptor.func6\n\t/workspace/vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/server.go:22\ngithub.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler\n\t/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:108\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/workspace/vendor/google.golang.org/grpc/server.go:1369\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/workspace/vendor/google.golang.org/grpc/server.go:1780\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1\n\t/workspace/vendor/google.golang.org/grpc/server.go:1019"}

```

### KEDA Version

2.14.0

### Kubernetes Version

1.29

### Platform

Amazon Web Services

### Scaler Details

External + Prometheus + cpu

### Anything else?

I can work on a PR, if it's relevant.
