### ISSUE TITLE
TriggerAuthentication : AWS Secret Manager should allow to pass "Secret key" as one of the parameter under secrets

### ISSUE THREAD

**Issue by Tejasvihuded** [kedacore/keda#5940]
### Report

There is no way I can pass "**Secret key**" under "**awsSecretManager.secrets**" section. When we actually create secret in AWS secret Manager it will have "Secret name" under which we will have "Key/Value" pairs.
**For Example:** 

"Secret name" can be "keda-int" under which we will have "Key/Value" pairs ,something like.

Secret key | Secret value
----------------------------
userName | dummyuser
password  | dummypass

For for above if I want to create "TriggerAuthentication",I want new parameter to pass **{aws-secret-key}**,else there is no way we can say which Secret Key to use for each parameter

```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: sample
spec:
    podIdentity:             
      provider: aws               
    region: us-east-2                                                 
    secrets:                                                              
    - parameter: userName
      name: keda-int
      *key: {aws-secret-name}*
    - parameter: password
      name: keda-int   
      *key: {aws-secret-name}*

```

### Expected Behavior

Need new "key" parameter under secrets section

### Actual Behavior

There is no way we can pass "Secret Key" today under "Secret Name"

### Steps to Reproduce the Problem

NA

### Logs from KEDA operator

NA

### KEDA Version

2.13.0

### Kubernetes Version

1.28

### Platform

Amazon Web Services

### Scaler Details

postgresql
