### ISSUE TITLE
Add support for Argo Rollouts

### ISSUE THREAD

**Issue by iremmats** [kedacore/keda#595]
My organization is using Argo Rollouts to allow us to do Canary and Blue Green deployments GitOps style. I would like to be able to use Keda in combination with this.

### Use-Case

Allow Keda to create HPAs for other resources than just Deployments. Example of how the ScaledObject could look like.

```yaml 
scaleTargetRef:
    deploymentName: order-processor
    apiVersion: argoproj.io
    kind: Rollout
```
