### ISSUE TITLE
ScaledJob with minReplicaCount to 0 with Azure Pipeline

### ISSUE THREAD

**Issue by jbatmalle** [kedacore/keda#5988]
### Report

Hi,
I want to trigger a job (azure pipeline agent) for each azure pipeline job.

If I set replicaMinCount to 0 it's not work. Azure pipelines job stopped immedialy because it don't found an agent.

But if I set replicaMinCount to 1 then I see 1 pod (normal) and another after few seconds. The first pod take the job.

I don't found a workarround 

My scaledJob :
```  
   apiVersion: keda.sh/v1alpha1
   kind: ScaledJob
   metadata:
     name: azure-agents-scaledjob
     namespace: azsh-agents
   spec:
     triggers:
       - type: azure-pipelines
         metadata:
           poolID: "{{ .Values.secret.data.AZP_POOL_ID_VALUE | b64dec }}"
           organizationURLFromEnv: "AZP_URL"
           personalAccessTokenFromEnv: "AZP_TOKEN"
         authenticationRef:
           name: azsh-agents-trigger-auth
     jobTargetRef:
       activeDeadlineSeconds: 3600
       backOffLimit: 0  
       template:
         spec:
           restartPolicy: Never
           containers:
             - name: azure-pipelines-agent
               image: <myimage>
               imagePullPolicy: always
               env:
                 - name: AZP_URL
                   valueFrom:
                     secretKeyRef:
                       name: {{ .Values.secret.name }}
                       key: AZP_URL
                 - name: AZP_TOKEN
                   valueFrom:
                     secretKeyRef:
                       name: {{ .Values.secret.name }}
                       key: AZP_TOKEN
                 - name: AZP_POOL
                   valueFrom:
                     secretKeyRef:
                       name: {{ .Values.secret.name }}
                       key: AZP_POOL_NAME
               volumeMounts:
                 - mountPath: /var/run/docker.sock
                   name: docker-volume
           volumes:
             - name: docker-volume
               hostPath:
                 path: /var/run/docker.sock
     pollingInterval: 10
     successfulJobsHistoryLimit: 5
     failedJobsHistoryLimit: 5
     minReplicaCount: 0
     maxReplicaCount: 6
```

My Trigger authentication
``` 
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azsh-agents-trigger-auth
  namespace: azsh-agents
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: {{ .Values.secret.name }}
      key: AZP_TOKEN
    - parameter: organizationURL
      name: {{ .Values.secret.name }}
      key: AZP_URL
```  

My scaledJob in k8s
![image](https://github.com/user-attachments/assets/fbe68c0a-fb24-402e-a0ef-cdaaaffb4f4a)

The azure Pipeline Error
![image](https://github.com/user-attachments/assets/8d9c68bc-5285-413f-ab26-3e869dac2bd6)

Keda operator logs errors
![image](https://github.com/user-attachments/assets/5596874a-c19e-4cff-944d-ca5c6ec4a364)

Pool agent is empty

### Expected Behavior

I want to trigger a job for each azure pipeline job. 

### Actual Behavior

Jobs are not triggered

### Steps to Reproduce the Problem

1. Create scaled job and trigger authentication (see report bug)
2. Create a job in AZure pipeline
3. Job fail because it was not found an agent

### Logs from KEDA operator

![image](https://github.com/user-attachments/assets/8de37594-407b-49eb-96f0-733f0671aac5)
![image](https://github.com/user-attachments/assets/19703e60-900f-485b-9405-9bc49ad54419)

### KEDA Version

2.14.0

### Kubernetes Version

1.29

### Platform

Amazon Web Services

### Scaler Details

Azure Pipelines
