### ISSUE TITLE
create ScaledObject when triggers type is prometheus metricType is Value err

### ISSUE THREAD

**Issue by LY-today** [kedacore/keda#6045]
### Report

when triggers type is prometheus， metricType is Value，create ScaledObject ，keda-operator is err
`2024-08-07T09:33:45Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"my-helm-demo","namespace":"crane-system"}, "namespace": "crane-system", "name": "my-helm-demo", "reconcileID": "f750f79f-5a1b-4fc9-88d2-b136a11b65ff", "error": "HorizontalPodAutoscaler.autoscaling \"keda-hpa-my-helm-demo\" is invalid: spec.metrics[0].external.target.type: Invalid value: \"value\": must be either Utilization, Value, or AverageValue"}`

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-helm-demo
  namespace: crane-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-helm-demo
  pollingInterval: 15
  minReplicaCount: 2
  maxReplicaCount: 50
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent 
              value: 100
              periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 500
              periodSeconds: 15
  triggers:
    - type: prometheus
      metricType: Value
      metadata:
        serverAddress: xxx
        metricName: portrait_pod_cpu_predict_compression_all_num
        query: portrait_pod_cpu_predict_compression_all_num{}
        threshold: "50"
```

### Expected Behavior

hpa resources can be created normally

### Actual Behavior

hpa not create
```
Name:         my-helm-demo
Namespace:    crane-system
Labels:       scaledobject.keda.sh/name=my-helm-demo
Annotations:  <none>
API Version:  keda.sh/v1alpha1
Kind:         ScaledObject
Metadata:
  Creation Timestamp:  2024-08-07T09:33:24Z
  Finalizers:
    finalizer.keda.sh
  Generation:        1
  Resource Version:  24908
  UID:               0d11f0d0-216e-4696-be18-51a49cad0bd3
Spec:
  Advanced:
    Horizontal Pod Autoscaler Config:
      Behavior:
        Scale Down:
          Policies:
            Period Seconds:              15
            Type:                        Percent
            Value:                       100
          Stabilization Window Seconds:  0
        Scale Up:
          Policies:
            Period Seconds:              15
            Type:                        Percent
            Value:                       500
          Stabilization Window Seconds:  0
  Max Replica Count:                     50
  Min Replica Count:                     2
  Polling Interval:                      15
  Scale Target Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         my-helm-demo
  Triggers:
    Metadata:
      Metric Name:     portrait_pod_cpu_predict_compression_all_num
      Query:           portrait_pod_cpu_predict_compression_all_num{}
      Server Address:  xxxx
      Threshold:       50
    Metric Type:       Value
    Type:              prometheus
Status:
  Conditions:
    Message:  Failed to ensure HPA is correctly created for ScaledObject
    Reason:   ScaledObjectCheckFailed
    Status:   False
    Type:     Ready
    Message:  ScaledObject check failed
    Reason:   UnkownState
    Status:   Unknown
    Type:     Active
    Status:   Unknown
    Type:     Fallback
  External Metric Names:
    s0-prometheus-portrait_pod_cpu_predict_compression_all_num
  Original Replica Count:  8
  Scale Target GVKR:
    Group:            apps
    Kind:             Deployment
    Resource:         deployments
    Version:          v1
  Scale Target Kind:  apps/v1.Deployment
Events:
  Type     Reason                   Age                   From           Message
  ----     ------                   ----                  ----           -------
  Warning  ScaledObjectCheckFailed  59s (x17 over 6m27s)  keda-operator  Failed to ensure HPA is correctly created for ScaledObject
```

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
2024-08-07T09:33:45Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"my-helm-demo","namespace":"crane-system"}, "namespace": "crane-system", "name": "my-helm-demo", "reconcileID": "f750f79f-5a1b-4fc9-88d2-b136a11b65ff", "error": "HorizontalPodAutoscaler.autoscaling \"keda-hpa-my-helm-demo\" is invalid: spec.metrics[0].external.target.type: Invalid value: \"value\": must be either Utilization, Value, or AverageValue"}
```

### KEDA Version

< 2.11.0

### Kubernetes Version

< 1.28

### Platform

None

### Scaler Details

prometheus

### Anything else?

$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.21.1
WARNING: version difference between client (1.29) and server (1.21) exceeds the supported minor version skew of +/-1

kubectl apply --server-side -f https://github.com/kedacore/keda/releases/download/v2.8.0/keda-2.8.0.yaml
