### ISSUE TITLE
Extend Prometheus Scaler to populate the namespace field by reference 

### ISSUE THREAD

**Issue by ZeidH** [kedacore/keda#6048]
### Proposal

I would like to be able to reference the namespace that the ScaledJob or ScaledObject is currently deployed in with the Prometheus Scaler's namespace field. 

So that instead of:
```
triggers:
- type: prometheus
  metadata:
    ...
    namespace: example-namespace  # for namespaced queries, eg. Thanos
```  
Do something more dynamic like:

```
    ...
    namespace: 
      fieldRef: metadata.namespace
```
  

### Use-Case

For us the namespace field is required as we use thanos-querier as our metric source, similar to many OpenShift users. 

Having the namespace field referenced would save us a lot of hassle with kustomize replacements and post-sync jobs to manage that namespace field automatically.

### Is this a feature you are interested in implementing yourself?

Maybe
