### ISSUE TITLE
Unable to scale jobs with Keda

### ISSUE THREAD

**Issue by VenkateshSrini** [kedacore/keda#606]
Hi,
I'm trying to scale job using KEDA. The entire code is at https://github.com/VenkateshSrini/sample-netcore-keda-rabbitmq. I'm able to get the rabbit mq installed in default namespace. Also I was able to deploy the scaledobject and publisher which is a kubernetes job. My observation is as below

## Expected Behavior
1) First when I run the scaled object definition creation that is https://github.com/VenkateshSrini/sample-netcore-keda-rabbitmq/blob/master/deploy/deploy-consumer-kedajob.yaml I expect the jobs to be created
2) When the publisher is run, I expect the scaled object to bring the job and execute. 

## Actual Behavior
Neither of the above is happening

## Steps to Reproduce the Problem

  1. Install Rabbit MQ in default cluster
  2. Install Keda in using the KUBCTL install (not the helm).
  3. First deploy the yaml file https://github.com/VenkateshSrini/sample-netcore-keda-rabbitmq/blob/master/deploy/deploy-consumer-kedajob.yaml
4. Then deploy https://github.com/VenkateshSrini/sample-netcore-keda-rabbitmq/blob/master/deploy/deploy-publisher-job.yaml

## Specifications

  - **KEDA Version:** *1.1*
  - **Platform & Version:** *Docker for windows stable latest*
  - **Kubernetes Version:** *version of kubernetes that comes with docker*
  - **Scaler(s):** *rabbitmq*

**Comment by tomislater** [comment]
What do you see in logs?

**Comment by VenkateshSrini** [comment]
Could you please see the yaml files and let me know all if fine. I will try to post the logs here.

**Comment by tomislater** [comment]
I had a similar problem with KEDA and RabbitMQ. But with deployments, not with jobs :/ But, it might be related...

I have a deployment with a consumer. This consumer should create a queue in Rabbit. BUT If `ScaledObject` is being creating too fast ;) KEDA will scale the deployment to `0` (delete the pod) and this deployment even cannot create the queue in Rabbit.

I use helm, so I just added to `ScaledObject`:
```
annotations:
    "helm.sh/hook": post-install,post-upgrade
```

and it has resolved my issue.

Maybe there is something wrong with this scaler? I think, it should not scale to `0` if the queue does not exist.

**Comment by VenkateshSrini** [comment]
> Could you please see the yaml files and let me know all if fine. I will try to post the logs here.

The POD is not getting created at all. I'm afraid it gets removed so fast

**Comment by VenkateshSrini** [comment]
> I had a similar problem with KEDA and RabbitMQ. But with deployments, not with jobs :/ But, it might be related...
> 
> I have a deployment with a consumer. This consumer should create a queue in Rabbit. BUT If `ScaledObject` is being creating too fast ;) KEDA will scale the deployment to `0` (delete the pod) and then this deployment cannot create the queue in Rabbit.
> 
> I use helm, so I just added to `ScaledObject`:
> 
> ```
> annotations:
>     "helm.sh/hook": post-install,post-upgrade
> ```
> 
> and it has resolved my issue.
> 
> Maybe there is something wrong with this scaler? I think, it should not scale replicas to `0` if the queue does not exist.

Where do I add this. In the scaledobject CRD provided by keda or do my deployment.yaml.

**Comment by VenkateshSrini** [comment]
My scaledjob job yaml looks like below

> apiVersion: keda.k8s.io/v1alpha1
> kind: ScaledObject
> metadata:
>   name: rabbitmq-consumer
>   namespace: default
>   labels:
>     deploymentName: rabbitmq-consumer
> spec:
>   scaleType: job
>   pollingInterval: 5   # Optional. Default: 30 seconds
>   cooldownPeriod: 30   # Optional. Default: 300 seconds
>   maxReplicaCount: 30  # Optional. Default: 100
>   completions: 1
>   jobTargetRef:
>     parallelism: 10
>     activeDeadlineSeconds: 3600
>     template:
>       spec:
>         containers:
>         - name: rabbitmq-consumer
>           image: venkateshsrini3/receivejob
>           imagePullPolicy: Always
>           args:
>           - 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672'
>         restartPolicy: Never  
>   triggers:
>   - type: rabbitmq
>     metadata:
>       queueName: hello
>       host: 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672'
>       queueLength  : '5'

It seems to attach itself to the rabbitmq for some reason. to check the solution offered by @tomislater , I first went head and first deployed the publisher, this created all the required queue and also put in a data packets. Then I tried to create the consumer (scaled object). But then the expectation is since every thing is ready the consumer should start working. But that did not happen. No Jobs or pods are created. Can you please help ? The code for receive is at **https://github.com/VenkateshSrini/sample-netcore-keda-rabbitmq/blob/master/Receive/Receive.cs**

Is it a code issue or Yaml issue, please help me to find out

**Comment by VenkateshSrini** [comment]
@tomislater ,
I have changed the deployment as per your recommendation I have changed the scaledobject definition. The yaml now looks as below

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer
  namespace: default
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  labels:
    deploymentName: rabbitmq-consumer
spec:
  scaleType: job
  pollingInterval: 5   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  maxReplicaCount: 30  # Optional. Default: 100
  completions: 1
  jobTargetRef:
    parallelism: 10
    activeDeadlineSeconds: 3600
    template:
      spec:
        containers:
        - name: rabbitmq-consumer
          image: venkateshsrini3/receivejob
          imagePullPolicy: Always
          args:
          - 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672'
        restartPolicy: Never  
  triggers:
  - type: rabbitmq
    metadata:
      queueName: hello
      host: 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672'
      queueLength  : '5'
```
But that also did not work.

**Comment by balchua** [comment]
@VenkateshSrini are the queues created on the fly?

Can you also help get the logs from the keda operator?

**Comment by VenkateshSrini** [comment]
> @VenkateshSrini are the queues created on the fly?
> [Reply] Ideally yes. But to see isolate and see if that is causing the issue, I first created the queue with out any packets and then deployed the application. Even then the binding with the queue does not seem to happen. 
> Can you also help get the logs from the keda operator?
> Thanks!

**Comment by VenkateshSrini** [comment]
Hi @balchua ,
Is this details sufficient. Could you please help me on this as we are doing a POC for a client and stillI'm unable to get this working. Any inputs to resolve the issue will be of immense help.

**Comment by balchua** [comment]
@VenkateshSrini 
You need to use the `TriggerAuthentication` Crd as well as the `Secret`.  The `host` attribute is no longer defined as the amqp url.  It has to be derived.

Check this out.  https://keda.sh/concepts/authentication/#defining-secrets-and-config-maps-on-scaledobject

**Comment by VenkateshSrini** [comment]
@balchua ,
Thanks for link. If I understand correctly can just mounting the secrets. Should the secret be base64 encoded or can it be a simple plain string also. Please let me know this alone so that I can get this working today

**Comment by balchua** [comment]
Secrets are always base64 encoded. Checkout the samples.

**Comment by VenkateshSrini** [comment]
@balchua , Thanks I was able to get it working. The only thing I see is there are some pods that are sill left running. Is there some where I can see why those pods did not get shut down. Also one more thing that I see is each pod actually have received more than 10 message. Is there a way I can say that each job created by scaled object should process exactly one message only?

**Comment by balchua** [comment]
@VenkateshSrini keda doesn't look into the message, nor it distributes the message to the pod.  That will be the job of the pod/workload.
I also see that you have `parallelism` set to `10`, that means it will have 10 pods per kubernetes `Job`.

To see the logs you will probably have to do `kubectl logs -f <podname> -n <pod namespace`

**Comment by VenkateshSrini** [comment]
I have seen the logs the pods are healthy and have completed execution. when I tried 
`kubectl get jobs` I see the jobs are still running even though the rabbit mq is empty. It is not signaled as completed

> NAME                      COMPLETIONS   DURATION   AGE
> rabbitmq-consumer-4jztw   0/1           8h         8h
> rabbitmq-consumer-86rvj   0/1           8h         8h
> rabbitmq-consumer-dc6m4   0/1           8h         8h
> rabbitmq-consumer-fj5w2   0/1           8h         8h
> rabbitmq-consumer-fqfzp   0/1           8h         8h
> rabbitmq-consumer-pkb98   0/1           8h         8h
> rabbitmq-consumer-qr9vh   0/1           8h         8h
> rabbitmq-consumer-szdjn   0/1           8h         8h
> rabbitmq-consumer-vsj6c   0/1           8h         8h
> rabbitmq-consumer-xmdww   0/1           8h         8h
> rabbitmq-publish          1/1           21s        8h

**Comment by balchua** [comment]
@VenkateshSrini non of the pods have completed, you can see `0/1`.  Since you are setting your job as a "work queue", these are the conditions to mark the Job as Completed.

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#writing-a-job-spec

Taking it from the documentation above.

>Parallel Jobs with a work queue:

> - do not specify .spec.completions, default to .spec.parallelism.

> - the Pods must coordinate amongst themselves or an external service to determine what each should work on. For example, a Pod might fetch a batch of up to N items from the work queue.

> - each Pod is independently capable of determining whether or not all its peers are done, and thus that the entire Job is done.

> - when any Pod from the Job terminates with success, no new Pods are created.

> - once at least one Pod has terminated with success and all Pods are terminated, then the Job is completed with success.

> - once any Pod has exited with success, no other Pod should still be doing any work for this task or writing any output. They should all be in the process of exiting.

Can you try setting `parallelism` to 1 for now and see if the job completes?

**Comment by VenkateshSrini** [comment]
> @VenkateshSrini non of the pods have completed, you can see `0/1`. Since you are setting your job as a "work queue", these are the conditions to mark the Job as Completed.
> 
> https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#writing-a-job-spec
> 
> Taking it from the documentation above.
> 
> > Parallel Jobs with a work queue:
> 
> > * do not specify .spec.completions, default to .spec.parallelism.
> 
> > * the Pods must coordinate amongst themselves or an external service to determine what each should work on. For example, a Pod might fetch a batch of up to N items from the work queue.
> 
> > * each Pod is independently capable of determining whether or not all its peers are done, and thus that the entire Job is done.
> 
> > * when any Pod from the Job terminates with success, no new Pods are created.
> 
> > * once at least one Pod has terminated with success and all Pods are terminated, then the Job is completed with success.
> 
> > * once any Pod has exited with success, no other Pod should still be doing any work for this task or writing any output. They should all be in the process of exiting.
> 
> Can you try setting `parallelism` to 1 for now and see if the job completes?

@balchua ,
Please see the modified yaml file
```
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmqhost
data:
  rabbitmqhostkey: YW1xcDovL3VzZXI6UEFTU1dPUkRAcmFiYml0bXEuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy #base64 encoded per secret spec
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer
  namespace: default
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  # labels:
  #   deploymentName: rabbitmq-consumer
spec:
  scaleType: job
  pollingInterval: 5   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  maxReplicaCount: 30  # Optional. Default: 100
  completions: 1
  jobTargetRef:
    parallelism: 1
    activeDeadlineSeconds: 3600
    template:
      spec:
        containers:
        - name: rabbitmq-consumer
          image: venkateshsrini3/receivejob
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: rabbitmqhost
          args:
          - 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672'
        restartPolicy: Never  
  triggers:
  - type: rabbitmq
    metadata:
      queueName: hello
      host: rabbitmqhostkey
      queueLength  : '5'

```
After doing this also the pod status is the same. The only improvement I got is I had lesser number of pods created per job. My doubt is on the `completion` setup. Should I remove it complete and let parallelism handle that?

**Comment by balchua** [comment]
@VenkateshSrini from ur yaml, the `completion` is not inside the `jobScaleRef`.
Have u tried without the `parallelism` and `completion`?

**Comment by VenkateshSrini** [comment]
> @VenkateshSrini from ur yaml, the `completion` is not inside the `jobScaleRef`.
> Have u tried without the `parallelism` and `completion`?

@balchua ,
My Yaml files now looks below. You can see that Parallelism and completion are commented. 
```
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmqhost
data:
  rabbitmqhostkey: YW1xcDovL3VzZXI6UEFTU1dPUkRAcmFiYml0bXEuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy #base64 encoded per secret spec
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer
  namespace: default
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  # labels:
  #   deploymentName: rabbitmq-consumer
spec:
  scaleType: job
  pollingInterval: 5   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  maxReplicaCount: 30  # Optional. Default: 100
  jobTargetRef:
    # parallelism: 1
    # completions: 1
    activeDeadlineSeconds: 3600
    template:
      spec:
        containers:
        - name: rabbitmq-consumer
          image: venkateshsrini3/receivejob
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: rabbitmqhost
          args:
          - 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672'
        restartPolicy: Never  
  triggers:
  - type: rabbitmq
    metadata:
      queueName: hello
      host: rabbitmqhostkey
      queueLength  : '5'
```
But still the jobs are not getting completed. The container actually runs .NET core code. The code can be seen at https://github.com/VenkateshSrini/sample-netcore-keda-rabbitmq/tree/master/Receive

Still the jobs have not been completed. Please see the below the output of `kubectl get jobs`

> NAME                      COMPLETIONS   DURATION   AGE
> rabbitmq-consumer-4xdm2   0/1           7m12s      7m13s
> rabbitmq-consumer-56n4q   0/1           7m13s      7m13s
> rabbitmq-consumer-57dgb   0/1           7m12s      7m13s
> rabbitmq-consumer-c27rc   0/1           7m13s      7m13s
> rabbitmq-consumer-fq8qk   0/1           7m14s      7m15s
> rabbitmq-consumer-h2wt7   0/1           7m13s      7m16s
> rabbitmq-consumer-t5bdt   0/1           7m16s      7m16s
> rabbitmq-consumer-tp2nz   0/1           7m13s      7m14s
