### ISSUE TITLE
Default value for missing data in Dynatrace scaler

### ISSUE THREAD

**Issue by zip-chanko** [kedacore/keda#6097]
### Proposal

A parameter for a scaler which fallbacks to a default value when the query returns no value.

Example: The `fallbackThreshold` parameter which fallbacks the value to `10` when the query returns no value.

```yaml
triggers:
  - type: dynatrace
    metadata:
      host: https://dummy-instance.live.dynatrace.com/
      metricSelector: 'MyCustomEvent:filter(eq("someProperty","someValue")):count:splitBy("dt.entity.process_group"):fold'
      threshold: "1000"
      fallbackThreshold: "10"
```

### Use-Case

As described in https://github.com/kedacore/keda/discussions/6054, Keda will show a warning `KEDAScalerFailed` if the query return no value.

### Is this a feature you are interested in implementing yourself?

No
