### ISSUE TITLE
Custom CA files not being loaded from /custom/ca

### ISSUE THREAD

**Issue by nickmhankins** [kedacore/keda#6100]
### Report

We are getting 401 errors from the kube-apiserver trying to query the keda-metrics-apiserver 
```
E0822 18:05:00.490964       1 available_controller.go:460] v1beta1.external.metrics.k8s.io failed with: failing or missing response from https://192.168.251.202:443/apis/external.metrics.k8s.io/v1beta1: bad status from https://192.168.251.202:443/apis/external.metrics.k8s.io/v1beta1: 401
```

And the logs in the kube-metrics-apiserver are saying:
```
Unable to authenticate the request ... certificate signed by unknown authority
```

Fine, we just need to get keda to trust our CA. According to the [documentation](https://keda.sh/docs/2.14/operate/security/#register-your-own-ca-in-keda-operator-trusted-store) we should be able to add CA files to the path `/custom/ca` on the keda-operator deployment.

We are doing that with the following kustomize patch:
```
- target:
    group: apps
    version: v1
    kind: Deployment
    name: keda-operator
    namespace: keda
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/1
      value:
        name: ca
        mountPath: /custom/ca
    - op: add
      path: /spec/template/spec/volumes/1
      value: 
        name: ca
        secret:
          secretName: ca
```

According the [this source ](https://arc.net/l/quote/vkueelsw) it should be logging every new certificate being added, however we're not seeing that log line so it doesn't look like the file is getting added to the trust store.

### Expected Behavior

Adding .pem files to the `/custom/ca` path on the keda-operator should log that it's adding them to the trust store, and then trust the certificate.

### Actual Behavior

It does not appear the trust store is actually loading the files, and our kube-apiserver is unable to query the `v1beta1.external.metrics.k8s.io`

### Steps to Reproduce the Problem

1. Have an internal CA
2. Add the CA.pem to /custom/ca with a volumeMount
3. Deploy

### KEDA Version

2.14.1

### Kubernetes Version

< 1.28

### Platform

Other
