### ISSUE TITLE
RabbitMQ trigger not work correctly for mode MessageRate and sum operator

### ISSUE THREAD

**Issue by abialas** [kedacore/keda#6110]
### Report

I am using trigger based on RabbitMQ and MessageRate as mode. As operation I am using sum and value is set to 150.
RabbitMQ has 4 queues. When every queue has incoming message rate at 50/s (200/s in sum) then I would expect to have two instances and this works fine. However, when my traffic increase and every queue has message rate 100/s (400/s in sum) I would expect three instances but Keda scales it up to my max which is six.

### Expected Behavior

When sum message rate is 400/s Keda should scale to three instances based on above setup.

### Actual Behavior

When sum message rate is 400/s Keda scales to six instances.

### Steps to Reproduce the Problem

1.ScaledObject definition:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaled-object-name
  namespace: namespace
spec:
  scaleTargetRef:
    name: release-name
  cooldownPeriod: 60
  pollingInterval: 10
  minReplicaCount: 2
  maxReplicaCount: 6
  triggers:
    - type: rabbitmq
      metadata:
        queueName: ^prefix.*$
        mode: MessageRate
        value: "150"
        unsafeSsl: "true"
        useRegex: "true"
        operation: sum
      authenticationRef:
        name: authRef
```
2. Rabbit with 4 queues every with message rate 100/s
3. Deployment release-name is scaled to six instances.

### KEDA Version

None

### Kubernetes Version

None

### Platform

Amazon Web Services

### Scaler Details

RabbitMQ Queue
