### ISSUE TITLE
Introduce version in the trigger spec

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#613]
Introduce version in the trigger spec so that we can release new versions of the trigger specification without breaking customers.

This allows us to introduce new ways of describing things without having messy documentation and is easier to troubleshoot.

### Use-Case

When a scaler decides to change things around by renaming fields, moving them around or introduce breaking changes there is no easy way to see the difference as a customer.

With clear versioning it would be more straight forward and the documentation can be built around it.

### Current

```yaml
triggers:
  - type: kafka
    metadata:
      brokerList: kafka.svc:9092
      consumerGroup: my-group
      topic: test-topic
      lagThreshold: '5'
```

### Proposal

We could add a `version` to the trigger spec:

```yaml
triggers:
  - type: kafka
    version: v1
    metadata:
      brokerList: kafka.svc:9092
      consumerGroup: my-group
      topic: test-topic
      lagThreshold: '5'
```

### Impact

The impact should be fairly minimal

- Configuration parsing should be able to coop with this
  - When no version is specified `v1` should be assumed
- Documentation should be updated
- Releases should note if new versions are released
