### ISSUE TITLE
Unable to fetch metrics from Prometheus Metrics Server:  unable to get external metric 

### ISSUE THREAD

**Issue by shreegithub** [kedacore/keda#6132]
### Report

I'm using KEDA to scale deployment based on Istio metrics. The ScaledObject is configured to use the istio_requests_total metric.

I'm encountering an issue while we deploy ScaledObject manifest. The Horizontal Pod Autoscaler (HPA) generated by KEDA's ScaledObject is throwing the following error:

`keda-autoscaling/s0-prometheus/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: istio-requests-scaler,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get s0-prometheus.external.metrics.k8s.io)`

I am able to fetch the metrics from the promethius server using curl but keda metrics server is failed to fetch the same metrics.

_**shrsingh@ITEM-S1$ kubectl describe hpa keda-hpa-istio-requests-scaler**_ 
```
Name:                                      keda-hpa-istio-requests-scaler
Namespace:                                 keda-autoscaling
Labels:                                    app.kubernetes.io/managed-by=keda-operator
                                           app.kubernetes.io/name=keda-hpa-istio-requests-scaler
                                           app.kubernetes.io/part-of=istio-requests-scaler
                                           app.kubernetes.io/version=2.15.1
                                           scaledobject.keda.sh/name=istio-requests-scaler
Annotations:                               <none>
CreationTimestamp:                         Tue, 03 Sep 2024 16:11:10 +0530
Reference:                                 Deployment/spring-prometheus
Metrics:                                   ( current / target )
  "s0-prometheus" (target average value):  <unknown> / 2
Min replicas:                              1
Max replicas:                              10
Deployment pods:                           1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric keda-autoscaling/s0-prometheus/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: istio-requests-scaler,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get s0-prometheus.external.metrics.k8s.io)
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetExternalMetric       10s (x5 over 70s)  horizontal-pod-autoscaler  unable to get external metric keda-autoscaling/s0-prometheus/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: istio-requests-scaler,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get s0-prometheus.external.metrics.k8s.io)
  Warning  FailedComputeMetricsReplicas  10s (x5 over 70s)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get s0-prometheus external metric value: failed to get s0-prometheus external metric: unable to get external metric keda-autoscaling/s0-prometheus/&LabelSelector{MatchLabels:map[string]string{scaledobject.keda.sh/name: istio-requests-scaler,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get s0-prometheus.external.metrics.k8s.io)

```

### Expected Behavior

Keda external metrics server should fetch the metrics from the promethius Server.

### Actual Behavior

Its throwing error in HPA generated by ScaledObject that not able to fetch Metrics 

### Steps to Reproduce the Problem

Scaled Object manifest:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: istio-requests-scaler
  namespace: keda-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-prometheus
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 300
  pollingInterval: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local
      metricName: istio_requests_total
      query: sum(rate(istio_requests_total{destination_workload="your-deployment-name"}[2m]))
      threshold: '50'

```

### Logs from KEDA operator

No Error in External Metrics Server

### KEDA Version

2.15.1

### Kubernetes Version

1.29

### Platform

Amazon Web Services

### Scaler Details

Promethius
