### ISSUE TITLE
Support for RocketMQ in KEDA

### ISSUE THREAD

**Issue by vb3328998** [kedacore/keda#6149]
Are there any plans to support RocketMQ as a scaler in KEDA? It would be great to have autoscaling based on RocketMQ metrics, similar to the existing scalers for other message queue systems like Kafka.

**Comment by JorTurFer** [comment]
Hey
This seems like a nice addition! Are you willing to support it?

**Comment by dovics** [comment]
Hello @JorTurFer I'm a beginner to keda and want to work on this good-first-issue

**Comment by dovics** [comment]
Hello,

In the past days, I took a look at the rocketmq clients([v4](https://github.com/apache/rocketmq-client-go) and [v5](https://github.com/apache/rocketmq-clients)). They currently lack admin methods and cannot obtain MaxOffset. Although the broker provides related interfaces, it uses a custom protocol implementation. If this part is added to KEDA Medium, maybe a little heavy.

I opened an issue(https://github.com/apache/rocketmq-client-go/issues/1167) to see what their community had to say.

Currently the best way to use rocketmq is probably to use prometheus scaler.

**Comment by arsenalzp** [comment]
Hello,
Is this issue still alive and valid?
Can I work on it?

**Comment by zroubalik** [comment]
@arsenalzp we need to check what is the status of the rocketmq clients as @dovics noted above, I will assing the issue to you as well. Please keep us posted

**Comment by arsenalzp** [comment]
Hello,
It seems `MaxOffset` is gotten from `PullResult` object:

```
type PullResult struct {
	NextBeginOffset      int64
	MinOffset            int64
	MaxOffset            int64
	Status               PullStatus
	SuggestWhichBrokerId int64
	// contains filtered or unexported fields
}
```

https://github.com/apache/rocketmq-client-go/blob/67ec50b93040567856cdbb32c03d607d8c292c3d/examples/consumer/pull/pull/main.go#L102-L112

**Comment by zroubalik** [comment]
@arsenalzp any update here?

**Comment by arsenalzp** [comment]
> [@arsenalzp](https://github.com/arsenalzp) any update here?

Hello,
I mentioned `MaxOffset` field is present in Rocketmq-client for Go. Is that what we expected for scale?
If so, I will implement rocketmq feature ASAP!

**Comment by sealbro** [comment]
Hey, I did research how to use KEDA with RocketMQ and since 5.x version RocketMQ natively exposes consumer lag as a Prometheus gauge `rocketmq_consumer_lag_messages{consumer_group, topic, is_retry, is_system, cluster, ...}` (defined in [RIP-46](https://github.com/apache/rocketmq/issues/5366), computed by the broker's `ConsumerLagCalculator`). KEDA's existing `prometheus` scaler can autoscale RocketMQ workloads on this directly — no new scaler code required.

**Broker config** (one block in `broker.conf`):

```text
metricsExporterType=PROM
metricsPromExporterPort=5557
enableLagAndDlqMetrics=true   # default is already true on 5.x
```

**Example ScaledObject:**

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rocketmq-consumer
spec:
  scaleTargetRef:
    name: my-consumer-deployment
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus:9090
      query: |
        sum(rocketmq_consumer_lag_messages{
          consumer_group="my-group",
          topic="my-topic",
          is_retry="false",
          is_system="false"
        })
      threshold: '10'
      activationThreshold: '1'
```

Verified locally against RocketMQ 5.3.2: the metric updates as messages flow and matches a direct broker-side lag calculation (`MaxOffset − ConsumerOffset` per queue) exactly.

**Caveat.** The broker only emits this metric for consumer groups with at least one active subscription (within a ~2-minute heartbeat window). For `minReplicaCount: 0` deployments this creates a cold-start hole: no consumer → no metric → KEDA can't trigger 0→1. Mitigations: `minReplicaCount: 1` (recommended), KEDA's `fallback` trigger, or a `cron` co-trigger for traffic windows.

**Why no native `rocketmq` KEDA scaler yet.** A native scaler would talk to the broker directly. Both upstream Go clients have gaps that block a clean implementation today:

- **v4** ([`apache/rocketmq-client-go`](https://github.com/apache/rocketmq-client-go)) — the legacy remoting client. Its internal layer already has the offset opcodes; they're just not exposed on the public `admin.Admin` interface ([#1167](https://github.com/apache/rocketmq-client-go/issues/1167)). The repo has had **no release since [`v2.1.2` in Sep 2023](https://github.com/apache/rocketmq-client-go/releases/tag/v2.1.2)**, so even a public-API PR merging to master is unconsumable as a vendored KEDA dep.
- **v5** ([`apache/rocketmq-clients/golang`](https://github.com/apache/rocketmq-clients/tree/master/golang)) — the strategic direction, actively released. `QueryOffset` / `GetOffset` are declared in the gRPC proto but the proxy server doesn't implement them, so calls return `UNIMPLEMENTED`. Filed details + proposed fix upstream: [apache/rocketmq#10434](https://github.com/apache/rocketmq/issues/10434).

Once the upstream change lands, a native KEDA `rocketmq` scaler becomes a wrapper over the v5 client. Happy to contribute it then.
