### ISSUE TITLE
Provide a Service Mesh Interface (SMI) scaler

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#615]
Provide a Service Mesh Interface (SMI) scaler.

### Use-Case

People who are using service meshes would love to autoscale their workloads as well.

### Proposal

[Service Mesh Interface (SMI)](http://smi-spec.io/) is a [specification](https://github.com/deislabs/smi-spec) which introduces a universal way to interact with service meshes.

As part of the specification, it covers how to retrieve [traffic metrics](https://github.com/deislabs/smi-spec/blob/master/traffic-metrics.md) which allows us to very easily integrate with it.

Good to know is that [Service Mesh Interface (SMI) is being donated to CNCF](https://github.com/cncf/toc/issues/337) ([deck](https://docs.google.com/presentation/d/1Pn6PvdaCnKf-MRhATWDFgKGmM7Z6tycumb07xYSev5U/edit?ts=5e179825#slide=id.g4054009e6b_5_0)), provides a [Go SDK](https://github.com/deislabs/smi-sdk-go) and is supported by a variety of services meshes already such as Linkerd (CNCF), SuperGloo (Solo.io), Istio*, Consul Connect* and more.

_(*) Via adapter_

Relates to https://github.com/kedacore/keda/issues/538
Relates to https://github.com/deislabs/smi-spec/issues/96

**Comment by tomkerkhove** [comment]
Here is a proposal for the trigger configuration:
```yaml
  triggers:
  - type: service-mesh-interface
    metadata:
      metricName: "p90_response_latency" # Required - Name of the metric in the SMI's TrafficMetrics resource.
      value: "30m"                       # Required - Value defining when we have to start scaling.
```
_Example is based on https://github.com/servicemeshinterface/smi-spec/blob/master/traffic-metrics.md#specification_

It would then pull the full `TrafficMetrics` object for the `scaleTargetRef` and filter out the configured `metricName` and make a decision on the value to scale on.

We can use the official Go SDK for accessing the information: https://github.com/deislabs/smi-sdk-go
