### ISSUE TITLE
Keda ScaledObject not able to connect to artemis queue

### ISSUE THREAD

**Issue by modishivang** [kedacore/keda#6170]
I am using Keda version 2.15 and Kubernetes 1.28

**Getting below error** 

Warning  KEDAScalerFailed    46s (x6 over 3m16s)   keda-operator  Get "http://queue-a:8161/console/jolokia/read/org.apache.activemq.artemis:broker=%220.0.0.0%22,component=addresses,address=%22provAPISANDBOXTestConfigin%22,subcomponent=queues,routing-type=%22anycast%22,queue=%22provAPISANDBOXTestConfigin%22/MessageCount": dial tcp: lookup queue-a on 172.20.0.10:53: no such host

If I exec into queue pod, do curl above command, it works successfully.

Here is my keda scaledobject yaml

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: provweb-scaledobject
  namespace: ce-0fda256a-ba0d-4769-9a8e-ac05c2c5eead
spec:
  scaleTargetRef:
    name: provweb-a
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: artemis-queue
    metadata:
      managementEndpoint: "queue-a:8161"
      queueName: "provAPISANDBOXTestConfigin"
      brokerName: "0.0.0.0"
      brokerAddress: "provAPISANDBOXTestConfigin"
      queueLength: '10'
      activationQueueLength: '0'
      username: ''
      password: ''
```

Please suggest if I missed anything here.
