### ISSUE TITLE
AWS SecretsManager TriggerAuth Unable to get secret

### ISSUE THREAD

**Issue by sreeboppana** [kedacore/keda#6249]
### Report

Keda version: keda:2.14.0
ghcr.io/kedacore/keda:2.14.0
kubenetes version: 1.29

keda TriggerAuth is unable to read the Secrets from AWS secretsManager though provided the correct secretName & secret parameter.

### Expected Behavior

Keda should have read the secrets from AWS secrets Manager. 

Verified that the secret Name is valid and present with in the AWS region's SecretsManager matches to that of the one configured within TriggerAuth.yaml

The secret Name : `service/test-svc/svc-api-key-path` existed within the intended aws regions's SecretsManager.

the target AWS secrets manager secret (service/test-svc/svc-api-key-path) is of the form:
    {
           "api-key":"MY-SECRET-KEY",
           "api-secret":"MY-SECRET--VAL"
     }

               triggerauth.yaml
```
apiVersion: v1
items:
  kind: TriggerAuthentication
  metadata:
    **name: test-triggerauth**
    namespace: my-microservice-namespace
   spec:
    awsSecretManager:
      podIdentity:
        provider: aws
        roleArn: arn:aws:iam::<accountId>:test-role/<test-role-ID>
      region: us-east-1
      secrets:
      - name: service/test-svc/svc-api-key-path
        parameter: api-key
      - name: service/test-svc/svc-api-key-path
        parameter: api-secret
```

### Actual Behavior

```
2024-10-18T14:39:47Z	ERROR	**scale_handler	error resolving auth params**	
   {
         "type": "ScaledObject", 
           "namespace": "my-microservice-namespace", 
            "name": "my-microservice", 
            "triggerIndex": 3, 
             "error": "error creating kafka client: kafka: client has run out of available brokers to talk to: read tcp 172.22.47.114:32914->100.66.23.62:9092: read: connection reset by peer"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
	/workspace/pkg/scaling/scalers_builder.go:99
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).performGetScalersCache
	/workspace/pkg/scaling/scale_handler.go:357
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:282
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:611
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:243
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:182
```

### Steps to Reproduce the Problem

Goal: Use Keda triggerAuth AWs secretsManager to read secrets and be able to scale Kafka.

Keda version: keda:2.14.0
ghcr.io/kedacore/keda:2.14.0
kubenetes version: 1.29
 
1. STEP-1  - 
               triggerauth.yaml
```
apiVersion: v1
items:
  kind: TriggerAuthentication
  metadata:
    **name: test-triggerauth**
    namespace: my-microservice-namespace
   spec:
    awsSecretManager:
      podIdentity:
        provider: aws
        roleArn: arn:aws:iam::<accountId>:test-role/<test-role-ID>
      region: us-east-1
      secrets:
      - name: service/test-svc/svc-api-key-path
        parameter: api-key
      - name: service/test-svc/svc-api-key-path
        parameter: api-secret
```
2.
                ScaledObject.yaml
```
Name:         my-microservice
Namespace:    my-microservice-namespace
API Version:  keda.sh/v1alpha1
Kind:         ScaledObject
Spec:
  Triggers:
    Metadata:
      Value:      10
    Metric Type:  Utilization
    Type:         cpu
    Metadata:
      Value:      10
    Metric Type:  Utilization
    Type:         memory
    Authentication Ref:
      **Name:  test-triggerauth**
    Metadata:
      Bootstrap Servers:  serverHostNames:9092
      Consumer Group:     xyz
      Lag Threshold:      30
      Topic:              event.xyz
    Type:                 kafka
```

3. the target AWS secrets manager secret (service/test-svc/svc-api-key-path) is of the form:
    {
           "api-key":"MY-SECRET-KEY",
           "api-secret":"MY-SECRET--VAL"
     }

    basically we are trying retrieve the api-key and api-secret values for that response above.

4. Deployed the resources and then keda operator logs are shown below:
as per the documentation https://keda.sh/docs/2.14/concepts/authentication/

**The secrets list within awsSecretManager defines the mapping between the AWS Secret Manager secret and the authentication parameter used in your application, including the parameter name, AWS Secret Manager secret name, and an optional version parameter, defaulting to the latest version if unspecified.**

```
2024-10-18T14:39:47Z	ERROR	**scale_handler	error resolving auth params**	
   {
         "type": "ScaledObject", 
           "namespace": "my-microservice-namespace", 
            "name": "my-microservice", 
            "triggerIndex": 3, 
             "error": "error creating kafka client: kafka: client has run out of available brokers to talk to: read tcp 172.22.47.114:32914->100.66.23.62:9092: read: connection reset by peer"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
	/workspace/pkg/scaling/scalers_builder.go:99
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).performGetScalersCache
	/workspace/pkg/scaling/scale_handler.go:357
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:282
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:611
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:243
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:182
```

### Logs from KEDA operator

```
2024-10-18T14:39:47Z	ERROR	**scale_handler	error resolving auth params**	
   {
         "type": "ScaledObject", 
           "namespace": "my-microservice-namespace", 
            "name": "my-microservice", 
            "triggerIndex": 3, 
             "error": "error creating kafka client: kafka: client has run out of available brokers to talk to: read tcp 172.22.47.114:32914->100.66.23.62:9092: read: connection reset by peer"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
	/workspace/pkg/scaling/scalers_builder.go:99
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).performGetScalersCache
	/workspace/pkg/scaling/scale_handler.go:357
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:282
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:611
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:243
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:182

2024-10-18T14:39:47Z	ERROR	scale_handler	error getting state of scaledObject	
{
   "scaledObject.Namespace": "my-microservice-namespace", 
     "scaledObject.Name": "my-microservice", 
      "error": "error getting scalers cache error creating kafka client: kafka: client has run out of available brokers to talk to: read tcp 172.22.47.114:32914->100.66.23.62:9092: read: connection reset by peer"}

```

### KEDA Version

2.14.0

### Kubernetes Version

1.29

### Platform

Amazon Web Services

### Scaler Details

kafka

### Anything else?

Verified that the secret Name is valid and present with in the AWS region's SecretsManager matches to that of the one configured within TriggerAuth.yaml
The secret Name : `service/test-svc/svc-api-key-path` existed within the intended aws regions's SecretsManager.

               triggerauth.yaml
```
apiVersion: v1
items:
  kind: TriggerAuthentication
  metadata:
    **name: test-triggerauth**
    namespace: my-microservice-namespace
   spec:
    awsSecretManager:
      podIdentity:
        provider: aws
        roleArn: arn:aws:iam::<accountId>:test-role/<test-role-ID>
      region: us-east-1
      secrets:
      - name: service/test-svc/svc-api-key-path
        parameter: api-key
      - name: service/test-svc/svc-api-key-path
        parameter: api-secret
```
