### ISSUE TITLE
Optional TLS verification disablement for Datadog scaler 

### ISSUE THREAD

**Issue by SomaSharathSurya** [kedacore/keda#6253]
### Proposal

I am using the Datadog scaler as described in the documentation: https://keda.sh/docs/2.14/scalers/datadog/. However, I encountered the following TLS issue.

**Error**:
`error establishing Datadog connection: error connecting to Datadog API endpoint: Get "https://api.datadoghq.com/api/v1/validate": tls: failed to verify certificate: x509: certificate signed by unknown authority`

I attempted to disable TLS verification by setting `unsafeSsl: 'true'` in the scaled object, but din't work. It would be helpful if KEDA could offer a way to disable TLS verification directly from the scaled object configuration. For reference, here is the configuration I used:

```
triggers:
-  authenticationRef:
      name: trigger-auth
    metadata:
      age: '90'
      metricUnavailableValue: '0'
      query: >
        xxxx
      queryValue: '20'
      unsafeSsl: 'true'
    type: datadog
    useCachedMetrics: true
```

**Other information**
- KEDA version being used: v2.14.0

### Use-Case

This feature would enable quick testing in development environment without worrying about certificate validation. It would reduce setup complexity by eliminating the need to manage/modify CA certificates during development phase and minimize dependency on cluster administrators 

### Is this a feature you are interested in implementing yourself?

No
