### ISSUE TITLE
Support metadata annotations in ScaledJob template's volume claims

### ISSUE THREAD

**Issue by dpertin** [kedacore/keda#6254]
### Report

Applying metadata annotations on a volume claim template, inside ScaledJob templates returns an error.
Here's the definition of the metadata annotations:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    argocd.argoproj.io/instance: xxx
  name: yyy
  namespace: zzz
spec:
(...)
        volumes:
(...)
          - ephemeral:
              volumeClaimTemplate:
                metadata:
                  annotations:
                    resize.topolvm.io/increase: 15Gi
                    resize.topolvm.io/inodes-threshold: 20%
                    resize.topolvm.io/storage_limit: 1024Gi
                    resize.topolvm.io/threshold: 30%
                    volume-type: ephemeral
```

### Expected Behavior

This should create a volume claim with the appropriate metadata annotations

### Actual Behavior

It returns the following error: `ScaledJob in version "v1alpha1" cannot be handled as a ScaledJob: strict decoding error: unknown field "spec.jobTargetRef.template.spec.volumes[5].ephemeral.volumeClaimTemplate.metadata.annotations"`

### Steps to Reproduce the Problem

1. Create a ScaledJobs based on the definition given above
2. Run `kubectl apply -f` using this definition
3. This returns the error

### KEDA Version

2.15.1

### Kubernetes Version

1.30

### Platform

Google Cloud
