### ISSUE TITLE
Potential RabbitMQ connection leak

### ISSUE THREAD

**Issue by xaka** [kedacore/keda#6266]
### Report

I've got ~600 scaled objects with similar rabbitmq config:

```
  triggers:
  - metadata:
      host: amqp://guest:guest@rabbitmq.default:5672
      mode: QueueLength
      protocol: amqp
      queueName: <unique-id>:queue
      value: "1"
      vhostName: /
    type: rabbitmq
```

Count TOP-10 connections by host
```
rabbitmq-0:/# rabbitmqctl list_connections | awk '
NR > 2 {count[$2]++}
END {
    for (host in count) {
        print host, count[host]
    }
}' | sort -k2,2nr | head -n 10
172.31.17.39 10369
172.31.26.39 1305
172.31.12.223 907
172.31.41.74 388
172.31.37.14 2
172.31.10.181 1
172.31.10.40 1
172.31.10.46 1
172.31.11.119 1
172.31.11.209 1
```

In this case `172.31.17.39` is keda operator pod and it opened 10k connections so far (5 days). The number is growing over time until rabbitmq gets stuck.

### Expected Behavior

Number of connections is stable over time and doesn't grow

### Actual Behavior

Connections are being opened over time, but never closed/disposed

### Steps to Reproduce the Problem

N/A

### Logs from KEDA operator

```
example
```

### KEDA Version

2.12.1

### Kubernetes Version

1.29

### Platform

Amazon Web Services

### Scaler Details

RabbitMQ
