### ISSUE TITLE
Operator fail when KEDA_RESTRICT_SECRET_ACCESS enabled

### ISSUE THREAD

**Issue by pacmanmulet** [kedacore/keda#6278]
### Report

I have deployed KEDA  enablng KEDA_RESTRICT_SECRET_ACCESS environment variable and operator returns an error:

![image](https://github.com/user-attachments/assets/afcace5f-9d3e-46be-a431-7d48968d5627)

### Expected Behavior
KEDA operator running without errors.

### Actual Behavior
KEDA operator fails to start

### Steps to Reproduce the Problem
KEDA is installed using helm and the access to secrets is limited using the following parameters in [values.yaml](https://github.com/kedacore/charts/blob/main/keda/values.yaml)
```
metricsServer:
  dnsPolicy: ClusterFirstWithHostNet
  useHostNetwork: true
nodeSelector:
  workergroup: compute
permissions:
  metricServer:
    restrict:
      secret: false
  operator:
    restrict:
      secret: true
```
KEDA Version
2.14.0

Kubernetes Version
v1.27.16-eks-ce1d5eb

Platform
EKS
