### ISSUE TITLE
Tool for Generating Trigger Schema 

### ISSUE THREAD

**Issue by SpiritZhou** [kedacore/keda#6345]
### Proposal

Generating trigger metadata schema according to new declarative scaler configuration, which can be used for validation or other related improvement.

Input: 
`
  make generate-scaler-schemas  [--keda-version][--specify-scaler][--outputfile]
`

Output:
scaler-metadata-schemas.yaml

Trigger metadata example:
```
kedaVersion: main
schemaVersion: 1
triggers:
    - type: prometheus
      metadata:
        - name: serverAddress
          type: string
        - name: query
          type: string
        - name: queryParameters
          type: string
          optional: true
        - name: threshold
          type: string
        - name: activationThreshold
          type: string
          optional: true
        - name: namespace
          type: string
          optional: true
        - name: customHeaders
          type: string
          optional: true
        - name: ignoreNullValues
          type: string
          optional: true
          default: "true"
        - name: unsafeSsl
          type: string
          optional: true
        - name: awsRegion
          type: string
          optional: true
          canReadFromAuth: true
```

### Is this a feature you are interested in implementing yourself?

Yes
