### ISSUE TITLE
Keda apache-kafka scaler for MSK cluster can't connect using IAM / K8s AssumeRole

### ISSUE THREAD

**Issue by nkfirdigi** [kedacore/keda#6409]
### Report

Keda apache-kafka scaler for MSK cluster can't connect using IAM / K8s AssumeRole
Using keda-2.14.2
Using apache-kafka scaler connected to MSK cluster.
Secret definition:
```
apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets-msk
data:
  sasl: {{ "aws_msk_iam" | b64enc }} # or scram_sha512
  tls: {{ "enable" | b64enc }}
  awsRoleArn: {{ "arn:aws:iam::<....>:role/KubernetesServiceAccount_keda" | b64enc }}
  awsRegion: {{ "eu-west-1" | b64enc }}
```

### Expected Behavior

Expecting the AWS client to use k8s assume role IAM to access MSK cluster with no need to specify access key and secret.

### Actual Behavior

ScaleObject error: requires to define access key and secret 
```
KEDAScalerFailed
error parsing kafka metadata: awsAccessKeyID not found
```

### Steps to Reproduce the Problem

1. define apache-kafka
2. define sasl of type "aws_msk_iam"
3. define tls: "enabled"

### Logs from KEDA operator

```
```

### KEDA Version

2.14.1

### Kubernetes Version

1.29

### Platform

Amazon Web Services

### Scaler Details

apache-kafka
