### ISSUE TITLE
Creating a new ScaledObject with the “paused” annotation is not working

### ISSUE THREAD

**Issue by Dark0096** [kedacore/keda#6421]
### Report

There is an issue where, after creating the initial ScaledObject with the “paused” annotation set, when resuming, the ScaledObject correctly generates the HPA, but the "Paused" condition state becomes True again, and the HPA remains in place.

### Expected Behavior

1. Init condition(Create the ScaledObject)
Ready: True
Active: True
Fallback: False
Paused: True
HPA: None

2. After resume(Paused Annotation Removed)
Ready: True
Active: True
Fallback: False
Paused: False
HPA: New one created by the scaled object

### Actual Behavior

1. Init condition(Create the ScaledObject)
Ready: True
Active: Unknown
Fallback: Unknown
Paused: True
HPA: None

2. After resume(Paused Annotation Removed)

2-1. Init
Ready: True
Active: Unknown
Fallback: Unknown
Paused: False
HPA: New one created by scaled object

2-2. After a few seconds
Ready: True
Active: Unknown
Fallback: False
Paused: True
HPA: New one created by scaled object

Here is a video from the Lens app demonstrating the issue
- https://github.com/user-attachments/assets/1bf899cf-2e69-4c47-8a5a-f40421534e23

### Steps to Reproduce the Problem

1. Write a ScaledObject manifest including the CPU and Cron Scalers.
2. Add the paused annotation to the created manifest.
3. Apply the created manifest using kubectl apply.

### Logs from KEDA operator

```
There are no specific logs available.
```

### KEDA Version

2.15.1

### Kubernetes Version

1.30

### Platform

Amazon Web Services

### Scaler Details

cpu, memory, cron

### Anything else?

Hi,

I’ve been using KEDA effectively, and I have a question.
Has the pattern of initially creating a ScaledObject resource with a paused annotation by default and resuming it as needed been considered?

If there are any parts of the code you suspect might be relevant, please let me know, and I’ll try making modifications myself.

Thank you!

**Comment by vtomasr5** [comment]
We have a similar issue with pausing.

If we add the `autoscaling.keda.sh/paused-replicas: "10"` annotation to the ScaledObject (SO) we see those logs in the `keda-operator`:

```
...
2024-12-18T15:49:18Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"querier","namespace":"mimir"}, "namespace": "mimir", "name": "querier", "reconcileID": "c931a2a2-0820-4847-9fd3-e88987b09e7e", "error": "ScaledObject paused replicas are being scaled"} 
  |   | /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227 |  
  |   | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2 |  
  |   | /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266 |  
  |   | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem |  
  |   | /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316 |  
  |   | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler |  
  |   | /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119 |  
  |   | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile |  
  |   | /workspace/controllers/keda/scaledobject_controller.go:196 |  
  |   | github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
...
```

Which comes from this [code](https://github.com/kedacore/keda/blob/release/v2.16/controllers/keda/scaledobject_controller.go#L314)

The Active type is `Unknown`, an issue for the ArgoCD syncing process that gets stuck forever.
```
status:
  conditions:
  - message: ScaledObject check failed
    reason: UnknownState
    status: Unknown
    type: Active
```

**Comment by SpiritZhou** [comment]
I believe there is a bug, but I am unable to reproduce it. Would you be able to provide the ScaledObject YAML?

**Comment by rickbrouwer** [comment]
I see this also (and other unexpected behavior).

If I specify the following scaledObject.yaml:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-biv-ui
  annotations:
    autoscaling.keda.sh/paused-replicas: "5"
    autoscaling.keda.sh/paused: "false"
spec:
  scaleTargetRef:
    name: my-manifest
  cooldownPeriod: 30
  fallback:
    failureThreshold: 3
    replicas: 2
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 30
  triggers:
    - type: ibmmq
      metadata:
        host: https://my-host/ibmmq/rest/v2/admin/action/qmgr/MQDEV/mqsc
        queueName: "my-queue.LQ"
        queueDepth: '4'
      authenticationRef:
        name: keda-ibmmq-trigger-auth
```

With a new deployment with this yaml, I don't get an HPA. In ArgoCD, the app health is set to `suspended`.
If I change it to `autoscaling.keda.sh/paused: "true"`, I do get an HPA and the number of `paused-replicas`.
If I then set it back to `autoscaling.keda.sh/paused: "false"`, the app health remains `suspended` in ArgoCD. It also keeps the number of `paused-replicas`.

In the status condition i see also the message:
```
    - message: ScaledObject check failed
      reason: UnknownState
      status: Unknown
      type: Active
```

**Comment by rickbrouwer** [comment]
I can only reproduce this if I specify both in a conflicting situation (both `false` and specifying `paused-replicas`). This:

```
annotations:
    autoscaling.keda.sh/paused-replicas: "2"
    autoscaling.keda.sh/paused: "false"
```

I think it would be clearer if `autoscaling.keda.sh/paused` will be leading? So if it is set to `false`, it is really paused regardless of whether `paused-replicas` is filled?
It am also curious if Dark0096 and vtomasr5 specify both or not. If not, I am also curious about the ScaledObject.yaml.

**Comment by Dark0096** [comment]
This issue occurred when paused was used during the initial creation of a new resource.
Below is a reproducible example, including the YAML configuration.

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    autoscaling.keda.sh/paused: 'false'
  labels:
    scaledobject.keda.sh/name: resource-name-1
  name: resource-name-1
  namespace: deployment-dev
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
            - periodSeconds: 60
              type: Percent
              value: 30
          selectPolicy: Min
          stabilizationWindowSeconds: 300
        scaleUp:
          policies:
            - periodSeconds: 15
              type: Pods
              value: 4
            - periodSeconds: 15
              type: Percent
              value: 100
          selectPolicy: Max
          stabilizationWindowSeconds: 0
      name: resource-name-1
    scalingModifiers: {}
  cooldownPeriod: 300
  maxReplicaCount: 3
  minReplicaCount: 1
  pollingInterval: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-name-1
  triggers:
    - metadata:
        desiredReplicas: '1'
        end: 30 1 * * *
        name: lateNight
        start: 0 1 * * *
        timezone: Asia/Seoul
      type: cron
    - metadata:
        desiredReplicas: '3'
        end: 30 9 * * *
        name: earlyMorning
        start: 0 9 * * *
        timezone: Asia/Seoul
      type: cron
    - metadata:
        desiredReplicas: '3'
        end: 0 16 * * *
        name: earlyEvening
        start: 30 15 * * *
        timezone: Asia/Seoul
      type: cron
    - metadata:
        value: '55'
      metricType: Utilization
      type: cpu
```

**Comment by rickbrouwer** [comment]
I use Keda 2.16.0 (with ArgoCD v2.12.8).

The only thing I can reproduce is the following:

When i initially place the above scaledObject with only a `paused` with value `false` I get the following status condition:

```
- status: Unknown
type: Paused
```
When I look at the code, an initial creation with the value `false` will give an `Unknown` status because the condition has never been `true`.

With a little adjustment in the `reconcileScaledObject` we can give a better status and message.

**Comment by Dark0096** [comment]
Thank you for checking this out. @rickbrouwer.

Unfortunately, if you create a scaledObject with the paused annotation set to true,
The same issue occurs with the following status and behavior.

1. Init condition(Create the ScaledObject)
Ready: True
Active: Unknown
Fallback: Unknown
Paused: True
HPA: None

2. After resume(Paused Annotation Removed)
Ready: True
Active: Unknown
Fallback: Unknown
Paused: False
HPA: New one created by scaled object

3. After a few seconds
Ready: True
Active: Unknown
Fallback: False
Paused: True
HPA: New one created by scaled object

Here is a video from the Lens app demonstrating the issue.

https://github.com/user-attachments/assets/1bf899cf-2e69-4c47-8a5a-f40421534e23

**Comment by SpiritZhou** [comment]
The tricky thing is that the paused status with SO will be changed from false to true. However, the kada operator will not update the paused status proactively.

**Comment by onedr0p** [comment]
I just ran into this where setting either of these annotations paused the workload.

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: zigbee
  annotations:
    autoscaling.keda.sh/paused: "false"
    autoscaling.keda.sh/paused-replicas: "0"
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  cooldownPeriod: 0
  minReplicaCount: 0
  maxReplicaCount: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zigbee
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.observability.svc.cluster.local:9090
        query: probe_success{instance=~"zigbee-controller.+"}
        threshold: "1"
        ignoreNullValues: "0"

```

I would expect the workload would only be paused when `autoscaling.keda.sh/paused: "true"`

Relevant logs:

```
2025-06-04T13:28:52Z	ERROR	ScaledObject paused replicas are being scaled	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"zigbee","namespace":"default"}, "namespace": "default", "name": "zigbee", "reconcileID": "81ea29fc-8ea6-4840-9dcb-ef27b579ac1c", "error": "ScaledObject paused replicas are being scaled"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:195
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:116
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224
```
