### ISSUE TITLE
Issue with Updating CPU ScaledObjects on GCP Clusters

### ISSUE THREAD

**Issue by harelhadar** [kedacore/keda#6438]
### Report

We are facing an issue when attempting to update ScaledObjects, which includes only CPU&memory triggers in our GCP Kubernetes clusters.
The following error occurs consistently across multiple GCP clusters:
`error: scaledobjects.keda.sh "harel-server" could not be patched: Timeout: request did not complete within requested timeout - context deadline exceeded`

Upon investigation, we identified long-duration calls (~24sec) to the Kubernetes API server related to vscaledobject.kb.io. This issue appears to be specific to GCP, as the same operations in AWS/Azure clusters function without any problems. We would also like to note that the issue reproduces on a cluster with 6 ScaledObjects, indicating that it is not related to the scale.

We found that temporarily removing the ValidatingWebhookConfiguration ("keda-admission") resolves the issue, but this is not a viable long-term solution for us.

### Expected Behavior

The scaledobject configuration should be updated.

### Actual Behavior

Failing with timeout error

### Steps to Reproduce the Problem

1. Create a CPU ScaledObject in a GCP Kubernetes cluster.
2. Attempt to update the ScaledObject using kubectl/helm (Update Polling Interval to "11")
3. Observe the timeout error

### Logs from KEDA operator

No related logs from operator / admission-webhook during the time.

### KEDA Version

2.13.1

### Kubernetes Version

1.30

### Platform

Google Cloud

### Scaler Details

CPU

### Anything else?

ScaledObject example config:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  finalizers:
  - finalizer.keda.sh
  name: harel-server
  namespace: harel
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 30
            type: Pods
            value: 1
          stabilizationWindowSeconds: 90
        scaleUp:
          policies:
          - periodSeconds: 30
            type: Pods
            value: 3
          stabilizationWindowSeconds: 90
  cooldownPeriod: 10
  maxReplicaCount: 3
  minReplicaCount: 2
  pollingInterval: 10
  scaleTargetRef:
    kind: Deployment
    name: harel-server
  triggers:
  - metadata:
      value: "200"
    metricType: Utilization
    type: cpu
  - metadata:
      value: "800"
    metricType: Utilization
    type: memory
```
