### ISSUE TITLE
rabbitmq scaler unsafeSsl does not work for amqps

### ISSUE THREAD

**Issue by alita-moore** [kedacore/keda#6461]
### Report

If you pass in a amqps host to the rabbitmq scalar it will require that the certificate is signed, however if you pass in https instead it works as expected.

### Expected Behavior

tls is enabled without validation

### Actual Behavior

Warning  KEDAScalerFailed         5m49s (x14 over 66m)  keda-operator  error establishing rabbitmq connection: tls: failed to verify certificate: x509: certificate signed by unknown authority

### Steps to Reproduce the Problem

1. install keda and rabbitmq
2. setup a ScaledObject with a config similar to the following
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-consumers-scaledobject
  namespace: ml-serving
spec:
  scaleTargetRef:
    name: queue-consumers
  pollingInterval: 5
  cooldownPeriod: 60
  maxReplicaCount: 10
  minReplicaCount: 1
  triggers:
    - type: rabbitmq
      metadata:
        queueName: prod.tasks.image.parsing
        value: "5"
        mode: QueueLength
        activationValue: "1"
        hostFromEnv: RABBITMQ_URL
        protocol: auto
        tls: "enable"
        unsafeSsl: "true"
      authenticationRef:
        name: rabbitmq-trigger-auth
```
3. start the deployment / scaler
4. notice that it only works if RABBITMQ_URL starts with `https` instead of `amqps`

### Logs from KEDA operator

```
 Warning  KEDAScalerFailed         5m49s (x14 over 66m)  keda-operator  error establishing rabbitmq connection: tls: failed to verify certificate: x509: certificate signed by unknown authority
```

### KEDA Version

None

### Kubernetes Version

Other

### Platform

Other

### Scaler Details

rabbitmq
