### ISSUE TITLE
Redis Streams Scaler Does Not Trigger on a Single Message

### ISSUE THREAD

**Issue by csabca83** [kedacore/keda#6478]
## Description:
When using the Redis Streams scaler in KEDA, I’ve observed that scaling does not occur when there is only a single message in the queue. The scaling only happens when at least 2 messages are present, which is problematic for use cases where individual messages need immediate processing.

This behavior seems to be related to the logic in the [Redis Streams scaler code](https://github.com/kedacore/keda/blob/3e87999f714410e517ce6773c6a2a6e581e16c11/pkg/scalers/redis_streams_scaler.go#L86), where the lag count is being checked.

Here is the trigger configuration I was using:
```yaml
  triggers:
  - type: redis-streams
    metadata:
      stream: messages
      consumerGroup: worker_group
      lagCount: "5"
      activationLagCount: "0"
```
and I had to change it to this one:
```yaml
  triggers:
  - type: redis-streams
    metadata:
      stream: messages
      consumerGroup: worker_group
      lagCount: "5"
      activationLagCount: "1"
```
## Steps to Reproduce:

1. Configure a Redis Streams scaler with the above configuration.
2. Send a single message to the fb_messages stream.
3. Observe that no scaling occurs when there is only one message in the stream.
4. Add a second message to the stream. At this point, scaling is triggered.

## Expected Behavior:
Scaling should occur when there is a single message in the stream, as long as the lag count exceeds the activationLagCount (which is set to 0 in this case).

## Actual Behavior:
Scaling only occurs when there are at least 2 messages in the stream, leading to delayed or missed processing for cases where only a single message arrives.

## Additional Context:
This issue affects use cases where low-latency processing of individual messages is required. If any additional configuration is needed to support this behavior, it should be documented.
