### ISSUE TITLE
Forgejo / Gitea runner jobs scaler

### ISSUE THREAD

**Issue by cobak78** [kedacore/keda#6488]
### Proposal

We want to improve scaling capabilites for the Forgejo Actions as explained in this issue (https://codeberg.org/forgejo/discussions/issues/241). To achieve that we already created new enpoints [here](https://codeberg.org/forgejo/forgejo/pulls/6300) for listing pending jobs, and a new --one-job runner execution command [here](https://code.forgejo.org/forgejo/runner/pulls/423).

 

### Scaler Source

Forgejo runners https://code.forgejo.org/forgejo/runner

### Scaling Mechanics

We tested this functionallity with a new scaled job definition that checks pending jobs on forgejo. And spawns pre-registered runners to execute the jobs one by one. 

This is an example of a scaled job definition

```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    app: forgejo-runner
  name: forgejo-runner
  namespace: runners
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: forgejo-runner
      spec:
        volumes:
        - name: runner-data
          persistentVolumeClaim:
            claimName: runner-pvc-claim
        - name: runner-config
          configMap:
            name: runner-config
        containers:
        - name: runner
          image: runner:6.1
          command: ["sh", "-c", "stackit-git-runner job"]
          volumeMounts:
          - name: runner-data
            mountPath: /data
          - name: runner-config
            mountPath: /config
            readOnly: false
  minReplicaCount: 0
  maxReplicaCount: 20
  pollingInterval: 30
  triggers:
  - type: forgejo-runner
    metadata:
      name: "forgejo-runner-ubuntu"
      token: "xxx"
      address: "https://v11.next.forgejo.org"
      global: "true"
      labels: "ubuntu-latest"
```

### Authentication Source

token authorization using forgejo token definition

### Anything else?

We are ready to create a PR with all the code and tests already done.
