### ISSUE TITLE
no scaler found for type: azure-monitor

### ISSUE THREAD

**Issue by vishal8k** [kedacore/keda#649]
I installed KEDA from helm charts following this document "https://keda.sh/deploy/". 
Keda chart = 1.2.0
Keda App version = 1.2.0

After setting up the scaledobject for Azure monitor I'm displayed with the error 

> "error":"error getting scaler for trigger #0: no scaler found for type: azure-monitor"

Below is my scaledobject.yaml

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-monitor-scaler
  labels:
    app: myapp
    deploymentName: mydeployment
spec:
  scaleTargetRef:
    deploymentName: mydeployment
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: azure-monitor
    metadata:
      resourceURI: Microsoft.Network/applicationGateways/myappgateway
      tenantId: <mytenantid>
      subscriptionId: <mysubscriptionid>
      resourceGroupName: <my-resource-group>
      metricName: CurrentConnections
      metricAggregationInterval: "0:1:0"
      metricAggregationType: Total
      targetValue: "300"
    authenticationRef:
      name: azure-monitor-trigger-auth

```

## Specifications
My cluster is on Azure Kubernetes Services (AKS)
  - **KEDA Version:** *1.2.0*
  - **Kubernetes Version:** *1.14.8*
  - **Scaler(s):** *azure-monitor*
