### ISSUE TITLE
globPattern does not work with hierarchical namespace while using azure-blob trigger

### ISSUE THREAD

**Issue by bene-tleilax-werdna** [kedacore/keda#6492]
When attempting to use the azure-blob trigger on an Azure Data Lake Storage account leveraging a hierarchical namespace, it seems the `globPattern` parameter does not work. 

Example, say your storage account is `adlsaccount` , container is `container` and you have directory structure such as:
```
folderA/
├─ subFolderA/
│  ├─ part-fileA.json
│  ├─ part-fileB.json
│  ├─ _METADATA_FILE
├─ subFolderB/
│  ├─ fileD.json
folderB/
├─ subFolderC/
│  ├─ fileE.txt
```

I want the scaler to trigger only if the scaler detects a *.json file in folderA/subFolderA.

According to the documentation, I should be able to use something like this:
```
triggers:
- type: azure-blob
  metadata:
    blobContainerName: container
    activationBlobCount: "1"
    blobCount: "5"
    connectionFromEnv: CONNECTION_STRING_ENV_NAME
    accountName: adlsaccount
    globPattern: "/folderA/subFolderA/*.json"
```

However, that does not work and it does not appear that the keda-operator logs indicate any reason why - the scaler will be healthy but will not activate. Using a double-asterisk makes no impact either.

We were able to work around this limitation with the common file prefix on the desired json files, as demonstrated below:
```
triggers:
- type: azure-blob
  metadata:
    blobContainerName: container
    activationBlobCount: "1"
    blobCount: "5"
    connectionFromEnv: CONNECTION_STRING_ENV_NAME
    accountName: adlsaccount
    blobPrefix: folderA/subFolderA/part-
    blobDelimiter: "/"
    recursive: "true"
```

That work-around works fine in my use-case but ideally we would want to leverage the ability to use glob patterns to match the desired blob files for which we want the scaler trigger to be invoked.

It looks like the glob pattern is not getting applied in the `GetAzureBlobListLength` function defined here: https://github.com/kedacore/keda/blob/6340991f9178912d6daf73766a0e50e6b438b212/pkg/scalers/azure/azure_blob.go

Someone more knowledgeable than I may have an idea of how best to resolve.
