### ISSUE TITLE
Keda with Prometheus Metrics [RPM] not working Properly.

### ISSUE THREAD

**Issue by ric-arrive** [kedacore/keda#6549]
### Report

Using KEDA metric type Prometheus. with the following configuration
```
      - type: prometheus
        metadata:
          serverAddress: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
          metricName: throughput
          query: |
            sum(rate(nginx_ingress_controller_requests{namespace="ingress-nginx"}[1m])) * 60
          threshold: '9000'
```
is not returning proper values

### Expected Behavior

[RPM] over 9000
10200/9k(avg)

### Actual Behavior

I'm getting the wrong value here, I'm assuming it is treating the metric value as if I was checking for memory or CPU. which is not the right one I'm looking form RPMs 

NAME            => keda-hpa-nginx-scaledobject                                       
REFERENCE   => Deployment/ingress-nginx-controller                                         
TARGETS       => 9334m/9k (avg)             
MINPODS     =>  3
MAXPODS    => 10
REPLICAS      => 3
AGE               => 2m48s  

### Steps to Reproduce the Problem

1. Use promethues metrics as a provider
2. Use above mentioned query
3. Check HPA values

### Logs from KEDA operator

```
No Logs related in KEDA Operator
```

### KEDA Version

2.16.1

### Kubernetes Version

1.31

### Platform

Microsoft Azure

### Scaler Details

Prometheus
