### ISSUE TITLE
Keda excludes unacknowledged rabbitMq messages when it shouldn't

### ISSUE THREAD

**Issue by nicolasprevot2** [kedacore/keda#6571]
### Report

I am using keda to scale jobs with the RabbitMq trigger

i have keda version 2.16.1

When there are 5 RabbitMq messages ready, and 5 unacknowledged and 5 jobs currently running: 
keda does not schedule new jobs. i would expect it to schedule 5 more jobs. (since there are 10 messages in total)

```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
...
  maxReplicaCount: 20
  pollingInterval: 10
  rollout: {}
  scalingStrategy: {}
  successfulJobsHistoryLimit: 3
  triggers:
  - metadata:
      hostFromEnv: RABBITMQ_FULL_HOST # It is amqp
      mode: QueueLength
      queueName: my_queue_name
      value: "1"
    type: rabbitmq
```

I tried setting       excludeUnackowledged to "true" or "false", the behaviour stays the same

### Expected Behavior

5 more jobs get scheduled

### Actual Behavior

No job get scheduled

### Steps to Reproduce the Problem

Set up keda with:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
...
  maxReplicaCount: 20
  pollingInterval: 10
  rollout: {}
  scalingStrategy: {}
  successfulJobsHistoryLimit: 3
  triggers:
  - metadata:
      hostFromEnv: RABBITMQ_FULL_HOST # It is amqp
      mode: QueueLength
      queueName: my_queue_name
      value: "1"
    type: rabbitmq
```

And have 5 ready, 5 unacknowledged jobs on rabbitMq

### KEDA Version

2.16.1

### Kubernetes Version

None

### Platform

Amazon Web Services

### Scaler Details

RabbitMq

### Anything else?

v1.29.13-eks-8cce635
