### ISSUE TITLE
azure-data-explorer Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alexhu20** [kedacore/keda#6620]
### Report

I have a snippet of the following scaler object but keep getting the admission webhook errors
```
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: azure-data-explorer-trigger-auth
spec:
  podIdentity:
    provider: azure-workload
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: skynetd-azure-data-explorer-scaler
  namespace: some-namespace
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
    validations.keda.sh/hpa-ownership: "true"
spec:
  scaleTargetRef:
    name: some-service-primary
  pollingInterval: 30
  cooldownPeriod: 45
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: azure-data-explorer
    metadata:
      databaseName: some-telemetry
      endpoint: https://adx.westeurope.kusto.windows.net
      query: |
        requests
        | where cloud_ClusterName contains "wu"
        | where timestamp > ago(30m)
        | summarize count() by bin(timestamp, 1s)
        | top 1 by count_ 
      threshold: "20"
    authenticationRef:
      name: azure-data-explorer-trigger-auth
```

### Expected Behavior

Should apply the scaler object

### Actual Behavior

throwing the error with exception
```
keda-admission-webhooks-689dffbb44-9z8tv net/http.(*ServeMux).ServeHTTP                                                                                  │
│ keda-admission-webhooks-689dffbb44-9z8tv     /usr/local/go/src/net/http/server.go:2747                                                                   │
│ keda-admission-webhooks-689dffbb44-9z8tv net/http.serverHandler.ServeHTTP                                                                                │
│ keda-admission-webhooks-689dffbb44-9z8tv     /usr/local/go/src/net/http/server.go:3210                                                                   │
│ keda-admission-webhooks-689dffbb44-9z8tv net/http.(*conn).serve                                                                                          │
│ keda-admission-webhooks-689dffbb44-9z8tv     /usr/local/go/src/net/http/server.go:2092                                                                   │
│ keda-admission-webhooks-689dffbb44-9z8tv 2025-03-13T01:29:06Z    ERROR    admission    Observed a panic    {"webhookGroup": "keda.sh", "webhookKind": "S │
│ caledObject", "ScaledObject": {"name":"skynetd-azure-data-explorer-scaler","namespace":"golden-gate"}, "namespace": "golden-gate", "name": "skynetd-azur │
│ e-data-explorer-scaler", "resource": {"group":"keda.sh","version":"v1alpha1","resource":"scaledobjects"}, "user": "alex.hu@uipath.com", "requestID": "01 │
│ 663ead-62c1-416c-8520-3e7419143cbc", "panic": "runtime error: invalid memory address or nil pointer dereference", "panicGoValue": "\"invalid memory addr │
│ ess or nil pointer dereference\"", "stacktrace": "goroutine 2128 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x1dd7be8, 0xc0006659e0}, {0 │
│ x18e0460, 0x2b4c070})\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/webhook/admissi │
│ on.(*Webhook).Handle.func1()\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:163 +0x103\npanic({0x18e0460?, 0x2b4c0 │
│ 70?})\n\t/usr/local/go/src/runtime/panic.go:785 +0x132\ngithub.com/kedacore/keda/v2/apis/keda/v1alpha1.verifyHpas(0xc000662d88, {0x1b17232, 0x6}, 0x6?)\ │
│ n\t/workspace/apis/keda/v1alpha1/scaledobject_webhook.go:268 +0xd17\ngithub.com/kedacore/keda/v2/apis/keda/v1alpha1.validateWorkload(0xc000662d88, {0x1b │
│ 17232, 0x6}, 0x0)\n\t/workspace/apis/keda/v1alpha1/scaledobject_webhook.go:160 +0xdf\ngithub.com/kedacore/keda/v2/apis/keda/v1alpha1.(*ScaledObject).Val │
│ idateCreate(0xc000662d88, 0xc000398366)\n\t/workspace/apis/keda/v1alpha1/scaledobject_webhook.go:118 +0x10f\ngithub.com/kedacore/keda/v2/apis/keda/v1alp │
│ ha1.ScaledObjectCustomValidator.ValidateCreate({}, {0x1dd7be8?, 0xc000665a10?}, {0x1dc23a0, 0xc000662d88})\n\t/workspace/apis/keda/v1alpha1/scaledobject │
│ _webhook.go:90 +0xe5\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*validatorForType).Handle(_, {_, _}, {{{0xc000583d10, 0x24}, {{0xc000398148, │
│  0x7}, {0xc000398220, 0x8}, {0xc000398230, ...}}, ...}})\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator_custom.go:9 │
│ 1 +0x2b6\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(_, {_, _}, {{{0xc000583d10, 0x24}, {{0xc000398148, 0x7}, {0xc000398220, │
│  0x8}, {0xc000398230, ...}}, ...}})\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:181 +0x224\nsigs.k8s.io/control │
│ ler-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc000023e00, {0x7f4e83728548, 0xc0001ed590}, 0xc00009f900)\n\t/workspace/vendor/sigs.k8s.io/cont │
│ roller-runtime/pkg/webhook/admission/http.go:119 +0xaf0\nsigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics.InstrumentedHook.InstrumentHandlerI │
│ nFlight.func1({0x7f4e83728548, 0xc0001ed590}, 0xc00009f900)\n\t/workspace/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_serv │
│ er.go:60 +0xbc\nnet/http.HandlerFunc.ServeHTTP(0x2b54280?, {0x7f4e83728548?, 0xc0001ed590?}, 0xc0000398d8?)\n\t/usr/local/go/src/net/http/server.go:2220 │
│  +0x29\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x1dc9fa0?, 0xc000034b60?}, 0xc00009f900)\n\t/workspace/ │
│ vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:147 +0xc3\nnet/http.HandlerFunc.ServeHTTP(0x1a14580?, {0x1dc9fa0?, 0 │
│ xc000034b60?}, 0xc000039a20?)\n\t/usr/local/go/src/net/http/server.go:2220 +0x29\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHand │
│ lerDuration.func2({0x1dc9fa0, 0xc000034b60}, 0xc00009f900)\n\t/workspace/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_serve │
│ r.go:109 +0xc2\nnet/http.HandlerFunc.ServeHTTP(0xc00019b420?, {0x1dc9fa0?, 0xc000034b60?}, 0x3?)\n\t/usr/local/go/src/net/http/server.go:2220 +0x29\nnet │
│ /http.(*ServeMux).ServeHTTP(0x410b25?, {0x1dc9fa0, 0xc000034b60}, 0xc00009f900)\n\t/usr/local/go/src/net/http/server.go:2747 +0x1ca\nnet/http.serverHand │
│ ler.ServeHTTP({0x1dc2db8?}, {0x1dc9fa0?, 0xc000034b60?}, 0x6?)\n\t/usr/local/go/src/net/http/server.go:3210 +0x8e\nnet/http.(*conn).serve(0xc0002bd830,  │
│ {0x1dd7be8, 0xc000592210})\n\t/usr/local/go/src/net/http/server.go:2092 +0x5d0\ncreated by net/http.(*Server).Serve in goroutine 85\n\t/usr/local/go/src │
│ /net/http/server.go:3360 +0x485\n"}
```

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

None

### Kubernetes Version

None

### Platform

None
