### ISSUE TITLE
SQS Trigger Error: invalid header field value for "Authorization"

### ISSUE THREAD

**Issue by sangloe** [kedacore/keda#6656]
I'm following the docs [here](https://keda.sh/docs/2.16/scalers/aws-sqs/) and am using the example [here](https://keda.sh/docs/2.16/scalers/aws-sqs/#scaling-a-deployment-using-iam-users).

I've created an SQS queue in the aws console and have verified that I can get the queue attributes with the same credentials I've included in the secret that the docs mention.

Here are my Keda resources:

```yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: keda
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID
    name: keda-aws-creds
    key: AWS_ACCESS_KEY_ID
  - parameter: awsSecretAccessKey
    name: keda-aws-creds
    key: AWS_SECRET_ACCESS_KEY
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: keda
spec:
  scaleTargetRef:
    name: nginx-deployment
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: https://sqs.us-east-1.amazonaws.com/<account>/<sqs-name>
      queueLength: "5"
      awsRegion: "us-east-1"
```

and here is the app I'm trying to scale:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: keda
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80

```

I've created a secret and have decoded it in my kubernetes cluster to verify that the AWS credential values are correct:

```
Name:         keda-aws-creds
Namespace:    keda
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
AWS_ACCESS_KEY_ID:      21 bytes
AWS_SECRET_ACCESS_KEY:  41 bytes
```

My Keda installation was performed with:

```
helm install keda kedacore/keda --namespace keda --create-namespace
```

It seems that no matter what I do, Keda cannot connect to my queue for attribute info.  I get the following error in the operator:

```
2025-03-27T04:38:04Z    ERROR   scale_handler   error getting metric for trigger        {"scaledObject.Namespace": "keda", "scaledObject.Name": "aws-sqs-queue-scaledobject", "trigger": "awsSqsQueueScaler", "error": "operation error SQS: GetQueueAttributes, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post \"https://sqs.us-east-1.amazonaws.com/\": net/http: invalid header field value for \"Authorization\""}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
        /workspace/pkg/scaling/scale_handler.go:553
github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
        /workspace/pkg/metricsservice/server.go:48
github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
        /workspace/pkg/metricsservice/api/metrics_grpc.pb.go:111
google.golang.org/grpc.(*Server).processUnaryRPC
        /workspace/vendor/google.golang.org/grpc/server.go:1394
google.golang.org/grpc.(*Server).handleStream
        /workspace/vendor/google.golang.org/grpc/server.go:1805
google.golang.org/grpc.(*Server).serveStreams.func2.1
        /workspace/vendor/google.golang.org/grpc/server.go:1029
2025-03-27T04:38:06Z    ERROR   aws_sqs_queue_scaler    Error getting queue length      {"type": "ScaledObject", "namespace": "keda", "name": "aws-sqs-queue-scaledobject", "error": "operation error SQS: GetQueueAttributes, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post \"https://sqs.us-east-1.amazonaws.com/\": net/http: invalid header field value for \"Authorization\""}
github.com/kedacore/keda/v2/pkg/scalers.(*awsSqsQueueScaler).GetMetricsAndActivity
        /workspace/pkg/scalers/aws_sqs_queue_scaler.go:226
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
        /workspace/pkg/scaling/cache/scalers_cache.go:151
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
        /workspace/pkg/scaling/scale_handler.go:758
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState.func1
        /workspace/pkg/scaling/scale_handler.go:633
```

It seems like Keda isn't able to see my credentials?  I've ensured that the secret and all other Keda objects are in the same namespace.  Any help would be appreciated!
