### ISSUE TITLE
Expression language feature not working in "scaling modifiers"

### ISSUE THREAD

**Issue by Oscaarjs** [kedacore/keda#6661]
### Report

I'm trying to keep my system on during office hours (I'm aware of the cron trigger, but I'm using scalingModifers so afaik I cant use in the way I want. Therefore I wanted to incorporate this functionality as a part of my scalingModifiers formula.

I tried to add this formula as part of the scalingModifers formula: 

`(now().Hour() >= 7 && now().Hour() < 16 && int(now().Weekday()) >= 1 && int(now().Weekday()) <= 5) ? 1 : 0`

### Expected Behavior

According to the docs [https://keda.sh/docs/2.16/reference/scaledobject-spec/#scalingmodifiersformula](url), it uses the language expr-lang. And in the playground at [https://expr-lang.org/playground](url) this command works fine.

### Actual Behavior

But I'm getting: 
```
unknown name core_running_files_indexer_duration_seconds (3:5)
 |     core_running_files_indexer_duration_seconds + 1,
 | ....^ && cannot patch "core-namer-scaledobject" with kind ScaledObject: admission webhook "vscaledobject.kb.io" denied the request: error validating formula in ScalingModifiers
invalid operation: int(time.Weekday) (7:4)
 |    int(now().Weekday()) >= 1 && int(now().Weekday()) <= 5) ? 1 : 0
 | ...^ && cannot patch "core-pre-indexer-scaledobject" with kind ScaledObject: admission webhook "vscaledobject.kb.io" denied the request: error validating formula in ScalingModifiers
unexpected token EOF (8:1)
 | )
 | ^ && cannot patch "core-segmenter-scaledobject" with kind ScaledObject: admission webhook "vscaledobject.kb.io" denied the request: error validating formula in ScalingModifiers
invalid operation: int(time.Weekday) (7:4)
 |    int(now().Weekday()) >= 1 && int(now().Weekday()) <= 5) ? 1 : 0
 | ...^ && cannot patch "core-transcriber-kb-scaledobject" with kind ScaledObject: admission webhook "vscaledobject.kb.io" denied the request: error validating formula in ScalingModifiers
invalid operation: int(time.Weekday) (7:4)
 |    int(now().Weekday()) >= 1 && int(now().Weekday()) <= 5) ? 1 : 0
 | ...^
```

### Steps to Reproduce the Problem

Add this formula as part of a scalingModifer formula.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.13.1

### Kubernetes Version

1.32

### Platform

Google Cloud

**Comment by JorTurFer** [comment]
Hello
Can you share your ScaledObject? I've checked and the code in theory parses the expression correctly

**Comment by Oscaarjs** [comment]
@JorTurFer Hello!

Ofc, this is an example of how I intend (try to) use it. Idea being that if either of my custom prometheus metrics are active (`core_running_files_transcription_kb_duration_seconds ` or `core_running_files_transcription_kb_count `) OR if its "office hours" I want there to be at least 1 replica.

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: core-transcriber-kb-scaledobject
  namespace: default
  labels:
    app.kubernetes.io/name: core-transcriber-kb
    app.kubernetes.io/part-of: core    
spec:
  scaleTargetRef:
    kind: Deployment
    name: core-transcriber-kb
  idleReplicaCount: 0
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 10
  cooldownPeriod: 3600
  fallback:
    failureThreshold: 3
    replicas: 1
  advanced:
    restoreToOriginalReplicaCount: true
    scalingModifiers:
      formula: >
        max(
          min(
            core_running_files_transcription_kb_duration_seconds + 1,
            core_running_files_transcription_kb_count * 3600
          ),
          (now().Hour() >= 7 && now().Hour() < 16 && 
           int(now().Weekday()) >= 1 && int(now().Weekday()) <= 5) ? 1 : 0
        )
      target: "3600"
      activationTarget: "0"
      metricType: AverageValue
  triggers:
    - type: prometheus
      name: core_running_files_transcription_kb_duration_seconds
      metadata:
        serverAddress: <prom adress>
        metricName: core_running_files_transcription_kb_duration_seconds
        query: "sum(core_running_files_transcription_kb_duration_seconds{namespace='default'})"
    - type: prometheus
      name: core_running_files_transcription_kb_count
      metadata:
        serverAddress: <prom adress>
        metricName: core_running_files_transcription_kb_count
        query: "sum(core_running_files_transcription_kb_count{namespace='default'})"
```
