### ISSUE TITLE
Encountering issues retrieving metric data from CloudWatch when using more than one dimension in the query.

### ISSUE THREAD

**Issue by tushar-rahinj** [kedacore/keda#6685]
### Report

We are using AWS Cloudwatch scaler. When utilising expression and one dimension, everything works as expected, however when the metric has more than one dimension, the scaler does not retrieve metrics data and default values are returned. 

### Expected Behavior

Using below triggers we expect to retrieve data from cloudwatch, but this is not happening
```
triggers:
- metadata:
        awsRegion: region
      defaultMetricCollectionTime: "60"
      defaultMetricStat: Average
      defaultMetricStatPeriod: "60"
      dimensionName: Cluster Name;Consumer Group;Topic
      dimensionValue: Cluster Name value;Consumer Group value;Topic value
      identityOwner: operator
      metricName: SumOffsetLag
      minMetricValue: "0"
      namespace: AWS/Kafka
      targetMetricValue: "100"
   type: aws-cloudwatch
```

### Actual Behavior

Getting below error:
INFO	aws_cloudwatch_scaler	empty metric data received, returning minMetricValue

### Steps to Reproduce the Problem

1. Create the trigger
2. See that metrics value is not returned from keda

### Logs from KEDA operator

```
INFO	aws_cloudwatch_scaler	empty metric data received, returning minMetricValue
```

### KEDA Version

2.16.1

### Kubernetes Version

1.30

### Platform

Amazon Web Services

### Scaler Details

aws-cloudwatch

### Anything else?

I have already applied the below fix by upgrading the helm chart to 2.16.1, however the issue still persists.
https://github.com/kedacore/keda/issues/6236
