### ISSUE TITLE
AWS EKS Pod Identity Authentication Provider Support (Not IRSA)

### ISSUE THREAD

**Issue by scottblack1** [kedacore/keda#6706]
### Proposal

Hi folks,

Based on the Keda authentication-providers documentation here; https://keda.sh/docs/2.17/authentication-providers/aws/ it looks like we currently support IRSA as the Pod Identity Mechanism.

As of EKS November 2023 EKS now supports AWS EKS Pod Identity using a new mechanism; https://aws.amazon.com/blogs/containers/amazon-eks-pod-identity-a-new-way-for-applications-on-eks-to-obtain-iam-credentials/

There are a good few use cases for requiring this functionality. For example, allowing us to use the same IAM role across multiple clusters / etc. IRSA has a limitation in this regard based on the AssumeRolePolicy Document size. I have added more in the Use-Case section.

1. If this is already supported it would be great to update the docs section to include this as an auth pattern (I could not see anything re this in any release notes)
2. If this is not supported currently, is there any timelines on when we are expecting to add this? Is this planned?

Thanks very much for any engagement ,

Scott

### Use-Case

Primarily, this would allow the same IAM role to be used across multiple clusters / regions etc without the need to continually update the roles AssumeRole policy. This makes things like blue / green upgrades and managing DR etc much easier.

One of the main benefits of this new mechanism as mentioned above is that there is no limitation re the number of clusters that can use the IAM role.

### Is this a feature you are interested in implementing yourself?

No

**Comment by zarko-a** [comment]
I was wondering the same thing. The docs mention pod identity, but it seems it's more in a generic sense than the actual EKS Pod Identity as a feature of EKS. 

Would be good to get clarification around this.

**Comment by zarko-a** [comment]
Looks like EKS pod-identity (non-IRSA) does indeed work with Keda

Here is our config provisioned with crossplane for cross account access.

```
apiVersion: eks.aws.upbound.io/v1beta1
kind: PodIdentityAssociation
metadata:
  name: keda
  namespace: keda
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  providerConfigRef:
    name: aws-crossplane-non-prod
  forProvider:
    clusterName: non-prod
    namespace: keda
    region: us-east-1
    roleArnRef:
      name: keda-non-prod
    serviceAccount: keda-operator
```

```
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: keda-non-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-60"
spec:
  providerConfigRef:
    name: aws-crossplane-non-prod
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Resource": "arn:aws:iam::111122223333:role/keda-cross-account-non-prod",
            "Action": ["sts:AssumeRole", "sts:TagSession"]
          }
        ]
      }
```
```
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: keda-non-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  providerConfigRef:
    name: aws-crossplane-non-prod
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [{
          "Effect": "Allow",
          "Principal": {
            "Service": "pods.eks.amazonaws.com"
          },
          "Action": ["sts:AssumeRole","sts:TagSession"]
          }]
      }
    managedPolicyArnsRefs:
      - name: keda-non-prod
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: keda-cross-account-non-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  providerConfigRef:
    name: aws-crossplane-management
  forProvider:
    assumeRolePolicy: |
      {
        "Version" : "2012-10-17",
        "Statement" : [
          {
            "Effect" : "Allow",
            "Principal" : {
              "AWS" : "arn:aws:iam::111122223333:role/keda-non-prod"
            },
            "Action" : ["sts:AssumeRole", "sts:TagSession"]
          }
        ]
      }
    managedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSQSReadOnlyAccess

```
```
---
# Source: keda/templates/clusterTriggerAuth.yaml
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: keda-aws-auth
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  podIdentity:
    provider: aws
    roleArn: arn:aws:iam::111122223333:role/keda-cross-account-non-prod

```
