### ISSUE TITLE
Replicas fluctuating with cron trigger

### ISSUE THREAD

**Issue by asobti** [kedacore/keda#6709]
### Report

We have a ScaledObject configured with `minReplicas=0` and a cron trigger to scale it up during certain hours up to `desiredReplicas=45`. ScaledObject is as below:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
   annotations:
      scaledobject.keda.sh/transfer-hpa-ownership: "true"
   name: foo-deployment
   namespace: foo-namespace
spec:
   advanced:
      horizontalPodAutoscalerConfig:
         behavior:
            scaleDown:
               policies:
                  - periodSeconds: 60
                     type: Percent
                     value: 5
         name: foo-deployment
   maxReplicaCount: 56
   minReplicaCount: 0
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: foo-deployment
   triggers:
      - metadata:
            desiredReplicas: "45"
            end: "0 15 * * 0-4"
            start: "0 3 * * 1-5"
            timezone: America/Los_Angeles
         type: cron
```

However, what we observe is that during the cron-period the number of replicas fluctuates between 47 and 50:

<img width="1709" alt="Image" src="https://github.com/user-attachments/assets/fdddd531-f255-4dc1-8306-725352515ffc" />

We have another deployment configured the same way except with `desiredReplicas=30` and we don't see the same behavior there.

### Expected Behavior

Deployment will scale to 45 replicas during the cron time window

### Actual Behavior

Deployment scale fluctuates between 47 and 50

### Steps to Reproduce the Problem

1. Create a Deployment with a ScaledObject as pasted above
2. Wait for deployment to scale as per cron window
3. Observe replicas are not stable

### Logs from KEDA operator

```
example
```

### KEDA Version

< 2.15.0

### Kubernetes Version

< 1.29

### Platform

Google Cloud

### Scaler Details

Cron

### Anything else?

Running Keda v2.13
