### ISSUE TITLE
KEDA scales down deployments even when pods are actively processing messages

### ISSUE THREAD

**Issue by shameemshah** [kedacore/keda#6719]
### Report

Hi team,

I'm using KEDA to scale my consumer deployments in Kubernetes.
However, I've noticed an issue where KEDA scales down the deployment even when a pod is still actively processing a message.

In our setup, we acknowledge (ack) messages only after processing is fully completed.
But KEDA sometimes scales down the pod before the processing finishes, which causes the running tasks to get interrupted.

Below is an example of the ScaledObject configuration we are using (with renamed identifiers):

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-consumer-runner
  namespace: demo-namespace
spec:
  scaleTargetRef:
    name: demo-consumer-runner
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 10
  cooldownPeriod: 360
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
    restoreToOriginalReplicaCount: true
  triggers:
  - type: rabbitmq
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
    metadata:
      queueName: demo_task_queue
      protocol: http
      mode: QueueLength
      value: "1"
```

# Environment:
      KEDA Version: 2.15.1
      Kubernetes Version: v1.30.9
      Scaler Type: RabbitMQ (mode: QueueLength)

Questions:

Is there a recommended way to prevent scaling down active pods?

Should we adjust the cooldownPeriod or is there a better approach?

Would implementing a custom metric for "in-progress" jobs help in this case?

Additional Context:

We're using the RabbitMQ scaler with mode: QueueLength.
We poll every 10 seconds and have a 5-minute stabilization window for scale-down configured.

Thank you for your help!

### Expected Behavior

KEDA should ideally not scale down a pod that is still actively processing a message, or there should be a way to configure this behavior.
We would expect that scale-down actions only happen after a pod has completed its task or is truly idle.

### Actual Behavior

When a pod picks up a message from the RabbitMQ queue, it immediately begins processing the task. However, since the scaler is based on the queue length, once the queue becomes empty (because the message has been picked up but not yet acknowledged), KEDA assumes there is no more work and proceeds to scale down the deployment. As a result, the pod that is still actively processing the task gets terminated before it finishes its work, leading to incomplete processing and potential data inconsistencies.

### Steps to Reproduce the Problem

1. Deploy a consumer application that fetches messages from a RabbitMQ queue and processes them. Ensure that the application acknowledges the message **only after the full processing is completed**.
2. Set up a KEDA `ScaledObject` with the RabbitMQ scaler using `mode: QueueLength` and configure scaling parameters similar to the ones shared above (e.g., polling interval of 10 seconds, cooldown period of 360 seconds, and stabilization window of 300 seconds).
3. Publish a message to the queue so that the consumer pod picks it up and starts processing.
4. Observe that after the message is dequeued (but before the processing is completed and acknowledged), KEDA detects that the queue length has dropped to zero.
5. Notice that KEDA initiates a scale-down event and terminates the pod, causing the ongoing processing to be interrupted.

### KEDA Version

2.15.1

### Kubernetes Version

1.30

### Platform

Google Cloud

### Scaler Details

Rabbitmq
