### ISSUE TITLE
Support for Resetting to minReplicaCount After `end` time with `scaleDown.selectPolicy: Disabled` in `cron` scaler

### ISSUE THREAD

**Issue by eminaktas** [kedacore/keda#6726]
### Proposal

I would like KEDA to support a mechanism that allows a ScaledObject to reset the replica count to minReplicaCount after `end` time with `scaleDown.selectPolicy: Disabled`.

Currently, I use a combination of `cron` and `memory` triggers, along with:

```yaml
advanced:
  horizontalPodAutoscalerConfig:
    behavior:
      scaleDown:
        selectPolicy: Disabled
```

This correctly prevents scale-in during working hours. However, once those hours are over, I want the deployment to scale back down to its defined minReplicaCount — but it doesn’t. `cron` supports scaling the deployment to 0 if the minReplicaCount is set to 0 but we always want to have available some number of pods.

Even with a cron trigger specifying a lower desiredReplicas, the deployment remains at the higher replica count.

A new option (e.g. resetToMinReplicaCount: true) or time-aware behavior control would be very helpful here.

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-out-only
  namespace: keda
spec:
  scaleTargetRef:
    name: hello-kubernetes
    # kind: StatefulSet
  minReplicaCount: 2
  maxReplicaCount: 12
  triggers:
  - type: cron
    metadata:
      timezone: "Europe/Amsterdam"
      start: 0 7 * * *  
      end: 0 16 * * *
      desiredReplicas: "2"
  - type: memory
    metricType: Utilization
    metadata:
      value: "60"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          selectPolicy: Disabled
```

### Use-Case

This would allow teams to keep services scaled up during peak business hours without risk of scale-in, while automatically scaling them down to minReplicaCount off-hours — without needing to patch or delete the ScaledObject, or run external cronjobs.

It simplifies autoscaling policies that follow clear day/night or weekday/weekend cycles and reduces infrastructure cost without losing responsiveness.

### Is this a feature you are interested in implementing yourself?

Maybe
