### ISSUE TITLE
Errors with KEDA and the Kafka scaler

### ISSUE THREAD

**Issue by paramjeet01** [kedacore/keda#6770]
### Report

We are encountering some errors with KEDA and the Kafka scaler. Initially, we see the following error:

Error log :
```
source:keda-operator-6cc75b98d7-x77tz container-name:keda-operator message:2025-04-22T21:26:21Z 
ERROR scale_handler error getting scale decision {"scaledObject.Namespace": "mynamespace", "scaledObject.Name": "cw-processor-eks", "scaler": "kafkaScaler", "error": "scaler with id 2 not found. Len = 0"}
```

Scaledobject config :

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
  finalizers:
  - finalizer.keda.sh
  labels:
    scaledobject.keda.sh/name: cw-processor-eks
  name: cw-processor-eks
  namespace: mynamespace
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      name: cw-processor-eks
    scalingModifiers: {}
  maxReplicaCount: 100
  minReplicaCount: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cw-processor-eks
  triggers:
  - metadata:
      value: "60"
    metricType: Utilization
    type: cpu
  - metadata:
      value: "70"
    metricType: Utilization
    type: memory
  - metadata:
      activationLagThreshold: "0"
      allowIdleConsumers: "false"
      bootstrapServers: broker-endpoint
      consumerGroup: cw-consumer-group
      excludePersistentLag: "false"
      lagThreshold: "4500"
      offsetResetPolicy: latest
      scaleToZeroOnInvalidOffset: "false"
      topic: ""
    type: kafka
  externalMetricNames:
  - cw-group-topics
  health:
    cw-group-topics:
      numberOfFailures: 0
      status: Happy
  hpaName: cw-processor-eks
  originalReplicaCount: 1
  resourceMetricNames:
  - cpu
  - memory
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment
```

### Expected Behavior

The errors should not be thrown during the scale decision.

### Actual Behavior

We are seeing errors during scale decision.

### Steps to Reproduce the Problem

1. Deploy a scaledobject with kafka scaler
2. Increase the workload in kafka
3. Look at the keda logs

### Logs from KEDA operator

```
source:keda-operator-6cc75b98d7-x77tz container-name:keda-operator message:2025-04-22T21:26:21Z 
ERROR scale_handler error getting scale decision {"scaledObject.Namespace": "mynamespace", "scaledObject.Name": "cw-processor-eks", "scaler": "kafkaScaler", "error": "scaler with id 2 not found. Len = 0"}
```

### KEDA Version

2.16.0

### Kubernetes Version

1.31

### Platform

Amazon Web Services

### Scaler Details

Kafka
