### ISSUE TITLE
KEDA DatadogAgent feature sends all the triggers to the agent

### ISSUE THREAD

**Issue by dumitraand** [kedacore/keda#6776]
### Report

When using a datadog scaler with `useClusterAgentProxy: true` and multiple triggers (such as `cron`) in a scaled object, KEDA sends _**all the metrics/triggers**_ to the datadog agent instead of sending only the `datadog` ones:

For example, using this Scaled Object
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-scaledobject
  namespace: staging
  labels:
    app.kubernetes.io/name: "my-app"
    app.kubernetes.io/version: "v1.0.0"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  pollingInterval: 30
  minReplicaCount: 2
  maxReplicaCount: 5
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      name: keda-autoscaler
      behavior:
        scaleDown:
          policies:
            - type: Pods
              value: 1
              periodSeconds: 600
            - type: Percent
              value: 5
              periodSeconds: 600
          stabilizationWindowSeconds: 600
        scaleUp:
          policies:
            - type: Pods
              value: 1
              periodSeconds: 120
            - type: Percent
              value: 10
              periodSeconds: 120
          stabilizationWindowSeconds: 120
  triggers:
    - type: datadog
      metricType: Value
      metadata:
        useClusterAgentProxy: "true"
        datadogMetricName: queue-duration
        datadogMetricNamespace: staging
        targetValue: "500"
        age: "90"
      authenticationRef:
        name: app-keda-datadog-trigger-auth
    - type: cron
      metadata:
        timezone: "Europe/Paris"
        start: "0 8 * * *"
        end: "0 10 * * *"
        desiredReplicas: "4"
    - type: cron
      metadata:
        timezone: "Europe/Paris"
        start: "0 13 * * *"
        end: "0 15 * * *"
        desiredReplicas: "4"
```

### Expected Behavior

- DatadogAgent receives queries just for the triggers which have `type: datadog` and `useClusterAgentProxy: true`
- The HPA behaves and scales correctly

### Actual Behavior

- DatadogAgent errors out with a log similar to:
```
cluster-agent unable to parse median_3(p95:my_app.requests.queue_duration{env:stage}),avg:s1-cron-Europe-Paris-09xxx-010xxx{scaledobject.keda.sh/name:my-scaledobject}.rollup(30),avg:s2-cron-Europe-Paris-015xxx-016xxx{scaledobject.keda.sh/name:my-scaledobject}.rollup(30): Rule 'query_expr' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with ',avg:s1-cron-Europe-' (line 1, column 62).
```
given it receives in the qurey also the `cron` triggers
- The HPA errors and it's in an invalid state

### Steps to Reproduce the Problem

1. Create a scaledObject with a `datadog` trigger using the `useClusterAgentProxy: true` feature ([DatadogAgent Experimental](https://keda.sh/docs/2.17/scalers/datadog/#using-the-datadog-cluster-agent-experimental))
2. Observe that it behaves correctly
3. Add a `cron` trigger alongside Datadog
5. The HPA will be broken and KEDA operator as well as the datadog agent will error out

### Logs from KEDA operator

```
{"level":"ERROR","scaledObject":{"Namespace":"staging","Name":"my-scaledobject"},"scaler":"datadogScaler","timestamp":1747220336000,"error":"error getting metric value: error getting metric value: Internal error occurred: DatadogMetric is invalid, err: Global error (all queries) from backend, invalid syntax in query? Check Cluster Agent leader logs for details"}
```

### KEDA Version

2.17.0

### Kubernetes Version

1.30

### Platform

Amazon Web Services
