### ISSUE TITLE
Replica Scaled Down is not waiting for  Cooldown Period + Cron Schedule End Parameter

### ISSUE THREAD

**Issue by kachi-app** [kedacore/keda#6787]
### Report

I have this ScaledObject where cooldownPeriod is 1.5 hours, with end cron at 15:30.

### Expected Behavior

Pod's replica count will scale to 0 at 17:00. Based on the documentation also said `By default the ScaledObject cooldownPeriod is 5 minutes, so the actual scaling down will happen 5 minutes after the cron schedule end parameter`. https://keda.sh/docs/2.14/scalers/cron/#scale-to-0-during-off-hours

### Actual Behavior

Pod scaledDown right at the cron schedule end parameter

<img width="1533" alt="Image" src="https://github.com/user-attachments/assets/f8c4e456-4f16-4d4b-aacd-fd6d52974aec" />

### Steps to Reproduce the Problem

Set cooldownPeriod, and the cron triggers. wait for trigger state change from active to inactive.
```
spec:
  cooldownPeriod: 5400
  maxReplicaCount: 1
  minReplicaCount: 0
  scaleTargetRef:
    name: task
  triggers:
    - metadata:
        httpScaledObject: task
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
      type: external-push
    - metadata:
        desiredReplicas: '1'
        end: 30 15 * * 1-5
        start: 0 10 * * 1-5
        timezone: Asia/Makassar
      type: cron
    - metadata:
        desiredReplicas: '1'
        end: 30 23 * * *
        start: 0 22 * * *
        timezone: Asia/Makassar
      type: cron
```

### Logs from KEDA operator

```
example
```

### KEDA Version

2.17.0

### Kubernetes Version

1.32

### Platform

Google Cloud

### Scaler Details

Cron, HttpScaledObject
