### ISSUE TITLE
ScaledObject Fails for Cluster-Scoped CRD

### ISSUE THREAD

**Issue by zfraziercoreweave** [kedacore/keda#6798]
### Report

When a KEDA `ScaledObject` targets a cluster-scoped Custom Resource (CR) that has a `/scale` subresource, KEDA (tested with v2.16.0 and v2.17.0) appears to incorrectly attempt to query the Kubernetes API server using the `meta.k8s.io` API group for the target resource, instead of using the API group specified in the `ScaledObject`'s `spec.scaleTargetRef.apiVersion`. This results in the `ScaledObject` failing to become Ready with a `ScaledObjectCheckFailed` reason, citing that the `scaleTargetRef` specification is incorrect due to the server not finding the resource under `meta.k8s.io`.

### Expected Behavior

We expected KEDA to:
1. Honor the `apiVersion` (e.g., `compute.coreweave.com/v1alpha1`) provided in the `ScaledObject`'s `spec.scaleTargetRef`.
2. Correctly discover and interact with the `/scale` subresource of the target cluster-scoped CR using its specified API group (`compute.coreweave.com`).
3. The `ScaledObject` should become `Ready: True`, indicating it can successfully monitor and scale the target resource.
4. For a `cron` trigger, the target resource's replica count should be updated according to the `desiredReplicas` when the cron schedule is active.

### Actual Behavior

1. The KEDA `ScaledObject` consistently fails to become `Ready: True`.
2. The status of the `ScaledObject` shows:
   - `type: Ready`, `status: "False"`, `reason: ScaledObjectCheckFailed`
   - `message: ScaledObject doesn't have correct scaleTargetRef specification`
3. KEDA operator logs show repeated errors indicating KEDA is trying to query the wrong API group:
   `ERROR Target resource doesn't expose /scale subresource ... "error": "the server could not find the requested resource (get nodepools.meta.k8s.io <target-resource-name>)"`
   `ERROR ScaledObject doesn't have correct scaleTargetRef specification ... "error": "the server could not find the requested resource (get nodepools.meta.k8s.io <target-resource-name>)"`
4. Due to the `ScaledObject` not being Ready, no scaling actions are performed on the target CR.
5. This behavior was observed with KEDA v2.17.0 and v2.16.0.
6. A test using the same KEDA version to scale a simple *namespaced* CRD (with a `/scale` subresource) worked correctly, with the `ScaledObject` becoming `Ready: True`. This suggests the issue is specific to KEDA's handling of our cluster-scoped CRD.

### Steps to Reproduce the Problem

1. **Environment:**
   * Kubernetes v1.30.x
   * KEDA v2.16.0 or v2.17.0 installed via Helm (e.g., `helm upgrade --install keda kedacore/keda --version 2.17.0 --namespace keda --create-namespace`).

2. **Prerequisites:**
   * Have a cluster-scoped CustomResourceDefinition (CRD) that defines a `/scale` subresource.
     * Example CRD structure (relevant parts):
       ```yaml
       apiVersion: apiextensions.k8s.io/v1
       kind: CustomResourceDefinition
       metadata:
         name: nodepools.compute.coreweave.com # Example: replace with your CRD name
       spec:
         group: compute.coreweave.com      # Example: replace with your API group
         scope: Cluster
         names:
           kind: NodePool                   # Example: replace with your Kind
           plural: nodepools                # Example: replace with your plural
         versions:
         - name: v1alpha1
           served: true
           storage: true
           subresources:
             scale:
               specReplicasPath: .spec.targetNodes      # Path to desired replicas
               statusReplicasPath: .status.currentNodes # Path to current replicas
             status: {}
           # ... (rest of schema)
       ```
   * Create an instance of this cluster-scoped CR (e.g., named `zachs-scaling-test`).
   * Ensure `kubectl scale <your-crd-plural-name> <instance-name> --replicas=N` works directly on this CR instance.

3. **Apply RBAC for KEDA:** Create a `ClusterRole` and `ClusterRoleBinding` to allow the `keda-operator` ServiceAccount (in the `keda` namespace) to `get`, `list`, `watch` your CRD instances and `get`, `update`, `patch` their `/scale` subresource.
   * Example `ClusterRole`:
     ```yaml
     apiVersion: rbac.authorization.k8s.io/v1
     kind: ClusterRole
     metadata:
       name: keda-custom-crd-scaler-role
     rules:
     - apiGroups: ["compute.coreweave.com"] # Your CRD's API group
       resources: ["nodepools"]             # Your CRD's plural name
       verbs: ["get", "list", "watch"]
     - apiGroups: ["compute.coreweave.com"] # Your CRD's API group
       resources: ["nodepools/scale"]       # Your CRD's plural name + /scale
       verbs: ["get", "update", "patch"]
     ```
   * Example `ClusterRoleBinding`:
     ```yaml
     apiVersion: rbac.authorization.k8s.io/v1
     kind: ClusterRoleBinding
     metadata:
       name: keda-custom-crd-scaler-binding
     roleRef:
       apiGroup: rbac.authorization.k8s.io
       kind: ClusterRole
       name: keda-custom-crd-scaler-role
     subjects:
     - kind: ServiceAccount
       namespace: keda
       name: keda-operator
     ```

4. **Create a KEDA ScaledObject:** Apply a `ScaledObject` manifest targeting your cluster-scoped CR instance.
   ```yaml
   apiVersion: keda.sh/v1alpha1
   kind: ScaledObject
   metadata:
     name: test-cluster-crd-scaler
     namespace: default # Or any namespace
   spec:
     scaleTargetRef:
       apiVersion: [compute.coreweave.com/v1alpha1](https://compute.coreweave.com/v1alpha1) # Your CRD's apiVersion
       kind: NodePool                            # Your CRD's Kind
       name: zachs-scaling-test                  # Instance name of your CR
     minReplicaCount: 1
     maxReplicaCount: 5
     pollingInterval: 10
     triggers:
     - type: cron # Using cron for a simple, predictable trigger
       metadata:
         timezone: "Etc/UTC"
         start: "0 * * * *" # Example: top of every hour
         end: "5 * * * *"   # Example: for 5 minutes
         desiredReplicas: "3"

5. Observe:

Check the status of the applied ScaledObject:
kubectl get scaledobject test-cluster-crd-scaler -n default -o yaml
Expected: It should become Ready: True.
Actual: It shows Ready: False with reason: ScaledObjectCheckFailed.

Check the KEDA operator logs:
kubectl logs -n keda <keda-operator-pod-name>
Expected: No errors related to scaleTargetRef.
Actual: Errors indicating KEDA is trying to query meta.k8s.io for the target resource.

### Logs from KEDA operator

 Logs from KEDA operator (provide logs from KEDA operator if need be)**
```text
Key error lines observed repeatedly in KEDA operator (v2.16.0 and v2.17.0) logs when the ScaledObject targeting our cluster-scoped NodePool CRD (`compute.coreweave.com/v1alpha1`) is applied:

`ERROR   Target resource doesn't expose /scale subresource       {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"<scaledobject-name>","namespace":"<namespace>"}, "namespace": "<namespace>", "name": "<scaledobject-name>", "reconcileID": "<id>", "resource": "compute.coreweave.com/v1alpha1.NodePool", "name": "<nodepool-instance-name>", "error": "the server could not find the requested resource (get nodepools.meta.k8s.io <nodepool-instance-name>)"}`

`ERROR   ScaledObject doesn't have correct scaleTargetRef specification  {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"<scaledobject-name>","namespace":"<namespace>"}, "namespace": "<namespace>", "name": "<scaledobject-name>", "reconcileID": "<id>", "error": "the server could not find the requested resource (get nodepools.meta.k8s.io <nodepool-instance-name>)"}`

### KEDA Version

2.17.0

### Kubernetes Version

1.30

### Platform

Other

### Scaler Details

cron

### Anything else?

_No response_
