### ISSUE TITLE
rabbitmq scaler unsafeSsl does not work for amqps

### ISSUE THREAD

**Issue by shysaApk** [kedacore/keda#6823]
### Report

If you pass in a amqps host to the rabbitmq scalar it will require that the certificate is signed, however if you pass in https instead it works as expected.

### Expected Behavior

tls is enabled without validation

### Actual Behavior

Warning KEDAScalerFailed 5m49s (x14 over 66m) keda-operator error establishing rabbitmq connection: tls: failed to verify certificate: x509: certificate signed by unknown authority

### Steps to Reproduce the Problem

1.install keda and rabbitmq
setup a ScaledObject with a config similar to the following
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-consumers-scaledobject
  namespace: ml-serving
spec:
  scaleTargetRef:
    name: queue-consumers
  pollingInterval: 5
  cooldownPeriod: 60
  maxReplicaCount: 10
  minReplicaCount: 1
  triggers:
    - type: rabbitmq
      metadata:
        queueName: prod.tasks.image.parsing
        value: "5"
        mode: QueueLength
        activationValue: "1"
        hostFromEnv: RABBITMQ_URL
        protocol: auto
        tls: "enable"
        unsafeSsl: "true"
      authenticationRef:
        name: rabbitmq-trigger-auth
start the deployment / scaler
notice that it only works if RABBITMQ_URL starts with https instead of amqps

### Logs from KEDA operator

```
 Warning  KEDAScalerFailed         5m49s (x14 over 66m)  keda-operator  error establishing rabbitmq connection: tls: failed to verify certificate: x509: certificate signed by unknown authority
```

### KEDA Version

None

### Kubernetes Version

None

### Platform

None

### Scaler Details

rabbitmq

**Comment by rickbrouwer** [comment]
Related: #6461

**Comment by THE-BRAHMA** [comment]
@shysaApk KEDA's RabbitMQ scaler does not recognize tls fields inside `metadata`. These should be configured in the `TriggerAuthentication` resource.

So the scaler ignores these fields silently, and your connection over TLS fails.

For example the correct way to do it is -
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-consumers-scaledobject
  namespace: ml-serving
spec:
  scaleTargetRef:
    name: queue-consumers
  pollingInterval: 5
  cooldownPeriod: 60
  maxReplicaCount: 10
  minReplicaCount: 1
  triggers:
    - type: rabbitmq
      metadata:
        queueName: prod.tasks.image.parsing
        value: "5"
        mode: QueueLength
        activationValue: "1"
        hostFromEnv: RABBITMQ_URL
        protocol: auto
        unsafeSsl: "true"
      authenticationRef:
        name: rabbitmq-trigger-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  host: <AMQPS URI connection string> # base64 encoded value of format amqps://guest:password@localhost:5672/vhost
  tls: "enable"
  ca: <your ca>
  cert: <your cert>
  key: <your key>
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: ml-serving
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
    - parameter: tls
      name: keda-rabbitmq-secret
      key: tls
    - parameter: ca
      name: keda-rabbitmq-secret
      key: ca
    - parameter: cert
      name: keda-rabbitmq-secret
      key: cert
    - parameter: key
      name: keda-rabbitmq-secret
      key: key
```
