### ISSUE TITLE
rabbitmq scaler does not work with hashicorp vault trigger authentication

### ISSUE THREAD

**Issue by shysaApk** [kedacore/keda#6835]
### Report

The hashicorp vault trigger authentication seems to be ignored. Using a secretTargetRef everything works fine. ( with same values )
I doublechecked vault side and the call from keda seems to be fine.

### Expected Behavior

scaler works correctly with hashicorp vault trigger authentication. 

### Actual Behavior

hashicorp vault trigger authentication seems to be ignored. 

### Steps to Reproduce the Problem

1. create a hashicorp trigger auth like this:  
```
hashiCorpVault:
    address: https://vault-hostname/
    authentication: kubernetes
    credential:
      serviceAccount: /var/run/secrets/kubernetes.io/serviceaccount/token
    role: entity
    mount: mountpoint
    secrets:
      - key: "username"
        parameter: "username"
        path: path/to/secret
        type: secret
      - key: "password"
        parameter: "password"
        path: path/to/secret
        type: secret
      - key: "host"
        parameter: "host"
        path: path/to/secret
        type: secret
      - key: "tls"
        parameter: "tls"
        path: path/to/secret
        type: secret
```
2. attach it to a scaler

### Logs from KEDA operator

`error parsing rabbitmq metadata: error parsing rabbitmq metadata: missing required parameter "host" in [triggerMetadata authParams resolvedEnv]`

### KEDA Version

2.17.0

### Kubernetes Version

1.32

### Platform

aws

### Scaler Details

      triggers:
        - type: rabbitmq
          authenticationRef:
            name: rabbitmq-trigger-auth
          metadata:
            protocol: amqp # Optional. Specifies protocol to use, either amqp or http, or auto to autodetect based on the `host` value. Default value is auto.
            mode: QueueLength # QueueLength or MessageRate
            value: "5" # message backlog or publish/sec. target per instance
            activationValue: "2" # Optional. Activation threshold
            queueName: testqueue
            unsafeSsl: "true"
            #timeout: "1000" # Optional. Custom timeout for the HTTP client used in this scaler
