### ISSUE TITLE
keda not honoring cooldownPeriod.

### ISSUE THREAD

**Issue by simtcrom** [kedacore/keda#6844]
**Issue**
When I set cooldownPeriod (for eg, 60 seconds), A scaled up deployment not scaling down at the expected time.

**How to reproduce the issue**
- setup a deployment with 1 replica. Don't deploy any HPA to manage the deployment.
- setup a cron based scheduler as below,
```
kind: ScaledObject
metadata:
  name: kafka-scaler
  namespace: xxx
spec:
  cooldownPeriod: 60
  maxReplicaCount: 3
  minReplicaCount: 1
  pollingInterval: 5
  scaleTargetRef:
    kind: Deployment
    name: <deployment_name>
  triggers:
  - metadata:
      desiredReplicas: "2"
      end: 17 07 * * 1-5
      start: 13 07 * * 1-5
      timezone: America/New_York
    type: cron
```
- Notice that deployment scale up at start time.
- Notice that, even after 3 minutes (start to end difference) and cooldownPeriod of 60 seconds, deployment not scaled down to 1 replicas.
- If you wait up some more time (I could not get a pattern on how long to wait), you can notice deployment scaled down to 1.

**Expected behavior**
deployment should have scaled down after 3minutes+60 seconds"

**Comment by simtcrom** [comment]
I also tested without cooldownPeriod: 60 maxReplicaCount: 3  pollingInterval: 5, that is as below, still not able to make it scale down at the exact end time. It does scale down after some time (some time after 8 minutes of start time).

```
kind: ScaledObject
metadata:
  name: kafka-scaler
  namespace: xxx
spec:
  minReplicaCount: 1
    kind: Deployment
    name: <deployment_name>
  triggers:
  - metadata:
      desiredReplicas: "2"
      end: 17 07 * * 1-5
      start: 13 07 * * 1-5
      timezone: America/New_York
    type: cron
```
