### ISSUE TITLE
in cron scaler can we have ability to add cron holiday schedule?

### ISSUE THREAD

**Issue by simtcrom** [kedacore/keda#6846]
### Proposal

in cron scaler can we have ability to add holiday schedule?

for example somthing as below,

```
cron_holidays = [
    "2023-10-18",
    "2023-10-19"
  ]
```

so that, cron schedule will not trigger the scaling operation during the cron_holidays specified.

### Use-Case

This would be useful to skip the cron operations on certain days.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rickbrouwer** [comment]
Hi!

You can set multiple triggers, and thus multiple cron triggers.
In theory, you can therefore create a 'holiday period' by specifying an intermediate period, like:

```
  triggers:
    - type: cron
      metadata:
        timezone: Europe/Amsterdam
        start: 0 5 18 6 *
        end: 0 0 18 10 *
        desiredReplicas: "1"
    - type: cron
      metadata:
        timezone: Europe/Amsterdam
        start: 0 0 20 10 *
        end: 0 5 18 6 *
        desiredReplicas: "1"
```
Which, I think, should mean it's always running, except "2023-10-18" and "2023-10-19".
Is this something that helps you?
