### ISSUE TITLE
hashicorp vault pki integration wrong pkiData formatting

### ISSUE THREAD

**Issue by shysaApk** [kedacore/keda#6852]
### Report

Hi team,
I think that keda tries to send wrong formatted data into vault. 
The issue seems to be the formatting of 
            pkiData: 
              commonName: host.com
              altNames: host.com

From what I see in vault log the are sent in camel case but Vault wanted those values with underscores like commont_name

### Expected Behavior

certificate created on vault

### Actual Behavior

error on vault and keda

### Steps to Reproduce the Problem

1. Create a hashicorp vault trigger authentication with these secrets 
```
          - key: certificate
            parameter: cert
            path: pki/issue/role            
            type: pki
            pkiData: 
              commonName: host.com
              altNames: host.com              
            ttl: 1h
```

### Logs from KEDA operator

Keda:
error establishing rabbitmq connection: tls: failed to verify certificate: x509: certificate signed by unknown authority

Vault logs
```
{"mount_point":"pki/","mount_type":"pki","mount_accessor":"pki_xxxxxxx","mount_running_plugin_version":"v1.15.4+builtin.vault","mount_class":"secret","data":{"error":"hmac"},"warnings":["Endpoint ignored these unrecognized parameters: [altNames commonName]"]}}
```

### KEDA Version

2.17.0

### Kubernetes Version

1.32

### Platform

Amazon Web Services
