### ISSUE TITLE
Keda version 2.17.2 use trigger cron with metadata.desiredReplicas: "0", generate error in the operator

### ISSUE THREAD

**Issue by ariefMudahMy** [kedacore/keda#6863]
this is ScaledObject manifest

```
---
# Source: common-app-chart/templates/autoscaler.yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "md-test-cicd"
  namespace: "md-test-cicd"
  labels:
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "common-app-chart-0.1.0"
    app: "md-test-cicd"
    system: "md-test-cicd"
    component: "app"
    team: "md-sre"
    workload: "md-test-cicd"
spec:
  cooldownPeriod: 30
  maxReplicaCount: 3
  minReplicaCount: 1
  pollingInterval: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "md-test-cicd"
  triggers:
  - metadata:
      timezone: Asia/Kuala_Lumpur
      start: 0 18 * * *
      end: 0 19 * * *
      desiredReplicas: "1"
    type: cron
  - metadata:
      timezone: Asia/Kuala_Lumpur
      start: 1 19 * * *
      end: 10 19 * * *
      desiredReplicas: "0"
    type: cron
```

Error in keda operator
```
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:183
2025-06-24T11:06:28Z	ERROR	scale_handler	error resolving auth params	{"type": "ScaledObject", "namespace": "md-test-cicd", "name": "md-test-cicd", "triggerIndex": 1, "error": "error parsing cron metadata: no desiredReplicas specified"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
	/workspace/pkg/scaling/scalers_builder.go:96
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).performGetScalersCache
	/workspace/pkg/scaling/scale_handler.go:355
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:283
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:609
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:244
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:183
2025-06-24T11:06:28Z	ERROR	scale_handler	error getting state of scaledObject	{"scaledObject.Namespace": "md-test-cicd", "scaledObject.Name": "md-test-cicd", "error": "error getting scalers cache error parsing cron metadata: no desiredReplicas specified"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:246
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:183
```

```
❯ k get scaledobjects.keda.sh md-test-cicd -w
NAME           SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   READY   ACTIVE    FALLBACK   PAUSED    TRIGGERS   AUTHENTICATIONS   AGE
md-test-cicd   apps/v1.Deployment   md-test-cicd      1     5     False   Unknown   False      Unknown   cron                         43m
```

i tested with only desiredReplicas: "1" it works fine, only issue when adding desiredReplicas: "0"

Any way to solve this?
i want to do POD number to be 0 at off peak hours

Update :
- i tried Keda v2.11.2, it working correctly
