### ISSUE TITLE
Support 'startThreshold' for queue scalers like Kafka

### ISSUE THREAD

**Issue by kellybirr** [kedacore/keda#692]
When using queue based scalers like EventHubs, Kafka, RabbitMQ it would be great to have a low threshold (of 1 message) when the HPA has scaled to zero, but keep the normal, larger lagThreshold when scaling up above one instance.

I'm mostly talking about Kafka a the moment, as that's what I use.  I'd like to let my ScaledObject drop to zero for topics that don't see much traffic and start when a single message needs processing.  However, I only want to scale one instance per 100 messages behind the head of the topic.  This is especially useful when messages come infrequently but in batches when they do.

Something like this:
```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: my-kafka-processor-keda
spec:
  scaleTargetRef:
    deploymentName: my-kafka-processor
  pollingInterval: 30
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: awesome.servicebus.windows.net:9093
      consumerGroup: my-kafka-worker
      topic: my-topic
      lagThreshold: "100"
      startThreshold: "1"
```

I think for this to work, the scaler would have to lie to the HPA about the metric value when it was greater or equal to the startThreshold but less than the lagThreshold and claim that it was the lagThreshold, or reconfigure the HPA when it scaled to zero and then back when scaled above zero.
