### ISSUE TITLE
Multiple Prometheus Scalers in same scaled object return same metric values

### ISSUE THREAD

**Issue by ycabrer** [kedacore/keda#702]
Hi,

I am using two prometheus scalers on the same scaled object to scale a single deployment based on different queries. 

Each metric has a distinct name and query yet ***both*** query results are returned on each metric. This is causing strange metrics in the resulting HPA.

## Expected Behavior
Each distinct metric / query in a scaled object should only return the data it is requesting

## Actual Behavior
Each distinct metric / query is returning all metrics for the all queries.

## Steps to Reproduce the Problem

  1. Create a scaled object with two prometheus scalers. 

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: multiple-queue-consumer
  namespace: qa
  labels:
    deploymentName: multiple-queue-consumer
spec:
  scaleTargetRef:
    deploymentName: multiple-queue-consumer
  pollingInterval: 30
  cooldownPeriod:  150
  minReplicaCount: 1
  maxReplicaCount: 16
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local
      metricName:  mq_messages_per_consumer_queue_1
      threshold: '6'
      query: >
        rabbitmq_queue_messages{queue="queue-1"}
        / 
        rabbitmq_queue_consumers{queue="queue-1"}
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local
      metricName: mq_messages_per_consumer_queue_2
      threshold: '6'
      query: >
        rabbitmq_queue_messages{queue="queue-2"} 
        / 
        rabbitmq_queue_consumers{queue="queue-2""}

```
  2. Use the kubectl to verify external metric values
`get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/qa/mq_messages_per_consumer_queue_1?labelSelector=deploymentName%3Dmultiple-queue-consumer" | jq`

result for queue 1:

```
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/qa/mq_messages_per_consumer_queue_1"
  },
  "items": [
    {
      "metricName": "mq_messages_per_consumer_queue_1",
      "metricLabels": null,
      "timestamp": "2020-03-25T22:17:24Z",
      "value": "21"
    },
    {
      "metricName": "mq_messages_per_consumer_queue_1",
      "metricLabels": null,
      "timestamp": "2020-03-25T22:17:24Z",
      "value": "8"
    }
  ]
}

```
`get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/qa/mq_messages_per_consumer_queue_1?labelSelector=deploymentName%3Dmultiple-queue-consumer" | jq`
result for queue 2:

```
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/qa/mq_messages_per_consumer_queue_2"
  },
  "items": [
    {
      "metricName": "mq_messages_per_consumer_queue_2",
      "metricLabels": null,
      "timestamp": "2020-03-25T22:17:24Z",
      "value": "21"
    },
    {
      "metricName": "mq_messages_per_consumer_queue_2",
      "metricLabels": null,
      "timestamp": "2020-03-25T22:17:24Z",
      "value": "8"
    }
  ]
}
```

The first value of 21 is the metric for queue-1 and the second is the metric for queue-2 in each case

## HPA

```
Name:                                            keda-hpa-multiple-queue-consumer
Namespace:                                       qa
Labels:                                          app.kubernetes.io/managed-by=keda-operator
                                                 app.kubernetes.io/name=keda-hpa-multiple-queue-consumer
                                                 app.kubernetes.io/part-of=multiple-queue-consumer
                                                 app.kubernetes.io/version=1.3.0
Annotations:                                     <none>
CreationTimestamp:                               Wed, 25 Mar 2020 14:51:46 -0600
Reference:                                       Deployment/multiple-queue-consumer
Metrics:                                         ( current / target )
  "mq_messages_per_consumer_queue_1" (target average value):  14500m / 6
  "mq_messages_per_consumer_queue_2" (target average value):   14500m / 6
Min replicas:                                    1
Max replicas:                                    16
Deployment pods:                                 4 current / 4 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from external metric mq_messages_per_consumer_queue_1(&LabelSelector{MatchLabels:map[stringstring{deploymentName: multiple-queue-consumer,},MatchExpressions:,})
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:
  Type     Reason                        Age                  From                       Message
  ----     ------                        ----                 ----                       -------
  Normal   SuccessfulRescale             46m                  horizontal-pod-autoscaler  New size: 2; reason: All metrics below target
  Normal   SuccessfulRescale             30m                  horizontal-pod-autoscaler  New size: 3; reason: external metric mq_messages_per_consumer_queue_1(&LabelSelector{MatchLabels:map[stringstring{deploymentName: multiple-queue-consumer,},MatchExpressions:,}) above target
  Normal   SuccessfulRescale             13m (x7 over 109m)   horizontal-pod-autoscaler  New size: 3; reason: All metrics below target
  Normal   SuccessfulRescale             85s (x7 over 87m)    horizontal-pod-autoscaler  New size: 4; reason: external metric mq_messages_per_consumer_queue_1(&LabelSelector{MatchLabels:map[stringstring{deploymentName: multiple-queue-consumer,},MatchExpressions:,}) above target

```

## Scaled Object

```
Name:         multiple-queue-consumer
Namespace:    qa
Labels:       deploymentName=multiple-queue-consumer
Annotations:  
API Version:  keda.k8s.io/v1alpha1
Kind:         ScaledObject
Metadata:
  Creation Timestamp:  2020-03-25T15:39:31Z
  Finalizers:
    finalizer.keda.k8s.io
  Generation:        8
  Resource Version:  18647747
  Self Link:         /apis/keda.k8s.io/v1alpha1/namespaces/qa/scaledobjects/multiple-queue-consumer
  UID:               d1e01b0d-6eae-11ea-bf96-0ed83b31ac69
Spec:
  Cooldown Period:    150
  Max Replica Count:  16
  Min Replica Count:  1
  Polling Interval:   30
  Scale Target Ref:
    Deployment Name:  multiple-queue-consumer
  Triggers:
    Metadata:
      Metric Name:  mq_messages_per_consumer_queue_1
      Query:        rabbitmq_queue_messages{queue="queue-1"} /  rabbitmq_queue_consumers{queue="queue-1"}

      Server Address:  http://prometheus-server.monitoring.svc.cluster.local
      Threshold:       6
    Type:              prometheus
    Metadata:
      Metric Name:  mq_messages_per_consumer_queue_2
      Query:        rabbitmq_queue_messages{queue="queue-2"} /  rabbitmq_queue_consumers{queue="queue-2"}

      Server Address:  http://prometheus-server.monitoring.svc.cluster.local
      Threshold:       6
    Type:              prometheus
Status:
  External Metric Names:
    mq_messages_per_consumer_queue_1
    mq_messages_per_consumer_queue_2
  Last Active Time:  2020-03-26T02:54:32Z
Events:              <none>
```

## Specifications

  - **KEDA Version:** 1.3.0
  - **Platform & Version:** EKS 1.14
  - **Kubernetes Version:** 1.14
  - **Scaler(s):** Prometheus
