### ISSUE TITLE
KEDA scales any CustomResource that implements Scale subresource

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#703]
KEDA could scale `Deploment, StatefulSet` (as requested in #497)  or any `CustomResource` that implemtents `/scale` [subresource](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#scale-subresource) (eg. Argo Rollout as requested in #595). This functionality should work out of the box for users, ie. they won't have to perform any changes on their workloads. 

 To enable this a few changes would be needed:
- modify the RBAC to allow operator to access `scale` subresource
- implement polymorphic scale client to access `scale` subresource on any CR
- make the scale logic more general and not bound strictly to `Deployment`
- change the spec of `ScaledObject` and create a special `CR` for `Job` as it is suggested in #653 
Proposed change:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {scaled-object-name}
spec:
  scaleTargetRef:
    apiVersion:  {apiVersion-of-object-to-scale}   # Optional. Default: apps/v1
    kind:        {kind-of-object-to-scale}.        # Optional. Default: Deployment
    name:        {name-of-object-to-scale}
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 100 # Optional. Default: 100
  triggers:
  # {list of triggers to activate the deployment}
```

There is a change in `scaleTargetRef` section, if user specifies only `name`, KEDA would assume that the target is `Deployment`, if user wants to target any other workload, fields `apiVersion` and `kind` need to be specified appropriately.

I am working on POC to check if it is possible to achieve this. There shouldn't be any major changes in the scalers.

**Open questions**
1. Do we want this functionality?
2. How to handle `Secrets` or [Authentication](https://keda.sh/concepts/authentication/) in general? 
   - We could drop support of `Secret` linked in containers in favor of `TriggerAuthentication`
   - We could keep support of `Secret` linked in containers only for `Deployment` and `StatefulSet`, it will be needed to specify the `containerName` property somewhere in the spec. Where? Authentication support for `CustomResources` would be possible only through `TriggerAuthentication` as it is hard to detect the correct container in the CR.

@jeffhollan @tomkerkhove @ahmelsayed @anirudhgarg ^
