### ISSUE TITLE
Can Rabbitmq scalar be used with regexes ? 

### ISSUE THREAD

**Issue by sbhardwaj-mt** [kedacore/keda#743]
Currently the example shown in the documentation is :
```
triggers:
- type: rabbitmq
  metadata:
    host: RabbitMqHost
    queueLength: '20' # Optional. Queue length target for HPA. Default: 20 messages
    queueName: testqueue
```
while we want to group some of the queues with the parameter to trigger these deployment. 
for eg:
```
triggers:
- type: rabbitmq
  metadata:
    host: RabbitMqHost
    queueLength: '20' # Optional. Queue length target for HPA. Default: 20 messages
    queueName: platform.*rabbitmq
```
Is this possible ?
