### ISSUE TITLE
Prometheus: Scaling to zero not working in KEDA 1.4.0

### ISSUE THREAD

**Issue by hmoravec** [kedacore/keda#770]
Scaling to and from zero is not working with Prometheus scaler after KEDA upgrade from 1.3.0 to 1.4.0.

## Expected Behavior
KEDA should scale up deployment from zero when Prometheus metric increases from zero and scale down to zero when the metric decreases to zero.

## Actual Behavior
KEDA scales deployment from zero to one replica even when Prometheus metric is zero and never scales it down to zero. 

## Steps to Reproduce the Problem

  1. Deploy KEDA in GKE cluster using KEDA Helm chart in version 1.4.0.
  2. Deploy any deployment and corresponding ScaledObject with `minReplicaCount=0` and use Prometheus scaler with query that returns constant zero.
  3. Watch that KEDA never scales the deployment down to zero.
  4. Upgrade KEDA using the same Helm chart with KEDA downgraded to 1.3.0 using values: 
```
image:
  keda: docker.io/kedacore/keda:1.3.0
  metricsAdapter: docker.io/kedacore/keda-metrics-adapter:1.3.0
```
and watch that KEDA scales the deployment to zero and again up from zero when the metric becomes positive as expected.

## Specifications

  - **KEDA Version:** 1.4.0
  - **Platform & Version:** linux/amd64
  - **Kubernetes Version:** 1.15 (1.15.9-gke.24)
  - **Scaler(s):** Prometheus

**Comment by zroubalik** [comment]
Could you please rerun 1.4.0 with debug log leve on KEDA operator? https://github.com/kedacore/keda#setting-log-levels (or set it in the chart).

**Comment by zroubalik** [comment]
And paste here your `ScaledObject` please.

**Comment by hmoravec** [comment]
```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaling
  labels:
    deploymentName: worker
spec:
  scaleTargetRef:
    deploymentName: worker
  pollingInterval: 30
  cooldownPeriod:  60
  minReplicaCount: 0
  maxReplicaCount: 2
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local:9090
      metricName: queue_length
      threshold: '120'
      query: avg_over_time(worker_queue_length[5m])
```
I don't see anything suspicious in [keda-logs.txt](https://github.com/kedacore/keda/files/4520505/keda-logs.txt), except the last line
`I0423 05:18:21.328041       1 wrap.go:47] GET /openapi/v2: (3.086429ms) 404 [ 172.16.0.23:33094]`

KEDA scales replica to 1 from 0 even though the Prometheus metric is zero: 
`{"level":"info","ts":1587618899.730634,"logger":"scalehandler","msg":"Successfully updated deployment","ScaledObject.Namespace":"staging","ScaledObject.Name":"prometheus-scaling","ScaledObject.ScaleType":"deployment","Deployment.Namespace":"staging","Deployment.Name":"worker","Original Replicas Count":0,"New Replicas Count":1}`
