### ISSUE TITLE
Kafka scaler is not working as expected

### ISSUE THREAD

**Issue by abhirockzz** [kedacore/keda#776]
I have a Kafka Go consumer application which I expect to be auto-scaled by KEDA Kafka scaler

## Expected Behavior

Consumer Deployment should be auto-scaled as per ScaledObject

## Actual Behavior

1. KEDA scales down the deployment to 0 (as expected)
2. When the producer application is started and partition lag is detected, the deployment is scaled to 1 (0 to 1 is working fine)
3. The application is not scaled further. 

I do realize that KEDA just does 0 to 1 (and vice-versa) but the HPA should act based on KEDA metrics. The logs are clear:

```
{"level":"debug","ts":1587711971.8334641,"logger":"kafka_scaler","msg":"Group $Default has a lag of 92 for topic keda-test and partition 4\n"}
```

> While debugging this, I also noticed that `GetMetricSpecForScaling` function in the Kafka Scaler is only invoked once (when the KEDA controller starts) - not sure if this is expected?

Here is the `ScaledObject` which has a `lagThreshold` of `10` - I should have ~ 9 replicas by now (give the partition lag is > 90)

```
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: default
  labels:
    deploymentName: kafka-consumer
spec:
  scaleTargetRef:
    deploymentName: kafka-consumer
  pollingInterval: 15
  cooldownPeriod: 100
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: <NAMESPACE>.servicebus.windows.net:9093
        consumerGroup: $Default
        topic: keda-test
        lagThreshold: "10"
      authenticationRef:
        name: kafka-triggerauth
```

## Steps to Reproduce the Problem

  1. deploy KEDA - activate `debug` logs
  2. create Deployment and scaled object
  3. keep track of KEDA operator logs

## Specifications

  - **KEDA Version:** 1.3.0
  - **Kubernetes Version:** 1.15
  - **Scaler(s):** Kafka
