### ISSUE TITLE
GSSAPI sasl mechanism for Kafka scaler

### ISSUE THREAD

**Issue by alexakr** [kedacore/keda#857]
Adding "GSSAPI" SASL mechanism for Kafka scaler.

### Use-Case

I would like to be able to work with Kafka that configured with Kerberos principals using keytab, jass.conf and krb5.conf

### Specification

- kind: secret
```
data:
  saslMechanism: GSSAPI  # or PLAIN for user/password, relevant only when authMode is "sasl_plaintext" or "sasl_ssl"
  keytab: <your keytab>
  jaas: <your jaas.conf>
  krb5: <your krb.conf>
```
- kind: TriggerAuthentication
```
spec:
  secretTargetRef:
  - parameter: saslMechanism
    name: keda-kafka-secrets
    key: saslMechanism
  - parameter: keytab
    name: keda-kafka-secrets
    key: keytab
  - parameter: jaas
    name: keda-kafka-secrets
    key: jaas
  - parameter: krb5
    name: keda-kafka-secrets
    key: krb5
```
