### ISSUE TITLE
Allow for usage of TriggerAuthentication from other namespaces

### ISSUE THREAD

**Issue by erick-thompson** [kedacore/keda#864]
Right now, the TriggerAuthentication must be in the same namespace as the ScaledObject. I would like to be able to reference a TriggerAuthentication from any ScaledObject, regardless of namespace. 

### Use-Case

Managing the authentication for a large number of functions across a large number of namespaces is difficult. What I would like to do is have a low permission identity that can read any of our supported scale sources (e.g., Azure Event Hub, Service Bus, etc). Then, each function can refer to that common TriggerAuthentication. This makes it easier for developers to spin up new functions and makes it easier to manage permissions on the trigger sources.

### Specification

In ScaledObject, allow references such as:
  
```
triggers:
  - type: {scaler-type}
    metadata:
      param1: {some-value}
    authenticationRef:
      name: {trigger-authencation-namespace}/{trigger-authencation-name} 

```

**Comment by tomkerkhove** [comment]
That makes sense, but I'd rather suggest this format:
```yaml
triggers:
  - type: {scaler-type}
    metadata:
      param1: {some-value}
    authenticationRef:
      name: {trigger-authencation-name}
      namespace: {trigger-authencation-namespace}
```
