### ISSUE TITLE
Error "Exactly one scaled object should match label deploymentName="

### ISSUE THREAD

**Issue by alexandery** [kedacore/keda#897]
## Expected Behavior
Expect to be able to define multiple ScaledObjects targeting same deployment.

## Actual Behavior
When creating more than one ScaledObject for same deployment, Metrics ApiServer throws the following error every 15 seconds  and the deployment doesn't scale past 1. 

```E0624 19:28:24.701998       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"Exactly one scaled object should match label deploymentName=keda-tester-group-1"}```

I'm using Kafka scaler and need to scale a single deployment based on multiple Kafka topics. I've tried changing ScaledObject definitions  - renaming metadata.labels value to a unique value per ScaledObject, removing metadata.labels, renaming metadata.labels to metadata.label ( I've found #158 and was trying to follow that thread in hopes to resolve my issue). None of this helped.

## Definitions
Deployment.yaml
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-tester-group-1
  namespace: keda-group-1
  labels:
    app: keda-tester-group-1
spec:
  replicas: 0
  selector:
    matchLabels:
      app: keda-tester-group-1
  template:
    metadata:
      labels:
        app: keda-tester-group-1
    spec:
      containers:
        - name: kafka-keda-tester
          image: mycontainerregistry.azurecr.io/poc/kafka-keda-tester:latest
          imagePullPolicy: Always
          env:
            - name: verb
              value: "consume"
            - name: first-topic
              value: "1"
            - name: last-topic
              value: "50"
```

ScaledObject1.yaml
``` yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: keda-scaleobject-1-group-1
  namespace: keda-group-1
  labels:
    deploymentName: keda-tester-group-1
spec:
  scaleTargetRef:
    deploymentName: keda-tester-group-1
  pollingInterval: 5
  minReplicaCount: 0   #Optional Default 0
  maxReplicaCount: 5  #Optional Default 100
  cooldownPeriod: 10
  triggers:
  - type: kafka
    metadata:
      # Required
      bootstrapServers: kafka:9092
      consumerGroup: keda-tester
      topic: Topic-1-KEDA
      lagThreshold: "5"
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
```

ScaledObject2.yaml
``` yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: keda-scaleobject-2-group-1
  namespace: keda-group-1
  labels:
    deploymentName: keda-tester-group-1
spec:
  scaleTargetRef:
    deploymentName: keda-tester-group-1
  pollingInterval: 5
  minReplicaCount: 0   #Optional Default 0
  maxReplicaCount: 5  #Optional Default 100
  cooldownPeriod: 10
  triggers:
  - type: kafka
    metadata:
      # Required
      bootstrapServers: kafka:9092
      consumerGroup: keda-tester
      topic: Topic-2-KEDA
      lagThreshold: "5"
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
```

## Specifications

  - **KEDA Version:** Latest as of yesterday installed via Helm
  - **Platform & Version:** Azure k8s
  - **Kubernetes Version:** 1.16.1
  - **Scaler(s):** Kafka
