### ISSUE TITLE
Azure Function Configuration convention is not supported

### ISSUE THREAD

**Issue by jsacapdev** [kedacore/keda#909]
## Expected Behavior

An Azure Function that pull its queue from configuration `%StarterQueue%`:

```
    public class StartQueueTrigger
    {
        private readonly TelemetryClient _client;

        public StartQueueTrigger(TelemetryConfiguration telemetryConfiguration)
        {
            _client = new TelemetryClient(telemetryConfiguration);
        }

        [FunctionName(Constants.StartQueueTrigger)]
        public void Run(
            [QueueTrigger("%StarterQueue%", Connection = "StorageConnectionString")]string myQueueItem, 
            ILogger log)
        {
            _client.LogTrace("Workflow Triggered");
        }
    }
```

Scales when deployed to k8s.

## Actual Behavior

The pod is deployed, terminates and never comes back. The messages (in this case on an azure queue) just sit there as the Azure Function will never get created.

```
kubectl logs --namespace=keda --selector=app=keda-operator -c keda-operator

{"level":"info","ts":1593759408.187155,"logger":"controller_scaledobject","msg":"Reconciling ScaledObject","Request.Namespace":"default","Request.Name":"functionapi"}
{"level":"info","ts":1593759408.1872313,"logger":"controller_scaledobject","msg":"Adding Finalizer for the ScaledObject","Request.Namespace":"default","Request.Name":"functionapi"}
{"level":"info","ts":1593759408.1969888,"logger":"controller_scaledobject","msg":"Detected ScaleType = Deployment","Request.Namespace":"default","Request.Name":"functionapi"}
{"level":"info","ts":1593759408.1970253,"logger":"controller_scaledobject","msg":"Creating a new HPA","Request.Namespace":"default","Request.Name":"functionapi","HPA.Namespace":"default","HPA.Name":"keda-hpa-functionapi"}
{"level":"info","ts":1593759408.418116,"logger":"controller_scaledobject","msg":"Reconciling ScaledObject","Request.Namespace":"default","Request.Name":"functionapi"}
{"level":"info","ts":1593759408.4217122,"logger":"controller_scaledobject","msg":"Detected ScaleType = Deployment","Request.Namespace":"default","Request.Name":"functionapi"}
{"level":"error","ts":1593759408.5193079,"logger":"azure_queue_scaler","msg":"error)","error":"-> github.com/Azure/azure-storage-queue-go/azqueue.newStorageError, /go/pkg/mod/github.com/!azure/azure-storage-queue-go@v0.0.0-20190416192124-a17745f1cdbf/azqueue/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=InvalidResourceName) =====\nDescription=The specifed resource name contains invalid characters.\nRequestId:01a1f36a-d003-00da-1907-516547000000\nTime:2020-07-03T06:56:48.5192146Z, Details: \n   Code: InvalidResourceName\n   PUT https://patternscndevwe.queue.core.windows.net/%25StarterQueue%25?timeout=61\n   Authorization: REDACTED\n   User-Agent: [Azure-Storage/0.1 (go1.13.3; linux)]\n   X-Ms-Client-Request-Id: [c262ea6d-5e4d-47a5-6e8e-aa5d2fc2b85e]\n   X-Ms-Date: [Fri, 03 Jul 2020 06:56:48 GMT]\n   X-Ms-Version: [2018-03-28]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 400 The specifed resource name contains invalid characters.\n   Content-Length: [243]\n   Content-Type: [application/xml]\n   Date: [Fri, 03 Jul 2020 06:56:48 GMT]\n   Server: [Windows-Azure-Queue/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [InvalidResourceName]\n   X-Ms-Request-Id: [01a1f36a-d003-00da-1907-516547000000]\n   X-Ms-Version: [2018-03-28]\n\n\n","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/kedacore/keda/pkg/scalers.(*azureQueueScaler).IsActive\n\tkeda/pkg/scalers/azure_queue_scaler.go:123\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).handleScaleDeployment\n\tkeda/pkg/handler/scale_loop.go:119\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).handleScale\n\tkeda/pkg/handler/scale_loop.go:45\ngithub.com/kedacore/keda/pkg/handler.(*ScaleHandler).HandleScaleLoop\n\tkeda/pkg/handler/scale_loop.go:14"}
{"level":"info","ts":1593759408.5273328,"logger":"scalehandler","msg":"Successfully scaled deployment to 0 replicas","ScaledObject.Namespace":"default","ScaledObject.Name":"functionapi","ScaledObject.ScaleType":"deployment","Deployment.Namespace":"default","Deployment.Name":"functionapi"}
```

It looks like this convention of pulling from configuration in the function is not supported. So the `yaml` file looks like this:

```
data:
  AzureWebJobsStorage: ???
  FUNCTIONS_WORKER_RUNTIME: ???
  StarterQueue: ???
  APPINSIGHTS_INSTRUMENTATIONKEY: ???
  StorageConnectionString: ???
apiVersion: v1
kind: Secret
metadata:
  name: functionapi
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: functionapi
  namespace: default
  labels:
    app: functionapi
spec:
  selector:
    matchLabels:
      app: functionapi
  template:
    metadata:
      labels:
        app: functionapi
    spec:
      containers:
      - name: functionapi
        image: patternscndevwe.azurecr.io/kedapoc/functionapi
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: StartQueueTrigger
        envFrom:
        - secretRef:
            name: functionapi
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: functionapi
  namespace: default
  labels:
    deploymentName: functionapi
spec:
  scaleTargetRef:
    deploymentName: functionapi
  triggers:
  - type: azure-queue
    metadata:
      type: queueTrigger
      connection: StorageConnectionString
      queueName: '%StarterQueue%'
      name: myQueueItem
---
```

If the queue name is hard coded in the Azure Function, it works as expected.

## Steps to Reproduce the Problem

  1. Create an Azure Function (mine was in .NET C#)
  2. Create a queue trigger
  3. Create a configuration setting in `local.settings.json` like `"StarterQueue": "kedaq"`
  4. Reference it in a Azure Function like:
  ```
    [FunctionName(Constants.StartQueueTrigger)]
    public void Run(
        [QueueTrigger("%StarterQueue%", Connection = "StorageConnectionString")]string myQueueItem, 
        ILogger log)
    {
        _client.LogTrace("Workflow Triggered");
    }
  ```
  5. Deploy it to K8s
  6. Check the operator logs `kubectl logs --namespace=keda --selector=app=keda-operator -c keda-operator`

## Specifications

  - **KEDA Version:** how can i check this?
  - **Platform & Version:** Azure AKS
  - **Kubernetes Version:** v1.16.9
  - **Scaler(s):** azure-queue
