### ISSUE TITLE
Cron Scaler throws error - unknown timezone

### ISSUE THREAD

**Issue by dan-leanix** [kedacore/keda#932]
## Expected Behavior

That this configuration works as described in the docs. But every time I am receiving an error in the log, that the timezone is unknown.

```YAML
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: test
spec:
  scaleTargetRef:
    deploymentName: test
  minReplicaCount: 1
  maxReplicaCount: 2
  triggers:
    - type: cron
      metadata:
        timezone: Europe/Berlin
        start: 00 15 * * *
        end: 30 15 * * *
        desiredReplicas: "2"

```

## Actual Behavior

```Shell
E0713 11:41:25.133260       1 provider.go:94] keda_metrics_adapter/provider "msg"="error getting metric for scaler" "error"="Unable to load timezone. Error: unknown time zone Europe/Berlin"  "ScaledObject.Name"="test" "ScaledObject.Namespace"="test" "Scaler"={}
```

## Steps to Reproduce the Problem

  1. Deploy KEDA 1.5.0
  2. Create `ScaledObject` from type `cron` with the configuration above
  3. Get logs from `keda-operator-metrics-apiserver` to check for any errors

## Specifications

  - **KEDA Version:** *1.5.0*
  - **Platform & Version:** *Azure Kubernetes Service*
  - **Kubernetes Version:** *1.16.10*
  - **Scaler(s):** *cron*

## Working configuration with KEDA 1.5.0 and Cron Scaler

```YAML
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: test
spec:
  scaleTargetRef:
    deploymentName: test
  minReplicaCount: 1
  maxReplicaCount: 2
  triggers:
    - type: cron
      metadata:
        timezone: Local
        start: 00 15 * * *
        end: 30 15 * * *
        desiredReplicas: "2"
```
