### ISSUE TITLE
Redis trigger not working- HOST:PORT not provided error

### ISSUE THREAD

**Issue by shaktsin** [kedacore/keda#934]
Redis trigger not working with remote redis sever. The following exception occurs - 

```
{"level":"error","ts":1594666097.0484922,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"scaledobject-controller","request":"default/redis-scaledobject2","error":"error getting scaler for trigger #0: error parsing redis metadata: no address given or host given. Address should be in the format of host:port or you should provide both host and port","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/zroubali/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/zroubali/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/zroubali/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/Users/zroubali/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/zroubali/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/zroubali/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/zroubali/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88"}
```

Scaled Object Config
```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject2
  labels:
    deploymentName: keda-redis-python
spec:
  scaleTargetRef:
    deploymentName: keda-redis-python
  triggers:
  - type: redis
    metadata:
      address: HOST:6380 # HOST is in azure 
      password: PASS
      enableTLS: "true"
      listName: queue 
      listLength: "5"
```

## Expected Behavior
I expect it connect redis as address space is give rightly 

## Actual Behavior

Set a metadata address for a redis scaler

## Specifications

  - 1.5.0
  - **Platform & Version:** Minikube 
  - **Kubernetes Version:** - v1.18.3
  - **Scaler(s):** Redis
