### ISSUE TITLE
[v2] queueLength for Azure Storage Queue scaler is confusing

### ISSUE THREAD

**Issue by TsuyoshiUshio** [kedacore/keda#950]
Rather than a use case, I'd like to discuss the proper naming for the Azure Storage Queue parameter `queueLength`. 
According to the code, It eventually added as `metric.External.Target.AverageValue`. I don't know the HPA logic, however, at least for the job, that means, "How many queues that a job can process?"  As a second language learner of English, I'm not sure what is the best naming, however, I feel that it is confusing. If you guys are ok, I'm fine. 

```yaml
triggers:
- type: azure-queue
  metadata:
    queueName: functionsqueue
    queueLength: '5' # Optional. Queue length target for HPA. Default: 5 messages
    connection: STORAGE_CONNECTIONSTRING_ENV_NAME
```
### Specification

https://keda.sh/docs/1.4/scalers/azure-storage-queue/
