### ISSUE TITLE
[v2] Remove minReplicaCount and cooldownPeriod from ScaledJob

### ISSUE THREAD

**Issue by TsuyoshiUshio** [kedacore/keda#955]
### Use-Case

For the ScaledJob on v2, `minReplicaCount` and `coolddownPeriod` is not make sense for ScaledJob. 
I want to remove before release v2 beta. Do you agree with it?

### Specification

```
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-consumer
data:
  RabbitMqHost: YW1xcDovL3VzZXI6UEFTU1dPUkRAcmFiYml0bXEuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy
  LocalHost: YW1xcDovL3VzZXI6UEFTU1dPUkRAMTI3LjAuMC4xOjU2NzI=
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: rabbitmq-consumer
  namespace: default
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: rabbitmq-client
          image: tsuyoshiushio/rabbitmq-client:dev3
          imagePullPolicy: Always
          command: ["receive",  "amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672", "job"]
          envFrom:
            - secretRef:
                name: rabbitmq-consumer
        restartPolicy: Never
    backoffLimit: 4  
  pollingInterval: 10   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds   **<- removed from ScaledJob**
  minReplicaCount: 0    # Optional.  **<- removed from ScaledJob**
  maxReplicaCount: 30  # Optional. Default: 100
```
